### ISSUE TITLE
Add Redirect helper method

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#10]
Add redirect helper method to Slim class. This method should set Location: header and the status code (which defaults to 302). An alternate status may be set, but it must be a valid status code to be set.

**Comment by djl** [comment]
I've got a working version of this running locally, but I've got a quick question about setting the status code.

If the status code has to be valid, should this be implemented at the lowest level (i.e. Response->status()) so it's application-wide or should it just be for this helper method?

**Comment by codeguy** [comment]
Good question. I would say validate this in Response::status since this error would then be caught app-wide. Open to other suggestions though. This is on my to-do list... don't think an Issue has been created for it just yet.
