### ISSUE TITLE
Sessions (Feedback Requested)

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#101]
I am working on secure sessions support in version 1.3. I have written and will soon commit a new Cookie session handler which persists session data with encrypted Cookies (using `Slim::setEncryptedCookie` and `Slim::getEncryptedCookie`). This is more secure because it persists the session id in a cookie, regenerates the session ID per request, and cryptographically signs and encrypts the session data cookie to prevent tampering.

My question... is there any reason this should not be the default handler for Slim app sessions? Or should sessions use the default session store defined in PHP.ini unless the new session Cookie store is requested?

**Comment by MatthewCallis** [comment]
The more secure the default settings the better, to a point. I don't think this crosses the point of being to cumbersome or too secure for an average use.

**Comment by codeguy** [comment]
@MatthewCallis That was my thinking as well. As far as the end user is concerned, all of this is 100% transparent. The user would continue using `$_SESSION` as usual.
