### ISSUE TITLE
Trailing slash at optional route parameters raises 404 error

### ISSUE THREAD

**Issue by velosipedist** [slimphp/Slim#1012]
Using one optional param, like in documentation

``` php
$app->get('/:year(/:month)', function($year, $month) {
  // handle route
});
```

There is 2 cases possible with `month` param:
`/2015/01` — works correctly
`/2015/01/` — throws 404

Apache has [mod_dir module](http://httpd.apache.org/docs/2.2/mod/mod_dir.html) which can automatically add trailing slashes at end of path. It is useful for more SEO-friendly uniform urls.

But now the only workaround for this bug is to add extra parentheses around each possible slash:

``` php
$app->get('/:year(/:month(/))', function($year, $month) {
  // handle route
});
```

But it is pretty ridiculous.

**Comment by tuupola** [comment]
Matter of taste.  `/2015/01` and `/2015/01/` are not the same thing.

**Comment by ghost** [comment]
In almost routing systems it should be same.

**Comment by codeguy** [comment]
They are not the same, by design. This is expected behavior.

**Comment by JoeBengalen** [comment]
If you want to support both urls (with and without trailing slash) you could add or remove the slash in a middleware layer to make sure it matches the route you expect.
