### ISSUE TITLE
Using 'Class:method' as a route middleware

### ISSUE THREAD

**Issue by plashenkov** [slimphp/Slim#1014]
Hello!

If I understand correctly, currently Slim does not allow to use 'Class:method' string as a route or group middleware. It would be very nice to have this possibility.

And, optionally, maybe some method called "filter" or "before" would be handy—in addition to "group" mehod—where route pattern will not be necessary.

This will allow to transfer all logic, including filtering methods, to Controller classes, leaving routes.php file simple and slim.

Thank you.

**Comment by oanhnn** [comment]
I think Slim framework really support this feature from [version 2.4.0](https://github.com/codeguy/Slim/releases/tag/2.4.0).
I used this for my [slim-skeleton](https://github.com/oanhnn/slim-skeleton/blob/master/config/bootstrap.php)
Was I understand your question correctly? @plashenkov

**Comment by plashenkov** [comment]
I mean:

``` php
$app->get('/admin', 'Auth:check', 'AdminController:index');
```

or

``` php
$app->group('/admin', 'Auth:check', function() use ($app)
{
    $app->get('/', 'AdminController:index');
    $app->get('/administrators', 'AdminController:listAdmininstrators');
    // ...
}
```

I tried this using 2.5.0 as well as new 3.0 and it does not work.

**Comment by oanhnn** [comment]
You can use:

``` php
$app->get('/admin', 'Auth::check', 'AdminController:index');
```

or

``` php
$app->group('/admin', 'Auth::check', function() use ($app)
{
    $app->get('/', 'AdminController:index');
    $app->get('/administrators', 'AdminController:listAdmininstrators');
    // ...
}
```

with **static function** `Auth::check()` .

**Comment by plashenkov** [comment]
That's possible, I know.

But if we can use "Class:method" as a callable, it is naturally to have an opportunity of using the same syntax for middleware too. If I can pass "Controller:method" as a route callable, and Slim instantiates the class if the route was triggered, it is very, very expected to use the same scheme for a middleware.

For example, in constructor of a controller class I usually do the following:

``` php
class Controller
{
    /**
     * @var Slim\Slim
     */
    protected $app;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->app = Slim\Slim::getInstance();
    }
}
```

And then I use `$this->app` to access Slim instance inside a class and its successors. In case of using static methods, I need manually call `Slim\Slim::getInstance()` in each static method. That is not nice. Besides this, there (in constructor) may be another, more complex logic. This is just an example, but the main argument is to use the same syntax for these "callable" parameters (route callables and middlewares).

**Comment by oanhnn** [comment]
"Class:method" is not callable but Slim Framework make it to callable by `Route::setCallable()` method 
https://github.com/codeguy/Slim/blob/master/Slim/Route.php#L162

You can modified `Route::setMiddleware()` method and implement this feature.
And create Pull request :smile:

**Comment by plashenkov** [comment]
> "Class:method" is not callable but Slim Framework make it to callable

Yeah, technically and strictly speaking it is not, I meant “callable” in a figurative sense.

For my app I’ve extended Slim\Slim class and made using of “Class:method” available for route middlewares as well as for notFound() and error() functions. This issue aims to make this functionality available "naturally", out-of-the-box. My humble opinion is that this is necessary. I just fear my implementation is not beautiful/right enough and Slim developers can implement this in their, more qualified and perfect way.

``` php
class App extends \Slim\Slim
{
    /**
     * Check if variable is a controller method and convert it to a callable
     *
     * @param mixed $callable
     */
    protected function checkControllerMethod(&$callable)
    {
        if (is_string($callable) && preg_match('!^([^\:]+)\:([[:alnum:]]+)$!', $callable, $matches)) {
            $class = $matches[1];
            $method = $matches[2];
            $callable = function() use ($class, $method) {
                static $obj = null;
                if ($obj === null) {
                    $obj = new $class;
                }
                return call_user_func([$obj, $method]);
            };
        }
    }

    /**
     * Route Groups
     */
    public function group()
    {
        $args = func_get_args();

        $pattern = array_shift($args);
        $callable = array_pop($args);

        foreach ($args as $key => $value) {
            $this->checkControllerMethod($args[$key]);
        }

        array_unshift($args, $pattern);
        array_push($args, $callable);

        call_user_func_array('parent::group', $args);
    }

    public function filter()
    {
        $args = func_get_args();
        array_unshift($args, '');
        call_user_func_array([$this, 'group'], $args);
    }

    /**
     * "Not found" handler
     *
     * @see   \Slim\Slim::notFound()
     * @param mixed $callable Anything that returns true for is_callable()
     */
    public function notFound($callable = null)
    {
        $this->checkControllerMethod($callable);
        parent::notFound($callable);
    }

    /**
     * Error handler
     *
     * @see   \Slim\Slim::error()
     * @param mixed $argument Callable|\Exception
     */
    public function error($argument = null)
    {
        $this->checkControllerMethod($argument);
        parent::error($argument);
    }
}
```

**Comment by oanhnn** [comment]
Like :+1:
