### ISSUE TITLE
Closures in unit test make it PHP >= 5.3 only

### ISSUE THREAD

**Issue by sprt** [slimphp/Slim#102]
See [/tests/RouterTest.php](https://github.com/codeguy/Slim/blob/master/tests/RouterTest.php) and maybe others.

**Comment by codeguy** [comment]
Converting unit tests to be compatible with PHP < 5.3 will simply take too much time and additional code at this point. I'm going to leave it as is. You'll need a PHP >= 5.3 interpreter to run the tests.
