### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Tjoosten** [slimphp/Slim#1022]
It could be handy if you tell in the documentation. How u break up the routing into controller.

P.S could you tell me how i do that. I need to that and i'm stuck.

**Comment by thejw23** [comment]
You can do this like that: http://akrabat.com/routing-to-a-controller-with-slim-framework/

**Comment by geggleto** [comment]
https://github.com/geggleto/slimtutorials been trying to put up some information of different patterns.

**Comment by codeguy** [comment]
Please move this thread to the Documentation repo.
