### ISSUE TITLE
URL helper problem for routes with optional parameters

### ISSUE THREAD

**Issue by phaseinducer** [slimphp/Slim#103]
I have this route :

```
Slim::get('/(:param)', function($param = 'default') {
  // Code
})->name('my_route');
```

If I want to generate a URL to this route with :
    Slim::urlFor('my_route', array('param' => 'somevalue'));
Then the generated URL looks like this :
    http://mydomain/(somevalue)?

**Comment by codeguy** [comment]
Good catch. Will bump this to the top of my to-do list.

**Comment by codeguy** [comment]
I've fixed this locally. I need to write unit tests for the fix this afternoon and I'll have it pushed up this evening.

**Comment by codeguy** [comment]
Just pushed a hotfix (tagged 1.2.4) to both branches.

**Comment by phaseinducer** [comment]
Great! I'll test this tomorrow.
Thank you for being so responsive ;)
