### ISSUE TITLE
[develop] Why do Route & App middlewares have different signatures?

### ISSUE THREAD

**Issue by alanpich** [slimphp/Slim#1030]
It seems a bit strange that route & application middleware have completely different signatures, and as such are not interchangeable. Is there a particular reason for this, as I think it will restrict the use of 3rd party middleware libraries?

**Comment by lalop** [comment]
Hi,
I made a pr for that https://github.com/slimphp/Slim/pull/1009

**Comment by silentworks** [comment]
This is being addressed by @lalop so will close this out.
