### ISSUE TITLE
Mini Encryption Audit

### ISSUE THREAD

**Issue by defuse** [slimphp/Slim#1037]
Looking at https://github.com/slimphp/Slim/blob/develop/Slim/Crypt.php...
1. The IV is not included in the HMAC. It needs to be, otherwise you can modify the IV to modify the plaintext.
2. It uses `MCRYPT_RIJNDAEL_256`. This is _not_ AES, it's the 256-bit _block_ version of rijndael. You want `MCRYPT_RIJNDAEL_128`.
3. The same key is used for encryption and authentication. This is a bad practice. You need to use something like HKDF to make two keys.
4. It's not `mbstring.func_overload`-safe (the `strlen()` in `validateKeyLength()`).
5. It uses zero-byte padding. If the plaintext ends in zero bytes they will get stripped, violating integrity. Use PKCS#5 padding. Actually, it's much worse than this, since it's replacing _all_ zero bytes, not just the ones at the end.
6. Exceptions leak the key: https://gist.github.com/defuse/c197a18a7b5a0667c92d

I only spent 10 minutes looking, so there are almost certainly more problems. Moral of the story: _Please, please, please, please_ don't write yet another broken PHP encryption library. I've already [written one](https://github.com/defuse/php-encryption/blob/master/Crypto.php), and have taken the time to get everything right. Please, just use that one, or make sure you _carefully_ go through it and address all of the things that can go wrong.

**Comment by padraic** [comment]
@defuse Could this not have been reported privately?

**Comment by defuse** [comment]
@padraic I saw no need. This is the development branch and my understanding is that it's not what everyone is using. The crypto everyone is using is actually worse, see #1035.

**Comment by silentworks** [comment]
I somewhat feel this would have been better disclosed privately first. Also parading it on Twitter doesn't help either, we know you probably know more about security than most of us, but don't think trying to make others work look bad is the way to prove that.

Anyway back to the original point, please share privately first next time, if you realise no-one is taking note of it after 30 days then by all means disclose it publicly.

**Comment by sarciszewski** [comment]
Please post a security@ contact address and PGP key on the project website then.

**Comment by padraic** [comment]
It just took me 10 seconds to locate an email for Josh. Not all communications require a security@ email address or a PGP key. A normal unencrypted email still has some reasonable degree of privacy that is better than a public github issue. A DM over Twitter can often solicit an email contact.

The proverbial cat is running far from the bag, so I'll return the topic to the issue reported.

**Comment by defuse** [comment]
@silentworks I tweeted [this](https://twitter.com/DefuseSec/status/572150470518562816) to raise awareness about this common problem. Slim is not the first framework I've seen trying to implement this exact same thing, and they are invariably insecure in the exact same ways. I don't "try to make others work look bad." I care only about the technical facts and what I can do to make things more secure, not about the people behind it. If I see something wrong, I will point out the technical details; it's never intended as an attack against the author.

**Comment by codeguy** [comment]
Just migrated the develop branch over to Zend\Crypt.

https://github.com/slimphp/Slim/commit/c5b6c76a2bba90dfab300280ed9258e2263edb52
