### ISSUE TITLE
Session Cookies are so big that Apache throw a 400 error

### ISSUE THREAD

**Issue by Calvein** [slimphp/Slim#104]
After a while on my website, Apache throw me a 400 error because a header was too big, it was the session cookie one. The only way to resolve this problem is to remove the cookie.
Here is the error :

Bad Request

Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.

**Comment by codeguy** [comment]
Hmm... for now set the Session handler setting to `null` to revert to PHP default session handling. What data were you putting into the Session? Cookies have an inherent limitation of 4k.

I will duplicate later tonight and try to figure out a solution.

**Comment by Calvein** [comment]
I have set the session handler to null, the weirdest part is that I havn't put any datas into the session

**Comment by codeguy** [comment]
That is odd. If possible, send me an example app that is as simple as possible while still duplicating the issue.

**Comment by Calvein** [comment]
The Development Release  has this issue.

**Comment by codeguy** [comment]
@Calvein Can you hop on IRC chat? ##slim

**Comment by codeguy** [comment]
Didn't mean to close this. I can't duplicate this. On my computer, for each request, the previous session cookie is deleted and a new one (with a new ID) is set, as expected. I don't see anything going on that would cause the cookie size to gradually increase. I'll need more information before I can do anything to fix this. Be sure you've pulled the very latest commits just in case.

Can you `print_r($_SESSION)` in one of your routes to inspect the session data? Be sure you do not `die` in your route callback because session data must be written out after the route and app finishes running. Do you see anything odd happening in Firefox/Firebug or Chrome/WebInspector regarding cookies?

**Comment by Calvein** [comment]
I was talking about the Development Release on the website (http://www.slimframework.com/) not the sources on github, I'll send you the trace of my `$_SESSION` tomorrow, I actually have to go right now.

Anyway, your framework looks very promising so here is a unicorn to make you happy :

<code>
                             \
                              \
                               \
                                \
                                 >\/7
                             _.-(6'  \
                            (=___._/`\
                                 )  \ |
                                /   / |
                               /    > /
                              j    < _\
                          _.-' :``.
                          \ r=._\        `.
                         <`\_  \         .`-.
                          \ r-7`-. ._  ' .  `\
                           \`,      `-.`7  7)   )
                            \/         |  \'  / `-._
                                       ||    .'
                                        \  (
                                         >\  >
                                     ,.-' >.'
                                    <.'_.''
                                      <'
</code>

**Comment by codeguy** [comment]
haha. Awesome. The download links at http://www.slimframework.com/install link directly to the latest commits from the `master` and `develop` branches on GitHub. Let me know if you still have this issue after pulling the latest code.

**Comment by Calvein** [comment]
I just get the very last version and the bug is still there.
Here is an image of the first request and after 50 refreshes :

http://i.imgur.com/Z9g1p.png

**Comment by codeguy** [comment]
Thanks for the image. Can you send me a screenshot of what you seen when you `print_r($_SESSION)` within one of your routes? I need to see what data isn't being remo ved on each request. This may be something specific to Ubuntu's PHP install as I'm not seeing this happen here. Thanks for your help.

**Comment by Calvein** [comment]
Here what I get :

<code>
Array
(
    [flash] => Array
        (
        )

)
</code>

One of my co-worker had this bug to this morning. Since he update it looks good (he's on Windows Vista with PHP 5.3.5).

By the way, here is my Slim configuration :

<code>
Slim::init(array(
    'templates_dir'   => '../templates',
    'log.enable'      => true,
    'log.path'        => '../logs',
    'session.handler' => null
));
</code>

**Comment by codeguy** [comment]
I've just pushed a new commit to the `develop` branch that should resolve this. Pull the changes and let me know if this works as expected for you. Thanks!

**Comment by codeguy** [comment]
Well I can no longer duplicate this issue, so I'm considering this resolved. If not, leave a comment with further debugging information.

**Comment by codeguy** [comment]
It appears I closed this prematurely. I've just pushed another hotfix to both branches that corrects an error in `CookieJar::deleteCookie`; before the latest hotfix, this method incorrectly set the Cookie expiration time which prevented the older session cookie from being invalidated on the client. This is now fixed for sure.
