### ISSUE TITLE
[develop] Make route matching faster using combined regular expressions

### ISSUE THREAD

**Issue by zoontek** [slimphp/Slim#1041]
Hello

Slim become actually a quite fast and futur proof framework. So, why not implement [FastRoute](http://nikic.github.io/2014/02/18/Fast-request-routing-using-regular-expressions.html) to reduce the routing preg_match operations?

Here's a blog post explaining why it's fast: http://nikic.github.io/2014/02/18/Fast-request-routing-using-regular-expressions.html

**Comment by nochso** [comment]
For some inspiration have a look at [thephpleague/route](https://github.com/thephpleague/route) which is using nikic/fast-route. I like the idea of different [strategies](http://route.thephpleague.com/request-response-strategy/) for the callable parts depending on use case or personal choice.

Then again I haven't looked at Slim's current router implementation yet, so maybe I should compare first.

**Comment by codeguy** [comment]
I'm open to alternative routers. I'll investigate tonight. Thanks!

**Comment by harikt** [comment]
Alternatives are https://github.com/DASPRiD/Dash ( zf3 prototype, see https://github.com/DASPRiD/Dash/pull/54 ) , Aura.Router , Symfony router .

**Comment by harikt** [comment]
I am not for league route for see the dependencies  https://github.com/thephpleague/route/blob/5d30947732d0da0998a4174911dc8c63f922b271/composer.json#L18-L23 .

As a router, the functionality is only to route, match, generate route back. Dispatching etc is not functionality of router. Again, as Slim is already using Pimple, I don't think there needs more containers to be bought . If you are interested you could take the `nikic/fast-route` than taking all the containers, symfony/http-foundation etc.

**Comment by zoontek** [comment]
Slim actually use quite the same routing logic as Symfony (preg_match all routes)

Add new dependencies is not an obligation, my suggestion was just to implement the regex matching engine of FastRoute and only one dispatcher of choice (like https://github.com/mrjgreen/phroute do)

**Comment by alanpich** [comment]
I'm going to try some experiments to benchmark it, but I'm thinking there might be a combination of nested routers & fastroute-style pattern matching that would both speed up matching and also allow for re-usable routing modules (like Express4 on nodejs)

If each nested router combined its child routes into a single regex in that way, the total number of regexs run would be reduced, without having to compile a behemoth pattern to encompass the entire site.

**Comment by codeguy** [comment]
@harikt Bear in mind the develop-route branch is purely experimental. If we do go with League/Route, I'll have them create a new tag without the Symfony dependency since I don't need that; I'll also probably favor League/Container instead of Pimple to reduce redundant dependencies.

@alanpich Looking forward to your findings.

**Comment by harikt** [comment]
@codeguy I just said what I noticed :) . You always have the right to hear and reject :) .
