### ISSUE TITLE
Add glob support to hook names

### ISSUE THREAD

**Issue by mike-marcacci** [slimphp/Slim#1043]
Hey there, I have a nice little feature request: can we get glob support on hook names?

We use an event emitter pattern in our apps to make them very easy to integrate with analytics and decision making systems, and have been using [our own middleware](https://github.com/the-control-group/php-event-emitter) which feels a bit redundant to Slim's native `hook` functionality.

This allows listeners (ie, hooks) to be applied based on patterns like `my.hook.*` instead of having to add a hook for each possible application. Given that you already use a `.` dot delimitated convention for hooks, this should be really easy and backwards compatible!

Let me know if this would be a welcome feature for 3.0!

**Comment by mike-marcacci** [comment]
No explanation for the close? I think this would be a pretty useful feature!

**Comment by silentworks** [comment]
Sorry looking at alternative routing solution for 3.0, I think when the routing is finalised this will become relevant or irrelevant then.

**Comment by mike-marcacci** [comment]
Ah, sounds fair. Cheers!
