### ISSUE TITLE
Deprecated $HTTP_RAW_POST_DATA php 5.6

### ISSUE THREAD

**Issue by IAmWebSA** [slimphp/Slim#1045]
Hi,
I am getting the following issue, while posting JSON data to Slim 2.6.0: 

PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

**Comment by tuupola** [comment]
It is an PHP 5.6 issue. 

https://www.bram.us/2014/10/26/php-5-6-automatically-populating-http_raw_post_data-is-deprecated-and-will-be-removed-in-a-future-version/
