### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by vutran** [slimphp/Slim#1046]
Is there a changelog available somewhere? I want to be able to update all my production apps but I don't know if there are any breaking changes in v2.6.1 as compared to 2.5.0.

In the meantime, I could go through the commits manually to check but a dedicated change log doc with briefs on what's added, changed, or removed would be super helpful.

**Comment by codeguy** [comment]
You can find details about each release on the release tag page. See those at https://github.com/slimphp/Slim/releases. Slim also follows Semantic Versioning... so 2.x up to but not including 3.0 will be backwards compatible with earlier 2.x releases.
