### ISSUE TITLE
[develop] Create session middleware

### ISSUE THREAD

**Issue by alanpich** [slimphp/Slim#1049]
I'm thinking that session handling should be removed from the core and left up to the user to implement via middleware. This would make it far easier to switch out session handling strategies and completely decouples it from the core routing & despatch systems.

Arguments for/against? If agreed I'll submit a PR once the middleware interface stabilises

**Comment by silentworks** [comment]
I am for this, I currently use the Laravel Session library through a middleware I created instead of the built in Session handling.

**Comment by codeguy** [comment]
I'm OK with this so long as we provide at least one good session middleware in the Slim-Middleware repo. @silentworks Do you want to get that going?

**Comment by alanpich** [comment]
Can the middleware be split out into separate repos? If i only want the Session handler middleware, i don't want to have to pull in the 10 other middlewares along with it that i'm not going to use.

Make slim/middleware a collection package of the other repos

**Comment by codeguy** [comment]
Seems reasonable to me.

**Comment by silentworks** [comment]
Yeah I will get this sorted.

**Comment by codeguy** [comment]
@silentworks Thanks! Send a PR to the develop branch when ready.

**Comment by codeguy** [comment]
Since we're extracting sessions from Slim core, I guess we can do away with the hard dependency on Zend/Crypt, correct? We'd lose encrypted cookies, but I'm not entirely sure that's necessary anyway due to the inherent 4Kb limitation on cookie data. I definitely want the new Session middleware to offer encryption as an option.

How close are you on this?

**Comment by akrabat** [comment]
I'd like to lose the encrypted cookies from core if we can. It feels like something that could also be in middleware.

**Comment by codeguy** [comment]
Agreed. I'll work on stripping out the encryption stuff today.

**Comment by silentworks** [comment]
I have started working on this now, should have something up on the weekend. I will need to touch base with you @codeguy over irc or on hangout before then.

**Comment by codeguy** [comment]
I'll be on irc all day. Just open a private query when you want.

**Comment by codeguy** [comment]
Don't forget to also accommodate flash messaging. The original Flash class still exists in the core repo. Feel free to migrate this class if necessary.

**Comment by codeguy** [comment]
I've removed sessions from core, so renaming this to something more appropriate for the new session middleware.

**Comment by codeguy** [comment]
@silentworks How's this coming along?

**Comment by silentworks** [comment]
@codeguy getting there, but slower than anticipated due to workload. Hit me up when ur on irc or hangout.

**Comment by codeguy** [comment]
@silentworks I'll be on irc most of the day if you need to chat.

**Comment by codeguy** [comment]
This can wait until after the 3.0.0 release if need be. So there's no super rush on this.

**Comment by silentworks** [comment]
Ok cool, sorry just got was too busy lately with other work. Downtime is currently minimal.

**Comment by codeguy** [comment]
No worries. That's what I figured.

**Comment by geggleto** [comment]
I am going to revive this topic for discussion. What features are we looking for in the middleware ?

``` php
$app->add(function ($req, $res, $next) {
    session_start();
    $next($req, $res);
});
```

**Comment by geggleto** [comment]
https://github.com/geggleto/SessionMiddleware

Takes _SESSION injects into Request via Attributes.

**Comment by codeguy** [comment]
My question is... do we even need this? Can we recommend another PSR-7 middleware that already exists? If not, more than happy to have this built

**Comment by geggleto** [comment]
I don't know of any but I would imagine its built already ?

**Comment by designermonkey** [comment]
Can this issue be closed? A repository exists for a Slim implementation of sessions, although no work has been done for a while.

I would assume Slim is not offering session handling as there are plenty of available libraries out there.

**Comment by akrabat** [comment]
Yeah - We'll have a Slim session implementation if someone cares enough...

**Comment by designermonkey** [comment]
:)
