### ISSUE TITLE
Slim Application Modes

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#105]
This is an upcoming feature in version 1.3. This feature will allow you to run a Slim application in one of three modes: PRODUCTION, DEVELOPMENT, or TEST. To define the application mode, you can either set an environment setting, available in PHP with `$_ENV['mode']`, or you can define the mode at runtime with:

```
Slim::setMode('PRODUCTION');
```

or with:

```
Slim::init(array('mode' => 'PRODUCTION'));
```

I will likely expose each mode as a class constant to avoid potential human error when specifying the mode names.

So, those are application modes. Now, I also want to enable the developer to configure the Slim application differently depending on the given mode. To do this, I will add the following static function to the Slim class:

```
Slim::configure(Slim::MODE_PRODUCTION, function () {
    //Init app for production
});

Slim::configure(Slim::MODE_DEVELOPMENT, function () {
    //Init app for production
});

Slim::configure(Slim::MODE_TEST, function () {
    //Init app for production
});
```

When the application is run, the appropriate callback defined above for the current mode will be invoked.

The `Slim::configure` method is likely too similar to the existing `Slim::config` method. I will probably rename `Slim::config` to something else, but keep `Silm::config` for backwards compatibility.

I will spearhead this feature. But feel free to post your thoughts here before I get started on this later this weekend.

**Comment by michaelsmanley** [comment]
I like the idea of having differentiated execution modes, but I'm always a little chafed when I'm limited to only a strict set of environments. 

Would it be possible to have those as a default set of modes, and allow for additional modes if necessary? In previous projects I've worked on there were DEV, QA (same as TEST), STAGE, PROD, CI and DEMO environments, each with its own configurations, for example. I'd like to be able to specify my own modes.

**Comment by codeguy** [comment]
@michaelsmanley I was thinking the same thing. It should be easily done with the same code above like this:

```
$_ENV['mode'] = 'foo';
```

or...

```
Slim::init(array('mode' => 'foo'));
```

And then:

```
Slim::configure('foo', function () { ... });
```

Thanks for mentioning that.

**Comment by michaelsmanley** [comment]
That looks good to me. Thanks much.

**Comment by codeguy** [comment]
This has been pushed up the `develop` branch.

## Determining application mode

The environment variable is given first priority. If `$_ENV['SLIM_MODE']` is available, that will determine the application mode. Else, if the mode was specified during configuration with `Slim::config(array('mode' => 'foo'))`, that will determine the application mode. Else, the default application mode is `development`.

## Configuring for an application mode

After you call `Slim::init()`, you can configure slim for a given mode with:

```
Slim::configureMode('name_of_mode', function () {
    //Configure Slim here for this mode
});
```

In a real scenario, you will likely call `Slim::configureMode` once for each potential application mode. Only the configuration for the current application mode will be invoked. Also, `Slim::configureMode` will invoke the configuration callable _immediately_.

Closing this out. Will provide more detailed documentation upon 1.3.0 release.
