### ISSUE TITLE
[develop-fastroute] Are Route Groups still required?

### ISSUE THREAD

**Issue by alanpich** [slimphp/Slim#1050]
Given the possibility of nested routers, are route groups still required? Can someone post a use case for them? I'm tempted to drop them in favour of nesting routers instead...

**Comment by codeguy** [comment]
Can you post an example of what route mounting syntax will look like?

**Comment by codeguy** [comment]
Also I've merged FastRoute into the develop branch, so send any PRs there.

**Comment by silentworks** [comment]
woot woot, any benchmark on performance difference?

**Comment by codeguy** [comment]
Not yet, but you're welcome to run and post some seige results comparing develop and master branches.

**Comment by harikt** [comment]
@codeguy @silentworks there will not much performance benefits. These are really nano seconds.

**Comment by alanpich** [comment]
@harikt nano seconds \* millions of requests is suddenly quite a significant number.

I'm still working on how the route mounting will fit in with the existing structure, I'm a bit worried it will change a large portion of the API so trying to be sensible about it. This is a rough synonpsis of my thinking:

# Slim Submodules (Router Mounting)

In Slim v3, 'Route Groups' have been replaced with a module structure that allows for re-usable, portable sub-applications to be `mounted` onto an application. The main conceptual change is the promotion of the Router to the primary interaction object within the library, and having Slim\App extend from it directly so as to inherit its behaviours.

## Key conceptual changes

The 'Application' ceases to be the central focus of the API, merely being a subclass of the Router (with a few useful additional methods). Once the Application is understood to be the _Primary Router_, then the relationship between nested routes & middleware becomes much more clear.

## Example pseudo-structure

```
Application (Primary Router)
- [middleware] SessionHandler
- [middleware] CORSHeaderMiddleware
- [route] /foo
- [route] /foo/:id
- [mount] /auth  Authentication Module (Child Router)
     -  [middleware] SomeOtherMiddleware
     -  [route] /login

```

## Middleware stacks & inheritance

Because of the nested nature of Routers, and the multiple points at which middleware can be attached to the application the order in which they get executed can get confusing. The way to think of the ordering is to walk down the router tree from the top (Primary/Application router), executing each level's middleware as you go. In the example above, the order of execution for the route `/auth/login` would be:
- SessionHandlerMiddleware
- CORSHeaderInjectorMiddleware
- SomeOtherMiddleware
- _any other middleware attached directly to the route_

## Example use

``` php
<?php /**
NOTE: For the purposes of this example, \Slim\App now extends \Slim\Router
*/

use Slim\Route;
use Slim\Router;

/** Top-level route definition, same as existing API */
$app = new Slim\App();

// Add some application-wide middleware
$app->uses( new CORSHeaderInjectionMiddleware )

// Define our top-level routes as normal
$app->get('/foo',function(Request $req, Response $res){
   // ...
});


/**
 * Create a re-usable module to be 'mounted' into a Slim app
 */
// Create the router for the module
$myModuleRouter = new Router();
// Add in some middleware for all routes in this module
$myModuleRouter
    ->uses( $myAuthenticationMiddleware )
    ->uses( $someOtherMiddleware )
// Define some routes on the module
$myModuleRouter->get('/baz',function(Request $req, Response $res){
    // ... do something
})


/**
 * Now mount the module into your app's router at the 
 * specified URI path. In this example, the module is
 * mounted at `/bar`, so the module's `/baz` route will
 * actually match `/bar/baz` 
 */
$app->mount('/bar',$myModuleRouter);


// Run the application...
$app->run();

```

**Comment by codeguy** [comment]
The only big issue I see with this is updating how Slim uses the application container (Pimple). We'll need to inject that somewhere so that we can define the factory methods for the request, response, crypt, etc. objects.

**Comment by alanpich** [comment]
Well crypt would presumably be dropped if the Session handler was extracted to a separate middleware, but I get your point. Would require a massive shift in structure...

**Comment by codeguy** [comment]
We'd still need crypt for cookie data.

**Comment by harikt** [comment]
I would like to point to an old benchmark : https://github.com/c9s/Pux/issues/17#issuecomment-32275754 .

**Comment by alanpich** [comment]
Cookies as optional middleware? Don't need them for all/every scenario.

**Comment by silentworks** [comment]
I am not too sure I agree with the direction this is headed. I think this removes the simplicity out of Slim, lets keep it simple please. I think the developer should make the decision of how much complexity they want their app to have rather than us making that decision.

**Comment by alanpich** [comment]
Exactly, let the developer include as much optional extras as they want, they shouldn't have packages thrust upon them that they might not need

**Comment by codeguy** [comment]
@silentworks Which parts specifically do you disagree with? Just asking for clarification. I think this particular thread is a bit much for 3.0... I may hold off on any huge API changes until a later release.

**Comment by silentworks** [comment]
I am referring to the route group changes and making it act like submodules. This to me would push a lot of users away, especially beginners. Slim has always been simple and beginner friendly, I think the kind of abstraction introduced above would remove that simplicity.

**Comment by codeguy** [comment]
I think it can work if done well. But I think this is probably too big a change to include in 3.0. I say let's put this idea on the backburner for now and re-visit in the future.

**Comment by codeguy** [comment]
Going to close this out. Let's revisit after 3.0 launches.
