### ISSUE TITLE
[develop] Suggest changing order of route params

### ISSUE THREAD

**Issue by silentworks** [slimphp/Slim#1052]
With the current setup it is expecting route name first then pattern and then callable. I reckon we should move name to be the last param.

current implementation

``` php
$app->get('home', '/', 'Class:method');
```

proposed implementation

``` php
$app->get('/', 'Class:method', 'home');
```

This way existing Slim 2 apps can port routing easier and also it leaves name optional at this point if its at the end as some users don't actually use route names.

**Comment by codeguy** [comment]
:+1: Send PR please

**Comment by harikt** [comment]
nice silentworks :) . 

Also this is much readable .
