### ISSUE TITLE
Authentication Plugin

### ISSUE THREAD

**Issue by tjbell** [slimphp/Slim#106]
The code below is from the release version of the docs.
    <?php
    /**
     \* MyPlugin.php
     */
     Slim::hook('slim.before.dispatch', function () {
        $request = Slim::request();
        $currentRoute = Slim::router()->current();
        if ( preg_match('@^users/@', $currentRoute->pattern) ) {
            //Authenticate current user or redirect to login page
        }
     });
When I tried this code I receive `Fatal error: Cannot access protected property Slim_Route::$pattern in /var/www/lost/plugins/authentication.php on line 9`.
Any help would be great appreciated.

**Comment by codeguy** [comment]
Sorry. I need to update that code in the docs. It should use `$currentRoute->getPattern()`.
