### ISSUE TITLE
Routes not matched when rewriting URL's to a subdirectory (under Windows)

### ISSUE THREAD

**Issue by emilh91** [slimphp/Slim#1063]
Consider using `$_SERVER['REDIRECT_URL']` instead of `$_SERVER['REQUEST_URI']` in [Environment::__construct(), line 131](https://github.com/slimphp/Slim/blob/master/Slim/Environment.php#L131).
No routes get matched because `$env['PATH_INFO']` does not have the physical path portion removed (line 145 does not get executed).

Here is my project structure:

```
project
    .htaccess
    app
    web
        .htaccess
        api
            v1
                index.php
        css
        img
        js
```

`project/.htaccess` contains the following to redirect all requests to the `web` subfolder:

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^$ web/ [L]
    RewriteRule (.*) web/$1 [L]
</IfModule>
```

`project/web/.htaccess` contains the following to route everything to `index.php`:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^api/v1 api/v1/index.php [QSA,L]
</IfModule>
```

Some potentially useful info:
- Windows 7
- Apache 2.4
- PHP 5.6.4
- Slim 2.6.1

**Comment by silentworks** [comment]
We are only doing security fixes to version 2 now. Please test this in version 3 and let us know if this is still true.
