### ISSUE TITLE
can't access to $c in App.php

### ISSUE THREAD

**Issue by nhymxu** [slimphp/Slim#1065]
> Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid HTTP version. Must be one of: 1.0, 1.1, 2.0' in E:\Software\OpenServer\domains\slim.local\slim\Http\Response.php:223 Stack trace: #0 E:\Software\OpenServer\domains\slim.local\slim\App.php(115): Slim\Http\Response->withProtocolVersion(NULL) #1 E:\Software\OpenServer\domains\slim.local\vendor\pimple\pimple\src\Pimple\Container.php(108): Slim\App->Slim{closure}(Object(Slim\App)) #2 E:\Software\OpenServer\domains\slim.local\slim\App.php(459): Pimple\Container->offsetGet('response') #3 E:\Software\OpenServer\domains\slim.local\index.php(49): Slim\App->run() #4 {main} thrown in E:\Software\OpenServer\domains\slim.local\slim\Http\Response.php on line 223

I try var_dump($c['settings'] and see 

>  ["defaults":protected]=>
>   array(17) {
>     ["mode"]=>
>     string(11) "development"
>     ["view.templates"]=>
>     string(12) "../templates"
>     ["cookies.encrypt"]=>
>     bool(false)
>     ["cookies.lifetime"]=>
>     string(10) "20 minutes"
>     ["cookies.path"]=>
>     string(1) "/"
>     ["cookies.domain"]=>
>     NULL
>     ["cookies.secure"]=>
>     bool(false)
>     ["cookies.httponly"]=>
>     bool(false)
>     ["crypt.key"]=>
>     string(32) "A9s_lWeIn7cML8M]S6Xg4aR^GwovA&UN"
>     ["crypt.cipher"]=>
>     string(3) "aes"
>     ["crypt.mode"]=>
>     string(3) "cbc"
>     ["crypt.hash"]=>
>     string(6) "sha256"
>     ["session.handler"]=>
>     NULL
>     ["session.flash_key"]=>
>     string(9) "slimflash"
>     ["session.encrypt"]=>
>     bool(false)
>     ["http.version"]=>
>     string(3) "1.1"
>     ["routes.case_sensitive"]=>
>     bool(true)
>   }

In line 115. **$c['settings']['http.version']** return null

Replace to **$c['settings']->getDefaults()['http.version']** and return 1.1

**Comment by nhymxu** [comment]
After change **.** to **_** I see slim work well.

> ```
> protected $defaults = array(
>     // Application
>     'mode' => 'development',
>     'view_templates' => '../templates',
>     // Cookies
>     'cookies_encrypt' => false,
>     'cookies_lifetime' => '20 minutes',
>     'cookies_path' => '/',
>     'cookies_domain' => null,
>     'cookies_secure' => false,
>     'cookies_httponly' => false,
>     // Encryption
>     'crypt_key' => 'A9s_lWeIn7cML8M]S6Xg4aR^GwovA&UN',
>     'crypt_cipher' => 'aes',
>     'crypt_mode' => 'cbc',
>     'crypt_hash' => 'sha256',
>     // Session
>     'session_handler' => null,
>     'session_flash_key' => 'slimflash',
>     'session_encrypt' => false,
>     // HTTP
>     'http_version' => '1.1',
>     // Routing
>     'routes_case_sensitive' => true
> );
> ```

change from **http.version** to **http_version** in Configuration.php and App.php
=> work

**Comment by codeguy** [comment]
@silentworks Is this supposed to happen?

**Comment by codeguy** [comment]
This is fixed.
