### ISSUE TITLE
Slim::redirect

### ISSUE THREAD

**Issue by tjbell** [slimphp/Slim#107]
If I create a get route and try to redirect to it I receive a 404. I'm not super familiar with low level HTTP. So, I was wondering if the redirect function only works with Slim::post or is 
this a php/apache/rewrite configuration problem.

**Comment by codeguy** [comment]
Hmm... Can you post some sample code that demonstrates this issue? `Slim::redirect` will accept and use any URL to set the `Location:` HTTP header; the `Location:` header instructs the client to send a subsequent request for the new URL. The `Slim::redirect` method also sets the HTTP response code to a 3xx redirect.

You should be able to call `Slim::redirect` from within any route... be it GET, POST, PUT, or DELETE.

**Comment by codeguy** [comment]
Nevermind. I've duplicated the issue here and am looking into it.

**Comment by codeguy** [comment]
Solution:

```
Slim::redirect('/new-url', 302);
```

This code issues a HTTP 302 Found redirect response. By default, `Slim::redirect` will send a HTTP 307 Temporary Redirect response. I'll need to do some additional resesarch to determine which response should be the default.

**Comment by codeguy** [comment]
After some quick searching, it appears HTTP 302 Found is the default status for generic redirects. I've updated both branches with a small hotfix... `Slim::redirect` will use 302 by default now. Should work. Let me know if it does not.
