### ISSUE TITLE
[develop] MiddlewareAware

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1071]
HI,

Would it be quicker and more efficient to use `SplStack` as the `$stack` instance instead of calling `array_unshift` for every appended middleware?

``` php
protected $stack;

protected function seedMiddlewareStack()
{
    if (is_null($this->stack)) {
        $this->stack = new SplStack;
        $this->stack->setIteratorMode(SplDoublyLinkedList::IT_MODE_LIFO | SplDoublyLinkedList::IT_MODE_KEEP);

        $this->stack[] = $this;
    }
}
```

**Comment by codeguy** [comment]
Probably :) Forgot that little guy existed.

**Comment by codeguy** [comment]
Do want to send a PR or should I do this?

**Comment by codeguy** [comment]
I was bored. Went ahead and pushed this up https://github.com/slimphp/Slim/commit/ed994a1ee44f66b6da8c2d734a9f41b46971044c
