### ISSUE TITLE
Add "RewriteBase /" to .htaccess file

### ISSUE THREAD

**Issue by brianwgibson** [slimphp/Slim#108]
Some hosting providers require this.  Include a comment about setting the path if installed in a subfolder.  This can be commented out by default or not.  It would certainly save time for those who encounter an Apache config error.

**Comment by codeguy** [comment]
I'll add a note about this in the default .htaccess file later this evening. Thanks!

**Comment by codeguy** [comment]
Done. Merged into both branches.

**Comment by benatkin** [comment]
If you have control of your Apache installation, how do you make it so RewriteBase isn't necessary? I'm looking for the information myself and I'll report what I find.
