### ISSUE TITLE
Group Middleware is a lie

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#1085]
While defining route we can attach middleware at the group level, on my point of view that's in fact a kind of helper to prefix a bunch of routes since there is no more group at the dispatch time.
So if 2 or more routes in a same group match the requested path the group's middleware will be called twice ( or more ).
Isn't that an issue ?
If yes maybe the group can act as a subrouter, the group's middleware will be call only once for the entire group's routes matching the requested path.

ps: sorry for the trolling title

**Comment by codeguy** [comment]
![lies](https://cloud.githubusercontent.com/assets/31677/6597439/16e79b62-c7d3-11e4-8bab-b7883da1aee6.gif)

**Comment by codeguy** [comment]
Only one route is ever invoked for each request, so I don't see how this is an issue.

**Comment by lalop** [comment]
oO
ok, this reflection comes from this issue https://github.com/slimphp/Slim/pull/953
I don't know enought about FastRoute to get that last point.
So yes there is no issue here.

**Comment by codeguy** [comment]
Cool. Route "passing" has been removed from 3.x because it's a rarely used feature with too much overhead.
