### ISSUE TITLE
[develop] Problem with the optional route name?

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#1086]
Consider:

``` php
$app->get(
    '/',
    function($request, $response) {
        echo "<p>Hello world</p>";
    }
);
```

There's no route name at the end, so `mapRoute()` will assign the last parameter to `$name`. It then works out that there's no callable, so assigns `$name` to `$callable` and then invents a new `$name` string. This works as expected. 

Now consider:

``` php
$app->get(
    '/',
    function($request, $response, $next) {
        echo "<p>Route middleware functionality</p>";
        return $next($request, $response);
    },
    function($request, $response) {
        echo "<p>Hello world</p>";
    }
);
```

In this case, `$name` is the "Hello world" closure and `$closure` is the route middleware. This doesn't work. We get this error: _Warning: Illegal offset type in Slim/Slim/Router.php on line 74_.

In theory we could detect this by noticing that $name is a callable, but then this case doesn't work:

``` php
$app->get(
    '/',
    function($request, $response, $next) {
        echo "<p>Route middleware functionality</p>";
        return $next($request, $response);
    },
    'App\Controller\HomeController:home'
);
```

In this case, `$name` is now 'App\Controller\HomeController:home', & `$callable` is the route middleware closure.

I _think_ the solution is to try and resolve `$name` to a callable using `resolveCallable` and if it turns into a closure, then rearrange stuff.

Clearly, this is why `$name` was a mandatory first parameter earlier in 3's dev cycle and why 2 has a separate `name()` method.

Thoughts?

**Comment by codeguy** [comment]
This was why I had the name parameter as required in the earlier 3.x version. The easiest solution is to require a name argument (first or last). This may be a pain to some, but it does make you think about what you are building and it does give you the ability to use the `urlFor()` method later on.

We could restore the `name()` method on the Route object, but this exposes/leaks the Router's internal implementation. It's messy from an architectural pov, but it solves the problem. It does add a tiny amount of overhead when looking up a named route because we have to iterate over all routes and cache a lookup table from name to route... this only has to be done once on the first call to `urlFor()`.

Thoughts?

**Comment by silentworks** [comment]
I almost feel like making route middleware attach through a method would be a better solution? This would also mean the API would feel the same as adding an middleware to the app.

``` php
$app->get('/', 'HomeController:index')->add('Your Closure Here');
```

If multiple route middleware

``` php
$app->get('/', 'HomeController:index')->add('Your Closure Here')->add('Your Closure Here');
```

**Comment by codeguy** [comment]
@akrabat What do you think about @silentworks' idea?

**Comment by funkatron** [comment]
You didn't ask me, but I'm a big fan of that approach of adding route middleware. Changing what a method parameter does based on the number of params always felt flaky and hard to anticipate to me (jQuery does this a ton and I think it makes it harder to remember the APIs and anticipate behavior).

**Comment by akrabat** [comment]
Where does the route name go?

**Comment by codeguy** [comment]
@akrabat I assume using a method call like version 2.x does.

```
$app->get('/', 'HomeController:index')->setName('name');
```

**Comment by akrabat** [comment]
i.e. is @silentworks's proposal:

``` php
$app->get($url, $callable)->add($routeMiddleware1)->add($routeMiddleware2)->name('my-name');
```

?

**Comment by codeguy** [comment]
@akrabat Yes

**Comment by akrabat** [comment]
Generally seems sane to me. 
Let's see what other feedback we get.

**Comment by silentworks** [comment]
@akrabat either that or keep it as third parameter, but as @funkatron said, remembering which param comes first isn't very predictable for first time users so creating a method call for each would be better. 

I however wonder if there is a better way internally to do all this before passing over to the mapRoute method, as I don't like the idea of leaking the router implementation out as we did in Slim 2.

**Comment by codeguy** [comment]
I just don't see a clean alternative. Exposing the route object is not as neat as I'd prefer, but it's something I can live with. I +1 @silentworks' solution.

**Comment by akrabat** [comment]
As a rule, I prefer explicit over magic, which is another plus point in @silentworks' explicit method call solution.

**Comment by codeguy** [comment]
Another option (not that I like it any better) is to introduce new methods on the `App` instance:

```
$app = new \Slim\App();
$app->namedGet('list', '/list', $callable);'
$app->run();
```

**Comment by codeguy** [comment]
We could also do something like this http://laravel.com/docs/4.2/routing#named-routes where the last argument is an array that could be overloaded to provide middleware, callable, name, etc.

```
$app->get('/list', [
    'name' => 'listUsers',
    'add' => [$mw1, $mw2],
    'callback' => $callable
]);
```

**Comment by codeguy** [comment]
Re: previous comment, if second argument is callable, consider it the route callable and be done with it. If the second argument is NOT callable and an array, make sure the array has a "callback" key, but also use the "name" and "add" keys to specify a name and middleware.

EDIT: If second arg is not callable and a string, run it through `setCallable()` and use the resultant value as the route callable.

**Comment by silentworks** [comment]
The second arg as an array still feels like its not explicit enough, as in an IDE won't know the keys for the array being passed, whereas the explicit naming would allow for this.

**Comment by codeguy** [comment]
I agree. I'll go ahead and make an executive decision that we move forward with @silentworks' solution. The `App` instance's routing methods (e.g., `get()`, `post()`, and so on) will always accept two arguments:
1. The route URI
2. The route callable

The `App` instance's routing methods return the new `Route` object, and you can chain additional methods provided by that `Route` object to set names or add middleware.

```
$app->get('/list', 'Controller::method')->setName('list')->add($mw);
```

**Comment by JoeBengalen** [comment]
I agree method chaining gives the nicest API. 

Altough I do think you need to document this solution well,. Chaining options to add `$mw` and a name does not become clear when using the `$app->get()` method, as it does not become visible as an argument.

**Comment by akrabat** [comment]
@codeguy: Works for me.

@JoeBengalen: I agree about documentation, though I think you'll find that with the appropriate doc blocks, IDEs will offer autocomplete for `add()` & `setName()`

**Comment by Xevris** [comment]
Might a more descriptive method name like "middleware" make more sense?

Would allowing the same method to accept an array and/or an unspecified number of arguments make more sense than repeated method calls?

->middleware('mw1', 'mw2');

**Comment by codeguy** [comment]
This is done. Route names are now optional and must be set using a chained method call like this:

```
$app->get('/pattern', 'callable')->setName('name');
```

**Comment by akrabat** [comment]
Thanks!
