### ISSUE TITLE
Conte-Type: application/json and params()

### ISSUE THREAD

**Issue by gambry** [slimphp/Slim#1087]
Hi,

Not sure if I'm doing anything wrong, but I have an issue with post data sent as JSON Payload.

I've setup Slim to deal with Restangular library. As Restangular is posting data with the JSON Payload (_Content-Type: application/json;charset=utf-8_) on the body of the request I'm using the \Slim\ContentTypes middleware to properly set $env['slim.input'];

However when I try to fetch the parameters with request->params('name') these are all empty.

Infact according with post() method on \Slim\Http\Request:

$this->env['slim.input'] is set
--> then it doesn't throw any Exception.

$this->env['slim.request.form_hash'] is not set
--> then it's set as array().

$this->formData() is false (as Content-Type is not null and MediaType is not _application/x-www-form-urlencoded_)
--> then $this->env['slim.request.form_hash'] is set as Util::stripSlashesIfMagicQuotes($_POST) who is clearly wrong as there is no $_POST data.

I've temporary patched the post() method adding this additional condition on line 265:

``` php
} else if (is_array($this->env['slim.input']) && isset($this->env['slim.input_original'])) {
    $this->env['slim.request.form_hash'] = Util::stripSlashesIfMagicQuotes($this->env['slim.input']);
}
```

Am I doing anything wrong?

Thanks

**Comment by codeguy** [comment]
You'll need to json decode `$request->getBody()`.

**Comment by gambry** [comment]
Thanks @codeguy , however I was trying to understand if there was an [even expected] way to fetch the json parameters from $request->params instead of the manual json decode $request->getBody for _application/json_ request. I understand the answer is no.
Thank you for your help and great job with Slim!

**Comment by codeguy** [comment]
In v2, only form urlencoded http bodies were decoded and made available via `params()`. Is this ideal? In hindsight, not really :) v3 will be much better about this.

**Comment by gambry** [comment]
Thank you for your time, I'll fork and apply my patch as I really need JSON data to be accessible via params(). (and if you want this on v2 I'll send a merge request as well)

**Comment by tuupola** [comment]
There already is [ContentTypes middleware](https://github.com/slimphp/Slim/blob/master/Slim/Middleware/ContentTypes.php) for v2.

**Comment by gambry** [comment]
@tuupola it parses the content-type, but it doens't make json data available via params().

**Comment by gambry** [comment]
However - just to be completed - I'm already using [ContentTypes middleware](https://github.com/slimphp/Slim/blob/master/Slim/Middleware/ContentTypes.php), which is great BTW, but the problem seems to be on \Slim\Http\Request->post(), as detailed above.
