### ISSUE TITLE
use of parse_str forces php-specific use of request values

### ISSUE THREAD

**Issue by skywaymsn** [slimphp/Slim#1088]
Calling in to $app->request->get/params() uses parse_str which requires the use of PHP-specific HTTP request vars in order to obtain multiple values for the same parameter.

Example:
http://SomeAPI/people?FirstName=Joe&FirstName=Bob

parse_str() only accepts the last value.
parse_str('param=X&param=Y&param=Z');

produces
$param = ['param' => 'Z'];

preferred:
$param = ['param' => ['X','Y','Z']];

The only way around it is to use the odd PHP construct of appending meaningless [] to the end of the request parameters:

http://SomeAPI/people?FirstName[]=Joe&FirstName[]=Bob

Can we replace the call to parse_str() with something that handles multiple parameters of the same name?  Or add an optional parseFactory or something so we drop in our own?

**Comment by codeguy** [comment]
As far as I know, there is no official specification or recommendation regarding parsing multiple query parameters with duplicate names. So I'd rather rely on an existing, well adopted solution which happens to be PHP's `parse_str()` function.

**Comment by UrvishSSPL** [comment]
There is another issue with the `parse_str` function. It replaces the '+' symbol with space.
If we read sort request from the query string like + for ascending or - for descending, the parse_str will remove the + symbol.
So, the request -order_date,+name will become -order_date, name.
