### ISSUE TITLE
[develop] method name more explicit than MiddlewareAware::app

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#1091]
I've done a look around and I think the method name `add` is not really explicit on what it does.

I look at Stackphp but the implementation is too much different.
Silex dosn't implement global middlewares, only before, after and finish.

The most used keywords for that is "use" :
- rails http://guides.rubyonrails.org/rails_on_rack.html
- sinatra http://www.sinatrarb.com/intro.html
- express http://expressjs.com/guide/using-middleware.html
  This is not much more explicit than add but it seems to be a kind of convention.

@weierophinney built a library (https://github.com/weierophinney/conduit) where he calls that `pipe`. I think that is much more clear Although it dosn't reflect the fact that the response make round-trip through the stack .

What do you think ?

**Comment by codeguy** [comment]
If we were to change it, I'd go with "uses()" or "use()". Nothing else really makes sense or is as easy to type.

**Comment by codeguy** [comment]
And I don't think we can get away with "use" as a function name anyway.

**Comment by tuupola** [comment]
Without context `add()` is a bit unintuitive. It becomes more clear when you add parameter to it. 

``` php
$app->add();
$app->add(new Slim\Middleware\FooBar);
```

**Comment by lalop** [comment]
@tuupola Yes but the Slim Application is a router, a container and a middleware stack so that can be disrupting for someone who discovers the framework excepts if that is going to change in Slim 3.

@codeguy we can't named a function use

**Comment by codeguy** [comment]
Eh, I'm happy with "add".
