### ISSUE TITLE
[develop] Separating the concerns

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1097]
Call me crazy, but I had an idea on app structure while playing with various PSR-7 implementations, and I thought I should mention it here.

As Sessions and Cryptography are going towards Middleware, I thought about how tightly wrapped up the App class actually is, and how in theory, the whole thing could just be a Middleware runner.

I was playing with Phly/Http, and adding everything in as a middleware. Phly/Http has a Server component separate from an app, so I looked at Slim's MiddlewareAware trait, using a very simple class to instantiate it. I tweaked things a little so that the invoke method was passed to the Server instead of being the final callback in the Middleware queue, and that the invoke method was basically doing what `run` does now in Slim.

Going down this route made me think that basically, every part of the App could actually be a Middleware, including Routing... The Router could be a middleware that runs sub-middleware-stacks being each Route. I know that the MiddlewareAware is already being added into Routes, so it kind of makes sense (I think).

The App is currently a lot of helper methods that point to methods inside the components of Slim, so each component could be made into Middleware with an invoke method. All the App would be is a Container housing a Server (which supplies the Request Response set with Headers and Cookies) and a Middleware Runner to plug things in to the Server.

Any thoughts anyone?

/cc @codeguy @silentworks

**Comment by codeguy** [comment]
I think some psuedo-code would help here.

**Comment by psychoticmeow** [comment]
It would be good to be able to combine Slim with ReactPHP's HTTP server, so we can have a process that handles asynchonous requests.

**Comment by designermonkey** [comment]
I'm no good with pseudo code.

[This is me playing](https://github.com/usebeagle/sandbox/commit/dd221fd3a91513431edbd2242559cea1036405e6) with the idea, and here's a lovely picture.

![screen shot 2015-03-15 at 16 45 34](https://cloud.githubusercontent.com/assets/221344/6657100/b4cb6878-cb38-11e4-80da-ee2baa61f049.png)

Left is how I see Slim at the mo, and right is the crazy that I'm talking.

**Comment by codeguy** [comment]
I think this is worth exploring, but not for version 3.0. Definitely 4.0. Keeping this open for discussion.

**Comment by r3wt** [comment]
@designermonkey Could you explain the benefits of this model? Does this increase modularity of Slim?

**Comment by geggleto** [comment]
@r3wt @codeguy @silentworks 

Might look something like...

```
$app = new \Slim\Slim();

//If we care to parse/sanitize environment variables
$app->add(new \Parser\EnvironmentParser()); 

//If we want to parse/sanitize JSON bodies
$app->add(new \Parser\JsonParser());

//If we want to parse/sanitize PlainText bodies
$app->add(new \Parser\BodyParser());

//If we want to parse/sanitize _POST
$app->add(new \Parser\PostParser());
... etc

```

It does give us more control over the project and makes it a bit more clear at a high level what goes on in our app. At the moment if I were to hand a project to a co-worker there is little way to view the code and KNOW how slim handles input. 

This would mirror other projects and languages (express.JS comes to mind).

**Comment by codeguy** [comment]
@geggleto Is this not already possible? You can add a JsonParser or a BodyParser and inject the parsed body into the Request object with `withParsedBody($parserResults)`.

**Comment by geggleto** [comment]
I think what this was mainly pointing to would be the ability to inject different Parsers as middleware instead of having them all contained in the app instance.

**Comment by AleksanderKoko** [comment]
I don't think ReactPHP is a good idea for Slim @psychoticmeow . Not only for Slim but for PHP in general. That kind of programming is not what PHP is being used for. It is nice to play with it, or to be an option. If you want to have very very good asynchronus applications, you should stay with NodeJS because Node does it better. Was build from the ground up for that purpose.

Don't forget that may be fast but have other new problems. Anyway, I don't think Slim should have ReactPHP aproach right now.

**Comment by designermonkey** [comment]
> Is this not already possible?

Well, yes in a way, it is already possible, but it isn't middleware at the moment, and the example just shows parsers. What I was meaning was _every_ aspect of the application, Configuration, Router, Sessions, Cookies, etc.

Currently it's all tightly wrapped in the App class. I know we discussed it before @codeguy and you told me that it's a write once framework where it could be overridden afterwards by a developer.

I do really think though that every part of Slim can be middleware, and a bootstrap file would replace the constructor that does all the work in App.php. That way a developer can either use the Slim bootstrap file, or make their own.

I know it's just another angle to the same end, but if middleware is the route that apps are going down, it would be awesome to be a full middleware stack.

**Comment by geggleto** [comment]
After speaking with @codeguy in IRC, I am going to surface the Parsers out of the request object and set them up as middleware.

**Comment by geggleto** [comment]
After looking into using middlewares for the parsers, it does not seem to be possible to abstract them out of the Request class and keep the PSR7 message interface on the middleware as it lacks the ability to reference the Slim\Http\Request->registerMediaTypeParser

We can get around this limitation by changing registerMediaTypeParser to static, as well as the bodyParser protected variable.

We would not need to use middleware, but access the request object after its created to add the parsers. Although this seems really hackish,

**Comment by codeguy** [comment]
Or we just leave it as is. That's always an option. How often are you going to consume data that isn't form urlencoded, json, or xml?

If you want to use your middleware approach, just parse the request body in the middleware and inject the parsed results back into the request with `withParsedBody()`. You incur early overhead while always parsing the request body, but if you are adding the middleware, odds are you want to do that anyway.
