### ISSUE TITLE
parse_url return false in nginx+php-fpm env

### ISSUE THREAD

**Issue by quard8** [slimphp/Slim#110]
I have strange issue, then I update code for latest 1.2.8 version, I see error.

Debugging shows me that parse_url can't parse url without protocol and host. 

Quick fix is to change in Slim/Http/Uri.php line 91 to

$uri = parse_url(($_SERVER['HTTPS'] ? "https://" : "http://").$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'], PHP_URL_PATH);

**Comment by codeguy** [comment]
Thanks! Will try to push up a fix this afternoon.

**Comment by codeguy** [comment]
Just pushed a hotfix to both branches. Tagged 1.2.9.

https://github.com/codeguy/Slim/commit/d08ae6b6df71dfa74563a4b704492bd4e332f62b
