### ISSUE TITLE
Implement `$_SERVER` support into Http\Request class

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#1100]
The `Http\Request` class needs to support the PSR-7 interface methods for dealing with the `$_SERVER` superglobal data. For Slim, this means the `\Slim\Http\Request::getServerParams()` method should return the data encapsulated by the current Environment object. The Environment object data, I imagine, should be injected during Request instantiation. This is currently unclaimed and anyone is free to work on this. Let me know if you intend on working on this so I can assign it.

**Comment by paul-court** [comment]
I'd like to get involved in contributing to Slim. Can I claim this and give it a poke and see how I get on?

**Comment by codeguy** [comment]
:+1: Go for it. Feel free to ask any questions here if you have them.

**Comment by paul-court** [comment]
I've sent a PR, but not sure if there is an intention to do something different with Environment? I can see it's initialised only with $_SERVER at the moment, but is the idea for it to be used with other data too?
