### ISSUE TITLE
slim 3.0 setName() and add() cannot use together

### ISSUE THREAD

**Issue by iLexN** [slimphp/Slim#1105]
I following the docs (http://docs-new.slimframework.com/) , and try the Slim 3

```
$app->get('/hello/{name}', function ($request, $response, $args) {
    echo "Hello, " . $args['name'];    
})->setName('profile');
```

above code is working find.

   $app->get('/hello/{name}', function ($request, $response, $args) {
        echo "Hello, " . $args['name'];  
    })->add($mw);        

This code also work.

When put setName and add() together

```
$app->get('/hello/{name}', function ($request, $response, $args) {
    echo "Hello, " . $args['name'];  
})->add($mw)->setName('profile');
```

or

```
$app->get('/hello/{name}', function ($request, $response, $args) {
    echo "Hello, " . $args['name'];  
})->setName('profile')->add($mw);
```

Fatal error: Call to a member function setName() on null  /
Fatal error: Call to a member function add() on null

**Comment by JoeBengalen** [comment]
That is because both of them do not return an instance of them selves. This should be changed in my opinion. Chaining as in the example given above should be possible.

I can make a PR of that tonight if you like @codeguy

**Comment by codeguy** [comment]
Yes they should be chained. Good catch. @JoeBengalen Yes please send PR when ready. Thank you!

**Comment by codeguy** [comment]
Looks like @lalop beat you to it. :) Closing this out.

**Comment by JoeBengalen** [comment]
Haha I noticed ;)
