### ISSUE TITLE
Return Http\Response from App::redirect

### ISSUE THREAD

**Issue by siiptuo** [slimphp/Slim#1107]
The redirect helper is nice but wouldn't it be better to do this:

```
return $app->redirect('/page');
```

instead of the current:

```
$app->redirect('/page');
```

The current implementation relies on `App::stop` and exceptions but this proposal makes the control flow much clearer. For example [Silex](http://silex.sensiolabs.org/doc/usage.html#redirects) already does this.

**Comment by codeguy** [comment]
This is a good observation. I tend to agree. Send PR when ready :+1:
