### ISSUE TITLE
encrypt empty value

### ISSUE THREAD

**Issue by t8g** [slimphp/Slim#111]
as mcrypt_generic will issue a warning when the datastring is empty, the CookieJar method _encrypt should handle empty cookie :

```
protected function _encrypt( $data, $key, $iv ) {
    $iv = $this->_validateIv($iv);
    $key = $this->_validateKey($key);
    mcrypt_generic_init($this->_cryptModule, $key, $iv);
    $res = @mcrypt_generic($this->_cryptModule, $data);
    mcrypt_generic_deinit($this->_cryptModule);
    return $res;
}
```

or something like this

**Comment by codeguy** [comment]
Will fix this later this afternoon. Thanks for the heads up.

**Comment by codeguy** [comment]
Done. Pushed hotfix to both branches.

https://github.com/codeguy/Slim/commit/08e00b7dc2dadbb60565703d7a284d943a85f224
