### ISSUE TITLE
Error when creating Uri from string without a port

### ISSUE THREAD

**Issue by jenssegers** [slimphp/Slim#1110]
When creating a uri from string (in v3) without a port I get the following exception:

```
InvalidArgumentException: Uri port must be null or an integer between 1 and 65535 (inclusive)
```

**Comment by codeguy** [comment]
Thanks! I'll work on a fix tonight unless someone else jumps on this before then.

**Comment by jenssegers** [comment]
Thanks! Also, even if no port was specified, the Uri will show :80 when casting to a string.

**Comment by JoeBengalen** [comment]
The other point @jenssegers made:

``` php
echo new Slim\Http\Uri('', 'www.example.com');
// result -> www.example.com:80/
```

The port 80 is visible because the method `hasStandardPort()` wont reconize an empty scheme. It only checks for schemes `http` and `https`. This is easely solved by:

``` php
protected function hasStandardPort()
{
    return (($this->scheme === 'http' || $this->scheme === '') && $this->port === 80) || ($this->scheme === 'https' && $this->port === 443);
}

// or more readable

protected function hasStandardPort()
{
    $defaultPorts = [
        '' => 80,
        'http' => 80,
        'https' => 443,
    ];

    return isset($defaultPorts[$this->scheme]) && $defaultPorts[$this->scheme] === $this->port;
}
```

Do you also want this changed? @codeguy

**Comment by codeguy** [comment]
I've got to go back and review the latest changes to the PSR-7 interfaces. Make sure it adheres to this interface. If the port is present and standard for the given scheme, it should be excluded. If the port is present and IS NOT standard, it should be included. If the port is not present, it should be excluded.

**Comment by codeguy** [comment]
Interface is https://github.com/php-fig/http-message/blob/master/src/UriInterface.php

**Comment by JoeBengalen** [comment]
But what if no scheme is present? I can take a look at this tomorrow if you like. (Internet is down tonight :S)

Also i noticed earlier that getPath() should return '/' if empty in the new psr changes.

**Comment by codeguy** [comment]
@JoeBengalen The spec is unclear what value to return if the scheme is not present. I would presume we return the port value if present (standard or not).

**Comment by JoeBengalen** [comment]
@codeguy 

``` php
/**
     * Retrieve the port segment of the URI.
     *
     * If a port is present, and it is non-standard for the current scheme,
     * this method MUST return it as an integer. If the port is the standard port
     * used with the current scheme, this method SHOULD return null.
     *
     * If no port is present, and no scheme is present, this method MUST return
     * a null value.
     *
     * If no port is present, but a scheme is present, this method MAY return
     * the standard port for that scheme, but SHOULD return null.
     *
     * @return null|int The port for the URI.
     */
    public function getPort();
```

So if no port AND no scheme are given `null` MUST be returned. Only problem is: in the current implementation there is no way of knowing if a port was given, or the constructor default of 80 is set.

The issue is fixed BTW

**Comment by codeguy** [comment]
I'm not too worried about this. I'm fine assuming a default port for the time being.

**Comment by JoeBengalen** [comment]
You mean if `$port === 80` assume it's not given?
Then the it does not work properly at this time:

``` php
$uri = new Slim\Http\Uri('', 'www.example.com');
var_dump($uri->getPort());
// result -> (int) 80 (SHOULD BE NULL)

```

**Comment by jenssegers** [comment]
To be honest, if the user specifically enters a port, either through the constructor or the `createFromString` method, then the port should be returned as well. Let me explain; for an API implementation, we require users to sign the url + get/post parameters using a private key (similar to oauth 1). To verify that signature, the servers must sign the received request as well and verify it. So if the client does a request to `example.com:80`, but the Uri returns only `example.com`, then the signature would not match.

I think the constructor should allow a null value for the port, but if a port is specifically requested using the `getPort` method, it should "calculate" it based on the scheme. Or does this go against the PSR?

**Comment by codeguy** [comment]
Re-opening for continued discussion

**Comment by JoeBengalen** [comment]
I tend to agree that the port should be decided on getting it, not on setting. But only for the port as others need to be returned as an empty string anyway.

I will try this out in a branch and see if you like it.

**Comment by codeguy** [comment]
This is resolved.

**Comment by jenssegers** [comment]
Thanks @codeguy and @JoeBengalen :)
