### ISSUE TITLE
Simplify access to GET and POST parameters

### ISSUE THREAD

**Issue by jenssegers** [slimphp/Slim#1114]
With the current implementation of the Request object, in order to get the GET or POST parameters you need to do:

```
$get = $request->getQueryParams();
$value = $get[’key'];
```

and

```
$post = $request->getParsedBody();
$value = $post['key'];
```

For route parameters it's a bit easier with the `getAttribute('key')` method. I am a big fan of the `input` and `all` methods that Laravel uses. The `input('key')` method searches in both GET and POST, so it's really easy to allow both GET and POST requests to a single route.

**Comment by JoeBengalen** [comment]
Request is following the PSR standard.

**Comment by codeguy** [comment]
I do think an additional method making this process easier would be nice. I don't want to use the `getAttributes()` method from the PSR7 interface though. I'll toss something together soon.

**Comment by codeguy** [comment]
# Proposal

Addition of these methods:
- withParameter($key, $value); // Replaces existing values for $key
- withAddedParameter($key, $value); // Merges into existing values for $key
- withoutParameter($key); // Removes existing values for $key
- getParameter($key);

I imagine POST data will take priority over GET data. There will be issues if a given key is duplicated in GET and POST data sets. Should we assume one value takes priority? Or should we merge both values into an array for the same key?

**Comment by codeguy** [comment]
The proposed `getParameter($key)` method would request the parsed body if the body has not already been parsed. This method must also inspect the _type_ of the parsed body result, because the parsed body can be an array, an object, or null.

**Comment by akrabat** [comment]
POST should take priority over GET for me.

**Comment by codeguy** [comment]
:+1:

**Comment by JoeBengalen** [comment]
Your proposal could some in handy indeed. POST always over GET.

How do you see the function `widthAddedParameter()`? Will you append strings to eachother? Adding an array value to a string value. How would that behaviour be? Just some examples.

**Comment by codeguy** [comment]
@JoeBengalen It mirrors the `withAddedHeader()` method on the Request and Response objects. Internally, each key is an array of values, even if only one value is present. Externally, the `getParameter()` method would return the single value or the complete array of values if more than one value is present.

**Comment by JoeBengalen** [comment]
Clear. Would be a nice addition then ;)

**Comment by codeguy** [comment]
After some thought, the `with*` methods above are unnecessary since parameter access is driven purely from query parameters and body parameters, both  of which are already overridable. I've added the `getParameter($key)` method. Please review.

https://github.com/slimphp/Slim/commit/b32ce17609edbf5b69269c62936730228e26eaf9

**Comment by jenssegers** [comment]
I agree that the `with` methods are unnecessary. One other suggestions would be to also add a `getParameters()` method that returns the merged version of GET and POST.

**Comment by codeguy** [comment]
Done.
