### ISSUE TITLE
getContentType() function needs more check for PUT Requests

### ISSUE THREAD

**Issue by silentworks** [slimphp/Slim#112]
I am unable to pass PUT requests from Backbone.js to Slim by using Slim::request()->put(); I looked at the getContentType() function and it doesn't have any way of checking for correct content type. The content type being passed is "application/json; charset=UTF-8"; I changed it to look like this on line 266:

<pre>
public function getContentType() {
        if ( !isset($this->contentType) ) {
            $header = explode(';', $this->headers('CONTENT_TYPE'));
            $real_header = $header[0];
            $this->contentType = is_null($real_header) ? 'application/x-www-form-urlencoded' : $real_header;
        }
        return $this->contentType;
}
</pre>

I also added in line 335:

<pre>
if ( $this->getContentType() === 'application/x-www-form-urlencoded' || $this->getContentType() === 'application/json' ) {
</pre>

Although Backbone.js has backward compatibility to support "application/x-www-form-urlencoded", it is still good to have "application/json" for future implimentations.

**Comment by codeguy** [comment]
Thanks. I'll apply this fix to the dev branch before merging it into master this weekend.

**Comment by codeguy** [comment]
Is this what caused the empty Slim::request()->put() issue you tweeted about? Or is that a separate issue?

**Comment by silentworks** [comment]
Yeah its all the same issue, even with the fix the results seem wrong. If i call Slim::request()->put() without a param passed to put() I seem to get the returned array as [values] => key, where I think that should be the other way around. I found that the problem is the way how parse_str works, its fine for the old "application/x-www-form-urlencoded" but not for "application/json". so I changed the function to look like this:

<pre>
protected function loadPutParameters() {
        if ( $this->getContentType() === 'application/x-www-form-urlencoded' ) {
            $input = is_string($this->body) ? $this->body : '';
            if ( function_exists('mb_parse_str') ) {
                mb_parse_str($input, $output);
            } else {
                parse_str($input, $output);
            }
            return $output;
        } elseif ( $this->getContentType() === 'application/json' ) {
            $input = is_string($this->body) ? $this->body : '';
            $output = array('body' => $input);
            return $output;
        } else {
            return array();
        }
 }
</pre>

**Comment by codeguy** [comment]
Ah I see. I don't want to special-case _every_ potential content-type in loadPutParameters... if your Request content-type is "application/json" or "application/xml" or "application/whatever", the raw request body will be available in `Slim::request()->getBody()`. Your application may then parse the Request body as is needed by your application. A future version may better support this scenario. For now, it's up to you to parse the Request body for non-urlencoded content types.

**Comment by codeguy** [comment]
Content-type parsing fixed and pushed to the develop branch (soon to become master in an hour or so).

https://github.com/codeguy/Slim/commit/ecda898fee67bb190b291dea772c90cbff8c470a

**Comment by codeguy** [comment]
I'm opening a new Issue to natively support JSON and XML content-type parsing just like I do already for url-encoded requests.

**Comment by silentworks** [comment]
Ok that makes sense, could you note this in the documentation for future versions. Because it is not clearly stated others could end up trying to do the same as I did. Also for future version implimentation take a look at Phil Sturgeon Rest Lib for Codeigniter https://github.com/philsturgeon/codeigniter-restserver/blob/master/application/libraries/REST_Controller.php, It might be of use.

**Comment by codeguy** [comment]
I agree. This is not noted in the docs. I'll make a note of it, and I've pushed the native JSON and XML request support to the top of the Issue Tracker. Thanks!
