### ISSUE TITLE
[Discussion] PSR-7 and Middlewares 

### ISSUE THREAD

**Issue by harikt** [slimphp/Slim#1122]
Hi ,

I have been thinking about Middleware and how we can make use of a middleware on every PSR-7 based frameworks.

I think @mwop also have a similar thought, ie why he have mentioned we will create a group once the PSR-7 is passed.
# Goals / Ideas
- Middleware should be self contained
- It can be reused on any frameworks, so we don't need to re-invent same things

This brings to another problem how the route is added / configured. So the middleware can have another router middleware .

So I am wondering whether routing can be moving to a Middleware , and only a base static route is needed.

This helps users who are building middleware to require the route middleware and add the routes to it.

Think about a blog middleware. How we could make a middleware with less coupling with framework like adding a route with `$app->get` , but with `$router->methods` . This is why I was thinking. Interested to discuss if you like. I know we can make this with Slim now also, but I wonder whether this will get tightly coupled to framework routing.

Thanks!

**Comment by harikt** [comment]
/ cc @weierophinney .

**Comment by joostshao** [comment]
https://groups.google.com/forum/#!msg/php-fig/42WhFKJzgrQ/9YbhKdLEOp4J

PHP Framework Interoperability Group ›
[CANCEL VOTE] PSR-7: HTTP Message Interface

**Comment by weierophinney** [comment]
@joostshao We've canceled to make clarifications; the program is far from dead.
