### ISSUE TITLE
removing set_error_handler from App::run()

### ISSUE THREAD

**Issue by JoeBengalen** [slimphp/Slim#1128]
What is the reason the `set_error_handler` and `restore_error_handler` are used in the `App->run()`?

I agree they are useful, but I want to use them more globally, not only within that method.

I know I can just put a second error handler more globally, but duplicating that code may not be the most ideal situation. Also if I want to handle errors differently, it is not possible in the current code. Not without extending the App class and overwriting the whole run method.

Also handling those errors is not really a task of the framework anyway I think.

If you do not want to remove it, at least make it configurable whether to use the error handler or not.

Opinions?

**Comment by opengeek** [comment]
:+1: I definitely would prefer to have optional error handler registration and the ability to avoid it altogether.

**Comment by codeguy** [comment]
Sounds good. I'll make it optional and injectable via Pimple. Or if anyone can jump on this today (I can't get to it til tomorrow) that'd be fine, too.

**Comment by piotr-cz** [comment]
So what is the recommended place to set the error handler?

I'd like to catch the _Catchable fatal error_ now which is not being catched by _errorHandler_ defined in container because it's not an exception but error.

**Comment by piotr-cz** [comment]
Okay, I've added _NativeErrorHandler_ middleware, but cannot add the `restore_error_handler` function there.
Nevertheless the _errorHandler_ registered in container should be called _exceptionHandler_
