### ISSUE TITLE
the url localhost/hello/asd shows ,but localhost/hello/asd/ shows 404

### ISSUE THREAD

**Issue by qiukeren** [slimphp/Slim#1129]
the framework is really good,
but here is a small problem:
the localhost/hello/asd shows "Hello, asd" normally ,
but localhost/hello/asd/ (with a slash ) shows 404 ,
Is there any need of doing something solve this ...

**Comment by explorewp** [comment]
have you added slash at the end of the route?

$app->get('/hello/asd/', function ($name) {
    echo "Hello, asd";
});

**Comment by explorewp** [comment]
Have you added slash at the end of the route?

```
$app->get('/hello/:name/', function ($name) { //there is slash at the end
    echo "Hello, $name";
});
```

you need to add it if you want to do http://localhost/hello/asd/ (with slash)

**Comment by harikt** [comment]
`localhost/hello/asd` and `localhost/hello/asd/` are different. So is an expected behavior .

**Comment by qiukeren** [comment]
I did not added slash..
OK,Now it is truely a expected behavior..
