### ISSUE TITLE
Issues with grouped routing containing '/' in v3

### ISSUE THREAD

**Issue by jenssegers** [slimphp/Slim#1130]
For an API application I have routes similar to this:

```
$app->group('/1.0', function () use ($app) {
    $app->group('/users/{userId:[0-9]+}/property', function () use ($app) {
        $app->get('/', '...');
        $app->get('/{propertyId:[0-9]+}', '...');
        $app->post('/', '...');
        $app->put('/{propertyId:[0-9]+}', '...');
        $app->delete('/{propertyId:[0-9]+}', '...');
    });
});
```

But using `'/'` as a route pattern inside a group doesn't seem to be working. If I replace it with just an empty string `''` it works.

**Comment by codeguy** [comment]
Thanks for the helpful info. Will look into this.

**Comment by jenssegers** [comment]
Probably because the pattern is registered as `/1.0/users/123/property/` which is not picked up for `/1.0/users/123/property`.

**Comment by codeguy** [comment]
Your PR assumes routes with trailing slashes are equal to the same route without a trailing slash. I'm not sure they are. @gmanricks What's your take on this?

**Comment by codeguy** [comment]
Bringing in @funkatron too

**Comment by tuupola** [comment]
For me routes `/foo` and `/foo/`are not the same.

**Comment by akrabat** [comment]
Personally, I think that `/user` and `/user/` are different.

**Comment by jenssegers** [comment]
I'm used to working with Laravel/Symfony, which handles both of them in the same way.

**Comment by geggleto** [comment]
RFC 3986 attempts to address this issue.
Reference: https://www.ietf.org/rfc/rfc3986.txt

```
6.2.4.  Protocol-Based Normalization
if they observe that a URI such as
      http://example.com/data
redirects to a URI differing only in the trailing slash
      http://example.com/data/
they will likely regard the two as equivalent in the future. .
```

Reference: http://en.wikipedia.org/wiki/URL_normalization

```
Adding trailing / Directories[clarify] are indicated with a trailing slash and should be included in URLs. Example: http://www.example.com/alice → http://www.example.com/alice/
However, there is no way to know if a URL path component represents a directory or not. RFC 3986 notes that if the former URL redirects to the latter URL, then that is an indication that they are equivalent.
```

Probably should be the same, but it doesn't sit well with me. For Example

```
/account
This route renders a "My Account" web-page and
/account/
This route is a API end-point for getting an AJAX request with all of the details for My Account.
```

**Comment by harikt** [comment]
I agree with @akrabat . There was also a discussion over https://github.com/auraphp/Aura.Router/pull/4

**Comment by funkatron** [comment]
I believe they should not, by default, be considered equivalent. 

Flask handles it like this:

Route: "/foo": `/foo` works. `/foo/` returns 404
Route: "/foo/": `/foo/` works. `/foo` redirects to `/foo/` (rewriting the URL) if no other match exists.

They're different things in HTTP, and I think they should be different things here. _Maybe_ offer Flask-style auto-resolution in optional middleware.
