### ISSUE TITLE
[discussion] return response instead of echoing them

### ISSUE THREAD

**Issue by endel** [slimphp/Slim#1133]
Slim currently only supports echoing strings to the response:

``` php
$app->get('/hello/{name}', function ($request, $response, $args) {
    echo "Hello, " . $args['name'];
});
```

It would be nice to allow returning any data type, and let the middleware to transform it as it needs to.

**Example:**

``` php
$app->get('/hello/{name}', function ($request, $response, $args) {
    return array( 'success' => true );
});
```

In this example it would be needed to use a middleware to encode the array for the response body.

**Example of middleware handling the response**

``` php
class ResponseTypeMiddleware extends Slim\Middleware
{
    public function call()
    {
        $response = $this->next->call():
        $this->app->response->headers->set('Content-type',  'application/json');
        $this->app->response->setBody(json_encode($response));
    }
}
```

What are your thoughts about it?

**Comment by codeguy** [comment]
Slim 3.x supports returning an `Psr\Http\Message\ResponseInterface` instance from route callbacks. Slim 3.x _also_ supports `echo`ing output from route callbacks, too, for legacy compat.

**Comment by endel** [comment]
@codeguy nice! I didn't know about that. Thanks :)

**Comment by codeguy** [comment]
Yep. The current master branch (2.x) is feature frozen and is only accepting security fixes. The current develop branch (to become 3.x) is where all current development is happening.
