### ISSUE TITLE
2.6.2 reports version 2.6.1

### ISSUE THREAD

**Issue by skywaymsn** [slimphp/Slim#1135]
--- a/Slim/Slim.php
+++ b/Slim/Slim.php
@@ -6,7 +6,7 @@
- @copyright   2011 Josh Lockhart
- @link        http://www.slimframework.com
- @license     http://www.slimframework.com/license
  - \* @version     2.4.2
  - \* @version     2.6.1
- @package     Slim
  *
- MIT LICENSE
  @@ -54,7 +54,7 @@ class Slim
   /**
  - @const string
    */
    -    const VERSION = '2.4.2';
    -    const VERSION = '2.6.1';
    
    /**

**Comment by codeguy** [comment]
v2.6.3 corrects this
