### ISSUE TITLE
Does not work (at all) with Quercus

### ISSUE THREAD

**Issue by perlun** [slimphp/Slim#114]
Hi!

I discovered your framework tonight, and gave it a try. It didn't work very well with the PHP server I'm using, which happens to be the Quercus PHP5 interpreter (which is a Java-implementation of the PHP language, allowing PHP applications to be run in e.g. Tomcat).

The error I'm getting is this:

C:\Program Files (x86)\LSODevServer-9.1.2\apache-tomcat-6.0.18\webapps\slim\Slim\Slim.php:606: Fatal Error: Method call 'error' is not allowed for a null value. 

Both the development and the stable versions give similar errors. (This is from the "development" zip, https://download.github.com/codeguy-Slim-1.2.9-71-gecda898.zip

I tried adding a bunch of "if ($stuff != null)" around a bunch of calls, but the only thing I got back (from the default index.php page) was a blank page.... It would be nice if this could be fixed, so that those of us running PHP this way can also use Slim.

**Comment by codeguy** [comment]
I'll take a look, but this could be any number of things. I've never heard of Quercus before. I admit this isn't going to be a huge priority because it will be extremely difficult for me to troubleshoot without an actual Quercus environment to use.

Is it at all possible for you to setup and give me access to a virtual host using your Quercus interpreter?

**Comment by perlun** [comment]
Hi,

I fully understand "blind" debugging this will be kind of meaningless...
Unfortunately, I'm running this on my laptop so providing a VM access is a
bit hard. But, you should be able to do this pretty easily:

1) Get the Quercus framework is available from http://quercus.caucho.com/.
Version 4.0.11 is the one I'm using.
2) Get the Tomcat installation from
http://tomcat.apache.org/download-60.cgi. I don't know if you are on
Windows or Unix? If on Windows, this should be pretty easy to get going,
provided you have a JVM.

Once the Tomcat is running, just drop the Quercus .war file in the webapps/
folder of Tomcat. This will create a http://localhost:8080/quercus or
similar application, in which you can run .php files without any
modifications. Bigger applications like Wordpress are supported, so I guess
the level of PHP compatibility is pretty high. But, obviously it isn't
100%... I guess.

Please, check it ouf it you have some time. Thanks!

Best regards,
Per Lundberg

-----Original Message-----
From: codeguy
[mailto:reply+i-707227-cc24352cb36758767049503a2df6f7fb5f21d178@reply.githu
b.com] 
Sent: den 27 mars 2011 00:06
To: Lundberg, Per
Subject: Re: [GitHub] Does not work (at all) with Quercus [codeguy/Slim
GH-114]

I'll take a look, but this could be any number of things. I've never heard
of Quercus before. I admit this isn't going to be a huge priority because
it will be extremely difficult for me to troubleshoot without an actual
Quercus environment to use.

Is it at all possible for you to setup and give me access to a virtual host
using your Quercus interpreter?

## 

Reply to this email directly or view it on GitHub:
https://github.com/codeguy/Slim/issues/114#comment_921339

**Comment by MatthewCallis** [comment]
@prelun do you have Resin installed? Did you convert the .htaccess to Resin dispatch?

```
<web-app xmlns="http://caucho.com/ns/resin" xmlns:resin="urn:java:com.caucho.resin">
    <resin:Dispatch>
        <resin:IfFileExists/>
    </resin:Dispatch>
    <resin:Forward regexp="^" target='/index.php'/>
</web-app>
```

**Comment by codeguy** [comment]
@perlun I use a Macbook with OS X 10.6.7 and MAMP Pro. I don't plan on installing Java and Tomcat just for testing an obscure web server. I don't mean to be dismissive at all. It's just not something I am going to do on my dev machine. I'm honestly not familiar enough with Java and Tomcat to build a VM from scratch, either.

If someone else is willing to tackle this, that's great. But it's not something I can do.

**Comment by perlun** [comment]
Fine by me. I _might_ actually be able to get a VM for you, where we could
debug this, but it will mean a little work. I'll get back to you if/when
this gets possible. Put the issue on hold for now.

Best regards,
Per 

-----Original Message-----
From: codeguy
[mailto:reply+i-707227-cc24352cb36758767049503a2df6f7fb5f21d178@reply.githu
b.com] 
Sent: den 27 mars 2011 23:12
To: Lundberg, Per
Subject: Re: [GitHub] Does not work (at all) with Quercus [codeguy/Slim
GH-114]

@perlun I use a Macbook with OS X 10.6.7 and MAMP Pro. I don't plan on
installing Java and Tomcat just for testing an obscure web server. I don't
mean to be dismissive at all. It's just not something I am going to do on
my dev machine. I'm honestly not familiar enough with Java and Tomcat to
build a VM from scratch, either.

If someone else is willing to tackle this, that's great. But it's not
something I can do.

## 

Reply to this email directly or view it on GitHub:
https://github.com/codeguy/Slim/issues/114#comment_923635

**Comment by codeguy** [comment]
Sounds good. On hold for now.

**Comment by codeguy** [comment]
Closing this out as I don't think it's an issue with the framework. But if you want to send a pull request to enable Quercus compatibility, I'll be happy to pull it in.
