### ISSUE TITLE
Content in "group" gets applied to all other routes

### ISSUE THREAD

**Issue by misilot** [slimphp/Slim#1147]
For example:

``` php
<?php
$app->group('/json', function () use ($app, $settings) {
  $app->contentType('application/json');

    $app->get('/test/:start/:end', function ($start,$end) use ($app) {
      $val = array('start'=> $start, 'end'=> $end);
      echo json_encode($val);
    });
});
```

the contentType gets applied to all routes even outside of /json/*

**Comment by geggleto** [comment]
I think this is actually a mis-use of the contentType. You should only use this when you know the route is going to output that type of content. I realize it might seem logical to group items that have the same content and in such a case you can use a route that passes control rather than a group.

Example: Not entire sure if this is 100% working code

```
$app->get('/json/:optional+', function () use ($app) {
    $app->contentType('application/json');
    $app->pass();
});
```

**Comment by misilot** [comment]
Thanks @geggleto that may work. It just seems like $app->group would define a scope in the code, which it clearly doesn't.

We were trying to define a route/group "/json" where that is all it was going to output was json.

The other place I have seen, is trying to add authentication via adding it to $app->group() inadvertently adds authentication to all routes.

Thanks

**Comment by geggleto** [comment]
You could also add a route middleware for this possibly as well.

**Comment by misilot** [comment]
Doesn't route middleware apply to all routes?

**Comment by geggleto** [comment]
in 2.x there are 2 different types... Route Middleware and Just Middleware.

Route Middleware is excellent for auth I have found. See below.

```
    public function isAuthed() {
        return function () {
            $user = self::get('user');

            if (!isset($user)) {
                $this->rejectAccess("Login Required");
            }
        };
    }

I use this in Routes like so:
$app->group('/games', $app->session->isAuthed(), function () use ($app) {
});
```

You can probably do a similar thing.

```

public function setContentType($type = 'application/json') {
        return function () use ($type) {
            $app = \Slim\Slim::getInstance();
            $app->contentType($type);
        };

}

$app->group('/json', $object->setContentType('application/json'), function () {
    //Your Stuff
});

```

**Comment by codeguy** [comment]
Closing. This is a moot issue in v3. Version 2.x is what it is. Please move any further discussion to the support forums.
