### ISSUE TITLE
Branch names

### ISSUE THREAD

**Issue by harikt** [slimphp/Slim#1151]
Hi Josh, 

I could not comment on http://www.slimframework.com/2015/02/11/whats-up-with-version-3.html 

I have a different thought of the change in name.

> The current master branch will be renamed to legacy-2.x (or something similar), and the current develop branch will be renamed to master. 

What about changing it to 2.x , 3.x ?

If you do so, we don't need to add an extra branch alias. 

This helps to make use of `2.*@dev`, `3.*@dev` in composer. And you can also remove master if you don't like.

Thoughts ?

**Comment by codeguy** [comment]
:+1:

**Comment by r3wt** [comment]
I think this approach would be optimal

**Comment by piotr-cz** [comment]
This concept is also great for future (4.x and so)

**Comment by akrabat** [comment]
Done.

**Comment by harikt** [comment]
Thank you @akrabat .

**Comment by lalop** [comment]
Shouldn't master branch be an alias to the more stable and up to date branch ?

**Comment by piotr-cz** [comment]
@lalop Usually you have to choose between _more stable_ and _up to date_

**Comment by lalop** [comment]
@piotr-cz since the more stable is the stable one with the biggest version number yes
