### ISSUE TITLE
Encoded URL returns 404 Not Found

### ISSUE THREAD

**Issue by AIR20** [slimphp/Slim#1154]
The URL `http://localhost/~adam/srs/`works as expected, while encoded form `http://localhost/%7Eadam/srs/` returns 404 Not Found in Safari.

Decode `REQUEST_URI` in [Line 131, environment.php](https://github.com/slimphp/Slim/blob/master/Slim/Environment.php#L131) fixed the problem for me. 

``` php
$requestUri = rawurldecode($_SERVER['REQUEST_URI']);
```

**Comment by silentworks** [comment]
This is no longer an issue in develop branch (Slim 3) so will be closing this one out.
