### ISSUE TITLE
Update PSR-7 compat

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#1160]
See latest PSR changes here:

https://github.com/php-fig/fig-standards/commit/609919a79b2e4ee7a6700932981d2eea729e2265

**Comment by alexantr** [comment]
PSR-7: vote cancelled
https://groups.google.com/forum/#!msg/php-fig/42WhFKJzgrQ/9YbhKdLEOp4J

**Comment by akrabat** [comment]
@alexantr The issues have now been sorted, so it's back in Review stage now: https://groups.google.com/forum/#!topic/php-fig/0lwqRXm94Ik
