### ISSUE TITLE
Middleware don't have method to replace response body?

### ISSUE THREAD

**Issue by nhymxu** [slimphp/Slim#1161]
I see slim v2 have method to overwrite response body (need for compress output, minify string, ...)
but v3 only append method ?

**Comment by lalop** [comment]
Hello,
You can overwrite the body via the withBody method https://github.com/slimphp/Slim/blob/develop/Slim/Http/Response.php#L472

**Comment by codeguy** [comment]
There will be more docs about this very soon.
