### ISSUE TITLE
Adjustable Configuration

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1165]
Hello,

I just noticed that in Slim there is a constant that I would likely want to change in production.

I get that most of the time 1024 is enough, for most but not likely for all.
Surfacing this would be nice or even just return the whole stream if available.

Slim:run() 413->421

```
                $body = $response->getBody();
                if ($body->isAttached()) {
                    $body->rewind();
                    while (!$body->eof()) {
                        echo $body->read(1024);
                    }
                }
```

Thoughts ?

**Comment by codeguy** [comment]
Seems like a good candidate for an application setting. Want to send a PR?

**Comment by geggleto** [comment]
Will Do
