### ISSUE TITLE
Smarty in 3.0

### ISSUE THREAD

**Issue by HomaEEE** [slimphp/Slim#1168]
Please integrate Smarty fot template in Slim 3.0

**Comment by harikt** [comment]
This is why I have made a common api earlier  https://github.com/cocoframework/Cocoframework.Renderer . It can render smarty, twig, aura/view, plates or even mustache.

**Comment by dopesong** [comment]
You can use for Slim view whatever you want and extend it by yourself. You can look to this example to see how to extend it: https://github.com/slimphp/Twig-View/blob/master/src/Twig.php

**Comment by silentworks** [comment]
I would suggest making a smarty view for Slim and use that instead. I think we will only officially maintain the Twig view at the moment as none of us constantly use Smarty in order to keep the view up to date or know the best way of working with it.

**Comment by nunocodex** [comment]
I don't have any knowledge with Smarty but I think is easy to integrate with service provider, for a moment i working only with twig (smarty i think is the bad version of twig) but after complete my base project i can develop a simple service provider for smarty. I think you can check the old version (I think one or more developer already release a smarty service provider) and the update is more easy. If you have the old smarty service provider you can link and i try to help you for porting to slim3.

**Comment by silentworks** [comment]
@namaless you can find it here https://github.com/slimphp/Slim-Views.
