### ISSUE TITLE
Session does not work when using no session handler

### ISSUE THREAD

**Issue by phaseinducer** [slimphp/Slim#117]
In my config i set session.handler to null. Then when i use $_SESSION in my routes it seems that session data is not retrieved.
Maybe a session id problem?

I use the last version (1.3.1).

**Comment by codeguy** [comment]
I can confirm that this works as expected. If you set the `session.handler` setting to `null`, it will use the session handler as specified in your php.ini file. Make sure that you are not calling `die()` or `exit()` within a route callback. Does `$_SESSION` work as expected from a normal non-Slim PHP file?

**Comment by phaseinducer** [comment]
Yes it does.
If it can help you the only solutions i found for the moment is :
- to call `session_start()` just before `Slim::init()`, but i don't think it's a good solution.
- to replace `session_regenerate_id(true)` by `session_regenerate_id()` (l. 369 in Slim.php). That's why i think the problem comes from the session id.

**Comment by codeguy** [comment]
Thanks for the additional information. What environment are you running? I'll investigate this further tonight.

**Comment by phaseinducer** [comment]
I'm running a WAMP server with PHP 5.3.1.

More information : the problem occurs when your page calls non existing resources (eg images). Since they don't match the htaccess condition the controller and so `Slim::init()` is called several times.

And I have the following error message in my log file :
    Message: session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed | File: C:\Users\Yohan\Documents\NetBeansProjects\unjeuneunpro\Slim\Slim.php | Line: 369 | Level: 2

**Comment by codeguy** [comment]
I think the issue is caused by too many simultaneous requests and Slim is trying to issue a new session ID per request to prevent session fixation attacks. I think issuing a new ID per request is a good thing, but perhaps not good for certain circumstances like this. I will add a new application setting called `session.regenerate` in a hotfix tonight which will let you enable/disable session ID regeneration.

**Comment by phaseinducer** [comment]
Good idea, thanks!

**Comment by codeguy** [comment]
After further testing on my end, there are a lot of issues with session id regeneration in 1.3.1 especially if there are many ajax or asset requests. For now I've removed session id regeneration in 1.3.2. I'll revisit in the future, but for now for the sake of stability I've removed that one feature.
