### ISSUE TITLE
Performance Increases

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1170]
With the release of lumen, I did some bench marking. Full results are here: http://104.236.58.25/

Benchmarks tldr;
Digital Ocean $5 Droplet [Centos 6.5] [PHP 5.6.7]
All tests were done with ab -t 60 -c 5 
[627.89 req/s] Lumen
[579.61 req/s] Slim 2.6.2
[376.28 req/s] Slim 3.x - develop

Now given that Lumen has a much larger diskspace footprint than Slim, I cannot see why it would also have more throughput. All 3 have composer utilized, granted the Lumen documents recommend installing with optimized autoloader. 

I think improving slims performance is important. Largely it is one of the main reasons why I use it for my REST APIs. I saw @codeguy mentioning some things on IRC and I think this discussion would be worth while for some of the Slim users here.

**Comment by r3wt** [comment]
@geggleto Have you tried a benchmark on HHVM in repo authorative mode? Slim 2.6.2 offers much higher throughput on HHVM once compiled.

**Comment by geggleto** [comment]
@r3wt No, I don't use HHVM in production. I know someone else has benchmarked it, was hoping to get some people to upload their results.

**Comment by StJudeWasHere** [comment]
@geggleto thanks for sharing the benchmarks.

Slim's loc went from _13400_ in version 2.6.2 to _121292_ in version 3.0, but it turns out most of that loc increase is due to the require-dev packages.

Install the dependencies with the `--no-dev` flag and 3.0 is only [12651 loc](http://pastebin.com/7f3Mc4kR) which is amazing. That simplicity is what I appreciate the most of Slim, kudos to everyone making this framework possible.

**Comment by sclearion** [comment]
actually it's 7731 loc --no-dev for Slim (I don't think it's fair to count comments). Also if Lumen is faster then I wonder if the composite/extraneous packages are a contributing factor. If they are then it would be misleading to conclude that Lumen itself is faster than Slim. I too am curious about the throughput of Lumen. That being said I love Slim because it is a scalpel and it allows me to stick to true engineering of PHP components rather than being handed a toolbox. The better I got at PHP the more I appreciate tools like Slim. Keep up the great work team and thanks to all the contributors.

**Comment by r3wt** [comment]
@sclearion yes lumen clearly has very few features in comparison to slim.

**Comment by lalop** [comment]
@r3wt Lumen has less features than Slim ?
How is that possible ?
At the first look Lumen seems to provide more features, am I wrong ?

**Comment by nhymxu** [comment]
I see Lumen composer.json
It's using tons of package from laravel (illuminate).
Lumen provide more features than Slim, And I think Lumen can using Laravel package (packalyst)

Why lumen using more but faster than slim?

**Comment by geggleto** [comment]
They are all disabled ;)

**Comment by geggleto** [comment]
Also the core of lumen is in the lumen kernel which is a composer dependency

**Comment by nhymxu** [comment]
without using this, I think core feautures of lumen same as slim v3.

**Comment by codeguy** [comment]
Performance gap will close closer to launch.

**Comment by geggleto** [comment]
Update as of this morning:
http://104.236.58.25/

Results

Note: All tests were done with ab -t 60 -c 5 
[627.89 req/s] Lumen Results
[579.61 req/s] Slim 2.6.2 Results
[488.95 req/s] Slim 3.x - develop **
[376.28 req/s] Slim 3.x - develop *

Note: These tests were done with siege using: siege -c 5 -t 30S -b 
[420.65 req/s] Slim 2 
[411.56 req/s] Slim-Dev *\* 
[392.18 req/s] Lumen 
[262.99 req/s] Slim-Dev \*

**Comment by geggleto** [comment]
http://104.236.58.25/xhprof/xhprof_html/index.php?run=552fdb96a5eee&source=myapp

Xhprof of current dev branch.

**Comment by geggleto** [comment]
http://stats.slimframework.com/
:+1:  Also great work completed on Slim today!

**Comment by nhymxu** [comment]
Hope slim not only micro-framework to build API server, hope slim can add multi middleware/component to full-stack framework if need <3

**Comment by tuupola** [comment]
@geggleto Good job! In the stats page it would be good idea to also mention how composer was run. Ie did you have `--no-dev`and `--optimize-autoloaded`switches. They make a world of difference. There is already much confusion about this.

**Comment by geggleto** [comment]
I will post the config files I think, But yeah --no-dev and optimize-autoload are used.

**Comment by pemedina** [comment]
This is what i get in an azure instance running apache 2.4.7 / PHP 5.6.7

Siege
siege -c 5 -t 30S -b http://localhost/lumen/public/abc  
Transaction rate:         344.74 trans/sec

siege -c 5 -t 30S -b http://localhost/slim/public/abc
Transaction rate:         433.96 trans/sec

ApacheBench
ab -t 60 -c 5  http://localhost/lumen/public/abc
Requests per second:    388.85 [#/sec](mean)

ab -H "Connection: close" -t 60 -c 5 http://localhost/slim/public/abc
Requests per second:    478.52 [#/sec](mean)

I've ran these tests many times each and the results are consistent. Slim 3 is always faster.  Both urls are public:

http://thesysadmin.cloudapp.net/slim/public/abc
http://thesysadmin.cloudapp.net/lumen/public/abc

Not sure if i'm doing something wrong. The "Connection: close" header has to be added to make ab work. This was discussed long time ago: http://help.slimframework.com/discussions/problems/24-high-loading-times-in-apache-bench. 

Not sure if i'm doing something wrong but, slim3 is _always_ faster?

**Comment by codeguy** [comment]
For reference http://seancoates.com/blogs/http-1-and-the-connection-header

**Comment by codeguy** [comment]
Closing this out.
