### ISSUE TITLE
Rename configuration name templates_dir to templates.path

### ISSUE THREAD

**Issue by jrivero** [slimphp/Slim#118]
I think the variable name templates_dir is incorrect because the others use a clearly identifiable pattern that uses the dot.

My suggestion is: "templates.path"

Other similar configuration names found:
- cookies.path
- log.path

**Comment by codeguy** [comment]
Yeah I agree. "templates_dir" is a vestige from 1.0.

**Comment by jrivero** [comment]
I Know :)

failed other names that do not like me too... examples:

on view object, the methods setData and appendData: may set or append anything other than "data"? is redundant, do not you think?

**Comment by codeguy** [comment]
Yep. Can certainly be trimmed down. Want to open another issue for that?

**Comment by jrivero** [comment]
ok

**Comment by codeguy** [comment]
I have renamed "templates_dir" to "templates.path" in 1.3.2

**Comment by jrivero** [comment]
Thanks!
