### ISSUE TITLE
is output buffering disabled in version3?

### ISSUE THREAD

**Issue by omarkhd** [slimphp/Slim#1189]
The example you have in the main page, does not work. You can echo something in a route, but then you got a Fatal error because the route is not returning the response. And to display something, you have to call the write method. Is this how it is supposed to work?

**Comment by geggleto** [comment]
It is currently how it works, there are talks about re-enabling output buffering support.

**Comment by omarkhd** [comment]
If you decide to re-enable it, I'd be glad to help.

**Comment by akrabat** [comment]
Fixed in #1206.
