### ISSUE TITLE
Trim down "Data" word of methods of view class

### ISSUE THREAD

**Issue by jrivero** [slimphp/Slim#119]
- "setData" to "set"
- "appendData" to "append"

**Comment by codeguy** [comment]
Oh I thought you were saying that `setData` and `appendData` were synonymous and therefore redundant. I'd like to keep the "Data" suffix on the method names just in case I need to add additional setters and getters in the future.

**Comment by jrivero** [comment]
he he he... I feel good, no problem

on this new topic (synonymous) I will say that I like to have a set and append, the latter do not normally use, but I like that there
