### ISSUE TITLE
just a comment/question

### ISSUE THREAD

**Issue by pine3ree** [slimphp/Slim#1191]
Hi @codeguy ,

is there any particular reason for using is_array|is_string(..) === true|false inside if control-structures? Aren't is_array, is_string....php functions already returning booleans? I generally use the identity operator for strict type checking.

kindly

**Comment by silentworks** [comment]
This might have been of the overly cautious nature of @codeguy at the time of writing that bit of code. I don't think there is any particular reason for it, but it doesn't hurt I guess.
