### ISSUE TITLE
URL encoding issue in router parameters?

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#1192]
For this index.php:

``` php
<?php
require 'vendor/autoload.php';

$app = new \Slim\App();

$app->get('/hello/{name}', function($request, $response, $args) use ($app) {
    return $response->write("Hello {$args['name']}");
})

$app->run();
```

When I try the URL: `http://localhost:8080/hello/Rob!`

I get the output:

```
Hello Rob%21
```

I was expecting:

```
Hello Rob!
```

Is this expected behaviour?

**Comment by codeguy** [comment]
No. We want those URL-decoded by the time we inject them into the route callback.
