### ISSUE TITLE
Accessing parsedArgs in route middleware?

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#1193]
I see that `Route::run()`sets `$this->parsedArgs`, but how do I access this from route middleware?

For clarification, I'm looking at how I could add route middleware that sanitised the route's named parameters which doesn't appear possible.  Should it be?

**Comment by akrabat** [comment]
Thinking aloud here, but I think that the route middleware should have access to the `Route` object and its `parsedArgs` property.

The most obvious way to to do this is to change `Route::add()` so that we do `$callable->bindTo($this)` rather than `$callable->bindTo($this->container)`. This means that the route middleware would have to access the container some other way such as `use ($app)` when defining it.

We should also make `$parsedArgs` public so that the route middleware can manipulate them before they are passed to the action callable.

Thoughts?

**Comment by codeguy** [comment]
Binding to the route makes sense, but the difference from app middleware should be well documented to avoid confusion.

**Comment by akrabat** [comment]
Hmm... My ideas here solve the problem for a closure, but not if we get the route middleware via the `CallableResolver`. More thinking required.

**Comment by mnapoli** [comment]
Those args should maybe be in the request? After all they describe the request done by the client, I don't see how they are different from query parameters or POST data.

By the way I think that's how it's done in Symfony.

**Comment by akrabat** [comment]
@mnapoli This is the conclusion that I'm coming to. 

We don't find out what they are until `Route::run()` is called, but we could then put them into the Request object, which would make them available to the route middleware. They would then be accessible in the action callable via $request or via the $args parameter.

**Comment by akrabat** [comment]
Doh! They are already there!

`$request->getAttributes()` and `$request->getAttribute($name, $default = null)` have the data already populated…

**Comment by mnapoli** [comment]
:+1: good to know!

**Comment by akrabat** [comment]
Though, if some route middleware does sanitise the request's arguments, then the action's `$args` parameter to the isn't updated, so the action callable must use `$request->getAttributes()` and ignore `$args`...

**Comment by akrabat** [comment]
https://github.com/slimphp/Slim/pull/1196 solves this problem and makes the Request's `attributes` and `$args` consistent at the point of dispatch.
