### ISSUE TITLE
PSR-7 ServerRequestInterface

### ISSUE THREAD

**Issue by pine3ree** [slimphp/Slim#1197]
Hello @codeguy ,

shouldn't Slim\Http\Request be implementing Psr\Http\Message\ServerRequestInterface, instead of 
Psr\Http\Message\RequestInterface?

regards

**Comment by pine3ree** [comment]
Hello @akrabat 
what is your opinion about this?
Also, shouldn't we implement middlewares' __invoke() method and route handler against \Psr\Http\Message\ServerRequestInterface as well?

regards

**Comment by JoeBengalen** [comment]
Already done in my WIP PR ;)

**Comment by pine3ree** [comment]
@JoeBengalen great!
