### ISSUE TITLE
MS SQL PDO Driver Unsupported?

### ISSUE THREAD

**Issue by neoncube2** [slimphp/Slim#1199]
I'm using the 64-bit (I think) MS SQLSRV PDO 5.6 thread-safe driver, but am getting this error from Slim:

```
Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[IMSSP]: This function is not implemented by this driver.' in ...\vendor\slim\slim\Slim\Helper\Set.php:86
Stack trace:
#0 ...\vendor\slim\slim\Slim\Helper\Set.php(86): method_exists(Object(PDO), '__invoke')
#1 ...\vendor\slim\slim\Slim\Slim.php(234): Slim\Helper\Set-&gt;get('conn')
#2 ...\index.php(30): Slim\Slim-&gt;__get('conn')
#3 {main}
  thrown in ...\vendor\slim\slim\Slim\Helper\Set.php on line 86

```

Is this driver supported by Slim?

Thanks :)

**Comment by JoeBengalen** [comment]
As far as I know Slim does not support ANY database driver at all. There is no code included that has anything to do with a database. So I guess you are using some other database package which is throwing the exception. Can you show the initialization code of `conn` and the code where the error occurs?

The error looks like a response from the MS SQL server though (or the PDO driver). Are you calling a method that is not supported by MS SQL?

**Comment by geggleto** [comment]
Slim does not support databases, slim does however catch all exceptions. In this case you can see that there is serving wrong with your database layer as it is throwing a pdoexception

**Comment by harikt** [comment]
@neoncube2 please provide the code also. It seems the method is not in PDO is called.

**Comment by neoncube2** [comment]
Thank you for the feedback, guys :)

God willing, I'll look into this within the next few days and get back to you with more details.

**Comment by skywaymsn** [comment]
We use MSSQL server via FreeTDS.  It requires PHP be built with `--with-mssql=/path/to/freetds`

In order to support this, we maintain a build of FreeTDS that we bring along with PHP when we deploy.  http://www.popmartian.com/tipsntricks/2014/10/20/how-to-build-non-root-freetds-for-linux/

Connect via:
    `$dbh = mssql_connect ($config->dbhost, $config->dbuser, $config->dbpass)`

We actually found it much faster and easier to abstract database queries from the Slim API and instead, have the API reach out to a dedicated SQL gateway.

**Comment by neoncube2** [comment]
Okay, the issue appears to be when I try to access a PDO object through a Slim object.

``` PHP
$app = new \Slim\Slim(array(
    'mode' => 'development',
    'debug' => true,
    'log.enabled' => true,
    'templates.path' => './',
    'cookies.encrypt' => true,
    'cookies.secret_key' => 'CHANGE ME. SERIOUSLY, CHANGE ME RIGHT NOW.',
));

$conn = new PDO('sqlsrv:server =[info here]; Database = [info here]', '[info here]', DB_PASSWORD);
$conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

$app->conn = $conn;

print_r($app->conn); // This dies with the essentially the same error message as the one that I originally posted
```

Doing

``` PHP
print_r($conn);
var_dump($conn)
```

yields this:

```

PDO Object
(
)
object(PDO)#2 (0) {
}
```

**Comment by neoncube2** [comment]
Changing method_exists() to is_callable() in

``` PHP
public function get($key, $default = null)
    {
        if ($this->has($key)) {
            $isInvokable = is_object($this->data[$this->normalizeKey($key)]) && method_exists($this->data[$this->normalizeKey($key)], '__invoke');

            return $isInvokable ? $this->data[$this->normalizeKey($key)]($this) : $this->data[$this->normalizeKey($key)];
        }

        return $default;
    }
```

in Slim/Helper/Set.php seems to fix the problem, and perhaps is_callable is better anyway? Thanks to  [this article](http://jmfeurprier.com/2010/01/03/method_exists-vs-is_callable/) for helping me figure this out  :)

**Comment by JoeBengalen** [comment]
Another tip for you: Your code doest throw exceptions when there is an error trying to connect. You have to set the attribute on connecting, not afterwards.

``` php
// wont throw connection errors
$conn = new PDO('sqlsrv:server =[info here]; Database = [info here]', '[info here]', DB_PASSWORD);
$conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

// will throw connection errors
$conn = new PDO('sqlsrv:server =[info here]; Database = [info here]', '[info here]', DB_PASSWORD, [
  PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);
```

**Comment by silentworks** [comment]
Also why not add this inside of the container, so its only instantiated when needed?

``` php
$app->container->singleton('pdo', function () {
    return new PDO('sqlsrv:server =[info here]; Database = [info here]', '[info here]', DB_PASSWORD, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);
});
```

**Comment by neoncube2** [comment]
Thank you for the suggestions :)

@JoeBengalen, actually, it seems like the code that I posted does throw exceptions when there's an error trying to connect. In fact, an exception is thrown even when I don't have the below line of code, although I'm not sure why.
    $conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

Still, I've changed to using your method, as your change does seem to make sense. Thank you again for the suggestion :)

Any chance of the bug fix that I posted making it into the core code?

**Comment by silentworks** [comment]
Your suggested change only fixes an issue you are having as the issue is not actually Slim related but more your code related, it doesn't make sense to have it in the core code.

The code I have posted is code I have used in the past and its code I have used when working with SQL Server also.

**Comment by neoncube2** [comment]
@silentworks, I respectfully disagree :)  It seems to me like using is_callable() instead of method_exists() makes sense because if method_exists() is true, the code calls the method, but even though the method exists, it may not be callable. Wouldn't it therefore make sense to use is_callable() instead of method_exists()?

**Comment by geggleto** [comment]
They are not inter-changeable. :-1: 

In slim's instance is_callable is used as a syntax check and not to check to see if its actually an available method.

Once significant difference between the two: If an object has the magic __call() method implemented, then is_callable() will return TRUE for any non-existent method, while method_exists() will return FALSE.

**Comment by akrabat** [comment]
Changing it would be a BC break on Slim 2 which isn't going to happen at this stage in Slim 2's life.

**Comment by neoncube2** [comment]
@silentworks, I tried out your code using the singleton and it works. Thank you for it :)
