### ISSUE TITLE
URL parameter truncates when it contains $ character

### ISSUE THREAD

**Issue by YeapseRinkado** [slimphp/Slim#1205]
URL Sample:http://testurl/CheckContent?Content=head$remainingcontent&Filter=none

I got parameters like:
$parameters = $api->request()->get();
print_r($parameters);

and I found the result is:
Array
(
    [Content] => head
    [Filter] => none
)

[Content] parameter have lost the content after $ character.

I guess the url parameter has been escaped because of the $ character.

**Comment by willrowe** [comment]
I don't believe that `$`s are allowed in urls like that, it should be properly encoded as `%24`. If you run `head$remainingcontent` through the `urlencode` function it will output `head%24remainingcontent`.

**Comment by YeapseRinkado** [comment]
Ah, sorry about that, I forgot to transfer it.XD
