### ISSUE TITLE
HMVC

### ISSUE THREAD

**Issue by cj** [slimphp/Slim#121]
First off great framework and thank you for your response before.  I have another quick question.  Would it be easy to create a method to call any route internally just as if you visited it from the url in your browser, something like Slim::visit('some/route/in/your/app', function($response){ // do something with $response });

Many thanks,

CJ

**Comment by codeguy** [comment]
That's not currently possible... I'll add it to the list of future considerations in the Road Map. Don't want to add this to the Issue Tracker just yet.

That's a tricky issue where you would have to mimic a second HTTP response and pass along headers, etc. So, right now... this isn't possible. In the future, perhaps.

Thanks!
