### ISSUE TITLE
Not able to use invoke magic method on singleton

### ISSUE THREAD

**Issue by iisurge** [slimphp/Slim#1210]
I want to be able to set a singleton like
`$app->container->singleton('main', function() {
        return  new Main("test");
    });`
And then use __invoke() like
`$app->main("invoke test");`
But I get the following error: 
`Call to undefined method Slim\Slim::main()`

**Comment by lalop** [comment]
Did you test like that ?

```
$main = $app->main;
$main("invoke test");
```

**Comment by iisurge** [comment]
@lalop this did not work

**Comment by silentworks** [comment]
You would need to make the singleton into a factory for that to work.

``` php
$app->container->singleton('main', function () {
    return function ($value) {
        return new Main($value)
    };
});
```

Now you should be able to run using

``` php
$app->main('invoke test');
```

or

``` php
$app->container['main']('invoke test');
```

Do note, I am not for this way of doing things, its better to create a real factory class than using the Container in this manner.

**Comment by lalop** [comment]
you can use too the built in helper `protect` 

```
$app->main = $app->container->protect(function() { 
     return 'test';
 });
$app->main("invoke test");
```

@iisurge  can you close this issue please if it's ok for you ?
