### ISSUE TITLE
When will 3.0 come?

### ISSUE THREAD

**Issue by yjgcwgg** [slimphp/Slim#1216]
Hi,
What's the exact time to release 3.0?

**Comment by JoeBengalen** [comment]
At least we have to wait till psr-7 is Accepted

**Comment by zz** [comment]
I think slim team need work hard, you publish a book, but laravel release the lumen. I just use lumen. Can not wait slim3 always on the way.

**Comment by nhymxu** [comment]
laravel publish faster because Taylor Otwell work full-time.
Codeguy code Slim in his free time.

Not same.

+1 "you publish a book, but laravel release the lumen. I just use lumen"

**Comment by jtwebb** [comment]
I'm looking forward to the release too. Fortunately, I have the luxury of waiting.

@JoeBengalen Waiting for PSR-7 to pass is a non-issue. As of May 5th it met the quorum and all were in favor at that time. So the remaining time and votes are all a formality now. For all intents and purposes, it's passed.

@zz I agree with @nhymxu, Josh is doing this on his free time and without cost to anyone. So there's no need to tell him to work harder. If you'd like to see 3.0 released sooner, maybe you could give him a hand.

I AM getting excited to play with the release, though :)

**Comment by moerphie** [comment]
Do you have a rough date for the release? -- ("within the next 8 weeks", "in September" or something like that)

Does it make sense to build new projects with the current Slim 2.x or should we wait?

**Comment by akrabat** [comment]
Currently, I'm hoping for first beta in the first week of June.

**Comment by yjgcwgg** [comment]
Wow, PSR-7 Acceptance, https://github.com/php-fig/http-message/releases/tag/1.0
