### ISSUE TITLE
POST to endpoint /vendor treated as GET when using Composer and Apache

### ISSUE THREAD

**Issue by skywaymsn** [slimphp/Slim#1220]
This is actually true for any endpoint that shares a name with a directory, but is default for Composer because /vendor is the default install location.

Slim either does not see the POST due to Apache rewrite rules, or acts differently on routes that match an existing directory.

Slim does receive the request and does process it, but POST is converted to GET, even if a POST route is defined.

In fact, $_SERVER['REQUEST_METHOD'] actually reports GET.  I'm not sure if Slim is doing this or perhaps Apache rewrite rules?

Example:

```
$app->get('/vendor', $some_get_function);
$app->post('/vendor', $some_post_function);
```

If I POST to /vendor, `$some_get_function` is executed and `$_SERVER['REQUEST_METHOD']` reports 'GET'

You can replicate this behavior with any directory, empty or not.

```
$app->get('/my_custom_directory', $some_get_function);
$app->post('/my_custom_directory', $some_post_function);
```

POST to /my_custom_directory

If my_custom_directory does not exist, `$some_post_function` is executed and `$_SERVER['REQUEST_METHOD']` reports 'POST'

If you create my_custom_directory does exist, `$some_get_function` is executed and `$_SERVER['REQUEST_METHOD']` reports 'GET'

**Comment by tuupola** [comment]
In general vendor should be outside of document root. But can you show also the `.htaccess` file?

**Comment by skywaymsn** [comment]
Sure, extremely primitive:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

Which checks to see if a file does not exist, but I'm not sure how Slim manages to convert a method if it **does** exist.  Apache logs the request as POST, but internally PHP and Slim see 'GET'

**Comment by tuupola** [comment]
Might be caused by [DirectorySlash](http://httpd.apache.org/docs/2.0/mod/mod_dir.html#directoryslash) config. Try turning it off.

**Comment by skywaymsn** [comment]
That's the solution!  I should have known better.
