### ISSUE TITLE
Fatal error: Uncaught exception 'Slim\\Exception\\Stop' with message ''

### ISSUE THREAD

**Issue by r3wt** [slimphp/Slim#1221]
on following code:

``` php
$app->halt(429,'Too Many Requests');
```

**Comment by JoeBengalen** [comment]
Called from where?

**Comment by r3wt** [comment]
@JoeBengalen this is just dumbed down version so you can understand it. 

``` php
$app = new \Slim\Slim();
$ratelimiter = new \App\RateLimiter;

$num = $ratelimiter->calc();

if($num > 60){
    $app->halt(429,'Too Many Requests');
}


// ... rest of code
```

**Comment by JoeBengalen** [comment]
What else did you expect? It is not called within Slim. The method `Slim\Slim:call()` will catch it if you call `halt()` within the application.

I think seeing the context you should put this code in middleware layer

**Comment by r3wt** [comment]
I expected it to halt the application and return the http response
I need it run unconditionally before any of the routes are run. Middleware isn't an option. it needs to run for every single route in the application. maybe the slim before hook?

**Comment by JoeBengalen** [comment]
A I see that's not supported in Slim v2. I have only used Slim v3 where it is possible to add middleware application wide.

I there no other way to call `halt()` within Slim?

**Comment by r3wt** [comment]
@JoeBengalen I resolved it ( i think ) by placing it in the slim.before hook

**Comment by JoeBengalen** [comment]
Reading about them that sounds like a good option ;)

**Comment by r3wt** [comment]
Thanks for the help good sir. You got me to thinking. :)

![img](http://puu.sh/hFMMm/9124ec4826.png)

**Comment by geggleto** [comment]
You are calling it before Slim::run()... so how can you halt something that hasn't happened yet.

**Comment by russkin** [comment]
This issue reproduced in Slim version 2.3.5
Version 2.6.2 is correct.
