### ISSUE TITLE
Stream-related error while reading POST request body (Slim 3.0)

### ISSUE THREAD

**Issue by realart** [slimphp/Slim#1229]
When getting request body with $request->getBody() and casting it to string, i get following errors:

> PHP Warning:  stream_get_contents(): stream does not support seeking in C:\projects\flsite\vendor\slim\slim\Slim\Http\Body.php on line 168
> PHP Warning:  stream_get_contents(): Failed to seek to position 0 in the stream in C:\projects\flsite\vendor\slim\slim\Slim\Http\Body.php on line 168
> PHP Catchable fatal error:  Method Slim\Http\Body::__toString() must return a string value

This does not happen when I switch the same action as a get route and test it with browser (with empty request body.

**Comment by lalop** [comment]
Can you provide some code sample ?

**Comment by silentworks** [comment]
Closing this one out, if you are still having this issue please provide some code sample and re-open.
