### ISSUE TITLE
Suggestion Slim3 : Multiple instance of CallableResolver while route mapping

### ISSUE THREAD

**Issue by rivetchip** [slimphp/Slim#1233]
For each mapped route using a "string controller", Slim create a new instance of `CallableResolver`.

``` php
$app->map(['GET'], '/hello', '\Controller\Class:function');
```

Isn't it more performance and better to resolve the callable directly into Route::__invoke() ?
So only **the one and final** instance will be created. Something like :

``` php
use use ResolveCallable;

public function __invoke( ... ) {

    [...]

    $function = is_string($this->callable) ? $this->resolveCallable($this->callable) : $this->callable;

    $newReponse = $function($request, $response, $request->getAttributes());
}
```

But it also have a counterparty :
_ passing Slim's Container to Route ( because of `ResolveCallable` Trait and `$this` )
or
_ removing `protected $container` of `CallableResolver`
( don't think it's really useful unless we want to register a controller )

.
**What do you guys thinking ?**

**Comment by JoeBengalen** [comment]
May be worth looking at, but it has to be resolved into a callable before any middleware can be added on top. So not sure if this is possible. Also we are not just talking about controllers, middleware also needs to use the same resolver.

**Comment by lalop** [comment]
Hello,
this is done in a pr https://github.com/slimphp/Slim/pull/1208

**Comment by rivetchip** [comment]
@lalop Thanks I haven't seen it, I'll look in more deeply.
