### ISSUE TITLE
ArrayAccess for Slim 3 App?

### ISSUE THREAD

**Issue by jenssegers** [slimphp/Slim#1234]
Now that the Slim 3 app does not extend the Pimple container anymore, the ArrayAccess functionality is lost. I think it makes sense adding it back so that you can do:

``` php
$app['foo'] = function() { ... };

$foo = $app['foo'];
```

**Comment by akrabat** [comment]
Personally, I disagree as I don't think a service container is inherently an array.

In Slim 3, __get() is available, so accessing a dependency is as easy as:

``` php
$foo = $app->foo;
// or
$foo = $app->getContainer()['foo'];
```

Note that __set() isn't implemented as the container interface we use doesn't specify how to set a service. 

To set up the dependencies, you use:

``` php
$app->getConatiner()['foo'] = function() { … };
// or
$container = $app->getContainer();
$container['foo'] = function() { … }
```

**Comment by jenssegers** [comment]
Using `$app->getContainer()['foo']` does not really look developer friendly.

It can't go much easier than just doing `$app['foo'] = ...`.

**Comment by JoeBengalen** [comment]
You can also get the container once ofcourse.

``` php
$container = $app->getContainer();

$container['foo'] = ...
$container['bar'] = ...
```

**Comment by akrabat** [comment]
They way that @JoeBengalen does it is the way that I do it.

**Comment by silentworks** [comment]
@JoeBengalen you beat me to it, I was just about to post that.

@jenssegers also note that even though the code might not look developer friendly, its a language feature, so we have to be prepared to use it if we need to, another solution is to create all your services in a separate class and register them to the container if you are using Pimple.

``` php
<?php

use Pimple\Container;
use Pimple\ServiceProviderInterface;

class MyServiceProvider implements ServiceProviderInterface
{
    public function register(Container $app)
    {
        $app['foo'] = function () {
            return new Foo();
        };
    }
}
```

Then just register that to the container like:

``` php
$app->getContainer()->register(new MyServiceProvider);
```

and for getting the service you can use the above suggestion by @akrabat.

I find this way better for organisational purpose.

**Comment by jenssegers** [comment]
@silentworks But then your service providers don't have access to application methods. Sorry for my stubbornness, I'm just really used to accessing the container this way from Laravel :)

**Comment by silentworks** [comment]
@jenssegers what kind of application logic would you want your service provider to have? you would have access to all Slim's registered services. I have never needed more than that but do tell me more about what you are after.

I also use Laravel and currently the Container works almost the same.

**Comment by jenssegers** [comment]
@silentworks For example; you could have a service provider that registers middleware or even routes.

**Comment by akrabat** [comment]
You have a service provider that registers routes and middleware when it's retrieved from the container?

How does that work? It implies that urlFor() for that route would only work if the correct service is retrieved first, even though that service may not be needed.

(For the record, I'm genuinely trying to understand your use-case here.)

**Comment by jenssegers** [comment]
@akrabat Service providers are executed immediately right.

For example, let's say you want a Clockwork service provider. Then you register a middleware that tracks a bunch of stuff, and add a route for the browser plugin to get the debug information. Eg: https://github.com/itsgoingd/clockwork/blob/v1/Clockwork/Support/Laravel/ClockworkServiceProvider.php

But we're deviating from the initial topic a bit now :)

**Comment by JoeBengalen** [comment]
``` php
$app = new Slim\App();

$container = $app->getContainer();

$container->register(new SomeServiceProvider($app));
```

**Comment by jenssegers** [comment]
@JoeBengalen I know the workarounds. For me it's just a matter of developer friendliness :) If the Slim maintainers decide to do it this way, so be it. But it's now that we are able to discuss about stuff like this now that it is still in development.

**Comment by JoeBengalen** [comment]
I fail to see how it would be a 'workaround' to be honest. Looks like pretty clean code to me.

**Comment by silentworks** [comment]
As @JoeBengalen stated above then your `SomeServiceProvider` would look like:

``` php
<?php

use Slim\App;
use Pimple\Container;
use Pimple\ServiceProviderInterface;

class MyServiceProvider implements ServiceProviderInterface
{
    protected $app;
    public function __construct(App $app)
    {
        $this->app = $app;
    }

    public function register(Container $app)
    {
        $app['foo'] = function () {
            return new Foo();
        };

        $this->app->get('/myroute', function () {
            return 'Here is my route';
        });
    }
}
```

I still don't understand what you mean by developer friendly, there is nothing hostile in the code and its even better organisation. And this is not a workaround, this is exactly what Laravel is doing in the background for you, I prefer to know about the magic than just have it happen without knowing what is going on.

**Comment by jenssegers** [comment]
I would prefer doing this, similar to what Laravel is doing:

``` php
$app = new Slim\App();

$app->register(new SomeServiceProvider($app));
```

This way you never have to worry about "Do I have the app instance now, or do I have the container?"

**Comment by akrabat** [comment]
I think the main place we differ is that I think

``` php
$container = $app->getContainer();
// do something with $container
```

is more developer friendly as it's more explicit and easier to understand when maintaining the app in the future.

**Comment by silentworks** [comment]
@jenssegers Laravel is bound to a single implementation of a Container, this was the case for the early versions of Slim 3, but this is no longer the case as not every developer want to work with Pimple.

I think the options we have outlined are sufficient for any developer to work with, I don't think this is going to change at the moment as this issue was open for quite a while and we had no objections until now that it has been merged in.

Another option would be to use this Service Manager https://github.com/itsgoingd/slim-services instead. You would probably need to modify it to work with Slim 3 as it was originally created for Slim 2.

**Comment by akrabat** [comment]
I would say that an equivalent way to replicate the Lavavel example is:

``` php
<?php
namespace My;

use Slim\App;
use Pimple\ServiceProviderInterface;
use Pimple\Container;

class MyServiceProvider implements ServiceProviderInterface
{
    public function boot(App $app)
    {
        // add route
        $app->get('/myroute', function () {
            return 'Here is my route';
        });

        // register services
        $app->getContainer()->register($this);
    }

    public function register(Container $app)
    {
        $app['foo'] = function () {
            return new Foo();
        };
    }
}
```

usage:

``` php
$app = new Slim\App();

$provider = new My\ServiceProvider();
$provider->boot($app);
```

**Comment by jenssegers** [comment]
It is up to you guys what you decide, I'm just leaving my opinion about this recent change now that I still have the chance :)

@silentworks Having ArrayAccess does not limit you to not use multiple implementations of the container. The App class can just call the correct methods from the container interface.

The Clockwork service provider was just an example that I know that registers routes and middleware, I'm not using it :)

**Comment by JoeBengalen** [comment]
@jenssegers And how would you know what the 'correct' method is in the container to register the service? There is no method for it in the container interface. That's the whole point.

**Comment by jenssegers** [comment]
Mh, that is quite a bummer actually. I thought that a container interface would at least have a getter and setter method.

**Comment by mnapoli** [comment]
@jenssegers the reason is that setting entries is very different from containers to containers. E.g. with Symfony's DIC you compile the container from definition sources (YAML, XML, …) and then it's read-only (i.e. can't set). In PHP-DI, you might want to do something similar to allow good use of cache and best practices (static configuration for the container). Also some container entries could come from autowiring, which you don't need to set in the container at all.

**Comment by jensscherbl** [comment]
> $app = new Slim\App();

$container = $app->getContainer();

$container->register(new SomeServiceProvider($app));

Sorry to bring this back up, but doesn't Slim's default container still expect a `Pimple\ServiceProviderInterface` instance here, which in return expects a `Pimple\Container` instance instead of a `Slim\App`instance?
