### ISSUE TITLE
Slim 3 - Session Management

### ISSUE THREAD

**Issue by maldoinc** [slimphp/Slim#1238]
Hey there I've written some piece of code which I believe can be used as a session management service for the upcoming version 3. Awaiting your feedback on this.

You can find it at https://github.com/maldoinc/Slim-Session

**Comment by lalop** [comment]
Hello,
nice to see.
There is some evolution on how slim 3 manage the container, I think that has some impact on your package

**Comment by nhymxu** [comment]
I see Cookie inside Core code. Wait Session with right code format from Josh

**Comment by maldoinc** [comment]
That is there to help with instantation, the core class is independent of the session superglobal.

**Comment by nhymxu** [comment]
I want real simple example from Josh to easy modify with right code format. Fuelphp session look great with many storage to save :)

**Comment by elhsmart** [comment]
@maldoinc, I think it would be nice to add some doc comments to the methods of your classes and merge whole repo into https://github.com/slimphp/Session-Middleware

**Comment by maldoinc** [comment]
You are right, that is indeed the correct repo to merge into. I was simply looking for feedback  over here. Will send a PR to the other repo instead.

Cheers
