### ISSUE TITLE
Slim3 - \Slim\Interfaces\RouteInterface should be more structured

### ISSUE THREAD

**Issue by elegos** [slimphp/Slim#1242]
Hello!

I've noticed that RouteInterface defines only the barebone methods needed by a route, but I think it defines way less methods than it should: for instance, the documentation talks about named routes. Writing my first version of my application, I'd use for sure this "feature" because it's... well, necessary? to create links between the project.

What if tomorrow I create my own route? I'd implement RouteInterface being sure everything will continue working - but it won't, because setName is not part of the interface.

In my opinion \Slim\Route should be a (good) example of RouteInterface implementation, i.e. the interface should define most, if not all, the public methods of the Slim's standard Router class.

**Comment by lalop** [comment]
Hello @elegos 
`setName` come from `Route` not `Router`,
But the issue is the same, `RouteInterface` doesn't define `setName`.
Giving it a deep look, there is no way to change is implementation... so I don't really see why there is an interface.

**Comment by akrabat** [comment]
`Router` creates each `Route` object. You can swap out the `Router` object, but this new router would have to create Route objects that match the interface.

**Comment by lalop** [comment]
ok I see.
you only have to implement `getPattern` and `__invoke__` to have a valid Slim3 `Route`.
Since the core library doesn't use `setName` this hasn't to be in the interface definition.

**Comment by akrabat** [comment]
Presumably that's because `urlFor` is also part of the router. What about `add` though?

**Comment by lalop** [comment]
Since this is used by the `Router` I think the answer is the same

**Comment by elegos** [comment]
Sorry for the miswriting, yes - we're of course talking about `Route` and not `Router` :)

Nonetheless the `RouteInterface` is just nuts, it only defines `getPattern` and `__invoke`. I can understand the core library doesn't use `setName` or anything else, but shouldn't be the interface something more than what the core uses? In the documentation it's taken for granted you use `setName`, `getName` (via `urlFor`) etc.

I know, I perfectly know we're talking about "style" in here, but in my personal opinion the interface should guide the developer to a standard way of writing the code, not only interfacing with the core. But I totally understand your point of view (i.e. the interface is the minimum you have to define to let Slim work by its own without using any "extra" methods).

**Comment by designermonkey** [comment]
When we put the initial interfaces together we only added what we decided was must have functionality to make Slim work. Granted that was a year ago, and opinions can change.  A route and router would work fine without a name, and is an advantage of using the in-built router and route classes.

**Comment by silentworks** [comment]
I think a recent experiment by @akrabat kinda proves why its good that we don't have setName in the Interface. He started implementing Aura.Router and noticed that it already had its own way of setting a name for a route, you had to pass it in as the last argument of the route itself rather than a independent method and there was no way of setting it later as it was required upon route creation, if `setName` was a hard requirement then he would have just created an empty method that does nothing and would not be of any use to anyone.

Some developers don't actually use `setName` and `urlFor` at all, because they are building small apis which don't require getting the url through the route name as its small enough to remember the path to each endpoint.

For these reasons I don't think it would be wise to add these methods to the Interface.

**Comment by opengeek** [comment]
I don't think this discussion should be closed. I think it is a mistake to be worried about making Router/Route swappable in Slim. If that is the case, perhaps we can just throw together whatever components I want to create my own microframework using exactly the DI container I want, and exactly the routing strategy I want, with no limitation imposed at all by Slim. At some point there are diminishing returns for making things too flexible—in this case I think the DI + Routing is a central part of Slim. I would recommend we keep the interfaces for Router and Route, even look to extend them somewhat. If you want to replace the router then, you would need to implement those interfaces, use an adaptor to another router or extend the Slim router.

**Comment by opengeek** [comment]
after further thought, perhaps a solution where the Router defines it's own RouteInterface could be the solution

**Comment by elegos** [comment]
Reading this discussion again let me think exactly why I opened it. When I did it, I wasn't 100% sure about why I wrote it (yes, I complained about the missing methods). Now that I've got a clearer view of the problem, it's the following: I expected the interface to perfectly match the Slim implementation (which I though was a reference, functional one). So when I tried implementing my own Route using the RouteInterface I was confused why there wasn't `setName` etc. I know this is more than adding methods in an interface which should, by project and original idea, be as "slim" as possible.

A possible solution though could be to create an extended route interface, for example `ExtendedRouteInterface` which includes all the extra methods, keeping the core interface clean. What do you think about?

P.S.
@akrabat I saw your Slim 3 Primer :+1:

**Comment by geggleto** [comment]
If you are extending the functionality it is really not Slim anymore ;)

**Comment by akrabat** [comment]
I believe that RouteInterface and RouterInterface now match what we use in the rest of Slim.
