### ISSUE TITLE
Can't use method return value in write context in \Slim\Http\Request.php on line 159

### ISSUE THREAD

**Issue by kminek** [slimphp/Slim#1244]
after latest changes

**Comment by akrabat** [comment]
Can you provide sample code that shows the problem?

**Comment by kminek** [comment]
sample code: https://github.com/slimphp/Slim/tree/develop#usage
it's fatal error

my composer.json:

```
"slim/slim": "dev-develop"
```

**Comment by kminek** [comment]
i am using PHP 5.4.25

after googling around:

limitation of empty() in PHP versions below 5.5:
empty() only checks variables as anything else will result in a parse error. 
In other words, the following will not work: empty(trim($name))

**Comment by akrabat** [comment]
aha! We'll have to get that captured in a unit test and get Travis up and running

**Comment by tuupola** [comment]
Seems it is already catched. 5.4 build failed with the above error message.

https://travis-ci.org/slimphp/Slim/jobs/63999203

**Comment by akrabat** [comment]
That's interesting!

**Comment by akrabat** [comment]
@kminek I think I've fixed this via PR #1245 - are you able test?

**Comment by akrabat** [comment]
Appears to work: https://travis-ci.org/slimphp/Slim/jobs/64138247

**Comment by kminek** [comment]
works for me too :)

**Comment by silentworks** [comment]
This has now been merged into develop.
