### ISSUE TITLE
Registration of Service Providers changed

### ISSUE THREAD

**Issue by bcremer** [slimphp/Slim#1250]
Since commit slimphp/Slim@ea4f1fc `\Slim\App` is no longer a instance of `\Pimple\Container`. This affects registration of Pimple Service Providers.

**Before**
A Service Provider can be registered on `\Slim\App`:

``` php
$app = new \Slim\App();
$app->register(new \Slim\Views\Twig()); // instance of \Pimple\ServiceProviderInterface
```

**After**
The container instance has to be fetched from the application first:

``` php
$app = new \Slim\App();
$container = $app->getContainer();
$container->register(new \Slim\Views\Twig()); // instance of \Pimple\ServiceProviderInterface
```

The following files are still referencing the old behavior:

| File | PR |
| --- | --- |
| https://github.com/slimphp/Slim-HttpCache/blob/master/README.md#usage | https://github.com/slimphp/Slim-HttpCache/pull/5 |
| https://github.com/slimphp/Twig-View/blob/master/README.md#usage | https://github.com/slimphp/Twig-View/pull/12 |
| https://github.com/slimphp/Slim-Flash/blob/master/README.md#usage | https://github.com/slimphp/Slim-Flash/pull/2 |
| https://github.com/slimphp/Slim-Documentation/blob/master/docs/features/templates.html#L83 | https://github.com/slimphp/Slim-Documentation/pull/11 |

**Comment by codeguy** [comment]
Feel free to submit a PR if you have time. Otherwise we can get to this soon.

**Comment by bcremer** [comment]
Just wanted to make sure this change was intentional and will not change. Pull requests are ready.

**Comment by bcremer** [comment]
Since all linked PRs are merged this issue can be closed.

**Comment by silentworks** [comment]
Nice, thanks for that.
