### ISSUE TITLE
Slim3 - binding app to route callable

### ISSUE THREAD

**Issue by ahundiak** [slimphp/Slim#1252]
The current implementation of Slim\App::map binds itself to callables.  Is this really necessary or desirable?  If the callable needs access to say the container then it can simply include it in the closure definition:

```
function ($request, $response, $args) use ($container) {
```

I suppose it could even include $app if it really needed it.

Binding the app basically gives the closure access to all kinds of stuff that most won't need.  I know there has been some debate on service locator vs dependency injection but it seems to me that it would make the closures easier to debug and maintain by only injecting what it needs.  

Plus, skipping the binding would eliminate a tiny performance hit.

**Comment by codeguy** [comment]
Callable binding is super convenient. We've discussed it earlier (no idea where), but it's going to stay in v3.
