### ISSUE TITLE
RFC Removing Autoloader class

### ISSUE THREAD

**Issue by silentworks** [slimphp/Slim#1253]
Earlier in the week @akrabat mentioned that it might be good to remove the Autoloader class from the core of the project and I was thinking about this earlier today and came to the same conclusion. I will state here my reasoning of why I think it should be removed.
- You won't be able to install Slim 3 without composer without going through lots and lots of hoops
- If you decide you don't mind doing step 1, there is already a slew of PSR4 Autoloaders available
- We should try and push the standards of PHP wherever possible, Composer has become the defacto package manager that has its own Autoloader.

Please comment below your thoughts and please note this is for Slim 3, so nothing related to Slim 2 in the comments please.

**Comment by tuupola** [comment]
Agreed.

**Comment by nhymxu** [comment]
Agreed.

**Comment by akrabat** [comment]
I agree too.

**Comment by JoeBengalen** [comment]
+1

**Comment by mnapoli** [comment]
+1

**Comment by Melbournite** [comment]
Definitely.

**Comment by funkatron** [comment]
Seems legit :+1:

**Comment by endel** [comment]
Agreed. :+1: 

Anybody who is not using Composer yet should definitely start to use it.

**Comment by PSchwisow** [comment]
DO EET!!!

**Comment by zither** [comment]
Agreed.

**Comment by jacobemerick** [comment]
:+1:

**Comment by dayofr** [comment]
Go for it

**Comment by rkarkut** [comment]
Agreed

**Comment by akrabat** [comment]
PR #1256 for you @silentworks

**Comment by harikt** [comment]
:+1:

**Comment by silentworks** [comment]
Thanks for all the input everyone. This has now been removed, thanks to @akrabat.

**Comment by codeguy** [comment]
Belated :+1:
