### ISSUE TITLE
[Slim v3] Middleware Adding does not resolve callables

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1258]
Example:

$app->add('\VMS2\Middleware\APILogger:run');

[Mon Jun 01 17:21:49 2015] [error] [client 10.0.2.2] PHP Catchable fatal error:
 Argument 1 passed to Slim\App::add() must be callable, string given, called in
 /vagrant/index.php on line 33 and defined in /vagrant/vendor/slim/slim/Slim/Mid
dlewareAware.php on line 49

**Comment by geggleto** [comment]
#1260 :+1:

**Comment by akrabat** [comment]
Fixed by #1260
