### ISSUE TITLE
How to back page and hold form data

### ISSUE THREAD

**Issue by kosgug** [slimphp/Slim#1261]
1. Use javascript history.back(), but the flash message can't show.
2. Save form data by session and redirect back. cumber a little i think.

Who had some idea by slim? Thx.

**Comment by tuupola** [comment]
http://garlicjs.org/

**Comment by geggleto** [comment]
You could also just post via ajax then pass a message back with a new URI if the form is successful

**Comment by kosgug** [comment]
@tuupola Thanks.
@gpoole Yeah, i will do it with ajax, thanks.
