### ISSUE TITLE
$app->flash() does not show any messages ever

### ISSUE THREAD

**Issue by Boldewyn** [slimphp/Slim#1262]
This is the stripped-down version of my app, using Slim 2.6.2:

``` php
<?php

require 'vendor/autoload.php';

/* @see <http://docs.slimframework.com/sessions/native/> */
session_cache_limiter(false);
session_start();

$app = new \Slim\Slim();
$app->add(new \Slim\Middleware\Flash());

$app->get('/', function () use ($app) {
    $app->flash('info', 'quark');
    $app->render('delme.php');
});

$app->run();
```

and a minimal `delme.php` template:

``` php
<?php
var_dump($flash->getMessages());
```

My understanding of the Flash middleware is, that from the second page view on, the `var_dump()` should show the "quark" message from line 13 in the app (always the message set in the previous request). However, `var_dump` always shows **an empty array**. If I use `flashNow()`, the same thing works, and as expected from the first page view on. What am I missing here?

**Edit:** To be clear, there are always messages in the `next` queue of the Flash middleware, but they get never propagated to `prev` or `now` state.

**Comment by geggleto** [comment]
You need to use flashNow, otherwise itll be available on the NEXT request.

**Comment by Boldewyn** [comment]
Um, yes, that's what the issue is about. There is nothing displayed on the second (i.e. the _next_) request, e.g., when I reload the page. The messages never get promoted from the `next` to the `prev` queue.

**Comment by geggleto** [comment]
in delme.php...

<?=$flash['info']?>

**Comment by Boldewyn** [comment]
Nope. It's always `NULL`, independent on how often I reload the page. Using PHP 5.5.6, if that is of any significance.

(No other code at work here. I test with the exact two files, that I wrote above, Slim installed via Composer.)

**Comment by geggleto** [comment]
Remove session_cache_limiter(false);

**Comment by Boldewyn** [comment]
No change, unfortunately. (Also I included it because of a remark in the Slim docs themselves.)

My `composer.json`:

``` json
{
    "name": "foo/bar",
    "require": {
        "slim/slim": "^2.6"
    }
}
```

So it's really only

```
composer.json
index.php
templates/delme.php
```

and no `flash()` messages :(

**Comment by Boldewyn** [comment]
In the route I included a

```
var_dump($_SESSION);
```

before the `$app->flash()` call, and it's almost empty:

```
array(1) { 'slim.flash' => array(0) { } }
```

So there are no flash messages from the last request stored (but the `slim.flash` array itself, strangely).

**Comment by Boldewyn** [comment]
OK, I've started diving into the Slim code. Obviously, `Middleware\Flash::save()` is called twice after the route execution, and that makes the second `save()` overwrite the flash messages with an empty array.

**Comment by Boldewyn** [comment]
I've found the problem:

```
$app->add(new \Slim\Middleware\Flash());
```

It seems, the Flash middleware is already added per default. This line creates a second instance, clobbering the data of the first one.

@geggleto Thanks for your help and the patience!

@codeguy Is that something, that the documentation should state somewhere? I.e., that some middleware is already included and doesn't need to be added separately?
