### ISSUE TITLE
[v3] Traits

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1272]
Just a quickie about traits.

Interfaces are defined in `Slim\Interfaces`. Should traits be in `Slim\Traits`?

Also, not sure if it is a standard or not in PSR, but interfaces should be defined as `MyAwesomeInterface`, abstracts as `MyNotSoCoolAbstract`, so should the traits be `WowSuchTrait`, all with the type at the end?

So, `CallableResolverAwareTrait` and `MiddlewareAwareTrait`

It's definitely a preference of mine to allow me to easily ascertain what is what in a codebase.

**Comment by akrabat** [comment]
I don't mind either way.

**Comment by codeguy** [comment]
I don't really care if they live beneath a `traits/` directory. I do think we should change the class suffix to be "Trait" to be in line with PSR suggestions.

**Comment by gabriel403** [comment]
@designermonkey have fixed the class suffix!
