### ISSUE TITLE
[v3] Middleware Namespace

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1275]
Would it be wise to provide all Slim 'core' middleware packages under a specific namespace?

```
Slim\Middleware\Flash
```

for example.

**Comment by tuupola** [comment]
I was also wondering why the `Middleware` part has been removed from namespace. It kind of makes sense to keep it there.

**Comment by geggleto** [comment]
Largely because middleware is application specific and the Middleware class has been deprecated.

**Comment by designermonkey** [comment]
I understand the class has been deprecated, what I'm talking about is the namespace, hence the title `[v3] Middleware Namespace`.

It makes for better structural organisation to hold them in a namespace, whether they're in the core package or not.

**Comment by akrabat** [comment]
I can see the logic for the Slim 3 compatible Middleware components to be in the `Slim\Middleware` namespace

**Comment by silentworks** [comment]
From what I can see we currently don't have any Slim 3 specific middleware at the moment, I think Session will be the first and probably will use the `Slim\Middleware` namespace.

**Comment by codeguy** [comment]
Why is the Session middleware Slim-specific?

**Comment by silentworks** [comment]
Well it wont be but it needs a namespace to live under as a Middleware.

**Comment by akrabat** [comment]
[Slim-HttpCache](https://github.com/slimphp/Slim-HttpCache) is Middleware

**Comment by geggleto** [comment]
I still stand firm on all middleware should be contained in the application namespace.

**Comment by silentworks** [comment]
@akrabat didn't see that one.

On a separate note can we stop coupling the ServiceProvider with the actual code for the package. I see this is becoming a pattern that others will follow. Now that we are using Container Interop, we shouldn't bind the actual package to the Pimple ServiceProviderInterface, we should create a separate class in each package to do this.

**Comment by akrabat** [comment]
I agree about the ServiceProvider coupling.

**Comment by tuupola** [comment]
This starts to be academic, but stirring it a bit more. If middlewares are not Slim specific why are they under Slim namespace then? It is matter of taste but `Slim\Middleware\HttpCache` sounds more logical to me than `Slim\HttpCache\Cache`. 

Is there a practical reason why Slim middleware should not be under `Slim\Middleware` namespace? Other than ones preferred way of naming things?

**Comment by silentworks** [comment]
I think its more of an identity to say where they came from and I guess to also lessen collision. But I do agree that it should be under `Slim\Middleware` namespace in order to not convolute the top level namespace.

**Comment by akrabat** [comment]
The top level namespace is for vendor, so all of this organisation's PHP projects should be under the `Slim` top level namespace regardless of whether they are Slim specific or not. 

I think that everyone other than geggleto agrees that any middleware that the organisation creates should be in the `Slim\Middleware` namespace.

**Comment by rszrama** [comment]
What about middleware not maintained in the slimphp organization? Could I still use the Slim\Middleware namespace to organize my own code?

**Comment by akrabat** [comment]
As a rule, you should use your own top level namespace for your code. e.g. I use `RKA` or `Akrabat`

**Comment by codeguy** [comment]
Yep. Choose a top-level vendor namespace that is unique to you.
