### ISSUE TITLE
[v3] Settings

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1279]
Is it just me, or are all the default cookie settings now void, as Cookies are not core any more?

**Comment by akrabat** [comment]
My understanding is that cookies are not in core any more.

**Comment by codeguy** [comment]
@akrabat is correct. I do want to create a cookie utility class (separate component) before we reach official 3.0.0 though.

**Comment by designermonkey** [comment]
I can look at that @codeguy this evening.

**Comment by codeguy** [comment]
@designermonkey Nice!

**Comment by codeguy** [comment]
@designermonkey Propose your ideas here before implementing please.

**Comment by designermonkey** [comment]
Well, to start, it's be the same basic component that was in last year's prep work for Slim3, just modified to be a service provider.

Obviously the code should be housed here, so if you wanted to create a repo for it, I can PR it to that.

**Comment by designermonkey** [comment]
@codeguy I don't think I could come up with anything other than a poor duplication of this, coupled with a service provider and middleware plug

https://github.com/dflydev/dflydev-fig-cookies

**Comment by codeguy** [comment]
Service provider for third-party component is fine.

**Comment by codeguy** [comment]
Creating repo now.

**Comment by codeguy** [comment]
@designermonkey Added the repo, and added you to the maintainers team. You should have access.
