### ISSUE TITLE
[discussion] Container responsibilty

### ISSUE THREAD

**Issue by pine3ree** [slimphp/Slim#1282]
I agree on having a separate container so that it could be changed with any other interop container interface. But i believe it's not the container's responsibility to create request/response/error handler instances. Those services / instances should be created by service providers, or just by the app instance acting as service provider for them.
If we want to use another container we would otherwise have to extend it and rewrite (copy and paste) the same ctor code to provide those initial services.

**Comment by mnapoli** [comment]
I agree that it's not the role of the container to create request and response objects (already voiced that in another comment but can't find the link). I don't think it's a big deal but having those factories inside the app (or another class) would help replacing containers more easily, so +1.

**Comment by pine3ree** [comment]
Hi @mnapoli 
sorry I missed your comment (I just got back to this project after a long "eu-cookie-law websites fixing week")

**Comment by mnapoli** [comment]
No worries I can't even find where it was. It's good to have an issue to discuss that.

**Comment by jaapverloop** [comment]
This one I guess https://github.com/slimphp/Slim/pull/1179#discussion_r30459907

**Comment by akrabat** [comment]
PR #1278 moves the creation of the Request into a factory method, so that Container is simply:

``` php
        $this['request'] = $this->factory(function ($c) {
            return Http\Request::createFromEnvironment($c['environment']);
        });
```

Looking at the rest of the factories in [Container](https://github.com/akrabat/Slim/blob/request-create-from-environment/Slim/Container.php) now, they all seem really really trivial to copy/paste into your own container if you're using something else.

**Comment by pine3ree** [comment]
Hello @akrabat,
It's really not about the simplicity of it, but more about the correctness of doing it (and also redoing it) in a container.
Let's take for instance the private property $defaultSettings. This is about cookie, http message settings or more generally application level configuration/settings. In my opinion a container should only provide new objects or shared services. The actual Container class in slim seems to me more like a not so slim slice cut off from the application cake.

A different container should only need to implement the get() interop interface method to fit in and replace the current one.

A class name such as \Slim\AppServices composing a simpler replaceable container would seem more sound to me for what it does now.

These are just my first impressions, i will re-read and rethink about it next week, maybe after reading other opinions. 

Of course, if it's already been decided for this implementation, you can close the discussion instantly.

kind regards
maks

**Comment by akrabat** [comment]
In some ways, Slim is intentionally opinionated; you're supposed to use our Container (and our Router).

Slim 3's App was originally written to extend Pimple so that changing the DIC was impossible. However, we have done enough work to enable replacement of Container with your own one, but you have to do a small amount of integration work. 

Personally, I think that the number of people what will change the DIC is small and would be able to provide an integration package on Composer for this DIC of choice.

I'm happy with this state of affairs as I particularly don't want any additional complexity such as two containers in play. I've done this with Slim 2's Set composing Zend\ServiceManager and it's a right old pain.

**Comment by pine3ree** [comment]
Hello @akrabat 

Along with You and - I believe - many other developers, I also think that slim should stay as slim as possible (we already have zf2 if we want greater SOLID compliance and more granularity). 
If we want it slim, then we cannot have too much separation of concerns. 

For the same reason if I had to choose between having a forced opinionated container and the ability to switch to another one with the condition of having to rebuld all the basic application services i would prefer the first and older way, even if i hate getting "things" via array access.

A better solution to me would be having an internal Slim Container (Service Locator) interface with an added set()/factory() method so that a container  would be a simple has/get/set/factory custom implementation or a 3d-party container bridge. All the basic (lazy) services creation could be moved back to the application constructor and the default slim container implementation could be a simple Pimple\Container bridge or decorator.

Shortly: switching to a different container should involve only the way or the actor in service creation and retrieval, the container should not be responsible of initializing the application.

As of now implementing a different container basically means rewriting the whole application bootstraping process and that also allows a dangerous flexibility. As an example, let's say (we discussed something related in another issue/pr) I implement a container that create an instance of phly/zend-diactoros server request. All the slim request's extra public methods would not be available anymore, and a change of container may result in runtime errors for the same unchanged application code. To have all those extra methods always available, a slim app must always start with its server request implementation and only allow external middlewares returning modified clones of it. The simplest/slimmest way to do that is having the application be the factory of the request instance like it was done before.

Another issue: suppose we have parts of the application that use the Pimple container factory() method to store a factory service. If we change the container, the new one may (probably) not have the factory method or may have it with a different signature. Well, since App::getContainer() simply returns a ContainerInterface we shouldn't even think about using the factory() method, so must we register all our factories inside the Container constructor? Simply put: how do i safely add factories to the generic service locator?

If we want to allow using different containers we should define a clear slim internal container (or more precisely a service-locator) interface.

After all what popped in my mind I feel that the current implementation of DIC independence adds more complexity and at the same time is taking away useful features that we assumed available when we were sure we were using Pimple (btw, i am not a Pimple fanatic, I just use it in some projects).

I didn't follow the whole #1179 discussion or other related discussions. If this argument was already largely discussed and "voted", feel free to close this. I surely don't want to cause any delay for the milestone release. These are just doubts that came to my mind.

kind regards

**Comment by akrabat** [comment]
I don't think your application should set anything new into the container after App is instantiated. If you choose to replace Slim's Request object with another one, then Slim will work, but your app needs to be written to target your new Request object or the PSR-7 baseline.

I'm happy with what we have at the moment.

**Comment by codeguy** [comment]
Same. We can revise for 3.x or 4.x later.

**Comment by designermonkey** [comment]
Now, I've been at odds with this approach myself for some time, and I remember discussing it with you before @codeguy, so forgive me for jumping in again here.

My preference would be to see the container filled by a `bootstrap.php` file which can be included in a project or replaced. There are enough exceptions through the codebase and the included components to show a developer what is missing and a bootstrap file can act as a guide, so it would seem to me that Slim can afford to be a little less opinionated in it's structure.

Container is a component of the framework, as is App, and all the other parts. Building contents of a container for an app to function is bootstrapping the app, so logically, it shouldn't happen inside one of the components, it should happen outside. All the container should do is employ the `Interop\Container\ContainerInterface` on top of `Pimple\Container`, not define it's own contents.

Even though Slim is small and powerful, which I love, it saddens me to see how tightly coupled it is with itself, when a few very minor changes can be made to make it so much more flexible.

**Comment by akrabat** [comment]
Not for 3.0 Maybe 3.x.
