### ISSUE TITLE
Middleware and ServiceProviders

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1288]
Just following on from a comment @silentworks made in #1275 about ServiceProviders.

> On a separate note can we stop coupling the ServiceProvider with the actual code for the package. I see this is becoming a pattern that others will follow. Now that we are using Container Interop, we shouldn't bind the actual package to the Pimple ServiceProviderInterface, we should create a separate class in each package to do this.

I think it was a very valid point, and something we should all discuss to make sure we come up with a convention to suit Middleware we create for Slim (which is available for other frameworks) and Middleware we use from other sources.

Details like this are useful to document for developers who come to the framework, and for ourselves.

One thing I'd like to bring to the fore is that there are two types of functionality at play here; We have Middleware which are invokable classes, and we have ServiceProviders which provide services via a container, we should be careful not to confuse the two, although a package could indeed provide both, ala Slim-HttpCache.
## ServiceProviders

If we opt for a separate ServiceProvider class, something like `PimpleServiceProvider`, then there would be a problem of how to instantiate a class with constructor options. Take the Slim-Flash package for example, it requires a `$storage` parameter in the constructor.

The only way I can see to do it is a bit of a long way round IMO

``` php

$flash = new Slim\Flash\Messages($_SESSION); // I know it's default, but for an example

$container->register(new Slim\Flash\PimpleServiceProvider($flash));
```

and in the `PimpleServiceProvider`

``` php
class PimpleServiceProvider implements Pimple\ServiceProvider
{
    protected $flash;

    public function __construct($flash)
    {
        $this->flash = $flash;
    }

    public function register(Container $container)
    {
        $container['flash'] = $this->flash;
    }
}
```

Is this a pattern everyone would be happy with? It seems a little backward to me as the `ServiceProviderInterface` is meant to be used directly in the class itself.
## Middleware

This is a simple one, though there are a few different implementations of Middleware out there. We opt for using `__invoke`, so maybe an interface would be a good idea?

An interface could define a class as invokable Middleware by requiring it to have a definite footprint.

``` php

public function __invoke(RequestInterface $request, ResponseInterface $response, $next = null);
```

Any additional arguments could be collected using `func_get_args()`.

I've set `$next = null` in the example, but personally I think that there should always be a `$next` available, even if it is a simple closure that returns the response as it is passed, but that's a preference.

**Comment by jensscherbl** [comment]
> Is this a pattern everyone would be happy with? It seems a little backward to me

Doesn't make much sense to me either. I'd do it like one of the following examples...

``` php
// application

$container->register(new \Slim\Flash\Provider($_SESSION));


// provider

class Provider implements \Pimple\ServiceProviderInterface
{
    protected $flashStorage;

    public function __construct($flashStorage)
    {
        $this->flashStorage = $flashStorage;
    }

    public function register(\Pimple\Container $container)
    {
        $container['flash'] = function ($container) {

            return new \Slim\Flash\Messages($this->flashStorage);
        };
    }
}
```

``` php
// application

$container['flashStorage'] = $_SESSION;

$container->register(new \Slim\Flash\Provider);


// provider

class Provider implements \Pimple\ServiceProviderInterface
{
    public function register(\Pimple\Container $container)
    {
        $container['flash'] = function ($container) {

            return new \Slim\Flash\Messages($container->get('flashStorage'));
        };
    }
}
```

``` php
// provider

class SessionProvider implements \Pimple\ServiceProviderInterface
{
    public function register(\Pimple\Container $container)
    {
        $container['flash'] = function ($container) {

            return new \Slim\Flash\Messages($_SESSION);
        };
    }
}
```

**Comment by jensscherbl** [comment]
> Middleware out there. We opt for using __invoke, so maybe an interface would be a good idea?

From my understanding, any callable implementing the expected signature can be a middleware, so not sure if an interface would really be that useful. Same would probably apply to controllers / route callbacks?

Are there any plans regarding [Relay](https://github.com/relayphp/Relay.Relay)?

**Comment by geggleto** [comment]
## Middleware

My problem with an interface is that we will lose the ability without some "magic" to do ... 

``` php
$app->add(function (...) {});
```

Slim is a micro-framework, and I think we don't need to wrap everything to objects.

**Comment by designermonkey** [comment]
I didn't mean we limit the use of middleware to the interface, only to use it more as a guide. Not a big deal though.

**Comment by piotr-cz** [comment]
Middleware interface would be helpful, but I like the option to define custom method instead of `__invoke`:

``` php
$app->add('menumanager:run');
```

This is helpful when storing Middleware as a service inside the container. By default Pimple checks if the `__invoke` method is available and passes container as an argument.

**Comment by akrabat** [comment]
I don't see much point in writing a class that implements `ServiceProviderInterface` when we can simply document the registration as:

``` php
$container['flash'] = function ($c) {
    return new \Slim\Flash\Messages;
};
```
