### ISSUE TITLE
cannot make slim work with nginx

### ISSUE THREAD

**Issue by valentinvieriu** [slimphp/Slim#129]
I am an nginx user, and I've tried to make it work with nginxrewrite. Is there some special thing to take into consideration when writing those rewrites?
here is my nginx config:

```
location / {
  root                              /var/www/new/Slim;
index  index.php index.html;

if (-f $request_filename) {
   break;
}

if (-d $request_filename) {
   break;
}
rewrite ^(.*)$ /index.php$1 last;



}  
```

This works for all routes but not for /

**Comment by codeguy** [comment]
If "/" is considered a directory, then you are breaking just before you hit the rewrite rule. Try removing the

```
if ( -d $request_filename ) {
    break;
}
```

code and see if it works then.

**Comment by hexa2k9** [comment]
I'm using Slim with nginx for quite a while. This is my rewrite which made me never have any problems (however - not a problem - my index.php still is called bootstrap.php):

```
location / {
  if (!-f $request_filename) {
    rewrite ^(.*)$ /bootstrap.php last;
  }
}
```

**Comment by valentinvieriu** [comment]
Thank you all. This was helpfull. I've managed to make it work.
Here is my config:

```
location / {
  root    /var/www/new/Slim;
      index  index.php;
    if (!-f $request_filename) {    
        rewrite ^(.*)$ /index.php$1 last;
    }
}  
```

It does not work if I don't add the $1 at the end of index.php. It gives me 404 ( slim 404 ) error on all pages.

Maybe you can add this on the front page for other to use it. 

Thank you again

**Comment by valentinvieriu** [comment]
One more thing I wanted to add: Because I am using php-fpm I needed to modify what goes to the fpm; notice the (.*)$ at the end is for Slim php

  location ~ .php(.*)$ {
      fastcgi_pass          unix:/var/run/php5-fpm.sock;
      include                   /etc/nginx/fastcgi.conf;
  }

**Comment by kkdg** [comment]
For my case, below code lines did the trick.

        location / {
                try_files $uri $uri/ @handler;
        }

        location @handler {
                rewrite / /index.php;
        }

**Comment by czmarcos** [comment]
hey huys, can anyone help me please? I'm new to slim and nginx

the root for my website is /var/www/html and is working fine, but I'd like to run slim on /var/www/html/api - which contains the files of slim and the api - and is not working.

what rewrite rule should I do in this case? I'd appreciate any help

**Comment by czmarcos** [comment]
hi guys, I'm new to nginx and slim.

I have a website with root files at /var/www/html - which is working fine - and my api is at /var/www/html/api - which contains my app index.php and all files. 

I tried to change my config, but it didn't work, when I hit any /api/v1/ url it is returning 404. Also, I have a router.php that includes my php files, that is why I have all the rewrite rules there.

This is my config. Thanks for any help.

```
# Default server configuration
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name xxx.xxx.x.xx;
        root /var/www/html;
        index index.php

        # nginx configuration

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
        rewrite ^/([a-zA-Z0-9_-]+)$ /router.php?pid=$1;
        rewrite ^/([a-zA-Z0-9_-]+)/$ /router.php?pid=$1;
        rewrite ^/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)$ /router.php?pid=$1&pid2=$2;
        rewrite ^/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/$ /router.php?pid=$1&pid2=$2;
        rewrite ^/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)$ /router.php?pid=$1&pid2=$2&pid3=$3;
        rewrite ^/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/$ /router.php?pid=$1&pid2=$2&pid3=$3;
        rewrite ^/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)$ /router.php?pid=$1&pid2=$2&pid3=$3&pid4=$4;
        rewrite ^/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/$ /router.php?pid=$1&pid2=$2&pid3=$3&pid4=$4;
        rewrite ^/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)$ /router.php?pid=$1&pid2=$2&pid3=$3&pid4=$4&pid5=$5;
        rewrite ^/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/([a-zA-Z0-9_-]+)/$ /router.php?pid=$1&pid2=$2&pid3=$3&pid4=$4&pid5=$5;
}

        location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
         }

        location /api/ {
        alias /var/www/html/api/v1/;
        try_files $uri /api/v1/index.php =404;

        location ~ \.php$ {
           try_files $uri /index.php =404;
           fastcgi_split_path_info ^(.+\.php)(/.+)$;
           fastcgi_index   index.php;
           fastcgi_pass    unix:/var/run/php5-fpm.sock;
           include         fastcgi_params;
           fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
         }
    }
      
}
```
