### ISSUE TITLE
Can I deploy slim 3.0 on production environment now?

### ISSUE THREAD

**Issue by zyx-rd** [slimphp/Slim#1297]
Hi guys,

First, thanks to all guys who contribute to Slim, it's perfect php framework i want to use for my project.
What's the time to release Slim 3.0? 
I noticed that 3.0 would be release the first week of June before.
So what's the exact time? 
Should I wait for?

Thanks,

**Comment by akrabat** [comment]
Having found what we thought was the last show-stopper for beta1 (uploaded files), we found another one (optional route parameters).

I'm hoping we'll have a decision on the approach we'll be taking this week, so we can can find someone to implement the required changes. Then we'll have an idea of when we can release beta1.

**Comment by Melbournite** [comment]
@zyx-rd 

To give you some piece of mind, I've been building an application on the dev branch for the past couple of weeks to get my head around how different it all is (things are quite different IMO).

Besides the optional route bug, I've not found any problems as yet. I don't think there are plans for any new features, either. Generally, the branch is pretty stable. Obviously, developing on a dev branch is of course always a little risky though :)

Will be interested to see what is decided on the routing bug. Real shame with the optionals not working.

**Comment by geggleto** [comment]
The router dependency has been updated. #1289
