### ISSUE TITLE
Error in documentation for Slim 1.5.0

### ISSUE THREAD

**Issue by valentinvieriu** [slimphp/Slim#130]
I don't see any wiki for the documentation for Slim 1.5.0 so I will post an issue

In the section Configure Slim for a specific mode you've missed a closing ")"

$app->configureMode('production', function () use ($app) {
    $app->config(array(
        'log.enable' => true,
        'log.path' => '../logs',
        'debug' => false
    ) ); // here is the missing )
});

also please review the development mode too

Thank you for your work

**Comment by codeguy** [comment]
Thanks! Fixed. I'm not able to create internal reference links with the GitHub Wiki (it's a known bug... not sure when to expect a fix). For now I've moved the docs elsewhere to make it easier for readers to navigate the docs.
