### ISSUE TITLE
[Develop] Fast-Route fails to install via Composer

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1308]
For now you need to add ...

```
"minimum-stability": "dev"
```

To your composer.json for slim to install

[Edit] or add

```
"nikic/fast-route": "dev-master"
```

to your main composer.json

**Comment by GrahamCampbell** [comment]
> "nikic/fast-route": "dev-master"

dev-master is always a bad idea. You should use a proper version constraint.

**Comment by geggleto** [comment]
100% agree, but a hack is required so our users can alpha our development branch.

**Comment by akrabat** [comment]
@GrahamCampbell: There isn't a version tag for the feature we need yet…

**Comment by mnapoli** [comment]
@GrahamCampbell I think the point is that Slim currently requires dev-master: https://github.com/slimphp/Slim/blob/develop/composer.json#L34 (which is the problem)

**Comment by GrahamCampbell** [comment]
> There isn't a version tag for the feature we need yet…

So, you can still use a version constraint?

**Comment by GrahamCampbell** [comment]
Example. Laravel 5.2 isn't tagged for another 5 months, but you can still install it with `5.2.*` provided you either include a dev annotation or lower your minimum stability.

**Comment by akrabat** [comment]
@GrahamCampbell explain please? If we set composer.json to `"nikic/fast-route": "^0.5",`, how do we guarantee that composer installs the tip of master and _not_ the 0.5 tag?

**Comment by GrahamCampbell** [comment]
Well, you want `^0.6` surely?

**Comment by GrahamCampbell** [comment]
Hmm, it seems fast route hasn't got any branch aliases. I'll send a PR...

**Comment by geggleto** [comment]
@GrahamCampbell 
- Installing nikic/fast-route (v0.5.0)
  Loading from cache

with `^0.5` ;(

**Comment by mnapoli** [comment]
@GrahamCampbell The branch alias will not make the branch be considered as stable by Composer or am I missing something?

In other words, requiring a branch is the same as requiring master, it's still `dev` stability level.

**Comment by GrahamCampbell** [comment]
@geggleto You need `^0.6`, though they've forgotten to add a branch alias. As I said' I've PRed a fix.

**Comment by GrahamCampbell** [comment]
> The branch alias will not make the branch be considered as stable by Composer or am I missing something?

No, the branch alias allows you to install a non-stable version by telling composer what version the branch represents.

**Comment by geggleto** [comment]
Ah ok, that explains the version not found error for ^0.6

**Comment by mnapoli** [comment]
The branch alias [you proposed](https://github.com/nikic/FastRoute/pull/57/files) is `0.6-dev` -> it's a dev version. I really don't think Composer will consider a branch as a stable/tag release. Maybe I'm wrong though.

**Comment by GrahamCampbell** [comment]
It doesn't consider it a stable tag. Why would it have to though?

**Comment by geggleto** [comment]
@GrahamCampbell So we can remove minimum-stability requirement from our project.

**Comment by mnapoli** [comment]
The whole problem is that if you have package A requiring Slim, then you have to explicitly allow minimum-stability: dev for it to work. This is because [Slim requires a dev version of FastRoute](https://github.com/slimphp/Slim/blob/develop/composer.json#L34).

To solve the problem, we need Slim to require a stable version of FastRoute, that way package A can require `slim/slim: develop@dev` without having to change the minimum-stability.

**Comment by GrahamCampbell** [comment]
>  slim/slim: develop@dev

NOOOOOO!

**Comment by GrahamCampbell** [comment]
`"slim/slim": "3.0.*@dev"` would be fine. Anything that's not a version constraint is essentially, wrong.

**Comment by mnapoli** [comment]
or `3.0.x-dev` whatever… that's the same! it's a dev version, not a tag. But whatever that's not the subject.

Edit: `3.0.x-dev` isn't really a version constraint. Anyway, we are talking about people trying out the future version, that's fine…

**Comment by GrahamCampbell** [comment]
`3.0.x-dev` is wrong too! That's NOT a version constraint!

**Comment by mnapoli** [comment]
whatever! That's not the issue :)

And `3.0.*@dev` isn't a tag too…

**Comment by GrahamCampbell** [comment]
> And 3.0.*@dev isn't a tag too…

So? I'm not talking about tags.

**Comment by mnapoli** [comment]
Right! Anyway, try to require Slim v3, and you'll see that you have to add a `minimum-stability` because of the FastRoute requirement, which is annoying. That's the issue :)

**Comment by GrahamCampbell** [comment]
Does `prefer-stable` true do what you want?

**Comment by geggleto** [comment]
it just might...

**Comment by geggleto** [comment]
#1314 :)

**Comment by silentworks** [comment]
Ok we now have a tag. This should no longer be an issue.
