### ISSUE TITLE
How to append data to view before any router?

### ISSUE THREAD

**Issue by zyx-rd** [slimphp/Slim#1309]
In slim2.x, we can $app->view->appendData([xx]) in before middleware, how to do that in slim3 + slim/twig?

thanks.

**Comment by Melbournite** [comment]
Maybe see here: http://docs-new.slimframework.com/concepts/middleware/

```
$response->write('BEFORE');
$response = $next($request, $response);
$response->write('AFTER');
```

To append something in Twig:

```
$app->view->offsetSet('key', 'value');
```

Return:

```
{{ key }}
```

**Comment by zyx-rd** [comment]
it works, Thanks @Codexing
