### ISSUE TITLE
Error: mdecrypt_generic() An empty string was passed

### ISSUE THREAD

**Issue by adrianmg** [slimphp/Slim#131]
I get this error from a very very basic example (require + init + run):

<pre>Message: mdecrypt_generic() [function.mdecrypt-generic]: An empty string was passed
File: lib/Slim/Http/CookieJar.php
Line: 361</pre>

My code in index.php is just:

<pre>require 'lib/Slim/Slim.php';
Slim::init();
Slim::run();
</pre>

I am using master branch with MAMP 1.9.6.1 with PHP 5.3 and all extensions activated but it doesn't work :(

**Comment by adrianmg** [comment]
As I supposed if you change the init settings it works fine:

<pre>cookies.encrypt = false</pre>


All is ok now.

**Comment by codeguy** [comment]
Pull from master and try again. I've changed CookieJar to avoid encrypting empty values. The Cookies are still secure/signed.

**Comment by adrianmg** [comment]
It is ok now! Glad to contribute :)
