### ISSUE TITLE
[Develop] Composer and FastRoute

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1313]
In relation to: #1308 

In the short-term I believe we have 2 options when it comes waiting for a tag for fast-route.

1) We fork fast route and tag it ourselves

2) We setup composer to pull that branch only (unsure if we still need the dev-stability)

**Comment by geggleto** [comment]
2)  still required minimum-stability

**Comment by mnapoli** [comment]
I'd say no need to duplicate the discussion from #1308

**Comment by akrabat** [comment]
Agreed.
