### ISSUE TITLE
Use Slim3 in production now

### ISSUE THREAD

**Issue by zyx-rd** [slimphp/Slim#1319]
Hi guys,

I don't know when slim3 will be released, but I can't waiting for.
Bless I needn't rework any code when slim3 version is released. :100: 

thanks all.

**Comment by silentworks** [comment]
This should mostly remain the same as it currently is from the api perspective, I think we currently only have 1 issue which is asking for a change to the urlFor #1316. Leave a comment over there if this will affect you in a big way please.
