### ISSUE TITLE
Empty string as root route for group

### ISSUE THREAD

**Issue by dopesong** [slimphp/Slim#1324]
Slim3 route now no longer support just slash as root route:

``` php
$app->group('/foo/bar', function () use ($app) {
    $app->get('/', 'FooBar:action');
    $app->get('/bar', 'FooBar:actionbar');
});
```

In order to get it work you have to keep string empty which is wrong while all other routes begins with slash

``` php
$app->group('/foo/bar', function () use ($app) {
    $app->get('', 'FooBar:action');
    $app->get('/bar', 'FooBar:actionbar');
});
```

**Comment by silentworks** [comment]
I think what we have currently is and should be considered the correct behaviour, my reason for this is if you look at anything in a group from the perspective of they all end without a slash, then the first item would be correct as it ends without a slash.

Groups are just prefixes, so they get prefixed onto each route nested within them, so in essence what the routes in the second example look like would be:

```
/foo/bar
/foo/bar/bar
```

**Comment by opengeek** [comment]
Does it work as `[/]`?The real problem IMO, is that the trailing slash should **always** be optional if defined on the route with matches without the trailing slash redirecting (301) to the URL with the trailing slash. If not always, there should be an option to enable this behavior. It is expected behavior from using Slim v2 and should be easily accomplishable without defining every trailing slash as optional.

**Comment by geggleto** [comment]
Is the real problem not what we get for pattern matching in FastRoute ?

**Comment by designermonkey** [comment]
So, let me get this right, if I want to define a route for my homepage, I have to use `$app->get('', 'FooBar:action');` and not `$app->get('/', 'FooBar:action');`? That sounds weird for me.

Though, hasn't the grouping changed now from the initial examples?

**Comment by geggleto** [comment]
@designermonkey only if you have a group at the root level...

**Comment by akrabat** [comment]
Given that we use fast route, I'm unclear how this could be changed.

**Comment by designermonkey** [comment]
So, there is a different style for a route group, and a single route? `''` vs `'/'`? That's just weird.

Consistency is key.

**Comment by akrabat** [comment]
We want a fix for this before RC1

**Comment by silentworks** [comment]
I suggest we trim the `/` on the group path before passing it over to FastRoute.

**Comment by akrabat** [comment]
The top-level issue is fixed. Not sure we can change the example in the initial report.

**Comment by designermonkey** [comment]
> Not sure we can change the example in the initial report.

Do you mean the initial report in this thread? I can confirm all is fixed as far as I can see...

**Comment by silentworks** [comment]
Yep every possible scenario is fixed, this is back to working as Slim 2 was.
