### ISSUE TITLE
Problems with HTTP_HOST containing IPv6 adress

### ISSUE THREAD

**Issue by Robbilie** [slimphp/Slim#1325]
when the said server var contains an ipv6 adress it splits the adress after the first  ":" (like before the port in ipv4 adress) which does not make any sense with an ipv6 adress

**Comment by akrabat** [comment]
Hi,

Are you seeing this in version 2 or the upcoming version 3?

**Comment by Robbilie** [comment]
"slim/slim": "~2.6.2"
