### ISSUE TITLE
Slim_Http_Cookie could not be loaded

### ISSUE THREAD

**Issue by valentinvieriu** [slimphp/Slim#133]
Fresh dev pull using Twig as a template ( I'm on a Mac using Mamp 1.9.1 ) and I get this error in php_error.log:

PHP Fatal error:  spl_autoload() [<a href='function.spl-autoload'>function.spl-autoload</a>]: Class Slim_Http_Cookie could not be loaded in /Users/valentinvieriu/Sites/new.carteapenet.local/lib/Slim/Slim/Http/CookieJar.php on line 285

My index.php is simple and basic and home.html is just hello world text.

<?php

require 'lib/Slim/Slim/Slim.php';
require 'lib/TwigView.php';
$app = new Slim(array(
  'view'=>'TwigView'
));

$app->get('/', function () use ($app) {
    $app->render('home.html');
});

$app->run();

The page is displayed, but I get this error in the log

**Comment by codeguy** [comment]
I'll take a look at this as soon as I'm back from the honeymoon on June 13th. If anyone can look at this sooner, that'd be great.

**Comment by MatthewCallis** [comment]
Can you try this and see if the error persist?

```
Slim::init(array(
    'view' => 'TwigView'
    'cookies.encrypt' => false,
    'session.handler' => null
));
```

**Comment by valentinvieriu** [comment]
that worked! But what it's strange now is that after removing those lines, works too.
I am using the development branch so it's 
$app = new Slim(array(
  'view'=>'TwigView',
  'cookies.encrypt' => false,
  'debug' => true, .....

Thank you guys for the feedback and good luck @codeguy in your honeymoon :)
