### ISSUE TITLE
Slim loops seemingly forever when Error is thrown after update to xdebug 2.3.3

### ISSUE THREAD

**Issue by flyon** [slimphp/Slim#1332]
All I changed today is upgraded my xdebug version to php_xdebug-2.3.3-5.4-vc9-x86_64.dll
Now everytime my Slim based API throws an error it seems to loop forever somehow.
when I debug with my editor everything goes well untill the very end of `public function call` in `PrettyExceptions.php`, once it returns from that function, my editor stops debugging and looks like the thread is done, however Chrome keeps showing 'pending' and when I re-execute the HTTP request nothing happens.

**Comment by geggleto** [comment]
what version of slim ? is it the 2.x branch or 3.x ?

Thanks

**Comment by flyon** [comment]
2.4.2

**Comment by geggleto** [comment]
This does not sound like a slim bug, but i am not an expert on xdebug either... 
//cc @akrabat @silentworks @codeguy

**Comment by akrabat** [comment]
Please test with latest version of Slim 2.

**Comment by akrabat** [comment]
As Slim 3 is released, we are only fixing Security issues on Slim 2.
