### ISSUE TITLE
v3 docs containers

### ISSUE THREAD

**Issue by Lewiscowles1986** [slimphp/Slim#1336]
In the v3 docs when describing how to setup a custom handler for 404, the code provided does not work, and is ambiguous.

``` php
$app['notFoundHandler'] = function ($c) { return function ($request, $response) use ($c) { return $c['response']->withStatus(404) ->withHeader('Content-Type', 'text/html') ->write('Page not found'); }; };
```

It should be

``` PHP
$c = new \Slim\Container();
$c['notFoundHandler'] = function ($c) {
    return function ($request, $response) use ($c) {
        return $c['response']->withStatus(404) ->withHeader('Content-Type', 'text/html') ->write('Page not found');
        };
};
$app = new \Slim\App($c);
```

This way you show syntax, add context, and due to the formatting, it's easier to read what it does.

Other things I think would be cool to document would be that without return in the callback, you will get an error, and as many exceptions as can be documented as to possible root causes.

Of course, I am happy to document, but there is a part-2 (sorry)

It might also be good to add some helper methods to the app `notFound` method, `error` method, and `notAllowed` method in `\Slim\App` would make this super-easy to read and understand; just for ease of use and readability.

:crying_cat_face: 
[Slim v2 had it](http://docs.slimframework.com/errors/404/)

**Comment by geggleto** [comment]
I am on the fence about adding helpers for notFound, Error and notAllowed... but I do see them as helping people migrate from v2 to v3. Having said that I will create a new issue for that discussion.

//cc @akrabat @silentworks I PR'd the docs repo with the updated code and this can be closed.
