### ISSUE TITLE
Make Trailing Slash Redirects Configurable

### ISSUE THREAD

**Issue by HughxDev** [slimphp/Slim#1340]
Hi,

I don't want requests to `/user` to do a 301 Redirect to `/user/`. I consider those to mean different things, i.e., `PUT /user` replaces a resource named "user", while `PUT /user/` would replace all resources under "user".

This happens even if I have only defined `$app->put('/user')` without the trailing slash, which leads the 301 to ultimately resolve to a 404.

I realize the 301 behavior is useful in other approaches to API design so I would like to be able to flip a switch in the config to turn this behavior off. It was very confusing to me why this was happening as I had not set up anything but the bare minimum RewriteRules in .htaccess.

**Comment by akrabat** [comment]
Which version of Slim are you using ?

**Comment by tuupola** [comment]
It might be Apache [DirectorySlash setting](http://httpd.apache.org/docs/2.2/mod/mod_dir.html#directoryslash) doing the redirect. Try setting it off.

```
DirectorySlash Off
```

**Comment by HughxDev** [comment]
@akrabat Slim 2.6.2. On Windows 7 x64 under XAMPP if that helps.

@tuupola I did not know about that directive, thanks. I turned it off, but while the endpoints no longer redirect, they only return blank responses with `200 OK`. Here are the results of some tests I ran:
- `$app->get('/users/me')` + `GET /users/me` = `200 OK`, `text/html`, blank page
- `$app->get('/users/me')` + `GET /users/me/` = `404 Not Found`, `text/html`, Slim Error Page
- `$app->get('/users/me/')` + `GET /users/me` = `200 OK`, `text/html`, blank page
- `$app->get('/users/me/')` + `GET /users/me/` = `200 OK`, `application/json`, JSON results as intended

The second and last results are the only ones that make sense.

It also seems that turning `DirectorySlash` on or off has no effect.

**Comment by akrabat** [comment]
We are not intending to change Slim2's behaviour at this point.

**Comment by HughxDev** [comment]
Why not? Shouldn't developers be able to design their APIs the way they want to? A configuration setting  to turn redirects on or off that defaults to the existing behavior wouldn't break any existing uses, but it WOULD give people a choice to honor REST principles if they are so inclined.

**Comment by silentworks** [comment]
@hguiney is this behaviour still the same in Slim 3? If yes send a PR to that please, we are only currently taking security fixes for Slim 2.

**Comment by tuupola** [comment]
Here is [original discussion](https://github.com/slimphp/Slim/issues/31) concerning the current behaviour.
