### ISSUE TITLE
Middleware for group?

### ISSUE THREAD

**Issue by Lewiscowles1986** [slimphp/Slim#1341]
Hello again :smile: 

> Note this is for Slim 3

Looking at docs on [Middleware](http://www.slimframework.com/docs/concepts/middleware.html), and [Router](http://www.slimframework.com/docs/objects/router.html); I feel routes for group, and middleware for all the three scenarios I can think of (app, route, group with callable (anon) and class), could benefit from notes on.
- authoring groups for routing - _and expected behaviour_
- combining groups with middleware

It is amazing that this works (I nearly asked if it could be done, but decided to test rather than ask), and can be seen in the below code sample, which is tested as working with `slim/slim:3.0-beta1`

``` php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new \Slim\App();

$app->group('/utils', function () use ($app) {
    $app->get('/date', function ($request, $response) {
        return $response->write(date('Y-m-d H:i:s'));
    });
    $app->get('/time', function ($request, $response) {
        return $response->write(time());
    });
})->add(function ($request, $response, $next) {
    $response->write('BEFORE');
    $response = $next($request, $response);
    $response->write('AFTER');

    return $response;
});
```

Happy to contribute this to docs, unless anyone else wants to? **_(not like this)**_, properly written up

**Comment by silentworks** [comment]
No stopping you now @Lewiscowles1986 you already on a roll with documentation, so if you see anything lacking, go ahead and send a PR.

Thanks again for your continuous contribution to this project.

**Comment by realart** [comment]
This functionality is actually very handy - no need to attach group-related middle-ware to each route within a group.

**Comment by Lewiscowles1986** [comment]
First part done, work catching up with me though :+1: 

https://github.com/slimphp/Slim-Website/pull/21

**Comment by Lewiscowles1986** [comment]
It looks like I forgot where I was with it... Pull request is still active...

Why is this closed?

**Comment by akrabat** [comment]
Docs aren't in this repo. So you can continue working on the PR and additional docs on https://github.com/slimphp/Slim-Website.

**Comment by Lewiscowles1986** [comment]
:+1: :wink: oh yeah haha
