### ISSUE TITLE
Unable to include php file in parent directory in templates

### ISSUE THREAD

**Issue by imdreamrunner** [slimphp/Slim#1347]
This is for Slim 2.

I am trying to calling a template in a sub folder say `member/login.php`. In the `login.php` file, if I try to call `include '../header.php'`, the "failed to open stream: No such file or directory" error will occur.

Thanks.

**Comment by akrabat** [comment]
PHP keeps track of its current directory and references file from there.

Try:

``` php
include __DIR__ . '/../header.php';
```

**Comment by imdreamrunner** [comment]
Thanks a lot. You solved my problem!

**Comment by Safnaj** [comment]
@akrabat Could you please help me in a issue ??
I need to include header.php which located in public/includes directory to register.php (public/)

![Error](https://user-images.githubusercontent.com/37530024/60659832-ff1c8e80-9e73-11e9-95b1-0d0c90f3316c.jpg)

**Comment by akrabat** [comment]
@Safnaj Your question is better asked on our [Slack](https://www.slimframework.com/#community) and/or our [discourse forum](http://discourse.slimframework.com/).

**Comment by Safnaj** [comment]
@akrabat Its not related to Slim Framework.. Its my common issue.. I found this issue via Google. Could you please answer here ??

**Comment by carc1n0gen** [comment]
@Safnaj that's exactly  he suggested slack or discourse.  This is a place for reporting bugs, not getting help with your own code
