### ISSUE TITLE
making intermittent cron tasks in slim

### ISSUE THREAD

**Issue by savdeep** [slimphp/Slim#1349]
Hi,

Is there any way to make intermittent cron tasks in slim? I don't want to use routing as these crons will run on same server only. Help appreciated.

**Comment by savdeep** [comment]
@codeguy, i read it in your interview somewhere that its possible and you use slim to run your crontasks. But, unfortunately i am not able to find out how i can use slim for same?

**Comment by mbretter** [comment]
You have to set the mock environment:

$app->container->singleton('environment', function ($c)
{
    return \Slim\Environment::mock();
});

**Comment by savdeep** [comment]
Thanks @mbretter , I have set the environment. It now shows me 404 html content on console

**Comment by mbretter** [comment]
You cant use the conventional slim routing features on the console. I make it this way:
$app = new \Slim\Slim();
$app->container->singleton('environment', function ($c)
{
    return \Slim\Environment::mock();
});
$x = new \Whatever\MW1();
$x->setApplication($app);
$x->call();

$x = new \Whatever\MW2();
$x->setApplication($app);
$x->call();

...

I'm invoking the Middlewares manually, without using $app->run()

**Comment by silentworks** [comment]
@savdeep checkout this blog post http://akrabat.com/run-a-slim-2-application-from-the-command-line/

**Comment by savdeep** [comment]
@silentworks , @mbretter Thanks a ton. saved me many hours.
