### ISSUE TITLE
When downloading source, .htaccess file not included.

### ISSUE THREAD

**Issue by NimbleHost** [slimphp/Slim#135]
This isn't a deal breaker by any means, but it looks like the .htaccess file is not being included with the rest of the files when downloading the source code via the Github website (or via the link on slimframework.com site). Again, no biggie, as it can be manually created easily, but it threw me for a loop initially when I couldn't find it. 

Of course, if I've missed something really simple, please do let me know.

**Comment by tinnet** [comment]
Works for me?
I just tried all links, the .htaccess was always included (in the main folder, same as index.php) . Could it be a problem with "show hidden files" on your end NimbleHost?

**Comment by NimbleHost** [comment]
That was the first thing I checked, and "show hidden files" is enabled - or so I thought. It was turned on in Transmit, but not in Finder. Sorry for the false alarm.

**Comment by codeguy** [comment]
@NimbleHost Glad you got it worked out. @tinnet Thanks for stepping in. Just returned from my honeymoon in St. Lucia. Will be catching up on emails over the next few days.

**Comment by NimbleHost** [comment]
@codeguy Welcome back~ Hope you had a great time, and...Congratulations!
