### ISSUE TITLE
UploadedFile->moveTo() - specify filename?

### ISSUE THREAD

**Issue by mgansler** [slimphp/Slim#1368]
Hi guys,

maybe I just overlooked how to do it, but I could not find a way to specify the file name when I want to move an uploaded file.

The current implementation of Slim 3 always uses the name provided by the client, one can only specify the target directory.
http://www.php-fig.org/psr/psr-7/ is not very clear on this subject.
On the one hand, the parameter for moveTo is called `$targetPath`, on the other there is an example, where the path AND filename are passed to the function.

Martin

**Comment by opengeek** [comment]
Confirmed—this appears to be a bug. PR shortly...

**Comment by mgansler** [comment]
Works as expected.
