### ISSUE TITLE
Multiple Slim apps and .htaccess

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#137]
From user:

"I have a current setup where I have created 2 instances of Slim, I wanted to keep them in separate files so I can keep the logic separate. I moved one file to a directory called admin and left the other at the root, i modified the .htaccess file to access the admin directory, but as soon as I hit the url I get a 404 Page not found error produced by Slim. The .htaccess is working because it accesses the file I want to in admin, if I write a echo in the file, i see it on the 404 page. I hope this is enough information for you to help me with."

**Comment by silentworks** [comment]
Hi codeguy just so you know I have worked this out now and its not a bug, it was a problem with my .htaccess rules. I will leave the ticket open as  I will be writing up a post of how to multiple instances of slim on one project. I am currently using it for a CMS backend and a front controller at the same time.

**Comment by codeguy** [comment]
@silentworks Great. Be sure to tweet a link to your article and I'll be happy to spread the word. Closing this out to keep the Issues area specifically for open problems. I follow you on Twitter so I'll see it once you post it to the web.
