### ISSUE TITLE
Way to add Middleware to ALL routes

### ISSUE THREAD

**Issue by yurevichcv** [slimphp/Slim#1373]
I'm migrating from Slim 2 to Slim 3 right now and trying to find elegant solution to replace "slim.before.dispatch" hook. I used in together with my ACL to check if guest/user has permission to access specific route name this way (simplified version):

```
$app->hook('slim.before.dispatch', function () use ($app, $acl) {
   $route = $app->router()->getCurrentRoute());
   if (!$acl->isAllowed('guest', $route->getName())) {
      //forbidden
   }
}
```

Currently I can not use application Middleware, because route is not dispatched yet, and therefore I don't know it's name.

The only way I have now is to add same Access Control Middleware to EACH route. This way I will have access to `$request->getAttribute('route')`.

I guess it should be some straightforward way to add Middleware for ALL routes.

**Comment by geggleto** [comment]
What you likely want is a ~~route~~ group middleware.
Groups are basically wrappers around urls to add middlewares.

``` php
$app->group('/', function (...)  use(...) {
    //Your site's routes

})->add(function ($request, $response, $next) {
    $route = $request->getAttribute('route');
    //do stuff
});
```

**Comment by yurevichcv** [comment]
I don't like above solution for few reasons:
1. I don't want to use "/" group for all my routes. Each of my routes has it's own groups ("/auth", "/user", etc). I guess this way it should be empty group: `$app->group("")`
2. This will require to define all routes in one file (or again, set middleware for each group definition).
3. Not sure about this, but this solution might be not optimal in terms of performance (adding groups, concatenation of patterns, iterations over groups, etc).

This is temporary solution I've found for myself, which is far from good (needs iteration over all routes, instead off adding middleware directly to dispatched route):

```
$router = $c->get('router');
foreach ($router->getRoutes() as $route) {
    $route->add(function (Request $request, Response $response, $next) use ($c) {
        ....
        ....
        $next($request, $response);
    });
}
```

Any other ideas? :)

**Comment by geggleto** [comment]
The above solution should be fine if you limit the number of routes in your app by inspecting the Envrionment and only loading routes based upon the resource URI that is being accessed.

Example (Using $_SERVER):

```
if (strpos($_SERVER['REQUEST_URI'], '/auth') !== false) 
{
    //Load /auth routes here
}

```

Then the cost is not exactly a lot, since you are only applying mw to a subset of the routes, and you are also only ever adding a subset of those routes. You can expect to get a fair amount of performance increase using this type of strategy [in larger applications].

I hope this helps!

**Comment by yurevichcv** [comment]
This way I will require a lot of this "if" statements :) On my opinion this logic of optional routes loading should be handled by groups.

Currently main problem of `$app->group` is that it immediately invokes callable. It will be great to implement lazy loading for group callable. This way it will be invoked only during dispatching process and only routes belonging to the group will be loaded.

**Comment by geggleto** [comment]
The problem would come into play if you tried to make a sub-request to a route that was in a group.
So then we would need to keep track of what groups were initialized or not... Another can of worms :)

**Comment by yurevichcv** [comment]
Yes, it will be required to register all groups with their patterns. And invoke their callable if pattern was found either in main request or in sub-request. But you are right, this will definitely require a lot of changes in routing architecture. But it definitely worth to be implemented some day, as it is critical moment for big applications with hundreds of routes.

Still didn't found good solution for my initial problem.

**Another interesting idea.**

Currently Slim architecture works following way if we have App and Route middleware:
`Start` -> `App Middleware` -> `Dispatching process` -> `Route Middleware` -> `Route` -> `Route Middleware` -> `App Middleware` -> `Finish`

New approach:
`Start` -> `Dispatching process` -> `App Middleware` -> `Route Middleware` -> `Route` -> `Route Middleware` -> `App Middleware` -> `Finish`

Idea here is that `App Middleware` (first part) will run after dispatching process. This way we will always have `$request->getAttribute('route')`. 

Main question is: are there any possible scenarios that may require to run middleware before dispatching? I can't find any.

**Comment by geggleto** [comment]
In my use case, I have a simple check to see if the user has the correct permissions to view the resource. I set that an app level and I inspect the request_uri and compare it to what is loaded into that users session.

If there is not, I return a 401 and do not continue the chain.

It is slight different than your use-case above.

**Comment by akrabat** [comment]
See #1357

**Comment by tuupola** [comment]
Instead of using the route name for checking authorization you can currently use the request uri instead.

**Comment by yurevichcv** [comment]
@tuupola Preferred approach is to use uri only in routes definition. And everywhere else to use route name. Because uri might change in future, and this way you will need to change it only in one place. Also, uri can by dynamic and use different regex patterns and parameters. This is why `pathFor` and `urlFor` methods are so valuable, as well as `getNamedRoute`.

**Comment by yurevichcv** [comment]
@akrabat @geggleto But what do you think about app middleware running after dispatching process? I guess it could have solved a lot of problems for many developers. This way in all Middlewares we will always have `$this->getAttribute('route')`.

Personally I can not imagine any possible and necessary scenarios of middleware required after `$app->run()`, but before dispatching. All configurations of container can be done before `$app->run`.

**Comment by yurevichcv** [comment]
I see, @AlexStansfield in his pull request #1357 proposed almost exactly the same... I think it is really nice solution.

**Comment by AlexStansfield** [comment]
My ears were burning :) 

I understand that you can access the request uri from the app middleware, but that is still pretty limiting.

So this is a feature I'd really like to see (hence #1357). I'm not sure if it's the best solution or if there are some problems that I overlooked, but would appreciate some eyes on it if I'm not the only one who needs it.

**Comment by poolslick2002** [comment]
Personally for me it makes sense to have the app middleware before dispatch:
- dealing with insensitive routes
- having a lang route segment (/about; /en/about; /fr/about; /de/about) - I can a have a middleware that sets the app lang and removes that first segment before dispatching to "/about"
  etc...

But I also agree that it would be nice to have a mechanism to attach an app middleware after the dispatch process and be able to do $request->getAttribute('route')

**Comment by yurevichcv** [comment]
@poolslick2002  For this purposes you don't need Middleware, you need to override Router. Actually, possibility to override Router completely replaces necessity to have Middleware before dispatching.

**Comment by yurevichcv** [comment]
@poolslick2002 You can also use regex and optional params in your routes: 

```
$app->group("[/{lang:en|de|fr}]", function() use ($app) {
   $app->get('/about', function() {
      ...
   });
})
```

**Comment by akrabat** [comment]
@yurevichcv I see you are proposing more complex solutions to @poolslick2002, having rejected the more complex solution of a route group for yourself…

**Comment by akrabat** [comment]
Maybe $app->add() should take a new last parameter of $afterDispatch which defaults to false. Then if you wanted the middleware to run after dispatch, you set it that parameter to true when adding the middleware?

**Comment by poolslick2002** [comment]
@akrabat this would be an elegant solution

**Comment by yurevichcv** [comment]
@akrabat I don't propose complex solution. I just think, that if you want to make any modifications of $uri - you should handle it inside custom Router. In my problem I have ACL-checks and it is not router-related.

Regarding you proposal about optional param - it is great, but this way MiddlewareAwareTrait will be different for app and routes. As well as it will require 2 middleware stacks for app.

**Comment by geggleto** [comment]
@akrabat then are we not just implementing hooks?
I'm okay with that, I would think that they have some use cases.

Pros: more granularity of the execution of the application
Cons: more complicated dispatch process
Seems like a non-starter to me

Hooks:
Before / After Dispatch
Not before / after route cause that actually is a middleware

**Comment by akrabat** [comment]
_shrugs_ All I'm saying is that a solution needs to be pragmatic for people who currently rely on the current behaviour as well.

Another option is to have the ability to force a new dispatch after app middleware is run. That is, we dispatch at the start and store the route information to the request's attributes. If after the app middleware is run we check for the route information and if it's missing, we dispatch again.

**Comment by akrabat** [comment]
Hooks are like middleware but not quite. Generally, I would like new users to only have to learn middleware.

**Comment by yurevichcv** [comment]
On my opinion the best solution will be to put middleware call after dispatching.

And not break backward compatibility it is possible to do the following:
1. Dispatch route (get route info and set it inside $request->setAttribute('route', $route))
2. Run Middleware
3. If after Middleware run $uri was modified - dispatch route again (for people who currently rely on the current behaviour)

**Comment by AlexStansfield** [comment]
@akrabat my solution did that. The route information is put into routeInfo attribute on the request. If once we get into __invoke in the app the routeInfo is missing then dispatch is done again. See https://github.com/slimphp/Slim/pull/1357/files#diff-eb6c3386171c6f5318119100a52f3db7R374

**Comment by yurevichcv** [comment]
@AlexStansfield I guess your solution doesn't have backward compatibility. In you code 'routeInfo' will always be in place if someone doesn't set it to NULL explicitly inside Middleware.

**Comment by AlexStansfield** [comment]
@yurevichcv yeah sorry, I didn't read your comment properly as I was responding to @akrabat. But I could modify my PR to check if the routeInfo is missing or if the uri has changed. If either of these then dispatch again.

**Comment by JoeBengalen** [comment]
Instead of implemented such logic that makes it just more complicated, can't you just introduce a single  configuration option (something like `callMiddlewareBeforeDispatch`) to indicate what behaviour you want? This seems to me like a much simpler implementation

**Comment by poolslick2002** [comment]
There is already middleware that is called after dispatch - it is the route level middleware - there is also a way to attach it to multiple routes - using groups - why remove flexibility by also moving the app level middleware after the dispatch?

Need something attached to every route? iterating over all routes makes sense for me.. 

Or lets add another middleware stack (eg: router level middleware) or find a better way to attach them to all routes - but don't modify a perfectly good functionality.

**Comment by AlexStansfield** [comment]
@yurevichcv I've updated my #1357 so that if the URI is changed in middleware then dispatch is run again.

@poolslick2002 I'm not sure how we've removed any flexibility. 

@JoeBengalen I don't think the solution has really made things more complicated. But I'm happy to go with a configuration option that will allow you to call dispatch before App Middleware so by default it behaves as before.

**Comment by poolslick2002** [comment]
@AlexStansfield - In both examples (that I mentioned earlier) - almost every time the dispatch process will happen twice and I think that in a large application with many routes this is very expensive..
So running the dispatch process again does not seem like a good solution for me. And by just moving the app middleware after dispatch (without a second dispatch) besides the fact that will break functionality for who is relying on the current behavior will also remove the flexibility of manipulating the route and influence the dispatch process..
Only for the language parameter in the route example - I agree that there are a lot of different ways to deal with that - but why use regex and optional params. in every route - for example - when I can keep my application DRY and just add a small piece of code that takes care of that..?

@JoeBengalen - introducing a configuration option could be a solution

**Comment by AlexStansfield** [comment]
@poolslick2002 I've already added an update to redispatch after changes to the URI or method which allows you to manipulate the URI or Method (the two things the dispatcher uses to find the route).

The only remaining issue I see is the two dispatches if you modify the URI or method. Which, if you do this for every request will be expensive. But as I said before I'm happy to go with @JoeBengalen's solution of a configuration option to turn this functionality on.

_edit_ and you can't change the routes themselves once the dispatch has been done, again using the configuration option that could just be a limitation someone would have to accept if they wanted to dispatch before app middleware.

**Comment by poolslick2002** [comment]
@AlexStansfield - please don't get me wrong, I think we have a very constructive discussion - yes I've seen your update (and I appreciate your work) - and I agree with adding a configuration option to turn this functionality on.

**Comment by AlexStansfield** [comment]
@poolslick2002 sorry, if the tone seemed off I didn't mean anything by it. I'm currently working on the configuration option. Hope to push it once we determine a nice name for the setting :)

**Comment by AlexStansfield** [comment]
@poolslick2002 & @JoeBengalen added the setting "dispatchBeforeAppMiddleware". Welcome suggestions of a better name. It's false by default, set it to true when instantiating the container or the app in order to enable the dispatch first functionality.

**Comment by poolslick2002** [comment]
@AlexStansfield I did not tested the code - but it looks good to me - thank you for your work!

**Comment by akrabat** [comment]
#1357 has now been merged.

**Comment by yurevichcv** [comment]
Thanks!
