### ISSUE TITLE
Does Slim call Serialize? Errors are transformed

### ISSUE THREAD

**Issue by flyon** [slimphp/Slim#1376]
My class ResourceCollection is throwing an error `new ErrorException("test error");`
Going to the next line of execution from that error with a debugger I come to `Slim.php::handleErrors`, which shows the correct error message ("test error"), filename etc.
Then handleErrors throws its own ErrorException, leading to a try catch block in `Slim.php::call`,
but here the message has transformed in `"app\ResourceCollection::serialize() must return a string or NULL"`

I Slim calling serialize somewhere in the error handling?
I don't think I am calling "serialize" myself, and I don't want to implement serialize in this class (cause it will change behaviour when saving to cache)

**Comment by akrabat** [comment]
Are you using version 2 or 3 beta?

**Comment by flyon** [comment]
version 2.4.2. Should I try the beta?

**Comment by akrabat** [comment]
Consider upgrading to to 2.6.2.

**Comment by flyon** [comment]
still the same

**Comment by akrabat** [comment]
Are you able to create a small example app showing the problem?

**Comment by flyon** [comment]
wasnt able to reproduce in a quick setup, will re-open if I succeed at that later. tnx
