### ISSUE TITLE
[3.x] Request::getHeader($name) return array of single string instead of strings?

### ISSUE THREAD

**Issue by feryardiant** [slimphp/Slim#1379]
As mentioned in [here](http://www.slimframework.com/docs/objects/request.html#fetch-single-header):

> ### Fetch Single Header
> 
> You can fetch a single header’s value(s) with the Request object’s `getHeader($name)` method. This returns an array of strings for the given header name.

and [here](http://www.php-fig.org/psr/psr-7/#headers-with-multiple-values):

> Use `getHeader()` to retrieve an array of all the header values for a particular case-insensitive header by name.

When I call `$request->getHeader('Accept')` for example, I was expected that I'll get something like this:

```
Array (
    [0] => text/html,
    [1] => application/xhtml+xml,
    [2] => application/xml
)
```

but, in reallity I got this:

```
Array (
    [0] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
)
```

Is it correct?

**Comment by zither** [comment]
``` php
    // https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Headers.php#L52
    public static function createFromEnvironment(Environment $environment)
    {
        $data = [];
        foreach ($environment as $key => $value) {
            $key = strtoupper($key);
            if (isset(static::$special[$key]) || strpos($key, 'HTTP_') === 0) {
                if ($key !== 'HTTP_CONTENT_LENGTH') {
                    $data[$key] =  $value;
                }
            }
        }
        return new static($data);
    }
```

Slim creates headers from $_SERVER, and does not parse each header's value,.
so you can't fetch expected value with Request's getHeader method.

**Comment by JoeBengalen** [comment]
Well Slim SHOULD parse the header following the psr-7 standards:
`getHeader()` should return `string[]` and `getHeaderLine()` should return `string` (comma-separated string of the values). So I would indeed expect the accept values to be exploded by the comma.

I can confirm that `getHeader('accept')` returns:

``` php
array (
  0 => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
)
```

In fact is seems no parsing of the headers happens at all. Is this just a forgotten feature or something?

**Comment by feryardiant** [comment]
Hi everyone,

Thanks for your responses. I don't mean to ask Slim to parse header request here anyway, I just want to ask about its behaviour and how do I expect the value should be. As per documentation said that `getHeader` will return array of strings so I expected that it will return multiple instead just one of string.

This morning, thanks to @weierophinney who gave me clue about this issue.

![psr7 - tweet mwop](https://cloud.githubusercontent.com/assets/508665/8928310/b8fd223c-3547-11e5-9137-8d6bd9e57ef3.png)

and I think that it should be note in doc as well.

But, would be great if Slim also have official component or middleware to parse or sanitize every request objects.

Regards :smile:

**Comment by akrabat** [comment]
Further explanation: https://mwop.net/blog/2015-07-28-on-psr7-headers.html

**Comment by feryardiant** [comment]
@akrabat yes, I've read that right after I saw his tweet. :smile:
