### ISSUE TITLE
Limit of response?

### ISSUE THREAD

**Issue by LeoLR** [slimphp/Slim#1388]
Hi,

I use Slim for a android application and i've some problem, i've made a get on slim with a request on my Mysql database, when i run the query on my database i've more than 200 records, and when i try whith Postman (chrome application Rest client) i've no answer... 
I think the response is to big for Slim, can i fix it?

Thanks

**Comment by geggleto** [comment]
Slim has no limit in terms of the length of its response.

**Comment by LeoLR** [comment]
So why i didn't have the response? 
The JSON?

**Comment by geggleto** [comment]
@LeoLR there are many possible reasons, it would be helpful if you could post more information other than "it doesn't work"

**Comment by LeoLR** [comment]
Ok, 

In my API i've before my response->write do a var_dump(count($response)) and that return me 144.

But when i let this: 
```
$resp = $app->response();
$resp->header('Access-Control-Allow-Origin', '*');
$resp->write(json_encode($response));```

In Postman i've status 200 OK, times 334ms but a white page... 

So i try to make a ```var_dump($response);```
And that return good information, so i think the problem is on the ```json_encode```

No? ^^'

**Comment by LeoLR** [comment]
Ok,

In my API i've before my response->write do a var_dump(count($response)) and that return me 144.

But when i let this:

$resp = $app->response();
$resp->header('Access-Control-Allow-Origin', '*');
$resp->write(json_encode($response));```

In Postman i've status 200 OK, times 334ms but a white page... 

So i try to make a `var_dump($response);`
And that return good information, so i think the problem is on the `json_encode`

No? ^^'

**Comment by geggleto** [comment]
What version of Slim are you using?

**Comment by LeoLR** [comment]
The 2.6.1

**Comment by LeoLR** [comment]
I've maybe find the problem, it was some f... caracters in the database... Like this -> �

**Comment by LeoLR** [comment]
It was a problem with encode/decode caracters.
