### ISSUE TITLE
Issue with determineRouteBeforeAppMiddleware = true

### ISSUE THREAD

**Issue by yurevichcv** [slimphp/Slim#1391]
Found an issue connected with PR #1357.

When I use `determineRouteBeforeAppMiddleware = true` I'm expecting `notAllowedHandler` and `notFoundHandler` to fire as well before App Middleware. Otherwise I will not have `route` attribute inside my `$request` and it doesn't make sense for me to run Middleware as well the the rest of the application.

**Comment by yurevichcv** [comment]
@AlexStansfield

**Comment by AlexStansfield** [comment]
The way I saw it all App Middleware would want to run before any route handlers (even ones for not allowed or not found). 

You can get the result of dispatch from `$request->getAttribute('routeInfo')[0]`. 

If you only want your middleware to run if the route is found then you can just return from it if `$request->getAttribute('routeInfo')[0] !== FastRoute\Dispatcher::FOUND`.

**Comment by AlexStansfield** [comment]
@silentworks & @akrabat, any thoughts from you guys?

**Comment by yurevichcv** [comment]
I guess `determineRouteBeforeAppMiddleware = true` was designed for people, who don't want to make any changes to $uri in Middleware, but wants to use $route object there instead. And If someone enters http://example.com/flsdkbascdjabcgkds on my website - I want default $notFoundHandler to be fired. 

Currently I implemented workaround (which I don't like). In each Middleware I make a check:

```
if (!$request->getAttribute('route') {
   $next($request, $response);
}
```

**Comment by AlexStansfield** [comment]
You can make changes to the $uri in Middleware if you want and it will work fine. If changes are detected after all the App Middleware have executed then it will run the dispatcher again and find the new route before handling it.

It just doesn't execute any route handlers before the App Middleware. It wasn't designed to do that. The idea wasn't to have routes executed before Middleware, but to be able to access any matched route. 

You can add an app middleware on the outside that calls the `notAllowedHandler` or `notFoundHandler` depending on the result of `$request->getAttribute('routeInfo')[0]`. It seems that would do exactly what you're looking for without having to edit each middleware.

**Comment by akrabat** [comment]
I think that the current design is correct. The intention of the feature is to allow app middleware to know which route is likely to be dispatched at the end of the middleware chain. As such, if there is no route, a piece of middleware can make a decision on what to do about that before dispatch happens.

As Alex says, for your use-case, a single outer app middleware that calls either `notFoundHandler` or `notAllowedHandler` is the the way to achieve your goal.

**Comment by yurevichcv** [comment]
But main idea is that if I **explicitly** set `determineRouteBeforeAppMiddleware = true` it means, that I **don't want** to change $uri inside Middleware and I **want** to use $request->getAttribute('route'). 

Anyway, if you think, that current design is correct - I can implement additional Middleware. But I'm almost 99% sure, that every person who uses `determineRouteBeforeAppMiddleware = true` will need this Middleware.

**Comment by silentworks** [comment]
I can tell you now that I have no use case for what you are suggesting @yurevichcv I need this feature purely for ACL at App Middleware level, nothing more.

**Comment by AlexStansfield** [comment]
To me the setting name suggests that all that happens is it determines the route before the app middleware. Default behaviour is always been to execute the App Middleware before the `notFoundHandler` or `notAllowedHandler`. I don't see why this should change because of this setting. 

Personally I have no use case for this, but this is an open source community project, so if it's an addition you think is important (like how I felt the original feature was important) then submit a PR.
