### ISSUE TITLE
Returning PSR7 responses from external services

### ISSUE THREAD

**Issue by AlexStansfield** [slimphp/Slim#1392]
Came across an interesting one.

The project I'm working on is a sort of api facade providing a public layer between client applications and our internal web services.

One of the things I liked about the Slim 3 / Guzzle 6 combination was they both use PSR7 responses.

So with this in mind once the response from guzzle has had the body manipulated depending on the internal service in question I was just returning it for Slim 3 to handle.

I found I was getting errors back from Apache which I tracked down to the Transfer-Encoding header in the original response given by guzzle.

I've fixed this in the project by having the app middleware strip that header from the response.

I was wondering if this was a feature that might be useful to have done automatically (and if so what other headers we should be stripping). To me it seems like a nice advantage of PSR7 that we can just pass back responses no matter where they originate without the developer having to modify them.

**Comment by AlexStansfield** [comment]
For reference the headers I had in the Guzzle response were:
- Cache-Control
- Content-Type
- Content-Length
- Date
- Server
- Transfer-Encoding
- Vary
- X-Powered-By

For me Content-Type seems one to obviously keep. Date, Server, Content-Length and Transfer-Encoding look like ones to strip and the others I wasn't too sure.

**Comment by JoeBengalen** [comment]
Not sure if you're on the right track here. I think no header should result in an error. Now you're just prevented the error instead of fixing the actual problem it seems.

Why is the error thrown and what error exactly?

Always removing some headers seems like no option to me as sometimes you might need them.

**Comment by AlexStansfield** [comment]
Chrome gave me "Could not get any response". I stepped through it all and everything is fine. It adds the headers and echoes the response body. Slim doesn't error. Apache just gives me no response. 

In the `App::respond` method it goes through all the headers and and calls `header()` to add them to the header of the response. Once I stopped it doing that with the Transfer-Encoding header everything was fine.

As for the other headers. I figured some things we should just let the webserver deal with. Apache will add a Date, Server, Content Length itself.

**Comment by JoeBengalen** [comment]
If the Transfer-Encoding header really is a problem, why does Guzzle send it?

I feel like this is not a problem in Slim we should try to solve. Slim does its job apparently: If the Transfer-Encoding header is there it should output it. If Transfer-Encoding causes errors it should not be in the Response object.

**Comment by AlexStansfield** [comment]
It's Apache returning the header. I get it if I call the same API Guzzle is calling directly from Postman. So Guzzle will include it as part of the response it gives me.

It seems a pretty common header (one Apache uses when it's compressing responses and so can't give a content-length). So seems to me that this would be a fairly common problem if apache doesn't send a response if you set this header.

As I said I've fixed the problem in my own code, but seems like this could block a really useful feature.

**Comment by akrabat** [comment]
We can't trust that Slim is being used with Apache (or any web server), so I take the view that we shouldn't automatically mess with the Response object.

**Comment by AlexStansfield** [comment]
Fair enough :)
