### ISSUE TITLE
PSR-7 Stream implementation returns stale data for mutable properties

### ISSUE THREAD

**Issue by opengeek** [slimphp/Slim#1399]
When opening a `\Slim\Http\Stream` in Slim 3.x all of the stream meta data is cached when the stream resource is `attach()`ed. For potentially mutable stream metadata like `size`, this causes stale data to be returned from certain methods like `getSize()` once anything about the stream is modified.

**Comment by geggleto** [comment]
I would just like to note that the `attach()` is not part of PSR-7.

To solve this problem would we not just throw an exception if you are trying to attach on a Stream that already has something attached ?

**Comment by opengeek** [comment]
This has nothing to do with attaching a stream. And attach() seems to have been changed to protected for some reason, and is not available to use to attach a new stream anyway.

The issue here is simply one of getting stream meta data on demand rather than when the stream is attached. For instance, if you write to the stream, the size changes and would not be the same as when the stream was attached.
