### ISSUE TITLE
Slim v2 unknown exception

### ISSUE THREAD

**Issue by r3wt** [slimphp/Slim#1406]
`$e->getMessage()` outputs ``

`$e->getFile()` outputs `/vendor/slim/slim/Slim/Slim.php`

`$e->getLine` outputs  `1057`

path is 

`/api/create_single`

route is:

``` php
$app->map('/api/:method',function($method){
    (new \StarterKit\Routes\API)->__try($method);
})->via('GET','POST');
```

Unsure what the problem is. its a simple form submit with a couple of file inputs. controller pattern is battle tested and working. unsure of this error reason.

**Comment by JoeBengalen** [comment]
Should be a `Slim\Exception\Pass`

https://github.com/slimphp/Slim/blob/2.x/Slim/Slim.php#L1057

**Comment by geggleto** [comment]
I can't reproduce it. Slim uses Exceptions to control the flow, which is just a quirk of slim 2.

**Comment by r3wt** [comment]
@geggleto  there are no usage of slim's pass inside of the controller, which is why i'm here. first thing i did was consult the source.

**Comment by r3wt** [comment]
could slim be running out of memory? i'm literally baffled.

**Comment by akrabat** [comment]
What is the type of the Exception?

**Comment by akrabat** [comment]
Also, $e->getTraceAsString() should show you the backtrace…

**Comment by r3wt** [comment]
@akrabat  The type of exception being thrown claims to be `Slim\Pass` however, the response from the server is `200 success` with my normal json response. it seems that somewhere in my code slim is throwing some type of exception to pass on the route????? and my error handling pattern for the json api is catching the slim pass exception, but i'm not sure how/why its occurring! if i submit an empty post request, i get the normal response from my control about missing form data. 

![img](http://puu.sh/jqgwD/aa6cb7f0e2.png)

**Comment by r3wt** [comment]
Oh my god, i need to go to sleep. it was a damn typo, referencing a function that doesn't exist on controller, which propagated to my app, which propagated all the way back to slim

**Comment by akrabat** [comment]
Glad you found it!
