### ISSUE TITLE
Different callback per route per method

### ISSUE THREAD

**Issue by Swader** [slimphp/Slim#1414]
Looked around, couldn't find if there's already an issue addressing this.

I'm interested in defining something like this:

```
$app->get('/users/login', 'App\Controllers\AuthController:loginViewAction');
$app->get('/users/register', 'App\Controllers\AuthController:registerViewAction');
$app->post('/users/login', 'App\Controllers\AuthController:loginProcessAction');
$app->post('/users/register', 'App\Controllers\AuthController:registerProcessAction');
```

So, a different method on the same route triggers a different controller action.

Right now, the router blocks me because `get` is defined on the `/users/login` route first, so the `post` fails.

I assume it would be possible to do this by setting a callback, mapping two methods to the same route, and then differentiating between the methods in the callback, followed by calling a specific controller/action, but that seems like too much work (and too much logic in the router) for something that's very common elsewhere.

**Comment by JoeBengalen** [comment]
Look to me like your example should work fine.

You mean that you GET action is called while you are sending a POST request? That should not be.

**Comment by silentworks** [comment]
@Swader I have this very setup in one of my application and it works as it should, you sure your actions don't have the same code in them?

**Comment by geggleto** [comment]
I can also say that your example code works fine, I am using such things in production.

**Comment by Swader** [comment]
User error. All work and no play...

The form was submitting to `/users` which didn't have a POST counterpart. So using `/users/login` was fine in both Get and Post form, but using `/users` was not.

Sorry all :/
