### ISSUE TITLE
Content negotiation and routing

### ISSUE THREAD

**Issue by ansdma** [slimphp/Slim#142]
Hi, 
I'm building some APIs that can be consumed as json or xml so I used `https://github.com/alghamdi/php-format` to format my payload (perhaps there're better solutions for content negotiation).
Anyway, for consumers to choose there payload they need to specify it in the same routing way: `api/user/1/details/json` where `json` is a parameter as well.
My question is: is it possible to make the url something like: `api/user/1/details.json` and still have `json` as parameter just to make it looks better?

Cheers

**Comment by silentworks** [comment]
You can do that in your code by using a switch statement. and have a case called details.json or just json. If just json you will need to explode the url param at the . and return only the second part of the array as the argument for the switch. If this is not clear enough I will do a example in my next comment if you need one.

**Comment by MatthewCallis** [comment]
The ideal would be to implement both: `api/user/1/details` (generic uri that supports conneg by Accept header) `api/user/1/details.xml`, `api/user/1/details.json`, the first of which is already in the [Road Map](https://github.com/codeguy/Slim/wiki/Road-Map)

**Comment by njh** [comment]
+1 to content negotiation using the Accept header.

**Comment by codeguy** [comment]
This is on the Road Map and will be coming in a future release. For now, you _should_ be able to use a URL param like "/foo/bar.:format" to respond to different format requests. Closing this out since this is not an immediate concern.

**Comment by ansdma** [comment]
Thanks anyway Josh. I'll be using what you suggested till the next improvement come.
Best

**Comment by njh** [comment]
I needed Content Negotiation for a project I am working on, so I have implemented it in a branch:
https://github.com/njh/Slim/tree/negotiation

Even if it doesn't get accepted into Slim master, hopefully some of the code will be re-usable and there is something that can be used in the meantime.

See #376 for details.

**Comment by sanrodari** [comment]
+1 to add content negotiation, thanks @njh for the fork.

**Comment by marleyiam** [comment]
Hi! Does anybody could show me an example about how to set and use Content Negotiation using SlimMiddleware ? Cheers!
