### ISSUE TITLE
NotFound handler is using non Psr-7 method

### ISSUE THREAD

**Issue by ppetermann** [slimphp/Slim#1420]
I'm trying to use Slim 3.0-beta1 as a middleware, and it turns out, the default notFound page is not standard conform, as it uses a method named "getBasePath" which is not consistent with Psr\Http\Message\UriInterface (which should be returned by $request->getUri())

https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/NotFound.php#L62

**Comment by silentworks** [comment]
We should fix that actually, will have a look during this week to see if we can find a better solution.

**Comment by akrabat** [comment]
From our point of view, the complexity is in the basePath handling of our `Uri` that isn't part of PSR-7. The simplest solution is to use `__toString()` with the relevant parts cleared out.

**Comment by silentworks** [comment]
This should be fixed now.
