### ISSUE TITLE
Should the Slim 3.x middleware signature use RequestInterface or ServerRequestInterface?

### ISSUE THREAD

**Issue by rszrama** [slimphp/Slim#1429]
Currently, the Slim 3.x documentation states,

> A middleware is a callable that accepts three arguments:
> 1. \Psr\Http\Message\RequestInterface - The request object
> 2. \Psr\Http\Message\ResponseInterface - The response object
> 3. callable - The next middleware callable

– http://www.slimframework.com/docs/concepts/middleware.html

However, in practice Slim only passes an instance of ServerRequestInterface through the stack. This extends RequestInterface, but by specifying only RequestInterface in the documentation, it requires middleware to make special accommodations if they want to maintain interoperability while taking advantage of request attributes.

(For example, I use ServerRequestInterface::withAttribute() in NegotiationMiddleware\Negotiator to store the negotiated media type in the request for inspection by future middlewares.)

Hence the question - should Slim 3.x use the more specific ServerRequestInterface or should it stick with RequestInterface?

_Argument for RequestInterface:_

Middleware maintains interoperability with any PSR-7 RequestInterface based middleware stack that doesn't require a full ServerRequestInterface object. I can't think of an example off the top of my head, but hypothetical applications may exist that use middleware but don't require server, cookie, get, post, or files management.

_Argument for ServerRequestInterface:_

However, this means middlewares that want to use methods from a ServerRequestInterface while maintaining interoperability with a simpler RequestInterface signature need to provide an adapter for use in those situations or roll with something janky like an instanceof check.

I just really don't know in what cases someone might create an application or framework that has a request / response oriented architecture that wouldn't use a full ServerRequestInterface request.

As far as Slim 3.x is concerned, it's fine to make this change, and it will make it easier for future middleware authors if they can write middleware assured that $request will implement ServerRequestInterface.

**Comment by geggleto** [comment]
Slim Internals in the middleware department are here....

https://github.com/slimphp/Slim/blob/3.x/Slim/MiddlewareAwareTrait.php#L66

Where you will see:
$request is of ServerRequestInterface type
$response is of ResponseInterface type

**Comment by akrabat** [comment]
The documentation should be updated to note that Slim will pass in a ServerRequestInterface. We don't enforce this though, so any given Middleware should be able to type hint to RequestInterface.

**Comment by rszrama** [comment]
Yeah, the question really came up because I was writing middleware for a Slim 3.x application that I also wanted to be framework agnostic. Right now my middleware is compatible with Slim 3.x but would be incompatible with another theoretical framework adopting Slim's signature pattern without its practice of using the more robust interface. I'm not sure any such frameworks do or should exist, but I need to decide if I should continue using ServerRequestInterface in my type hint or refactor my code to accommodate just RequestInterface to maintain interoperability.

**Comment by JoeBengalen** [comment]
For a server side implementation you should be save to use `ServerRequestInterface`. The `RequestInterface` is meant for client implementation.

**Comment by codeguy** [comment]
I would think you'll be safe with `ServerRequestInterface` as @JoeBengalen said. @weierophinney Thoughts?

**Comment by weierophinney** [comment]
Go for `ServerRequestInterface` - that's the one that server-side middleware should be using; without it, you lose important features like the parsed body parameters, cookies, query parameters, etc.

**Comment by akrabat** [comment]
PR: https://github.com/slimphp/Slim-Website/pull/38
