### ISSUE TITLE
[Slim3] Do not assume response body stream is seekable

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#1434]
Not all streams are seekable, and we should not assume this here:

https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L352

This bit me when trying to send a Guzzle PumpStream which tosses an exception when you try to seek it. I'll send a PR shortly.

**Comment by geggleto** [comment]
I am pretty sure this came about from the discussion about php://input not being seekable
