### ISSUE TITLE
How to use new Flash message in Slim 3?

### ISSUE THREAD

**Issue by sunaryohadi** [slimphp/Slim#1436]
The documentation is still not available yet.
http://www.slimframework.com/docs/features/flash.html

**Comment by JoeBengalen** [comment]
You could try https://github.com/slimphp/Slim-Flash. Not sure if it is completely compatible yet.

At least you have to change `$this['flash']` to `$this->flash`.

Also I guess the question should be in the slim flash repo.

**Comment by sunaryohadi** [comment]
Thank you Joe.
