### ISSUE TITLE
Services coupling to Pimple\ServiceProviderInterface

### ISSUE THREAD

**Issue by juliangut** [slimphp/Slim#1438]
I'm trying to integrate PHP-DI dependency injection container into Slim3 and as far as container creation and provision to Slim\App it is just straight forward, still missing one PHP-DI configuration to sort out.

What I've found is that integration of services with this new container is not so easy. If we take a look at slim/flash, slim/csrf, slim/http-cache or my own juliangut/slim-controller they all implement \Pimple\ServiceProviderInterface, so for all of them `register` method has this signature:

``` php
public function register(\Pimple\Container $container)
```

It expects a Pimple\Container (or Slim\Container extending from it). This makes the implementation of `register` method in the bridge class seem off as it has to mimic the one present in Pimple\Container:

``` php
public function register(\Pimple\ServiceProviderInterface $provider, array $values = [])
```

Inside that method I cannot pass my bridge container as parameter to service's register method as it expects a Pimple Container, so you have to create an intermediate Pimple Container to be populated with services and then pull them out into the bridge container

``` php
public function register(ServiceProviderInterface $provider, array $values = [])
{
    $container = new PimpleContainer;
    $container['settings'] = $this->get('settings');

    $provider->register($container);

    foreach ($container->keys() as $service) {
        $this->set($service, $container->raw($service));
    }

    unset($container);

    foreach ($values as $key => $value) {
        $this->set($key, $value);
    }

    return $this;
}
```

All this said I think Slim3 should not depend so much upon Pimple\ServiceProviderInterface but provide its own `Slim\Interfaces\ServiceProviderInterface` expecting not Pimple\Container but `Interop\Container\ContainerInterface`, current services will still be valid and we don't have to code new services with Pimple in mind

Switching DI container should be made easy, we should bridge them to Slim needs (default services) not to Pimple needs

**Comment by akrabat** [comment]
`ContainerInterface` doesn't have any methods for registering services, so it's not the right interface to use as there's no way to work out how the given service provider expected registration.

However, in general you can ignore the `register` method completely as usually they do next to nothing. e.g. for Twig-View, it's simply:

``` php
    public function register(\Pimple\Container $container)
    {
        $container['view'] = $this;
    }
```

If anything, I'd prefer to just remove `register` completely and document how to register for the default container.

**Comment by juliangut** [comment]
I fully agree with you, we shouldn't use a method that forces us to use `ServiceProviderInterface`, so I'm going to drop Interface and `register` method from PHP-DI bridge container and document the registration process.

But this brings me to another related topic, shouldn't we stop using ArrayAccess interface in access examples as it is coupled with how Pimple works? PHP-DI does not and I had it implemented in the bridge class to behave as Pimple does, I see it now as a bad idea.

Taken from examples on documentation from slim/flash

``` php
$app->get('/foo', function ($req, $res, $args) {
    // Set flash message for next request
    $this['flash']->addMessage('Test', 'This is a message');

    // Redirect
    return $res->withStatus(302)->withHeader('Location', '/bar');
});
```

It should be clearly stated that the example is for Pimple container if you use ArrayAccess syntax to access it instead of ContainerInterface methods (get, has).

On the other hand as `ContainerInterface` does not provide a `set` mechanism, every container having its own will make the documentation harder as you have to document registration process to every kind of container, or ArrayAccess should be the default to be implemented

I'm trying to make services truly container independent, don't know if I'm missing something

**Comment by silentworks** [comment]
In the docs we state you should access services using `$this->view` and not `$this['view']`, this might have not been updated for the flash repo. But all this is doing is falling back to `$container->get()`. 

I agree with you about removing `ServiceProviderInterface` and the `register` method all together as this will cause confusion for any developer looking to use their own Container implementation.

**Comment by juliangut** [comment]
I see this is being removed really fast wow!
I'm closing this and opening a new issue for the last topic I introduced in the conversation about container assignment
