### ISSUE TITLE
[Slim3] Problem installing slim/csrf

### ISSUE THREAD

**Issue by sunaryohadi** [slimphp/Slim#1442]
> composer require slim/csrf
> 
> ```
> Using version ^0.1.0 for slim/csrf
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> Problem 1
>     - Installation request for slim/csrf ^0.1.0 -> satisfiable by slim/csrf[0.1.
> 0].
>     - Conclusion: remove psr/http-message 1.0
>     - Conclusion: don't install psr/http-message 1.0
>     - slim/csrf 0.1.0 requires psr/http-message ~0.9 -> satisfiable by psr/http-
> message[0.10.0, 0.10.1, 0.11.0, 0.9.0, 0.9.1, 0.9.2].
>     - Can only install one of: psr/http-message[0.10.0, 1.0].
>     - Can only install one of: psr/http-message[0.10.1, 1.0].
>     - Can only install one of: psr/http-message[0.11.0, 1.0].
>     - Can only install one of: psr/http-message[0.9.0, 1.0].
>     - Can only install one of: psr/http-message[0.9.1, 1.0].
>     - Can only install one of: psr/http-message[0.9.2, 1.0].
>     - Installation request for psr/http-message == 1.0.0.0 -> satisfiable by psr
> /http-message[1.0].
> Installation failed, reverting ./composer.json to its original content.
> ```

**Comment by akrabat** [comment]
Use `composer require slim/csrf:dev-master` until a new tag is added.
