### ISSUE TITLE
Container services assignment

### ISSUE THREAD

**Issue by juliangut** [slimphp/Slim#1444]
Coming from discussion in issue #1438 

When it comes to services assignment in the container in all the examples we see this:

``` php
$container['csrf']  = function ($c) {
    return new \Slim\Csrf\Guard;
};
```

But what happens if the container we're using does not implement \ArrayAccess Interface? In the bridge container for PHP-DI I'm working on I added ArrayAccess to be able to use already created services as slim/csrf as it use ArrayAccess syntax

This means every container to be used in Slim3 should implement this syntax as `ContainerInterface` does not force any assignment mechanism?

**Comment by codeguy** [comment]
These examples assume you are using Slim's default container. If you are using another container, you just need to make sure the container returns service `foo` for `$container->get('foo');`

**Comment by akrabat** [comment]
Agreed. If container-interop or a FIG standard ever comes up with a `set` interface, then we can revisit.

The only place you should see container set up code is in `\Slim\Container` or in documentation which assumes that `\Slim\Container` is being used.

**Comment by juliangut** [comment]
Ok :)
