### ISSUE TITLE
Incorrect root URI if 404 Not Found response

### ISSUE THREAD

**Issue by xiaozi** [slimphp/Slim#145]
When in the 404 page.Slim::request()->getRootUri(),this function will run in the wrong way.
Example:' localhost/404', that function will return '/404' instead of  '/'.

**Comment by codeguy** [comment]
I am unable to duplicate this issue. Here is sample code I am using with version 1.5.0.2.

```
$app = new Slim(array('debug' => false));

$app->notFound(function () use ($app) {
    echo "Root URI: ", $app->request()->getRootUri(), "<br/>Resource URI: ", $app->request()->getResourceUri();
});

$app->run();
```

This outputs the expected results. I'm removing this from the 1.5.1 milestone for now; it will be helpful if you can provide more details to help me duplicate this issue.

**Comment by codeguy** [comment]
Closing this out. Please leave a new comment here if you are able to reliably duplicate this.
