### ISSUE TITLE
Pass array using post request for single name

### ISSUE THREAD

**Issue by hardik99** [slimphp/Slim#1452]
I want to pass array of emails using post request for single names but it receives only last name.

here is my code ...

```
       $app->post('/email', function() use ($app) { 
        // check for required params 
        verifyRequiredParams(array('emailto', 'emailfrom', 'message'));
        $response = array(); 
        // reading post params 
        $emailto = $app->request->post('emailto'); 
        vardump($emailto);

        $emailfrom = $app->request->post('emailfrom'); 
        $message = $app->request->post('message'); 

        // validating email address 
        validateEmail($emailfrom); 

        // echo json response 
        echoRespnse(201, $response); 
    });
```

email to only returns the last value which i send ...

I want array of emails in emailto ....

How can I ?

**Comment by geggleto** [comment]
Simple...

```
<input type=text name=emailto[] value=''>
<input type=text name=emailto[] value=''>
<input type=text name=emailto[] value=''>
<input type=text name=emailto[] value=''>
<input type=text name=emailto[] value=''>
<input type=text name=emailto[] value=''>
<input type=text name=emailto[] value=''>
```

**Comment by hardik99** [comment]
Is it required to use form bcoz i direct pass request from ios ?
And i don't need it ....

**Comment by geggleto** [comment]
well, I was merely pointing out that if you can create a proper request you can have an array of emails.

The above example was 1 way to do it.

**Comment by silentworks** [comment]
Try `$app->request->post()` and check if that contains all of your emailto's.

**Comment by hardik99** [comment]
i have check but it only returns last value ...

**Comment by silentworks** [comment]
Well that means something is wrong on the other side of this, not the Slim side.

**Comment by hardik99** [comment]
can you provide sample code for that how can i do this ?

**Comment by silentworks** [comment]
I don't write iOS code, both myself and @geggleto have provided you with sufficient amount of code that should result in getting this working.

**Comment by akrabat** [comment]
Do you have `curl` based example of how you are sending the data to your Slim application?

**Comment by hardik99** [comment]
no ...  i am testing using postman rest client ....

**Comment by akrabat** [comment]
Can you screenshot the request and response in it then?

**Comment by JoeBengalen** [comment]
and you have named the parameters including the `[]` at the end?

**Comment by akrabat** [comment]
Can you screenshot the Request and Response in postman?

**Comment by hardik99** [comment]
![request](https://cloud.githubusercontent.com/assets/8007526/9335275/be4b0ba0-45f0-11e5-9e8b-36379662d48a.png)
![response](https://cloud.githubusercontent.com/assets/8007526/9335276/be4f2816-45f0-11e5-9990-81ade5c6b15c.png)

**Comment by JoeBengalen** [comment]
name them `emailto[]`

**Comment by akrabat** [comment]
The three `emailto` fields will override each other, so name them `emailto[]`

**Comment by hardik99** [comment]
ok ... it works ... thanks ... 

How can i upload multiple image using slim ?
