### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by hardik99** [slimphp/Slim#1453]
I have tried to upload files using this code ....
but its not working ...

$app->post('/', 'uploadFile');
function uploadFile () {  
    if (!isset($_FILES['uploads'])) {
        echo "No files uploaded!!";
        return;
    }
    $imgs = array();
    $files = $_FILES['uploads'];
    var_dump($files);
    $cnt = count($files['name']);
}

![fileup](https://cloud.githubusercontent.com/assets/8007526/9336670/61d1ded2-45f8-11e5-9bae-5e6f05a7f6f3.png)

**Comment by geggleto** [comment]
Wrong encoding on the request.

**Comment by hardik99** [comment]
then how can I ?

**Comment by geggleto** [comment]
screenshot your headers tab

**Comment by hardik99** [comment]
![header](https://cloud.githubusercontent.com/assets/8007526/9336914/be508e00-45f9-11e5-8849-4ae26b36fb26.png)

**Comment by hardik99** [comment]
how can i upload files ?

**Comment by JoeBengalen** [comment]
I just want to note that issues are meant for problems related to the Slim framework. Not to explain how postman works.

Please read the [postman documentation](https://www.getpostman.com/docs).
