### ISSUE TITLE
Get route name when class is defined as callable

### ISSUE THREAD

**Issue by juriansluiman** [slimphp/Slim#1458]
While this might not sound like a solid idea (pun intended), I think this is a valid case:

```
$app->get('/foo', 'App\Controller\StandardController::showPage')->setName('foo');
$app->get('/bar', 'App\Controller\StandardController::showPage')->setName('bar');
```

Different routes, same controller. I stumbled upon this case by implementing a "mini-CMS" where I want to show a text from DB based on the route name (or URL, but preferably from the route name). So I define all pages in a long list (like above) all pointing to the same controller. Based on route names, it fetches the right text.

Is this possible in Slim v3?

**Comment by JoeBengalen** [comment]
notation should be `Controller:method`, but that should work yeah.

Although you may find it easier to have single route there with some regex instead of several pointing to the same action.

**Comment by silentworks** [comment]
Yes this is possible.
