### ISSUE TITLE
Error Hook / Callback

### ISSUE THREAD

**Issue by MatthewCallis** [slimphp/Slim#146]
To process erros currently it requires a bit of core hacking to say, submit errors to something like [HopToad](https://hoptoadapp.com/pages/home) or process them internally, a hook into that could be useful or external access to the error itself rather than hijacking set_error_handler / set_exception_handler from Slim just to make a call and return it.

**Comment by codeguy** [comment]
See https://github.com/codeguy/Slim/issues/160. If you need further customization, let me know in the forums or on IRC and we can chat further. Errors are converted to ErrorExceptions, but the error message and code are maintained through the conversion as the ErrorException code and message. Closing this for now.
