### ISSUE TITLE
Slim 3: Not able to use callable class with static method.

### ISSUE THREAD

**Issue by mrcorex** [slimphp/Slim#1460]
According to http://php.net/manual/en/language.types.callable.php it should be possible to do

// Type 2: Static class method call
call_user_func(array('MyClass', 'myCallbackMethod')); 

but it does not work anymore.

Example: $app->get('/', array('MyClass', 'run'));

**Comment by geggleto** [comment]
Can confirm this works in 9430d0efc06d0eb27f5c3a4db720a464a613203c

``` php
$app->get('/test', array(Controllers\TestController::class, 'test'));
```

**Comment by geggleto** [comment]
Can confirm this works in 6d6d861cb2be2b0a0535aaea61abea6476c87c7d

``` php
$app->get('/test', array(Controllers\TestController::class, 'test'));
```

**Comment by geggleto** [comment]
In both cases Test is a public static method on the TestController class.

**Comment by geggleto** [comment]
@mrcorex are you using the full namespace of the class in your array syntax ?

**Comment by silentworks** [comment]
I can also confirm this works. If you look at the resolver code you will notice if its a callable it goes straight to the else.

**Comment by jaapverloop** [comment]
The provided example seems correct.

``` php
$app->get('/test', array(Controllers\TestController::class, 'test'));
```

...but, I guess the following line could cause problems: https://github.com/slimphp/Slim/blob/6d6d861cb2be2b0a0535aaea61abea6476c87c7d/Slim/Handlers/Strategies/RequestResponse.php#L41

See issue https://github.com/slimphp/Slim/issues/1331 for more info.

``` php
return $callable($request, $response, $routeArguments);
```

should be:

``` php
return call_user_func($callable, $request, $response, $routeArguments);
```

**Comment by silentworks** [comment]
Yes you are correct, that could cause an issue again. Will get that updated or you are welcome to send a PR.

**Comment by mrcorex** [comment]
I am trying to develop a tool/builder/documentor, which, in large webservice-api's, will take the pain out of many things, like field-handling, query-limitation, versioning, etc. I want to base this on Slim 3. I am trying to develop 2 composer-packages (slimservice and slimbuilder), both PSR4.

I am not using full namespace, because the service-handling was all about the class-name. I registered an autoloader which would turn i.e. "SystemKeysService" into "/components/system/services/keys/SystemKeysService.php" and "SystemKeysTest" into "/components/system/tests/keys/SystemKeysTest.php" and so on.

I might change this slightly, because I want to add a service-layer as well, but you get the idea....

array('SystemKeysService', 'run') is a documented way of doing it and is parseable to "call_user_func". The suggestion was to do a "array(new SystemKeysService(), 'run')" but that would create an instance of the class, when I register it. I do not want that. If I do the other thing "array('SystemKeysService', 'run')", it will make the instance when it is called and not before. A kind of lazy loading....

I know that this was a long text, and some of it might not be interesting, but it should give you an idea of what I am trying to accomplish.

**Comment by jaapverloop** [comment]
@silentworks I will send a PR

**Comment by silentworks** [comment]
This should be fixed from the PR sent by @jaapverloop
