### ISSUE TITLE
Route::getMiddleware implies on returning an callable, but returns an array of callables

### ISSUE THREAD

**Issue by piotr-cz** [slimphp/Slim#1461]
Shouldn't the method be called `getMiddlewares` instead?

**Comment by silentworks** [comment]
I would like to think `Middleware` is both singular and plural.

**Comment by akrabat** [comment]
The plural of middleware is middleware.

**Comment by piotr-cz** [comment]
Thank for clarification, I thought it's just like _wares_ is the plural for _ware_.
