### ISSUE TITLE
Slim 3: App->get() Add GET route strange behaviour.

### ISSUE THREAD

**Issue by mrcorex** [slimphp/Slim#1462]
Look at following example:

$app = new \Slim\App();
$app->get('/test', function ($request, $response, $args) {
    print('test1');
});
$app->get('/test/', function ($request, $response, $args) {
    print('test2');
});

/test is not the same as /test/

Is it me or is this a bug?

**Comment by ppetermann** [comment]
why would it be the same?

**Comment by mrcorex** [comment]
Because it is a path and / is a separator ? I am not sure I understand your question?

Reason for asking is that SOME browsers automatically adds the / after url. Some dont. And if people are not aware of this when connecting to a service, then this can create confusion when debug'ing.

I am trying to determine if it is a design-"bug" or if I need to do 2 x $app->get() on the same path every time to be sure that I do not create unnecessary work for myself.

**Comment by opengeek** [comment]
Historically, the behavior has been that a trailing slash defined in a route was optional but ultimately canonical. IOW, if you defined a route in 2.x with a trailing slash, requests without the trailing slash still worked, but they 301 redirected to the URL with the trailing slash appended.

That said, I think it's valid to allow explicit definition of what is essentially a file versus a folder. I am accepting requests for both forms by defining trailing slashes as optional explicitly in 3.x, e.g.

```
$app->get('/test[/]', function($request, $response, $args) {});
```

I plan to mimic 2.x behavior by 301 redirecting requests on routes with an optional trailing slash to the preferred canonical URL (either with or without the optional trailing slash) via middleware.

**Comment by mrcorex** [comment]
[/] is a good solution for me. I understand the difference of with and without the slash, but on a framework with web-services, it is a pain.

Thanks for answer.

**Comment by akrabat** [comment]
From a SEO point of view, Google's view is that they are different endpoints and ideally one should redirect to the other. However they will handle it in their indexing, presumably because so many sites don't get it right:

> If both slash and non-trailing-slash versions contain the same content and each returns 200, you can:
> - Consider changing this behavior (more info below) to reduce duplicate content and improve crawl efficiency.
> - Leave it as-is. Many sites have duplicate content. Our indexing process often handles this case for webmasters and users. While it’s not totally optimal behavior, it’s perfectly legitimate and a-okay. :)

From: http://googlewebmastercentral.blogspot.co.uk/2010/04/to-slash-or-not-to-slash.html

**Comment by kadimi** [comment]
Conventionally speaking, I **believe** that `test/` would point to a directory or listing of tests whereas `test` would point to a single test, so it makes sense to be able to handle them differently with the framework.

**Comment by opengeek** [comment]
Actually, that is a separate issue. A collection would be represented by `tests` or `tests/` — a single test would be identified in a new segment within the collection, e.g. `tests/1` or `tests/1/`. There are use cases where the representation of `tests` and `tests/` could be different, but in most cases both SHOULD match the same route and SHOULD redirect to the preferred canonical representation.

**Comment by akrabat** [comment]
Current behaviour is expected: `/test` and `/test/` are different and if you want one route to cover both, the you use `/test[/]`.

I've added an issue to the docs repository to get his documented.
