### ISSUE TITLE
Slim 3: missing referer in Request

### ISSUE THREAD

**Issue by shamotj** [slimphp/Slim#1463]
I can't access referer in Request object in Slim 3. It seems there is none. Shouldn't be referer set automatically when routing/redirecting?

Update: There is referer but not always. When I use:

``` php
return $response->withRedirect('/admin/user/login');
```

in middlewere, I cannot see any referer in action handling this URI.

**Comment by akrabat** [comment]
How are you reading the referrer?

**Comment by shamotj** [comment]
I check $request->getHeaders(). I wanted to use getHeader('HTTP_REFERER').

**Comment by silentworks** [comment]
I tested this and it was present at the time, the only time the referrer was missing was if I went directly to the route itself, but on using the build in redirect it was always present.

**Comment by tuupola** [comment]
Also browser does not always the send referer header.

**Comment by shamotj** [comment]
I tried simple action like this:

``` php
public function test(Request $request, Response $response, $args) {
     return $response->withRedirect('/admin/user/login');
}

public function login(Request $request, Response $response, $args) {
    var_dump($request->getHeaders());die();
}
```

And there is no REFERER header. Can you please confirm you have it there?

**Comment by akrabat** [comment]
How are you testing?

**Comment by akrabat** [comment]
The REFERER header is set by the browser. So, you need to use the browser to redirect from test to login.

**Comment by akrabat** [comment]
i.e.:

``` php

$app->get('/one', function ($request, $response, $args) {
     return $response->write('<a href="/two">Click here</a>');
});

$app->get('/two', function ($request, $response, $args) {
    var_dump($request->getHeaders());
});
```

**Comment by tuupola** [comment]
Doing `return $response->withRedirect('/two');` instructs the browser to do a redirect. It is not an internal Slim subrequest. Following gives me `HTTP_REFERER` header at `/two`.

``` php
$app->get("/one", function ($request, $response, $args) {
     return $response->write('<a href="/redirect">Click here</a>');
});

$app->get("/redirect", function ($request, $response, $args) {
    return $response->withRedirect("/two");
});

$app->get("/two", function ($request, $response, $args) {
    print_r($request->getHeader("HTTP_REFERER"));
});
```

Yields.

```
Array
(
    [0] => http://0.0.0.0:8081/one
)
```

**Comment by akrabat** [comment]
@tuupola, Your example shows what's going on. The act of clicking on "click here" sets the HTTP_REFERER to /one. Then, The redirect in /redirect simply passes that HTTP_REFERER value onto /two. 

i.e. using `withRedirect` doesn't set or change the HTTP_REFERER header.

**Comment by shamotj** [comment]
But withRedirect returns HTTP 302 response with Location in header. Browser then makes new request with that Location. And if it doesn't create Referer, what is the best way to get original location?

**Comment by akrabat** [comment]
I use `?r=xyz` in URL that I redirect

**Comment by shamotj** [comment]
That will work. I must Google for some best practice for this. Anyway I think this issue is well answered and should be closed. Thanks for replies.

**Comment by tuupola** [comment]
@akrabat my point exactly. If referer header exists using `withRedirect()` will not remove it.  So you can use `withRedirect()` and still have the referer header. 

But in any case relying on referer header is bad practice since there any many cases when it might be missing.
