### ISSUE TITLE
Most of container variables appear to be "frozen" even before app run. 

### ISSUE THREAD

**Issue by yurevichcv** [slimphp/Slim#1465]
This issue is caused by PR #1443

Unfortunately, this PR doesn't have backward compatibility. Before I was able to "override" container values before `$app->run()`. 

Before I was able to do the following in unit tests:

```
$app = new \Slim\App();

Configurator::configureApp($app); //seudo-code

$c = $app->getContainer();
$c['environment'] = $c->factory(function ($c) {
....
});
$c['request'] = $c->factory(function ($c) {
....
});
```

Now it is not possible, getting following error:

```
RuntimeException : Cannot override frozen service "environment".
```

And main problem is that now you freeze almost all container variables during router initialisation:

Before it was (worked perfectly):

```
 $this['router'] = function ($c) {
     return new Router();
};
```

Not it is:

```
if (!isset($this['router'])) {
            $this['router'] = function ($c) {
                $router = new Router();

                $uri = $c['request']->getUri();

                if (is_callable([$uri, 'getBasePath'])) {
                    $router->setBasePath($uri->getBasePath());
                }

                return $router;
            };
}
```

As you can see, now you access $c['request'], which automatically freezes almost all essential components in container.

Main idea is that essential container components, such as `environment`, `request` and `response` should not be frozen before app run.

Use case:
1. I want to configure my application (including all routes, acl, domain services, etc)
2. Save it to static property or to cache.
3. Override container's `environment`, `request` and `response` with factories.
4. Run many tests against the same instance of application.

**Comment by yurevichcv** [comment]
The same issue was with Twig-View extension, which was "freezing" `request` object even before `$app->run()`: https://github.com/slimphp/Twig-View/pull/30

**Comment by JoeBengalen** [comment]
When does it freeze? If wont freeze as long as you do not get anything from the container. Following code works fine:

``` php
$app = new Slim\App();

$c = $app->getContainer();

$c['environment'] = function ($c) {
    return new Slim\Http\Environment($_SERVER);
};

$c['router'] = function () {
    return new \Slim\Router();
};

$app->get('/', function () {
    echo 'home';
});
```

Indeed if you use the `router` you cannot override any used service anymore. Following code gives your error:

``` php
$app = new Slim\App();

$c = $app->getContainer();

$app->get('/', function () {
    echo 'home';
});

$c['environment'] = function ($c) {
    return new Slim\Http\Environment($_SERVER);
};

$c['router'] = function () {
    return new \Slim\Router();
};
```

**Comment by yurevichcv** [comment]
```
$app = new Slim\App();
$app->get('/', function($request, $response, $args) {
//
});

$c = $app->getContainer();

$c['environment'] = function ($c) {
    return new Slim\Http\Environment($_SERVER);
};
```

It should be possible to make full configuration of the app before passing any $requests and $environments into it. This is especially essential in Unit Testing.

**Comment by JoeBengalen** [comment]
Disagree. How do you want to add routes to the router if you want to set the router after setting the routes? Sounds a bit weird to me.

**Comment by akrabat** [comment]
The problem you have is that `get` requires the `router`. Therefore you need to set up your container before you start using `$app`

**Comment by yurevichcv** [comment]
I don't want to set the route after router. I want to set `request` after routes.

The only way to test `$app->run()` now is to override `$c['request']` with a factory.

**Comment by akrabat** [comment]
You can't change the request after adding routes as the router needs the request to work…

**Comment by yurevichcv** [comment]
@akrabat Router needs request during dispatching, but it **should not** need it during routes initialization. Route initialisations are "rules". And when this rules defined - I should be able to "feed" dispatcher with any request.

**Comment by yurevichcv** [comment]
Before this PR everything was working perfect. What is your solution for testing `$app->run()` now?

Take into account, that huge projects can not allow to initialize new `App` instance every time. This way `App` with all it's huge configurations (including 200+ routes) should be initialized once, and then it needs to run 300+ different unit tests with 300 different requests. 

Before it was possible to do it.

**Comment by JoeBengalen** [comment]
You should set your container before you start using any service from it (adding routes)

**Comment by yurevichcv** [comment]
"Setting container" in most cases = configuring the app.

**Comment by silentworks** [comment]
Configuring app != configuring app dependencies.

**Comment by yurevichcv** [comment]
Main idea here is that `router` **should not** depend on "current" request. I should be able to configure everything:
1. Dependencies
2. Routes.
3. Middleware

And only after that feed **any** request to my app.

**Comment by yurevichcv** [comment]
Request is kinda "input param" to the application

Request 1 ------> App (configured) -------> Response 1
Request 2 ------> App (configured) -------> Response 2
Request 3 ------> App (configured) -------> Response 3

But in your case it looks like following:

Request 1 ------> App (configured using Request 1) -------> Response 1
Request 2 ------> App (configured using Request 1) -------> Response 2??
Request 3 ------> App (configured using Request 1) -------> Response 3??

**Comment by akrabat** [comment]
Are you calling `run` more than once per instantiation of `App` ?

**Comment by yurevichcv** [comment]
@akrabat Sure. In unit tests. 

It allows do decrease time of test case initialization many times. Initialisation includes settings routes, acl, db connection, etc.

When I was looking into `$app->__invoke($request, $response)` examples in your unit tests I was expecting `$app` to be reusable against different requests.

**Comment by akrabat** [comment]
Can you do this:

```
unset($container['request']);
$container['request'] = function($c) {};
```

?

**Comment by yurevichcv** [comment]
I can try. But this way I will also need to `unset($container['router'])`, as it was built based on previous request. That's why I want route to be independent.

**Comment by yurevichcv** [comment]
And also re-configure all my routes again.

**Comment by akrabat** [comment]
Nope. The router only uses the request for the base path, so you can just set the router's basepath:

```
unset($container['request']);
$container['request'] = function($c) {};
$container['router']->setBasePath($container['request']->getUri()->getBasePath());
```

**Comment by JoeBengalen** [comment]
Amazingly enough unset seems to work lolz. But the router can stay the same if you dont you the pathFor method

**Comment by yurevichcv** [comment]
@akrabat Your solution works, but the code now is little bit smelly.

This is solution which is much better from architectural point of view:

```
if (!isset($this['router'])) {
    $this['router'] = function ($c) {
        $router = new Router();
        if (isset($c['settings']['basePath']))) {
            $router->setBasePath($c['settings']['basePath']);
        }

        return $router;
    };
}
```

**Comment by yurevichcv** [comment]
This way we have expected behaviour. Yes, I can `unset($c['request'])`, but are you going to put this into documentation? How other users will know about all this "tips&tricks". Defining "basePath" in settings is predictable way. And now router is absolutely independent from **current request**.

**Comment by akrabat** [comment]
if basePath is a setting, then Slim will no longer work out of the box in a subdirectory.

I will submit a PR that moves the setting of basePath though.

**Comment by yurevichcv** [comment]
At least it is possible to put this info in documentation:

If you are using Slim inside subfolder you should define `basePath` settings like this:

```
$app = new \Slim\App([
   'settings' => [
      'basePath' => '/subfolder'
   ]
]);
```

**Comment by akrabat** [comment]
Hopefully #1467 is a better solution.

**Comment by yurevichcv** [comment]
Yes, definitely much better, then current solution :+1:

**Comment by silentworks** [comment]
This has now been merged.
