### ISSUE TITLE
No conditions support on groups but only on routes?

### ISSUE THREAD

**Issue by wouterds** [slimphp/Slim#1468]
Would be a nice feature, any plans or reasons why it hasn't been done?

**Comment by silentworks** [comment]
What do you mean by conditionals? and what version of Slim are you referring to?

**Comment by geggleto** [comment]
Maybe he means the defaultConditions from slim2 ?

**Comment by wouterds** [comment]
I'm refering Slim 2 and I mean conditions like so:
`$app->get('/verify/:code', 'Controller:method')->conditions(['code' => '[a-zA-Z]{7}']);`

**Comment by silentworks** [comment]
You can now do that directly on the placeholder according to FastRoute docs.

https://github.com/nikic/FastRoute

``` php
$app->get('/verify/{code:[a-zA-Z]}', 'Controller:method');
```

**Comment by geggleto** [comment]
`$app->put(      '/blog/{id:\d+}',   BlogController::class . ":update")->addMiddleware(SecurityMiddleware::class);`

**Comment by piotr-cz** [comment]
This pattern may be already used on group routes in v3-beta.2, too:

``` php
$app->group('/{locale:en|pl}', function() use ($app) {

    $app->get('', 'App\Action\HomeAction::dispatch');
        ->setName('homepage');
});
```
