### ISSUE TITLE
Invokable class unusable as route callback

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1469]
Using the following (not pretty I know)

``` php
<?php

require __DIR__ . '/../vendor/autoload.php';

$app = new Slim\App();

class Test
{
    public function __invoke()
    {
        return 'test';
    }
}

$app->get('/', Test::class);

$app->run();
```

And after reading @silentworks article [here](http://thoughts.silentworks.co.uk/lazy-loading-controller-action/), and with my own expectations that an invokable object should just be invoked, this is the result I get:

```
Slim Application Error
The application could not run because of the following error:

Details

Type: RuntimeException
Message: Test is not resolvable
File: /data/sites/local/vendor/slim/slim/Slim/CallableResolver.php
Line: 94
Trace

#0 /data/sites/local/vendor/slim/slim/Slim/CallableResolver.php(107): Slim\CallableResolver->resolve()
#1 /data/sites/local/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): Slim\CallableResolver->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /data/sites/local/vendor/slim/slim/Slim/Route.php(314): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Slim\CallableResolver), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /data/sites/local/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(114): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /data/sites/local/vendor/slim/slim/Slim/Route.php(288): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /data/sites/local/vendor/slim/slim/Slim/App.php(392): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /data/sites/local/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(114): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /data/sites/local/vendor/slim/slim/Slim/App.php(304): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /data/sites/local/public/index.php(32): Slim\App->run()
#9 {main}
```

> The reason we are able to just call the Action Class name here is that Slim 3 will check for the __invoke method.

Sadly @silentworks this isn't right, although I agree with you it should be.

**Comment by designermonkey** [comment]
To get this to work, I have to manually create an instance of every callback class, which goes against the point of making this all accept string references to classes and methods.

``` php
$app->get('/', new Test);
```

or tell it to look for the invoke method:

``` php
$app->get('/', Test::class . ':__invoke');
```

All this seems a little odd. Could the `CallableResolver` be updated to allow the use of invokable classes?

**Comment by designermonkey** [comment]
Pretty embarrassed here, I looked at the code in the repo here and it has been changed since my local copy. Updated and it all works fine.

Sorry chaps.

**Comment by designermonkey** [comment]
I don't technically want to reopen this, but I still don't understand how Slim verifies that a class is invokable. It seems to me to just assume it is right at the end of the if/else block in the CallableResolver?

https://github.com/slimphp/Slim/blob/3.x/Slim/CallableResolver.php#L76

**Comment by akrabat** [comment]
Line 73 ensures that $class can be autoloaded and so line 76 instantiates it.

Line 81 checks that it is invokable.

**Comment by designermonkey** [comment]
Why am I so blind recently? Thanks.
