### ISSUE TITLE
I think there is issue when using more than 3 route variables.

### ISSUE THREAD

**Issue by Abhinav1217** [slimphp/Slim#1471]
I was dealing with an issue discussed [here](http://stackoverflow.com/questions/32191920/serve-images-assests-using-slim-framework) and [here](http://help.slimframework.com/discussions/questions/7993-how-to-echo-images-from-slim-framework).

I was bothered why none of the method worked and I stumbled upon an issue which I think belongs to slim framework itself.  I made a fresh folder and did some testing.

``` php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

require_once '../vendor/autoload.php';

$app = new \Slim\Slim();

/*  ---- Everything works textbook perfect from here ---- */
/*  ---- i.e. whether the url ends with trailing slash or not. ----  */

$app->get('/assets(/)', function() use ($app) {
    echo '/assets(/)';
});

$app->get('/assets/:height(/)', function($height) use ($app) {
    echo '/assets/:height(/)';
});

$app->get('/assets/:height/:width(/)', function($height, $width) use ($app) {
    echo '/assets/:height/:width(/)';
});

/* ----- To Here ----- */


/* -- But when I use 3 or more values in url such as this -- */
/* -- " http://urltest.local/assets/200/200/logo/png "   Does not work - give 404 error -- */
/* -- " http://urltest.local/assets/200/200/logo/png/ "   Does not work - give 404 error  -- */

$app->get('/assets/:height/:width/:id(/)', function($height, $width, $id) use ($app) {
    echo '/assets/:height/:width/:id(/)';
});

$app->get('/assets/:height/:width/:id/:type(/)', function($height, $width,  $id, $type) use ($app) {
    echo '/assets/:height/:width/:id/:type(/)';
});

/* -- also alternativly this does not work - give 404 error -- */

$app->get('/assets/:height/:width/:id/:type', function($height, $width,  $id, $type) use ($app) {
    echo '/assets/:height/:width/:id/:type';
});

/* -- but this alternative does work when there is trailing slash -- */

$app->get('/assets/:height/:width/:id/:type/', function($height, $width, $id, $type) use ($app) {
    echo '/assets/:height/:width/:id/:type/';
});


?>
```

**Update :** **Edited the copy-paste mistake I did when I posted this.**

**Comment by r3wt** [comment]
Your function signatures define an unused variable $image. The number of route ooacehokders doesn't match the number of arguments to the callback

**Comment by Abhinav1217** [comment]
No,  I copy pasted wrongly here,  Actually,  when It gave 404 error on 4 variables, I decided to replace id and type with just image, and split its extension to get id and type.  I forgot to remove $image when I wrote here. My bad, I will update the code.  But error is there , on 3 and more variable, I need to add a trailing slash or else I get a 404. I can replicate it as many time as you ask. 

My System
Fedora 22 64bit,
Nginx, php-fpm, (all updated)

**Comment by tuupola** [comment]
The following code works for me. Note that your example is missing `$app->run()`

``` php
require "./vendor/autoload.php";

$app = new \Slim\Slim();

$app->get("/assets/:height/:width/:id/:type(/)", function($height, $width,  $id, $type) use ($app) {
    echo "/assets/{$height}/{$width}/{$id}/{$type}(/) \n";
});

$app->run();
```

yields

```
$ php -S 0.0.0.0:8080 index.php
$ curl http://0.0.0.0:8081/assets/100/200/6/png/
/assets/100/200/6/png(/) 
$ curl http://0.0.0.0:8081/assets/100/200/6/png
/assets/100/200/6/png(/) 
```

**Comment by Abhinav1217** [comment]
What server are you using,  I copied the your code and I have to add trailing slash to make it work.  
I am using Nginx with php-fpm.  System is updated.

About `$app->run();` I missed it copying.  This was test.php file i keep in my active project to quickly test some random logic or code snippet.  So i didn't  just copied all of it. Just the part I thought was relevant to post here.

**Comment by silentworks** [comment]
From the code, he is using the built in PHP webserver, I am inclined to think this is a server configuration issue rather than a Slim itself issue.

**Comment by Abhinav1217** [comment]
I ended up using get parameters for my project due to time constraint. I have kept the test app aside. This is what I can gather on my linux system and on my friends windows 8.1 system.  I am using the Apache rewrite rules and Nginx server config from the slim docs itself. http://docs.slimframework.com/routing/rewrite/ 

Nginx :  trailing slash is required for more than 3 rest attributes.
Apache : Trailing slash is required for more than 3 rest attributes.
It was same on my ubuntu machine also.

Windows : Apache (AMPPS),  Trailing slash is required after 3 rest attributes.  

Only thing I changed in php.ini, was to enable errors. Apache and nginx were what came default.  
I can't think of any other configuration which might cause this. 

Let us remove server from equation.  Tomorrow I will check  if this happens on some other restful micro-framework.  This should confirm server's involvement on this.

**Comment by tuupola** [comment]
Just tested the code from my previous comment with fresh CentOS 6.5 + Apache 2.2 install. It works as expected.

```
$ curl --include http://192.168.50.10/assets/100/200/6/png/
HTTP/1.1 200 OK
Date: Sat, 05 Sep 2015 16:30:58 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.6.12
Content-Length: 26
Connection: close
Content-Type: text/html;charset=UTF-8

/assets/100/200/6/png(/) 

$ curl --include http://192.168.50.10/assets/100/200/6/png
HTTP/1.1 200 OK
Date: Sat, 05 Sep 2015 16:31:06 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.6.12
Content-Length: 26
Connection: close
Content-Type: text/html;charset=UTF-8

/assets/100/200/6/png(/) 
```

**Comment by Abhinav1217** [comment]
ok.  I am out of reasons here now. There might be something wrong in my code or my nginx config.  Here is my Nginx config if someone can point something to me. I am open to all suggestions. 

```
# Common Resources

server {
  listen 80;
  server_name static.CouponApna.local;
  root /var/www/CouponApna/Resource;

              location / {
                  index index.php;
                  try_files $uri $uri/ /index.php?$args;
              }
              location ~ \.php/?(.*)$ {
                  fastcgi_connect_timeout 3s;     # default of 60s is just too long
                  fastcgi_read_timeout 10s;       # default of 60s is just too long
                  fastcgi_pass unix:/run/php-fpm/www.sock;
                  fastcgi_index  index.php;
                  include fastcgi_params;
                  fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
              }
              location ~* ^.+.(jpg|jpeg|svg|gif|css|png|js|ico|xml)$ {
                access_log        off;
                expires           360d;
            }
            location ~ /\.ht {
                deny  all;
            }
}
```

**Comment by silentworks** [comment]
I am closing this one out, I think we tested as much as we could and it doesn't seem to be an issue with Slim itself.
