### ISSUE TITLE
Controllers - Is it possible in slim

### ISSUE THREAD

**Issue by rrubio** [slimphp/Slim#1473]
Hi Guys,

Please excuse me if this has been asked before. Is there a way to add controllers to slim?

Cheers in advance

**Comment by JoeBengalen** [comment]
You can execute any callable, including Controller methods or invokable Actions.

**Comment by akrabat** [comment]
One way in Slim 2 is to use (rka-slim-controller)[https://github.com/akrabat/rka-slim-controller]

The basic functionality shown in rka-slim-controller is built into Slim 3 - see this [`routes.php`](https://github.com/akrabat/slim-bookshelf/blob/master/app/src/routes.php) in my slim-bookshelf app.

**Comment by rrubio** [comment]
thanks guys! :+1:
