### ISSUE TITLE
getting error while adding data

### ISSUE THREAD

**Issue by vinita90** [slimphp/Slim#1474]
i wrote a function.
function insertUpdate() {
    $request = \Slim\Slim::getInstance()->request();
    $update = json_decode($request->getBody());
    $sql = "INSERT INTO Student (name, email, password, contact) VALUES (:name, :email, :password, :contact)";
    try {
        $db = getDB();
        $stmt = $db->prepare($sql);  
        $stmt->bindParam("name", $update->name);
        $stmt->bindParam("email", $update->email);
        //$time=time();
        $stmt->bindParam("password", $update->password);
                $stmt->bindParam("contact", $update->contact);
        //$ip=$_SERVER['REMOTE_ADDR'];
        //$stmt->bindParam("ip", $ip);
                //var_dump($smtp);
        $stmt->execute();
        $update->id = $db->lastInsertId();
        $db = null;
        $update_id= $update->id;
        getUserUpdate($update_id);
    } catch(PDOException $e) {
        //error_log($e->getMessage(), 3, '/var/tmp/php.log');
        echo '{"error":{"text":'. $e->getMessage() .'}}'; 
    }
}

calling by post but getting following error -

{"error":{"text":SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null}}

**Comment by geggleto** [comment]
Yes. This has nothing to do with slim. Your $update->name is an empty string and that is not allowed by your database.

_edit_ Furthermore you are using the correct methods to get and parse the JSON body... There must be a problem with your actual Request.

**Comment by vinita90** [comment]
how can i test my api except doing request from form.

**Comment by geggleto** [comment]
1. You can write unit tests.
2. You can use Postman (an extension for chrome).
3. You can use cURL from command line.

Forms do not send data via JSON, unless you are sending them via an ajax form.

**Comment by tuupola** [comment]
Also [Paw](https://luckymarmot.com/paw) is simply amazing.
