### ISSUE TITLE
Remove hard dependency on App in RouteGroup invocation?

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1475]
Can we remove the hard dependency on the `App` class in the `RouteGroup::__invoke` method please?

I am trying to build a `SlimeRouteMapper` class which allows me to use a nested array to define the routes and callbacks, but this at no point interacts with the `App` class, and instead mimics the `App::group` behaviour for nested routes.

Most of the other facets of Slim are only dependant on key requirements to their internal functionality, so it would make sense to me to allow any class to be passed to the method, so that it can be bound to anything.

Either that, or allow it's footprint to be `App $app = null` so I can get away with ignoring it (as I want to really). I know my callback isn't a closure, so doesn't need binding to anything, as it's an existing class and method.

Any thoughts @silentworks @akrabat @gmanricks @codeguy ?

**Comment by designermonkey** [comment]
Sorry, shouldn't add a milestone until it's decided on.

**Comment by designermonkey** [comment]
Looking at it a little more, the invoke method always assumes that the returned callable is a closure irrespective. I can't pass `[[$this, 'groupCallback'], [$routable]]` for example, to my group as a callable, which the resolver resolves fine, as it isn't called with `call_user_func_array` which it really should be.

**Comment by geggleto** [comment]
I assume the reason why we bind the App is to get the closure... you could only then remove the App dependency and replace it with a Container-Interop dependency... I am unsure about the side-effects if you were to ignore at minimum passing the container which slim uses.

**Comment by akrabat** [comment]
I see no reason why the signature can't be `public function __invoke(App $app = null)`

When you send in the PR, don't forget to update the `if` to check for $app being not null before we try to bind to it.

**Comment by designermonkey** [comment]
Certainly can.

**Comment by designermonkey** [comment]
Thanks.
