### ISSUE TITLE
my function returns blank but db have so many records

### ISSUE THREAD

**Issue by vinita90** [slimphp/Slim#1477]
function getProfile() {
    $sql = "select \* from ver3_users u join ver3_data_profiles  p on u.ID = p.profile_id";
    try {
        $db = getDB();
        $stmt = $db->query($sql);  
        $profiles = $stmt->fetchAll(PDO::FETCH_OBJ);
        //print_r($profiles);
        $db = null;
        echo '{"profiles": ' . json_encode($profiles) . '}';
    } catch(PDOException $e) {
        //error_log($e->getMessage(), 3, '/var/tmp/php.log');
        echo '{"error":{"text":'. $e->getMessage() .'}}'; 
    }
}

**Comment by JoeBengalen** [comment]
So ... How is this Slim related?

**Comment by danopz** [comment]
Try to ask such questions on [Stackoverflow](http://stackoverflow.com/questions/tagged/slim).
