### ISSUE TITLE
Complicated dependency structure causes issues if not followed perfectly

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1479]
<del>I am passing a string into a route callable: `Embark\Journey\Home\GetAction`.

The class referenced does not exist, so I would expect an exception from the CallableResolver telling me so, but unfortunately I get:</del>

<del>
```
Catchable fatal error: Argument 1 passed to Slim\Handlers\Strategies\RequestResponse::__invoke() must be callable, string given, called in /Users/designermonkey/Projects/Sites/app.nigella.local.embarknow.net/vendor/slim/slim/Slim/Route.php on line 317 and defined in /Users/designermonkey/Projects/Sites/app.nigella.local.embarknow.net/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php on line 32
Call Stack
#   Time    Memory  Function    Location
1   0.0002  240616  {main}( )   .../index.php:0
2   0.0095  1181144 Slim\App->run( )    .../index.php:32
3   0.0149  1903568 Slim\App->callMiddlewareStack( )    .../App.php:308
4   0.0149  1903712 Slim\App->Slim\{closure}( ) .../MiddlewareAwareTrait.php:114
5   0.0149  1903760 call_user_func:{/Users/designermonkey/Projects/Sites/app.nigella.local.embarknow.net/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:67} ( ) .../MiddlewareAwareTrait.php:67
6   0.0149  1904016 Slim\Csrf\Guard->__invoke( )    .../MiddlewareAwareTrait.php:67
7   0.0150  1907032 Slim\App->__invoke( )   .../Guard.php:146
8   0.0155  1935704 Slim\Route->run( )  .../App.php:398
9   0.0155  1935840 Slim\Route->callMiddlewareStack( )  .../Route.php:288
10  0.0155  1936880 Slim\Route->__invoke( ) .../MiddlewareAwareTrait.php:114
11  0.0157  1961136 Slim\Handlers\Strategies\RequestResponse->__invoke( )
```
</del>

<del>
I have no idea even how to debug this :(

If I've been an idiot, please let me know.</del>

**Edit:** The original issue is my code, but the cause is as the title edit above

**Comment by geggleto** [comment]
Can we see the actual code ?

Could be a bug with something, there were recent changes made to the callable resolver things....

**Comment by designermonkey** [comment]
As this is a custom code route mapper, it turns out that it is because the container isn't passed along properly during my mapping process.

I have to say from reading through all this code, I am pretty shocked at how much the container is passed around outside of class definitions in the initial container setup! The point of a dependency container is to resolve dependencies before your app runs, so code like this

``` php
    public function map(array $methods, $pattern, $callable)
    {
        if ($callable instanceof Closure) {
            $callable = $callable->bindTo($this);
        }

        $route = $this->container->get('router')->map($methods, $pattern, $callable);
        if (is_callable([$route, 'setContainer'])) {
            $route->setContainer($this->container);
        }

        if (is_callable([$route, 'setOutputBuffering'])) {
            $route->setOutputBuffering($this->container->get('settings')['outputBuffering']);
        }

        return $route;
    }
```

taken from the App class is pretty bad. The chain here should be that the Router has the container and passes it along to the Route before it returns it from the `map` method. This code is really complicated because of this requiring the container at a later stage.

Dependencies of the Router (being Route) require a Container, so that by logic becomes a dependency of the Router, as it is a factory for Route; It must already have all the requirements for Route, as Route can't function correctly without them.

**Comment by designermonkey** [comment]
The OCD in me is making me tidy this up, hopefully won't be long chaps...

**Comment by geggleto** [comment]
Yeah I am all for cleaning up the internals... It does appear to be a mess and I dislike reading the router code especially since there is no comments describing what is going on.

Why can't we actually just have a RouteFactory that handles the construction of the routes ?
Dependencies can be injected from the container and then the logic for making a route falls in that factory class.

**Comment by designermonkey** [comment]
Personally, I would be all for a factory instance, but I'll keep the footprint of classes the same for now, and just tidy the functionality.

**Comment by geggleto** [comment]
Maybe for 3.1 ... Reading through the source it just screams spaghetti  ... there are a lot of optimizations that can be done ... but I know there is quite a push to get it to release atm.

**Comment by designermonkey** [comment]
Maybe I should come back to this another day then.

**Comment by geggleto** [comment]
I would tag for 3.1 might as well do it proper. Then again others might not care for the Factory methods ;)

**Comment by designermonkey** [comment]
It's open for discussion anyway :)

**Comment by silentworks** [comment]
I would like to see a PR with the cleanups, even if it includes a RouteFactory, anything to make the code more readable and easy to follow is welcomed.

**Comment by silentworks** [comment]
@designermonkey @geggleto I have taken a shot at this and would like some feedback from both of you #1497

**Comment by designermonkey** [comment]
Hi @silentworks I can see where you're aiming for here, but I must say I think it is still too overly complicated. No offence meant.

To me, the complication lies within the Route and Router classes themselves; the fact they both need a container, middleware awareness, callable resolving etc, and the hoops being jumped through to make them work. The aim of Slim 3 was to simplify and decouple the overly complicated dependencies (at least how I understood when we started). Dependencies in groups like a Router and Route are fine, and some obvious ones are too like a container, but I feel like the chain here is too heavy at the bottom.

Re-reading my comments earlier in the thread, I may have come off a little hot, with no intention, so apologies there. This is way better than it was.

I really want to delve into this properly, with the eye on the separation of routing as much as possible from Slim, so it could be used without it (I'm not suggesting actual separation from the codebase).

Can I ask for someone to explain the invocation strategy idea? Why was this needed?

**Comment by akrabat** [comment]
The invocation strategy came about because some people really wanted the function signature for route callables to be very close to Slim 2's to make it easier for migration and setting parameter defaults.

**Comment by akrabat** [comment]
Nothing further to do here.

If any PRs turn up, we can evaluate them.
