### ISSUE TITLE
Not matching routes with parameters

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1482]
I will investigate this now, but just logging the issue.
- When I have a route `/recipes` a match is made by the router.
- When I have a route `/recipes/{handle}` no match is made.

This occurs whether I explicitly define routes separately, or as a grouped route, as per the docs.

I have tried this with a nested route separately and as a group using `/recipes/members` which matches, so narrowed down to it being parameters.

**Comment by geggleto** [comment]
I dont see why you would think /recipes would match /recipes/{handle}... you did not mark the 2nd route with handle being optional

**Comment by designermonkey** [comment]
Each route is defined in the router separately, so should match.

``` php
// $app->group('/recipes', function () {
//     $this->get('', 'Embark\Recipes\RecipesLandingAction');
//     $this->get('/{recipe-handle}', 'Embark\Recipes\RecipesEntryAction');
// });

$app->get('/recipes', 'Embark\Recipes\RecipesLandingAction');
$app->get('/recipes/{recipe-handle}', 'Embark\Recipes\RecipesEntryAction');
```

**Comment by geggleto** [comment]
and what route are you accessing? just /recipes ?

**Comment by silentworks** [comment]
I have this exact setup in my test app and its working as expected.

https://github.com/silentworks/idiaz/blob/develop/config/routes.php

You can clone the repo and test.

**Comment by designermonkey** [comment]
Hi @silentworks do you know what commit Slim is at that composer pulls down for that repo?

I am currently at: 13a0fbce7064ea1b2e60b7c788d2d097d44dd732

**Comment by silentworks** [comment]
@designermonkey I just updated to that hash and its all still working, you can clone the repo now I have pushed my updates.

**Comment by silentworks** [comment]
@designermonkey the issue is the hyphen in the placeholder, make it snake case or just one word and it will work correctly.

**Comment by designermonkey** [comment]
Well spotted that man @silentworks !!

it never occurred to me, coming from an XML and XSLT background, I wouldn't have thought.

I don't suppose there is any way we can allow hyphens? ;P

**Comment by geggleto** [comment]
me thinks its a quirk of FastRoute :D

**Comment by designermonkey** [comment]
ah well. Thanks for the help guys, really appreciate it (so busy here).

**Comment by akrabat** [comment]
you could possibly escape it with a backslash?
