### ISSUE TITLE
Route parameters in Middleware

### ISSUE THREAD

**Issue by errodr** [slimphp/Slim#1487]
Using Slim v3, beta 2

I have this simple route/middleware combination:

``` php
$app->get('/hello/{name}', function($request, $response, $args) {
    echo 'Middleware test, hello: ';
})->add(function($request, $response, $next) {
    $name = strtoupper($request->getAttribute('name'));
    $name2 = strtoupper($request->getParam(''name));

    $response = $next($request, $response);
    $response->getBody()->write($name);
    $response->getBody()->write($name2);

    return $response;
});
```

The result I'm getting is: **Middleware test, hello:**

I have tried a few things, neither `getParam` or `getAttribute` seem to work. I'm not sure why I am unable to retrieve the **name** route parameter from the request.

Can someone point me in the right direction?

Thanks

**Comment by akrabat** [comment]
The route's parameters are not assigned to the request until the route callable is [invoked](https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/Strategies/RequestResponse.php#L37-L39).

This is why it isn't in the request object in your route middleware as the route middleware is executed before the route callable and hence the $request doesn't have them. However, as the system has determined which route to dispatch, the information you need is in the request's `routeInfo` attribute, so this will work:

``` php
$app->get('/hello/{name}', function ($request, $response, $args) {
    $response->write('Middleware test, hello: ');
})->add(function ($request, $response, $next) {

    $routeParams = $request->getAttribute('routeInfo')[2];
    $name = strtoupper($routeParams['name']);

    $response = $next($request, $response);
    $response->write($name);

    return $response;
});
```
