### ISSUE TITLE
PUT & DELETE not working with curl

### ISSUE THREAD

**Issue by ansdma** [slimphp/Slim#149]
Hi,

I'm trying to do PUT & DELETE requests with curl but I got an error. I was doing:
 `curl -X DELETE http://localhost/\~Home/slim/delete` and got the following error : 

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Access forbidden!</title>
<link rev="made" href="mailto:you@example.com" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
body { color: #000000; background-color: #FFFFFF; }
a:link { color: #0000CC; }
p, address {margin-left: 3em;}
span {font-size: smaller;}
/*]]>*/--></style>
</head>

<body>
<h1>Access forbidden!</h1>
<p>

You don't have permission to access the requested object.
It is either read-protected or not readable by the server.

</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:you@example.com">webmaster</a>.

</p>

<h2>Error 403</h2>
<address>
  <a href="/">localhost</a><br />

  <span>Tue Jul 19 21:44:51 2011<br />
  Apache/2.2.14 (Unix) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l PHP/5.3.1 mod_perl/2.0.4 Perl/v5.10.1</span>
</address>
</body>
</html>
```

Any clue please.

Many Thanks

**Comment by njh** [comment]
At a guess, I think this is coming straight from Apache, not Slim.

Documentation for the <LIMIT> directive:
http://httpd.apache.org/docs/current/mod/core.html#limit

**Comment by codeguy** [comment]
I don't think you're hitting the Slim application... I would make sure your .htaccess file is successfully funneling requests to your bootstrap file. A simple test case can confirm this. Closing this out. However, _please_ let me know if you can confirm this is a Slim issue and I'll be happy to re-open.
