### ISSUE TITLE
Question about the Slim\Views namespace

### ISSUE THREAD

**Issue by feryardiant** [slimphp/Slim#1493]
Hi, guys.

First of, sorry for post it in wrong place. I've tried to post in [support forum](http://help.slimframework.com/) but I can't see it anywhere right after submited.

Well, couple hours ago I create Slim 3.x view component using [Plates](http://platesphp.com) template system. Could you please [check it out](http://github.com/feryardiant/slim-plates-view) and let me know what you think. Also, could you please allow me to published it under `Slim\Views` namespace at packagist?

Regards :grin:

**Comment by silentworks** [comment]
Hi @feryardiant I had a look at the code earlier and it looks really good, but unfortunately I will have to ask if you can change the namespace from `Slim\Views` to your own namespace. 

We tend to create our own namespaces for projects not managed by the Slim team to keep support requests away from the Slim team and also to keep the association clear.

**Comment by feryardiant** [comment]
Hi @silentworks 

Thanks for your advice and sure I'll change the namespace from now on. I just think that it should be cool if distributed under `Slim` namespace, hehehe. :grin: 

Regards.
