### ISSUE TITLE
problem in writing slim function

### ISSUE THREAD

**Issue by vinita90** [slimphp/Slim#1494]
Please help and show me how I write the slim code for this call:
http://myapp.com/api/profiles/?name=4&contact=9999999999

**Comment by ppetermann** [comment]
Somehow your issue is missing a description of your actual problem,
and the link you provided seems to forward me to a chinese(?) android store?

**Comment by silentworks** [comment]
I think this is spam, also this is the wrong place for questions about how to use Slim.
