### ISSUE TITLE
Return '405 Method not allowed' when a route exists, but not for the requested method

### ISSUE THREAD

**Issue by njh** [slimphp/Slim#150]
I am implementing a RESTful application and it would be great if Slim returned 405 if a route existed but not for the requested method.

Thanks!

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.6

**Comment by nielsen** [comment]
+1

**Comment by alexturpin** [comment]
I also think this would be a better behaviour than the 404

**Comment by codeguy** [comment]
@Xeon06 Agreed. I'm working on a fix.

**Comment by codeguy** [comment]
Now available in the develop branch. Docs available at http://slimframework.com/documentation/develop#routes

Enjoy!
Josh

**Comment by aaronjameslang** [comment]
This appears to be broken again. Slim is returning 404 when the URL matches but not the method, it should return 405.

**Comment by silentworks** [comment]
@aaronjameslang what version of Slim are you using?

**Comment by aaronjameslang** [comment]
2.4.3, according to composer.lock . Thanks
4906b77a07c7bd6ff1a99aea903e940a2d4fa106

**Comment by silentworks** [comment]
Right I can see it was done here https://github.com/codeguy/Slim/blob/1.5.1/Slim/Slim.php#L1059 but was removed.

**Comment by aaronjameslang** [comment]
Is there any information on why it was removed? Or a workaround?
