### ISSUE TITLE
Error messages changes while being caught

### ISSUE THREAD

**Issue by flyon** [slimphp/Slim#1501]
Currently, if an error occurs anywhere in my slim based API, if gets caught in Slim.php:1407 handleErrors.

There, while debugging, I can see the 'correct' **$errorstr** with some usefull error message about what kind of error occured. Then 3 lines further slim throws it's own error which get's caught by Slim.php on line 1374:

```
    } catch (\Exception $e) {
        if ($this->config('debug')) {
            throw $e;
```

Here, $e is an Exception, but the **message has changed** to:

`davine\core\collections\ResourceCollection::serialize() must return a string or NULL`

Whatever error initially occured, I always get this error message in Slim's error report. 
The stacktrace still helps me get close to the point where the initial error occured,

But the error report always shows:

```
Type: Exception
Message: davine\core\collections\ResourceCollection::serialize() must return a string or NULL
File: F:\wamp\www\davine\daServer\vendor\slim\slim\Slim\Slim.php
Line: 1411
```

Surely this must at some level have to do with my own classes. 
However I do not understand why this class ResourceCollection (which extends ArrayObject) would need to implement serialize, and why the way Slim handles exceptions would require that?

**Comment by geggleto** [comment]
Serialize is not required by Slim ... but I have no idea why your app is trying to serialize your collection.

Is there some sort of middleware going on or?

**Comment by geggleto** [comment]
What version of slim is it?

1411 is a blank space in the head repo.
but it might be https://github.com/slimphp/Slim/blob/2.x/Slim/Slim.php#L1412

**Comment by flyon** [comment]
yes that's the one. no, no other middleware

**Comment by flyon** [comment]
version 2.6.2

**Comment by akrabat** [comment]
Something is trying to serialise an instance of ResourceCollection. Usually this implies you have it in the session.

**Comment by flyon** [comment]
I store one big Instance of a class with APC, which has plenty of ResourceCollection instances connected to it. So apc_fetch / apc_store will probably call serialize/unserialise, but I guess it always used ArrayObject its native implementation, as it never caused trouble.

I see APC converts parameters to strings in the call stack, I'm guessing this might cause the problem?

**Comment by akrabat** [comment]
As Slim 3 is released, we are only fixing Security issues on Slim 2.
