### ISSUE TITLE
Disable output buffering?

### ISSUE THREAD

**Issue by SergeyTsalkov** [slimphp/Slim#1502]
My site needs a page that returns very large amounts of text, on the order of several hundred MB. Slim's output buffering makes this problematic: not only does it use lots of memory, but nothing shows up on the user's screen until the whole page is done building.

I'd really like to disable output buffering so my controller can send the page in pieces as it's built. Is that possible?

**Comment by designermonkey** [comment]
Which version of Slim are you using?

**Comment by SergeyTsalkov** [comment]
I'm using Slim 2.6.2, the latest! I guess this is changing with Slim 3
coming out soon?

**Comment by designermonkey** [comment]
I just wanted to verify it so we know :) I'm not sure yet on how to resolve the issue, but we know where to be looking now.

**Comment by akrabat** [comment]
Yes - you can turn off output buffering on Slim 3, Set the `outputBuffering` setting to `false`.

**Comment by designermonkey** [comment]
Can you do the same on Slim2 though?

**Comment by geggleto** [comment]
You can flush the buffer.... yourself... http://php.net/manual/en/function.ob-flush.php ... It's a bit of a pain...

**Comment by akrabat** [comment]
As Slim 3 is released, we are only fixing Security issues on Slim 2.
