### ISSUE TITLE
Slim 3 Bug - can't set the content type in separate files?

### ISSUE THREAD

**Issue by lautiamkok** [slimphp/Slim#1503]
I think there is a bug in Slim 3.

```
    require_once __DIR__ . '/../vendor/autoload.php';

    $app = new \Slim\App();

    // Routes:
    $app->get('/hello/{name}', function ($request, $response, $args) {

        // fetch the id attribute to discover what was matched.
        $name = $request->getAttribute('name');

        $response->getBody()->write('Hello, ' . $name);
        return $response->withHeader('Content-type', 'application/json');

    });

    $app->run();
```

Test
http://example.com/public/hello/world

```
   Connection Keep-Alive
    Content-Length 12
    Content-Type application/json
    Date Sun, 20 Sep 2015 06:53:57 GMT
    Keep-Alive  timeout=5, max=100
    Server Apache/2.4.7 (Win32) PHP/5.5.8
    X-Powered-By PHP/5.5.8
```

I get `Content-Type` as `application/json` which is correct.

But if I try **separate** the code and use require_once or include to fetch the file, the `Content-Type` becomes `text/html`!

```
    $app->get('/hello/{name}', function ($request, $response, $args) {

        // fetch the id attribute to discover what was matched.
        $name = $request->getAttribute('name');

        require_once __DIR__ . '/hello.php';

    });

    $app->run();
```

hello.php,

```
    $response->getBody()->write('Hello, ' . $name);
    return $response->withHeader('Content-type', 'application/json');
```

Test
http://example.com/public/hello/world

```
    Connection Keep-Alive
    Content-Length 12
    Content-Type text/html
    Date Sun, 20 Sep 2015 06:53:57 GMT
    Keep-Alive  timeout=5, max=100
    Server Apache/2.4.7 (Win32) PHP/5.5.8
    X-Powered-By PHP/5.5.8
```

It seems can't set the content type in the separate file which does not really make sense...

Why?? Any ideas?

**Comment by ppetermann** [comment]
First of all: thats now how you should separate things, 
a good example on how to do this would be in akrabats skeleton: https://github.com/akrabat/slim3-skeleton

Second: you are missing a return - the return within your required file marks the return value of the require_once, hence you have to 
`return require_once __DIR__ . '/hello.php';`
otherwise you will return the original $response object, and not the new instance created by $response->withHeader(...)

so, not a bug in Slim.

**Comment by lautiamkok** [comment]
I see! thank you very much. I was migrating from slim 2 to 3. I didn't have to use `return` in slim 2. thanks!
