### ISSUE TITLE
[Slim_Http_Response] Expose response content

### ISSUE THREAD

**Issue by maboiteaspam** [slimphp/Slim#152]
Hi,

Slim_Http_Response does not expose response content, so it is impossible to add a hook that would update this content for 'whatever i want todo before i render the content'.
For exemple, i needed to insert javascript before the content is rendered and i m stuck.

Is this possible to have a such method added ?

Bye

**Comment by codeguy** [comment]
`$res->write('foo')` appends content to the response body. `$res->body('foo')` overwrites the response body. Do you require direct accessors for the response body, e.g. `$res->getBody()` and `$res->setBody()`?

**Comment by maboiteaspam** [comment]
Hi,

sorry i did not read the code carefully enough !!! 
I simply need to call for `$res->body(null)` to get the body content.

And yes, direct accessors is what i was looking for.

Thanks for all,
and sorry for unnecessary issue.

bye
