### ISSUE TITLE
App->subRequest not working directly with Router->pathFor

### ISSUE THREAD

**Issue by pokmot** [slimphp/Slim#1521]
I am working in a sub-folder, so getBasePath() = '/MM/systems/admin'

$App->subRequest('POST', $router->pathFor('myNamedRoute')) produces:
/MM/systems/admin/myroute

However, subRequest is only expecting 'myroute'

To make this work, I have to do a str_replace:

$App->subRequest('POST', str_replace($request->getUri()->getBasePath(), '', $router->pathFor('myNameRoute')));

**Comment by akrabat** [comment]
Hmm.
Does the router need a different method for this? or a parameter on pathFor() ?

**Comment by pokmot** [comment]
My gut feeling is that something like $router->internalPathFor() would be appropriate; it would make it clear whether the path is returned with or without getBasePath() prepended.

**Comment by akrabat** [comment]
I quite like `internalPathFor()` too.

**Comment by pokmot** [comment]
I've made a suggested code change (#1551) - unfortunately I won't have a chance to update any unit tests, but hope it helps/is useful.

**Comment by akrabat** [comment]
ok. I'll sort out.

**Comment by silentworks** [comment]
This is now fixed with the new `$router->relativePathFor()` method.
