### ISSUE TITLE
Some 2 -> 3 updates problems.

### ISSUE THREAD

**Issue by Serhioromano** [slimphp/Slim#1525]
First i had config.php file that was loaded firts and there I had

``` php
$app = new \Slim\Slim();
$app_config = array(
    'debug'          => TRUE,
    'templates.path' => 'templates'
);
$app->config($app_config);
```

I initiated and configured application. later in `index.php` or anywhere else I could simple call `\Slim\Slim::getInstance()` and I always had access to `$app` object from any place in the code. 

I am not sure how it works now. I do not know how to get access to my initial `$app = new \Slim\App()` in other methods and if there is configuration still.

Also I cannot find how to create `$request` object? I mean the one that is passed to my `->post`. I call other methods there and I cannot pass $request there. I want to get instance of that object programmatically and get access to my POST parameters. Possible? How? 

In fact the only reason I access `$app` with `\Slim\Slim::getInstance()` in the other places is to use `$app->request->params('name')`.

**Comment by geggleto** [comment]
the method signature changed and your route callables are provided with a request and response object.

```
$app->get('/', function (Request $req, Response $resp, $args) { });
```

**Comment by Serhioromano** [comment]
That is I know. But let's say

``` php
$app->get('/', function (Request $req, Response $resp, $args) { 
    \My\Api::call()
});
```

how do I get POST params in my `\My\Api::call()` if I cannot pass `$request` there?

**Comment by geggleto** [comment]
You will need to modify your `\My\Api::call()` to accept parameters. It is not possible with PSR-7 to globally fetch the Request object as any modification to it results in the invalidation of the previous object because PSR-7 request/response objects are VALUE objects and are immutable.

**Comment by akrabat** [comment]
``` php
$app->post('/', function (Request $req, Response $resp, $args) { 
    \My\Api::call($request);
});
```

or

``` php
$app->post('/', function (Request $req, Response $resp, $args) { 
    \My\Api::call($request->getParsedBody());
});
```

**Comment by Serhioromano** [comment]
My real project is more complicated than an example. It is high level modular API framework. I will not explain why and paste all code here, but the fact is - I need a way to get access to `$request` object without having it injected into method.

The `$app->request` is still there. What about `$app` instances?

**Comment by geggleto** [comment]
No App instances 
No access to $app->request ... $app->request will pull the original request object from the container, which will NOT have any middleware executed on it.

**Comment by Serhioromano** [comment]
Is it a limitation of RC or is it a concept? Is there configuration like it used to be for debug and template path?

**Comment by akrabat** [comment]
One of the design goals of Slim 3 is to remove globals which leads to less than optimal software design due to undesirable coupling of code the app, request, response and router objects.

i.e. Your underlying code should not expect a global app/request object to exist and so Slim 3 enforces this by not providing a way to get a the app instance. The PSR-7 standard further enforces the idea of injecting dependencies into your objects due to the immutability of the Request object which means that `$app->request` is out of date as soon as `run()` is executed. As such, I would recommend that you refactor to support injecting the `$request` in the route callable into the rest of your application.

**Comment by Serhioromano** [comment]
before I used `request->params()` which returned parameter sent by POST or GET. But how there is no such a parameter and my universal parameter aggregator looks like this.

``` php
$get  = (array)$request->getQueryParams();
$post = (array)$request->getParsedBody();
$req  = array_merge($get, $post);
```

Am I on the right track? The code looks a little weird to me, but this is only what I have managed to do. Is there more elegant way?

**Comment by akrabat** [comment]
If you use Slim's implementations, then there is [`getParam()`](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L1033) and [`getParams()`](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L1054) on the `Request` object.

**Comment by Serhioromano** [comment]
This is true. It works. There was no autocompletion/intellisense for that. So I did not know that this exists.

I am runing it like this

``` php
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;

$app->map(['POST', 'GET'], '/{module}/{group}/{action}[/{id}]',
    function (ServerRequestInterface $request, ResponseInterface $response, $params)
```

Is it correct or there are Slim's instances?

**Comment by akrabat** [comment]
Correct - `getParam` and `getParams` are Slim specific and aren't in the PSR-7 interface, so you would be coupling to the Slim implementation.

**Comment by geggleto** [comment]
`function (\Slim\Http\Request $request, \Slim\Http\Response $response, $params)`
should give you autocomplete with getParam getParams

**Comment by Serhioromano** [comment]
Thank you everyone. It is working now.
