### ISSUE TITLE
are there any $app->pass() method in version 3 ?

### ISSUE THREAD

**Issue by p3ym4n** [slimphp/Slim#1527]
hi, 
in ver2 we used $app->pass() in some situations that the matched route doesn't fit the given request after checking some if(s).so we pass to the next route.
in version 3 i can't find any way to pass a route after these checks , so are there any alternates for that? or some way to pass a route from middleware ?

**Comment by geggleto** [comment]
https://github.com/nikic/FastRoute for router documentation!

**Comment by p3ym4n** [comment]
@geggleto all that document are talking about how to define routes. 
i'm looking for a way to pass the matched route from inside it and i think it doesn't relates to the route component.
so tell me if i'm wrong 😃.

**Comment by p3ym4n** [comment]
i finally find it , its $app->subRequest() method .
