### ISSUE TITLE
[documentation] slim.after.router hook

### ISSUE THREAD

**Issue by maboiteaspam** [slimphp/Slim#153]
Hi,

As doc said:

> slim.after.router
> This hook is invoked after the router is dispatched, before the Response is sent to the client, and before output buffering is 
> turned off. This hook is invoked once during the Slim application lifecycle.

But the code say this :

``` self::response()->write(ob_get_clean());
            self::applyHook('slim.after.router');
```

So hook is triggered after the output buffering is turned off.

And the doc is not correct.

Doc is : http://www.slimframework.com/documentation/stable#slim-application-hooks-filters
Code is : Slim.1.3.5::run()

bye

**Comment by codeguy** [comment]
Docs updated.
