### ISSUE TITLE
Cookie Handling

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#154]
I just upgraded my Application for an API to 1.5 - which works great. But generally I don't need cookies for this. Slim however wants to set one on an otherwise cookieless domain. Is there a way to completely disable cookies? I've set all config values having anything to do with cookies to `null`, however that does not seem to have any effect.

```
Set-Cookie: c81c2617a01416d4efba06d1d0434d05=deleted; expires=Thu, 29-Jul-2010 17:05:50 GMT; path=/ 
```

**Comment by codeguy** [comment]
By default, Slim stores session data in an encrypted cookie. In your app config, set `session.handler` to `null` to use the default PHP session store. Should solve your issue. If not, leave another comment here and I'll investigate further.

**Comment by hexa2k9** [comment]
That fixed it. Thanks Josh.

**Comment by lucianboldu** [comment]
In php.ini i have:  
session.use_cookies = 0
session.use_only_cookies = 1
session.auto_start = 0

I receive the following message when i set 
$app = new Slim(array(  
 'session.handler' => null
));

Fatal error: Uncaught exception 'ErrorException' with message 'session_start(): open(/var/lib/php/session/sess_38af698c85cd8e2c1e0f5f95810e9679, O_RDWR) failed: Permission denied (13)' in /usr/share/nginx/v1/Slim/Slim.php:211
Stack trace:
)' in /usr/share/nginx/v1/Slim/Slim.php:211
Stack trace:
#0 [internal function]: Slim->handleErrors(2, 'session_start()...', '/usr/share/ngin...', 211, Array)
#1 /usr/share/nginx/v1/Slim/Slim.php(211): session_start()
#2 /usr/share/nginx/v1/index.php(7): Slim->__construct(Array)
#3 {main}
  thrown in /usr/share/nginx/v1/Slim/Slim.php on line 211

Fatal error: Exception thrown without a stack frame in Unknown on line 0

**Comment by codeguy** [comment]
By default, Slim uses a Cookie for session data. By setting `session.handler` to `null`, Slim uses whatever your default session handler is; in most default PHP installs, I believe this is usually a flat file somewhere in `/tmp`. This looks like the user running the PHP process does not have permission to write to this flat file to store session data. Try setting a custom session directory with the session save path ini setting...

http://www.php.net/manual/en/session.configuration.php#ini.session.save-path

**Comment by lucianboldu** [comment]
i moved my session path to /tmp from /var/lib/php/session . Thanks alot
