### ISSUE TITLE
What version does not require composer?

### ISSUE THREAD

**Issue by neosin** [slimphp/Slim#1549]
I have used Slim before and came back to it now for another project but I find that it now requires composer to use. Since we are not able to use composer here, what version does not require composer?

**Comment by silentworks** [comment]
Current stable version doesn't require composer to run. So anything in the 2.x version can be used without composer, also you can use composer during development for 3.x and upload the entire project along with the vendor directory and it should work as normal. Remember you shouldn't be doing composer related stuff on production servers.

**Comment by akrabat** [comment]
For what it's worth, I commit my vendor directory to git, so that composer is only used on dev when changing the requirements.
