### ISSUE TITLE
getMethod + halt before route definition not sending content-body in response 

### ISSUE THREAD

**Issue by lucianboldu** [slimphp/Slim#155]
if i have something like this:

$app = new Slim();
header("Allow: GET,PUT");
<b>$method = $app->request()->getMethod();</b>

<b>
if ($method == "HEAD")
{ 
        $app->halt(403,"Unspecified method... please view allow header");
}

if ($method == "SEARCH")
{ 
        $app->halt(403,"Unspecified method... please view allow header");
}

</b>

$app->get('/', function () {
     echo "This is the GET route";
});

$app->put('/put', function () {
    echo 'This is a PUT route';
});

HEAD http://api.domain.com/ HTTP/1.1
User-Agent: Fiddler
Host: api.domain.com
Accept-Encoding: gzip

When i make a SEARCH or HEAD request i receive something like that:

HTTP/1.1 403 Forbidden
Date: Sat, 30 Jul 2011 00:04:31 GMT
Content-Type: text/html
Connection: keep-alive
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Allow: GET,PUT
Content-Length: 46

---

i know that HEAD is not suppose to return any content-body, but in the second post i detailed the problem from logs
when i call the SEARCH method the content is received but with the error specified in the second post
.

The response doesn't contain the: <b>Unspecified method... please view allow header</b>
The Content-Length is correct but the response is not sending.
even if i send another response code then response is the same.

---

The content body is received when i put the <b>$app->halt(403,"Unspecified method... please view allow header");</b> in then GET route or in other route implemented.

$app->get('/', function () {
  $app->halt(403,"Please Login ... ");
 echo "This is the GET route";
});

I think there is a problem!
Have a nice day.

**Comment by lucianboldu** [comment]
Seconds ago i tried with curl the same HEAD call to server:

 curl -v -X HEAD -H "Content-Type:application/json" -H "Accept-Encoding: gzip,deflate"  api.domain.com/

the curl call remain blocked at  
< Allow: GET,PUT
< Content-Length: 23

and after i wait a few seconds i received:
- transfer closed with 23 bytes remaining to read
- Closing connection #0
  curl: (18) transfer closed with 23 bytes remaining to read

The content lenght is different from first post because i use another message.

This is the error message from nginx logs:
2011/07/30 03:21:20 [error] 3874#0: *76 FastCGI sent in stderr: "PHP Fatal error:  Uncaught exception 'Slim_Exception_Stop' in /usr/share/nginx/html/Slim/Slim.php:780
Stack trace:
#0 /usr/share/nginx/html/Slim/Slim.php(802): Slim->stop()
#1 /usr/share/nginx/html/index.php(22): Slim->halt(403, 'Unspecified method ... ')
#2 {main}
  thrown in /usr/share/nginx/html/Slim/Slim.php on line 780" while reading response header from upstream, client: xx.xx.xx.xx, server: api.domain.com request: "HEAD /v1/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.domain.com"

curl -v -X SEARCH -H "Content-Type:application/json" -H "Accept-Encoding: gzip,deflate"  api.domain.com/

<html><head><title>Slim Application Error</title><style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style></head><body><h1>Slim Application Error</h1><p>The application could not run because of the following error:</p><h2>Details:</h2><strong>Message:</strong> Undefined index: SEARCH<br/><strong>File:</strong> /usr/share/nginx/html/Slim/Router.php<br/><strong>Line:</strong> 116<br/><h2>Stack Trace:</h2>#0 /usr/share/nginx/html/Slim/Router.php(116): Slim::handleErrors(8, 'Undefined index...', '/usr/share/ngin...', 116, Array)<br />
#1 /usr/share/nginx/html/Slim/Slim.php(1013): Slim_Router->getMatchedRoutes()<br />
#2 /usr/share/nginx/html/v1/index.php(80): Slim->run()<br />
- Connection #0 to host api.domain.com left intact
- Closing connection #0
  #3 {main}

**Comment by codeguy** [comment]
You should place the method detection into a hook that is run before each application route instead of performing the detection in the global namespace.

**Comment by codeguy** [comment]
Closing this out for now as it's not really a bug. Feel free to email me directly or start a chat on IRC.

**Comment by lucianboldu** [comment]
Everything works great with hooks. Thanks alot
