### ISSUE TITLE
Ability to get the "Accept" header from Request

### ISSUE THREAD

**Issue by aneek** [slimphp/Slim#1556]
This can be categorized as a Feature Request. An use case is,
As a developer I might want to prepare the Response differently depending on the "Accept" header present in the Request.

For instance the below example:

``` php
<?php

require 'vendor/autoload.php';

$app = new Slim\App();

$app->get('/hello/{name}', function ($request, $response, $args) {
    $accept = $request->getAcceptHeader();
    switch ($accept) {
        case 'application/json':
            $response->write(json_encode([
              'message' => 'Hello ' . $args['name']
            ]));
            break;
      case 'text/html':
          $response->write('<div>Hello ' . $args['name'] . '</div>');
          break;
    }
    return $response;
});

```

This `$request->getAcceptHeader();` might have the same logic like  `Error::determineContentType($acceptHeader)` has.

I might be missing something but as of now Request class doesn't have this feature.

@akrabat - If you think this is a valid request then I'd like to contribute on this.
Thanks!

**Comment by silentworks** [comment]
At the moment this can be done via a middleware, actually there is already a middleware created that deals with this nicely. You can check it out here https://github.com/rszrama/negotiation-middleware

**Comment by aneek** [comment]
Ahh, this seems appropriate. Only thing is that to enable this type of content negotiation we have to add this middleware. However, I still think a helper method to get proper accept header would be great. But yes, since a middleware exists this can be closed.
