### ISSUE TITLE
setData using Array doesnt render View

### ISSUE THREAD

**Issue by kennethsam** [slimphp/Slim#156]
When trying to setData using an array - the views are not rendered.

$app->view()->setData(array('title'=> 'title','body'=>'body'));

However the following below works

 $app->view()->setData('title',$title);
 $app->view()->setData('body',$body);

**Comment by maboiteaspam** [comment]
hi,

wich view class are you talking about ?
wich version ?

Because in 1.3.5, code looks fine :

``` php
public function setData() {
        $args = func_get_args();
        if ( count($args) === 1 && is_array($args[0]) ) {
            $this->data = $args[0];
        } else if ( count($args) === 2 ) {
            $this->data[(string)$args[0]] = $args[1];
        } else {
            throw new InvalidArgumentException('Cannot set View data with provided arguments. Usage: `View::setData( $key, $value );` or `View::setData([ key => value, ... ]);`');
        }
    }
```

bye

**Comment by kennethsam** [comment]
TwigView

Version 1.5.0

Ken

**Comment by codeguy** [comment]
I really don't have enough information to go on, and I'm doubtful (at the moment) that this is a bug. Hop on IRC when you get a chance and I'll be happy to talk with you more about this so you can find a solution.
