### ISSUE TITLE
Custom Error Handler

### ISSUE THREAD

**Issue by errodr** [slimphp/Slim#1560]
I would like to create a custom error handler specifically to handle a 403 response. I'd like to be able to throw a "Forbidden" exception and have a response with a 403 code returned.

I see where the other handlers are defined I just don't understand how to wire up a new, custom error/exception handler.

Thanks

**Comment by juliangut** [comment]
On https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L343 you see that any \Exception is finally handled by 'errorHandler' service

``` php
$errorHandler = $this->container->get('errorHandler');
$response = $errorHandler($request, $response, $e);
```

Just replace default error handler with your own and check for exception type in there

``` php
if ($exception instanceof ForbiddenException) {
    return $response->withStatus(403);
}
```

**Comment by juliangut** [comment]
Anyway you might check into verify user credentials early on a Middleware instead of in a route callback

**Comment by errodr** [comment]
Thanks much!
