### ISSUE TITLE
Response Body is empty

### ISSUE THREAD

**Issue by shashvattrip** [slimphp/Slim#1561]
I have been stuck at this for sometime now can cannot figure out what the problem is. The same code was working few minutes ago and it suddenly stopped working, on its own, without me making any changes to it whatsoever.
As you can see from the code, there are two roles. Now, when I try to use the /login POST API, I am able to login with RoleA. However with RoleB (the only other role in the DB) I get an empty response from the server. When I say empty I mean the body is empty with response status 200 and content length = 0.

I know its not the php code because the same code was working a few minutes ago and it still is on my AWS instance. I have checked apache error logs and couldn't find anything. What could be the problem and how do I go about finding the solution (or even the zeroing in on the problem because I am not able to figure out what the problem is)?

```
$app->post('/login', function () use ($app) {
  try {
    $user = Sentinel::authenticate($userCredentials);
    if ($user == false) {
      $appResponseMessage = "Unauthorized";
      $app->response->setStatus(401);
      $appResponseJson = json_encode(array('message' => $appResponseMessage));
      $app->response->body($appResponseJson);
    } 
    else {
      $loggedIn = Sentinel::login($user);
      $role=$user["roles"][0]["slug"];      
      $userId=$user["id"];
      if ($role == "roleA") {
        //Do something here[1]
        $appResponseMessage['message'] = "loggedIn";
        $appResponseMessage['role'] = $role;
      } 
      else {
        // Do something here [2]
        $appResponseMessage['message'] = "loggedIn";
        $appResponseMessage['role'] = $role;
      }
      $appResponseJson = json_encode($appResponseMessage);
      $app->response->body($appResponseJson);
    }
  }
  catch(Exception $e) {
    $appResponseJson = json_encode(array('message' => $e->getMessage()));
    $app->response->body($appResponseJson);
  }
});
```

Thanks!

EDIT: 
I tried doing this around [2]

```
print_r($appResponseMessage); //or anything just to check if this code was being executed and found out that it was.
```

Does this indicates that there might be an issue with $app->response->body() method?
Again I am not sure.

**Comment by geggleto** [comment]
Your user is false. this results in nothing being displayed.

**Comment by shashvattrip** [comment]
Nope, this is the code when the user is false. I had omitted the code for brevity. To be clear, this code replaces comment with [0]

```
$appResponseMessage = "Unauthorized";
$app->response->setStatus(401);
$appResponseJson = json_encode(array('message' => $appResponseMessage));
 $app->response->body($appResponseJson);
```

So that is not the problem. The user is true and this code executes for sure.

```
        // Do something here [2]
        $appResponseMessage['message'] = "loggedIn";
        $appResponseMessage['role'] = $role;
```

**Comment by sankalpsans** [comment]
Have a look at your `else` block. You're trying to assign a value to `$appResponseMessage['some_index']` assuming that `$appResponseMessage` is an array, which it is not (yet). So, try this:

```
$app->post('/login', function () use ($app) {
  try {
    $user = Sentinel::authenticate($userCredentials);
    if ($user == false) {
      $appResponseMessage = "Unauthorized";
      $app->response->setStatus(401);
      $appResponseJson = json_encode(array('message' => $appResponseMessage));
      $app->response->body($appResponseJson);
    } 
    else {
      $loggedIn = Sentinel::login($user);
      $role=$user["roles"][0]["slug"];      
      $userId=$user["id"];
      $appResponseMessage = array();
      if ($role == "roleA") {
        //Do something here[1]
        $appResponseMessage['message'] = "loggedIn";
        $appResponseMessage['role'] = $role;
      } 
      else {
        // Do something here [2]
        $appResponseMessage['message'] = "loggedIn";
        $appResponseMessage['role'] = $role;
      }
      $appResponseJson = json_encode($appResponseMessage);
      $app->response->body($appResponseJson);
    }
  }
  catch(Exception $e) {
    $appResponseJson = json_encode(array('message' => $e->getMessage()));
    $app->response->body($appResponseJson);
  }
});
```

I've just initialized that array as `$appResponseMessage = array();`

**Comment by shashvattrip** [comment]
No the problem wasn't in PHP code. It was a weird problem in phpmyadmin. I was copy-pasting some value in a column(VARCHAR 255) through phpmyadmin which as being queried in the PHP code. When I remove that row with copy-pasted value, and typed it manually, the select query started to work and php code ran fine.

Which leads me to believe that there is an issue with the text I was pasting. However, I was simply copying about 150 characters with no special characters apart from punctuation. I still don't know what's wrong and as I am on a deadline, I decided to just type out the text.

**Comment by sankalpsans** [comment]
In that case, it is possible you made a syntactical error. Maybe a single / double quote here and there. Enable error logging to be verbose and read through them.

**Comment by shashvattrip** [comment]
That's the thing. Error logging was enabled. Even then it failed silently.

**Comment by sankalpsans** [comment]
Could you paste your code snippet with the exact characters that cause it to fail?

**Comment by geggleto** [comment]
tip of the day, dont use php my admin... use something like sqlyog or mysql workbench when dealing with mysql related stuff.

**Comment by tuupola** [comment]
It is actually possible to do the same thing with a text editor, TextMate in my case. I had couple of times a case where PHP would just silently die. Debugged it by removing code line by line. Found the line, didn't see anything wrong with it. Pasted it back and PHP dies. Removed it and typed everything again, PHP works.

With hex editor I could see there was an invisible control character in the end of the line. Sadly I do not remember what it is but it was possible to accidentaly write it using some key combination. It probably was something close to cmd-s which TextMate uses for saving.

**Comment by shashvattrip** [comment]
Yup, lesson learnt on special characters.
