### ISSUE TITLE
Enable X-HttpMethod-Override via GET

### ISSUE THREAD

**Issue by tthiery** [slimphp/Slim#1562]
I am facing an environment where i do cross server calls with ajax ... and I fail to do calls with HTTP verbs beyond GET and POST. I cannot set a header (browser restriction w/o options preflight) and my POST body is not form data (so _METHOD is not possible) but JSON. As a consequence I wrote a middleware to do a verb override with a GET parameter.

Is that an option for the framework? And should I create a PR for you?

**Comment by geggleto** [comment]
You can do this currently with Slim, no PR needed.

For PUT iirc:

```
$.post('/mypost', { _method: "PUT" }, function (success) {}); 
```

**Comment by tthiery** [comment]
I just tried sending as part of my JSON request a property with name _method. Is not recognized. Also the Slim Framework code - as far as I understand it - does not parse the JSON. The MethodOverride middleware reads the $req->post() methods ... which again reads the _POST in case of content-type other than form data (I have not debugged, just read the code here). Maybe I missed a line (i send here text/plain instead json content-type ... but i have not seen this affecting it).

POST /blaba
Accept:_/_
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,de-DE;q=0.6,de;q=0.4
Connection:keep-alive
Content-Length:100
Content-Type:text/plain
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

{
   foo: "bar",
   _method: "DELETE"
}

**Comment by Lewiscowles1986** [comment]
buddy @geggleto code was for the browser JS, using X-Form-Encoded, so you'll need to send your JSON body inside another object

``` javascript
function send_data(data, url, method, success, error) {
    method = (method || 'GET').toUpperCase();
    success = success || function(data){ console.log('Success:',data) };
    error = error || function(err){ console.log('Error:',err) };
    jQuery.post( url, { "_method" : method, "json_data" : JSON.stringify(data) }, success ).error(error); 
}
```

**usage**

``` javascript
send_data({'some':'json'},'/wherever','PUT');
```

then in your app when you want to use your json data simply json_decode it (perhaps do this in a middleware so it is throughout your app?

What I don't understand is why your HTTP frontend needs to use PUT; API's generally don' connect directly to web-browsers

**Comment by geggleto** [comment]
I guessed he had been doing something in Angular.

**Comment by Lewiscowles1986** [comment]
surely in angular 

``` javascript
$http.put(url, json_data).
  then(
    function(response) {
      //success
    },
    function(response) {
      //failure
    }
);
```

**Comment by tthiery** [comment]
Slim is a general purpose api framework. It features method overrides for form posts and headers. It does not support query string based overrides, which is a pity. I do not change my api design and cripple the data model because of a technology choice (especially since I already have this feature implemented as a slim middleware). I think the slim maintainer should decide yes or no for the feature request. Discussing which client framework is used (does not matter BTW its plain jquery) does not help. 
Further using put and delete is a recommended best practice ... Also for client side webs, spa and apps.

**Comment by geggleto** [comment]
a middleware would be perfect for this. this is outside the psr7 spec but i
get taht some people might want it which fits well with middleware in
general. i would love to see a middleware library that is psr7 compliant
that does request modification.

**Comment by akrabat** [comment]
These sort of requirements are exactly the province of middleware. At some point we should have a directory of middleware.

**Comment by silentworks** [comment]
I am working on a directory for middleware. I should put it on Github so you can keep track of its progress.

**Comment by Lewiscowles1986** [comment]
:+1: so closed, or is the dir of middleware going to be added to Slim?

**Comment by geggleto** [comment]
I will cook up a middleware to solve this problem.

**Comment by geggleto** [comment]
Here we are :)

https://github.com/geggleto/method-override

**Comment by geggleto** [comment]
https://packagist.org/packages/geggleto/method-override

`composer require geggleto/method-override`

**Comment by tthiery** [comment]
@geggleto btw: Thanks for the Middleware. have not upgraded yet to Slim with PSR-7 Middlewares .. but it is on the list ;).
