### ISSUE TITLE
Write migration guide to 3.0

### ISSUE THREAD

**Issue by clicman** [slimphp/Slim#1565]
As Slim 3.0 becomes RC I thing it will good to have migration from "Slim 2 guide" article.
I`ve tried to run my slim 2 api roject in 3.0 and its fails to run.
Possible scope:
1. Basic initialization.
2. Middleware migration.
3. View migration
...

**Comment by akrabat** [comment]
We have http://www.slimframework.com/docs/start/upgrade.html so far and would love contributions to it at https://github.com/slimphp/Slim-Website

**Comment by juliangut** [comment]
The other day I answer a question on how to implement custom Exceptions in routes and how to automatically handle them. I feel this is something that should go on the migration guide, or at least on the docs

**Comment by geggleto** [comment]
Well Given that in Slim 2 you nearly can't use exceptions at all, we can likely add that in there somewhere.

**Comment by akrabat** [comment]
Please just raise PRs against Slim-Website :)
