### ISSUE TITLE
get request parameter names 

### ISSUE THREAD

**Issue by EmadAdly** [slimphp/Slim#1566]
I'm trying to get request parameter names and values dynamically,and in the same
i have other static route

Here is an example:

`name.com/username`

```
$app->get('/:username', function($username) use ($app){

})->name('profile'); 
```

and static route
`name.com/setting`

```
$app->get('/settings',  function() use($app){

})->name('profile');
```

any idea for work this ,thank you

**Comment by tuupola** [comment]
In your code put route for `/settings` first. Then both `/settings` and `/foobar` should work. Also you probably should not use same `->name('profile')` for both routes.

**Comment by EmadAdly** [comment]
thanks you tuupola 
Just that only ,ha ha ha I try a hour ago to make them work through the filter or Middleware
profile here by mistake 
thanks
