### ISSUE TITLE
Potentially insecure use of client-set headers?

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#1567]
`Slim\Http\Uri` uses the headers `HTTP_X_FORWARDED_PROTO` & `HTTP_X_FORWARDED_HOST` in [createFromEnvironment()](https://github.com/slimphp/Slim/blob/8bd1002bb69fc1a0c354e72c3195bc56d7dd22c1/Slim/Http/Uri.php#L161-L179).

Should these be removed?

**Comment by akrabat** [comment]
Note that Dicatoros also uses `X-Forwarded-Proto` here: https://github.com/zendframework/zend-diactoros/blob/master/src/ServerRequestFactory.php#L237-L243

**Comment by akrabat** [comment]
Another thought. Is this a web server config issue? Apache has `mod_remoteip` and nginx has `ngx_http_realip_module` - both of which allow you to whitelist which IPs are able to sent replacement addresses.

**Comment by akrabat** [comment]
If we remove them, then https://github.com/akrabat/rka-scheme-and-host-detection-middleware would work as a middleware replacement.

**Comment by akrabat** [comment]
Really need discussion on this as to whether it's secure to leave them in place or not.

**Comment by piotr-cz** [comment]
IMHO this is a security issue, described in details [here](https://github.com/joomla/joomla-framework/pull/212).

I see two ways around it:
- Manually set if connection is secure (using environment variables).
- Add an option to set if headers are trusted (as seen in [Symfony2/HttpFoundation/Request](https://github.com/symfony/http-foundation/blob/2.8/Request.php#L1185))

Developer is able to find out whether server is using proxy, and so may set environment variable in .htaccess file nginx config, redirect to https or decide to enable trusted headers.

**Comment by silentworks** [comment]
We have decided to remove these and opt for a middleware instead.
