### ISSUE TITLE
Slim\Http\Uri's getQueryParams() is missing

### ISSUE THREAD

**Issue by carlosneves0** [slimphp/Slim#1568]

**Comment by akrabat** [comment]
`getQueryParams()` is a method on [`Request`](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L710) as it's part of PSR-7's [`ServerRequestInterface`](https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php#L99).

**Comment by carlosneves0** [comment]
Hmm. Thanks. The documentation under Request -> The Request URI misled me.

> You can fetch the PSR 7 Request object’s URI with its getUri() method:
> 
> $uri = $request->getUri();
> The PSR 7 Request object’s URI is itself an object that provides the following methods to inspect the HTTP request’s URL parts:
> 
> getScheme()
> getHost()
> getPort()
> getPath()
> getBasePath()
> getQuery() (returns string)
> getQueryParams() (returns associative array)

**Comment by losttheplot** [comment]
Given the URI https://www.whatever.co.uk/api/getEvents/&foo=red&bar=green, neither $request->getQueryParams() nor $request->getUri()->getQuery() return any values. Am I doing something wrong please, or is this a bug? What is the correct way to extract the values for foo and bar from the URI please?

**Comment by tuupola** [comment]
https://www.whatever.co.uk/api/getEvents/?foo=red&bar=green

**Comment by losttheplot** [comment]
Thanks. I tried that first off but got a Page Not Found. However, having now changed $app->get('/getEvents/{args]', function ($request, $response, $args) { to $app->get('/getEvents/', function ($request, $response, $args) { it works fine. Sorry, I'm brand new to Slim3 and just needed a nudge in the right direction :)

**Comment by tuupola** [comment]
It is not directly Slim related. 

RFC 3986 governs how [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) should be built. The `?` character denotes start of query string. Query string itself is usually `key=value` pairs separated by either `&` or `;` character.

It looks like you want to use query string for search, but ended up doing something else.

**Comment by losttheplot** [comment]
I'm new to OOP, APIs and routes but not to how URIs normally work. As I was getting a Page Not Found using '?' I thought that Slim might work differently to what I expected. Needless to say, I now feel like a total noob, which I am not. Time for a beer me thinks - thanks ;)
