### ISSUE TITLE
Router not working properly on subdir

### ISSUE THREAD

**Issue by vikkio88** [slimphp/Slim#1569]
Hi all, I discovery this framework yday and I loved it. I have a small problem though, locally on my apache server everything was working fine, on the shared hosting though I have a problem on routing, basically all the first level routes works like a charm:

```
GET blabla.com/subdir/api/items
GET blabla.com/subdir/api/ping
GET blabla.com/subdir/api/blabla
```

the problem appear once I try to access to more complex routes

```
GET blabla.com/subdir/api/items/2/blabla
```

I think it must be something related to the .htaccess, which, again locally was working.

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

i put this in the same dir as the index.php file so /www/subdir/api

Is that a problem of my hosting or someone else had this problem before? I was searching around either in the issues here and in the forum but I could not find anything related.

Thank you in advance

**Comment by tuupola** [comment]
How does your code look like?

**Comment by vikkio88** [comment]
I am terribly sorry, I just realize that I was missing some files and so was not a route problem. thank you the same, and apologize
