### ISSUE TITLE
Uri::createFromEnvironment resolutions when using Server rewrites

### ISSUE THREAD

**Issue by piotr-cz** [slimphp/Slim#1571]
Let's assume that the document root is set to `./`, public folder resides in `./public` (just like in [slim3-skeleton](https://github.com/akrabat/slim3-skeleton) app) and the `.htaccess` in the **document root redirects all requests to public folder** using [L] flag:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule .* public/$0 [L,QSA,E=PATH_INFO:/$0,E=PUBLIC_DIR:public]
</IfModule>
```

In this scenario base path resolution in `Uri::createFromEnvironment` doesn't work properly: real base path value instead of being stored in `$basePath` variable is stored in the `$virtualPath`.

I admit that this is very sketchy example and I use it only during local development when I'm too lazy to setup separate virutal host for each project.

The point is that using `$_SERVER['SCRIPT_NAME']` and `$_SERVER['REQUEST_URI']` for `$basePath` and `$virtualPath` resolutions will fail when using complex server rewrites.

One solution may be to provide public folder path as an environment variable (as I've done in the example), but more bullet-proof solution I'd like to see is that the method would respect project uri set manually in the container settings.

This could help solving another issue: the connection could be set manually as being secure or not as this is not trivial to autodetect when behind load balancer.

**Comment by geggleto** [comment]
You should be setting your webroot to the public folder, not using an .htaccess to redirect queries.

**Comment by ppetermann** [comment]
+1 on geggleto. public is called public, because it should contain all files exposed to public, as its the projects document root.

**Comment by piotr-cz** [comment]
I know. The point is how the base path resolution works now.

Image I'm using (invisible) server redirect to redirect `http://foo.org/oldsite` to `http://foo.org/newsite` on the server. The resolution mechanism assumes that [request uri overlays physical path](https://github.com/slimphp/Slim/blob/3.0.0-RC1/Slim/Http/Uri.php#L194-L204) which is not correct.

So the user will see `http://foo.org/oldsite` in browser, `$basePath` will be set to `''` and `$virtualPath` to `newsite`

**Comment by akrabat** [comment]
Arguably, one solution is to add middleware that does:

``` php
$request = $request->withBasePath('/newsite')->withPath('');
```

**Comment by piotr-cz** [comment]
@akrabat Yes, but if I'd like to use any routes in application I'd have to resolve the `$virtualPath` in middleware.

**Comment by akrabat** [comment]
I don't understand. That line would work the same way as using a config setting.

**Comment by piotr-cz** [comment]
Yes for no routes, but not for `http://foo.org/oldsite/about`

**Comment by akrabat** [comment]
Hmm... the point of setting it into `BasePath` was so that routes would work. I'll have to test it now!

**Comment by akrabat** [comment]
I have no idea what to actually do with this issue. What specific change do you propose should be made?

**Comment by geggleto** [comment]
This is such a huge edge case, I am for not doing anything.

**Comment by codeguy** [comment]
I would ignore this one.

**Comment by piotr-cz** [comment]
@akrabat 
I'd like to see is that the method would respect project uri set manually in the container settings.

But I don't mind closing the issue ATM either

**Comment by akrabat** [comment]
How about PR'ing what you imagine?

**Comment by piotr-cz** [comment]
I'll prepare PR, but it may take some time until I get some time

**Comment by geggleto** [comment]
Quite old, closing :)
