### ISSUE TITLE
Add clickjacking protection middleware (optional)

### ISSUE THREAD

**Issue by mikicaivosevic** [slimphp/Slim#1572]
Maybe we can add [clickjacking](https://www.owasp.org/index.php/Clickjacking) protection [middleware](https://github.com/mikicaivosevic/clickjacking-middleware) that sets the X-Frame-Options HTTP header in HTTP responses ?

**Comment by geggleto** [comment]
you can do this as an application developer via your own middleware!

**Comment by mikicaivosevic** [comment]
Yea, ofcourse. 
I just wanted to suggest to add clickjacking protection middleware in "Add Ons", the same as CSRF protection middleware.

**Comment by piotr-cz** [comment]
Using frames is an unseen practice these days unless you are developing a Facebook app.
