### ISSUE TITLE
Loosing Slim\App & Di\Container in callback context (Action)

### ISSUE THREAD

**Issue by orykami** [slimphp/Slim#1575]
Hi everyone,

I'm a beginner on Slim Framework, which is really great so far :-)
Did someone else loosing capability to use Slim\App or Di\Container in Models/Action(s) ?

Why Strategies don't inject Di into callbacks ? like :

``` php
public function __invoke(
  callable $callable,
  Di\Container $container,
  ServerRequestInterface $request,
  ResponseInterface $response,
  array $routeArguments
) {
    // [...] 
    return call_user_func($callable, $container, $request, $response, $routeArguments);
    }
```

**Comment by geggleto** [comment]
An Action could look like this...

```
class MyAction {
    public __construct( ... my DI stuff )  { }

    public function __invoke($request, $response, $args)  { 
        return $response;
    }
}
```

**Comment by orykami** [comment]
@geggleto Well, it's Slim\CallableResolver which construct our Callable via Strategies with ($request, $response, $args). So __construct() with no arguments right ?

**Comment by akrabat** [comment]
@orykami Actually, CallableResolver will pass the container into the construct when it creates it: https://github.com/slimphp/Slim/blob/3.x/Slim/CallableResolver.php#L64

The strategy will determine which arguments to pass to the `$method` when it is dispatched.

**Comment by piotr-cz** [comment]
Note that this is not available in 3.0.0-RC1.

**Comment by orykami** [comment]
@akrabat I'm on 3.0.0-RC1, that's why i mentionned it.

**Comment by silentworks** [comment]
@orykami this will be in RC2 which will be out over the weekend or next week, just need to finalise some bits with @akrabat.
