### ISSUE TITLE
Redirect in slim3

### ISSUE THREAD

**Issue by piernik** [slimphp/Slim#1579]
How to redirect to different route in slim 3?

**Comment by akrabat** [comment]
``` php
return $response->withRedirect('/foo');
```

or:

``` php
// inside route callable closure:
$router = $this->router;
return $response->withRedirect($router->pathFor('route-name');
```

**Comment by piernik** [comment]
Oh with `return` - thanks

**Comment by TimoDJatomika** [comment]
I don't have the  'withRedirect' function:
I get the following error:
 `Fatal error: Call to undefined method Slim\Http\Response::wihRedirect()`

What did I wrong

**Comment by JoeBengalen** [comment]
Typo. Wit or with

**Comment by TimoDJatomika** [comment]
oh sorry my bad
Now it works :+1:

**Comment by niranjanwnmt** [comment]
Hi,
//in controller
`return $response->withRedirect('/checkParams');`
this is not working in controller.
//route
`$app->post(
    '/checkParams',
    'ValidatorController:checkParams'
);`

is there anything more to be done while using in controller?

**Comment by akrabat** [comment]
A redirect is always a GET request. You have made `/checkParams` a POST, so it won't match.

**Comment by niranjanwnmt** [comment]
@akrabat Wow that was lightning fast response. Thanks for super quick response. I will change my route to GET.

**Comment by niranjanwnmt** [comment]
@akrabat 
I got it working as expected when I turned POST to GET. Now what I am finding challenging is allow cross domain request. Let me explain my scenario in brief.
1. my web app domain say http://mywebapp.com will call my API end point at http://myapi.com/process/
2. the internal working of the ProcessController API will be as follows
  a. process method will do some work and will redirect to other controller method ValidatorController:checkParams
  b. ValidatorController:checkParams will check parameters and will redirect to another controller say ExecutorController:executeprocess.

Now if request to API call is from same origin then it works like charm. Complete redirections work as expected and I get final result.
But in case of cross domain call, My ProcessController method gets called but it halts execution where I redirected it to ValidatorController:checkParams with no error or warning.

Following changes I have made.
in index.php of API codebase

`  if (isset($_SERVER['HTTP_ORIGIN'])) {
    header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
    header('Access-Control-Allow-Credentials: true');
    header('Access-Control-Max-Age: 86400');    // cache for 1 day
}
  // Access-Control headers are received during OPTIONS requests
  if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD'])) {
        header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");
    }
if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS'])) {
        header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");
    }
}
`

my redirection code in ProcessController which should redirect to ValidatorController:checkParams
`$qryParams = http_build_query(['requestlogID'=>$result]);
                $uri = $request->getUri()->withQuery($qryParams)->withPath($this->_router->pathFor('checkParams'));
                return $response->withStatus(200)
                        ->withHeader("Access-Control-Allow-Origin", $_SERVER['HTTP_ORIGIN'])
                        ->withHeader("Access-Control-Allow-Credentials", true)
                        ->withHeader("Access-Control-Max-Age", 86400)
                        ->withHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
                        ->withHeader("Location", $uri);`

can you please guide what am I doing wrong?
Thanks

**Comment by mathmarques** [comment]
@niranjanwnmt 
Read this: [Setting up CORS](https://www.slimframework.com/docs/cookbook/enable-cors.html)

**Comment by bbmattieu9** [comment]
how can i understand how slim3 works with relationships....any well explained article anyone??

**Comment by bbmattieu9** [comment]
Redirecting not working...Someone please help debug
HomeController has---> 
$app->get('/', 'HomeController:index')->setName('home');
AuthController has --->
return $response->withRedirect($this->router->pathFor('home'));

Not working...keeps redirecting back to auth/signup instead of index page

**Comment by akrabat** [comment]
@bbmattieu9  please provide code in a single `index.php` file along with `curl` examples that show that it doesn't work.

**Comment by bbmattieu9** [comment]
@akrabat thanks....

my index page has:

<?php

require __DIR__ . '/../bootstrap/app.php';

$app->run();
-----------------------------------------------------------------------------------------------------

ROUTES FILE has:

 <?php

$app->get('/', 'HomeController:index')->setName('home');

$app->get('/auth/signup', 'AuthController:getSignUp')->setName('auth.signup');
$app->post('/auth/signup', 'AuthController:postSignUp');

--------------------------------------------------------------------------------------------------------

HomController has this:
<?php


namespace App\Controllers;

use \Slim\Views\Twig as View;


class HomeController extends Controller{



  public function index($request, $response)
  {

      return $this->view->render($response, 'home.twig');
  }

}

---------------------------------------------------------------------------------------------------------------

AuthController has:

<?php

namespace App\Controllers\Auth;

use App\Models\User;

use App\Controllers\Controller;




class AuthController extends Controller
{

    public function getSignUp($request, $response)
    {
        return $this->view->render($response, 'auth/signup.twig');
    }

    public function postSignUp($request, $response)
    {
         $user = User::create
         ([
             'name' => $request->getParam('name'),
             'email' => $request->getParam('email'),
             'password' => password_hash($request->getParam('password'), PASSWORD_DEFAULT),
       ]);

      return $response->withRedirect($this->router->pathFor('home'));
    }
}
-----------------------------------------------------------------------------------------------

app.php...bootstrap file has:

<?php

session_start();

//require the vendor autoloader directory/file
 require __DIR__ . '/../vendor/autoload.php';



 $app = new \Slim\App([

    'settings' => [
        'displayErrorDetails' => true,
        'db'=>[
          'driver'=> 'mysql',
          'host'=> 'localhost',
          'database' => 'dbName',
          'username'=> 'root',
          'password'=> '',
          //'port' => 8889,
          'charset'=> 'utf8',
          'collation'=> 'utf8_unicode_ci',
          'prefix'=> '',
        ]
    ],
 ]);

 $container = $app->getContainer();

//Add and configure Eloquent
 $capsule = new \Illuminate\Database\Capsule\Manager;
 $capsule->addConnection($container['settings']['db']);
 $capsule->setAsGlobal();
 $capsule->bootEloquent();

 $container['db'] = function ($container) use ($capsule){
    return $capsule;
 };

 $container['view'] = function($container){
      $view = new \Slim\Views\Twig(__DIR__ . '/../resources/views',[

          'cache' => false,
      ]);

      $view->addExtension(new \Slim\Views\TwigExtension(
          $container->router,
          $container->request->getUri()
      ));
      return $view;
 };

 $container['HomeController']= function($container){

      return new \App\Controllers\HomeController($container);

 };

 $container['AuthController']= function($container)
 {

      return new \App\Controllers\Auth\AuthController($container);

 };


 require __DIR__ . '/../app/routes.php';
-----------------------------------------------------------------------------------------------------


i HOPE THIS INFORMATION IS ENOUGH TO HELP ME FIND WHERE I WENT WRONG. 

When i sign up, it submits the data into the db but fails to reDirect to the index page. Instead it goes back to auth/signup but doesn't show the form, Just a blank page.

Thanks in advance.

**Comment by bbmattieu9** [comment]
`<?php


session_start();

//require the vendor autoloader directory/file
require __DIR__ . '/../vendor/autoload.php';



$app = new \Slim\App([

'settings' => [
   'displayErrorDetails' => true,
   'db'=>[
     'driver'=> 'mysql',
     'host'=> 'localhost',
     'database' => 'dbNameHere',
     'username'=> 'root',
     'password'=> '',
     'charset'=> 'utf8',
     'collation'=> 'utf8_unicode_ci',
     'prefix'=> '',
   ]
],
]);

$container = $app->getContainer();

//Add and configure Eloquent
$capsule = new \Illuminate\Database\Capsule\Manager;
$capsule->addConnection($container['settings']['db']);
$capsule->setAsGlobal();
$capsule->bootEloquent();

$container['db'] = function ($container) use ($capsule){
return $capsule;
};

$container['view'] = function($container){
 $view = new \Slim\Views\Twig(__DIR__ . '/../resources/views',[

     'cache' => false,
 ]);

 $view->addExtension(new \Slim\Views\TwigExtension(
     $container->router,
     $container->request->getUri()
 ));
 return $view;
};

$container['HomeController']= function($container){

 return new \App\Controllers\HomeController($container);

};

$container['AuthController']= function($container)
{

 return new \App\Controllers\Auth\AuthController($container);

};


require __DIR__ . '/../app/routes.php';
//  End of app.php File


//==========================================================================================

//index.php file
require __DIR__ . '/../bootstrap/app.php';

$app->run();
//  End of index.php File



//==========================================================================================
//AuthController.php file


namespace App\Controllers\Auth;

use App\Models\User;

use App\Controllers\Controller;




class AuthController extends Controller
{

    public function getSignUp($request, $response)
    {
        return $this->view->render($response, 'auth/signup.twig');
    }

    public function postSignUp($request, $response)
    {
         $user = User::create
         ([
             'name' => $request->getParam('name'),
             'email' => $request->getParam('email'),
             'password' => password_hash($request->getParam('password'), PASSWORD_DEFAULT),
       ]);

      return $response->withRedirect($this->router->pathFor('home'));
    }
}
//  End of AuthController.php File


//==========================================================================================
//routes.php file


$app->get('/', 'HomeController:index')->setName('home');

$app->get('/auth/signup', 'AuthController:getSignUp')->setName('auth.signup');
$app->post('/auth/signup', 'AuthController:postSignUp');
//  End of routes.php File



//==========================================================================================
//HomeController.php file


namespace App\Controllers;

use \Slim\Views\Twig as View;


class HomeController extends Controller{



  public function index($request, $response)
  {

      return $this->view->render($response, 'home.twig');
  }

}//  End of routes.php File


//==========================================================================================
//Controller.php file

namespace App\Controllers;

class Controller{

  protected $container;

  public function __construct($container)
  {
      $this->container = $container;
  }

  public function __get($property)
  {
       if($this->container->{$property}){
         return $this->container->{$property};
       }
  }
}//  End of routes.php File


 ?>
`

**Comment by bbmattieu9** [comment]
[index.php.zip](https://github.com/slimphp/Slim/files/1663587/index.php.zip)


Attached here-with is an index file containing my source code. i hope this will help you debug the code. thanks in advance

**Comment by bbmattieu9** [comment]
@akrabat Attached here-with is an index file containing my source code. i hope this will help you debug the code. thanks in advance
[index.php.zip](https://github.com/slimphp/Slim/files/1663592/index.php.zip)
