### ISSUE TITLE
HTTP Basic Authentication

### ISSUE THREAD

**Issue by lucianboldu** [slimphp/Slim#158]
Is there a better way to handle basic realm authentication from Slim ?
I create a hook who is apply to any route before anything else is executing.
My example is below:

include 'Slim/Slimp.php';
$app = new Slim ( array ('session.handler' => null) );

//verification hook
$app->hook ( 'verification', function () use($app) {
    $app->contentType ( HEADER_RESPONSE_JSON );

```
//authentication part
 if(!isset($_SERVER ['PHP_AUTH_USER'])){
    $app->response ()->header ( 'WWW-Authenticate', 'Basic realm="domain API"' );
    $app->halt(401,'USER_NOT_AUTHENTICATED');
}else{
    echo "<p>Hello {$_SERVER['PHP_AUTH_USER']}.</p>";
    echo "<p>You entered {$_SERVER['PHP_AUTH_PW']} as your password.</p>";
}

     //more verification on the account specified in basic realm
```

});

$app->get ( '/', function () use($app) {
    $app->applyHook ( 'verification' );
        //more code here to satisfy the request if it's legit
});

<b>Is this a good way to implement http basic realm authentication with slim ?</b>

**Comment by codeguy** [comment]
I think Slim could provide better built-in support for HTTP authentication. I'll add this to the Road Map. For now, your approach seems reasonable.

**Comment by lucianboldu** [comment]
Thanks alot
Have a nice day

**Comment by codeguy** [comment]
Closing this out out since it is not an issue with the framework. Will add it to the Road Map shortly.
