### ISSUE TITLE
Slim3 map is case sensitive

### ISSUE THREAD

**Issue by piernik** [slimphp/Slim#1580]
Now map is case sensitive `$app->map(['GET', 'POST']` != `$app->map(['get', 'post']`
Maybe it could be insensitive?

**Comment by silentworks** [comment]
Chrome shows them all as uppercase in the Network view, most examples online show them as uppercase, I see no reason to make them case insensitive, just just an unnecessary overhead. 

If you need it be case insensitive extend App and add some code to deal with it.

**Comment by geggleto** [comment]
I think it should be case insensitive.

**Comment by akrabat** [comment]
According to the RFC, they are upper case. I don't mind if we `strtoupper` them though.

**Comment by piotr-cz** [comment]
I'd be for `strtoupper`ing methods. I usually use uppercase only for constants and consider it good practice.

**Comment by piernik** [comment]
If, according to RFC, they are always uppercase it could be case _insensitive_. It would be easier for developer.

**Comment by Lewiscowles1986** [comment]
> I'd be for strtouppering methods. I usually use uppercase only for constants and consider it good practice.

Of course strings are data, not code, so coding conventions should not affect the use of case in a string...

Slight other suggestion if the developer wants to use case-insensitive, I think @silentworks suggestion was 100% on-point

**Comment by silentworks** [comment]
Fixed.
