### ISSUE TITLE
Slim\Body getContents requires rewind before being read

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1584]
I was writing some test cases from php-view when I came across the tests failing because the output of
`$response->getBody()->getContents()` was a null string despite there being content inside the buffer.

Failing test segment

```
$newResponse = $renderer->render($response, "testTemplate.php", array("hello" => "Hi"));
//$newResponse->getBody()->rewind();
$this->assertEquals("Hi", $newResponse->getBody()->getContents());
```

Uncommenting the rewind fixes the test case failure.

I would expect that getContents() would:
1) Preserve the pointer in the body of the stream and
2) return the actual contents of the stream.

Thoughts?

**Comment by akrabat** [comment]
PSR-7's `SteamInterface::getContents()` [docblock](https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php#L137)  says:

>  Returns the remaining contents in a string

That doesn't imply that it should do a rewind to me.
