### ISSUE TITLE
Unable to redirect from a 404 handler [Slim 3 RC 2]

### ISSUE THREAD

**Issue by artemgordinskiy** [slimphp/Slim#1586]
Hey guys,

I've been trying to do a redirect from inside a `notFoundHandler`, but never got it working.
Here is an approximation of my code:

``` php
$container = new \Slim\Container();
$container['notFoundHandler'] = function ($container) {
    return function ($request, $response) use ($container) {
        return $container['response']->withRedirect('/404.html');
    };
};

$app = new Slim\App($container);

// routes...

$app->run();
```

When I do a request to a non-existent route, all I get is a 200 response with an empty body.
Am I missing something here?

**Comment by geggleto** [comment]
This  is what I use. This is not fully PSR-7 compliant because I use the getBasePath() Slim internal method on the URI object.

```
    'notFoundHandler' => function ($container) {
        return function (\Slim\Http\Request $request, \Slim\Http\Response $response) {
            return $response->withStatus(301)->withHeader("Location", $request->getUri()->getBasePath() . "/404");
        };
    }
```

**Comment by artemgordinskiy** [comment]
Thanks!
It's weird but it doesn't seem to be working for me:

```
HTTP/1.1 200 OK
Date: Fri, 13 Nov 2015 13:27:18 GMT
Server: Apache
X-Powered-By: PHP/5.6.10
Content-Type: text/html; charset=UTF-8
```

Are you using RC 2 too?

**Comment by geggleto** [comment]
Hmmm No, this was still on RC1 ... let me check rc2.

**Comment by geggleto** [comment]
The redirect works for me.

**Comment by geggleto** [comment]
The only time this wouldn't work as expected would be if the app is dumping white space to the browser.
Check the Content-Length of the HTTP response. Don't just rely on a "white" page. There is likely a space or carriage return causing the problem.

**Comment by artemgordinskiy** [comment]
Yep, a stray whitespace was the culprit. Thanks a lot for your help!
