### ISSUE TITLE
Slim 3 RC2 Uncaught Exception

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#1589]
Hello, I have a problem with the exception handler, exceptions are not automatically caught by Slim and I dont't understand why...

**Comment by geggleto** [comment]
In App:run .. There is a try-catch 
https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L324-L350 

If you are referring to there not being a Stack Trace in the output. In RC2 the stack trace has been disabled by default.
You can set this to true in your container config to get the stack trace.
https://github.com/slimphp/Slim/blob/3.x/Slim/Container.php#L59

**Comment by silentworks** [comment]
Info on turning error reporting back on.

http://www.slimframework.com/docs/handlers/error.html
