### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by lucianboldu** [slimphp/Slim#159]
It will ve very nice to have some JSON Schema implemented directly in Slim.
It will be very usefull for API validation content.

**Comment by codeguy** [comment]
1. How do you see JSON Schema being implemented in Slim? What benefit would it serve to the core framework?
2. Slim is a framework used to build APIs. Do you think JSON Schema is something that sould be in the core framework? Or is this something that you would use yourself in a specific Slim application? Not rhetorical. Interested in what you think.

**Comment by lucianboldu** [comment]
I'm using slim framework for my clients, and the biggest problem so far is the integrity of  JSON object content received by the server through POST,PULL.
 Just as DTD is used to validate the content of XML, I thought that JSON should do the same, because the JSON phenomenon has gained momentum in the web services community, and I think we need some kind of validation. Web services are consume by the most diverse users and besides these there are people who try to harm the service provider, and this validation would be a little wall built in front of them.

Not just web services would benefit from validation but the entire community that uses JSON.

In connection with the slim framework implementation of JSON schema, i think it's important in the future to consider this request. Not for me, but for the entire slim framework community.
So far you did a great job with the slim and I wish you all the best. 
I'm sorry for my english, but is not my primary language.
All the best.

**Comment by codeguy** [comment]
Closing this out because it's not an issue with the framework. But I will keep this in mind and may add it to the Road Map for a future release.
