### ISSUE TITLE
Issue with "index.php" appearing in Pretty Rewrite URLs

### ISSUE THREAD

**Issue by pokmot** [slimphp/Slim#1590]
This can of course be resolved with middleware, however as this has an effect on potentially all sites using URL rewrites I thought I would raise it now.

If, when using URL rewrite, you access the site by including the PHP file name in the url (e.g. index.php), getBasePath includes the file name in the result. When using this as a base href="" tag, all my static files are now being routed through the PHP file:

```
In HTML:
<base href="{{ BasePath }}">
<link rel="stylesheet" href="css/style.css"/>

Sample:
$uri = \Slim\Http\Uri::createFromEnvironment(
    \Slim\Http\Environment::mock(
        [
            'SCRIPT_NAME' => '/foo/index.php',
            'REQUEST_URI' => '/foo/index.php',
        ])
);
print $uri->getBasePath();

// Output: /foo/index.php
// Asset path becomes: /foo/index.php/css/style.css **not working**


$uri = \Slim\Http\Uri::createFromEnvironment(
    \Slim\Http\Environment::mock(
        [
            'SCRIPT_NAME' => '/foo/index.php',
            'REQUEST_URI' => '/foo/',
        ])
);
print $uri->getBasePath();

// Output: /foo
// Asset path becomes: /foo/css/style.css **works great**
```

The issue is the comparison made on line 197 of Uri.php - as the request uri and the script name is the same, getBasePath will return it including the script name.

I do understand this is desired behavior for those not using URL rewriting, however for those that do, this is an issue.

My main issue is that the behavior is inconsistent and depends whether it's loading a script directly or using URL rewriting. If it always included the script name I would simply use dirname(). If it never included it I could easily add index.php where needed.

With this scenario I need to do the same comparison as done on line 197 in Uri.php, and if they match I use dirname to get the path on its own,

Any thoughts on how this is best resolved? Middleware or Slim code change? Or use a redirect in .htaccess?

**Comment by pokmot** [comment]
I currently resolve this issue in the following way:

```
// Register Twig View helper
$container['view'] = function ($c) use ($app) {
  $view = new Twig(
      $app->settings['view']['template_path'], [
          'cache' => $app->settings['view']['twig']['cache'],
          'auto_reload' => $app->settings['view']['twig']['auto_reload'],
          'strict_variables' => $app->settings['view']['twig']['strict_variables'],
      ]
  );

  // We need to adjust the base URL a little when the script name is included
  $requestScriptName = parse_url($c['environment']->get('SCRIPT_NAME'), PHP_URL_PATH);
  $requestUri = parse_url($c['environment']->get('REQUEST_URI'), PHP_URL_PATH);
  $uri = $c['request']->getUri();
  if (stripos($requestUri, $requestScriptName) === 0) {
    $uri = $uri->withBasePath(dirname($uri->getBasePath()));
  }

  $view['BaseUrl'] = $uri->getBaseUrl() . '/';

  // Instantiate and add Slim specific extension
  $view->addExtension(new TwigExtension($c['router'], $uri));

  return $view;
};
```

**Comment by silentworks** [comment]
Is this by any chance related to #1571

**Comment by pokmot** [comment]
Although they might be related, I don't think they are exactly the same.

My issue here isn't regarding rewriting to a different folder, but rather the physical path matching the browser URL, causing /index.php to appear in getBaseUrl() in that specific scenario.

So:

http://localhost/ -> getBaseUrl = /
http://localhost/testurl -> getBaseUrl = /  (Addtional example)
http://localhost/index.php -> getBaseUrl = /index.php

and when using getBaseUrl to retrieve the path it will sometimes include the file name. The only way I can see around it is to carry out the same match as is done in Slim to remove the index.php part.

**Comment by akrabat** [comment]
I'm unclear what sort of fix you are imagining. Can you provide a code sample of the fix you think that would work?

**Comment by pokmot** [comment]
I can't see an easy code fix - it will either cause problems for those not using rewrites, or potential problems for those using them.

Providing a "getVirtualBaseUrl" method doesn't seem to be easy as the environment is not available to the method.

At the end of the day, I think it's easier for those using rewrites to resolve the issue, potentially through a redirect if the script is accessed directly, or using the method I described above, than to introduce this complexity into a great and elegant framework.

I am happy for the issue to be closed as it is relatively easy to fix in own code.

**Comment by pokmot** [comment]
@akrabat I just realised that the following produces an incorrect output:

```
$uri = \Slim\Http\Uri::createFromEnvironment(
    \Slim\Http\Environment::mock(
        [
            'SCRIPT_NAME' => '/foo/index.php',
            'REQUEST_URI' => '/foo/index.phpXYZ',
        ])
);
print $uri->getBasePath();

// Produces /foo/index.php - correct output should be /foo/    
```

The issue is the use of stripos on line 197 in Uri.php - as long as you include the file name of the currently executing script you can add anything you like - and the file is returned.

Presumably **strcasecmp** would be better than stripos? It can be substituted directly and it will work.

```
if (strcasecmp($requestUri, $requestScriptName) === 0) {
```

**Comment by akrabat** [comment]
Fixed.
