### ISSUE TITLE
DI Required services missing `CallableResolver`

### ISSUE THREAD

**Issue by michaelboke** [slimphp/Slim#1591]
Hi, i'm using the DI container from [league](http://container.thephpleague.com/) and not the builtin  provided by Slim 3 rc2.
I followed the [documentation](http://www.slimframework.com/docs/concepts/di.html) and added all the required services.

When i run the skeleton app i get a exception thrown by the container that the service **callableResolver** not being managed by the container. There is nothing in the documentation stating  that this service is required. 

I added the missing service and inject it with the container (league)

``` php
$container->share('callableResolver', \Slim\CallableResolver::class)
    ->withArgument($container);
```

I have found that the _Slim\CallableResolverAwareTrait_ method _resolveCallable_ is trying to get the callable resolver from the container. this trait is used by _Slim\App_.

Documentation at fault ? hidden dependency or am i missing something here.

**Comment by mathmarques** [comment]
callableResolver is a required service:
https://github.com/slimphp/Slim/blob/3.x/Slim/Container.php#L230

It was missing on doc

**Comment by silentworks** [comment]
Added to the docs thanks to @mathmarques

**Comment by michaelboke** [comment]
Thanks.
