### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by KevinWaterson** [slimphp/Slim#1601]
One of the biggest draw-cards of Slim, has always been that 'it just works out of the box'.
The removal of .htaccess prevents even the most basic of routing requests given in the index.php file.
This raises the bar for the level of entry into the Slim framework. 
Whilst old hands will work it out, those new to the framework only see that it is broken, without knowing why.

**Comment by geggleto** [comment]
:+1: PLEASE FOR ALL THE NOOBS, just so they can copy paste it somewhere else ;)

**Comment by silentworks** [comment]
Send a PR and will get this re-instated.

**Comment by ximex** [comment]
:+1:

**Comment by rivetchip** [comment]
Everything is _[indicated in the doc](http://www.slimframework.com/docs/start/web-servers.html)_ on how to use rewriting on different web-servers ;)

**Comment by tuupola** [comment]
I think it is more of documentation issue. Might be good idea to mention rewrite rules already in [installation](http://www.slimframework.com/docs/start/installation.html) page. That is the only page most people with problems read.

**Comment by KevinWaterson** [comment]
This is not a documentation issue. This is a deployment issue.
The application no longer works out-of-the-box.
Many who use Slim are new to API/PHP and have little to know idea of configuring htaccess or even that it exists.
Quite simply, when the application is first installed, it seems to be broken.

**Comment by piotr-cz** [comment]
This repository is a library (installed into `/vendor/slim/slim` folder), not a deployable application with a public folder.
While one don't have to use composer and can put everything into a public folder, it should be considered is a bad practice. I see no reasons to expose metadata files like composer.json, CONTRIBUTING.md to public access other than to show which architecture that was used to build an app.

But I think that the [slimphp organisation](https://github.com/slimphp) should have own Slim v3 skeleton app repository, similar to @akrabats [work](https://github.com/akrabat/slim3-skeleton), like it has for [Slim v2](https://github.com/slimphp/Slim-Skeleton)

**Comment by KevinWaterson** [comment]
If it is not a deployable application,  why is there an index.php?
Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Piotr notifications@github.com </div><div>Date:21/11/2015  12:19  (GMT+00:00) </div><div>To: slimphp/Slim Slim@noreply.github.com </div><div>Cc: Kevin Waterson kevin.waterson@gmail.com </div><div>Subject: Re: [Slim] .htaccess (#1601) </div><div>
</div>This repository is a library (installed into /vendor/slim/slim folder), not a deployable application with a public folder.
While one don't have to use composer and can put everything into a public folder, it should be considered is a bad practice. I see no reasons to expose metadata files like composer.json, CONTRIBUTING.md to public access other than to show which architecture that was used to build an app.

But I think that the slimphp organisation should have own Slim v3 skeleton app repository, similar to @akrabats work, like it has for Slim v2

**Comment by silentworks** [comment]
Fixed. You can now find this in a example directory.
