### ISSUE TITLE
Why are middleware and route callables bound different?

### ISSUE THREAD

**Issue by sirdiego** [slimphp/Slim#1602]
Hey,

why is the middleware callable bound to the container and the route callable to the app? I tried to figure out why there would be two different ways to get to the stuff, but I can't :confused: 

I think it would be great if I could use them both in the same way.

By the way, good job! I like Slim 3 already :smile_cat:

**Comment by geggleto** [comment]
@sirdiego it's mostly the same since the APP redirects stuff to the container anyway.

**Comment by sirdiego** [comment]
Hey @geggleto,

I know that it is _mostly_ the same, but it isn't exactly. On the container you can access the stored entries by $container->get('name') and $container['name']. For the application you have to use $this->name, because the get method is already used for the routes and the array access dies with this exception:

```
Fatal error: Cannot use object of type Slim\App as array
```

That's why I started thinking about the reasoning behind the different bindings.

[edit] Oh by the way, the container also has no magic __get implemented, so there is no $container->name possibility. So I have to be aware of the exact context I'm in to use the right way of getting to the entry.

```
Notice: Undefined property: Slim\Container::name
```

**Comment by akrabat** [comment]
My personal preference would be to always bind the container to the `$this`.

This would mean that if you wanted to use `subRequest` in a route callable, you'd have to `use ($app)`, though.

**Comment by codeguy** [comment]
+1 what @akrabat said.

**Comment by silentworks** [comment]
I agree with @akrabat and @codeguy

**Comment by akrabat** [comment]
Fixed. We now bind Container everywhere!

**Comment by sirdiego** [comment]
Awesome, thanks!
