### ISSUE TITLE
Request::getBasePath missing?

### ISSUE THREAD

**Issue by enygma** [slimphp/Slim#1608]
In the docs (http://www.slimframework.com/docs/objects/request.html#the-request-method) it mentions the `getBasePath` method as a way of getting the information from the request. Unfortunately this method doesn't seem to exist:

```
[Sat Nov 21 21:14:24.694714 2015] [:error] [pid 94524] [client 127.0.0.1:51578] PHP Fatal error:  Call to undefined method Slim\\Http\\Request::getBasePath() in [...].php on line 9
```

**Comment by akrabat** [comment]
`getBasePath` is on the URI object: `$basePath = $request->getUri()->getBasePath()`
