### ISSUE TITLE
Default Initialization of Middleware

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1609]
Instantiate middleware with the container as the first argument like controller classes

**Comment by piotr-cz** [comment]
Why middleware should have access to the container?

I usually register middlewares within container in the _app/dependencies.php_ file and pass just things it needs like so (in this case it's the debug and environment option):

``` php
$container->register(
    new App\Middleware\NativeErrorHandler(
        $container['settings']['app']
    )
);
```

and then in in _app/middleware.php_

``` php
$app->add('nativeErrorHandler:run');
```

If you pass whole container, there is no dependency graph - you have no idea what class is using at all unless you inspect it's code.

I know it's tiring to define dependencies for each container item, but it's only the case when not using DI that supports autowiring.

**Comment by akrabat** [comment]
Not everyone uses best practices. This issue provides a pragmatic solution for people who just want to get up and running... 

It will not prevent the preferred solution of registering the middleware class with the DIC.

**Comment by geggleto** [comment]
Furthermore it also follows 'Slim's conventions' given that if you don't initialize your classes in the container we will pass the container to your classes.

**Comment by piotr-cz** [comment]
Okay, this makes sense.
I see there are lot of questions on the support forum about accessing container data from within middleware, maybe a blogpost on Slim framework website could be helpful too.

**Comment by akrabat** [comment]
Testing shows that this is already in place as we use `resolveCallable` in `RouteGroup::add()` and in `Route::add()` already.
