### ISSUE TITLE
v3 get instance?

### ISSUE THREAD

**Issue by danielemontesi** [slimphp/Slim#1611]
in version 3 how can i get instace of application like v2 \Slim\Slim::getInstance() ?

**Comment by danopz** [comment]
``` php
$app->get('/foo', function ($request, $response, $args) {
    //$this is App
});
```

**Comment by bmutinda** [comment]
@danielemontesi  Got any solution for your issue?

**Comment by akrabat** [comment]
As @copynpaste has pointed out, `$this` within a route callback is the `App` instance. If you're using a class for your route callable, then register it with the DI container and inject what you need into the constructor:

``` php
$c = $app->getContainer();
$c['HelloController'] = function ($c) {
    $router = $c->get('router');
    return new HelloController($router);
};

$app->get('/hello', 'HelloController:helloAction');
```
