### ISSUE TITLE
Slim3: Unable to set unrecognised response codes

### ISSUE THREAD

**Issue by rbairwell** [slimphp/Slim#1613]
I have a need to set a "419 Authentication Timeout" (for exactly the same reasons as https://github.com/GetBlimp/django-rest-framework-jwt/issues/158 !) and whilst I agree that the status code is "non-standard", I do not believe Slim should block people from using any status codes they like (and, since PSR7 does not "dictate" which status codes are "correct", I believe Slim3 is going against the PSR7 by blocking unrecognised codes)...

By all means, keep the "lookup list" of Reason Phrases for when someone provides a status code without a reason phrase/message (but if there is an "unrecognised code" with no message, no message should be provided IMHO), but please do not filter (or allow us to modify the list).

Test case:

```
<?php
require __DIR__.'/vendor/autoload.php';
$app=new \Slim\App(['settings'=>['displayErrorDetails'=>true]]);
$app->get('/test',function ($request,$response,$arg) {
    $response = $response->withStatus(419,'Authentication Timed Out');
    return $response;
});
$app->run();
```

Expected output:
A HTTP Response with the header "HTTP/1.1 419 Authentication Timed Out"

Actual response:
500 error page

```
The application could not run because of the following error:
Details
Type: InvalidArgumentException
Message: Invalid HTTP status code
File:/vagrant/project/test/vendor/slim/slim/Slim/Http/Response.php Line: 203
```

**Comment by akrabat** [comment]
I would love a PR… :)

**Comment by akrabat** [comment]
Fixed.
