### ISSUE TITLE
PHPDocs

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1617]
Can we get the PHP docs put up somewhere? I can never remember the methods and properties available :(

**Comment by p3ym4n** [comment]
👍

**Comment by tw2113** [comment]
Recommendation after some talk in IRC.

http://www.apigen.org/

As easy as this command from a terminal in the root directory of a checkout:

```
apigen generate --source Slim --destination ../docs --template-theme bootstrap --title "Slim Framework"
```

Change the destination to wherever desired and commit afterwards.

**Comment by tw2113** [comment]
Example output:

![apigen](https://cloud.githubusercontent.com/assets/484075/11453976/3bc1ee44-95e4-11e5-8d5c-30420b07e9cd.png)

**Comment by geggleto** [comment]
@tw2113 oh I likey...

**Comment by akrabat** [comment]
Within Slim-Website, we need a script that creates the api docs and adds them to the Slim-Website repository. This way we can run it after we release a new version and update the website.

**Comment by tflight** [comment]
Automated way to [Generate API [docs] to Github pages via Travis](https://github.com/ApiGen/ApiGen/wiki/Generate-API-to-Github-pages-via-Travis)?

**Comment by designermonkey** [comment]
I have been revisiting this, and stumbled at the first hurdle, as apigen seems to not be installable via composer right now without package version issues.

**Comment by akrabat** [comment]
Thinking about this, the API docs need to be on the Slim-Website repository as we're going to need this for 3.x and 4.x.

Maybe this needs to be a bash/php script that is on Slim-Website that checks out the Slim repo, creates the api docs in the right place on the website and then deletes the Slim repo?

**Comment by designermonkey** [comment]
Good idea @akrabat

**Comment by designermonkey** [comment]
Posted too early...

~~I have a script that does this kind of thing as I used to do this for server deployments of client projects. I'll clean it up and post here if this is how it wants to be done?~~

I can't find it any more :(

**Comment by akrabat** [comment]
So close…

**Comment by ertogs** [comment]
Hi there, 
this can be automated with travis ci quite easy. 
also see https://github.com/slimphp/Slim-Website/pull/214
I will create a new PR with setup instructions in a few minutes.

**Comment by MarcHagen** [comment]
And what about just a simple webhook triggering the build?  
I'm used to have a deploy script that handles this stuff for me.

**Comment by akrabat** [comment]
See https://github.com/slimphp/Slim-Website/issues/213
