### ISSUE TITLE
Setting to toggle HTTP 1.1 and 1.0

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#162]
Specifically for PHPFog, but generally useful in edge cases. Enough users are using Slim with PHPFog that this edge-case is worth having.

**Comment by zeroecco** [comment]
Sweet!  Thanks!

-Rich, Support Engineer, PHP Fog

**Comment by codeguy** [comment]
This is now available in the `develop` branch. Use the application setting `http.version` and set it to a string value of "1.0" or "1.1". You can set this directly on the Response object, too, with `$response->httpVersion("1.0")`.

```
$app = new Slim(array('http.version' => '1.0'));
```

Enjoy!
