### ISSUE TITLE
Slim3: RouteInterface missing middleware relevant methods

### ISSUE THREAD

**Issue by rbairwell** [slimphp/Slim#1621]
Slim\App->map()'s docblock says it returns a RouteInterface (actual object returned is of class Slim\Route). However, though Slim\Route has the MiddlewareAwareTrait (and hence has the "addMiddleware" method) and also has the "add" method, neither of these are detailed in the RouteInterface meaning that IDE autocompletion does not suggest ->add() or ->addMiddleware() being valid calls after a ->map (or ->get, or ->post etc etc).

Is there a reason those calls aren't listed the RouteInterface?

**Comment by silentworks** [comment]
A PR has been accepted with that fix recently. #1618

**Comment by rbairwell** [comment]
Ah - thanks. Didn't see that. Cheers!

**Comment by silentworks** [comment]
@rbairwell thanks for testing, contributing PRs and providing feedback.
