### ISSUE TITLE
XXE attack in 3.x

### ISSUE THREAD

**Issue by phith0n** [slimphp/Slim#1623]
Just like https://github.com/slimphp/Slim/pull/610
XXE attack also affects slim framework 3.x, 
While my application accept post data, attacker can read arbitrary file or lead to other system impacts.
show a screen cupture of XXE attack result:
![](http://en.moepic.net/images/2015/11/28/QQ20151127-22x.png)
The vulnerability code:

```
$app->post("/info", function($request, $response) {
    $parsedBody = $request->getParsedBody();
    print_r($parsedBody);
});
```

**Comment by akrabat** [comment]
Fixed in #1624. Thank you very much for the report.
