### ISSUE TITLE
Improve Router class interface

### ISSUE THREAD

**Issue by maboiteaspam** [slimphp/Slim#163]
Hi !

I m feeling struggled with current urlFor and routes implementation.

Simply, i d like to have a more sofisticated urlFor method.

To achieve this, at this day, i have to `try{ urlFor() }catch{ urlForSoficticated() }`, it works, but it is tricky.

It would be nicer if there was a method like routeExists( name ), 
OR if route's names was exposed,
OR if there was a/many catchAll right before Exception is thrown.

My example usage is a catch all route wih an unique name, that is serving contents according to an external datasource.
Each content has a name.
So i can call urlFor with content's name, instead of route's name.
So i can keep my controlers DRY.

bye

**Comment by codeguy** [comment]
The `urlFor` method is meant to build a complete URL to a given route with an optional array of parameter values used to build the URL if the given route requires them.

If you need to use custom logic that checks for existing routes, I can definitely improve the Router/Route interface to accommodate that.

**Comment by maboiteaspam** [comment]
> > If you need to use custom logic that checks for existing routes, I can definitely improve the Router/Route interface to accommodate that.

yes, i think you resumed well my needs. Thanks !

bye

**Comment by codeguy** [comment]
This is done and available in the `develop` branch. New interface changes are:

```
addNamedRoute( string $name, Slim_Route $route ); //returns void
hasNamedRoute( string $name ); //returns bool
getNamedRoute( string $name ); //returns Slim_Route or NULL
getNamedRoutes(); //returns ArrayIterator for all named routes registered with given Slim_Router instance
```
