### ISSUE TITLE
Broken short routing variant $app->get('/route', 'Controller:method');

### ISSUE THREAD

**Issue by tssvl** [slimphp/Slim#1639]
I cannot say exactly which commit leads to this problem. I updated my project through composer (48be9d2) and saw that routes like:

``` php
$app->get('/', function () {
    ...
});
```

work well, but routes like:

``` php
$app->get('/route', 'Controller:method');
```

doesn't work.

**Comment by mathmarques** [comment]
Show the exception throwed

Just remember if the controller isn't on your Container, you must use the fully qualified class name. 
something like:

``` php
$app->get('/', '\App\Controller\YourController:method');
```

**Comment by tssvl** [comment]
Page not found 404.
 I suppose it means - no exceptions. In this particular case I didn't use namespaces. Fully qualified class name exactly `YourController:method`
I want to say that application worked well and after last update (using composer) I have problems and for now I can't continue developing my app.

**Comment by tssvl** [comment]
Sorry guys. I mistaken. Just tested my case on pure `slim/slim (3.0.0-RC3)` installation. 
Routing doesn't work at all. 
Works only `$app->get('/'` pattern.
For example: `$app->get('/test'` gives Page Not Found.

My code:

``` php
<?php

require __DIR__ . '/src/vendor/autoload.php';

$app = new \Slim\App;

$app->get('/', function ($request, $response, $args) {
    return $response->write("It works... only");
});

$app->get('/test', function ($request, $response, $args) {
    return $response->write("It doesn't works...");
});

$app->get('/hello/{name}', function ($request, $response, $args) {
    return $response->write("Hello " . $args['name']); //doesn't works too
});

$app->run();
```

**Comment by tuupola** [comment]
You do have rewrite rules in `.htaccess` file?

**Comment by akrabat** [comment]
Your code works for me in a clean project using the built-in PHP web server (PHP -S).

**Comment by tssvl** [comment]
I switched to older version

```
  - Removing slim/slim (3.0.0-RC3)
  - Installing slim/slim (3.0.0-RC2)
```

Now all work just fine. 

If it's my apache/.httaccess configuration problem I can give you all data you need. 
**But it seems very strange then.**

My configuration:
Windows 10
XAMP
Apache/2.4.16 (Win32) OpenSSL/1.0.1p 
PHP Version 5.6.11
Rewrite module endbled and AllowOverride All (it does not matter )

From apache access log:

```
::1 - - [02/Dec/2015:11:58:30 +0200] "GET /slim3/api.php HTTP/1.1" 200 6 "-" "Mozilla/5.0
::1 - - [02/Dec/2015:11:58:34 +0200] "GET /slim3/api.php/users HTTP/1.1" 404 886 "-" "Mozilla/5.0
```

after I switched to (3.0.0-RC2)

```
::1 - - [02/Dec/2015:12:44:55 +0200] "GET /slim3/api.php HTTP/1.1" 200 6 "-" "Mozilla/5.0
::1 - - [02/Dec/2015:12:44:59 +0200] "GET /slim3/api.php/users HTTP/1.1" 200 2634 "-" "Mozilla/5.0
```

**Comment by akrabat** [comment]
hmm... so you're accessing your test app via:

```
localhost/somepath/index.php/test
```

?

**Comment by tssvl** [comment]
Yes. For example route from my current app: 

```
http://localhost:8081/slim3/api.php/users
```

**Comment by geniuscd** [comment]
I can confirm this issue. after updating to RC3 the routing is broken.
I'm not using .htaccess,  im on tomcat :/ (long story)
so i'm using `localhost/project/public/index.php/route`
it used to work normally when i change one line of code in **Uri.php** line _194_
from

``` php
$requestUri = parse_url($env->get('REQUEST_URI'), PHP_URL_PATH);
```

to 

``` php
$requestUri = parse_url($env->get('PHP_SELF'), PHP_URL_PATH);
```

after updating to the latest version, but now its broken.
here is my route file

``` php
$app->group('/', function() use ($app) {
    $app->group('/employees', function() use ($app) {
        $app->get('', 'App\Controller\View\EmployeesController:dispatch')->setName('employees');
        $app->get('/categories', 'App\Controller\View\employeesCategoriesViewController:dispatch')->setName('employeesCategories');
    });
});
```

**Comment by dukeatcoding** [comment]
I can confirm the issue too. Running the project with lighthttp 

Rolled back to RC2

**Comment by akrabat** [comment]
This is a base path issue which was reported as https://github.com/slimphp/Slim/issues/1590

The fix: https://github.com/slimphp/Slim/pull/1606 is what causes this problem

**Comment by elshobokshy** [comment]
Is there a fix? I'm having this same problem. Only my root path works, but anything thing else '/xxx' doesn't work... :(
