### ISSUE TITLE
Slim3 app->router()->getCurrentRoute()

### ISSUE THREAD

**Issue by mbretter** [slimphp/Slim#1644]
Hi,

during the migration from Slim2 => 3, I have not found a way in slim3 to get the current Route, in slim2 it was 
$app->router()->getCurrentRoute()

thx,
cheers

**Comment by silentworks** [comment]
Take a look here https://github.com/slimphp/Slim/issues/1594#issuecomment-157010524

**Comment by geggleto** [comment]
`$request->getAttribute('route')`

**Comment by mbretter** [comment]
thx!

**Comment by mbretter** [comment]
If you are accessing this attribute within an app middleware it's important to set
'determineRouteBeforeAppMiddleware' => true,
otherwise $request->getAttribute('route') returns null

**Comment by aleksey-kozakov** [comment]
@silentworks  Thank you, man. Finally I got it.

**Comment by aleksey-kozakov** [comment]
Set in the app config - 'determineRouteBeforeAppMiddleware' => true

```
$request->getAttribute('route')->getName()
```

**Comment by Motard** [comment]
I am having some trouble with this. I am getting null when i do `$request->getAttribute('route')->getName()`. And I have also the `determineRouteBeforeAppMiddleware' => true` in the settings.php.

Anyone has any suggestion?

**Comment by akrabat** [comment]
@Motard The Url hasn't matched or you haven't called `->setName()` after you defined your route.

**Comment by Motard** [comment]
Thx @akrabat. The problem was the missing `->setName()` after declaring the route.
