### ISSUE TITLE
Interfaces for Handler Classes

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1646]
In 3.x Container doc
-  - errorHandler: a callable with the signature: function($request, $response, $exception)
-  - notFoundHandler: a callable with the signature: function($request, $response)
-  - notAllowedHandler: a callable with the signature: function($request, $response, $allowedHttpMethods)

I would like to create  a base interface for these.

Could keep them separated...

``` php
interface IErrorHandler {
    public function __invoke($request, $response, $exception);
}
```

Or we could provide a handler class...

``` php
interface ISlimHandler {
    public function errorHandler($request, $response, $exception);
    public function notFoundHandler($request, $response);
    public function notAllowedHandler($request, $response, $allowedHttpMethods);
}
```

Having a base class that is extendable?

Not needed for 3.0 but maybe 3.1

@akrabat @codeguy @silentworks 

Thoughts ?

**Comment by p-golovin** [comment]
It will be great to be able create and inject own error handlers without modifing or extending Slim\App. And extending them from base ErrorHandling class, redefining only messages for html/xml/json formats and http code.

**Comment by geggleto** [comment]
@p-golovin you can overwrite the the default handlers in the container as long as you keep the same function signature.

**Comment by p-golovin** [comment]
@geggleto I talk not about owerwriting existing handlers, but about adding new one. For example: BadRequest (400 http code). But for now I can't call them for given type of exception without rewriting \Slim\App::handleException function.
And also there may exists different handlers with same logic of defining content-type, but only difference in message text in output.
So it will be great to have smth like this

``` php
class Handler
{
    protected $message = [
        'html' => '...',
        'xml' => '...',
        'json' => '...',
    ];

    private function determineContentType(...)
    { ... }

    protected function renderJsonOutput(...)
    { ... }

    ...
}

class NotFound extends Handler
{
    // redefine $message
}
```

And be able configure map between exceptions and handlers via container for this

``` php
    protected function handleException(Exception $e, ServerRequestInterface $request, ResponseInterface $response)
    {
        if ($e instanceof MethodNotAllowedException) {
            $handler = 'notAllowedHandler';
            $params = [$e->getRequest(), $e->getResponse(), $e->getAllowedMethods()];
        } elseif ($e instanceof NotFoundException) {
            $handler = 'notFoundHandler';
            $params = [$e->getRequest(), $e->getResponse()];
        } elseif ($e instanceof SlimException) {
            // This is a Stop exception and contains the response
            return $e->getResponse();
        } else {
            // Other exception, use $request and $response params
            $handler = 'errorHandler';
            $params = [$request, $response, $e];
        }
```

**Comment by geggleto** [comment]
You can easily do this in a middleware!

Something like this.

``` php
$app->add(function ($req, $res, $next) {
    $res = $next($req, $res);
    $hnd = null;
    switch($res->getStatusCode()) {
        case 400: { $hnd = $this->get('400Handler'); }
        ///.....
    }
    if (!is_null($hnd)) { $res = $hnd($req, $res); } 
    return $res;
});

```

**Comment by akrabat** [comment]
I don't see the advantage of an interface?

**Comment by geggleto** [comment]
Will hopefully address in 4.0
