### ISSUE TITLE
Slim 3 RC3 Response cut off

### ISSUE THREAD

**Issue by andrewpros** [slimphp/Slim#1647]
The response is just cut off, simple script

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use Slim\App;
use Slim\Http\Request;
use Slim\Http\Response;

require 'vendor/autoload.php';

$app = new App;

$app->get('/', function (Request $in, Response $out, $args) {
 return $out->write("xxx");
});

$app->run();
```

Running using built in php server - php -S localhost:8000 (5.5.12)

Outputs nothing, changed to

return $out->write("xxxyyyzzz")

outputs xxxyyy

As if 3 letters are always missing.

**Comment by irfanevrens** [comment]
I try, it writes what it is in write function.

**Comment by andrewpros** [comment]
There must be a reason, i've even traced it to https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L390 and the echo returns the whole string, so i don't know where is the problem, it is the most basic simple script.

I will do some checks now.

**Comment by andrewpros** [comment]
Ok it works with the latest php 7.0.0 ts x64 from dec 3.

**Comment by andrewpros** [comment]
Ok, it is something with my php setup, but any other script works fine, not sure why there is problem with slim3.

**Comment by akrabat** [comment]
I'm sorry, but I can't reproduce. I don't have PHP 5.5.12, so I tested withPHP 5.5.30.

**Comment by akrabat** [comment]
I can't even think what it might be. Can you test with curl please?

```
curl -v http://localhost:8000/
```

and report the response.

**Comment by andrewpros** [comment]
Thx man, found it.

The response was

```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /api.php HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.45.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Host: localhost:8000
< Connection: close
< X-Powered-By: PHP/5.5.12
< Content-Type: text/html; charset=UTF-8
< Content-Length: 9
<
* Excess found in a non pipelined read: excess = 3, size = 9, maxdownload = 9, bytecount = 0
´╗┐xxxyyy* Closing connection 0
```

So i immediately noticed the extra signs, never seen them before, the file was UTF-8, i double checked that before i even posted here, even with show all sings in notepad++, phpstorm was not complaining either, but it turns out it was with BOM, converted to utf-8 without BOM and that was it.

Still not sure if slim3 should be affected by that, but i know the reason at least.

**Comment by akrabat** [comment]
Slim is affected because we set the content length of the response based on the length of the data. The BOM characters were not counted, but were output.

Glad you found it!
