### ISSUE TITLE
Default Branch is not 3.x

### ISSUE THREAD

**Issue by irfanevrens** [slimphp/Slim#1648]
When enter the code tab of github repo, I think default branch should become 3.x.

**Comment by akrabat** [comment]
The current stable version of Slim is the 2.6.2. When Slim 3.0 is released, then we will change the default branch to 3.x

**Comment by irfanevrens** [comment]
Thanks for your info.

**Comment by akrabat** [comment]
3.0 is now released and I've switched the default branch to 3.x.

**Comment by irfanevrens** [comment]
Congratulations.

**Comment by MehdiRaash** [comment]
well done.

**Comment by MehdiRaash** [comment]
**Well done**
