### ISSUE TITLE
the newest composer 3.0 RC package can't get container by $this->getContainer()

### ISSUE THREAD

**Issue by zdkmygod** [slimphp/Slim#1650]
And will tell you "PHP Fatal error:  Call to undefined method Slim\Container::getContainer()".
I find an old RC package in my VPS, and it has no that problem.

I paste the code which I test this quesion:

```
<?php
require './vendor/autoload.php';

$container = new \Slim\Container([
    "host" => "hehe"
]);
$app = new \Slim\App($container);
$app->get('/', function ($req, $res, $args) {
    $container = $this->getContainer();
    echo 'aac';
    return $res;
});
//run app
$app->run();
```

**Comment by akrabat** [comment]
Please check the BC breaks listed in the [Release notes for RC3](https://github.com/slimphp/Slim/releases/tag/3.0.0-RC3).

Specifically:

> #1631 - The route callable is now bound to the Container rather than to the App to be consistent with middleware binding. This means that if you are using $this->subRequest then you now need to `use ($app)` and then `$app->subRequest(…)`. Also if you were using `$this->getContainer()->get(…)`, you need to change this to `$this->get(…)`. Note that using `$this->foo` to retrieve a service from the container continues to work.

i.e. in the route callable, `$this` is the Container now.
