### ISSUE TITLE
How to use container in a class which extend InvocationStrategyInterface

### ISSUE THREAD

**Issue by irfanevrens** [slimphp/Slim#1651]
Hello, I have class extend InvocationStrategyInterface.

``` php
public function __invoke(callable $callable, ServerRequestInterface $request, ResponseInterface $response, array $routeArguments)
{
    // how can I use container here?
}
```

**Comment by mathmarques** [comment]
It depends.
How do you use this class?

Pass like "className:function", through container or just new className()?

**Comment by mathmarques** [comment]
The container or the dependencies should be inject through class constructor.

If you use you class like "fullyClassName:function", the container will be inject on constructor automatically.

Other ways you will have to inject through constructor manually

**Comment by irfanevrens** [comment]
It is a foundHandler, the container does not injected on constructor. I think there is no need $request and $response if $container will given. am I right @akrabat

**Comment by akrabat** [comment]
you always need request and response in the route callable as they could be changed by middleware.

**Comment by akrabat** [comment]
Really, they shouldn't be in the container at all

**Comment by irfanevrens** [comment]
Thanks.
