### ISSUE TITLE
About Middleware Execution

### ISSUE THREAD

**Issue by irfanevrens** [slimphp/Slim#1658]
Hello, why application middlewares are executed as Last In First Executed (LIFE) - why not First In First Executed (FIFE)

**Comment by fyfey** [comment]
This caught me out as well, I was expecting the latter.

It uses a SplStack under the hood, so think of it as each time you add one, you're adding to the stack, Slim then takes middleware from the top of the stack.

**Comment by akrabat** [comment]
It's visualised in the [docs](http://www.slimframework.com/docs/concepts/middleware.html#how-does-middleware-work) as a set of concentric circles. Every call to `add` adds a new outer circle.
