### ISSUE TITLE
Slim3 Route middleware with args

### ISSUE THREAD

**Issue by mbretter** [slimphp/Slim#1659]
Hey, 

in Slim2 I have a route middleware invoked with arguments:

```
$app->get('/foo/bar', $authorize('whatever'), function () use ($app)
```

How can I do this with Slim3? I've only found that route middlewares can be attached with add(), but no args can be passed, I'missing something like:

```
$app->get('/foo/bar', function ($request, $response, $args) use ($app)
...
})->add($authorize, 'whatever');
```

thx

**Comment by silentworks** [comment]
The code below works in Slim 3.

``` php
$app->get('/foo/bar', function ($request, $response, $args) use ($app)
...
})->add($authorize('whatever'));
```

**Comment by mbretter** [comment]
great, works thx!
