### ISSUE TITLE
phpunit tests failed

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#166]
Hi,

When I run command `$ phpunit tests` I get this output:

<pre>
 PHPUnit 3.5.13 by Sebastian Bergmann.

..........................F................E...................  63 / 142 ( 44%)
............................/foo/foo................................... 126 / 142 ( 88%)
................

Time: 7928:03:50, Memory: 7.25Mb

There was 1 error:

1) SlimTest::testSlimDefaultView
session_start(): Cannot send session cookie - headers already sent by (output started at /usr/share/php/PHPUnit/Util/Printer.php:173)

~/codeguy-Slim-88462cf/Slim/Slim.php:208
~/codeguy-Slim-88462cf/tests/SlimTest.php:132

--

There was 1 failure:

1) RequestTest::testStripSlashesIfMagicQuotes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-bar'd
+bar\'d

~/codeguy-Slim-88462cf/tests/Http/RequestTest.php:153

FAILURES!
Tests: 142, Assertions: 360, Failures: 1, Errors: 1. 
</pre>

Checked master 1.5.0.2 and develop branch with the same result. I have magic_quotes_gpc = Off  (it's deprecated in PHP 5.3.0) so if I turn on magic_quotes_gpc I haven't failure.

All the best
Tom

**Comment by codeguy** [comment]
I see that too. For now if you run with `--stderr` they will run successfully. I'll try to find that and fix it.

**Comment by codeguy** [comment]
Fixed. See commit https://github.com/codeguy/Slim/commit/c49873d027f4598c7750b142243324a628bc8925. PHPUnit was apparently sending output really early. Starting a session earlier in the tests fixes the error.

**Comment by ghost** [comment]
Ok, but also test RequestTest::testStripSlashesIfMagicQuotes should run ok when magic_quotes_gpc is off. I wrote workaround, but I don't know that it's correct:

<pre>
diff --git a/tests/Http/RequestTest.php b/tests/Http/RequestTest.php
index 1a1970d..467375a 100644
--- a/tests/Http/RequestTest.php
+++ b/tests/Http/RequestTest.php
@@ -150,7 +150,10 @@ class RequestTest extends PHPUnit_Framework_TestCase {
     public function testStripSlashesIfMagicQuotes() {
         $_GET['foo1'] = "bar\'d";
         $getData = Slim_Http_Request::stripSlashesIfMagicQuotes($_GET);
-        $this->assertEquals("bar'd", $getData['foo1']);
+       if(get_magic_quotes_gpc())
+               $this->assertEquals("bar'd", $getData['foo1']);
+       else
+               $this->assertEquals("bar\'d", $getData['foo1']);
     }
     
     /* TEST REQUEST METHODS */
</pre>
