### ISSUE TITLE
Slim3 app magic __get passthrough

### ISSUE THREAD

**Issue by mbretter** [slimphp/Slim#1660]
Hi,

during the migration from slim2 to 3, I've found that it would help a lot having

```
    public function __get($name)
    {
        return $this->container->get($name);
    }
```

within \Slim\App
any chance getting this into Slim3?

thx,

**Comment by silentworks** [comment]
This is actually in the Container and since a closure is bound to the Container you can call services the same as you would in Slim 2.

https://github.com/slimphp/Slim/blob/3.x/Slim/Container.php#L287

``` php
$app->get('/foo/bar', function ($request, $response)
    $this->router->methodName();
});
```

You should also note there is a Strategy that allows you to map placeholders to args like in Slim 2, so you can do.

``` php
$app->get('/foo/bar/:name', function ($request, $response, $name)
    return $response->getBody()->write("Hello $name")
});
```

Will get something written up about migrating soon.

**Comment by mbretter** [comment]
I've used Slim2 as a container for a lot of stuff, like

```
$app->cache->get(...
```

with slim3 I have to rewrite tons of calls to 

```
$app->getContainer()->cache->get(...
```

cache is in this case not a callable, so the __call() passthrough does nothing in this case

**Comment by silentworks** [comment]
Look at my example again, you can do the same, you just need to replace `$app` in the Closure to `$this`.

**Comment by geggleto** [comment]
As @silentworks mentioned

`$app->cache->get(...` becomes `$this->cache` in slim 3.
The container has magic method support.

**Comment by mbretter** [comment]
most of my code is not directly in the route callback, it's inside classes somewhere else, where I'm getting the app using \Slim\Slim::getInstance(); (using a trait)

**Comment by silentworks** [comment]
Do note all classes that are instantiated by Slim itself using

``` php
$app->get('/', 'MyClass:hello');
```

The constructor is passed an instance of `Container`, so you can do

``` php

class MyClass
{
    private $container;
    public function __construct($container)
    {
        $this->container = $container;
    }

    public function hello()
    {
        $this->container->cache->get(...
    }
}
```

or you can create your own App class and extend `Slim\App` and add the magic getter to your version.

**Comment by mbretter** [comment]
My classes are Singletons, they are not directly instantiated by Slim, this would mean that I have to change the constructor/init of all of my classes and pass the container to all of them. 
Without accessing the global $app I have to make big changes to my source code.

One possibility would be exchanging the content from $app (currently instance of \Slim\App) with $app->getContainer().

It's not a big thing if you are starting from scratch with a new Slim application, but I'm migrating an existing application, I'm trying to keep the necessary code changes as small as possible.
However I made a subclass of Slim and put the __get() in there.

**Comment by geggleto** [comment]
Glad you got it sorted.

If you could plz open an issue in the slim-website repo with what you did we can put it into the docs under a Strategy section!

**Comment by feryardiant** [comment]
I'm using `__get()` in my [`base controller`](https://github.com/projek-xyz/slim-skeleton/blob/master/app/src/Actions/Base.php#L30-L33) so I can just use `$this->view->..` form my [`main controller`](https://github.com/projek-xyz/slim-skeleton/blob/master/app/src/Actions/HomeAction.php#L10)

**Comment by mbretter** [comment]
doc issue in website repo opened:
https://github.com/slimphp/Slim-Website/issues/83
