### ISSUE TITLE
Better way of create links

### ISSUE THREAD

**Issue by leandroruel** [slimphp/Slim#1661]
create links to our routes is a bit complicated, create links like this would be great:

``` html
<a href="{{ route('home'); }}">home</a>
```

**Comment by geggleto** [comment]
There is my friend. I see you are using Twig. If you are using Twig-View...

``` html
<a href="{{ path_for('home') }}">home</a>
```

https://github.com/slimphp/Twig-View/blob/master/src/TwigExtension.php#L37

**Comment by leandroruel** [comment]
yes! i'm using twig-slim
