### ISSUE TITLE
Routes via container

### ISSUE THREAD

**Issue by Lewiscowles1986** [slimphp/Slim#1668]
Okay this may be an absolutely stupid question; but looking at the documentation and the source code I see the router is injected via a container, and can be replaced by any class implementing `\Slim\Interfaces\RouterInterface`. Is it possible to get the router from a separate service container, which can add it's own route's; and should this be documented in the official documentation?

I'm happy to document if this is valid, I just wanted to get some feedback to see if I'm loosing my marbles thinking it's a lot cleaner, and more modular than using `$app->{$verb}` globally, or requiring files which $app->verb?

My thinking is that a lot of frameworks will be supporting PSR-7, they will also likely have some low-level routing interoperability and it could increase code sharing potential for services to work on multiple frameworks.

**Comment by akrabat** [comment]
> Is it possible to get the router from a separate service container, which can add it's own route's;

I'm sorry, but I'm not sure that I understand the question. Slim already has a container and retrieves the router from it. It looks for the key called `router` and you can provide whatever class you like for that.

**Comment by Lewiscowles1986** [comment]
Hi @akrabat not looking to override the router itself, but asking about handling routes themselves via di instead of require as in your slim3 example

So non-trivial complex services that register routes themselves, maybe even middleware also with an application.

**Comment by geggleto** [comment]
@Lewiscowles1986 you can store routes in an array if you want and iterate over that key elsewhere...

``` php
//In Container...
'routetable' => [
    'verb' => [
        'pattern' => 'callback'
    ],
]

//someplace else...
$routetable = $app->getContainer()['routetable'];

foreach ($routetable as $verb = > $routes) {
    foreach ($routes as $pattern => $callback) {
        $app->map([$verb], $pattern, $callback);
    }
}
```

Or something like that ;)

**Comment by Lewiscowles1986** [comment]
Thanks @geggleto!
