### ISSUE TITLE
setPattern() in Slim 3.x? 

### ISSUE THREAD

**Issue by tachyon-ops** [slimphp/Slim#1669]
Hi there,

How can I dynamically assign setPattern in Slim 3.x?

**Comment by tachyon-ops** [comment]
So, with the help of @akrabat on #slimphp freenode channel I accomplished this making a setter in Slim's Routable.php;

```
   /**
     * Set the route pattern
     *
     * @set string
     */
    public function setPattern($newPat)
    {
        $this->pattern = $newPat;
    }
```

I suggest this to be implemented in the code.

**Comment by tachyon-ops** [comment]
User case:

i18n dynamic assignment through named routes.
configuration driven urls
...

**Comment by akrabat** [comment]
I'm not adverse to someone creating a PR for this.
