### ISSUE TITLE
Remove index.php from Request root URI

### ISSUE THREAD

**Issue by rubentlz** [slimphp/Slim#167]
Can Slim work on IIS 6.0 without mod-rewrite?

EDIT: See comments below.

**Comment by codeguy** [comment]
I am not familiar enough with IIS. Slim does work on Apache without mod_rewrite. If it does not work on IIS, let me know what errors you receive and I'll take a closer look.

**Comment by rubentlz** [comment]
It doesn't work so far in my shared server. Take a look at http://can-i.com.my/demo. Two things:

Firstly, Slim::request()->getRootUri(); gives me http://can-i.com.my/demo/index.php, which means my css and js files would not be loaded (click view source). If I remove the index.php, static files load just fine.

Secondly, there's a route at http://can-i.com.my/demo/admin, which works locally (I'm running MAMP) on Apache, but doesn't in my server (IIS 6.0). You can take a look at the phpinfo() page at http://can-i.com.my/demo/test.php.

**Comment by codeguy** [comment]
1. Removing "index.php" from Request->getRootUri() is a valid issue that needs to be addressed for asset paths.
2. It seems that your Apache server is using mod_rewrite and that your IIS server is not, so the route on IIS would be "/demo/index.php/admin" and not  "/demo/admin".

I'll re-open this issue only for removing index.php from Request root URI.

**Comment by codeguy** [comment]
Thinking more on this, however, you'll want the Root URI to be the absolute path to which the resource URI can be appended to create a full absolute application URI... removing "index.php" may be good for assets but not for building application paths. I'm not sure yet how I want to change this, if at all... will think on it. Anyone else have an opinion?

**Comment by rubentlz** [comment]
I don't mind adding in index.php to my routes. That's the least of my problems. Adding a getResourceUri() on the other hand, as a companion to getRootUri(), would be nice if we have assets served from a different location (CDN maybe?) or folder.

**Comment by rubentlz** [comment]
I am the stupid. There already is getResourceUri. Closing this issue now.

**Comment by codeguy** [comment]
No worries :) Let me know if you have any other questions; post them to the forum at http://forum.slimframework.com.
