### ISSUE TITLE
Is $uploadedFile['tmp_name'] a typo?

### ISSUE THREAD

**Issue by upliu** [slimphp/Slim#1673]
hello,
I am reading slim's source code. In file Slim\Http\UploadedFile.php:108 and line 118 in with the line 

```
isset($uploadedFile['tmp_name']) ? $uploadedFile['name'] : null,
```

Why isset($uploadedFile['tmp_name']) , I think it should be isset($uploadedFile['name']):

```
isset($uploadedFile['name']) ? $uploadedFile['name'] : null,
```

Some can help me ? thanks.

**Comment by silentworks** [comment]
This is correct as it is. Read from the link below for reference on $_FILES in php.

http://php.net/manual/en/features.file-upload.post-method.php
