### ISSUE TITLE
Query Params issue

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1674]
`$request->getQueryParams()` is returning duplicated parameters.

`?tags%5B%5D=Express&tags%5B%5D=Baking` as a url is returning the following

```
array (size=4)
  0 => string 'Express' (length=7)
  1 => string 'Baking' (length=6)
  2 => string 'Express' (length=7)
  3 => string 'Baking' (length=6)
```

There is no intervention into the object by app code, it is the raw request object generated by Slim.

**Comment by designermonkey** [comment]
This is at the present commit of `48fb2ce25255ad73f0c322f8914d289d8e55e923`

**Comment by designermonkey** [comment]
Tested with 

``` php
var_dump($app->getContainer()['request']->getQueryParams());die;
```

**Comment by silentworks** [comment]
This is the result I get using the PHP built in webserver on the hash you have above.

```
array(1) {
  ["tags"]=>
  array(2) {
    [0]=>
    string(7) "Express"
    [1]=>
    string(6) "Baking"
  }
}
```

**Comment by designermonkey** [comment]
I can confirm that if I don't use the router and just `var_dump($app->getContainer()['request']->getQueryParams());die;` after I initialise an app, it works as expected. As soon as I use the router, it doubles up the parameters.

**Comment by designermonkey** [comment]
I've just var_dump'ed the Uri object and found the querystring duplicated, which led me to look in my nginx config.

I've always been used to defining the querystring on the index file, but obviously Slim works more intelligently than that.

I would love to see any examples of a simple nginx config for Slim.
