### ISSUE TITLE
Fail to find route when there is trailing slash

### ISSUE THREAD

**Issue by nmhnmh** [slimphp/Slim#1677]
Slim treat /api/test and /api/test/ as two different url, this may cause some problem.
If we have something like this:

``` php
$app->group('/rest', function(){
    $this->group('/users', function(){
        //will not match /rest/users, only match /rest/users/
        $this->get('/', function($req, $res){});
        $this->post('/validate', function($req, $res){});
        $this->post('/login', function($req, $res){});
    });
});
```

Can we just match literally when there is two routes(same path, but one with trailing slash and one without), and use the same route when there is only one route(with or without trailing slash)?

**Comment by danopz** [comment]
#1626
Just register them `$app->get('/user[/]', ...`

**Comment by akrabat** [comment]
Alternatively, use middleware: http://www.slimframework.com/docs/cookbook/route-patterns.html

**Comment by nmhnmh** [comment]
@akrabat Thank your for your advice, middleware seems to be a good solution at the moment.
