### ISSUE TITLE
Routing bug?

### ISSUE THREAD

**Issue by feryardiant** [slimphp/Slim#1679]
Here I have setup my [`routes.php`](https://github.com/projek-xyz/slim-skeleton/blob/develop/app/routers.php)

``` php
$app->get('/[{name}]', 'App\Actions\HomeAction:index')->setName('home-page');
```

and here my index method in [action class](https://github.com/projek-xyz/slim-skeleton/blob/develop/app/src/Actions/HomeAction.php)

``` php
public function index($req, $res, $args)
{
    if (isset($args['name'])) {
        return $this->view->render('hello', [
            'name' => $args['name'],
            'desc' => 'Welcome to world',
        ]);
    }
    return $this->view->render('home');
}
```

and sure it works as expected

| Request URI | Response |
| --- | --- |
| `example.com[/]` | render `home` template |
| `example.com/foobar` | render `hallo` template, with `$args['name'] = 'foobar'` |
| `example.com/foo/bar` | return not found |

but I don't expect it could work like this.

| Request URI | Response |
| --- | --- |
| `example.com//` | render `home` template |
| `example.com//foo` | render `home` template |
| `example.com//foo/bar` | render `hallo` template, with `$args['name'] = 'bar'` |
| `example.com//foo/bar/bas` | return not found |
| `example.com///foo` | render `home` template |
| `example.com///foo/bar` | render `home` template |
| `example.com///foo/bar/bas` | render `home` template |

Is it a bug?

**EDIT**: I'm using local ubuntu server with nginx

**Comment by geggleto** [comment]
Well Given that we use https://github.com/nikic/FastRoute ... I am not 100% sure.

**Comment by silentworks** [comment]
This is not a bug. I somewhat think its a browser/web server behaviour. I just tried this on some websites and it worked, also note some websites do redirect to the url with only 1 slash.

https://github.com///slimphp/Slim/issues/1679
https://www.google.com///doodles

**Comment by feryardiant** [comment]
@silentworks yes, you're right. But, can you see the difference between _common_ behaviour and the way slim does?

I've also expect that slim route should work that way in my setup.

| Request URI | Response |
| --- | --- |
| `example.com//` | render `home` template |
| `example.com//foo` | render `hallo` template, with `$args['name'] = 'foo'` |
| `example.com//foo/bar` | return not found |
| `example.com//foo/bar/bas` | return not found |
| `example.com///foo` | render `hallo` template, with `$args['name'] = 'foo'` |
| `example.com///foo/bar` | return not found |
| `example.com///foo/bar/bas` | return not found |

**Comment by geggleto** [comment]
Not to be a stickler.... but `difference between common behaviour and the way slim does` ... we are using a 3rd party router that is very popular ... See my last comment.

**Comment by feryardiant** [comment]
So, anyone have test this case with other framework that use same _3rd party router that is very popular_??

**Comment by akrabat** [comment]
This feels like a bug to me.

**Comment by akrabat** [comment]
I'm looking at the `//foo/bar` case. 

This comes into Slim as `$_SERVER['REQUEST_URI']` which is set to `//foo/bar` as you'd expect.

However, `Uri::createFromEnvironment` extracts it using this [line](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Uri.php#L194):

``` php
$requestUri = parse_url($env->get('REQUEST_URI'), PHP_URL_PATH);
```

which results in `$requestUri` set to `/bar`

This isn't what I would expect!

**Comment by akrabat** [comment]
I'm pretty sure that using `parse_url` is wrong in this case and this line should be:

``` php
$requestUri = $env->get('REQUEST_URI');
```

Thoughts @codeguy, @silentworks?

**Comment by geggleto** [comment]
This is not a bug and is documented in FastRoute.

From the README.md of FastRoute

```
// Matches /user/foobar, but not /user/foo/bar
$r->addRoute('GET', '/user/{name}', 'handler');

// Matches /user/foo/bar as well
$r->addRoute('GET', '/user/{name:.+}', 'handler');
```

The correct pattern would be...
$app->get('/[{name:.+}]', 'App\Actions\HomeAction:index')->setName('home-page');

example.com// ==> home
example.com//foo ==> hallo 
example.com//foo/bar => matches because of the .+
example.com//foo/bar/bas => matches because of the .+
example.com///foo => hallo
example.com///foo/bar =>   matches because of the .+
example.com///foo/bar/bas =>  matches because of the .+

I am not a regex wizard. But there would be a regex possible I think to do exactly what he wants.

**Comment by geggleto** [comment]
Also as a follow-up @akrabat 

From FastRoute's documentation...

``` php
// Fetch method and URI from somewhere
$httpMethod = $_SERVER['REQUEST_METHOD'];
$uri = rawurldecode(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH));
```

**Comment by akrabat** [comment]
This has nothing to do with FastRoute.

For the URL `http://example.com//foo/bar` we send `/bar` to FastRoute. i.e. we've removed the `//foo/` from the URL before we set it into the `Uri` instance.

**Comment by akrabat** [comment]
That documentation snippet explains where we got the idea to use `parse_url()`!

However, the [documentation for parse_url](http://php.net/parse_url) says:

> **Note:**
> This function doesn't work with relative URLs.

**Comment by geggleto** [comment]
haha...

`This function is intended specifically for the purpose of parsing URLs and not URIs.`

**Comment by akrabat** [comment]
How about solving like this:

``` php
$requestUri = parse_url('http://example.com' . $env->get('REQUEST_URI'), PHP_URL_PATH);
```

As we only want the URI, the actual value of the scheme and domain are unimportant, but it will make `parse_uri` work as we would expect.

**Comment by geggleto** [comment]
Reference: https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Uri.php#L194

**Comment by geggleto** [comment]
That solution looks fine to me.

I was wondering if the output of requestURI was being based into the constructor of the URI but it is not.

:+1:
