### ISSUE TITLE
Add to Media Parsers

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1683]
Weird issue in IE.
http://www.entwicklungsgedanken.de/2008/06/06/problems-with-internet-explorer-and-applicationjson/
Add text/javascript for JSON

**Comment by codeguy** [comment]
We'll address this soon. I want to discuss future road map with @silentworks and @akrabat first.

**Comment by geggleto** [comment]
@codeguy I found a work around for this issue this morning.

By overriding the default container factory for request, it is possible to register a media parser before the App class is created.

Example:

``` php
//...
// Required to manually create the container
$container = new \Slim\Container();
// Create new factory 
$container['request'] = function ($c) {
    // construct request from environment
    $request = \Slim\Http\Request::createFromEnvironment($c['env']);
    // add media parser
    $request->registerMediaTypeParser("text/javascript", function ($input) {
        return json_decode($input, true);
    });
};

// Construct App
$app = new Slim\App($container);
//...
```
