### ISSUE TITLE
[idea] Use relative path in exception trace?

### ISSUE THREAD

**Issue by feryardiant** [slimphp/Slim#1691]
Hi,

Did you guys like the idea of using relative path in `Slim\Handlers\Error` exception trace? May be something like this.

![slim application error](https://cloud.githubusercontent.com/assets/508665/11913711/17f5dc56-a6a0-11e5-8c85-7de9ca1bc2bc.png)

I know that I can easely extend the class, but I believe it would be greate if Slim have it by default.

Any thought?

**Comment by piotr-cz** [comment]
I like it, but honestly I don't think changing native behavior of `Exception::getTraceAsString` is worth the effort.
In other words, it would make codebase more complex for a little advantage.

If are into more fancy exception messages, I can recommend [whoops!](https://filp.github.io/whoops/), it should be possible to use it as an error handler instead of native one.

**Comment by feryardiant** [comment]
Hi @piotr-cz.

Yes you're right about _whould make codebase more complex_ but I believe that using [Whoops!](https://filp.github.io/whoops/) is way more complex. If I should use external error handler, I rather go with [phperror](http://phperror.net/) or [Symfony Error](http://symfony.com/doc/current/cookbook/controller/error_pages.html).

Anyway, here I actualy wanna ask is Slim had kind of idea or plan? Because some other framework also use it by default for security reason.

**Comment by piotr-cz** [comment]
You are right, full path disclosure is a security concern, but probably just like showing up whole stack trace.

In my application I'm using a debug and environment settings to decide whether to show user-friendly http page or default stack trace. Maybe similar strategy should be used in Slim core.

I mean for the end-user probably a message: Something bad happened, _please contact admin@site.com_ would be more beneficial.

**Comment by akrabat** [comment]
> Maybe similar strategy should be used in Slim core.

This is in place. The setting `displayErrorDetails` defaults to `false` and needs to be set to `true` in order to display the stack trace.

**Comment by feryardiant** [comment]
Hi @akrabat

Yes, I know it already. I meant when the `displayErrorDetails` settings is
set to `true` should we use a relative path in stack trace?.

---

Best :)
Fery Wardiyanto

**Comment by codeguy** [comment]
If I turn on a stack trace,  I'm either developing, debugging, or both. And in both cases I want to see exactly where my errors are. You should not need to turn on stack traces in production.
