### ISSUE TITLE
Need for .htaccess ommited from homepage

### ISSUE THREAD

**Issue by wiserweb** [slimphp/Slim#1692]
Just a suggestion to reduce the chances of 'Page not Found' frustrations when trying out the sample from http://www.slimframework.com/ homepage.

For some people, it may not be obvious that if they are just starting up an .htaccess file will need to be created and placed into the root of where the slim framework will be installed. They might not get the .zip version which includes a working .htaccess file. Perhaps supply a link to get the .htaccess file or supply code sample.

**Comment by silentworks** [comment]
An .htaccess file is not necessary to use Slim. If one should be required we have that covered in the docs and we also provide an example directory in the repo with one in it.

**Comment by wiserweb** [comment]
Using this sample

```
<?php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;

require 'vendor/autoload.php';

$app = new \Slim\App;
$app->get('/hello/{name}', function (Request $request, Response $response) {
    $name = $request->getAttribute('name');
    $response->getBody()->write("Hello, $name");

    return $response;
});
$app->run();
```

It seems that out-of-the box anyone using MAMP on OSX, XAMPP (Windows, Mac, Linux) or even a custom LAMP installation will encounter 'Page Not Found' if no .htaccess exists with at least these directives.

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
```

**Comment by akrabat** [comment]
An out of the box nginx install will also not work… However, an out-of-the-box  PHP built-in server will work as expected.
