### ISSUE TITLE
Get Name of router

### ISSUE THREAD

**Issue by songyanho** [slimphp/Slim#1695]
Hi, I am converting my project from v2 to v3 of Slim.Previously I was using middleware as a security clearance before user reach the specific route by checking the route name.

How could I access the routeName? Previously I was using $app->router()->getCurrentRoute()->getName();

Thank you.

**Comment by akrabat** [comment]
`$request->getAttribute("routeInfo");` should have the information you need.

Note that you'll also need the `determineRouteBeforeAppMiddleware` setting:

```
$settings = [
    'settings' => [
        'determineRouteBeforeAppMiddleware' => true,
    ]
];
$app = new Slim\App($settings);
// ...
```

**Comment by songyanho** [comment]
Noted; Thank you for your help!
