### ISSUE TITLE
Create SmartyView

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#17]
Create SmartyView custom View class. I'm working on this now and should have it wrapped up by this weekend.

**Comment by josedasilva** [comment]
I there, do you have some news on this? Need some help with it?

**Comment by codeguy** [comment]
It's on my to-do list, but I've been swamped at the day job lately. If you want to take a stab at it, you are more than welcome. Just let me know if you decide to take it on. You can see TwigView and MustacheView that have been coded by other contributors.

**Comment by josedasilva** [comment]
Yes, i have forked the project already and will start to work on it.

**Comment by josedasilva** [comment]
Just sent a Pull Request on the SmartyView custom view implementation. Feedback is welcomed.
