### ISSUE TITLE
[RFC] Slim 3 Refactor Container

### ISSUE THREAD

**Issue by praswicaksono** [slimphp/Slim#1701]
I think is better to move `registerDefaultServices` method in `Container` to `App`. Im having difficulty when trying to replace default `Container` because I have re-define default service and config.

**Comment by mathmarques** [comment]
You will have to re-define everything. Slim cannot register the services on all containers. There is no standard to register services.

See: https://github.com/container-interop/container-interop/blob/master/src/Interop/Container/ContainerInterface.php

**Comment by AndrewCarterUK** [comment]
@Atriedes have you tried decorating the container?

**Comment by praswicaksono** [comment]
@mathmarques I mean, i shouldn't have to re define the default service such as `response` and `request` object, since the default service is defined in `Container` level so I have to re-define it when I tried to use another container other that pimple

@AndrewCarterUK Im not decorating but replace pimple container to other container that already implement container interop.

**Comment by akrabat** [comment]
@Atriedes How could app create the services? Container intro doesn't define how to register a service…

**Comment by praswicaksono** [comment]
well here is my initial thought

``` php
namespace Slim;

class App
{
    private $container;

    public function __construct($container = [])
    {
        if (is_array($container)) {
            $container = new Container($container);
        }
        if (!$container instanceof ContainerInterface) {
            throw new InvalidArgumentException('Expected a ContainerInterface');
        }
        $this->container = $container;

        // register default service
        $this->registerDefaultService();
    }

    private function registerDefaultServices()
    {
        // all default service definition moved here instead defined in Container
    }
}
```

the container class will be more simpler since default service has defined in App class

``` php
<?php

namespace Slim;

class Container extends PimpleContainer implements ContainerInterface
{
    public function get($id)
    {
        if (!$this->offsetExists($id)) {
            throw new ContainerValueNotFoundException(sprintf('Identifier "%s" is not defined.', $id));
        }
        return $this->offsetGet($id);
    }

    public function has($id)
    {
        return $this->offsetExists($id);
    }
}
```

**Comment by akrabat** [comment]
The problem is that we have no idea how to write `registerDefaultServices` so that it works with any DI container…

**Comment by praswicaksono** [comment]
Ah my bad, i just notice that container interop doesn't have contract for registering service in container. I guess it solved now I have to redefine the default service if I want to use my own container.

thanks for your response

**Comment by akrabat** [comment]
You're welcome. I did the same here: https://github.com/akrabat/rka-slim-zfsm-container/blob/master/src/Container.php
