### ISSUE TITLE
Get $router in Middleware

### ISSUE THREAD

**Issue by songyanho** [slimphp/Slim#1702]
I tried to access router through $this->router in the middleware but failed. It gives notice Undefined property: Authentication::$router in ... and then fatal error when I access its member.

**Comment by geggleto** [comment]
If you were using a anon function, the function is bound to the container and you wouldn't have this problem.

so I am guessing you are using a class, in which case you need to either inject it yourself, or do something like below.

``` php

class YourMiddleware {
    protected $container;
    public function __construct(ContainerInterface $container) {
        $this->container = $container;
    }

    public function __get($name) {
        return $this->container->get($name);
    }

    public function __invoke($req, $res, $next) {
        //$this->router
        return $next($req, $res);
    }

}
```

**Comment by silentworks** [comment]
You don't need to inject it yourself if you are using `->add('Class:method')` or `->add(new Class)`. In these cases we inject `container` into the constructor for you. So you can call `$this->container->get('router')`.

**Comment by ddannyc** [comment]
@silentworks Sorry,  I am using ->add('Class:method') or ->add(new Class) and both failed to get container in slim3

**Comment by feryardiant** [comment]
@wayne712 **AFAIK** if you use `$app->add('Class:method')` the argument [will be resolved](https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L108) by `CallableResolver` and will inject the `Container` object through [constructor](https://github.com/slimphp/Slim/blob/3.x/Slim/CallableResolver.php#L76).

**Comment by ddannyc** [comment]
@feryardiant Thanks for reply. I am still got the problem.   My sample are below.

``` php
// routes.php
$app->get('/test', new \App\views\Test());
// or route
$app->get('/test', '\\App\\views\\Test:index');

// Test.php
namespace App\views;

use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;

class Test
{
    public function index(RequestInterface $request, ResponseInterface $response)
    {
        $this->logger->info('log info');

        return $response;
    }
    public function __invoke(RequestInterface $request, ResponseInterface $response)
    {
        $this->logger->info('log info');
        $response->getBody()->write('Hello world');
        return $response;
    }
}
```

Notice: Undefined property: App\views\Test::$logger in \App\src\views\Test.php

**Comment by feryardiant** [comment]
What about

``` php
// Test.php
namespace App\views;

class Test
{
    private $logger;

    public function __construct($container)
    {
        $this->logger = $container->get('logger');
    }

    public function index(RequestInterface $request, ResponseInterface $response)
    {
        $this->logger->info('log info');

        return $response;
    }

    // your __invoke() method
}
```

**Comment by ddannyc** [comment]
@feryardiant ,  Thank you very much. I don't want to inject the `Container` myself. Anonymous function case works but object don't

``` php
$app->get('/test', function (RequestInterface $request, ResponseInterface $response) {
        $this->logger->info('log info');

        return $response;
    });
```

**Comment by feryardiant** [comment]
Sure, you can get `logger` instance using closure, because it bound the container.

I wonder how could you get the `logger` instance when you don't want to inject the `container` to your class.

Best, Fery.

**Comment by ddannyc** [comment]
@feryardiant , thanks. I saw the comments by  silentworks,he said 
"You don't need to inject it yourself if you are using ->add('Class:method') or ->add(new Class). In these cases we inject container into the constructor for you. So you can call $this->container->get('router')."
So I also wonder how it makes.

**Comment by ddannyc** [comment]
@feryardiant , thanks.  Base on your replied.  I think I understand now.

**Comment by feryardiant** [comment]
You're right he said

>  we inject container into the constructor for you.

But, you still need yo create your class constructor yourself. Right?

Best, Fery.

On Dec 30, 2015 13:49, wayne712 notifications@github.com wrote:

@feryardiant , thanks. I saw the comments by silentworks,he said 
"You don't need to inject it yourself if you are using ->add('Class:method') or ->add(new Class). In these cases we inject container into the constructor for you. So you can call $this->container->get('router')."
So I also wonder how it make.

**Comment by designermonkey** [comment]
I think this is resolved?

Just for clarity:
1. Classes that are to be used as middleware, and require access to objects from the container, need to use the constructor pattern. The best example is from @geggleto above https://github.com/slimphp/Slim/issues/1702#issuecomment-167036377
2. For clarity sake, closure middleware can access the container as `$this` inside the closure.

If anyone feels this isn't resolved, please re-open with comments.
