### ISSUE TITLE
Group routing

### ISSUE THREAD

**Issue by dewey92** [slimphp/Slim#1703]
I think it would be so pleasing if this is documented:

```
$app->group('/myposts', function() {
    $this->get('/', function ($req, $res, $args) {
       // Le code
    });
}
```

The code above doesn't work and return 404. However, when we omit the slash in the child, it works like a charm:

```
$app->group('/myposts', function() {
    $this->get('', function ($req, $res, $args) { // Omit the slash
       // Le code
    });
}
```

**Comment by akrabat** [comment]
With and without the `/` are different URLs.

The first example is routed via `http://example.com/myposts/` and the second via `http://example.com/myposts`.

**Comment by dewey92** [comment]
Indeed, I have set up my middleware to handle the trailing slash as in the doc:

```
$app->add(function (Request $req, Response $res, callable $next) {
    $uri = $req->getUri();
    $path = $uri->getPath();

    if ($path != '/' && substr($path, -1) == '/') {
        // permanently redirect paths with a trailing slash
        // to their non-trailing counterpart
        $uri = $uri->withPath(substr($path, 0, -1));
        return $res->withRedirect((string) $uri, 301);
    }

    return $next($req, $res);
});
```

The middleware is okay with the other routes but for the group routes like above, unfortunately, it still returns 404.
