### ISSUE TITLE
Slim 3: debug mode

### ISSUE THREAD

**Issue by adambro** [slimphp/Slim#1707]
Would you support debug mode, like in Slim 2?

**Comment by mathmarques** [comment]
Do you mean show uncaught exceptions?

``` php
$app = new \Slim\App([
    'settings' => [
        'displayErrorDetails' => true
    ]
]);
```

**Comment by adambro** [comment]
I guess it's something I was looking for. Got stack trace on 500 error in Slim-Skeleton app as expected. What confused me is the for 404 it does not show stack trace, just HTML error page.

EDIT: would be good to have it documented somehow. Slim2 docs has got nice paragraph about debug mode.

**Comment by akrabat** [comment]
There's nothing to stack trace on a 404 - it means that the router failed to find a match.

We'd love a PR to [Slim-Website](https://github.com/slimphp/Slim-Website) :)
