### ISSUE TITLE
$request->getQueryParams() should not contain question mark

### ISSUE THREAD

**Issue by shamotj** [slimphp/Slim#1709]
I don't see any reason why getQueryParams method returns first parameter with question mark. Question mark is not part of query string, it just defines where it starts. I believe we should strip it.

**Comment by geggleto** [comment]
It does not ... 

Please see this unit test.
https://github.com/slimphp/Slim/blob/3.x/tests/Http/RequestTest.php#L537-L540

**Comment by shamotj** [comment]
My bad, I had error in my NGINX config. I had _/index.php_**?**_$is_args$args_ instead of _/index.php$is_args$args_.

**Comment by apolinux** [comment]
> My bad, I had error in my NGINX config. I had _/index.php_**?**_$is_args$args_ instead of _/index.php$is_args$args_.

thanks for this tip. I have searched in many sites and the solution was very simple. thanks again.
