### ISSUE TITLE
Slim 3: Document container keys used by Slim

### ISSUE THREAD

**Issue by ilijastuden** [slimphp/Slim#1717]
As it stands now, it's a minefield. I managed to step on `cache` (it's an add-on, but still a problematic name because HTTP cache is not the only type of cache that app will have) and `environment` already. 

After documentation, I think that next step would be to prefix Slim's system resources. Our app uses `environment` to determine whether we are in dev, staging or production environment, so we had to use a different key (`app_env`, sigh).

What's your option on this? Do you even see it as a problem that needs to be addressed?

**Comment by akrabat** [comment]
We'd love a documentation PR!

We can't change the key names until 4.0 is released.

**Comment by ilijastuden** [comment]
Yes, understood. No BC breaks until next major release. I'll see what I can do about the docs.
