### ISSUE TITLE
Mock method

### ISSUE THREAD

**Issue by iolloyd** [slimphp/Slim#1718]
https://github.com/slimphp/Slim/blob/3.x/Slim%2FInterfaces%2FHttp%2FEnvironmentInterface.php#L19

Is this method only for testing, and If so, would an extended interface in tests make more sense?

**Comment by designermonkey** [comment]
If I remember rightly, the method is only for testing. When we initially put the interfaces together, we just listed all the required functionality.

I reckon we don't even need the method to be defined in the interface at all, or even an extension of it as testing is testing and the method is not required to reproduce functionality in application specific derivatives.

**Comment by silentworks** [comment]
Yeah we should be able to get rid of that, but can't at the moment because of BC breaks it would cause. We are bound by that Contract for this moment.
