### ISSUE TITLE
Slim3 - cannot use it with phpdocumentor

### ISSUE THREAD

**Issue by fajnalowiec** [slimphp/Slim#1721]
Hi,
Unfortunately I am forced to stay with v2.6.2, cause I am using phpdocumentor package as well. The problem is that Slim3 requires pimple v3 while phpdocumentor requires cilex v1.0 and cilex requires pimple v1.0 thus 2 different version of pimple are suddenly required at the same time which is too much for poor composer/ php ;)

**Comment by ppetermann** [comment]
1) I don't see how that is a slim issue.
2) install phpdocumentor globally, not as a dependency of your project, your code does not depend on it.

**Comment by designermonkey** [comment]
@ppetermann is right on both counts. This isn't a Slim issue, and utilities like `phpdocumentor` should be installed globally.

Closing this issue. If you disagree, please re-open it with comments.
