### ISSUE TITLE
How can I pass external parameters to my controller?

### ISSUE THREAD

**Issue by fredw** [slimphp/Slim#1723]
Hello,

I am creating dynamic routes for my app and I don't know how can I pass a external data to my controller. You can look below a example:

``` php
$app = new \Slim\App(new \SlimAura\Container);
$urls = ['url1', 'url2', 'urlN'];

foreach ($urls as $url) {
    $app->get($url, '\MyController:index');
}
```

I tried to use a controller injection (example below), but doesn't work. The injected param is always the last element of my loop.

``` php
// ...
$container->set('\MyController', function () use ($container, $url) {
    return new \MyController($container, $url);
});
// ...
```

I would like to use a controller, not a clousure on my routes. It is the only way would be doing through closures, calling my controller within the clousure (example below)? 

``` php
//...
foreach ($urls as $url) {
    $app->get($url, function(ServerRequestInterface $request, ResponseInterface $response, array $args) use ($url) {
        $controller = new \MyController($container, $url);
       return $controller->index($request, $response, $args);
    });
}
```

**Comment by geggleto** [comment]
fredw, you can use constructor injection by defining your controller in the application container.

``` php
$container[MyController::class] = function ($c) { return new MyController($yourdeps,...); };

foreach ($urls as $url) {
    $app->get($url, MyController::class . ':index');
}
```

**Comment by fredw** [comment]
@geggleto I already did it using Aura.DI container as I said before:

``` php
// ...
foreach ($urls as $url) {
    $container->set('\MyController', function () use ($container, $url) {
        return new \MyController($container, $url);
    });
    $app->get($url, '\MyController:index');
}
```

Normaly, outside a loop with any other parameter it works, but not in a loop.
If I access the `/url1` and debug `$url` variable on my controller, the value is `urlN`.

**Comment by geggleto** [comment]
@fredw you are re-creating the MyController `count($urls)` times so it will only end up with the last `$url` in the constructor because of the way the application lifecycle works.

When $app->get() is called it simply registers the route with the disaptcher. Nothing is executed. Simply registered.

The application is executed when $app->run is called.

I have not been able to figure out what you are trying to do... It looks like some sort of static page controller?

This might work but it's kind of ugly...

``` php
foreach ($urls as $url) {
    $container->set('\MyController_'.$url, function () use ($container, $url) {
        return new \MyController($container, $url);
    });
    $app->get($url, '\MyController'.$url.':index');
}
```

You are now registering a "class" per URL, which contains that URL in the constructor. then Registering it. The new ClasssUrl Name is registered in the container so slim will find it and use it.

You will probably want to do something with `$url` if it has `/ or {}` in it...

**Comment by akrabat** [comment]
Register the controller once and add the multiple urls:

``` php
$container->set('\MyController', function () use ($container) {
    return new \MyController($container);
});
foreach ($urls as $url) {
    $app->get($url, '\MyController:index');
}
```

Now, in `index` you can grab `url` from the Request:

``` php
class MyController
{
    public function index($request, $response, $args)
    {
        $url = $request->getAttribute->getRoute()->getPattern();

        // do something different with $url and set $response

        return $response;
    }
}
```

**Comment by fredw** [comment]
@geggleto I don't want to create a controller per url. I have particular reasons to have unique controller for all this dynamics urls. This example I mentioned is just to understand the problem.

@akrabat Thank you, it works perfeclty. Here is the right called methods:

``` php
class MyController
{
    public function index($request, $response, $args)
    {
        $url = $request->getAttribute('route')->getPattern();
        // ...
    }
}
```

**Comment by designermonkey** [comment]
Closing as a solution was found.
