### ISSUE TITLE
Slim 3 getPath in subdirectory missing left most slash

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1724]
Example:
https://gist.github.com/geggleto/6cc2d792305fefc2bf64

http://dev/slim3/develop-testbed/public/yes/no => yes/no
http://develop-testbed.slim3.dev/yes/no => /yes/no

getPath is getting ltrim'd somewhere.

**Comment by akrabat** [comment]
This is intentional. If the leading `/` is missing, then the base path is set.

**Comment by tuupola** [comment]
Same as #1554.

Even though intentional it still is confusing for me that behaviour is different depending on whether Slim is installed in subfolder or not. I guess there will be lots of bug reports and support requests about this. In the end I just ended up doing something like following:

``` php
$path = "/" . $request->getUri()->getPath();
$path = str_replace("//", "/", $path);
```

**Comment by alexweissman** [comment]
> If the leading / is missing, then the base path is set.

Do you mean "base path is set" -> "leading `/` will be stripped"?

Also, what is the motivation behind this behavior?  Is this part of PSR-7?
