### ISSUE TITLE
How to use Carbon with Slim

### ISSUE THREAD

**Issue by AviRns** [slimphp/Slim#1725]
i have a method that returns date from oracle database.
like `return $this->sailpnos{'date_of_joining'}`

how can the returned date instantiate a Carbon object so that i can use
`return $this->sailpnos{'date_of_joining'}->format('M j, Y');`

Please help
Thanks

**Comment by juliangut** [comment]
Try with

``` php
return Carbon::instance($this->sailpnos{'date_of_joining'})->format('M j, Y');
```

**Comment by designermonkey** [comment]
The above is a good example.

I would suggest that the best way to get answers to implementation questions like these are to join in the IRC channel where fellow Slim PHP users could offer advice or help.

Details can be found here https://github.com/slimphp/Slim/wiki/IRC-Chat
