### ISSUE TITLE
Slim 3: [ask] Request and Response obj is accessible from route?

### ISSUE THREAD

**Issue by feryardiant** [slimphp/Slim#1740]
Hi,

Just notice that Slim route can actualy work like this.

``` php
$app = new Slim\App;

$app->get('/', function () {
    return $this->response->write('Hello, world');
});

$app->run();
```

Somehow I feel odd with this behaviour, and because slim put the request and response instance in [container](https://github.com/slimphp/Slim/blob/3.x/Slim/Container.php#L122-L149) and [bound it](https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L243) to route I don't think we could easly access it from any where.

Should we avoid this? or should we use something like this?

``` php
// Slim\Container::registerDefaultServices
if (!isset($this[ServerRequestInterface::class])) {
    /**
     * . . .
     */
    $this[ServerRequestInterface::class] = function ($c) {
        return Request::createFromEnvironment($c->get('environment'));
    };
}

if (!isset($this[ResponseInterface::class])) {
    /**
     * comment . . .
     */
    $this[ResponseInterface::class] = function ($c) {
        $headers = new Headers(['Content-Type' => 'text/html; charset=UTF-8']);
        $response = new Response(200, $headers);

        return $response->withProtocolVersion($c->get('settings')['httpVersion']);
    };
}
```

any thought?

Best :)

**Comment by silentworks** [comment]
It is indeed possible for someone to use Slim in such way, there are also other ways people can use Slim which could give such side effects but we think the documentation is clear enough to guide the user in using Slim correctly.

**Comment by feryardiant** [comment]
Hi @silentworks, Thanks for reply

> It is indeed possible for someone to use Slim in such way

If so, why do we need to pass them (request and response) as parameter in route callable?

P.S: Sorry for my english :grin: 

Best.

**Comment by AndrewCarterUK** [comment]
I strongly recommend not using the request and response entries in the container. The presence of these container entries is a design flaw, and I assume they'll be removed in the next major version.

Because PSR-7 request/response objects are immutable, if you are using middleware in your app the request and response objects in the container will not be valid. Again, pretend that these container entries do not exist! :)

**Comment by akrabat** [comment]
As @AndrewCarterUK says, they will be removed from the container in the next version.

**Comment by feryardiant** [comment]
Great. :+1:
