### ISSUE TITLE
Integration with Symfony DI Container

### ISSUE THREAD

**Issue by chippyash** [slimphp/Slim#1741]
Not an issue but thought you might like to know that there is now an integration with your V3 framework and the Symfony DI.  see [here](https://github.com/chippyash/Slim-Symfony-Dic).

It had me running about a bit, particularly as you have a dependency on the Container within the container itself (take a look at the examples/dic.slim.xml). But sorted now.

_if_ you get a chance, would appreciate any feedback you have.  It's possible I've missed something crucial. You can consider I hope, that what I've done as some kind of homage for your work. I use Slim and Symfony DI all the time.  Makes a very powerful combination.

**Comment by silentworks** [comment]
Thanks for this, we will be sorting out a section of the website for stuff like this soon. In the time being just post it on the Wiki of this repo.
