### ISSUE TITLE
extends from onther directory

### ISSUE THREAD

**Issue by ammoriz** [slimphp/Slim#1742]
In slim 2.x how can I extends default page into sub-directory page.
{% extends 'templates/default.php' %}

Thnaks

**Comment by silentworks** [comment]
I don't understand what you mean by this, are you using Twig? or is this using plain PHP? because your template file is `default.php` but you are using Twig's `{%` syntax.

**Comment by ammoriz** [comment]
I'm sorry my fault :) I have to post the Q on the right place :+1:
