### ISSUE TITLE
Slim cannot receive correct uri using IIS rewrite

### ISSUE THREAD

**Issue by mosullivan93** [slimphp/Slim#1744]
Please see if you can find the time to make the software more robust as it appears the latest version of IIS has caused problems. IIS can be detected in the SERVER_SOFTWARE environment variable. Apologies in advance if I've not formatted or submitted this info correctly. I thought it will help anyone in the meantime and I did my best to explain the issue.

My software:
Windows 10 64bit 10586.63 using IIS 10.0.10586 with PHP Version 5.5.31.

Problem:
Slim\Http\Uri.php does not parse the correct URI because it only looks for REQUEST_URI.

Description:
The REQUEST_URI server/env variable is not being passed through from IIS. If we use the recommended rewrite on http://www.slimframework.com/docs/start/web-servers.html then the original URI will be in HTTP_X_ORIGINAL_URL.

Workaround:
Change line 205 in Slim\Http\Uri.php from
        $requestUri = parse_url('http://example.com' . $env->get('REQUEST_URI'), PHP_URL_PATH);
to
        $requestUri = parse_url('http://example.com' . $env->get('HTTP_X_ORIGINAL_URL'), PHP_URL_PATH);

**Comment by geggleto** [comment]
I think this one slipped through our unit tests.

I just want to be clear.

On IIS 10, REQUEST_URI is not present in _SERVER[] when you are using rewriting?

**Comment by OptimusCrime** [comment]
Why IIS, WHYYYY

**Comment by silentworks** [comment]
@OptimusCrime because its a web server like all the others and some companies like having the backing of a larger company behind their server architecture choice.

**Comment by mosullivan93** [comment]
@geggleto @OptimusCrime @silentworks 
So funnily enough, my problem appears to have been caused by the fact that I was running PHP as a CgiModule instead of a FastCgiModule. The REQUEST_URI is present when I configured it correctly.

Can confirm everything is working under the standard install of Slim with this handler mapping configured correctly.

My bad.

**Comment by silentworks** [comment]
Happy to hear that @miitchyy, I will close this one out on that note.

**Comment by geggleto** [comment]
@miitchyy oh thank god. I was going to have to install some form of windows iis 10 to test the fix ;(

**Comment by feryardiant** [comment]
I think that

> my problem appears to have been caused by the fact that I was running PHP as a CgiModule instead of a FastCgiModule. The REQUEST_URI is present when I configured it correctly.

need to be documented.
