### ISSUE TITLE
Multiple optional parameters path_for() ?

### ISSUE THREAD

**Issue by rss1** [slimphp/Slim#1746]
Hi there,

I need to create route with few optional parameters. I'm doing the following, using FastRoute's syntax.

``` php
    $app->get('/businesses[/{state}[/{city}[/{page}]]]', function ($request, $response, $args) {
```

As I implemented twig templates in my project I can say that everything is working fine (thanks!), everything but this route and links to it. I use following function:

``` php
{{ path_for('businesses', { 'page': 2 }) }}
```

The url created is <i>localhost/.../businesses<i>. As if the {page} part is ignored.

In this case I need to use only one of optional parameters and NULL the others (or simply ignore it). It works fine If I put all three variables as function parameter, but not single or two.

``` php
{{ path_for('businesses', { 'page': 2, 'city':'somecity','state':'somestate' }) }}
```

The route should be generated for following cases:
businesses
businesses/1
businesses/somestate
businesses/somestate/1
businesses/somestate/somecity
businesses/somestate/somecity/1

Is there any way to make it working correctly? Or am I misunderstanding basics of slim routing?

**Comment by geggleto** [comment]
This seems like it working correctly, because in your route you have nested conditionals.
There is no way in Fastroute to bypass the first 2 and just have the 3rd.
You could not have business/3 with the route pattern you provided.
in order to use the page... you must have the previous 2 parameters as well.

**Comment by rss1** [comment]
Could you suggest any solution, which allows using parameters as I want? 
I tried to find some more Fastroute documentation regarding multi optional parameters but the example provided was the only one I stumbled upon.

**Comment by geggleto** [comment]
I am mostly certain that what you are trying to do.. cannot be done... 

There's no way to know that business/1 is suppose to be page rather than state or city.

You could try something like this...

``` php
$app->get('/businesses[/{state}][/{city}][/{page}]', function ($request, $response, $args) {
```

But that is only going to get you so far... /businesses/0/0/1 == > /businesses/1

**Comment by mathmarques** [comment]
This is a Fastroute issue. 

But you can handle it with some logic.

``` php
    $app->get('/businesses[/{arg1}[/{arg2}[/{arg3}]]]', function ($request, $response, $args) {
```

If only the first arg is set, this arg is the page
If the first and second are set, the first is city and second is page 
etc...

**Comment by akrabat** [comment]
As @geggleto says, optional parameters work left to right. You can't omit ones to the left.

**Comment by abr4xas** [comment]
Hi there, my issues is relate to this.

My route to view a post

``` php
$app->get('/post[/{id:[0-9]+}[/{name:[A-Za-z]+}]]',
 function ($request, $response, $args) 
 use ($container) {
....
})->setName('post.detail');
```

When i try to access this url: `post/1/lorem-ipsum-dolor-sit-amet-con` get `404`

Any advice?

ps: i don't know how access this 2 params :(

**Comment by OptimusCrime** [comment]
You don't include `-` in your regex for the name param? Should be something like this `[A-Za-z\-]+`

**Comment by abr4xas** [comment]
This work for me :smile: 

``` php
$app->get('/post/[{id:[0-9-]+}/[{name:[A-Za-z-]+}]]', 
function ($request, $response, $args)  
use ($container) {

    echo $args['id'];
    echo '<br>';
    echo $args['name'];

})->setName('post.detail');
```
