### ISSUE TITLE
Add Lighttpd rules to README

### ISSUE THREAD

**Issue by paulyg** [slimphp/Slim#175]
I got Slim working with Lighttpd and figured I would contribute back what I came up with. I am using the following in my `lighttpd.conf`:

```
url.rewrite-if-not-file = ("^/slimapp/.*" => "/slimapp/index.php")
```

where `slimapp` is a subfolder under my document root. Note that `url.rewrite-if-not-file` requires Lighttpd 1.4.24 and up.

It would be nice to have that in the docs after the Apache rewrite rules for those of us using other servers.

I saw an issue dealing with rewrite rules for nginx in in the tracker here so It'd be nice to have that docs too.

**Comment by codeguy** [comment]
Agreed. I'll likely add this to the Slim-Extras repository, and in the README for the main repository. I'm admittedly not that familiar with anything other than Apache (so far) hence only the Apache-specific instructions :) I'll try to incorporate this soon. Thanks!

**Comment by codeguy** [comment]
Can you test the following for a Slim app at the top of your document root?

```
url.rewrite-if-not-file = ("^" => "/index.php")
```

**Comment by paulyg** [comment]
Yes, it worked.

**Comment by codeguy** [comment]
Thanks! I'll move the Lighttpd setup into the README soon.
