### ISSUE TITLE
Slim 3 access response/request object from another class

### ISSUE THREAD

**Issue by pokakhoaitay** [slimphp/Slim#1750]
I have a Utils class, I need to use $response/$request from Slim 3 to use some useful methods (ex: $request->getUri()->getPath(), etc.), how can I access to $request or $response like this or any solution for me to write a helper class like this:

<pre>
class Utils
{

    public static function AllowRoutePass($request, $response)
    {
        //How can i access $request, $response here
        $reqMethod =$request->getUri()->getPath();
        if (in_array($reqMethod, AppConfig::IGNORE_ROUTES))
            return true;
        return false;
    }

}

</pre>

**Comment by tuupola** [comment]
What you describe sounds like a good candidate for [middleware](http://www.slimframework.com/docs/concepts/middleware.html).

**Comment by pokakhoaitay** [comment]
A also create a middleware (referrence to this [https://github.com/akrabat/slim3-skeleton/blob/master/app/dependencies.php](url)  ):
- Index.php
  
  <pre>
  $container = $app->getContainer();
  $container['xcore\AppCore']=function ($c){
  return new xcore\AppCore($c);
  };
  </pre>
- Utils.php
  <pre>
  use Psr\Http\Message\ServerRequestInterface as Request;
  use Psr\Http\Message\ResponseInterface as Response;
  final class AppCore
  {
  function __construct($c)
  {
  }
  public function AllowRoutePass(Request $request, Response $response)
  {
      $reqMethod =$request->getUri()->getPath();
      if (in_array($reqMethod, AppConfig::IGNORE_ROUTES))
          return true;
      return false;
  }

}
</pre>

But i still have error and unable access $request/$response object.

Anyway, any solution for me that access $request/$response object without create a middleware?

Thanks!

**Comment by akrabat** [comment]
I don't understand the problem. The `$request` object is a parameter to the `AllowRoutePass` method, so pass it in when you call that method.

Please show the code used to call `AllowRoutePass`.

**Comment by pokakhoaitay** [comment]
I have a middleware, similar to this:

<pre>
&lt;?php
class ExampleMiddleware
{
   public function __invoke($request, $response, $next)
    {
        //I want to use some methods from my own Helper class (maybe used in other projects) at here. How can i use $request, $response object in my class?
        //Ex: MyHelper->CheckSomethingWhichNeedRequestAndResponseObject();
        //I don't want to pass parameters to my helper methods like this: 
        //Ex: MyHelper->CheckSomethingWhichNeedRequestAndResponseObject($request, $response);
        $response = $next($request, $response);
        $response->getBody()->write('AFTER');
        return $response;
    }
}
</pre>

My problem is how can i re-use my helper class but still can access $request, $response from Slim 3 framework. In other word, I want MyHelper class able to use any where-any time.
Please give me advice!
Thank you!

**Comment by mbretter** [comment]
in your code snippet you are passing the container to the constructor of your AppCore class:

```
final class AppCore
{

function __construct($c)
{
    $this->request = $c->request;
}
```

your pass directly the request object to your constructor:

```
$container = $app->getContainer();
$container['xcore\AppCore']=function ($c){
return new xcore\AppCore($c->request);
};

function __construct($request)
{
```

**Comment by pokakhoaitay** [comment]
oh, you mean i should create a  $request variable in my class and assign to it from the consrtuctor. and the methods in my class will read the $request variable. Sound like my class now not a 'helper' class, it's a 'dependency'. Because I want to make my class look like 'portable', it should be have not any variable inside, even i want the methods in my class are static, that mean i no need create an instance whenever i use my class. hmm...maybe i can't do that in Slim!!?

Thank everyone, I have workaround by implemented my class like this: [https://github.com/brtriver/slim3-controller/blob/master/src/Controller/Controller.php](url), like @mbretter suggested and more understand about @akrabat's  slim-skeleton project. It working now. But it is not my intention as my describe above. Perhaps i temporary implement my class like that first.

**Comment by geggleto** [comment]
@mbretter You should never get the request from the container. ever. The Request is set in the container once, and once middleware is applied is no longer the valid current request.

**Comment by clemens-tolboom** [comment]
> You should never get the request from the container. ever. The Request is set in the container once, and once middleware is applied is no longer the valid current request.

@geggleto the documentation has no warning for this. Can we improve this somehow?

I checked here https://www.slimframework.com/docs/v3/concepts/di.html#required-services

I need the applications `basepath` and both `request` and `router` provides this. Guess the latter is best.

```php
$router = $app->getContainer()->router
```

[edit]But that has not getter for basePath :-([/edit]
