### ISSUE TITLE
Slim 3 - where is \Slim\Log ?

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#1751]
So where is it ? i need \Slim\Log

there is nothing here [http://www.slimframework.com/docs/start/upgrade.html](http://www.slimframework.com/docs/start/upgrade.html)

**Comment by tuupola** [comment]
Slim 3 does not include logger. Instead you can use [Monolog](https://github.com/Seldaek/monolog) or something similar. [Initialise the logger into a container](https://github.com/tuupola/slim-skeleton/blob/master/config/logger.php) and then you can call it with something like:

``` php
$app->get("/", function ($request, $response, $arguments) {
    $this->logger->debug("Hello world!");
});
```
