### ISSUE TITLE
Request objects in the Route parameter and Container do not match 

### ISSUE THREAD

**Issue by ose1955** [slimphp/Slim#1754]
The `Request` object in the `Closure` parameters of the `Route` does not match with the `Request` in the `Container`. Some `Middleware` such as **CSRF** pass data via `Request` object and application has to store `$request` instead of using `Container`. 

```
$app->get('/csrf',function($request, $response, $args) {
    $request_container = $this->get('request');
    var_dump($request->getAttributes());
    var_dump($request_container->getAttributes());

});
```

**Comment by akrabat** [comment]
Yes. Do not use the one in the container. It shouldn't be there.
