### ISSUE TITLE
Create a TodoBackend implementation using Slim

### ISSUE THREAD

**Issue by moredip** [slimphp/Slim#1756]
Hi,

I'm a curator for [todobackend.com](http://todobackend.com), a community resource showing examples of how to build the same simple HTTP API using different frameworks. We'd love to get a Slim implementation contributed - in fact we have an [issue filed](https://github.com/TodoBackend/todo-backend-site/issues/12) for it! We have a Symfony2 implementation, and it would be nice to see how Slim differs.

Creating a todobackend implementation usually only takes a hour or two for someone experienced in the framework they're using. There's lots more information about how to do it on the todobackend site [here](http://todobackend.com/contribute.html).

**Comment by tuupola** [comment]
I can take a look at it. Is there and todo API spec somewhere or do I just read the source of other implementations? Looking at the Sinatra example that is pretty much how I do my APIs. One difference being I return `200` from DELETE actions instead of `204`.

**Comment by tuupola** [comment]
Needs some polishing but [passes tests](http://todobackend.com/specs/index.html?http://slim3-todo-backend.appelsiini.net/todos).

https://github.com/tuupola/slim-todo-backend

**Comment by tuupola** [comment]
This can be closed.
