### ISSUE TITLE
Calling an external api

### ISSUE THREAD

**Issue by pokakhoaitay** [slimphp/Slim#1757]
Good day,
 I would like to make a HTTP call to an external API. 
For example: 

<pre>
$app->get('/get-blah', function ($request, $response) {
    $blahFromAPI=//How can i receive the result from an external endpoint api IN SLIM 3(Ex: api.fake.com/blahblah)
    return $response->withJson(['data' => $blahFromAPI]);
});
</pre>

Is there a way to do this using Slim 3?

Thanks in advance!

**Comment by akrabat** [comment]
Use an http client. e.g. PHP streams via file_get_contents(), Guzzle or similar.

**Comment by lplume** [comment]
@akrabat is right, consider one thing, choosing a "lowlevel" tools such as streams, give you complete control over the request but it requires to tweak everything. Using third party client like guzzle (which is great) usually it makes things simplier.

**Comment by pokakhoaitay** [comment]
Exactly what i want. Can you please close this topic. Thank you!
