### ISSUE TITLE
Small example mistake in the documentation

### ISSUE THREAD

**Issue by doobdargent** [slimphp/Slim#176]
Hey there.
I didn't use Slim yet but I'm reading the documentation and it seems pretty nice. So I might use it in the future.

I found a little mistake in the [doc](http://www.slimframework.com/documentation/develop#slim-scope-resolution):

---

Now it works as expected. If you are using PHP < 5.3, you can use Slim::getInstance() instead.
$app = new Slim();
$app->get('/foo', function () {
    $app = Slim::getInstance();
    $app->render('foo.php');
});

---

But in PHP < 5.3 there is no anonymous function as you said in the [learn page](http://www.slimframework.com/learn).

Keep up the good work ;)
dOob d'Argent

**Comment by codeguy** [comment]
Nice catch! I'll get this fixed later tonight after work.

**Comment by codeguy** [comment]
Fixed
