### ISSUE TITLE
Write to error_log when displayErrorDetails is false

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#1761]
When `displayErrorDetails` is false (the default), the ErrorHandler doesn't display any information. It should write to the `error_log` in this situation so that people who do not know about the `displayErrorDetails` setting can see that that Slim knows what went wrong. 

Bonus points for writing a note about the `displayErrorDetails` setting into the error_log too.

**Comment by opengeek** [comment]
Yes—1000% yes. Also, clear documentation on settings like this is needed badly.

**Comment by akrabat** [comment]
The docs at http://www.slimframework.com/docs/handlers/error.html are fairly clear I think? If you think that they can be improved, can you raise an issue (or PR!) at https://github.com/slimphp/Slim-Website?

**Comment by opengeek** [comment]
Hmmm — I guess I was looking for a section on what settings are available for Slim period. It isn't intuitive to look at the error handler documentation for out-of-the-box configuration settings IMO.
