### ISSUE TITLE
Why i am getting the message "The requested method PUT is not allowed for url X" ?.

### ISSUE THREAD

**Issue by ismnoiet** [slimphp/Slim#1773]
I'm using Slim3 for a little while now and i'm enjoying it BUT BUT i have a problem with **PUT,DELETE** routes i can't make it work. For the others HTTP verbs like GET and POST it works like a charm and there is no problem.
I've tried the straightforward example :

``` php
$app->put('/home',function($request,$response,$args){
    // some code here.
});
```

I've tried using `map` syntax for example : 

``` php
$app->map(array('PUT'),'/home',function($request,$response,$args){
    // some code here     
});
```

i've also tried without and  with `.htaccess` in place with the following content 

```
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

Any suggestion or help would be appreciated.

**Comment by ismnoiet** [comment]
I've tried a fresh new installation with the previous `.htaccess` in the same level as `index.php` 
and it worked for some reasons that i don't know.
**But** i want to hear an answer from you about the reasons  that may cause this problem and thank you.

**Comment by geggleto** [comment]
you need to have the .htaccess in the same directory as your front controller file [index.php]

**Comment by ismnoiet** [comment]
Yes , but  what i can't understand now is that even if remove `.htaccess`  it is working also !!!

**Comment by geggleto** [comment]
Likely because you aren't using Apache :)

**Comment by ismnoiet** [comment]
@geggleto i'm using apache.

**Comment by OptimusCrime** [comment]
What web server are you using?

**Comment by ismnoiet** [comment]
APACHE.

**Comment by OptimusCrime** [comment]
Then it is indeed very weird. I suggest closing as not an issue with Slim. There is an error in the setup or configuration somewhere.

**Comment by ismnoiet** [comment]
Yes you're right @OptimusCrime

**Comment by akrabat** [comment]
How are you testing? I've checked my local installation.

``` php
$app->put('/home', function($request,$response,$args){
    return $response->write(var_export($request->getParsedBody(),true));
});
```

Test via curl:

```
curl -X PUT -d '{"test":"foo"}' -H "Content-type: application/json" http://localhost:8888/home
```

Output:

```
array (
  'test' => 'foo',
)
```

**Comment by ismnoiet** [comment]
I'm using **postman for chrome** and sometimes **curl**.
Now it is working properly :)
