### ISSUE TITLE
How to Direct Routing basePath not using /index.php or File Name as start indexing

### ISSUE THREAD

**Issue by pentagonal** [slimphp/Slim#1775]
How to make Router detect routing index as '/' and prevent use '/index.php' as start of routing base path indexing?

``` php
/**
 * Example 
 */
$url = 'https://domain.com/index.php/aa';
// will never be match as route of :
$slim->get('/aa', closure $fn);

// but it will be detect as itself
$slim->get('/index.php/aa', closure $fn);

```

for easy way, I was comment on variable of $virtualpath on `\Slim\Http\Uri` class 

``` php
public static function createFromEnvironment(Environment $env)
{
   ....
    if ($basePath) {
        //  $virtualPath = ltrim(substr($requestUri, strlen($basePath)), '/');
    }
   ....
}
```

Maybe any other methods or setting to implement it without comment it ?
if nothin , maybe add some feature of configuration that use context of use script file name as start indexing or not, to prevent duplicate URL acess.

**Comment by OptimusCrime** [comment]
Do you use URL rewrites? That should fix the problem.

**Comment by pentagonal** [comment]
@OptimusCrime yep I use URL rewrites
But not all fix problems,
client also allowed access domain.com/index.php/a -> same with domain.com/a
URL rewrite is not better idea to handle this, if script still detect /index.php ( or script name) as basePath

and now I found how to make it without change the core, to change thiis case we must change the Environment of SCRIPT_NAME from uri Environment set it on `\Slim\App` container setting
because the uri environment will be use as Script name if first of word of REQUEST_URI and SCRIPT_NAME on position of 0 

``` php
/**
 * on line 209 \Slim\Http\Uri
 * variable take from slim environment
 */
...
if (stripos($requestUri, $requestScriptName) === 0) { 
...
```
1. first we could set 

``` php
// set additional cached variable for $_SERVER
$reqServer = $_SERVER;
// add first of slash on keyname : SCRIPT_NAME
$reqServer['SCRIPT_NAME'] = "/{$_SERVER['SCRIPT_NAME']}";
/**
 * Add Overide on Application initial
 * set container request with new value of \Slim\Http\Request
 *  with new values 
 */
$app = new \Slim\App(
    array(
        'settings' => array(
           // .. set your settings 
        ),
       // set container request as custom $_SERVER , that only change SCRIPT_NAME 
        'request' => \Slim\Http\Request::createFromEnvironment(
            \Slim\Http\Environment::mock(
                $reqServer
            )
        )
    )
);
```

this help for use path as basePath of Uri Routing Segmentation.
after route parsed (inside Route not in route group - if use group route make sure set after route mapping) , you could u re - set the Request Environment with 

``` php
// example of route mapping
$app->get('/', function() use($app) {
    $container = $app->getContainer();
    $container['request'] = \Slim\Http\Request::createFromEnvironment(
        \Slim\Http\Environment::mock(
              $_SERVER
        )
    )
   ... call next
});
$app->run();
```

this my way :laughing: 
how about other?
or if you dont want re - set the environment use original GLOBALS of $_SERVER for SCRIPT_NAME
and if you want use SCRIPT_NAME from environment you could use replace double slash with single slash on start of value.

**Comment by JoeBengalen** [comment]
How about middleware that removes the index.php from the url?

**Comment by pentagonal** [comment]
@JoeBengalen BTW I was very new on Slim 3 , maybe just 2 days work (till now - started 3 hours before posted this issues).
`\Slim\App::run` , it will be direct to processing request & response to `\Slim\App::proccess() , 
on process method , middleware stack called after`\Slim\Http\Uri` (that take from request class) .
on \Slim\App::proccess method with line contain :

``` php
... checking request uri basePath & router setBasePath Method
$router->setBasePath($request->getUri()->getBasePath());
```

But maybe best recommendation ffor me :)
I will try set uri base Path on middle ware :)

**Comment by pentagonal** [comment]
@JoeBengalen : 
is use this for middleware 

``` php
$app->add(function ($request, $response, $next) {
       // clone environment , using clone prevent to overide
    $env = clone $this->environment;
    $env->set('SCRIPT_NAME', '/'.$env->get('SCRIPT_NAME'));
    $this->request = \Slim\Http\Request::createFromEnvironment($env);
    $response = $next($this->request, $response);
    return $response;
});
```

not all nested  `\Slim\Http\Request::uri` property setted with same value ,
but maybe this enough,
because application getting URI object from `\Slim\Container->Request->getUri()`

thanks for suggestion :)
