### ISSUE TITLE
The actual callable is not passed to InvocationStrategy since introduction of DeferredCallable in Slim 3.2.0

### ISSUE THREAD

**Issue by astax-t** [slimphp/Slim#1785]
Since introduction of `DeferredCallable` in Slim 3.2.0, the actual controller's callable is not given to the class implementing InvocationStrategy (the one set in `$container['foundHandler']`)

This makes it impossible to use reflection to find what are actual expected parameters.

I'm trying to use a custom `InvocationStrategy` that would match controller parameters names to route parameters - similar to the way it's done in Symfony HttpKernel. This was working in Slim 3.1.0, but not in 3.2.0.

**Comment by astax-t** [comment]
The pull request https://github.com/slimphp/Slim/pull/1783 would help to mitigate this, if accepted. I'd be able to retrieve the resolved callable and get its parameters using reflection.

But really it would be better to call the custom InvocationStrategy from DeferredCallable instead of just passing arguments given to `DeferredCallable ::__invoke()`

**Comment by irfanevrens** [comment]
I am agree with @astax-t and I also use a custon InvocationStrategy.

**Comment by michaelboke** [comment]
Having the same issue since 3.2 my auto wiring isn't working anymore.

@irfanevrens i added a pull request on #1783 that now passes the resolvedCallable result to the foundHandler. Restoring the old behavior.

**Comment by akrabat** [comment]
Can you provide an example of code that's no longer working please?

**Comment by astax-t** [comment]
Sure. It's not the minimal code to replicate the problem, but pretty much copied from HttpFoundation:

```
class CompatibilityInvocationStrategy implements InvocationStrategyInterface
{
    public function __invoke(
        callable $callable,
        ServerRequestInterface $request,
        ResponseInterface $response,
        array $routeArguments
    )
    {
        if (is_array($callable))
        {
            $r = new \ReflectionMethod($callable[0], $callable[1]);
        } elseif (is_object($callable) && !$callable instanceof \Closure)
        {
            /** @noinspection PhpParamsInspection */
            $r = new \ReflectionObject($callable);
            $r = $r->getMethod('__invoke');
        } else
        {
            $r = new \ReflectionFunction($callable);
        }

        $arguments = $this->doGetArguments($request, $response, $routeArguments, $r->getParameters());

        $result = call_user_func_array($callable, $arguments);

        return $result;
    }

    protected function doGetArguments($request, $response, $attributes, array $parameters)
    {
        $arguments = array();
        foreach ($parameters as $param)
        {
            /** @var \ReflectionParameter $param */
            /** @var \ReflectionClass|null $class */
            $class = $param->getClass() ?: null;
            if ($class && $class->isInstance($request)) {
                $arguments[] = $request;
            } elseif ($class && $class->isInstance($response)) {
                $arguments[] = $response;
            } elseif (array_key_exists($param->name, $attributes)) {
                $arguments[] = $attributes[$param->name];
            } elseif ($param->isDefaultValueAvailable()) {
                $arguments[] = $param->getDefaultValue();
            } else {
                throw new \RuntimeException(sprintf('Controller requires that you provide a value for the "$%s" argument (because there is no default value or because there is a non optional argument after this one).', $param->name));
            }
        }
        return $arguments;
    }
}
```

But there is another PR to fix this problem. Maybe it's even better.

**Comment by akrabat** [comment]
Please test 3.x and let me know if this is now solved.

**Comment by astax-t** [comment]
Tested and is working correctly now

**Comment by akrabat** [comment]
Version 3.2.1 released now. Thank you very much for reporting this issue.
