### ISSUE TITLE
Weird route match

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#1786]
Hello. Im trying to understand why such URLs 
domain.com/api/v1/galleries/:1342
domain.com/api/v1/galleries/:65/:543
are always matched as home route.

I should get a 404 because _:1342_ is not _1342_.

My routes:
`$app->get('/galleries', 'App\Http\Controllers\GalleriesController:galleries')
    ->setName('galleries');

$app->get('/galleries/{id:[0-9]+}', 'App\Http\Controllers\GalleriesController:gallery')
    ->setName('gallery');

$app->get('/', 'App\Http\Controllers\HomeController:getIndexRoute')
    ->setName('home');`

Thanks.

**Comment by OptimusCrime** [comment]
They dont match any of the gallery routes? `'/galleries/{id:[0-9]+}'` matches `/galleries/[id here]`, such as `/galleries/1` or `/galleries/2345212`. Adding a colon before the ID does not match the regex.

**Comment by ghost** [comment]
/galleries/2 matches a gallery
/galleries/:2 matches home instead of 404

**Comment by ghost** [comment]
I have updated slim from 3.0.0 to 3.2.0 and everything works as expected. Now I get a 404.

**Comment by OptimusCrime** [comment]
So....? Fixed?

**Comment by ghost** [comment]
Yes. In version 3.2.0 it is fixed. Thanks for conversation :)
