### ISSUE TITLE
getHeader(s) format

### ISSUE THREAD

**Issue by betweenbrain** [slimphp/Slim#1788]
I'm wondering why Slim 3.2.0 returns an array of arrays with `getHeaders`, each inner array containing one key/value pair that contains a header,  whereas PHP returns an array of the headers. I've tested this by adding two custom headers and both Slim and PHP return an identical comma separated string.

A good example of this can be seen with #1784

**Comment by geggleto** [comment]
PSR-7. even when you grab a single header line, it will return an array. This is by design.

Reference.
https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L63-L68

`
@return array Returns an associative array of the message's headers. Each
     *     key MUST be a header name, and each value MUST be an array of strings
     *     for that header.
`

**Comment by betweenbrain** [comment]
Thanks! I wasn't aware of that.
