### ISSUE TITLE
I as understood the app allow to use any of container which implements ..

### ISSUE THREAD

**Issue by parfumix** [slimphp/Slim#1791]
I as understood the app allow to use any of container which implements container interface  standart *https://github.com/container-interop/fig-standards/blob/master/proposed/container.md.

There is a problem by default slim container register DefaultServiceProvider in container constructor which broke all the app when is trying to use another container.

Will be ok if the service providers will be send as args to the app constructor or will be resigistered via addProviders method which will let me change without problem container. 

Thx..

**Comment by akrabat** [comment]
The constructor to `Slim\App` takes a Container object. You can pass in any container that implements container-interop and has the services that Slim requires registered with it. 

Does this not work for you?

**Comment by parfumix** [comment]
If you look to the \Slim\Container class you will see in the constructor that part of code
`$this->registerDefaultServices($userSettings);`

If think that code broke SOLID - the "S" principle. For example i was try to pass League/Container which implement container-interpop and all the application is broken because in \Slim\Container is injected DefaultServiceProvider which boot required settings.

That's why i propose to register service providers using App class.

Thx.

**Comment by akrabat** [comment]
I don't understand why you care about \Slim\Container if you're supplying your own container to App's constructor.

**Comment by parfumix** [comment]
K, i pass my container 
`
$app = (new App(
    new League\Container\Container
));

$app->get('/hello/{name}', function ($request, $response, $args) {
    return $response->write("Hello " . $args['name']);
});

$app->run();
`

i got error like `Fatal error: Uncaught League\Container\Exception\NotFoundException: Alias (router) is not being managed by the container in ...`

**Comment by akrabat** [comment]
You have to provide your own registration for all the services that Slim needs to operate. 

See this example that integrates Zend\ServiceManager with Slim: https://github.com/akrabat/rka-slim-zfsm-container/blob/master/src/Container.php

**Comment by akrabat** [comment]
This is documented at http://www.slimframework.com/docs/concepts/di.html#required-services

**Comment by parfumix** [comment]
Thanks, results that the container register needed services. Why don't giving that responsabillity to the Application class?

**Comment by akrabat** [comment]
We can't put it on the Application class as the container-interop interface doesn't specify how to register a service with the container.

**Comment by akrabat** [comment]
Note that if your container supports registering services in the same way as Pimple, then you can use our `DefaultServicesProvider`:

``` php
$container = new \Some\DiC()
$defaultProvider = new \Slim\DefaultServicesProvider();
$defaultProvider->register($container);

$app = new \Slim\App($container);
```
