### ISSUE TITLE
Uploaded files contains an empty UploadedFiles …

### ISSUE THREAD

**Issue by Melindrea** [slimphp/Slim#1792]
… when no file is supplied.

That is, I have a form for uploading images, and sometimes we don't want an image. Reading the comment on `$request->getUploadedFiles()`: `@return array An array tree of UploadedFileInterface instances; an empty array MUST be returned if no data is present` suggested to me that I should be able to go `if (! empty($request->getUploadedFiles())` and then move into what I do with the images. However, that's not working. Instead, it returns:

```
Array ( [file] => Array ( [0] => Slim\Http\UploadedFile Object ( [name:protected] => [type:protected] => [size:protected] => 0 [error:protected] => 4 [sapi:protected] => 1 [stream:protected] => [moved:protected] => [file] => ) ) )
```

Am I misunderstanding something? How are you intending to check whether a file was uploaded or not? I can check `$_FILES`, but I prefer working with as few globals as possible.

Also, thank you for your good work, I'm enjoying using Slim.

**Comment by mathmarques** [comment]
$_FILES will be parsed as an array of UploadedFileInterface

You'll need to check the same way you would do with $_FILE.
Something like:

``` php
$image = $request->getUploadedFiles()['file']; //your upload image form name is file, right?
if($image->getError() != UPLOAD_ERR_OK){
    //You don't have an image :)
}
```

If you could have more than 1 image named `file`: `$image` will be an array of `UploadedFileInterface`

**Comment by Melindrea** [comment]
Thanks =) Alright, so I’d misunderstood what the interface demanded.

This can be closed
