### ISSUE TITLE
How can i store config data and use it from a model?

### ISSUE THREAD

**Issue by rubobaquero** [slimphp/Slim#1795]
Hello,

I want to store some config vars in my project so i can use them in any class. For example, my Amazon Web Services secret keys. Which is the best method to do that in Slim 3?

I think that this kind of info should be in the $container, but i don´t know how to access to the container outside of the controllers. For example, if I need de AWS keys inside an Eloquent ORM model, How do i get them?

Thanks in advance!

**Comment by geggleto** [comment]
You can put them into the 'settings' key in the container.

``` php
$container = $app->getContainer();
$container['settings']['AWS'] = [...];
```

For Eloquent.... I am not sure how to inject additional information.. I do know they have their own container, so you can likely put it there.

**Comment by rubobaquero** [comment]
I geggleto, thanks for your quick answer. My problem is how to access them from an Eloquent Model (or any other class that i use on my code).

For example, with the action controllers i know that i have to pass the container to the constructor:

``` php
final class ApiAction
{   
    protected $container;

    public function __construct($container){
        $this->container = $container;
    }
}
```

But, how i do the same in other classes where i can´t pass the $container as an argument to the constructor? For example, in my User model class:

``` php
class User extends \Illuminate\Database\Eloquent\Model
{
    public function send_activation_mail()
    {
        // How do i access here to $container['settings']['AWS'] ???
    }
}
```

Thanks again in advance for your help!

**Comment by geggleto** [comment]
When you bootstrap Eloquent it does create a container.

https://github.com/illuminate/database

``` php
// Set the event dispatcher used by Eloquent models... (optional)
use Illuminate\Events\Dispatcher;
use Illuminate\Container\Container;
$capsule->setEventDispatcher(new Dispatcher(new Container));
```

I have no idea how you can load the info from Slim's container into Eloquent's. That would be a question for them

**Comment by rubobaquero** [comment]
Hi geggleto,

Thanks once again for your answer. The Eloquent ORM is just an example, but this is happening to me with other classes. What i would like to know is if does exist any way to load the container info without having to pass it as an argument to the class constructor or to the class method. In other frameworks there is a static $config var or similar so you can access it from any part of the code.

**Comment by akrabat** [comment]
@rubobaquero, There isn't a static as that creates global coupling. The correct way to handle dependencies, including settings is to inject via the constructor.

**Comment by akrabat** [comment]
@rubobaquero.

Of course, if you don't care about this, you can always do:

``` php
global $app;
$settings = $app->settings;
```

I wouldn't advise this, though!

**Comment by tflight** [comment]
You _could_ also pull in something like [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) and load them into an environmental variable, which also gives you the ability to exclude the file with your credentials from version control, but that has its [own issues](https://blog.fortrabbit.com/how-to-keep-a-secret).

**Comment by geggleto** [comment]
@rubobaquero I think there are 3 solutions to your problem.

1) Service Location [phpdotenv]
2) Dependency Injection [below]
3) Globals [akrabat]

With DI,  you inject your information into an Object either via Setter injection or Constructor injection.

``` php
$model->set($dependency); //setter injection
new Model($dependency); // constructor injection
```

**Comment by tflight** [comment]
Pick number 2! :+1:

**Comment by rubobaquero** [comment]
Hi,
Thanks a lot to everybody for giving me different options to choose for. I think i will choose the second one proposed by geggleto. We already have a solution for not storing the passwords on the VCS. The problem is that i am used to code with Kohana Framework (that have a Kohana::$config var) and i was looking for a similar way of doing things. One of the first things that i learned when i started coding is that using global variables is a bad practice, but never heard anything about static class vars and the global coupling problem that mentions akrabat.

**Comment by akrabat** [comment]
Item 2 is the preferred way in Slim
