### ISSUE TITLE
PSR-7 compliance: Request::getAttributes() is always empty

### ISSUE THREAD

**Issue by aimeos** [slimphp/Slim#1797]
We are trying to access the URL attributes (e.g. `/{site}/update` -> "site" parameter) from objects that don't have direct access to the `$args` parameter when adding a route. PSR-7 requests has the getAttributes() method to return such values but it seems to be never populated in Slim.

Where does Slim need to be changed to push the route attributes into the PSR-7 request?

**Comment by akrabat** [comment]
What code are you using?

**Comment by geggleto** [comment]
~~@aimeos you need to change the default foundHandler~~

**Comment by aimeos** [comment]
We are using Slim 3.1. For the unit tests, we tried to create a mock environment like this:

```
$app = new \Slim\App( array(
    'settings' => array( 'determineRouteBeforeAppMiddleware' => true )
) );

$app->group( '/{site}/', function() {
    $this->map(['GET'], 'detail/{d_prodid}', function( $request, $response, $args ) {
        return \Aimeos\Catalog::detailAction( $this, $request, $response, $args );
    })->setName( 'aimeos_shop_detail' );
} );

$c = $app->getContainer();
$env = \Slim\Http\Environment::mock( array(
    'REQUEST_URI' => '/unittest/detail/1'
));
$c['request'] = \Slim\Http\Request::createFromEnvironment( $env );
$c['response'] = new \Slim\Http\Response();

return $app->run( true );
```

We haven't found any code in Slim3 that populates the request attributes at some point, so

```
$app->getContainer()->get( 'request' )->getAttributes();
```

always returns an empty array.

**Comment by geggleto** [comment]
Yep.

That's the problem

This line.
`$app->getContainer()->get( 'request' )->getAttributes();`

Do not ever pull the request from the container. PSR-7 mandates that the request/response objects be immutable. So they are never updated in the container.

**Comment by aimeos** [comment]
OK, we've fixed this by passing the `$args` parameter from the route around. Thanks for your help!
