### ISSUE TITLE
Route Caching

### ISSUE THREAD

**Issue by Ninestein** [slimphp/Slim#1801]
Hey guys,

Loving the framework, but had a question nosing into how the Fast Router works. Are there any plans or easy ways to implement their route caching in the roadmap?

https://github.com/nikic/FastRoute#caching

Else I'll look at implementing something myself to build on that.

Cheers

**Comment by danopz** [comment]
#1364 + #1749

**Comment by Ninestein** [comment]
Awesome, thanks
