### ISSUE TITLE
there is an posibillity to generate url from route name (any helper?)

### ISSUE THREAD

**Issue by parfumix** [slimphp/Slim#1802]

**Comment by tflight** [comment]
Do you mean something like this?

`echo $app->getContainer()->get('router')->pathFor('home');`

See the [route names](http://www.slimframework.com/docs/objects/router.html#route-names) section of the docs for another example. And if you are using Twig, there is an extension there so you can do something like this:

`{{ path_for('home') }}`

**Comment by parfumix** [comment]
Thank you!

**Comment by netmou** [comment]
is there a way to access path_for in php-view

**Comment by tflight** [comment]
@netmou, see [Inserting a path to a named route in a php-view template?](https://github.com/slimphp/PHP-View/issues/31)

**Comment by netmou** [comment]
very thanks ,
i do it like this

```
// view renderer
$container['renderer'] = function ($c) {
    $settings = $c->get('settings')['renderer'];
    $renderer = new Slim\Views\PhpRenderer($settings['template_path']);
    $renderer -> addAttribute('router',$c->get('router'));
    return $renderer;
};
```
