### ISSUE TITLE
Slim 2: Avoid removal of physical path in PATH_INFO

### ISSUE THREAD

**Issue by carminexx** [slimphp/Slim#1809]
Hi,
I have a Slim application where each URL within the controllers is prefixed with the base_url path (that is a string constant defined in my app config file). This allows me to use different base paths (ex: if running behind a reverse proxy, in a different folder, etc.). 
But, I noticed that in Environment.php, line 143, the "physical" path is removed from PATH_INFO that will be consumed by the router. 
By doing so, it's impossible to run correctly Slim in a subfolder, because all requests have the base path removed.

Is this a bug?
Is it possible to tell Slim not to remove the physical path? I can edit the Environment.php by myself, but, obviously, I can't use composer if I modify Slim libs files.

**Comment by akrabat** [comment]
Can you provide a unit test or code that shows the problem?

**Comment by akrabat** [comment]
Oh. For Slim 2, we're only fixing security issues as Slim 3 is now released.
