### ISSUE TITLE
Arguments passed to middleware classes

### ISSUE THREAD

**Issue by AmibeWebsites** [slimphp/Slim#1814]
Is it possible to pass arguments to middleware from a route?

What I want to say (in code) 'this route is allowed access by these user roles', where the middleware authorises access by comparing allowable roles to the current user's role (the user is already authenticated. The middleware is a class, set up as a dependency in the container, with relevant container elements injected in via the middleware class constructor.

I tried by setting route arguments but these are not passed to the middleware method but this give the idea of what I'm thinking:

```
  $app->get('/users', 'App\UserController:get')
    ->setName('user-list')
    ->setArgument('allow', ['admin'])
    ->add( 'App\AuthMiddleware:authorize' );
```

Another conceptual idea I thought of is something as follows:

```
  $app->get('/users', 'App\UserController:get')
    ->setName('user-list')
    ->add( "App\AuthMiddleware:allow(['admin'])" )
    ->add( "App\AuthMiddleware:authorize" );
```

**Comment by akrabat** [comment]
You can inject whatever you like into a middleware class via DI.

You can also pass information from one piece of middleware to the next via the request's 'withAttributes()`and`getAttributes()` methods.

**Comment by AmibeWebsites** [comment]
Okay, so my first example would work and I use $request->getAttributes() in the middleware method to access it? I shall attempt it immediately. Thank you for the fast response.

**Comment by AmibeWebsites** [comment]
Fantastic, it worked. For the record, this was the code:

For my route:

```
$app->get('/users', 'App\UserController:get')
    ->setName('user-list')
    ->setArgument('allow', ['admin'])
    ->add( 'App\AuthMiddleware:authorize' );
```

For my middleware:

```
public function authorize($request, $response, $next)
{
    $route = $request->getAttribute('route');
    $allow = $route->getArgument('allow');

    // Code to check auth here

    $response = $next($request, $response);
    return $response;    
}

```
