### ISSUE TITLE
Interface for content renderers

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1821]
Related to: https://github.com/slimphp/PHP-View/issues/24

It does make sense for Slim as a project to have an interface that defines a set of common data access methods.

Here is what I was thinking based upon TwigView.

``` php

namespace Slim\Views;

interface ViewRenderer {

    public function fetch($template, $data = []);

    public function render(ResponseInterface $response, $template, $data = []);

}

```

We could add get/set for global template values.

**Comment by mathmarques** [comment]
:+1: 
I think we could extend `\ArrayAccess`on this interface to get/set global values (like TwigView)

**Comment by geggleto** [comment]
Yeah I think that would be a good idea, php-view doesn't but it was something that was being asked for.

**Comment by dopesong** [comment]
I think it should be in separate repo - like container-interpop interface.

**Comment by geggleto** [comment]
@dopesong This one is suppose to be for Slim specific render implementations... It seems rather wasteful to have a separate repo for a single interface.

**Comment by dopesong** [comment]
I'm using slim for APIs so it's wasteful for me to have such interface with Slim. I think Slim should stand for its name and should not cary what is not needed. As twig view and your php-view are just 3-rd party libs in my opinion they should implement some interface which works with PSR-7 and should not be attached to Slim. :)

**Comment by rachellcarbone** [comment]
Are we able to create custom views currently without this interface? I just upgraded from v2 to v3 and am trying to re-implement a custom JSON view that uniformly formats all responses. I'm having a hard time figuring out how to connect it to the API.

**Comment by silentworks** [comment]
@rachellcarbone yes currently you can create custom views, take a look at the Twig-View or the PHP-View to see how its done. How was the custom JSON view implemented in v2? was it a hook or a middleware or just manually called in each route callable?

**Comment by rachellcarbone** [comment]
@silentworks Hello! It was called by `$app->render` manually in each route to complete the method. I was hoping to implement it in a similar way.

**Comment by rachellcarbone** [comment]
@silentworks Thank you I was able to figure out how to add it as a container view and use render by looking at the PHP-View. Thanks for the help!

**Comment by kminek** [comment]
i totally agree with @dopesong - view renderers are third-party libs. i guess we will have to wait for PHP-FIG interface for view renderer in MVC :)

**Comment by geggleto** [comment]
@kminek we will still provide renderers by default ;)

**Comment by kminek** [comment]
@geggleto  why should Slim provide abstraction for third-party library? if we would like to take that
path - why not provide abstraction for configuration or database access? Slim is micro-framework
and as dopesong pointed "should not cary what is not needed"

**Comment by geggleto** [comment]
@kminek traditionally we provide Twig and PHP renderers. In order to facilitate further 3rd party packages we need a defined interface published ;)

**Comment by geekish** [comment]
I see no problem in having one extra interface in Slim as long as it is completely optional to use.

**Comment by geggleto** [comment]
@geekish would be 100% optional.

It will just allow us to keep a standard API between different rendering libraries... ie TWIG, PHP ... etc

**Comment by geekish** [comment]
@geggleto Just had to throw my two cents in since it seems there are a few against this. I see no problem with one extra interface when the alternative is creating a separate package just for the interface. I know Expressive does this but they have some helpers in there IIRC.

**Comment by dopesong** [comment]
So we have Middlewares, we have PSR-7. What's the point of additional interface? Still, can't understand that while you can achieve the same thing with a more global approach. :)

**Comment by mathmarques** [comment]
I think this can be closed as discussed https://github.com/slimphp/Slim/pull/2445
