### ISSUE TITLE
Slim3 optional parameter with controller method as callback

### ISSUE THREAD

**Issue by developer239** [slimphp/Slim#1822]
http://stackoverflow.com/questions/36114711/slim3-optional-parameter-with-controller-method-as-callback

**Comment by MichalJarnot** [comment]
These things should be stated on OBVIOUS PLACES.

**Comment by akrabat** [comment]
Slim is open source and as such we rely on contributions from our community to write and document the framework.

I have added some initial documentation about optional parameters to http://www.slimframework.com/docs/objects/router.html#route-placeholders

**Comment by bochoven** [comment]
I don't want to hijack this thread, but is there a way to have 'unlimited' optional parameters?

**Comment by akrabat** [comment]
You have to do it a bit manually:

``` php
$app->get('/test/{params:.*}', function ($request, $response, $args) {
    $params = explode('/', $request->getAttribute('params'));

    // do something with $params and $response

    return $response;
});
```

Then, for a URL of `/test/this/out`, `$params` is an array of two elements: 

```
array (size=2)
  0 => string 'this' (length=4)
  1 => string 'out' (length=3)
```

**Comment by akrabat** [comment]
I have also documented this.

**Comment by bochoven** [comment]
Ha, thanks!

**Comment by developer239** [comment]
Cool :)

**Comment by OptimusCrime** [comment]
You do great work for the open source community in PHP, @akrabat :)

**Comment by adiramardiani** [comment]
Hai @akrabat and @all
First, sorry if I ask here (and bad english), a try in stackoverflow but someone not answer

I have a route with optional data argument like this
```php
$app->get('/books[/{name}[/{section}[/{to}]]]', function ($request, $response, $args) {
     ...
     var_dump($args);
     ...
});
```

I dump with link
```php
<?=$router->pathFor('books', ['name' => 'book-a','section'=>1,'to'=>2])?>
```

The result is correct : 
```
{ ["name"]=> string(6) "book-a" ["section"]=> string(1) "1" ["to"]=> string(1) "2" }
```

This link generate url like : books/book-a/1/2

But how to generate url like : books/book-a:1-2 ?
(the `section` and `to` data argument (':1-2') is optional, books give list book, book-a only give detail book-a, if add :1 give book-a section 1, if add :1-2 give book-a section 1-2) ?

I use : 
```php
$app->get('/books[/{name}[:{section}[-{to}]]]', function ($request, $response, $args) {}
```

but when i var_dump the result is not like a write above, but
```
{ ["name"]=> string(10) "book-a:1-2" }
```

my purpose is still
```
{ ["name"]=> string(6) "book-a" ["section"]=> string(1) "1" ["to"]=> string(1) "2" }
```

what route pattern to create scheme like that ?

**Comment by akrabat** [comment]
@adiramardiani I think this is a question you should ask the FastRoute people.

**Comment by adiramardiani** [comment]
Can you help me about this case (with reference link or some code) or must leave this issue to ask someone again ?

**Comment by OptimusCrime** [comment]
@adiramardiani The issue you have here is not related to Slim, but FastRoute. Their GitHub repository is located here: https://github.com/nikic/FastRoute

Edit: It might be worth noting that most GitHub repositories does not help like this in their issue section. You will either need to fix this yourself, or get someone to answer your StackOverflow question. GitHub is not really used for guidance like this.

**Comment by adiramardiani** [comment]
@OptimusCrime `adriencarbonne` do you mean me (adiramardiani) ?

Thanks

**Comment by OptimusCrime** [comment]
Yes, I ment you. Sorry.

**Comment by adiramardiani** [comment]
Oke, thanks

My case is done

Once again, thank you all :D
