### ISSUE TITLE
Add an assert-handler

### ISSUE THREAD

**Issue by patricksavalle** [slimphp/Slim#1824]
It used to be good practice to check preconditions, invariants and postconditions. Back than :) Why not have the assert-function throw exceptions, or write to logging. Turn the assert-checking off for production-servers.

**Comment by geggleto** [comment]
Hmm this is an interesting idea... given the nature of Slim you could realistically do this now via Route middleware and basic validation libraries.

**Comment by akrabat** [comment]
PHP has [assert()](http://php.net/assert) and there are [many libraries on packagist](https://packagist.org/search/?q=assert).
