### ISSUE TITLE
Merging in settings without relying on App

### ISSUE THREAD

**Issue by alexweissman** [slimphp/Slim#1832]
I've developed a [`Config` class](https://github.com/userfrosting/config), which implements `ArrayAccess`, and I'd like to use it as my `settings` service.  I can do something like this:

```
$app = new \Slim\App();

$container = $app->getContainer();    

// Create and inject new config item
$container['settings'] = function ($c) {
    $config = new \UserFrosting\Config\Config();
    $config->setPaths([
        '/path/to/main/config/',
        '/path/to/plugin/config/'
    ]);

    $config->loadConfigurationFiles('production');

    return $config;
};
```

This seems like it would work, except that by completely replacing the `settings` service, I am overwriting all of Slim's default settings (`outputBuffering`, 'httpVersion`, etc).  

So, I thought to myself, "No problem, I'll just grab the default array for `settings` from the container, then manually merge using the `mergeItems` method that I created for my `Config` class:

```
$defaultSettings = $container->get('settings')->all();

$container['settings'] = function ($c) use ($defaultSettings) {
    $config = new \UserFrosting\Config\Config();
    $config->setPaths(...);

    $config->loadConfigurationFiles('production');

    $config->mergeItems(null, $defaultSettings);

    return $config;
};
```

Unfortunately, when I do this I get:

> Fatal error: Uncaught exception 'RuntimeException' with message 'Cannot override frozen service "settings"

This is happening because, once I access `$c->get('settings')`, the service is frozen and so I can no longer modify it.

I'd really like to use something more than just a basic array to manage my site's configuration settings.  Is there another way, short of registering my own service (with blackjack, and hookers) separate from Slim's `settings`?

**Comment by dopesong** [comment]
This is my nasty way for frozen service:

``` php
        $defaultSettings = $this->container['settings'];

        if ($defaultSettings instanceof \Slim\Collection) {
            $defaultSettings = $defaultSettings->all();
        }

        unset($this->container['settings']);

        $this->container['settings'] = array_merge(
            $defaultSettings,
            $this->container['config']['settings']
        );
```

**Comment by alexweissman** [comment]
I actually just ended up registering a separate service (with blackjack, and hookers), keyed to `config`:

```
    // Site config object (separate from Slim settings)
    $container['config'] = function ($c) {
        // Create and inject new config item
        $config = new \UserFrosting\Config\Config();

        $config->setPaths([
            ...
        ]);

        $config->loadConfigurationFiles('production');

        return $config;
    };
```

So, I let Slim use `settings` for its internal features, but any other configuration my application requires is accessed through `$container['config']`.

**Comment by dopesong** [comment]
Yeah, I have the same, but in this case I'm using `$this->container['config']['settings']` just for Slim settings
