### ISSUE TITLE
Wildcard in the route

### ISSUE THREAD

**Issue by semencov** [slimphp/Slim#184]
Is there any option to set the wildcard to the route or to the part of it?

While inspired by Nesta CMS which is based on Sinatra, I didn't find such feature in your framework (did I miss something?).

In Nesta it is used to catch all URLs ant to retrieve specific template file. 

``` ruby
    get '*' do
      set_common_variables
      @heading = @title
      parts = params[:splat].map { |p| p.sub(/\/$/, '') }
      @page = Nesta::Page.find_by_path(File.join(parts))
      raise Sinatra::NotFound if @page.nil?
      @title = @page.title
      set_from_page(:description, :keywords)
      cache haml(@page.template, :layout => @page.layout)
    end
```

The difference is that in your framework it parse URL parameters by word (\w), so you can not make some common rule with unknown amount of parameters or words.

I like your framework a lot, so could we see something similar?

**Comment by codeguy** [comment]
I've been meaning to add this for a while. This isn't an immediate concern, but I'll add it to the Road Map.

**Comment by silentworks** [comment]
I don't recommend this but what I did was use the notFound method as my catchall since it isn't implemented as yet.

**Comment by semencov** [comment]
Yes, I've considered this possibility, but still hope there will be native support for wildcards, as it could be greate to use it more flexible than simple '*'.

**Comment by codeguy** [comment]
Closing this out. Please post feature requests to http://help.joshlockhart.com. I've opened a thread here:

http://help.slimframework.com/discussions/suggestions/2-wild-card-in-routes
