### ISSUE TITLE
allow to get stream resource from the body

### ISSUE THREAD

**Issue by RusAlex** [slimphp/Slim#1843]
I want to use fputcsv function to convert array to a csv. But cucrently I cant get access to a stream variable in a Body class.

It would be good to create a public getter for stream.

**Comment by akrabat** [comment]
I'm pretty sure that the intention is that you care create a new Stream and then attach it.

**Comment by RusAlex** [comment]
But I cant neither replace $response->body nor attach new resource to it (attach is protected method) .

**Comment by akrabat** [comment]
```
$response = $response->withBody($myNewStream);
```

**Comment by RusAlex** [comment]
Thank you so much.
