### ISSUE TITLE
Using OpenID With Slim

### ISSUE THREAD

**Issue by farazappy** [slimphp/Slim#1845]
Hey,
I am trying to use **Slim2** as a _framework_ and **Twig** as the _template engine_ for my project and I want to allow my users to Login/Register using their **social accounts** _(Facebook/Google/Twitter/Others)_. For this purpose I'm trying to use **OpenID** but can't get how to use it with Slim. 

If anybody could help me please.

Thanks!

**Comment by tflight** [comment]
Hi @farazappy,

This is better suited for the [help/support forum](http://discourse.slimframework.com) than here in the issue tracker, but have a look at [openid/php-openid](https://github.com/openid/php-openid) or [Auth0](https://github.com/auth0/auth0-PHP) and if you need more help I'd ask over in [Slim's help forum](http://discourse.slimframework.com).

**Comment by farazappy** [comment]
@tflight Thanks! Didn't knew about the forum's will post there about the same! Thanks again!

_Update_: I just tried to post there but it said my account has been blocked. Any possible reason why?

**Comment by silentworks** [comment]
@farazappy now unblocked, not sure why that happened.

**Comment by farazappy** [comment]
@silentworks Thanks for doing so!
