### ISSUE TITLE
Petition to remove Silentworks

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1847]
As per my recent twitter interaction I think we should remove silentworks from the project because he has now switched sides from PHP to the evil NodeJS crowd.

Proof:
http://i.imgur.com/BSU3MFc.png

For his replacement, I nominate myself.

//cc @akrabat @codeguy @silentworks

**Comment by silentworks** [comment]
Petition Denied for the lack of real evidence. We need Immutable evidence as proof. There is Node other way we can React on this Petition.

**Comment by geggleto** [comment]
BEST.
RESPONSE.
EVER
