### ISSUE TITLE
Matching argument with extension

### ISSUE THREAD

**Issue by maciekpaprocki** [slimphp/Slim#1849]
I am sure it is somewhere, but I cannot find it for few last hours. 

I need to match img/kayak.jpg

Surprisingly 

`$app->get('/img/{file:.*}',function(){});`

Doesn't work. Any ideas?

**Comment by norkunas** [comment]
#359

**Comment by nisbeti** [comment]
Slim uses fastroute, so here is an article about fastroute's use of regex 
http://nikic.github.io/2014/02/18/Fast-request-routing-using-regular-expressions.html
