### ISSUE TITLE
Setting view data as array: Fatal error

### ISSUE THREAD

**Issue by DevDavido** [slimphp/Slim#185]
If I use the example code snippet from the [documentation](http://www.slimframework.com/documentation/stable#view-data):

```
$app->view()->setData(array('foo' => 'bar', 'one' => 1));
```

I get this error:

```
Fatal error: Call to a member function save() on a non-object in xxx\Slim\Slim.php on line 1073
```

Setting it like that works:

```
$app->view()->setData('foo', 'bar');
```

PHP: 5.2.11, Slim: 1.5

**Comment by codeguy** [comment]
<del>Can you provide code for the simplest Slim application you can build that demonstrates this issue? It's difficult to diagnose out of context. I don't think the View method is related to the error being triggered.</del>


EDIT:  _Actually_ what is happening is that when you call `$app->view()->setData(array(...))`, you are effectively _overwriting_ all of the View's variables, including the object responsible for Flash messaging. I encourage you to use `$view->appendData(array(...))` instead :) Not really a bug, just need to use the appropriate View instance method. Closing this out.
