### ISSUE TITLE
[RFC] CORS Support

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1851]
Looking towards 4.0... I was wondering about including CORS support built-in for Slim users and I want to hear your feedback on it.

Ideally it would be something that you can either turn ON or OFF, so that you are not forced to use it.

The idea comes from the few projects that already address this issue.
[1] https://github.com/palanik/CorsSlim
[2] http://joshuasampia.com/2015/11/05/cors-slim-php-setup/
... etc

**Comment by silentworks** [comment]
I don't think this belongs in the core of Slim, but can be part of Slim Skeleton.

**Comment by akrabat** [comment]
Are there any things within Slim that make supporting CORS harder than it could be?

**Comment by mathmarques** [comment]
I don't think we should add this on Slim.
A 'simple' middleware could add CORS Support.
Maybe we only need a Middleware/Addon section on slim website to index these useful things

**Comment by geggleto** [comment]
@mathmarques @akrabat 

The problem with CORS is that in the pre-flighted requests you need to know what endpoints are registered.

Example:
Resource: `/v1/user` 
- Supports: GET, POST, PUT

The preflight OPTIONS `/v1/user` should return a header with 
`Access-Control-Allow-Methods: POST, GET, PUT`

Doing this in a middleware... I have no idea how that could be done.

It makes most sense to do it at the router level, as it can inspect the Dispatcher to find routes LIKE this one and construct a HTTP METHOD List for this resource.

**Comment by geggleto** [comment]
@silentworks Not sure if it should land in core myself, but its something that I deal with frequently. Perhaps a CorsRouter might be more useful.

**Comment by lalop** [comment]
I'm maybe wrong but any middleware can access to the routes registred in the router, no ?

**Comment by geggleto** [comment]
@lalop true... in order to figure out what ROUTE you are in you will need to use the determineRouteBeforeDispatch setting.

**Comment by akrabat** [comment]
Should we be organising the information in the router, so that getting this information out is reasonably easy?

**Comment by lalop** [comment]
Adding a route middleware and the route information as attribute to the request should do the trick I suppose

**Comment by tuupola** [comment]
I think CORS does not belong to core.There already are couple of middlewares,  including [mine](https://github.com/tuupola/cors-middleware) which uses [neomerx/cors-psr7](https://github.com/neomerx/cors-psr7) for heavy lifting. However the OPTIONS problem @geggleto mentioned is real.

BTW. Slim already has some code in place for OPTION magic. You do not need to specify and OPTIONS route to get a list of allowed methods. However I think it is not possible to access the list of allowed methods in middleware. It is only outputted in the error handler.

In one sentence what is needed is a way for a middleware to know which HTTP verbs are defined for a given and/or current route.

**Comment by Alex-PK** [comment]
The main problem I had in implementing CORS in Slim was (is) the absence of the Origin header in $request->getHeader*()

Same thing happened with Authorization (for OAuth2). I had to use a SetEnvIf in htaccess to have access to it.

A way to add "whitelisted headers" in Headers' $special array before the createFromEnvironment() would be great, IMHO. 
Right now the call to it is hardcoded in Request, so you can't even override it in Application. You need to extend Request and rewrite its createFromEnvironment from scratch.

While I'm on it, a way to extend Request's $validMethods would be nice too, as I had (still, for CORS) to use PROPFIND (or create a new INFO method) where I used OPTIONS, because the latter is hijacked by CORS.

**Comment by tuupola** [comment]
The `Authorization` header thing is not related to Slim. It is considered a PHP feature. If you send anything else than a valid `Authorization: Basic` header it will not be available to PHP without the `.htaccess` workaround. Or it is, but only using `apache_request_headers()` which is Apache specific.

**Comment by Alex-PK** [comment]
Sorry, forget what I said about the Options header. It's a bug in my Postman. The Origin header gets correctly parsed by Slim.

It would still be nice to have a way to customize $validmethods. :)

**Comment by geggleto** [comment]
The more I think about the OPTIONS problem the more I think we should have a different Router to handle it. If we had a CORS Router that could track routes and the method they are mounted to it would be rather trivial to solve the options problem with CORS. This wouldn't be a BC break as we are adding a new Router for our users to use, and most importantly it would be optional.

It would simply require a replace in the container... or we could even have it as a configuration option when constructing the container.

The CORSRouter would then extend the Slim basic router and would overload the methods that register routes. A new list would be created to track the routes, with Pattern being the key and verbs added on.

a simple getter to the router with a pattern would suffice to get a list of VERBS supported by your application.

``` php
//...  Rough Pseudo Code
protected $patterns = [];

public function getSupportedVerbs($pattern) { 
    return $this->patterns[$pattern];
}

protected function addSupportedVerb($pattern, $verb) {
    $this->patterns[$pattern][] = $verb;
}

public function get(....) {
    $this->addSupportedVerb($pattern, 'GET');
    parent::get(....);
}

//...
```

**Comment by tuupola** [comment]
I found a way for middleware to get the defined verbs for current routes **pattern** with the code below. Note that this is not always the the same as all the defined verbs for current routes **uri**. However it is close enough for most use cases.

```php
require __DIR__ . "/vendor/autoload.php";

$app = new Slim\App([
    "settings"  => [
        "determineRouteBeforeAppMiddleware" => true,
    ]
]);

$app->add(function($request, $response, $next) {
    $pattern = $request->getAttribute("route")->getPattern();

    $methods = [];
    foreach ($this->router->getRoutes() as $route) {
        if ($pattern === $route->getPattern()) {
            $methods = array_merge_recursive($methods, $route->getMethods());
        }
    }

    $response->write(print_r($methods, true));
    return $next($request, $response);
});

$app->get("/api/{id}", function($request, $response, $arguments) {
});

$app->post("/api/{id}", function($request, $response, $arguments) {
});

$app->map(["DELETE", "PATCH"], "/api/{id}", function($request, $response, $arguments) {
});

$app->run();
```

```
%curl --include http://localhost:8080/api/xxx
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Content-Length: 76

Array
(
    [0] => GET
    [1] => POST
    [2] => DELETE
    [3] => PATCH
)
```
