### ISSUE TITLE
Improve Error handling function signature in documentation

### ISSUE THREAD

**Issue by BetterBetsLobos** [slimphp/Slim#1852]
In the section http://www.slimframework.com/docs/handlers/error.html in the custom error handler function give, the function signature could be improved to read like this: 

```
return function (ServerRequestInterface $request, ResponseInterface $response, Exception $exception) use ($c) 
```

ie: add type hinting.

**Comment by ppetermann** [comment]
well if you go all typehint in the example, it probably makes sense to use full qualified namespaces..
