### ISSUE TITLE
Inconsistent types for route argument setting vs getting

### ISSUE THREAD

**Issue by sander-bol** [slimphp/Slim#1868]
According to it's docblock, `RouteInterface::setArgument()`'s $value argument needs to a string, whereas `RouteInterface::getArgument()` returns `mixed`, and accepts `mixed` type for its $default parameter.

Will be happy to provide a PR to resolve the inconsistency, but need to know which solution you prefer: should route arguments always be strings, or should we accept `mixed` for the value? The latter makes more sense to me - in my own case, I was trying to set a boolean flag on the route as argument (worked perfectly, except that static analysis complains about violating the parameter type).

**Comment by geggleto** [comment]
It should be string... https://github.com/slimphp/Slim/blob/3.x/Slim/Interfaces/RouteInterface.php#L28
string | null, I suspect.
