### ISSUE TITLE
Fatal error: Call to a member function save() on a non-object

### ISSUE THREAD

**Issue by CBeerta** [slimphp/Slim#187]
I am getting the following error after updating Slim from 1.3 to 1.5 and adapting my code.

```
Fatal error: Call to a member function save() on a non-object in /home/claus/www/mywebpage/vendor/Slim/Slim/Slim.php on line 1074
```

I've used `$app->view()->setData()` initially to set some global view data which seems to replace the 'flash' data. Replacing setData() with appendData() solves the problem.

This shouldn't be the case though?

**Comment by codeguy** [comment]
Use `$view->appendData(array())` instead. The error is a result of you replacing the Flash messaging variable in the View object.

**Comment by CBeerta** [comment]
It's what i did. But doesn't that render setData() pretty redundant?
