### ISSUE TITLE
Slim_Http_Cookie could not be loaded

### ISSUE THREAD

**Issue by nansenat16** [slimphp/Slim#188]
Hi, I get more error with redirect method in Slim 1.5.0

I try set cookies.encrypt to false, but not work.

PHP Fatal error:  spl_autoload(): Class Slim_Http_Cookie could not be loaded in /var/www/html/4money/Slim/Http/CookieJar.php on line 285, referer: http://192.168.31.99/4money/bootstrap.php/quotation_list

**Comment by codeguy** [comment]
I've not seen this before, nor can I duplicate having tried here really quickly. What version of PHP are you using?

**Comment by nansenat16** [comment]
CentOS6 x64 PHP 5.3.2 Apache/2.2.15 (no mod_rewrite support)

**Comment by nansenat16** [comment]
Sorry, I sure the problem in cookie, not in redirect function

when I have a cookie in request like is:
PHPSESSID=dbbea4b04ea22f92196d36045a836acb; dbbea4b04ea22f92196d36045a836acb=DEFAULT%7C0%7CZmxhc2h8YTowOnt9%7Cb161b6580e43cc79d18932d556d4651fb6de53ce

request page full code:
<?php
require 'Slim/Slim.php';
$slim_settings = array(
    'mode'               => 'production',
    'debug'              => true, 
    'log.enable'         => false,
    'cookies.encrypt'    => false,
    'cookies.secret_key' => 'PLEASE CHANGE THIS',
);
$app = new Slim($slim_settings);
?>

**Comment by rcrowe** [comment]
Not sure if this is the same cause that you are seeing, but your example code suggests that you have omitted:

``` php
$app->run();
```

If I comment this line out in my code I see the error:

``` php
Fatal error: spl_autoload() [<a href='function.spl-autoload'>function.spl-autoload</a>]: Class Slim_Http_Cookie could not be loaded in /Applications/MAMP/htdocs/builder/vendor/Slim/Http/CookieJar.php on line 285
```

**Comment by DevDavido** [comment]
I get this error too if I add inside a action e.g. 
<code>var_dump(123);die;</code>

**Comment by codeguy** [comment]
You should not `die` within a callback, else the Slim application is unable to complete it's lifecycle (i.e. sending headers to the HTTP client at the end of the application lifecycle). I recommend you call `$app->halt(status, message)` instead.

The issue at the top of the thread... I still cannot duplicate.

**Comment by nansenat16** [comment]
I duplicate it
1. Browser have 2 cookie
   PHPSESSID=f4a9b5b4d37cbff1634116ede87805cd; f4a9b5b4d37cbff1634116ede87805cd=DEFAULT%7C0%7CZmxhc2h8YTowOnt9%7Cb161b6580e43cc79d18932d556d4651fb6de53ce
2. The page use redirect like this:

``` php
<?php
require 'Slim/Slim.php';
$slim_settings = array(
    'mode'               => 'development',
    'debug'              => true,
    'log.enable'         => false,
    'cookies.encrypt'    => false,
    'cookies.secret_key' => 'PLEASE CHANGE THIS',
);
$app = new Slim($slim_settings);

$app->get('/', function() use ($app) {
    $app->redirect('home');
});

$app->run();
?>
```
1. if browser no cache, get the error

[Fri Dec 02 23:33:30 2011] [error] [client 192.168.31.151] PHP Fatal error:  spl_autoload(): Class Slim_Http_Cookie could not be loaded in /var/www/html/myapp/Slim/Http/CookieJar.php on line 285, referer: http://192.168.31.99/myapp/

**Comment by nansenat16** [comment]
when use PHP 5.3.6 or higher it's no error msg.

**Comment by snez** [comment]
I get this too on php 5.3.2, however if I run the same application on two different servers, both running php 5.3.2, one of them is failing and the other doesn't, so not entirely sure what is causing this.

**Comment by snez** [comment]
Found it, I had a $param = $_GET['param'] somewhere while the get param was not set, wierd how this throws a slim error and not a php error.

**Comment by codeguy** [comment]
@snez Cool. Slim will catch any PHP errors and convert them into more manageable `ErrorException` objects which are re-thrown and caught by either your own custom error handler (when `debug` is `false`) or by Slim's default handler that shows detailed debugging information about the exception (when `debug` is `true`).
