### ISSUE TITLE
How to use the controller inside di

### ISSUE THREAD

**Issue by lazycms** [slimphp/Slim#1888]
code like this. but i dont how use render
namespace Controller;

class admin extends  base
{

```
public function index($request, $response, $args) {

    return $this->app->renderer->render('','index.phtml');
}
```

}

**Comment by francoism90** [comment]
You need to inject the Container into the class.

**deps.php:**

```
<?php
$ci['render'] = function ($ci) {
  return new \Path\To\Controller($ci);
}
```

**controller.php:**

```
<?php
namespace ..
class Controller {
  private $ci;

  public function __construct($ci) {
    $this->ci = $ci;
  }

  public function myMethod($request, $response, $args) {
    return $this->ci['render']->method();
  }
}
```

**Comment by danielgsims** [comment]
Here is the documentation on Container Resolution. This is how you store a Controller class in the Container and wire it up to a route:

http://www.slimframework.com/docs/objects/router.html#container-resolution
