### ISSUE TITLE
Undocumented "slim.files" option

### ISSUE THREAD

**Issue by llvdl** [slimphp/Slim#1890]
In the function `Slim\Http\UploadedFile::createFromEnvironment` I found the following lines:

``` php
        if (is_array($env['slim.files']) && $env->has('slim.files')) {
            return $env['slim.files'];
        } // else ...
```

The "slim.files" option doesn't seem to be documented and isn't covered by any tests. Is there a reason for keeping it in? And if so, what is to the use case?

**Comment by Raistlfiren** [comment]
`slim.files` is used for testing purposes. You can view the comment here - https://github.com/slimphp/Slim/issues/1099#issuecomment-83735868

**Comment by llvdl** [comment]
Is this for testing an application that uses Slim?

`slim.files` is not used by Slims internal tests. If I remove the `slim.files` part, the tests still succeed.

**Comment by akrabat** [comment]
Now used in the unit test `testCreateFromEnvironmentFromUserData`.
