### ISSUE TITLE
Google Bot No Longer Renders Page

### ISSUE THREAD

**Issue by jonathankaiser** [slimphp/Slim#1892]
I started getting a "Temporarily unreachable" error from the google bot when I upgraded from 3.3.0 to 3.4.1. Is this now expected and should I add something to the .htaccess file or somewhere else for bots?

Type: UnexpectedValueException
Message: Cannot render unknown content type
File: app/vendor/slim/slim/Slim/Handlers/NotFound.php
Line:   51

**Comment by mathmarques** [comment]
The "problem" was created here: #1866 

Probably googlebot is sending an Accept header that isn't application/json, application/xml, text/xml or text/html.
Couldn't find the full googlebot request to see what google send on Accept header.

To fix this you could implement your Not Found handler. See [here](http://www.slimframework.com/docs/handlers/not-found.html#custom-not-found-handler).

**Comment by adamaltman** [comment]
The problem is that the change in #1866 (part of 3.4.1) is integrated as a bugfix release if semantic versioning is followed, and it's breaking its contract by now throwing an `UnexpectedValueException`.  This might have been identified as a breaking change.

**Comment by akrabat** [comment]
I'm confused.

[`determineContentType()`](https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/AbstractHandler.php#L40-L58) is guaranteed to return a [`knownContentType`](https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/AbstractHandler.php#L40-L58). 

Hence the `default` in [`Error`](https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/Error.php) should never happen.

**Comment by akrabat** [comment]
I'm mostly confused something's already gone wrong if you're in the error handler...

**Comment by jonathankaiser** [comment]
I went and did some further digging with the headers coming from the google bots. The HTTP_ACCEPT is "text/plain,text/html". Inside determineContentType(), $selectedContentTypes is generated with an index of 1 instead of 0.

`Array
(
    [1] => text/html
)`

Here are the headers coming from the google bot

`HTTP_CONNECTION Keep-alive`
`HTTP_ACCEPT text/plain,text/html`
`HTTP_USER_AGENT Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
`HTTP_ACCEPT_ENCODING    gzip,deflate,br`

The reason this is popping up now is because I don't have a robots.txt file at the root of my site which I could easily add but google won't be able to crawl a Slim site without it which was still possible in 3.3.0.

**Comment by akrabat** [comment]
@jonathankaiser why is google bot hitting the error handler though?

**Comment by jonathankaiser** [comment]
It's hitting the NotFound handler because it's trying to find a /robots.txt file at the root of my site.

**Comment by akrabat** [comment]
aha! Sorry - I now know what you mean!

**Comment by akrabat** [comment]
That should fix it. Will try and get it released today.
