### ISSUE TITLE
Typo in Slim/App::respond()

### ISSUE THREAD

**Issue by dinacel** [slimphp/Slim#1895]
I've didn't review the code, so I don't know if there's side effects:

https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L389

`if (isset($contentLength)) {`

is always true, because l.383:

`$contentLength  = $response->getHeaderLine('Content-Length');`

**Comment by JoeBengalen** [comment]
But `getHeaderLine` could return empty and the `getSize` could return `null`, so `isset(null) == false`

https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L383
https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L385

**Comment by dinacel** [comment]
My bad, I didn't know that `isset(null) == false`

**Comment by l1905** [comment]
`isset(null) == false` may be unreadable code, why not use `is_null(null)`?
