### ISSUE TITLE
I use pathFor, Why return "/"

### ISSUE THREAD

**Issue by lixinxiaobai** [slimphp/Slim#1900]
`$app->get('/hello/{name}', function ($request, $response, $args) {`
       `$url = $this->router->pathFor("hello",["name" => "world"]); // $url is "/"`
       `$response->write("<a href='$url'>Home</a>");`
       `$response->write('Hello, ' . $args['name']);`
       `return $response;`
`});`
`$url` did not return any url path, only to return a "/"

**Comment by tuupola** [comment]
http://www.slimframework.com/docs/objects/router.html#route-names

You need to give your route a name. Ie something like:

``` php
$app->get('/hello/{name}', function ($request, $response, $args) {
    $url = $this->router->pathFor("hello",["name" => "world"]); // $url is "/"
    $response->write("<a href='$url'>Home</a>");
    $response->write('Hello, ' . $args['name']);
    return $response;
})->setName('hello');
```
