### ISSUE TITLE
Multiple Invocation Strategies

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1902]
I was hoping to eliminate some code from my route actions, mainly a lot of the DB calls to find objects. I was recently looking at how other frameworks do this sort of thing and Laravel caught my eye.

The function signature would look like

``` php
public function Action(DepClass $classInstance) { 

}
```

And I thought how might I achieve this in Slim... 
## One method

The only thing we have to modify the signature of the callable is the InvocationStrategy class. This is set in the container and applies to all routes in your project...
## Second

``` php
class UserAction extends Action
{
    public function __invoke(Request $request, Response $response, array $args)
    {
        $user = User::find($args['user']);
        return $this->handle($request, $response, $user);
    }
    public function handle(Request $request, Response $response, User $user) {
    }
}
```

This second option seems a bit hackish... Another close option to the second option is to have a middleware that resolves it to an object and passes it along in a Request Attribute [bleh]. It's very hard to document the attributes of Request.
## Solution

It would be nice if we could define the InvocationStrategy on a per-route / per-route-group level.

``` php
$app->get('/user/{:id}', function ($req, $res, User $user) {})->setInvocation(UserInvocationStrategy::class); //<-- The strategy would be pulled/constructed from the container
```

Thoughts?
Did I miss any other options

**Comment by silentworks** [comment]
Looks like PHP-DI covers most of your cases http://php-di.org/doc/frameworks/slim.html#request-or-response-injection
