### ISSUE TITLE
Adding a header causes the HTTP status of the response to be altered

### ISSUE THREAD

**Issue by hhihi** [slimphp/Slim#1908]
I have a rest endpoint that is not returning the HTTP status code that I have set. It is a fairly 
straightforward section of code, and works if I don't set any headers, but once I do, it replies with the wrong status. (302 instead of 204)

I have the following function

```
public function update(Request $request, Response $response, $arguments){

    // ....

    // This works:
    return $response->withStatus(HttpStatus::NO_CONTENT);


    // but if I replace that with this it does not:
    return $response->withStatus(HttpStatus::NO_CONTENT)
                    ->withHeader("location", $location );
}
```

That function is called directly by the route:

```
$slim->put( API_PATH_BASE.'/'
            .User::_CLASS.'/{'.User::USERNAME.'}/'
            .Event::_CLASS."/{".Event::ID."}",
            'EventController:update');
```

I have not added any of my own middleware

Response with location header (incorrect status):

```
PUT https://example.com/user/JohnSmith/event/2

HTTP/1.1 302 Found
Date: Sat, 11 Jun 2016 15:45:07 GMT
X-Powered-By: PHP/7.0.5
location: https://example.com/user/JohnSmith/event/2
Content-Length: 0
```

Response without header (correct status):

```
PUT https://example.com/user/JohnSmith/event/2

HTTP/1.1 204 No Content
Date: Sat, 11 Jun 2016 15:52:12 GMT
X-Powered-By: PHP/7.0.5
Content-Length: 0
```

This is running Slim version 3.4.2

**Comment by JoeBengalen** [comment]
Can you check the status in the response object of slim after running the application?  Just to make sure it is indeed slim doing something wrong and not the webserver altering the response status because it recognized the location header.

**Comment by hhihi** [comment]
Yes, for sure. What would be the best way to do that? add a middleware?

Immediately after the calls to withStatus and withHeader it does look like the status is correct:

```
        $check = $response->withStatus(HttpStatus::NO_CONTENT)
            ->withHeader("location",$location );

        var_dump($check->getStatusCode());
        die();
```

## 

```
int(204)
```

**Comment by tuupola** [comment]
You could also test your code with internal PHP webserver.

**Comment by JoeBengalen** [comment]
`$app->run ($silent = true)` returns the final response which you can check.

**Comment by geggleto** [comment]
Works fine locally.

### Code:

``` php
$app->get('/test', function ($req, $res, $args) {
    $check = $res->withStatus(200)
        ->withHeader("location", "" );

    var_dump($check->getStatusCode());
    die();
});
```

### Output:

`int(200)`

**Comment by mathmarques** [comment]
This is not a Slim issue. It's a PHP header 'feature'.
See [header manual here](http://php.net/manual/en/function.header.php).

> The second special case is the "Location:" header. Not only does it send this header back to the browser, but it also returns a REDIRECT (302) status code to the browser unless the 201 or a 3xx status code has already been set.

If you set Location header, you can only change 302 status to 201 or 3xx

**Comment by designermonkey** [comment]
Thanks for clarifying that @mathmarques.

As this isn't a slim issue, I'm closing this out. If there are any more comments or suggestions, it can be reopened.
