### ISSUE TITLE
Slim\App invoke method and $next parameter

### ISSUE THREAD

**Issue by kdubuc** [slimphp/Slim#1909]
Why Slim\App invoke method (https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L427) doesn't have a $next parameter ? I want to use applications as middlewares, but the lack of $next stop the stack at first middleware, and send the response.

**Comment by mathmarques** [comment]
Because Slim\App invoke will always be the last App level middleware to be called.

**Comment by kdubuc** [comment]
It limit the benefits to use an app as middleware 😕  Because, it can't be in the middle actually ..

**Comment by mathmarques** [comment]
Do you have an use case? I can't imagine that...

**Comment by kdubuc** [comment]
I want to moduralize every generics modules of my app (like oauth2, errors, policies and user agreements, user devices ...). I want to do that with middlewares. But with enriched middlewares. For example oauth2 : it must have routes (/oauth2/authorize ; /oauth2/access_roken), other middlewares (access token checker), services (oauth2 server), models (client, consumer, tokens) etc etc ..
So, I want to encapsulate this into one big app middleware.

**Comment by designermonkey** [comment]
Thanks for the explanation, but I too am a little lost as to what the use case needs beyond what is available.

The App will always run as the last middleware item in the list, and doesn't need a `$next` parameter, as nothing can be added after it.

If I think what you mean is to have your functionality in an 'app' and add Slim as a middleware to that? If so, then currently, the best way to achieve that is to extend `Slim\App` directly.

**Comment by menismu** [comment]
Just a thought as this is remembering me an application I´ve developed where a feature needed to be executed always after the logic of each web service, and as `Slim\App` is the last bit executed was not possible.

Let´s say we have an application with a couple of middleware to be executed like:

middleware 1 -> app -> middleware 2

Middleware 1 could be token validation middleware 2 could be something like audit feature where I need to get all responses tracked. Also, if I would need different implementations of the middleware 2 depending on the environment or to be reused is telling me a middleware is a better option than something implemented in the app.

This could be inline with @kdubuc comment and I'm wondering which would be the best approach to this in Slim.

**Comment by akrabat** [comment]
If you want to execute some code after the route callable, then register middleware with the code after the call to `next`:

i.e.  middleware 2 from https://github.com/slimphp/Slim/issues/1909#issuecomment-264724682 looks like this:

```php
$app->add(function ($request, $response, $next) {
    $response = $next($request, $response);

    // do work now that the App's route callable has executed

    return $response;
});
```
