### ISSUE TITLE
Fails silently

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1910]
We need to add a check to Route Actions to ensure they are returning a response.

In the event of no returned response a 200 Okay is generated.... we should be raising an exception to aide the developer in debugging.
## Example

``` php
    $this->post('/create', function (Request $request, Response $response) use ($post) {
        $post->create($request, $response);
        //$post->create returns $response->withRedirect(); ... 200 is generated.
    });
```
## Expected

```
throw new \Exception("No response returned from callable");
```
## Options

We should provide an additional container key to toggle this functionality on/off.

`enforceResponseFromRouteAction`

**Comment by JoeBengalen** [comment]
Is the code an exact copy? You forgot a return

```php
    $this->post('/create', function (Request $request, Response $response) use ($post) {
        return $post->create($request, $response);
    });
```

**Comment by geggleto** [comment]
That's my point :)

if you forget the return it's so stupid hard to debug because no errors are
raised ;)

**Comment by JoeBengalen** [comment]
Haha yeah, I reread your post and noticed that.
I had already removed it, hoping nobody would notice. Guess I was too late :disappointed:

**Comment by akrabat** [comment]
Not returning anything is an intentional state. You can turn it off by setting `outputBuffering` to `false`.

We should probably warn if we detect that the output buffer is empty and response wasn't returned though.

**Comment by geggleto** [comment]
@akrabat sounds like a lot of effort, idk i think it can be covered in 4.0
