### ISSUE TITLE
Change default controller if go middleware

### ISSUE THREAD

**Issue by andrey900** [slimphp/Slim#1911]
Can you tell, and if I could change the controller or method used by default when you go middleware?
Example:

``` php
$app->get('/articles/{page}', "DefaultControler:indexAction")->add(new ControllerChanger());

class ControllerChanger{
    public function __invoke($request, $response, $next)
    {
        // Change controller handler if
/* 
* case($page) ... 
* DefaultControler:tagAction
* SearchControler:indexAction
*/
        return $response;
    }
}
```

**Comment by geggleto** [comment]
There is no way to change the Action of a Route once it has been created.

Reference: https://github.com/slimphp/Slim/blob/3.x/Slim/Route.php
Getter no Setter.

**Comment by JoeBengalen** [comment]
No, but you can update the route in middleware before the action is determined.

But why would you need to? Just register multiple routes (one for each switch case in your example)

**Comment by andrey900** [comment]
I generate routes on the fly from a database, but I want to be able to change the default behavior of the controller, depending on a URL. I thought that there will use middleware. I'll try use, the pattern strategy for the controller.

**Comment by silentworks** [comment]
I think @JoeBengalen answer is a solution to your issue. Closing this issue for that reason. Please reopen if you feel its not resolved.
