### ISSUE TITLE
Cancelling (continuing past) a route

### ISSUE THREAD

**Issue by matthew-dean** [slimphp/Slim#1912]
It's a common use case to want to cancel a route after it has matched. For example, say you have a matching wildcard route that maps to a list of files. If that file doesn't exist, you want the router to continue looking for a matching route (and possibly end up in a 404 if no other routes match). Does that functionality exist in Slim 3? I thought there was something like that with `$app->pass` in Slim 2 IIRC. How do you tell Slim, "Nope, sorry, this route doesn't match after all. Check other routes." ?

**Comment by geggleto** [comment]
@matthew-dean Slim supports everything that `nikic/FastRoute` does... https://github.com/nikic/FastRoute ... I don't believe this functionality is supported.

**Comment by matthew-dean** [comment]
Hmm, ok. I wonder what the rationale is for reducing features.

**Comment by geggleto** [comment]
The pass method in Slim internally used Exceptions which break's a lot of things. Using exceptions for control flow like that was a bad design.

**Comment by matthew-dean** [comment]
@geggleto Alright. That's fine. But do you have another suggestion for how to achieve this? How do you un-match a match? Can middleware on a route cancel (continue) the route?

**Comment by geggleto** [comment]
@matthew-dean hmm, I don't know what you are trying to do exactly...

**Comment by matthew-dean** [comment]
Okay, I'll give you a specific (slightly simplified) use case:

``` php
$app->get('/wireframes/{page}/', function ($req, $res, $args) {
  if( /* page exists */)
      echo $this->page->render($args['page']);
  else 
      /* continue routing until eventual 404  */
});
```

Express.js uses this kind of pattern.

**Comment by tuupola** [comment]
If you are trying to have both hardcoded routes and route with named argument you can put the hardcoded routes first.

``` php
$app->get("/wireframes/foo/", function ($req, $res, $args) {
   print "foo";
});

$app->get("/wireframes/{page}/", function ($req, $res, $args) {
    if( /* page exists */) { 
        print $args["name"];
    }
});
```

**Comment by matthew-dean** [comment]
@tuupola 

With those routes, `/wireframes/fiddlefaddle` (assuming fiddlefaddle does not exist) would never (rightfully) result in a 404. Or do you just manually set a 404 header? Do you separate out a 404 function that is fired when nothing matches, and manually call the function in this case? What's the "Slim way" for rejecting a matched route? Or, is the short answer simply: Slim has no solution for this use case?

**Comment by matthew-dean** [comment]
As a parallel metaphor, when creating parsers, it's common to match a pattern, and then further examine the match to determine if it qualifies. That's all I'm trying to do here, but with route patterns.

**Comment by tuupola** [comment]
You can return 404 response when needed.

``` php
$app->get("/middleware/foo", function ($request, $response, $args) {
    return $response->write("foo");
});

$app->get("/middleware/{name}", function ($request, $response, $args) {
    if ("fiddlefaddle" === $args["name"]) {
        return $response->withStatus(404);
    } else {
        return $response->write($args["name"]);
    }
});
```

Another option is to throw an `NotFoundException`.

``` php
$app->get("/middleware/{name}", function ($request, $response, $args) {
    if ("fiddlefaddle" === $args["name"]) {
        throw new \Slim\Exception\NotFoundException($request, $response);
    } else {
        return $response->write($args["name"]);
    }
});
```

**Comment by silentworks** [comment]
@matthew-dean rightfully as @tuupola put it, the route was matched, so the router would have done its job, returning a 404 would be the job of the action within that route itself.

**Comment by matthew-dean** [comment]
Okay! Perfect. Thanks for the tips. I saw that in Slim 3, requests and responses were immutable, so I didn't realize you could return them from a route. Thanks!
