### ISSUE TITLE
$request->getAttribute('route') inside Middleware with a POST request

### ISSUE THREAD

**Issue by dcp-dev** [slimphp/Slim#1913]
I have an issue with accessing Route info inside a middleware if my request is send by post.

First of all, I already set inside my settings: `
        'determineRouteBeforeAppMiddleware' => true,`

In my middleware I try : 
`public function __invoke(Request $request, Response $response, $next)
        {
                $requestedRoute = $request->getAttribute('route');
                var_dump($requestedRoute);
        }`

If my request is sent by GET, everything is OK, I get all informations about current route.
However, if I send It by POST, I only retrieve `null`.

The only informations I have are those which are returned by `$request->getAttribute('routeInfo');` But It's very incomplete.

Did I forgot something or is this an unresolved issue ?

**Comment by akrabat** [comment]
Does your route definition accept POST or is it defined as `$app->get()` ?

**Comment by dcp-dev** [comment]
My route definition accept POST of course : 
`$app->post('/users', 'UtilisateurController:createUser' )->setName('create_user');`

**Comment by akrabat** [comment]
Hmmm

It works for me:

``` php
$config = [
    'settings' => [
        'determineRouteBeforeAppMiddleware' => true,
    ],
];
$app = new \Slim\App($config);

$app->post("/test", function ($request, $response) {
    $response->write("Hello world");
    return $response;
})->setName("post-test");

$app->add(function ($request, $response, $next) {
    $response->write("Route: " . $request->getAttribute('route')->getName() . "\n");
    return $next($request, $response);
});

$app->run();
```

Then, curl gives this output:

``` bash
$ curl -X POST http://develop-testbed.slim3.dev/test
Route: post-test
Hello world
```
