### ISSUE TITLE
Wrong information about disabling Slim`s error handling in documentation

### ISSUE THREAD

**Issue by fetzi** [slimphp/Slim#1915]
The section Disabling on the System Error Handler docs page suggests that you can disable slim error handling by unsetting the `errorHandler`key in the container.

> To completely disable Slim’s error handling, simply remove the error handler from the container:
> 
> unset($app->getContainer()['errorHandler']);
> 
> You are now responsible for handling any exceptions that occur in your application as they will not be handled by Slim.

This information is not true for PHP 7+ Throwables because they get handled by the `PhpError` class. If you are using PHP 7+ you have to use the following code to completely disable Slim's error handling:

```
unset($app->getContainer()['errorHandler']);
unset($app->getContainer()['phpErrorHandler']);
```

**Comment by fetzi** [comment]
Do you have looked into this issue?

**Comment by akrabat** [comment]
Fixed by https://github.com/slimphp/Slim-Website/commit/a9a41a8d242f42c8d5e498a7e6746932bb1f3e31
