### ISSUE TITLE
Enforce ResponseInterface from route actions

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1917]
Currently, Slim does not enforce developers to return a ResponseInterface from a route callable.
### Example:

``` php
$app->get('/test', function ($req, $res, $args) {
    print "do stuff";
});
```
### Proper:

``` php
$app->get('/test', function ($req, $res, $args) {
    return $res->write("do stuff");
});
```
### What should happen

``` php
$app->get('/test', function ($req, $res, $args) {
    print "do stuff";
});
```

An exception should be raised. \Exception("Response Interface should be returned from a Route Callable");

**Comment by silentworks** [comment]
This is due to BC, where we allow you to `echo` instead of `return ResponseInterface`.

**Comment by geggleto** [comment]
I thought we had stopped that?

**Comment by silentworks** [comment]
I don't remember it being removed. Maybe add to the 4.0 Roadmap.

**Comment by geggleto** [comment]
I would then propose a different Strategy for capturing the buffer output from the callable and pass it down the chain.

``` php
ob_start();
$callable($req, $res);
$response->write(ob_get_clean());
```

**Comment by geggleto** [comment]
Or we can possibly modify the current one to include a ob_\* capture if the callable doesn't respond with a response interface?

**Comment by geggleto** [comment]
I suppose we could make this a 4.0 thing

**Comment by phpinfo-in-th** [comment]
This is an idea from my developing framework. (Which in fact, came up from this behavior of Slim.)
In my framework, I do not enforce user to return `ResponseInterface` from route callables.
Instead I provide an interface method to handle result and return `ResponseInterface` or throw exception from that.

~~~php
<?php
// ...
class Test extends App
{
    // This will be called if route callables return value
    // which is not ResponseInterface
    public function handleActionResult($result, ResponseInterface $response)
    {
        return parent::handleActionResult($result, $response);
    }
}

$app = new Test();
$app->run([
    '@GET' => [
        '/return-anything' => function () {
            return 'index.html'; // This will be assigned to a property so user can use it later at @done
        },
        '/not-found' => function () {
            return 404; // $response->withStatus(404);
        },
        '/api' => function () {
            return [200, ['success' => true]]; // Special array format to return JSON response
        },
        '/forbidden' => function () {
            return [301, '/']; // Special array format to redirect
        },
        '@done' => function () use ($app) {
            echo $app->mainResult; // Value return from route callable
        },
    ],
]);
~~~

**Comment by akrabat** [comment]
> I would then propose a different Strategy for capturing the buffer output from the callable and pass it down the chain.
> 
> ``` php
> ob_start();
> $callable($req, $res);
> $response->write(ob_get_clean());
> ```

https://github.com/slimphp/Slim/blob/3.x/Slim/Route.php#L324-L326

This would have to be a 4.0 thing anyway.
