### ISSUE TITLE
Data get's cutting with getParsedBody()

### ISSUE THREAD

**Issue by madcyph3r** [slimphp/Slim#1918]
Hello, i have a problem with the getParsedBody() function.

I send data to the slim framework (v. 3) with the unirest framework.

Client Code:

```
$deliveryJSON = $_POST['deliveryJSON'];
$delivery = json_decode($deliveryJSON);

$headers = array('Accept' => 'application/json', 'Authorization' => 'Bearer ' . $_SESSION['login_token']);
$dataForm = Unirest\Request\Body::Form($delivery);
$response = Unirest\Request::post(REST_URL . '/MMMScannerApp/Deliveries', $headers, $dataForm);
```

When i get the the parsed body with the slim framework, the array has only <= 125 objects.
So all object from the position 126  are not in the array.

Server Code:
`$parsedBody = $request->getParsedBody()`

It must be the getParsedBody() function, because in the $request->getBody() there are all data available.
For now i send the json file directly and i call json_decode and work with Std Class objects. But i want to use the parsedBody() function.

**Comment by geggleto** [comment]
Uh... Can you paste some code that is slim related?

I have no idea what Unirest\Request is or what it does...

**Comment by madcyph3r** [comment]
Unirest is a lightweight HTTP request library.

Here is some code (Old code, which i want):

```
$app->post('/Deliveries', function (Request $request, Response $response) {
        // send the whole body, because of the complexity from the object
        $parsedBody = $request->getParsedBody();
        // $articleList is an array. the max size is 125 objects.
        // all object over 125 are not in the array
        $articleList = $parsedBody['articleList'];
        foreach ($articleList as $article) {
               // do what ever
        }
}
```

New code (works, but not really nice)

```
$app->post('/Deliveries', function (Request $request, Response $response) {
        // read the json string
        $body = $request->getBody();
        $parsedBody = json_decode($body);
        $articleList = $parsedBody -> articleList;
        // now $articleList has all Objects
        foreach ($articleList as $article) {
                // do what ever
        }
}
```

**Comment by madcyph3r** [comment]
Hello, i tried another framework (Httpful), there it works without problems ;). So i close this issues now.

**Comment by geggleto** [comment]
glad you were able to get it resolved :)
