### ISSUE TITLE
V4 proposal: Replace Pimple with a variant of Set

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#1922]
Our needs for a DI container are really simple and we don't use anything in Pimple that we don't have in [Set](https://github.com/slimphp/Slim/blob/2.x/Slim/Helper/Set.php).

The main benefits are:
- We don't need our extension class to make it container-interop as Set already implements the two methods required…
- We don't have to worry about Pimple updates.

**Comment by geggleto** [comment]
We still would want to have DI Interoperability... so I guess we would simply create an Interface that people can implement on top of the DI Container of their choice.

**Comment by JoeBengalen** [comment]
Why create an interface? We should implement `container-interop/container-interop`.

**Comment by geggleto** [comment]
@JoeBengalen The set class does way more than containter-interop specifies... need to make sure that either
1.  Slim only uses the `->get()` and `->has()`
2. We provide an interface to guide implementors of other container libraries

### Example

If slim defines a bunch of services using `Set::protect()`, then other DI libraries also need to have that wired in.

This is loosely related too: https://github.com/slimphp/Slim/issues/1923

**Comment by akrabat** [comment]
Closing - not happening.
