### ISSUE TITLE
Some advices required about writing a wrapper around Slim\App

### ISSUE THREAD

**Issue by pyrsmk** [slimphp/Slim#1924]
Hi!

I'm the maintainer of the [Lumy framework](https://github.com/pyrsmk/Lumy). For its future, I've decided to drop all the code and replace it by Slim. But since I want to use the [Chernozem container](https://github.com/pyrsmk/Chernozem) with its ArrayAccess writing style, I had the idea to create a wrapper around Slim.

To make it works like a charm, I'll just have a Lumy class, which will extend Chernozem. In the constructor, I'll instantiate Slim, and add Lumy (which extends Chernozem) as the container of Slim. I'll add a `__call` function to bind all undefined methods to Slim.

But is it enough? I've seen an `__invoke` method in `Slim\App`. Do I need to bind it too? And am I missing some other things?

Thanks a lot for your response ;)

**Comment by geggleto** [comment]
@pyrsmk you need to define the Continer-Interop Interface as well.

Ref: 
https://github.com/slimphp/Slim/blob/3.x/Slim/Container.php#L47
https://github.com/container-interop/container-interop/blob/master/src/Interop/Container/ContainerInterface.php

**Comment by pyrsmk** [comment]
It's already the case ^^ See at Chernozem repo ;)
