### ISSUE TITLE
Let Response::withJson() accept strings

### ISSUE THREAD

**Issue by mgirouard** [slimphp/Slim#1930]
I find it not always practical to pass an array or object to `Response::withJson()`. This is especially true when working with a serializer (like Symfony's or JMS').

I think the spirit of #1276 was to make a single method that made it convenient to set JSON data in the response and automatically set an appropriate header.

Given that `$data` isn't typehinted and is documented as a "mixed" type, can we allow it to accept strings of already encoded JSON too?

**Comment by geggleto** [comment]
`$data` should be an array and not a string, I think this is a docs bug.

Having said that, moving along in the future I think it would make more sense to have views that modify the response.... So Slim would have a `JsonView::write($response, array);` or `JsonView::addHeaders($response)->write($jsonString);`

Similarly, `HtmlView::write();` `HtmlView::addHeaders()`

Having a set few amount of Views then an interface to define more View Classes.

Then we end up with a good list of View Helpers...
- TWIG
- Smarty
- League
- Json
- Html
- CSV... all come to mind.

But I think this is a 4.0 thing not on the 3.x branch

**Comment by mgirouard** [comment]
Thanks for the reply. That's all reasonable.

Do you want me to close this and file a docs bug instead? I can also just PR it since it's going to only be a 1 line diff.

**Comment by akrabat** [comment]
We'd love a PR for the docs :)

**Comment by akrabat** [comment]
This issue is related to #1931.

**Comment by RusAlex** [comment]
@mgirouard @akrabat 

Suppose there is no any error in docs. Response::withJson just pass $data as input to json_encode function. 

> PHP implements a superset of JSON as specified in the original » RFC 4627 - it will also encode and decode scalar types and NULL. RFC 4627 only supports these values when they are nested inside an array or an object.

$data can be also be an object which then will be encoded to json.
