### ISSUE TITLE
Slim Framework 3 Redirect with arguments without using Flash messages

### ISSUE THREAD

**Issue by sowmyanadimpally** [slimphp/Slim#1933]
I am not using any sessions in my website. I found urlFor in slim2. Can i have example where I can redirect to a path along with arguments. I am not using any flash messages.

I used, 
`return $app->response->withAttribute('game' , 'bar')->withRedirect(GLOBAL_DIR_PATH."source/announcements.php/announcements/".$args['UserDetails']);`

gave me a blank page.

**Comment by akrabat** [comment]
What's in your PHP error log

**Comment by sowmyanadimpally** [comment]
No errors logged regarding this issue. It is not getting redirected to the given path when I use withAttribute(). I just want to know that, can I redirect to a path along with arguments.

**Comment by akrabat** [comment]
oh. `Response` doesn't have a `withAttribute()` method…

**Comment by sowmyanadimpally** [comment]
Ok. Give me an example code where I can redirect along with arguments

**Comment by akrabat** [comment]
You could use [`pathFor()`](http://www.slimframework.com/docs/objects/router.html#route-names):

```
return $response->withRedirect($this->router->pathFor('routename', ['game' => 'bar']));
```

**Comment by sowmyanadimpally** [comment]
Redirection is done perfectly but it is not passing any array values to views after redirecting. Can I pass any array values through pathFor to the view(html) page.

**Comment by akrabat** [comment]
You can't pass an HTTP body via a 30x redirect…

**Comment by sowmyanadimpally** [comment]
Ok. Thank you

**Comment by silentworks** [comment]
Closing as I think it was reopened by mistake.
