### ISSUE TITLE
Send Custom Parameters to Middleware 

### ISSUE THREAD

**Issue by rachellcarbone** [slimphp/Slim#1934]
How can I send a parameter to middleware in Slim PHP v3? 

I was using v2 through the following method which passed the Slim App and a string to an anonymous function.

```
$authenticateForRole = function ($role) use ($slimApp) {
    return function () use ($slimApp, $role) {
        APIAuth::isAuthorized($slimApp, $role);
    };
};

 $app->post("/user/update/password/", $authenticateForRole('member'), function () use ($app) {
        AuthController::changeUserPassword($app);
});
```

Inside `APIAuth::isAuthorized` if the user authentication failed I called the `halt` method to stop the Route method from executing at all.

```
$slimApp->halt(401, json_encode($response));
return false;
```

Is there a way to call a middleware _invoke method with `$request, $response, $next` **and** `$role`?

I would want to use this on both route groups and individual routes.

Thank you.

**Comment by geggleto** [comment]
The solution would be using Dependency Injection.

Your Middleware requires things to work, so you construct an instance of your middleware.

### Step 1: Make your middleware class

``` php
class MyMiddleware {
     public function __construct(MyDep $dep) { ... } //setup dependencies

     public function __invoke($request, $response, $next) { ... } // Do work
}
```

### Step 2: Register your middleware with the Slim Container.

``` php
$container = $app->getContainer();
$container[MyMiddleware::class] = function ($c) {
    return new MyMiddleware( ... );
};
```

### Step 3: Use your middleware

``` php
$app->get()->add(MyMiddleware::class); //on a Route
$app->add(MyMiddleware::class); //On the entire application
```

**Comment by rachellcarbone** [comment]
Thank you I'm going to try this out. I don't understand what the `::class` refers to though in the `$container[MyMiddleware::class]` and `->add(MyMiddleware::class);` lines though.

**Comment by geggleto** [comment]
``Class::class` is the namespace constant

**Comment by rachellcarbone** [comment]
Hello again, I've been playing with this but I still cant figure out how to pass a custom parameter to this middle-ware.

I need to pass a string (like 'public', 'member' or 'admin') to this authentication method. The method then logs in the user and checks to see that they have the appropriate rights to see.

The goal is to call `$authenticateForRole('member')` or add this as middle ware on a route or group basis so that each route can have individual permissions.

**Comment by geggleto** [comment]
``` php
$member = function ($role) {
    return function ($req, $res, $next) {
        return $next($req, $res);
    };
};

$app->get()->add($member('member'));
```

**Comment by rachellcarbone** [comment]
Ohhhhh.... lol I was over complicating it.

Thank you so much for the help @geggleto !

**Comment by sn0rcha** [comment]
hmm... this doesn't seem to be working with the latest version of slim 3 - i get:

```
 Middleware must return instance of \Psr\Http\Message\ResponseInterface
```

with the above function. Any ideas?

**Comment by geggleto** [comment]
@sn0rcha this is only valid for v2

**Comment by sciamano89** [comment]
I asked for this in the Slim Discourse, but nobody has responded yet, so I decided to try on here.
**Is there an equivalent for v4?** I'm using the approach described above (Middleware as class and adding it to the DI Container). I just don't know how to pass args to it.

Here's what I'm trying to achieve:
```php
$app->get('/myroute', MyController::class . ':myAction')
    ->add(MyMiddleware1::class)
    ->add(MyMiddleware2::class, ["hello", 123]);
```

And here's what I have so far:
```php
 $app->get('/myroute', MyController::class . ':myAction')
     ->add(MyMiddleware1::class)
     ->add($this->get(MyMiddleware2::class)->setArgs(["hello", 123]));
```
where `setArgs()` is something like this (modifies the instance in the container and returns it):
```php
function setArgs(Array $args){
    $this->args = $args;
    return $this;
}
```
Any help is appreciated! Thanks
