### ISSUE TITLE
Documentation about controller routing strategy missing

### ISSUE THREAD

**Issue by PauloPhagula** [slimphp/Slim#1936]
The approach outlined in [DI Factories for Slim Controllers](https://dzone.com/articles/di-factories-for-slim-controllers) article by @akrabat which allows a single controller to have many actions is not mentioned in the documentation under the Router section.

Furthermore, a very important detail about the usage of the this strategy which the article misses but can be found outlined in the http://stackoverflow.com/questions/36504033/slim-framework-3-how-to-inject-logger-to-route-controller thread is:

> Note that if you make the format route callable be a string of 'class name' colon 'method name', then Slim 3 will call the method for you after extracting the controller class from the DI container. If the class name is not a registered key with the container, then it will instantiate it and pass the container to the constructor.

I'd like to suggest adding this method/technique on the documentation about routing as I believe it would be invaluable to newcomers like myself.

Thanks.

**Comment by netmou** [comment]
metoo

**Comment by akrabat** [comment]
We'd love someone to submit a PR to the Slim-Website repository for this.

**Comment by PauloPhagula** [comment]
Going again through the docs, I found out this was already documented on the [Router page, under the Container Resolution section](http://www.slimframework.com/docs/objects/router.html#container-resolution).
