### ISSUE TITLE
Class Slim_Http_Cookie – Fatal error

### ISSUE THREAD

**Issue by maxmert** [slimphp/Slim#194]
Hello!

I'm trying to run this code (url is http://site.com/0.1/blog.php/)

<code>
    ini_set('display_errors', '1');

```
require '../Slim/Slim.php';

$slim_settings = array(
    'mode'               => 'development',
    'debug'              => true,
    'log.enable'         => false,
    'cookies.encrypt'    => false,
    'session.handler' => null
);
$app = new Slim();

$app->get('/', function () {
    echo 1;
});

$app->run();
```

</code>

After that I get a browser error <b>Erorr 330 (net::ERR_CONTENT_DECODING_FAILED): unknown error</b>

If i comment <b>$app->run();</b> then I get Slim error <i>Fatal error: spl_autoload(): Class Slim_Http_Cookie could not be loaded in /home/sites/maxmert.com/subdomains/api/httpdocs/Slim/Http/CookieJar.php on line 285</i>.

Please, help me to get through it! Thank you!

**Comment by codeguy** [comment]
If you are on PHPFog, make sure you are using the `http.version` setting so that its value is "1.0". If you are not on PHPFog, I'll have to investigate further.

Josh

**Comment by maxmert** [comment]
Thank you for your response!
I don't use any frameworks like PHPFog.

I use PHP 5.3.3-7+squeeze3 with Suhosin-Patch, Zend Engine v2.3.0, mcrypt 2.6.8-1. Are there any other dependences for good work? I made all permissions to 777 just in case.

Thanks again!

**Comment by nansenat16** [comment]
The load error , upgrade PHP will be fix it

https://github.com/codeguy/Slim/issues/188

**Comment by codeguy** [comment]
This will be resolved in the next stable release. It is already resolved in the **develop** branch. Closing this out. If you have any further questions on this, please don't hesitate to post a question to the support forum at http://help.slimframework.com.
