### ISSUE TITLE
SLIM FRAMEWORK! Working fine in Localhost, but not in web hosting. 

### ISSUE THREAD

**Issue by konskript** [slimphp/Slim#1941]
I was half way on my project. And I tried to put it on live hosting. And now, I encountered  a problem that when I use my login page, and submit the form.. It didn`t redirect to any page, instead it returned me the same routing page with a blank content/page. 

I have a scenaro..
![error](https://cloud.githubusercontent.com/assets/20536714/17203741/baa4fd88-54d3-11e6-9c58-e86f20c8a189.png)

**Comment by dopesong** [comment]
Which version of slim framework your are using? Any code example?

**Comment by konskript** [comment]
@dopesong  the latest version. slim v3.0 
I follow the tutorial of codecourse authentication slim 3. 
here is some reference for the videos. https://www.youtube.com/watch?v=RhcQXFeor9g

**Comment by dopesong** [comment]
Yeah, but without code example we won't be able to help you :)

**Comment by konskript** [comment]
Well, I can give you the code. but where do I start? from routing or the index? .htaccess?

**Comment by dopesong** [comment]
You should try to debug at which part of request you get blank screen. Maybe errors disabled in server and you can't see any?

**Comment by konskript** [comment]
no. there`s is no errors nor in server errors. the path_for() is good. 
![check3](https://cloud.githubusercontent.com/assets/20536714/17206190/1aa25b74-54e1-11e6-8841-b13a81863585.PNG)

**Comment by dopesong** [comment]
Try to add logger and debug steps where it stops. Maybe it even stopped at User::create?

**Comment by konskript** [comment]
It works perfectly fine. After I submit the button. It created another data in my database. But it still redirect me to the same pages with blank content..

**Comment by akrabat** [comment]
if you get a blank page, you either have no output created or, more likely, a PHP error has occurred.

Do you have the [`displayErrorDetails`](http://www.slimframework.com/docs/objects/application.html#application-configuration) setting set to `true`?

**Comment by matthewtrask** [comment]
do you have a .htaccess file in the root?

**Comment by konskript** [comment]
@akrabat  yes~! I set it into true.. .. It was perfectly fine in my local before I make it live website.
![check4](https://cloud.githubusercontent.com/assets/20536714/17234417/58091e0a-556b-11e6-85d0-92b9416b5764.PNG)

**Comment by konskript** [comment]
@rocketpastsix yes, I was following the tutorial of codecourse: Authentication Slim 3
here is some reference videos. https://www.youtube.com/watch?v=RhcQXFeor9g

 It was perfectly fine in my local before I make it live website.

**Comment by konskript** [comment]
@akrabat here is my live website. 
http://web-pos.kolwebs.com/login 
username: 123123
password: 123123

code for my LoginController.
![login1](https://cloud.githubusercontent.com/assets/20536714/17238625/e0619178-558f-11e6-8b07-0669c4c48828.PNG)
![login2](https://cloud.githubusercontent.com/assets/20536714/17238624/e0618a16-558f-11e6-85f4-fc2a8d1411b6.PNG)

**Comment by Tpojka** [comment]
Try to follow method naming convention. It is `pathFor()`.

**Comment by konskript** [comment]
@Tpojka Its still not working.

**Comment by froschdesign** [comment]
@konskript 
You can check the redirects with the Developer tools of your browser. For example with [Chrome or Opera](https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/resource-loading#network-panel-overview).

**Comment by konskript** [comment]
@froschdesign  do you want me to record things? or to see if my login page is working? if its 404 responds?

Here is the image of my screenshot about dev. tools
![1](https://cloud.githubusercontent.com/assets/20536714/17239311/b1e24b34-5595-11e6-9054-45b3da763ae4.PNG)

**Comment by froschdesign** [comment]
@konskript 

>  or to see if my login page is working? 

Is working after you submitted the button.

**Comment by konskript** [comment]
@froschdesign yes! Login page is working. Its just that it returns me blank page. And the Url was still in the /login.. This is just my theory, myy problem was redirecting to another page after submitting a form..

**Comment by akrabat** [comment]
Try debugging the old fashioned way.

In `postLogin`, add `echo "here"; exit;` immediately after the opening brace. If that works, then move it to immediately before the `if (!$verify) {` line. If that works, then var_dump() each pathFor call and check that they return the correct string.

**Comment by froschdesign** [comment]
@konskript 

> my problem was redirecting to another page after submitting a form

You should check this with the browser developer tools. There you can see, if a redirect is performed.

**Comment by konskript** [comment]
@froschdesign  Well, sad to say. I`m still not familiar using dev. tools.

**Comment by konskript** [comment]
@akrabat Ok, Im going to try it..

**Comment by konskript** [comment]
@akrabat I don`t know if this is the correct way..

See if it does.

![3](https://cloud.githubusercontent.com/assets/20536714/17240191/5e35597a-559c-11e6-8b29-f6f0079421a7.PNG)

The result.
![2](https://cloud.githubusercontent.com/assets/20536714/17240204/6e8868d0-559c-11e6-8523-6dd4ec4db0c5.PNG)

**Comment by konskript** [comment]
Anyone? I need some help!

**Comment by geggleto** [comment]
White Page means...

### 1. Fatal error

How to verify:
- Check Web Server Log Files
- Enable Error Reporting

### 2. No Content

How to verify:
- Use Chrome's developer tools (f12) to verify the status code of the page
- Blank page with status code 200 means the code path results in no content being outputted to the browser. A status code of 5xx means there is a problem in your PHP code.

**Comment by konskript** [comment]
@geggleto How to verify it? Should I click the submission form first or after the load of the php?

**Comment by konskript** [comment]
@geggleto I don`t know what kind of problem it is. Because there is no page display. And in Dev. Tools. It display status 200.. 

If you don`t mind. Can you try it?
Here is my site.
http://web-pos.kolwebs.com/login
username: 123123
password: 123123

**Comment by akrabat** [comment]
@konskript,

The output after submitting is a 200 OK status with this text in the body:

```
<!-- <!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<input type="text" name="">
</body>
</html> -->
```

You can see this if you view source.

**Comment by konskript** [comment]
@akrabat yeah I know. I inspect element it. And it returns that. I don`t know where is the error. But my theory is that, it has a problem with redirect..

**Comment by geggleto** [comment]
There is no redirect.

Can you please list out ALL of the routes you have defined?

**Comment by konskript** [comment]
@geggleto 

Here is some of my codes of LoginController.php 
![login1](https://cloud.githubusercontent.com/assets/20536714/17250305/4f812e42-55d6-11e6-8fe1-b4022fcea298.PNG)
![login2](https://cloud.githubusercontent.com/assets/20536714/17250306/4f81799c-55d6-11e6-93af-7b0d166b0c85.PNG)

Here is some routes.
![routes](https://cloud.githubusercontent.com/assets/20536714/17250316/5cf3a6fe-55d6-11e6-98f5-a0a645011715.PNG)

Here is my Home page
![index](https://cloud.githubusercontent.com/assets/20536714/17250335/6f10a56c-55d6-11e6-9345-3bb1476dab25.PNG)

Here is some of my forms..
![front](https://cloud.githubusercontent.com/assets/20536714/17250338/7434ae58-55d6-11e6-8be8-c4d157ba32c5.PNG)

**Comment by geggleto** [comment]
Okay... but I still need all of your routes... that is only a few of them I suspect ;)

**Comment by geggleto** [comment]
Is this project on something like GitHub?

There is clearly a problem in your code and without seeing ALL of it, I doubt I can help further.

**Comment by konskript** [comment]
@geggleto  what do you mean all routes? 

Do you mean by this.. 
![allroutes](https://cloud.githubusercontent.com/assets/20536714/17250441/f8cb656c-55d6-11e6-8992-553e0503ee65.PNG)

**Comment by geggleto** [comment]
Yup, all of them :)

**Comment by konskript** [comment]
@geggleto Well, this is a project of Authenticate Slim 3 from codecourse. I was trying to use his code to build an app for myself as a start to this micro framework..

**Comment by geggleto** [comment]
I highly suspect that there is a catch-all route that is getting executed instead of your controller one.

**Comment by konskript** [comment]
What do you mean? Can you elaborate it that even newbie can understand..

**Comment by geggleto** [comment]
There is likely a route like....

``` php
$app->post("/{catch:+}"); 
```

That is getting executed before your post Login.

**Comment by geggleto** [comment]
Are you uploading your code changes to your production server after you make changes locally.

**Comment by konskript** [comment]
Well, I`m new to this framework. And this is my first time framework.. So I hope if you don`t mind, can you tell me more about it? I still have a difficulties on understanding this..

**Comment by konskript** [comment]
I`m not coding in local right.. I was changing every code in the production stage.

**Comment by geggleto** [comment]
I need you to do 2 things.
1. List All of the application routes! Hopefully you have them all in one file.
2. Make sure you update your "production" server with all of the code changes you have made.

**Comment by konskript** [comment]
1.) All my application routes was in my routes.php
2.) I was coding in production now.

**Comment by geggleto** [comment]
@konskript the recent screenshot you posted lacks some of the routes... please pastebin, or gist your routes.php

https://gist.github.com/

http://pastebin.com/

**Comment by konskript** [comment]
@geggleto <script src="https://gist.github.com/konskript/ff504c9ae7c1ac0b853877023c9fe8be.js"></script>

**Comment by konskript** [comment]
@geggleto how to send the gist to you?

**Comment by konskript** [comment]
@geggleto https://gist.github.com/konskript/b190e88a1b57aff7346f5e8e4a42ece9

**Comment by geggleto** [comment]
Thank you.
At the bottom of that file... remove lines 233 -> all the way to the end and retry plz.

**Comment by konskript** [comment]
It works. ! Thanks. WOW! It was a stupid of mine.

**Comment by geggleto** [comment]
:D Hooooorayyyy!

**Comment by konskript** [comment]
Thanks! but there is still a problem. :(

**Comment by geggleto** [comment]
Yeah it doesn't look like its rendering your error message but at least it's redirecting ;) more work for you to do!

**Comment by konskript** [comment]
@geggleto yeah. Its good now like in my local.Big help!

**Comment by konskript** [comment]
@geggleto When I submitted my form.. There is this default_timezone_get() and when I change it to set.. and set it to default_timezone_set('Manila/Asia')

it appears me this.. 
![another](https://cloud.githubusercontent.com/assets/20536714/17251943/454509a6-55dd-11e6-916b-8f56262ebf75.PNG)

**Comment by geggleto** [comment]
No idea. why are you tinkering with the timezones ?

**Comment by konskript** [comment]
wait. I will printscreen the first error it made.. It happen everytime I create a new user or a submission form has been trigger..

**Comment by konskript** [comment]
Okay. Sorry.. My bad. But before my routes.php fix.. It happened that the carbon.php line 172 must set a default timezone.. Well nevermind. As long as it was perfectly fine.. Thank you!

Anyway. Why is that a problem in my routes.php that I commented at the last part?

**Comment by geggleto** [comment]
@konskript you didn't comment out the last part.
You terminated the php page on line 233... which then lead php to output the contents of 234-> before the framework was started.

When it output the contents of the page it sent out the default php headers which includes as status code, and since you cannot RESEND the status code, the 301 is ignored by php since it had already sent the headers, leading to a blank page which is what the content of the lines 234+ ended up being.

**Comment by konskript** [comment]
Ohhh..I see, thanks for the info.

Sir, @geggleto Do you have any idea about file upload with the use of slim framework, and as well an Ajax with use of bootstrap modal.. I hope you can suggest me some of tutorials related with it..

**Comment by geggleto** [comment]
konscript, the boostrap docs are really good and modals are completely UI.

you can use forms to interact with your API.

You should probably read up about REST API Development.

http://www.restapitutorial.com/

File upload in Slim v3... https://akrabat.com/psr-7-file-uploads-in-slim-3/

**Comment by konskript** [comment]
@geggleto  thanks for the referral..
