### ISSUE TITLE
SLIM FRAMEWORK! Working fine in Localhost, but not in web hosting

### ISSUE THREAD

**Issue by konskript** [slimphp/Slim#1942]
I was half way on my project. And I tried to put it on live hosting. And now, I encountered  a problem that when I use my login page, and submit the form.. It didn`t redirect to any page, instead it returned me the same routing page with a blank content/page. 

I have a scenaro..
![error](https://cloud.githubusercontent.com/assets/20536714/17203741/baa4fd88-54d3-11e6-9c58-e86f20c8a189.png)

**Comment by dopesong** [comment]
Duplicate #1941
