### ISSUE TITLE
/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 172

### ISSUE THREAD

**Issue by konskript** [slimphp/Slim#1945]
I don`t know why, there is no problem in my create method. 
But in my update method appear an error like this.. please refer to first image. And the second image is my small code of item update. 

![time1](https://cloud.githubusercontent.com/assets/20536714/17326301/fdc334fa-58e2-11e6-9a39-fb2193523268.PNG)
![time2](https://cloud.githubusercontent.com/assets/20536714/17326302/fdca66d0-58e2-11e6-85d0-b13cad960c73.PNG)

**Comment by tuupola** [comment]
Probably should ask from Carbon people.

https://github.com/briannesbitt/Carbon

**Comment by dopesong** [comment]
Its releated with php config, not code: http://stackoverflow.com/questions/13033407/php-ini-default-timezone-vs-date-timezone

**Comment by konskript** [comment]
@tuupola thanks for referring.

**Comment by konskript** [comment]
@dopesong thanks for referrering.

**Comment by konskript** [comment]
@dopesong but still, I dont quietly understand this things..

**Comment by dopesong** [comment]
Change your default timezone in your php.ini :)

**Comment by konskript** [comment]
Why it has been closed? @akrabat

**Comment by dopesong** [comment]
Because it was answered and its not slim related @konskript

**Comment by konskript** [comment]
@dopesong well, its in slim vendor right?

**Comment by akrabat** [comment]
@konskipt This is not a problem with Slim and how to fix it is displayed in the message provided by the [warning](https://cloud.githubusercontent.com/assets/20536714/17326301/fdc334fa-58e2-11e6-9a39-fb2193523268.PNG):

> You are _required_ to use the date.timezone setting or the date_default_timezone_set() function.

i.e. update your php.ini file and add a timezone to the `date.timezone` setting in there.

**Comment by akrabat** [comment]
> @dopesong well, its in slim vendor right?

The `vendor` directory contains code from other libraries that you have installed. In this case a library called "Carbon" from someone called "nesbot". i.e. it is not Slim code.

**Comment by konskript** [comment]
@akrabat well, I see, I thought, I should not revise anything in the vendor.. Because If I change anything from vendor.. It would destroy under those code that I changed.. Well anyway. Sorry, my bad for asking not related to slim. But thanks anyway, I learned a lot.. :+1:  I`m still learning this slim. :D

**Comment by akrabat** [comment]
@konskript You do not need to edit anything in vendor to solve this issue. Please read [this comment](https://github.com/slimphp/Slim/issues/1945#issuecomment-236874882) again.

**Comment by konskript** [comment]
Ok, I see.. Thanks @akrabat, @dopesong and @tuupola ! You guys are a big help to the community. :+1:
