### ISSUE TITLE
Doc Improvement

### ISSUE THREAD

**Issue by SusanthCom** [slimphp/Slim#1951]
Doc Improvement Suggestion

Location >> http://www.slimframework.com/docs/objects/router.html
Section : Route groups

After the code Example, it is written :

> Note inside the group closure, $this is used instead of $app. Slim binds the closure to the application instance for you, just like it is the case with route callbacks.

I wish, if it was :

> Note inside the group closure, $this is used instead of $app. Slim binds the closure to the application instance for you, just like it is the case with route callbacks binds **with container instance.**
> - inside group closure, $this is binded  to the instance of  'Slim\App'
> - inside route callbacks, $this is binded  to the instance of 'Slim\Container'

**Comment by silentworks** [comment]
Thats a good suggestion, please create a Pull Request on the Slim-Website repo please. Here is a link to the file you need to modify https://github.com/slimphp/Slim-Website/blob/gh-pages/docs/objects/router.md

**Comment by SusanthCom** [comment]
@silentworks  Done 👍 https://github.com/slimphp/Slim-Website/pull/169

**Comment by silentworks** [comment]
Thanks again.

**Comment by SusanthCom** [comment]
@silentworks  Minor Fix Done. https://github.com/slimphp/Slim-Website/pull/170
Please Approve.
