### ISSUE TITLE
Headers are not set

### ISSUE THREAD

**Issue by oscarr-reyes** [slimphp/Slim#1958]
Just trying out the V3 version of this framework by doing some tests, including adding some headers.. but i was unable to change or add any header.

File example is simple, it has this code:

``` PHP
<?php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response

$app->get("/users", function(Request $request, Response response){
    $data = [];

    $response->withJson($data);
    $response->withHeader("Random-Header", "some value");

    return $response;
});
```

in the client the response does not have the header i just set, just any other normal header with `content-type: text/html` which should be `content-type: application/json` like the documentation says.

I bother to debug the headers that are being sent by using `$response->getHeaders()` but the only thing it has is an array that defines the `content-type` with `text/html` as value which is not even overwritten if using `$response->withHeader("Content-type", "application/json");

OS: Linux/Debian 16.04 x64
Host: Apache 2.4.13
Language: PHP 7.0.9
Framework: Slim 3.5.0

**Comment by akrabat** [comment]
Slim 3 uses [PSR-7](http://www.php-fig.org/psr/psr-7/) which has [immutable request and response objects](http://www.php-fig.org/psr/psr-7/meta/#why-value-objects). As such you need to reassign whenever you use a "with" function.

Try:

``` php
<?php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response

$app->get("/users", function(Request $request, Response response){
    $data = [];

    $response = $response->withJson($data);
    $response = $response->withHeader("Random-Header", "some value");

    return $response;
});
```

**Comment by oscarr-reyes** [comment]
My bad, it was my fault for not doing enough research.. it worked and thanks alot for your reply

**Comment by akrabat** [comment]
No problem :)

Good luck with your use of Slim.
