### ISSUE TITLE
Can I use error templates ?

### ISSUE THREAD

**Issue by 84564221** [slimphp/Slim#196]
Is it possible to detect any error-messages (403,404) before SLIM posts his default 404-message?

index.php example:

$app->get('*', function (iserror) use ($app) {
    $app->render('error404.tpl', array('mainTitle' => 'Error 404'));
});

?

**Comment by codeguy** [comment]
This is a great use-case for the middleware in v1.5.2+. You can write middleware to inspect the response status; if the status is 4xx, you can overwrite the response body as you see fit. Bear in mind that middleware surrounds the Slim application. Middleware does not act within the Slim application.
