### ISSUE TITLE
Regex simplification

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#1960]
Just because...

In the callable resolver, there is a regex that matches a callable string. This is based on that which is in the PHP.net documentation.

The aim of the regex is to validate the latter part of a callable string and split it into class and method parts.

As the callable resolver is not required to cover validation of a class/method name (as PHP won't allow invalid class/method names and would error long before the regex is processed), I propose we simplify the regex to remove the superfluous computation. I also propose we use correct start and end qualifiers for a string, as we are only interested in single line strings, and not multiline as defined by our use of `^$`.

```
'!\A([^\:]+)\:([^\Z]+)\Z!'
```

Another reason to choose this, is that by using the current regex, we should have implemented tests to prove it's validity by providing class and method names to test all of it's possible outcomes. This is a silly waste of time as we don't need to test validity with the regex.

I'm open to comment on this, and discussion.

NB: This regex still passes all current tests.

**Comment by geggleto** [comment]
Can we get a PR? :D
