### ISSUE TITLE
getQueryParams

### ISSUE THREAD

**Issue by elvispdosreis** [slimphp/Slim#1961]
$request->getQueryParams();

http://127.0.0.1:8082/api/user?user.name=Elvis&user.city=Rio+Preto

$queryParams = [
  'user_name' => 'Elvis',
  'user_city' => 'Rio Preto'
]

the right would return
$queryParams = [
  'user.name' => 'Elvis',
  'user.city' => 'Rio Preto'
]

**Comment by akrabat** [comment]
That's a PHP thing isn't it? What's in `$_GET` ?

**Comment by elvispdosreis** [comment]
Yes the parse_str function converts the data $ _GET

**Comment by akrabat** [comment]
I mean, Can you var_dump $_GET for me please?

**Comment by elvispdosreis** [comment]
the var_dump has the same output of slim however in debug appears as sent.
check the picture

var_dump
array (size=2)
  'user_name' => string 'Elvis' (length=5)
  'user_city' => string 'Rio Preto' (length=9)

![image](https://cloud.githubusercontent.com/assets/15267623/17671734/e7e0a33c-62ee-11e6-899f-d42273457d8c.png)

**Comment by akrabat** [comment]
if `var_dump($_GET)` shows the `.` replaced with a `_`, then it's a PHP behaviour, not a Slim one.

**Comment by akrabat** [comment]
Ah yeah. Here we go: http://www.php.net/manual/en/language.variables.external.php#language.variables.external.dot-in-names

**Comment by elvispdosreis** [comment]
thanks

2016-08-15 13:53 GMT-03:00 Rob Allen notifications@github.com:
