### ISSUE TITLE
Replacing Route "callable"

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1962]
It came to mind that it might be required to replace a "callable" on a Route.

We should add a `Route::setCallable(callable/string $callable)`

This would be a step forward in fixing/adding #1938

**Comment by geggleto** [comment]
For example: If I have a website A that implements a bunch of end-points... and I install package B that overrides some of the end-points... currently that process is a non-starter.

**Comment by akrabat** [comment]
Fixed with #1963
