### ISSUE TITLE
invalid Uri produced on misconfigured server

### ISSUE THREAD

**Issue by nyamsprod** [slimphp/Slim#1968]
## Issue summary

When using Slim 3.x on a misconfigured server the `Slim\Http\Request` object returns an invalid URI. 
By Misconfigured I mean the server did not return any value for `$_SERVER['HTTP_HOST']` or `$_SERVER['SERVER_NAME']`.
## Standalone code to reproduce the problem

``` php
$app->get('/test', function ($request, $response) {
    $json = json_encode([
        'uri' => (string) $request->getUri(),
        'host' => $request->getHeaderLine('Host'),
        'server_name' => $request->getServerParams()["SERVER_NAME"],
    ], JSON_PRETTY_PRINT);
    $response = $response->withHeader('Content-Type', 'application/json');
    $response->getBody()->write($json);

    return $response;
});
```
### Expected result

A 500 error page or an Exception to be thrown
### Actual result

```
{
    "uri": "http:\/test",
    "host": "",
    "server_name": ""
}
```

**Comment by geggleto** [comment]
This is not an error.
