### ISSUE TITLE
UploadedFile.php moveTo() function throwing exception on windows with php.exe built in webserver

### ISSUE THREAD

**Issue by vyruz1986** [slimphp/Slim#1969]
Hi,

I spent the better part of today troubleshooting a problem encountered with this framework.
We are developing a php webapp in Visual Studio and use the DevSense php tools plugin to debug our PHP code. This plugin uses php.exe's built-in webserver and xdebug to debug php code.

It seems that for some reason, php's is_writable() call incorrectly returns false in our situation..
I found the following bug on the PHP bug tracker: https://bugs.php.net/bug.php?id=68926 and I've added a comment (see comment of 26/08/2016) describing our problem.
On our test webserver which also runs on windows but uses apache instead of PHP's built in webserver the function seems to work fine.

Just thought It would be good to a have a record of this problem on this page as well, as other windows users might run into it.

**Comment by geggleto** [comment]
Thanks :) But I am going to close this because we really try not to encourage the php built-in webserver as it has a lot of issues.
