### ISSUE TITLE
Error when php.ini's always_populate_raw_post_data is not set to -1

### ISSUE THREAD

**Issue by thiagodp** [slimphp/Slim#1970]
I checked this problem with versions `3.0` to `3.5`, using PHP `5.6`. When `php.ini`'s `always_populate_raw_post_data` is not set to `-1`, these warnings/errors occour:

```
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  session_start(): Cannot send session cache limiter - headers already sent in <b>C:\...\index.php</b> on line <b>3</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'RuntimeException' with message 'Unexpected data in output buffer. Maybe you have characters before an opening &lt;?php tag?' in C:\...\vendor\slim\slim\Slim\App.php:552
Stack trace:
#0 C:\...\vendor\slim\slim\Slim\App.php(344): Slim\App-&gt;finalize(Object(Slim\Http\Response))
#1 C:\...\vendor\slim\slim\Slim\App.php(298): Slim\App-&gt;process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#2 C:\...\index.php(170): Slim\App-&gt;run()
#3 {main}
  thrown in <b>C:\...\vendor\slim\slim\Slim\App.php</b> on line <b>552</b><br />
```

It would be interesting to check the ini configuration in `Slim\App.php` and throw an exception with an appropriated message. Example:

``` php
$value = ini_get( 'always_populate_raw_post_data' );
if ( false !== $value && "-1" !== $value ) {
    throw new \RuntimeException( 'You must set the key "always_populate_raw_post_data" to -1 in your php.ini file before using Slim.' );
}
```

Additionally, to include this information in Slim documentation (maybe in the Getting Started section).

**Comment by mathmarques** [comment]
This problem isn't related to Slim. It's because php printed the Deprecated message before Slim send the response(causing the header error). You could just change PHP error report config on php.ini or:

``` php
error_reporting(E_ALL ^ E_DEPRECATED);
```

**Comment by thiagodp** [comment]
@mathmarques  Please try to comment the line `always_populate_raw_post_data` in your php.ini to see what happens.
The warnings are not the problem. This line is (Slim\App.php, line 552):

```
<b>Fatal error</b>:  Uncaught exception 'RuntimeException' with message 'Unexpected data in output buffer. Maybe you have characters before an opening &lt;?php tag?' in C:\...\vendor\slim\slim\Slim\App.php:552
```

**Comment by thiagodp** [comment]
@mathmarques Adjusting the error reporting the way you informed also does the trick. However, when this report option is not set, the problem occurs. So, I think Slim could check for both, in order to inform better about problems like these.

**Comment by akrabat** [comment]
Slim isn't going to check for and provide a warning for every deprecated PHP ini directive.

The deprecation of always_populate_raw_post_data is in the migration guide: http://php.net/manual/en/migration56.deprecated.php

**Comment by thiagodp** [comment]
Of course not, and I didn't ask for this. But Slim could include some common problems in their checkings or, at least, in the documentation (Getting Started, FAQ, or whatever). This can save developers' time and avoid unnecessary Issues.

**Comment by adriano-ghezzi** [comment]
imho there should be a better error message.
I lost a lot of time to check files for "unexpected" characters.

by the way I tried all the workarounds
commented out or set to on|off|-1 ;always_populate_raw_post_data
and set `error_reporting(E_ALL ^ E_DEPRECATED);
`
Nothing to do error still remains

I was an happy user of Slim 2.0 never had any problem.

**Comment by akrabat** [comment]
@adriano-ghezzi This is related to a change in PHP 5.6 and not Slim.

In your php.ini file, you also need to remove the leading `;` before `always_populate_raw_post_data` as that semi-colon means that your change doesn't have any effect. You also need to restart your web server when you change a php.ini setting.

The 'Unexpected data in output buffer.' exception is from Slim. To stop this happening, update your settings:

``` php
$config = ['settings' => [
    'addContentLengthHeader' => false,
]];
$app = new Slim\App($config);
```
