### ISSUE TITLE
Flash doesn't work when using a URL that takes parameters

### ISSUE THREAD

**Issue by mrdarrengriffin** [slimphp/Slim#1971]
```
$app->get('/article/:seoName',function($seoName = "contents") use ($app){

        $article = Article::where('url',$seoName)->first();
        if(!$article){
    $app->flash('error','This article could not be found.');
    $app->response->redirect($app->urlFor('home'));
        }

    })->name('article');
```

That's my code. When I use the flash followed by a redirect, the flash does not appear. 

I have tried dumping the flash variable and nothing seems to be there.

I know for a fact that the flashes do work, as the login page shows them fine. It's only when I use any URL that takes parameters, like shown above.

I have experienced this issue before but have not found a fix yet.

Any ideas?

**Comment by mrdarrengriffin** [comment]
Update:  Here is the code I had when it wasn't working

```
    use MrDarrenGriffin\Article\Article;

    $app->get('/article/:seoName',function($seoName = "contents") use ($app){

       $article = Article::where('url',$seoName)->first();
        if(1 == 1){
        $app->flash('error','That article was not found');
            $app->response->redirect($app->urlFor('home'));
            }
       print_r($articles);

        })->name('article');
```

It seems that if there is an error present after the flash and redirect, the flash will not show (I don't know why).

See that when I print $articles, I should be printing $article.

Typo, yes. Expected behaviour of Slim, unsure...

Thought this update may help others who face the same issue

**Comment by geggleto** [comment]
Closing as resolved.
