### ISSUE TITLE
use route arguments in the application middleware

### ISSUE THREAD

**Issue by nicolas-wallerand** [slimphp/Slim#1973]
hello 

use route arguments in the application middleware ?

**Comment by akrabat** [comment]
Hi, 

You need to set `determineRouteBeforeAppMiddleware` to true in your settings:

``` php
$config = [
    'settings' => [
        'displayErrorDetails' => true,
        'determineRouteBeforeAppMiddleware' => true,
    ],
];
```

You now have access to the resolved route from `$request->getAttribute('route');` in your middleware.

**Comment by nicolas-wallerand** [comment]
Thank you :-)
