### ISSUE TITLE
CallableResolver class should not be final

### ISSUE THREAD

**Issue by plashenkov** [slimphp/Slim#1974]
What is the reason for CallableResolver class to be final? I really want just to extend it. It has a rich logic in its `resolve` method, I would like to keep it, not to duplicate it. All I want to do is to prepend controller classes with controllers’ namespace, that’s all:

```
$app->setControllersNamespace('app\controllers');
$app->get('/', 'HomeController:index');
```

It turns out now that I must duplicate all the logic.

**Comment by akrabat** [comment]
Given that  `CallableResponder` implements just the single method in `CallableResolverInterface`, declaring it `final` is acceptable. 

It can always be composed into another class that implements `CallableResolverInterface` if the input or output to it needs to be changed.
