### ISSUE TITLE
Abstract class or Interface for Middleware

### ISSUE THREAD

**Issue by dannykopping** [slimphp/Slim#198]
Maybe I'm not understanding the latest addition in the `develop` branch, but to me it would seem like a good idea to have a simple abstract class or interface to define the default or prescribed behaviour of custom `middleware` classes

**Comment by codeguy** [comment]
Agreed. I'll add an abstract `Slim_Middleware_Base` class that all middleware should extend.

**Comment by codeguy** [comment]
This is done.

https://github.com/codeguy/Slim/commit/be3c90edf0c625f928acb3801686154fab37bb5c

All middleware must implement `Slim_Middleware_Interface`.
