### ISSUE TITLE
slim frame work doesn't work well in web hosting 

### ISSUE THREAD

**Issue by ahmedkaballo** [slimphp/Slim#1981]
hi , slim framework works well in my local host , but when i try to use it in web hosting some functions don't work i don't know why

**Comment by JoeBengalen** [comment]
Can you be a bit more specific? What doesnt work? Which version of Slim are you using?

**Comment by ahmedkaballo** [comment]
i'm using version 2.3.5 , the main thing that causes the problem is redirecting (i.e it doesn't redirect me to the index.php) though it works well in local host . i'm using the following .htaccess file
![captursssssse](https://cloud.githubusercontent.com/assets/19692038/18228838/74100900-7268-11e6-8955-17fc9ceab730.PNG)
i'm hosting the web app at infinityfree.com
they use php version 5.6.23 .

**Comment by JoeBengalen** [comment]
Make sure the host supports htaccess and read docs about it. Just uploading the file might not be enough

**Comment by ahmedkaballo** [comment]
ok thanks alot
sorry but can i show you my code ? maybe the problem from slim not from redirection .mainly i have a chat app and when i open the main page it loads the chat rooms but it says "unable to fetch topic messages"
here is my index.php
![index](https://cloud.githubusercontent.com/assets/19692038/18230155/68c173b2-729b-11e6-8cdd-7e1f4cf2f689.PNG)
and this is the function "getChatroomMessages"
![chatroom](https://cloud.githubusercontent.com/assets/19692038/18230274/68e810a0-729e-11e6-9647-e96b7e12d143.PNG)
and this is the DB_handler that selects the messages from database
![dbhandler](https://cloud.githubusercontent.com/assets/19692038/18230277/8d1491e2-729e-11e6-842f-e23b8d9640e3.PNG)
