### ISSUE TITLE
Throwable exception uncaught in Route.php unlike in App.php

### ISSUE THREAD

**Issue by Starli0n** [slimphp/Slim#1983]
Hi,

I found a bug while dealing with `phpErrorHandler`. I noticed that `Throwable` exceptions are not caught in `Route.php` on line 324 whereas this case is handle in `App.php`

``` php
    try {
        ob_start();
        $newResponse = $handler($this->callable, $request, $response, $this->arguments);
        $output = ob_get_clean();
    } catch (Exception $e) {
        ob_end_clean();
        throw $e;
    }
```

For `Throwable` exceptions, `ob_end_clean()` is never called.

It should be replace by:

``` php
    try {
        ob_start();
        $newResponse = $handler($this->callable, $request, $response, $this->arguments);
        $output = ob_get_clean();
    } catch (Exception $e) {
        ob_end_clean();
        throw $e;
    } catch (Throwable $e) {
        ob_end_clean();
        throw $e;
    }
```

Thanks

**Comment by rrpadilla** [comment]
Following the documentation http://php.net/manual/en/language.errors.php7.php#119652, we should "add a catch block for Exception AFTER catching Throwable first".
Just switch catch blocks:

try {
        ob_start();
        $newResponse = $handler($this->callable, $request, $response, $this->arguments);
        $output = ob_get_clean();
    } catch (Throwable $e) {
        ob_end_clean();
        throw $e;
    } catch (Exception $e) {
        ob_end_clean();
        throw $e;
    }

**Comment by Starli0n** [comment]
I put `Throwable` first.

Thanks

**Comment by akrabat** [comment]
Thank you !
