### ISSUE TITLE
any way to use slim with free hosting sites? I tried a lot of hosting sites but non of them fully support slim

### ISSUE THREAD

**Issue by ahmedkaballo** [slimphp/Slim#1986]

**Comment by tflight** [comment]
It doesn't matter if or how much the hosting company charges, what matters is only if the host meets the [System Requirements](http://www.slimframework.com/docs/start/installation.html). The requirements are very minimal so Slim should work just about anywhere.

In many cases, "free" hosting or shared hosting will not allow command line (shell) access. In which case you wouldn't be able to install Slim or its dependencies with composer, however you could still install and build it locally and then upload with S/FTP.

**Comment by ahmedkaballo** [comment]
@tflight thanks for claryifing

**Comment by garnold** [comment]
@ahmedkaballo FWIW we run a number of Slim-based apps in Google App Engine (GAE) and thus far have stayed within their generous free tier.  Similar to @tflight 's answer, we install dependencies in our local dev environments and push to GAE.

**Comment by geggleto** [comment]
This is not a slim issue. I think you should use our forums for this type of discussion.
