### ISSUE TITLE
Bug in rendering html text

### ISSUE THREAD

**Issue by safaa-alnabulsi** [slimphp/Slim#1987]
I've tried many ways to render html stored in a variable, but I'm not able to do it until now.
I'd need some explanation from you. what am I doing wrong ?
data before using them:

```
&lt;img alt=&quot;User-added image&quot; src=&quot;https://rrrrr;amp;feoid=00N2400000H7Rxb&amp;amp;refid=0EM7E0000004FgN&quot; style=&quot;height: 333px; width: 500px;&quot;&gt;&lt;/img&gt;&lt;br&gt;&lt;br&gt;Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam 
```

data after using them:

``````
    = raw resource.comments
    = sanitize resource.comments
    = strip_tags "'#{resource.comments}'"
    = ActionView::Base.full_sanitizer.sanitize(resource.comments)```
``````

or 

``````
def formatted_comments
  h.sanitize(comments, :tags => [], :attributes => [])
end 

 = formatted_comments```

**result:**

``````

<  i mg alt="User-added image" src="https://rrrrr;feoid=00N2400000H7Rxb&amp;refid=0EM7E0000004FgN" style="height: 333px; width: 500px;"></img><br><br>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam 

```

I noticed that the rendered html tag contains the following. " my result of html tags here " = $0 trying to remove it manually, all html was rendered!

```

**Comment by danopz** [comment]
Looks like you are looking for [this](https://github.com/slim-template/slim) instead of SlimFramework for PHP.

**Comment by safaa-alnabulsi** [comment]
yes, thank you. sorry
