### ISSUE TITLE
GetName() from route middleware returns null

### ISSUE THREAD

**Issue by oscarr-reyes** [slimphp/Slim#1988]
for some reason when i try to get the name of the route, it returns null so i cannot evaluate the process that depends on checking the name, the application has this configuration

``` php
$app = new \Slim\App([
    "settings" => [
        "determineRouteBeforeAppMiddleware" => true
    ]
]);
```

there is only 1 middleware function registered  which it is setting the `CORS` headers and evaluate the access as long as it's not a login route

``` php
$app->add(function($request, $response, $next)
{
    $route = $request->getAttribute("route");
    $methods = [];
    if(count($route->getArguments()) > 0)
    {
        $methods = ["GET", "PUT", "DELETE", "OPTIONS"];
    }
    else
    {
        $methods = ["GET, POST", "OPTIONS"];
    }
    // Check for access as long as the current route is not login
    if($route->getName() != "/login")
    {
        include_once "models/Account.php";
        $token = $request->getHeaderLine("X-Access-Token");
        // X-Access-Token is not defined, return unauthorized
        if(!$token)
        {
            $response = $response->withStatus(401);
            return $response;
        }
        else
        {
            $data = Account::model()->findByAttributes([
                "access_token" => $token
            ]);
            // provided token is not found, return unauthorized
            if(!$data)
            {
                $response = $response->withStatus(401);
                return $response;
            }
        }
    }
    // Set CORS headers
    $response = $response->withHeader("Access-Control-Allow-Origin", "*");
    $response = $response->withHeader("Access-Control-Allow-Methods", implode(", ", $methods));
    $response = $response->withHeader("Access-Control-Allow-Headers", "Content-Type, X-Access-Token"); // Allow content-type other than defaults
    $response = $response->withHeader("Access-Control-Max-Age", "86400"); // 24hrs for preflight cache
    return $next($request, $response);
});
```

but seeing that the name conditional is always executed i have made a `var_dump` on the name which shows `null`

**Comment by tuupola** [comment]
Have you defined the route you are trying to access?

**Comment by oscarr-reyes** [comment]
all routes are defined, and `/login` has only one `POST` route defined

**Comment by tuupola** [comment]
Have you given the route a name with `->setName("foo")`? Seeing the route definition would be helpful.

**Comment by oscarr-reyes** [comment]
the routes are defined like this:

``` PHP
$app->get("/accounts", function($request, $response)
{
    $query = $_GET;
    $filter = [
        "LIMIT" => isset($query["limit"]) ? $query["limit"] : 10
    ];
    $model = Account::model()->findAll($filter, "batch");
    $response = $response->withJson($model);
    return $response;
});
```

as long as the middleware process passes the validation

this is the route i am having problems with:

``` PHP
$app->post("/login", function($request, $response)
{
    $data = $request->getParsedBody();
    $model = Account::model()->findByAttributes([
        "username" => $data["username"],
        "password" => $data["password"]
    ]);
    $result = [];
    if($model)
    {
        $result = (Object) [
            "username" => $model[0]["username"],
            "user_id" => $model[0]["user_id"],
            "access_token" => $model[0]["access_token"]
        ];
    }
    $response = $response->withJson($result);
    return $response;
});
```

the middleware code is actually defined just before all routes are defined.. i tried on defining this after the routes.. but as expected the result doesn't change because routes are returning the responses directly rather than returning the callable middleware, this issue was not happening before. this code was being worked on another system and literally both systems have the same settings, i would like to check if the other system would have this issue as well but currently is unavailable to use, but all the code seems fine atleast for me, the application works without the middleware so the problem comes from there

**Comment by tuupola** [comment]
You have not defined a [name](http://www.slimframework.com/docs/objects/router.html#route-names) for the `/login` route. For  `$request->getName()` to return a value you need to call `->setName("foo")` for the given route. For example:

``` php
$app->get("/login", function($request, $response, $arguments) {
    return $response;
})->setName("login");
```

However I have a feeling you are looking for request path.

``` php
$app->add(function($request, $response, $next) {
    $response = $next($request, $response);
    $path = $request->getUri()->getPath();
    $response = $response->write(print_r($path, true));
    return $response;
});

$app->get("/login", function($request, $response, $arguments) {
    return $response;
});
```

```
$ curl --include http://0.0.0.0:8080/login
HTTP/1.1 200 OK
Host: 0.0.0.0:8080
Connection: close
X-Powered-By: PHP/5.6.17
Content-Type: text/html; charset=UTF-8
Content-Length: 6

/login
```

**Comment by oscarr-reyes** [comment]
that code looks fine and i tried it, but now for some reason the code gives other errors now

``` PHP
if(count($route->getArguments()) > 0)
{
    $methods = ["GET", "PUT", "DELETE", "OPTIONS"];
}
```

this error is only thrown for the route `/login`, the error thrown is `Call to a member function getArguments() on null`.. at this point i have to set the allowed methods on the route depending if the request has URI parameters like `account/:id`

**Comment by oscarr-reyes** [comment]
i just found the solution.. i had to define a `OPTIONS` method for route `/login`, that made everything else work
