### ISSUE TITLE
Slim\App: Obsoleted magic methods but their PHPDocs remain alive

### ISSUE THREAD

**Issue by acgrid** [slimphp/Slim#1989]
As commit fb85bdbd8d5739a7f7e8c6172301b535ea16ab2c shows, `Slim\App` does not contains `__isset()` and `__get()` magic methods any more.
However, its related phpdocs still present since then, see https://github.com/slimphp/Slim/blame/3.x/Slim/App.php#L38-L48

I've spent some minutes to figure out where these "mysterious" phpdocs come out. I suggest to evaluate whether introducing such magic methods or not, and remove superfluous phpdocs if magic methods are confirmed to be wiped out.

**Comment by akrabat** [comment]
Fixed in the upcoming version 3.6. Thanks for reporting.
