### ISSUE TITLE
Custom exception handler regression

### ISSUE THREAD

**Issue by dannykopping** [slimphp/Slim#199]
In the `develop` branch, the custom exception handler functionality no longer works.

The following code:

``` php
$app->error(function(Exception $e)
{
    $app = Slim::getInstance();
    $app->halt(500, "Something bad happened");
}
```

does not behave as in 1.5.1; in the previous version, the custom exception handler would halt execution and **only** display the string provided to the `halt` function as the second parameter. Now, it calls the `PrettyExceptions::renderBody` function when the execution is halted, with `debug` mode either `on` or `off`.

**Comment by codeguy** [comment]
Thanks for pointing this out! I'll take care of this later today.

**Comment by codeguy** [comment]
@dannykopping When you invoke `$app->halt(...)`, that method will set the HTTP status and HTTP body on the current response object and throw a `Slim_Stop_Exception` to prompt the application to immediately send the response; behind the scenes, the `Slim_Stop_Exception` is caught by a `catch` block later in the Slim app's `call()` method. The error handler is invoked to handle an Exception caught during runtime; invoking `halt()` in the error handler throws another `Slim_Stop_Exception` that can only be caught by the upstream diagnostics middleware.

You do not need to call `halt()` in your error handler; instead, `echo()` the response body. The resultant HTTP response will automatically have a 500 status and will use the content that you `echo()` from the error handler.

Does this seem reasonable? I suppose I could add an additional `catch` block in the `call()` method to handle this situation, but not sure if that is necessary.

**Comment by dannykopping** [comment]
Hhmm - yeah, that's a solution although there are other mitigating factors.
For one, if I just `echo` a response inside the `error` handler, Slim won't respect any other custom headers I want to send back... Here's an example:

``` php
$app->error(function(Exception $e)
{
    $app = Slim::getInstance();

    $app->contentType("application/json");
    $app->response()->header("Access-Control-Allow-Origin", "*");

    echo json_encode(array(
                          "error" => array(
                              "message" => $e->getMessage(),
                              "code"    => $e->getCode()
                          )
                     ));
});
```

Even if this is a solution, I think this is a small blight on the otherwise perfect complexion of Slim. If you do it this way, you are now forced to send `500` codes when an exception occurs, and - at least for me - this won't work. I'm writing a meta-framework that will handle a number of different exceptions which will in turn halt the execution with different HTTP codes. For example, if a request body cannot be deserialized, I fire the `InvalidRequestFormatException` which should send back a `400 Bad Request` header.

**Comment by dannykopping** [comment]
I've pushed up an experimental branch to a fork of the repository to illustrate how the previous `halt` functionality could be restored:

https://github.com/dannykopping/Slim/commit/3b9ac1b21e1f37c6c1aec21507604254334ba6b5

There is a problem with this, however; the code will only work with one Slim application (i.e. the `default` application) by calling `Slim::getInstance()` as there is no way that I could find to get a reference to the top-level application from the `PrettyExceptions` class. The issue is compounded by the fact that this `PrettyExceptions` class is a middleware class, so changing its functionality may affect middleware as a whole.

**Comment by dannykopping** [comment]
Note that this method also respects any custom `contentType` or `headers` assigned to the `Response` object.

An example response:

``` http
HTTP/1.1 403 Forbidden
Date: Mon, 26 Dec 2011 20:04:34 GMT
Server: Apache/2.2.14 (Unix) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l PHP/5.3.1 mod_perl/2.0.4 Perl/v5.10.1
X-Powered-By: PHP/5.3.1
content-length: 45
access-control-allow-origin: *
Content-Type: application/json

{"error":{"message":"something...","code":0}}
```

generated by:

``` php
$app->halt(403, json_encode(array(
                                 "error" => array(
                                     "message" => $e->getMessage(),
                                     "code" => $e->getCode()
                                 )
                            )));
```

**Comment by codeguy** [comment]
I agree with you that you should be able to set the HTTP status and HTTP headers in the event of an error, instead of Slim using a HTTP 500 response automatically.

Here's the `error()` method in the Slim class:

```
public function error( $argument = null ) {
    if ( is_callable($argument) ) {
        //Register error handler
        $this->router->error($argument);
    } else {
        //Invoke error handler
        $this->halt(500, $this->callErrorHandler($argument));
    }
}
```

And here are my suggested changes to keep the necessary changes as simple as possible:

```
public function error( $argument = null ) {
    if ( is_callable($argument) ) {
        //Register error handler
        $this->router->error($argument);
    } else {
        //Invoke error handler
        $this->response()->status(500);
        $this->response()->body('');
        $this->response()->write($this->callErrorHandler($argument));
        $this->stop();
    }
}
```

This change ensures that, in the event of an error, the response status will (by default) be 500 BUT this can now be changed in the custom error handler. Any content `echo()`d in the error handler will be written to the response body; the custom error handler may also append content manually to the Response body rather than `echo()` content. This also respects existing headers since the current Response object is used rather than replaced. And error handling is still contained and managed by each separate application.

Thoughts?

**Comment by codeguy** [comment]
I'll still need to update the Slim class `call()` method to catch the `Slim_Exception_Stop` exception thrown by the above changes of course.

**Comment by dannykopping** [comment]
Yeah, that seems like a good idea - I'll test it out once the `Slim::call` function is updated
Thanks @codeguy

**Comment by codeguy** [comment]
@dannykopping This is now available in the develop branch. Added a unit test to `tests/SlimTest.php` on line 1293 that demonstrates functionality.

**Comment by codeguy** [comment]
Link:

https://github.com/codeguy/Slim/blob/develop/tests/SlimTest.php#L1293

**Comment by dannykopping** [comment]
Excellent - the changes have restored the original functionality
Thanks @codeguy :)
