### ISSUE TITLE
Slim 2 and Maxmind GeoIP2

### ISSUE THREAD

**Issue by bigHosting** [slimphp/Slim#1990]
Hi,

I am trying to integrate Slim2 and MaxMind GeoIP2 database however I am running into issues in a sense that geoip lookups don't work at all and the scipt/API times out. geoip api is set up in a separate folder and installed via composer as instructed @ https://github.com/maxmind/GeoIP2-php .  Slim works fine by itself, geoip2 works fine by itself it's just the integration between the two that gives me headache. Am i running into a bug here ?

Thank you

In the route file I have:
defined('DIRECT') OR exit('No direct script access allowed');

require_once 'geo/vendor/autoload.php';
use GeoIp2\Database\Reader;
use GeoIp2\Exception\AddressNotFoundException;

$app->get("/table/blacklistgeo(/)", function() use($app)
{  
        $info = array();

```
    // DB user/password settings
    include_once 'lib/DB.php';

    // count number of matches
    $total = $db->get_count( 'blacklist' );
    if ( $total > 0 )
    {

            $results = $db->get_all( 'blacklist' );

            $country = "UNK";

            $geoIPdb = "/etc/GeoLite2-City.mmdb";
            if (!file_exists($geoIPdb)){
                throw new \Exception("Geo database file does not exist");
            }

            // GeoIP2 database handler
            $reader = new Reader($geoIPdb);

            foreach( $results as $row)
            {       
                    $ip      =  inet_ntop($row['sourceip']);
                    $type    =  ip_type($ip);

                    $record = $reader->city($ip);
                    $country = $record->country->isoCode;

                    $info[] = array( 
                                     'sourceip'     => $ip,
                                     'type'         => $type,
                                     'country'      => $country
                                   );
            }
            json(200, 0, $info );
    } else {
            $info = array("response" => "table: 0 rows");
            json(200, 1, $info );
    }
```

});

?>

**Comment by tuupola** [comment]
What is the actual problem in here?

**Comment by bigHosting** [comment]
Issue found in the geoIP code. Sorry.
