### ISSUE TITLE
Webpage documentation issue

### ISSUE THREAD

**Issue by RTCeables** [slimphp/Slim#1992]
Sorry I'm a stickler for documentation. In your [website ](http://www.slimframework.com/) you note

"We recommend you install the Slim Framework with the Composer dependency manager." Yes super cool but then you do not state how. In gitub though you do... So suggest you add in this important line of text into your homepage to prevent confusion, as I was rather baffled at first by the next sentence on your homepage.

SO INSERT INTO HOMEPAGE:

`$ composer require slim/slim "^3.0"`
This will install Slim and all required dependencies. Slim requires PHP 5.5.0 or newer.

**Comment by geggleto** [comment]
please open an issue on our Website Repo for this :)

https://github.com/slimphp/Slim-Website

**Comment by RTCeables** [comment]
Sure

**Comment by geggleto** [comment]
ty sir :)

**Comment by tuupola** [comment]
Just `$ composer require slim/slim` is enough.
