### ISSUE TITLE
range out of order in character class at offset 13

### ISSUE THREAD

**Issue by DracotMolver** [slimphp/Slim#1997]
I am not sure if I am doing something wrong or not. The error itself, it is not something that screw my project, but I don't wanna have to erase the error log over and over again lol. So, the error is as follow:

```
 PHP Warning:  preg_match(): Compilation failed: range out of order in character class at offset 13  in /home/.../vendor/nikic/fast-route/src/Route.php on line 35
```

I'm using groups routes as follow:

``` php
$app->group('/vehiculo', function () {
   $this->map(['GET', 'POST'], '', function (Request $request, Response $response) {
        // Here I return something...
    });
});
```

as I said, it works fine. it returning me the data, but I'd like to know if I am doing something wrong - and learn how to do it well - or no :). Thanks guys

**Comment by JoeBengalen** [comment]
What PHP version?

**Comment by DracotMolver** [comment]
I'm running v5.5.38

**Comment by DracotMolver** [comment]
I fixed the issue. It was a misunderstood using regex expression in routes.
I have several routes and some of them with some regex like {patente:[A-Z0-9]+}, {anio:[0-9]+} and so on. The thing was the **+** which of course is gonna look for any matching from here to the "infinite" lol. So I don't know if you could add this thing as a warning or something in the doc, so people can be aware of it. "Don't abuse of regex, it is a dangerous power." :)
