### ISSUE TITLE
I'm cannot remove or modify cookie (FIG Cookie)

### ISSUE THREAD

**Issue by musaev-haybulla** [slimphp/Slim#1999]
You are recommended use **FIG Cookie**.
And i have question.

If i set **_withPath_** method, i cannot remove or modify cookie any way.

This code sets a cookie that I can delete:
`$setCookie = SetCookie::create('auth')->withValue('1'); $response = FigResponseCookies::set($response, $setCookie);`

but this code set cookie that i cannot remove (expire) and modify in Safari and Chrome (other browsers not verified)
`$setCookie = SetCookie::create('auth')->withValue('1')->withPath('/'); $response = FigResponseCookies::set($response, $setCookie);`

What could it be?.. And how can I fix it?..

**Comment by tuupola** [comment]
You probably should ask in [dflydev/dflydev-fig-cookies](https://github.com/dflydev/dflydev-fig-cookies) instead.

**Comment by musaev-haybulla** [comment]
There I already asked. And just in case asked here too, maybe someone have encountered.
