### ISSUE TITLE
Add a custom function to the $request in a middleware

### ISSUE THREAD

**Issue by DavidePastore** [slimphp/Slim#2001]
Hi, I developed the [Slim-Validation](https://github.com/DavidePastore/Slim-Validation) middleware and I think that its configuration is not that simple. These are the steps to make it works:
- inject in the container for every route validation (let's use `yourContainerKey` in our case and only for one route);
- `$app->add($middleware)` retrieving `$middleware` from the container;
- check if `$request` has any errors in the route callback calling `$this->yourContainerKey->hasErrors()`.

Now what I think it's verbose is the  `$container` usage in three different steps (the first one is the source of the evil and the less flexible because you have to use a different key for each route).

Am i missing anything? What I think would be more concise is a way to directly inject the `hasErrors` function in the `$app` or even in the `$request` object. Can I do something like this so I could simply use the validator without create 10 different keys in the container (and 10 different usage keys in the route callback)?

We talked about this [here](https://github.com/DavidePastore/Slim-Validation/issues/6#issuecomment-249540228).

Thanks

**Comment by akrabat** [comment]
`$request` has a `withAttribute()` and `getAttribute()` method, so your middleware should set an attribute that can then be read in the route callback.

**Comment by DavidePastore** [comment]
@akrabat Thanks for your suggestion. Do you think this is the best way to achieve it?

**Comment by geggleto** [comment]
@DavidePastore this is the exact reason why we have with/getAttribute on the request object :)

**Comment by DavidePastore** [comment]
Thanks, feel free to close this issue. :+1:
