### ISSUE TITLE
Set base URL path enviroment config (Question)

### ISSUE THREAD

**Issue by JoniJnm** [slimphp/Slim#2003]
How can I set a base url path to resolve routes?

Slim takes base url path from $_SERVER['SCRIPT_NAME'] in Uri::createFromEnvironment()

``` php
// Path
$requestScriptName = parse_url($env->get('SCRIPT_NAME'), PHP_URL_PATH);
$requestScriptDir = dirname($requestScriptName);

...

if (stripos($requestUri, $requestScriptName) === 0) {
    $basePath = $requestScriptName;
} elseif ($requestScriptDir !== '/' && stripos($requestUri, $requestScriptDir) === 0) {
    $basePath = $requestScriptDir;
}

...

if ($basePath) {
    $uri = $uri->withBasePath($basePath);
}
```

I have a complex virtualHost and the DOCUMENT_ROOT can not be the slim root directory. Is there any way to set basePath? Currently I'm doing it modifying the SCRIPT_NAME in index.php:

``` php
$_SERVER['SCRIPT_NAME'] = '/api/index.php';
$app = new \Slim\App($container);
```

**Comment by Loic-Rameau** [comment]
You may do this by setting the basePath in the app's router.

By doing :
```.php
$app->get('container')->get('router')->setBasePath('your base path');
```

**Comment by Loic-Rameau** [comment]
You can achieve this by overriding the default Request and Uri class in the container.

First override the Request::createFromEnvironment method to get your Uri class and then override juste the Uri::createFromEnvironment method.

So you will have the same default behavior but with a custom Uri definition.

Or alternatively modify directly the environment in the container after is initialization. And add your logic to make the REQUEST_URI or SCRIPT_NAME as if Slim was on root directory.
