### ISSUE TITLE
How to overwrite the router?

### ISSUE THREAD

**Issue by aimeos** [slimphp/Slim#2009]
How can we overwrite the router object with an own implementation?

This leads to `Cannot override frozen service "router"`:

```
$container['router'] = function( $c ) {
    return new \Aimeos\Slim\Router();
};
```

These lines produce `Identifier "router" does not contain an object definition`:

```
$container['router'] = $container->extend( 'router', function( $c ) {
    return new \Aimeos\Slim\Router();
} );
```

**Comment by geggleto** [comment]
If you try to extend router, it's a closure until it get's called for the first time.

You would need to do what you did above.

``` php
$container['router'] = function( $c ) {
    return new \Aimeos\Slim\Router();
};
```

right after the App is constructed.

**Comment by aimeos** [comment]
Unfortunately, it doesn't overwrite the existing router:

```
$settings = require __DIR__ . '/../src/settings.php';
$app = new \Slim\App($settings);
$container = $app->getContainer();

$container['router'] = function( $c ) {
        return new \Aimeos\Slim\Router();
};
```

**Comment by silentworks** [comment]
You need to override it before the new instance of `Slim\App`.

``` php
$settings = require __DIR__ . '/../src/settings.php';
$settings['router'] = function( $c ) {
        return new \Aimeos\Slim\Router();
};
$app = new \Slim\App($settings);
```

**Comment by aimeos** [comment]
Sorry, doing it right after `new \Slim\App($settings)` worked but I hadn't noticed the difference.
Thanks
