### ISSUE TITLE
Using sub classes with SLIM

### ISSUE THREAD

**Issue by 84564221** [slimphp/Slim#201]
Is it possible to call any kind of sub class, without using the onion handler?

**Comment by codeguy** [comment]
I'm not really sure what you are trying to accomplish. If you want to append new methods to the Slim application class, you can extend the Slim class (I advise against this) or use a decorator like this:

```
<?php
class MySlim {
    protected $app;
    public function __construct( Slim $app ) {
        $this->app = $app;
    }

    public function __call($methodName, $args) {
        if ( method_exists($this->app, $methodName) ) {
            $this->app->$methodName($args);
        }
    }

    public function alias() {
        //Do something
    }
}
?>
```

But that's getting messy, and I'm hesitant to suggest this without knowing more about what you want to accomplish.
