### ISSUE TITLE
Slim\App::subRequest() makes difficults on using custom PSR-7 implementation

### ISSUE THREAD

**Issue by acgrid** [slimphp/Slim#2010]
I want use my own `Request` implementation by registering the factory before Slim's default service provider.

However the `Slim\App::subRequest()` breaks everything because it instantiate `Slim\Http\Request` in literal and more worse, I can not override this method since its private field `$container`.

Suggestions I can come up with:
- Make `Slim\App::$container` protected to allow inheritance.
- Dynamic instantiation by `get_class()` on request object in container.
- Replace data from cloned original request already in the container (maybe toxic, and a bit difficult with replacing headers)

Reference: https://github.com/slimphp/Slim/blob/184352bc1913d7ba552ab4131d62f4730ddb0893/Slim/App.php#L495

**Comment by vlakoff** [comment]
About your suggestions:
- Is there any reason this property is private?
- Seems a bit tricky to me, for example could the custom request have a different construct signature?
- Seems more reasonable than #2, imho

**Comment by acgrid** [comment]
Yeah you reminded me, suggestion 2 may be awful with different constructor signature.

Then it seems that the first option is most straightforward, so I also want to question "Is there any reason this property is private?"

**Comment by akrabat** [comment]
I recommend just writing creating instantiating your own request and response objects and calling $app->__invoke() directly.

**Comment by acgrid** [comment]
Thanks for your reply. I've edited my code to avoid `subRequest()` and no impacts so far.
