### ISSUE TITLE
Proposal: Throwable responses

### ISSUE THREAD

**Issue by vlakoff** [slimphp/Slim#2012]
Would you be interested in a feature like https://github.com/laravel/framework/pull/13473?

Currently, throwing a response requires the following. As more, `SlimException` isn't really appropriate.

```
$response = $response->withRedirect($url);
throw new \Slim\Exception\SlimException($request, $response);
```

Whereas a few additions would allow to do this:

```
$response->withRedirect($url)->throwResponse();
```

Note the request isn't used actually.

**Comment by KuroThing** [comment]
Exceptions as control flow are generally considered an anti pattern, there is some discussion about it on [stackoverflow](https://softwareengineering.stackexchange.com/a/189225).

**Comment by vlakoff** [comment]
Sure thing, but there are *exceptions* to this. In this situation, exceptions play really nice.

* Otherwise you have to propagate returns all the way up, which sometimes isn't even doable.
* These exceptions allows fine-grained and centralized handling (error handling, logging, and much more).
* Features like Laravel's [terminable middlewares](https://laravel.com/docs/5.4/middleware#terminable-middleware) free you from the sequential flow constraint.

As a result, you have a really great application flow that wouldn't be possible without these exceptions.

**Comment by KuroThing** [comment]
And exceptions are not not designed for this kind of control flow.

In a website that has thousands of hits an hour, using Exceptions as Control Flow is terrible performance wise, and doesn't scale. At all.

Why encourage bad design?

**Comment by geggleto** [comment]
I can't get behind this idea at all.

Throwable response will not work in Slim.

The idea being that you can immediately terminate from the app strikes me as weird as it's you need to go back through your middleware to complete any actions, throwing response breaks that.

**Comment by vlakoff** [comment]
*Populus locutus est*, closing as there is a clear consensus, no need to pursue.
