### ISSUE TITLE
Can't get params on remote server

### ISSUE THREAD

**Issue by QQizi** [slimphp/Slim#2016]
Hi,

I'm doing a simple API with Slim 3 and have no problem at all on local.

As soon as i put it on my client server i'v no way to get the request params.

Here's all the methods i tried : 

`$app->post('/test', function (ServerRequestInterface $request, ResponseInterface $response) {
    var_dump($request->getParsedBody());
    var_dump($_REQUEST); 
    var_dump($_POST); 
    var_dump($request->getQueryParams());
    var_dump($request->getParams());
    var_dump($request->getParam('test'));
    return $response->withJson($request->getParsedBody());
});`

When i'm using the exact same request on local server it work fine.
The method is called, if i do an `echo 'whatever';` i can see the 'whatever' so this is not a url problem.

sorry for the code sample can't find a way to make it prettier...

**Comment by geggleto** [comment]
It sounds like your server isn't running the app at all, do you just get a white screen?

**Comment by QQizi** [comment]
@geggleto The app is running, when i'm using echo or whatever else it is working, my routes are available. The problem is just in getting the POST params, i get the `args` params in GET tho.

**Comment by tuupola** [comment]
What content type you are submitting? IIRC `application/x-www-form-urlencoded` is needed for PHP to populate `$_POST`. Can you provide curl commandline example request.

**Comment by QQizi** [comment]
@tuupola here's the curl request : 

`curl -X POST -H "Cache-Control: no-cache" -H "Postman-Token: 6affc27d-dd25-5967-d119-c756647abf43" -H "Content-Type: application/x-www-form-urlencoded" -d 'paramkey=paramvalue' "__url_api__/__method__"`

Here's the response : 

`Array
(
)
Array
(
)
Array
(
)
Array
(
)
Array
(
)
`

Each array correspond to the var_dump that i display in my first message.

**Comment by tuupola** [comment]
Look for differences in server config between local and live environments. For example [enable_post_data_reading](http://php.net/manual/en/ini.core.php#ini.enable-post-data-reading).

**Comment by tuupola** [comment]
BTW. The code you show and the response with curl request do not match.  The curl request requests something which calls `print_r()` and not `var_dump()`.

`var_dump([])` yields:

```
array(0) {
}
```

`print_r([])` yields:

```
Array
(
)
```

**Comment by geggleto** [comment]
Closing this as no updates for months.

Please reopen if required.
