### ISSUE TITLE
Do slim framework support mongodb?

### ISSUE THREAD

**Issue by yongloon** [slimphp/Slim#2018]

**Comment by PauloPhagula** [comment]
Slim supports it as an external pluggable dependency (which is easy to add)in the same way it supports any other database, not as something that is built-in.

On the [First Application Walkthrough](http://www.slimframework.com/docs/tutorial/first-app.html) page, in the documentation, it is explained how you can add the dependencies required by your app.  You can use the examples shown there and easily adapt them to mongodb.

Hope it helps
