### ISSUE TITLE
Interesting behavior with request attributes

### ISSUE THREAD

**Issue by garnold** [slimphp/Slim#2019]
Hello,

It appears that if I set a request attribute in middleware using the same name as a path argument, the attribute value is reset when it reaches the route callback.  However, the value is correct when accessed in other middleware before reaching the route callback.  For example:

``` php
class Middleware1 {
    public function __invoke(Request $request, Response $response, callable $next) {
        $foo = $request->getAttribute('foo'); // expected 'bar'; got 'bar'
        return $next($request->withAttribute('foo', 'baz'), $response)); // set 'foo' to 'baz'
    }
}
class Middleware2 {
    public function __invoke(Request $request, Response $response, callable $next) {
        $foo = $request->getAttribute('foo'); // expected 'baz'; got 'baz'
        return $next($request, $response));
    }
}
class RequestHandler {
    public function __invoke(Request $request, Response $response) {
        $foo = $request->getAttribute('foo'); // expected 'baz'; got 'bar' ← ← ←
        return $response;
    }
}

$this->group('/{foo}', function () {
    $this->any('', '\RequestHandler')->add(new Middleware2());
})->add(new Middleware1());

// make request for http://localhost/bar
```

Certainly there are reasons why I shouldn't overwrite a path argument this way, but the inconsistency is interesting.

Best,
Geoff.

**Comment by garnold** [comment]
Quick update: **request attributes** are overwritten by **route arguments** in `Slim\Handlers\Strategies\RequestResponse:__invoke` prior to invoking the route callback:

``` php
        foreach ($routeArguments as $k => $v) {
            $request = $request->withAttribute($k, $v);
        }
```

This is unexpected behavior, as the route callback is already passed an array of **request arguments**, implying that one should retrieve the **request attributes** using `$request->getAttribute()` and **route arguments** from the `$args` parameter.

Luckily there is an easy workaround by replacing the `foundHandler` on the container, however I'd still consider this a bug.

**Comment by geggleto** [comment]
This is not a bug, it is how middleware is executed which is documented on our site :)

**Comment by mathmarques** [comment]
Just a comment:
```php
class Middleware1 {
    public function __invoke(Request $request, Response $response, callable $next) {
        $foo = $request->getAttribute('foo'); // expected 'bar'; got 'bar'
        return $next($request->withAttribute('foo', 'baz'), $response)); // set 'foo' to 'baz'
    }
}
```
`// expected 'bar'; got 'bar'` is not true. $foo here is null, 'cause only the Route Strategy set the Url Arguments as Attributes(before the call to the route callable).
So we could add to docs that Route Strategy may overwrite your previous attributes.

**Comment by geggleto** [comment]
Yeah the whole middleware stack can be a bit ... challenging to see. I don't find that in the current setup it is intuitive, but in theory it is documented. Perhaps the docs should be updated.
