### ISSUE TITLE
Can't get X-Access-Token using $request (Slim 3)

### ISSUE THREAD

**Issue by developer239** [slimphp/Slim#2020]
How do I get X-Access-Token using \Slim\Http\Request object?

I got it working only like this:

```
    $request_headers = getallheaders();
    $accessToken = $request_headers["X-Access-Token"];
```

**Comment by robwittman** [comment]
[http://www.slimframework.com/docs/objects/request.html#the-request-headers](url)

You should be able to access it using $request->getHeader("X-Access-Token")[0];

Notice that getHeader($key) returns an array, as multiple values can be supplied for a given header. Here I'm presuming you need the first one

**Comment by developer239** [comment]
Thanks a lot.
