### ISSUE TITLE
Can I get route by name

### ISSUE THREAD

**Issue by developer239** [slimphp/Slim#2021]
How do I get full route by name? Is it possible? For example in twig template. In Laravel I can do something like this:

```
Route::get('user/profile', 'UserController@showProfile')->name('profile');
$url = route('profile'); // returns /user/profile
```

**Comment by tuupola** [comment]
http://www.slimframework.com/docs/objects/router.html#route-names

**Comment by developer239** [comment]
I am so blind. Sorry. Thank you.
