### ISSUE TITLE
Locale in URL Router

### ISSUE THREAD

**Issue by danielbarenkamp** [slimphp/Slim#2023]
Hello,

I am working on a web application, that should be available in many other locales, e.g.:
1. www.domain.com/en-us/
2. www.domain.com/de-de/
...

I already figured out to load the locales for Gettext, but now I am stuck with the URL routing. 

Question:
How can I make the "pathFor" function dynamic so that I can create routes as before but with the local loaded dynamically before? 

I have achieved this in Slim 2 with overwriting the url function like this:

``` php
class MultilingualSlim extends \Slim\Slim {
    public function urlFor( $name, $params = array() ) {
        return sprintf('/%s%s', $this->view()->getLang(), parent::urlFor($name, $params));
    }
}
```

**Comment by tflight** [comment]
Use a [Route Placeholder](http://www.slimframework.com/docs/objects/router.html#route-placeholders) for the locale when creating the route. The `pathFor()` method accepts an array of route placeholders as the second argument.

``` php
$app->get('/{locale}/action', function ($request, $response, $args) {
    echo "Hello, " . $args['locale'];
})->setName('hello');
```

The pathFor method in a controller might look like this.

``` php
echo $app->getContainer()->get('router')->pathFor('hello', [
    'locale' => $this->view()->getLang()
]);
```

**Comment by danielbarenkamp** [comment]
Thanks for the suggestion, but isn't there an other way instead of writing the {locale} every time at the start of the route? Maybe by modifying the basePath or the routing functionality?

**Comment by tflight** [comment]
Sure, you could use the [setBasePath method of the Router](https://github.com/slimphp/Slim/blob/3.x/Slim/Router.php#L96-L112). Then you could write a very simple [middleware](http://www.slimframework.com/docs/concepts/middleware.html), the language to the constructor, setting the base path, and forwarding along the request.

**Comment by danielbarenkamp** [comment]
Thank you for the fast support - I really appreciate it.

I tried creating a Middleware like you said, but I am not able to get it work ...

```
<?php
namespace lib;

class LocaleMiddleWare
{

    private $container;

    public function __construct($container) {
        $this->container = $container;
    }
    /**
     * Middleware to set the right Locale
     *
     * @param  \Psr\Http\Message\ServerRequestInterface $request  PSR7 request
     * @param  \Psr\Http\Message\ResponseInterface      $response PSR7 response
     * @param  callable                                 $next     Next middleware
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function __invoke($request, $response, $next)
    {

        $this->container->router->setBasePath('de-de');

        return $next($request, $response);
    }
}
```

I have set the basePath, but how can I modify the request?

**Comment by tflight** [comment]
I've never played around with `setBasePath` before, but I just tried it in a simple middleware and it seems to work as I'd expect. Once it is set, you don't need to modify the request as any URL you construct with pathFor will include the basePath set. Here is an example of a middleware I tested with.

``` php
<?php

namespace App\Middleware;

use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;
use Slim\Router;

class LocaleMiddleware
{
    protected $router;

    public function __construct(Router $router)
    {
        $this->router = $router;
    }

    /**
     * Locale middleware invokable class
     *
     * @param  \Psr\Http\Message\ServerRequestInterface $request  PSR7 request
     * @param  \Psr\Http\Message\ResponseInterface      $response PSR7 response
     * @param  callable                                 $next     Next middleware
     *
     * @return \Psr\Http\Message\ResponseInterface
    **/
    public function __invoke(Request $request, Response $response, $next)
    {
        $this->router->setBasePath('de-de');
        $response = $next($request, $response);
        return $response;
    }
}
```

When I did that, all of my `pathFor` URLs include `de-de`, for example `http://example.com/de-de/user`

**Comment by danielbarenkamp** [comment]
Why is this working for you but not for me .. this drives me nuts!

The Middleware is exactly the same as you have instead that I use namespace lib.

How I initialize the Middleware

```
$app->add(new lib\LocaleMiddleware($app->getContainer()->router));
```

My routes: 

```
$app->get('/', 'MyController:method1');

$app->get('/test', 'MyController:method2');
```

My Controller

```
<?php
namespace controller;
use models;

class MyController extends \controller\Controller {

   public function method1($request, $response, $args) {
      // Sample log message
      $this->c->logger->info("Slim-Skeleton '/' route");

      $teachers = new models\Teachers();

      // Render index view
      // $this->c->view->setMasterView('adminMasterV2.php');
      return $this->c->view->render($response, 'login.php', $args);
   }

   public function method2($request, $response, $args) {
        echo "test";
   }

   public function method3($request, $response, $args) {
        //your code
        //to access items in the container... $this->ci->get('');
   }
}
```

When I try to access www.domain.com/de-de/ I get a page not found. When I try www.domain.com/de-de/test/ I also get a page not found ...

**Comment by tflight** [comment]
You are getting a route not found because neither of your two routes match that pattern. `/de-de/test/` doesn't match either `'/'` or `'/test`. You will need something like this.

``` php
$app->get('{locale}/', 'MyController:method1');
$app->get('{locale}/test', 'MyController:method2');
```

You could also use a regular expression to make sure the locale is set properly. I'm not great with regex, but perhaps something like:

``` php
$app->get('{locale:[a-z][a-z]\-[a-z][a-z]}/', 'MyController:method1');
```

**Comment by tflight** [comment]
You could also add the locale part as a [route group](http://www.slimframework.com/docs/objects/router.html#route-groups) to avoid repeating it through your app.

**Comment by tuupola** [comment]
Also `/test/` and `/test`  are two different routes.

**Comment by danielbarenkamp** [comment]
Hmm, but my inital Question was if I could create routes without the {local} parameter ... is this not possible?

**Comment by tflight** [comment]
In order for a route like `/de-de/something` to be routed, it needs to _match_ a route. So regardless if you use the placeholder or not, the URL needs to match the route.

**Comment by JoeBengalen** [comment]
You could create middleware that strips the locale from the url in the request before the route is determined

**Comment by danielbarenkamp** [comment]
@JoeBengalen How can I modify the request when there are only private variables and no method to modify the URL value? Do you have an example for me?

**Comment by tuupola** [comment]
I do not know what you are trying to achieve, but I would just keep the `{locale}` in the route. It will make life much easier.

**Comment by geggleto** [comment]
Closing as the issue is old and I think we had a resolution.
