### ISSUE TITLE
Not able to access url

### ISSUE THREAD

**Issue by yongloon** [slimphp/Slim#2024]
This route not able to access by the url without **'/'.**
$app->get('**/user/upload**', function ($request, $response, $args) {

```
$sth = getConnection()->prepare("SELECT * FROM user ORDER BY id");
$sth->execute();
$todos = $sth->fetchAll(PDO::FETCH_ASSOC);
return $response->withJson($todos);
```

});

While this is work when add **'/'** on it.
$app->get('**/user/upload/**', function ($request, $response, $args) {

```
$sth = getConnection()->prepare("SELECT * FROM user ORDER BY id");
$sth->execute();
$todos = $sth->fetchAll(PDO::FETCH_ASSOC);
return $response->withJson($todos);
```

});

Can i know why?

**Comment by robertprice** [comment]
Do you have anything automatically adding a trailing slash to a request, perhaps in a .htaccess file?

**Comment by juliangut** [comment]
Have a look here https://github.com/oscarotero/psr7-middlewares#trailingslash

**Comment by jdmcalee** [comment]
If you just want it to work either way:
`$app->get('/user/upload[/]', function ($request, $response, $args) {`

**Comment by geggleto** [comment]
closing this as resolved.
