### ISSUE TITLE
Request in Controller is empty/null

### ISSUE THREAD

**Issue by 3HMonkey** [slimphp/Slim#2026]
Hello guys, 

I already read through the net and tried to find a solution for my problem.
First I want to say that I have been building a REST API using the slim framework. 
I just want to give you an example (which is working fine):

``` php
$app->post('/login', function ($request, $response, $args) {


    $response_array = array(
        "status" => "sucess",
        "data" => array(),
        "message" => null



    );

    $parsedBody = $request->getParsedBody();


    $validate = new Validate();
    $validation = $validate->check($parsedBody, array(
            'username' => array(
                'required' => true,


            ),
            'password' => array(
                'required' => true,
                'min' => 10

            )

        )
    );

    if($validation->passed()){

        echo 'working';

    }else{


        $response->write(json_encode($response_array));

    }



    return $response;


});
```

Well this is working fine while sending a JSON object to "/login". But my index.php is getting bigger and bigger now, so I decided start using controllers by creating an abstract class which represents the main controller interface.

``` php
$app->get('/', \Routes\RootController::class);
$app->post('/login', \Routes\LoginController::class);
```

``` php
<?php

namespace Routes;



use Interop\Container\ContainerInterface;



abstract class MainController
{
    protected $ci;

    public function __construct(ContainerInterface $ci)
    {
        $this->ci = $ci;
    }

    abstract public function __invoke($request, $response, $args);
}
```

Then I created the LoginController.

``` php
<?php


namespace Routes;


class LoginController extends MainController
{

    public function __invoke($request, $response, $args)
    {
        $response_array = array(
            "status" => "sucess",
            "data" => array(),
            "message" => null



        );



        $parsedBody = $request->getParsedBody();


        $validate = new \Validate();
        $validation = $validate->check($parsedBody, array(
                'username' => array(
                    'required' => true,


                ),
                'password' => array(
                    'required' => true,
                    'min' => 10

                )

            )
        );

        if($validation->passed()){

            echo 'working';


        }else{


            $response->write(json_encode($response_array));

        }
        return $response;
    }
}
```

And here the problem came up. It seems that the "$request" is empty or null. Also by checking it with:

``` php
if(!$request){
echo 'not null';
}
```

Really thanks a lot for your time!!!

**Comment by cyrildewit** [comment]
I'm a beginner to PHP, but i know that codecourse.com created a complete course about creating a authentication app with Slim 3. I suggest you to watch his course and read the the forum.

I hope this will help you!

**Comment by Lewiscowles1986** [comment]
I think you might be missing a call to parent::__construct().

More importantly I think this might work better as a middleware within a routing group for routes requiring login as it centralizes the login logic.

Not really a slimphp issue

**Comment by nicowernli** [comment]
@3HMonkey copied and pasted your code and works fine to me. Which version of Slim are you using? Are you using any middleware that could be replacing the $request object?

**Comment by geggleto** [comment]
This doesn't look like a slim issue, it must be middleware.

Please feel free to reopen if you require further assistance.
