### ISSUE TITLE
Problem with File CSS

### ISSUE THREAD

**Issue by carbos10** [slimphp/Slim#2027]
Hi, this is my directory in templates:

> templates
> -test.phtml
> ->materialize
> -->css
> ---materialize.css

If i use link href to materialize.css it doesn't open the materialize.css file but open test.phtml (as the Route for /) i think there are problems with htaccess, this is my htaccess

```
RewriteEngine On
# Some hosts may require you to use the `RewriteBase` directive.
# If you need to use the `RewriteBase` directive, it should be the
# absolute physical path to the directory that contains this htaccess file.
#
# RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

**Comment by geggleto** [comment]
You need to move the css to a publicly accessible directory. They are not in the public directory so you cannot access them.
