### ISSUE TITLE
Multiple apps in one file

### ISSUE THREAD

**Issue by silentworks** [slimphp/Slim#203]
I have tested running multiple apps in index.php file and I get 404 for one app while getting the correct for the other app. This is due to the url not being found in one of the apps, I have tested this on the latest develop branch and its still the same. There seem to be no way of independently separating the routes between apps. Code example below:

```
$app = new Slim();
$app->setName('frontend');

$admin = new Slim();
$admin->setName('admin');

$app->get('/', function () { 
    echo "Hello, Dude";
});

$admin->get('/world/:name', function ($name) { 
    echo "Hello, $name";
});

$app->run();
$admin->run();
```

This as it is will give a 404 for $admin app upon run if you are at the base url due to no url matching the $admin routes.

**Comment by codeguy** [comment]
I guess looking at this further, it makes sense that two apps in the same file cannot run simultaneously. Only one set of headers and HTTP response should ultimately be sent.

Where I _would_ ultimately like to take this is to enable one to mount an app at a given endpoint on another app. Now that v1.5.2 introduces the `call()` method, this becomes possible.

However, that's too far off and I don't want to worry about it just now. Will add to the road map but remove from the Issue Tracker.
