### ISSUE TITLE
Please ensure the docs track the new features ;-)

### ISSUE THREAD

**Issue by udf2457** [slimphp/Slim#2030]
For example, useful stuff like getUploadedFiles() from #1263, which was merged in 2015.

No trace of that in the docs.

I only found out about its existence after Googling how-to use $_FILES with slim.  All sorts of answers come up but this one seems the most sensible.

Coding new features is all well and good, but not much good if nobody knows about them !  ;-)

**Comment by akrabat** [comment]
We would love a PR to https://github.com/slimphp/Slim-Website.

**Comment by udf2457** [comment]
Well yeah... you would love a PR for that feature.... now that I've found .... that feature.

How about all the other ones you haven't bothered documenting ?  You know your source tree better than I do.  I'm certainly not going to be reading through all your source code and try to correlate it all myself.

That's my point.  There's not much point merging a new feature if you're not going to merge an update to the docs at the same time !

**Comment by akrabat** [comment]
We try to ensure that the docs are good. However, as an open source project, not all contributors provide a docs PR when they write a feature. 

Also, as someone very close to the code, I rarely need the docs, so am not always aware of what's missing or note explained well. As we know about this one now, I'm confident that it'll be sorted at some point.

**Comment by udf2457** [comment]
"However, as an open source project, not all contributors provide a docs PR when they write a feature. "

I'd call that sloppy coding.  There should be a "no doc, no merge" policy.

Yes I agree, its a perennial problem with opensource problems that people prefer hacking away at the code instead of writing the docs.  But I don't think that's an area where you want to proudly follow the status quo.

But that's why opensource is so frustrating.  The project maintainers will go tell you to RTFM and then you go RTFM and there's nothing there because the project maintainers/contributors/whatever don't UTFM. 

Anyway.  Rant over.  ;-)

**Comment by akrabat** [comment]
I will say this for Slim, we don't say "RTFM" :) We will link you to the correct docs page though (if there is one!).

Seriously, thanks for the feedback as I do want Slim to be the best it can be and I appreciate the time you've taken to report this.
