### ISSUE TITLE
Next to #429 :  About SlimV3 documentation

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2032]
Could you make an offline version as Docset for Dash/Zeal or PDF format ?

And could you add an example of vhost for Apache2 ?
If you want I can give you mine. (I don't use the .htaccess, only vhost)

**Comment by geggleto** [comment]
The docs can be pulled in for offline consumption by cloning the Slim-Website Repo (https://github.com/slimphp/Slim-Website)

Giving a vhost might seem to be logical, but it opens the flood-gates for support...
