### ISSUE TITLE
getParsedBody conflicting with middleware

### ISSUE THREAD

**Issue by sander-bol** [slimphp/Slim#2035]
Just  FYI: https://github.com/oscarotero/psr7-middlewares/issues/50

TLDR: Slim's getParsedBody() is conflicting with the Payload middleware in OscarOtero's Middleware repository.

If possible I'd like to get your opinion on the fix for this. I feel this is another case of Slim's Request object taking on responsibilities which might be better deferred to Middleware.

**Comment by akrabat** [comment]
Well,

The PSR-7 spec says this about `getParsedBody()`:

> ```
>  * @return null|array|object The deserialized body parameters, if any.
>  *     These will typically be an array or object.
>  */
> public function getParsedBody();
> ```

Slim has to implement this method in `Request` in order to meet the specification and is within that spec to return an array.

**Comment by sander-bol** [comment]
Fair enough. Thanks for the feedback!
