### ISSUE TITLE
Integrated event bus

### ISSUE THREAD

**Issue by garnold** [slimphp/Slim#2036]
❤️  Slim Framework!

The more I use Slim, the more I'm finding use cases for event bus functionality, preferably built into (or on top of) the container.  Any plans to add an event bus to Slim?

Thanks,
Geoff.

**Comment by codeguy** [comment]
Thanks for using Slim! We probably will not add an event bus into Slim though as that goes against our core principles. It should be easy enough to find an external component to do that though.

**Comment by garnold** [comment]
@codeguy Thanks for the quick response!  I thought it might fit in as an Add On / first-party component, but maybe not.  Have you documented Slim's core principles somehwere?

**Comment by tflight** [comment]
@garnold While it hasn't been updated in several years, there are a few [goals listed here](https://github.com/slimphp/Slim/wiki/Road-Map) that are likely still applicable today-- though I can't speak to that.

**Comment by garnold** [comment]
Thanks for the pointer @tflight
