### ISSUE TITLE
Fix PHP 7.1 build failure

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#2039]
> ```
> There was 1 error:
> 1) Slim\Tests\AppTest::testRespondWithPaddedStreamFilterOutput
> stream_filter_append(): mcrypt and mdecrypt stream filters have been deprecated
> /home/travis/build/slimphp/Slim/tests/AppTest.php:1538
> /home/travis/build/slimphp/Slim/Slim/Handlers/Strategies/RequestResponse.php:41
> /home/travis/build/slimphp/Slim/Slim/Route.php:344
> /home/travis/build/slimphp/Slim/Slim/MiddlewareAwareTrait.php:116
> /home/travis/build/slimphp/Slim/Slim/Route.php:316
> /home/travis/build/slimphp/Slim/Slim/App.php:438
> /home/travis/build/slimphp/Slim/tests/AppTest.php:1568
> /home/travis/.phpenv/versions/7.1.0RC3/bin/phpunit:572
> ERRORS!
> Tests: 557, Assertions: 895, Errors: 1, Skipped: 13, Risky: 1.
> ```

**Comment by mathmarques** [comment]
This can be closed, was fixed on #2117
