### ISSUE TITLE
Extract setting content-length to middleware

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2043]
Current implementation conflicts with New Relic. Make this an optional middleware.

**Comment by codeguy** [comment]
@akrabat Was this for the inbound request object or outbound response or both?

**Comment by akrabat** [comment]
Outbound. See https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L543-L553

**Comment by akrabat** [comment]
Fixed by https://github.com/slimphp/Slim/pull/2254.
