### ISSUE TITLE
Remove sub-request functionality

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2044]

**Comment by far-blue** [comment]
out of curiosity, are sub-requests being superseded by something 'better' or just considered a bad idea?

I am currently investigating using sub-requests to support multiplexed update requests via PATCH  - where the PATCH payload is actually a batch of partial updates to possibly multiple different records and which need to be unpacked and dispatched as if they were individual PUT / POST / DELETE requests. Kind of like https://tools.ietf.org/html/rfc6902 but for REST requests. This reduces the number of individual REST requests.

If not sub-requests, any suggestions on how this could still work?

**Comment by codeguy** [comment]
Resolved.
