### ISSUE TITLE
Separate PSR-7 implementation into own component

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2045]
This will be ONLY the PSR-7 methods and nothing more.

**Comment by mnapoli** [comment]
Any reason why not reusing Zend Diactoros? That would be less things to maintain

**Comment by akrabat** [comment]
The main reason is that we think that for a robust ecosystem there should be more components implementing the PSR than just one.

**Comment by akrabat** [comment]
Slim 4 uses [Slim-Http](https://github.com/slimphp/Slim-Http).
