### ISSUE TITLE
Let user inject third-party PSR-7 request via `App::run()` argument

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2048]
Support third-party PSR-7 request objects by injecting them as argument to `App::run()`.

    $app = new \Slim\App();
    // Route definitions
    $app->run(new \My\OtherRequest());

Related  to #2046

**Comment by geggleto** [comment]
How do we handle PSR-7 responses with that signature?

**Comment by geekish** [comment]
It's up to you to create and return them, which is why a `ResponseFactory` of some sort is going to be very useful.

**Comment by geggleto** [comment]
https://github.com/slimphp/Slim/issues/2047#issuecomment-261964564

**Comment by tuupola** [comment]
After using http://httplug.io/ for a while I also have also become fan of things like `ResponseFactory` and `RequestFactory`. Especially when combined with autodiscovery.

**Comment by geggleto** [comment]
@tuupola Yeah there is a PSR in the works for them :)

**Comment by akrabat** [comment]
@geekish wrote:

> It's up to you to create and return them, which is why a ResponseFactory of some sort is going to be very useful.

Why is a ResponseFactory preferable to `new Response()` ?

**Comment by geggleto** [comment]
@akrabat because it would be the only way to fully replace the PSR-7 implementation objects.

**Comment by tuupola** [comment]
This code is good example why factories are useful. As @geggleto said the instantitation of PSR-7 objects is not standardized.

https://github.com/php-http/message/tree/master/src/MessageFactory

**Comment by geekish** [comment]
@akrabat Since the Response object is not already available as it was previously, it provides an easy way for users to create the Response, and it gives you a place to put some of the non-PSR-7 methods currently in Response. See my comment on [#2056](//github.com/slimphp/Slim/issues/2056#issuecomment-261745391).

**Comment by akrabat** [comment]
My thought was that `$response = new Response();` is as easy as `$response = ResponseFactory::createResponse();` and is one fewer class to write.

**Comment by codeguy** [comment]
I tend to agree with @akrabat on this one. I think our goal for 4.0 will be to move forward with `new Response()`, see what problems arise if any, and then take appropriate action with 4.1.

**Comment by l0gicgate** [comment]
This was solved with #2222.
