### ISSUE TITLE
Remove traits if possible, simplify stack trace

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2053]
Will require more investigation.

**Comment by geggleto** [comment]
I floated the idea of removing Callable Resolver to it's own repo. Ideally it can be provided as a static or singleton class inside the DIC. There really isnt a reason for it being a trait.

Moving it to it's own class should stop some of the jumping across the files.

**Comment by codeguy** [comment]
@geggleto I wasn't paying much attention to Slim when this was added, so I'm not 100% familiar with the internals of the current implementation. Can you walk me through it sometime soon on Slack?

**Comment by geggleto** [comment]
@codeguy Yeah, just ping me when you want to go through it.

**Comment by akrabat** [comment]
Maybe the trait should become a class and be composed into `App` and `Route`?

**Comment by mathmarques** [comment]
I think that a class `MiddlewareAware` composed into App and Route would be better than extends an abstract class.
If you want, I can make this change.

**Comment by akrabat** [comment]
> If you want, I can make this change.

Yes. This probably affects into the PSR-15 support that @bnf has started.

**Comment by l0gicgate** [comment]
Closed as per #2555
