### ISSUE TITLE
Remove `Slim\Exception\SlimException` class

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2055]

**Comment by geggleto** [comment]
What are we going to replace them with ? :) Are we going to just extend from `\Exception` or `\Throwable`

**Comment by codeguy** [comment]
Updated title. This only affects the `Slim\Exception\SlimException` class.

**Comment by mrailton** [comment]
Any objections to me working on this?

**Comment by akrabat** [comment]
Fixed by #2124
