### ISSUE TITLE
Provide built-in HTTP response factories, support PSR-17

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2056]
Implement HTTP factories for PSR-7 response object creation, covering:

* Success
* Created
* Redirect
* BadRequest
* Forbidden
* NotFound
* Error

Also perhaps factory methods to return new Response for content types (e.g. JSON, XML, CSV).

NOTE: Updated this post based on subsequent discussion.

**Comment by geekish** [comment]
Wouldn't a ResponseFactory be better than making a Response class for every possible status?

**Comment by codeguy** [comment]
We'll hit the main ones I think. We could also do something like `JsonResponse()`, etc. /cc @akrabat

**Comment by codeguy** [comment]
@geekish Can you post a very brief snippet of code that demonstrates what you're thinking?

**Comment by geekish** [comment]
Looks like they're trying to create a PSR for HTTP factories, think something like this:
https://github.com/http-interop/http-factory-slim/blob/master/src/ResponseFactory.php

But with some methods like:

``` php
public function createRedirectResponse($url, $status = 302) {
    return (new Response)->withHeader('Location', $url)->withStatus($status);
}
public function createJsonResponse($url, $content) {
    // basically the code Response->withJson() does
}
```

**Comment by geggleto** [comment]
//cc @codeguy @akrabat @geekish Yes this is on my todo list. We should have proper factory classes to make the HTTP Objects.

**Comment by codeguy** [comment]
For reference:

https://github.com/php-fig/fig-standards/blob/master/proposed/http-factory/http-factory.md

**Comment by codeguy** [comment]
And the meta doc:

https://github.com/php-fig/fig-standards/blob/master/proposed/http-factory/http-factory-meta.md

**Comment by codeguy** [comment]
See https://github.com/slimphp/Slim/issues/2048#issuecomment-264172923

**Comment by tuupola** [comment]
For reference there is currently two PSR-17 implementations supporting Slim. Mine is for `slim/slim` and the second one is for `slim/http`.

https://github.com/tuupola/http-factory
https://github.com/http-interop/http-factory-slim

HTTP Interop also provides integration tests.

https://github.com/http-interop/http-factory-tests

**Comment by akrabat** [comment]
This is a [Slim-Http](https://github.com/slimphp/Slim-Http) thing. See https://github.com/slimphp/Slim-Http/pull/27

**Comment by l0gicgate** [comment]
Closing, this has been resolved. [Slim-Psr7/pull/27](https://github.com/slimphp/Slim-Psr7/pull/17) has been merged.
