### ISSUE TITLE
api/#/path instead of api/index.php/path ????

### ISSUE THREAD

**Issue by schill32** [slimphp/Slim#2064]
Hey everyone.  I've been struggling with .htaccess files for about the last 24hrs trying to get it to run correctly on my local dev, and has got me wondering if there is not an easier way.  Lately I have been doing a lot of work in Angular which has me wondering if perhaps a change could be made to allow for a hash instead of all the rewrite logic?  Seems like it would certainly simplify things around configuration.  Thoughts?

**Comment by codeguy** [comment]
This would be a client-side concern if you are using URL fragments. You're better off asking this on the Slack channel. Plenty of folks there who can give you some pointers :)
