### ISSUE TITLE
Update Twig-view / PHP-View

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#2065]
- Need to update Twig/PHP -view for 4.x

**Comment by dopesong** [comment]
No description provided. ?

**Comment by 1f7** [comment]
Suggest add array to items collection
https://github.com/slimphp/Twig-View/pull/66
need to collect items from different classes that not have Response
not important as it will be called `offsetAdd` or `addGlobal` or like on another

**Comment by pine3ree** [comment]
Hello @geggleto, @codeguy 
It would be nice to have a View template renderer interface and a different signature for the `render` method:
```php
public function render($template, array $data = []);
```
I believe that a template renderer should not be aware of nor interact with `Psr\Http\Message\ResponseInterface`.
The response can be written to directly inside middleware using the response interface methods. Something like this:
```php
return $response->write(
    $this->view->render('/my/template/file.phtml', [
        //..key=>value pairs here
    ]);
);

//or

return new HtmlResponse($this->view->render('/my/template/file.phtml', [/*...*/]);
```

kind regards

**Comment by akrabat** [comment]
Issues need to be opened on relevant repositories for Slim 4 updates.
