### ISSUE TITLE
Problem with routes params ended with space(s)

### ISSUE THREAD

**Issue by brutto** [slimphp/Slim#2071]
Slim v 3.6

Have this kind of route:
```
$this->map(['GET', 'OPTIONS'], '/users/{login}/', '\DD\Controllers\UsersController:showProfile');
```

If i'll try to access like `'~/users/<login> [only space(s) here]     /'` request is hanging for several seconds (5-15) and then return empty result. =\

**Comment by geggleto** [comment]
This one is related to FastRoute.... Closing.
