### ISSUE TITLE
css and js files are not loaded with multiple .htaccess slimframework

### ISSUE THREAD

**Issue by antoniomerlin** [slimphp/Slim#2072]
well i have setup slim skeleton directly in public_html where in that directory their is first .htaccess file contain routing to public folder.
first .htaccess contain:

    RewriteEngine On

    RewriteBase /public/
    RewriteRule ^$ public/

due to which my domain is directly pointing to public/index.php
which contain second .htaccess file with slimframework standard .htaccess file:

    RewriteEngine On

    # Some hosts may require you to use the `RewriteBase` directive.
    # If you need to use the `RewriteBase` directive, it should be the
    # absolute physical path to the directory that contains this htaccess file.
    #
    # RewriteBase /

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ index.php [QSA,L]

Because of this my css and js files are not loaded inside template and they are going as in console 

> GET http://domain.com/css/bootstrap.min.css 
returning 404 error
I am struugling with this issue from two days but still not able to get where should i change as its working fine on my local server but not over godaddy server.

**Comment by geggleto** [comment]
This is really not a Slim problem, but an environment problem.

You should not need an HTACCESS file to rewrite to your public/ directory.

**Comment by 1f7** [comment]
`.htaccess` in `public` live as is in slim skeleton
`.htaccess` in `public_html`  try like that

```
RewriteEngine On
RewriteBase /public/

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^assets/(.*) /public/assets/$1 [QSA,L]
RewriteRule ^ index.php [QSA,L]
```
but better change your apache .conf
`DocumentRoot /path/to/your/public_html/public`

**Comment by antoniomerlin** [comment]
I am getting in apache errorlog
> RewriteRule: bad flag delimiters

`RewriteEngine On

RewriteBase /public/

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ css/(.*) /public/css/$1 [QSA,L]
RewriteRule ^ index.php [QSA,L]`

**Comment by 1f7** [comment]
delete space `^ css/(.*)` => `^css/(.*)`

repeat:
> but better change your apache .conf
`DocumentRoot /path/to/your/public_html/public`

**Comment by antoniomerlin** [comment]
yup my final solution is to create symlink of public directory to public_html. As i don't have access to modify apache.conf

**Comment by geggleto** [comment]
closing this as resolved.
