### ISSUE TITLE
Consider not listening on 0.0.0.0

### ISSUE THREAD

**Issue by kevinburke** [slimphp/Slim#2074]
The documentation recommends that you bind your dev server to 0.0.0.0. Listening on 0.0.0.0 means that the development environment is available on all interfaces. If a user's development machine has a public IP address, that means that they'll be accidentally exposing their development environment to the public. Tools like [Shodan](https://www.shodan.io/) make it easy to scan the entire IPv4 address space for a given tool.

Many MongoDB users accidentally exposed the contents of their database for the longest time for the same reason, this has led to e.g. the personal information of 80 million Mexicans being dumped. http://www.tothenew.com/blog/is-your-mongodb-publicly-accessible/

**Comment by majoess** [comment]
Really important, never use 0.0.0.0 if the computer is public reachable.

**Comment by kevinburke** [comment]
Note that MongoDB instances that listen on 0.0.0.0 are currently being taken over & held for ransom

http://arstechnica.co.uk/security/2017/01/more-than-10000-online-databases-taken-hostage-by-ransomware-attackers/

**Comment by akrabat** [comment]
PRs raised to fix in the skeleton and on the website.

**Comment by geggleto** [comment]
I am going to close this then.
