### ISSUE TITLE
Do not assume Flash variable is assigned to View

### ISSUE THREAD

**Issue by yaph** [slimphp/Slim#208]
Slim version used is 1.5.1.4.zip 

The line that leads to the error looks like:
$this->view->getData('flash')->save();

$this->view->getData('flash') is NULL in may case, I don't use the flash feature and the documentation does not state that it's a requirement. When I replace the code with the following the application runs flawless

if ($flash = $this->view->getData('flash')) {
    $flash->save();
}

**Comment by codeguy** [comment]
If you invoke `$view->setData(array(...))` anywhere in your app, you're overwriting the View's `flash` data variable. I recommend you instead use `$view->appendData(array(...))` instead to avoid the issue. I hope to resolve this assumption in the near future.

**Comment by yaph** [comment]
Thanks for the quick reply, replacing all calls to setData with appendData resolves the issue.
