### ISSUE TITLE
Slim's problem with ApacheBench solved

### ISSUE THREAD

**Issue by reinir** [slimphp/Slim#2083]
I accidently found Slim's problem with ApacheBench while benchmarking.
I also found [a discussion about it](http://help.slimframework.com/discussions/problems/24-high-loading-times-in-apache-bench) that started in January 2012.

Apparently the cause is a bug in Slim, not ApacheBench.
The solution is really simple.
Just add this code to your framework:

```php
// Send "Connection: close" to all HTTP/1.0 requests with no Connection header
// See http://cogframework.com/findings/http-slim-and-apachebench
if($_SERVER['SERVER_PROTOCOL']=='HTTP/1.0' && empty($_SERVER['HTTP_CONNECTION'])){
    header('Connection: close');
}
```

Since I'm not a Slim user, I'm leaving it to you to decide where to put the solution.
I recommend putting it at the start of `Slim\App` constructor, like this:

```php
public function __construct($container = [])
{
    // Send "Connection: close" to all HTTP/1.0 requests with no Connection header
    // See http://cogframework.com/findings/http-slim-and-apachebench
    if ($_SERVER['SERVER_PROTOCOL'] == 'HTTP/1.0' && empty($_SERVER['HTTP_CONNECTION'])) {
        header('Connection: close');
    }
    if (is_array($container)) {
        $container = new Container($container);
    }
    if (!$container instanceof ContainerInterface) {
        throw new InvalidArgumentException('Expected a ContainerInterface');
    }
    $this->container = $container;
}
```

For the full account of the investigation and an explanation on why that is the solution,
see my article [HTTP, Slim and ApacheBench](http://cogframework.com/findings/http-slim-and-apachebench).

**Comment by Zegnat** [comment]
I don't think adding `header()` calls is the right way to do this, instead you would want to add this header to the PSR-7 Response and let [Slim's `respond()` method](https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L344-L405) actually send it.

If this is a header that is always needed, I propose adding it to the response in the [`finalize()`](https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L528-L557) step. Something like adding this right before the `isEmptyResponse()` check:

```php
if (!$response->hasHeader('Connection') &&
    $_SERVER['SERVER_PROTOCOL'] == 'HTTP/1.0' &&
    empty($_SERVER['HTTP_CONNECTION'])) {
    $response = $response->withHeader('Connection', 'close');
}
```

Though it would probably be preffered to access the `$_SERVER` data some other way. `getServerParams()` on the Request might do the trick, but `finalize()` is only given the Response.

**Comment by geggleto** [comment]
I would prefer this to be a middleware.

it would be quite simple.

Would gladly accept a PR on it @Zegnat

**Comment by Zegnat** [comment]
@geggleto, I don’t mind drafting a PR, but I am not clear on exactly what you’d like. As far as I can see Slim does not ship with any predefined middleware, and I would hesitate to add any to the stack from the framework.

I can do a PR for updating `finalize()` (on either Slim 3.x or 4.x, whichever you would prefer), but that still leaves the problem of passing an instance of ServerRequestInterface to it.

**Comment by Zegnat** [comment]
Oh, I guess Slim 4.x will try and replace `finalize()` code with middleware, as per #2043? Is there any example of how Slim is planning to ship (optional) default middleware?

---

Edited to add, I think this should work as middleware:

```php
/**
 * When the client sends an HTTP 1.0 request, and the server is not sending
 * an HTTP 1.0 response, include a Connection header with value "close".
 *
 * @link   http://cogframework.com/findings/http-slim-and-apachebench
 *
 * @param  \Psr\Http\Message\ServerRequestInterface $request  PSR7 request
 * @param  \Psr\Http\Message\ResponseInterface      $response PSR7 response
 * @param  callable                                 $next     Next middleware
 *
 * @return \Psr\Http\Message\ResponseInterface
 */
function closeHttpConnection($request, $response, $next)
{
    $response = $next($request, $response);
    if ($request->getProtocolVersion() === '1.0' &&
        $response->getProtocolVersion() !== '1.0' &&
        !$response->hasHeader('Connection')) {
        $response = $response->withHeader('Connection', 'close');
    }
    return $response;
}
```

**Comment by geggleto** [comment]
I am going to leave this open so we don't forget about it.

**Comment by reinir** [comment]
I agree with your decision to leave this open.
This seems to be one of those things that is easily missed, so a reminder is a good idea.

**Comment by akrabat** [comment]
I don't think that this needs to be in core Slim.

**Comment by ndobromirov** [comment]
@Zegnat, ```$request->getProtocolVersion() === '1.0' &&
        $response->getProtocolVersion() !== '1.0'``` is always false...

**Comment by Zegnat** [comment]
> `$request->getProtocolVersion() === '1.0' && $response->getProtocolVersion() !== '1.0'` is always false...

@ndobromirov it wasn’t at the time I wrote the above code. Have taken a break from Slim so maybe it changed, but the `$response` used to be created as version `1.1` even if the `$request` was of version `1.0`. The `$response` being of a different version to the `$request` was the entire crux of this issue…

Or maybe you just misread and thought I was checking the protocol version on the same object? Because that would’ve always been false, yes.
