### ISSUE TITLE
Bad route parameter string causes uncaught compile error as warning rather than a useful error

### ISSUE THREAD

**Issue by ErynManela** [slimphp/Slim#2084]
#Using 
Slim 3.5.0
PHP 7

Using the following (erroneous) code in a controller to declare a route for options:
`$thisPtr = &$this;
$app->options('/{name:+}',function($req, $res, $args)  use ($thisPtr) {
						return $thisPtr->optionsCall($req, $res, $args);});`

Instead of throwing an error saying which route had a bad string, all Slim gives is a warning for a compilation error in fast-route, leaving it up to the developer to figure out which string was bad:
`PHP Warning:  preg_match(): Compilation failed: nothing to repeat at offset 6 in /Users/username/project/vendor/nikic/fast-route/src/Dispatcher/GroupCountBased.php on line 12`

**Comment by geggleto** [comment]
This is PHP complaining about something you have done.. Nothing we can do about it.

**Comment by geggleto** [comment]
Closing... if you have any other questions please reopen.
