### ISSUE TITLE
Uri::basePath  property and PSR-7 Uri interoperability

### ISSUE THREAD

**Issue by nyamsprod** [slimphp/Slim#2085]
On the project I'm working on I receive a URI object from GuzzleHttp/Psr7/Uri and I transfert it to Slim\Http\Request. But because the GuzzleHttp\Psr7\Uri does not know about Uri::basePath when calling Request::getRequestTarget is called an error stating that my Uri object lacks the basePath property is issued and the program halts.

offending lines: https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L472-L474

**Comment by geggleto** [comment]
Ugh I know your pain. Unfortunately we wont be able to do anything about it until 4.x.

**Comment by nyamsprod** [comment]
@geggleto a quick question why close the issue if other people stumble on the same issue leaving it open even with a wontfix status may help find it ?

**Comment by geggleto** [comment]
You are right, should be on slim 4 ;)

**Comment by danopz** [comment]
Looks like this is already fixed in Slim-Http

**Comment by akrabat** [comment]
Slim-Http has resolved this as it doesn't use a base path.
