### ISSUE TITLE
Cache response for minimum database hit ?

### ISSUE THREAD

**Issue by antoniomerlin** [slimphp/Slim#2089]
Can this scenario is possible if a response of a request is stored in cache and when the same request is triggered again instead for approaching to database directly give response from cache. So that database hit can reduce. Any implementation.

**Comment by ivandokov** [comment]
This is waaay to specific. I think it will be great used as external package.

**Comment by antoniomerlin** [comment]
how ?

**Comment by tuupola** [comment]
There are many userland cache implementations. Read about couple of them and choose one which suits your coding style the best.

https://packagist.org/search/?q=cache
http://www.php-cache.com/en/latest/

**Comment by antoniomerlin** [comment]
thanks.
