### ISSUE TITLE
Server problem - IdeaHosting

### ISSUE THREAD

**Issue by piernik** [slimphp/Slim#2090]
I have problem with Home.pl and it's IdeaHosting (it is based on apache but it's not apache). It is very popular company in Poland  that provides hosting.

What I want to accomplish is to send response with 406 and "Reason" phrase.
Here is my code:

```
use Slim\Http\Request;
use Slim\Http\Response;

if (PHP_SAPI == 'cli-server') {
    $url = parse_url($_SERVER['REQUEST_URI']);
    $file = __DIR__ . $url['path'];
    if (is_file($file)) {
        return false;
    }
}

require __DIR__ . '/../vendor/autoload.php';

session_start();

$settings = [];
$app = new \Slim\App($settings);

$app->get('/', function (Request $req, Response $res, $arg) {
    return $res->withStatus(406, "Reason");
});

$app->run();

```

As a result (http://beta.infirma.pl/blad.php) I have "500 Internal Error" page with Status is 406 but without reason phrase.

If I change code to:
```
$app->get('/', function (Request $req, Response $res, $arg) {
    echo "a";
    return $res->withStatus(406, "Reason");
});
```
500 Internal Error disapears and echoes "a" and status is 406 but still no reason phrase.

I know that You cannot test it but can You give me any clue where to look for solution?
I'm using slim 3.6

**Comment by aalfiann** [comment]
Slim3 is recommend you to show output response in json. 

Try to change your code into this:

$app->get('/', function (Request $req, Response $res, $arg) {
    $body = $res->getBody();
    $body->write(json_encode([ 
        'test' => 'a',
        'message' => $res->withStatus(406, "Reason")->getReasonPhrase()], JSON_PRETTY_PRINT));
    return $res
            ->withStatus(406, "Reason")
            ->withBody($body);
    });

This will output header 406 and get the message of reason phrase.

Actualy i've test your code it run perfectly on my server, there is no 500 internal error. Maybe the problem is only on idea hosting, you should create a ticket to idea hosting about this problem.

**Comment by akrabat** [comment]
Does this work:

```php
<?php

header("HTTP/1.1 406 Reaon");
exit;
```


Testing locally, I can't see any problems with your code, so suspect that it's related to the hosting.

**Comment by akrabat** [comment]
> Slim3 is recommend you to show output response in json.

For what it's worth, this is not a recommendation of the Slim project. Slim can be used to output content in any media type.

**Comment by aalfiann** [comment]
> For what it's worth, this is not a recommendation of the Slim project. Slim can be used to output content in any media type.

I've read in somewhere says that slim3 is for json rest api. Yes you right. actually im not really agree with that after I know how to render in php or html using twig.

**Comment by akrabat** [comment]
Slim is awesome for APIs :)

**Comment by piernik** [comment]
```
header("HTTP/1.1 406 Reaon");
```
Outputs 500 error - it's something with server:/

**Comment by akrabat** [comment]
> Outputs 500 error - it's something with server:/

Looks that way. Best to contact Home.pl and ask for help.
