### ISSUE TITLE
[Http] PSR-7 contract violation

### ISSUE THREAD

**Issue by 1ma** [slimphp/Slim#2091]
### spec
```php
// MessageInterface.php

/**
 * Retrieves all message header values.
 *
 * The keys represent the header name as it will be sent over the wire, and
 * each value is an array of strings associated with the header.
 *
 *     // Represent the headers as a string
 *     foreach ($message->getHeaders() as $name => $values) {
 *         echo $name . ": " . implode(", ", $values);
 *     }
 *
 *     // Emit headers iteratively:
 *     foreach ($message->getHeaders() as $name => $values) {
 *         foreach ($values as $value) {
 *             header(sprintf('%s: %s', $name, $value), false);
 *         }
 *     }
 *
 * While header names are not case-sensitive, getHeaders() will preserve the
 * exact case in which headers were originally specified.
 *
 * @return string[][] Returns an associative array of the message's headers. Each
 *     key MUST be a header name, and each value MUST be an array of strings
 *     for that header.
 */
public function getHeaders();
```

### problem
Slim [initializes its environment](https://github.com/slimphp/Slim/blob/50029c8a625bd3aaf9d6889da4570f9423b8e61a/Slim/DefaultServicesProvider.php#L47) by feeding it the raw $_SERVER superglobal. Later in the request lifecycle, this environment is used to [create the headers array for the request object](https://github.com/slimphp/Slim/blob/50029c8a625bd3aaf9d6889da4570f9423b8e61a/Slim/Http/Request.php#L140). Unfortunately, when running under a FastCGI execution environment the headers sent by the client are in the format of 'HTTP_FOO_BAR' instead of the original 'Foo-Bar', which violates the PSR-7 contract.

![debug headers](http://i.imgur.com/6ntEU2j.png)

### ferfuxsake why do you care?
I am the author of an [HMAC HTTP authentication library](https://github.com/1ma/Psr7Hmac) that aims to work out of the box with any PSR-7 implementation, so in my use case the whole spec is a very hard dependency. I found out this problem while developing and testing a Slim middleware for Psr7Hmac.

**Comment by 1ma** [comment]
I think I could manage a PR for that, just need to know the proper branch to submit it :)

**Comment by geggleto** [comment]
@1ma 3.x

**Comment by 1ma** [comment]
Presto.

**Comment by akrabat** [comment]
I thought I saw a PSR-7 compliance test suite somewhere. This may help with that too.

**Comment by tuupola** [comment]
https://github.com/php-http/psr7-integration-tests

**Comment by akrabat** [comment]
Fixed for Slim 4 in https://github.com/slimphp/Slim-Http/pull/26
