### ISSUE TITLE
Slim 4 ability for a middleware action to trigger downstream actions multiple times

### ISSUE THREAD

**Issue by far-blue** [slimphp/Slim#2092]
With the current design of Slim 4 underway I'd like to request an ability for a middleware action to trigger multiple downstream middleware actions, routing etc.

In particular this would be useful with multiplexed requests where multiple actions are bundled into a single request and need to be split out, routed, actioned and then the replies re-assembled into a multiplexed return payload. Such multiplexed requests are much less resource intensive when updating hundreds of assets at once.

**Comment by designermonkey** [comment]
Would you like to provide some pseudo code to help the discussion?

**Comment by akrabat** [comment]
With no discussion since 2016 other than @designermonkey's comment, I'm closing. Please re-open if there's more to discuss.
