### ISSUE TITLE
SLIM4 suggestion: query-parameter validation using regex

### ISSUE THREAD

**Issue by patricksavalle** [slimphp/Slim#2093]
Seems to me this is a fundamental part of any REST framework? I would suggest something like this:

    $slimapp->get('', ...)->add(new QueryParameters([
        '{text:\w+}',
        '{fromdate:\date}',
        '{distance:\float},0.0',
        '{orderby:(name|date)},name',
        '{reversed:\bool},false',
        '{offset:\int},1',
        '{count:\int},100',
    ]);

Something similar for the POST parameters.

For SLIM 3 I created a package that implements this as middleware, but it could also be made more integrated with SLIM. Anyhow, I think it is essential and here is a package that implements such a system. For inspiration.

https://github.com/patricksavalle/slim-request-params

regards.

A complete example:
```

<?php

declare(strict_types = 1);

namespace YourApi;

define("BASE_PATH", dirname(__FILE__));

require BASE_PATH . '/vendor/autoload.php';

use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;
use \SlimRequestParams\BodyParameters;
use \SlimRequestParams\QueryParameters;
use \SlimRequestParams\RequestResponseArgsObject;

$app = new \Slim\App;

$app->getContainer()['foundHandler'] = function (): \stdClass {
    return new RequestResponseArgsObject;
};

$app->get('/hello/{name}', function (Request $request, Response $response, \stdClass $args) : Response {
    $name = $args->name;
    $text = $args->text;
    $response->getBody()->write("$text, $name");
    return $response;
})
    ->add(new QueryParameters(['{text:[\w-.~@]+},Hello']));

$app->run();
```

**Comment by aldas** [comment]
Would it not bloat microframework? there are very capable validator frameworks out there ala https://github.com/Respect/Validation that can do proper error messages etc. only thing you need to do is to build validator, validate controller $args and respons json with validation errors.

```
use Respect\Validation\Validator as v;
...
$validator = v::key('text', v::stringType()->alnum()->length(1, 255))
    ->key('offset', v::intVal()->positive(), false);

try {
    $validator->assert($args);
} catch (NestedValidationException $e) {
    return $response->withJson(['messages' => $e->getMessages()], 422);
}
```

that try catch can be even in application error handler so you only need to build validator and assert args in controller

**Comment by damianopetrungaro** [comment]
ATM i do not see any advantage about using it and imho should not be not added to the core, the userland may use your package instead.

**Comment by designermonkey** [comment]
I would think this is a middleware, as not everyone creates REST apps with Slim.

I'm going to close this issue on that basis. If you think this is the wrong decision, please say so, and we can discuss it further.
