### ISSUE TITLE
Improvement: decodeSecureCookie time()

### ISSUE THREAD

**Issue by 84564221** [slimphp/Slim#210]
I suggest to specify more details for the `cookies.lifetime` - it should be set per default as a timestamp value - default value is '20 minutes' now.

_Slim.php_

``` php
-        'cookies.lifetime' => '20 minutes',
+        'cookies.lifetime' => time() + (1 * 24 * 60 * 60), // Set the Cookie-Lifetime for 1 day

```

**Comment by codeguy** [comment]
It should accept both a string and an integer. If it does not, it's a bug. I'll look into this. This should be isolated to 1.6.0 in the develop branch only and not the stable branch.
