### ISSUE TITLE
[DISCUSS] Remove output buffering from route

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2103]
Should we remove output buffering from routes and enforce the return of a valid PSR-7 response from route callables?

How will this affect the use of `var_dump()` inside of a route callable?

**Comment by akrabat** [comment]
As a minimum we should enforce returning a `Response` regardless.

**Comment by akrabat** [comment]
maybe we can have middleware that captures the output buffer and appends/prepends it to the body of the response on the way back out?

**Comment by codeguy** [comment]
@akrabat Middleware will become single-pass though since it is unpredictable to try and edit a response on the way out.

**Comment by akrabat** [comment]
Nope - Middleware is totally able to modify Response on the way out. It won't be able to modify it on the way in

**Comment by codeguy** [comment]
Well, if that'll work then it seems the best alternative.

**Comment by geggleto** [comment]
I like the middleware option :)

**Comment by codeguy** [comment]
Assigning to me.

**Comment by codeguy** [comment]
PR here https://github.com/slimphp/Slim/pull/2166

**Comment by geggleto** [comment]
Closed via #2166
