### ISSUE TITLE
RuntimeException thrown when submitting invalid XML

### ISSUE THREAD

**Issue by masadelante** [slimphp/Slim#2106]
Slim seems to throw a RuntimeException when submitting invalid XML data.

The xml media parser in Request.php, which uses simplexml_load_string to parse the request body, returns false when it's unable to validate the xml, and thereupon, an exception is thrown if the media parser doesn't return an array, an object or a null value.

Is this behaviour by design, or is it a bug? It seems a bit strange to me to stop the processing abruptly at this early point, before reaching a route. Wouldn't it be better to return a null value, and to let the routes - or middleware - decide what to do no valid data is passed to them?

May be related to issue #1807.

**Comment by akrabat** [comment]
I agree that this feels like an error as our JSON handling doesn't do this.

PR #2122 raised.
