### ISSUE TITLE
Uri.php createFromEnvironment

### ISSUE THREAD

**Issue by sungjunwi** [slimphp/Slim#2108]
#2107 similar issue.

```php
$basePath = '';
$virtualPath = $requestUri;
if (stripos($requestUri, $requestScriptName) === 0) {
    $basePath = $requestScriptName;
} elseif ($requestScriptDir !== '/' && stripos($requestUri, $requestScriptDir) === 0) {
    $basePath = $requestScriptDir;
}
```

plain english in the url will execute

```php
if (stripos($requestUri, $requestScriptName) === 0) {
$basePath = $requestScriptName;
```

non-english in the url converts to %blahblah...  executes

```php
elseif ($requestScriptDir !== '/' && stripos($requestUri, $requestScriptDir) === 0) {
$basePath = $requestScriptDir;
 ```
there's something wrong with those part. I have no idea what the problem is but if I put

```php
$virtualPath = $requestUri;
```
then run 
```php
$uri = new static($scheme, $host, $port, $virtualPath, $queryString, $fragment, $username, $password);
```
everythings works fine after that

it's not multi-byte safe

`stripos` that is

probably needs to use `mb_stripos` if availabl

It's not exactly the same, but #2107 issue probably has some connection with mine. basePath, requestScript, virtualPath, etc  there are somethings wrong with these parts

**Comment by geggleto** [comment]
I think this is going to make it into v4.

**Comment by akrabat** [comment]
[Slim-Http](https://github.com/slimphp/Slim-Http) no longer has a concept of base path.
