### ISSUE TITLE
Slim request not compatible with Guzzle (PSR-7 issue?)

### ISSUE THREAD

**Issue by damianopetrungaro** [slimphp/Slim#2111]
Hello!
I had an issue while i was building an API gateway.
What I noticed was that sending data from a Slim Request by a Guzzle Client if there was some data sent by the body, the api didn't get the right request parameters.

When i tried to get the params from the request `$data = $req->getParams();` it returned an error on key value pairing.

Instead of 
`'translations" => "{"en":{"name":"...","short_description":"...","long_description":"..."}}'`
i get this
`'translations:{"en":{"name":"...","short_description":"...","long_description":"..."}}' => ''`

I solved mapping `$apiRequest` from Slim request to a Guzzle request.

```php
    protected function call(RequestInterface $apiRequest)
        {
            try {
                return $this->client->send($apiRequest);
           } ...
        }

```

```php
    protected function call(RequestInterface $apiRequest)
    {
        // Rebuild the request from Slim to Guzzle
        try {
            // Get method, body, uri, headers by request
            $method = $apiRequest->getMethod();
            $body = $apiRequest->getBody()->getContents();
            $uri = $apiRequest->getUri();
            $headers = [];

            // Clean up all headers
            foreach ($apiRequest->getHeaders() as $key => $value) {
                $headers[$key] = $value[0];
            }

            $request = new Request($method, $uri, $headers, $body);

            return $this->client->send($request);
        } ...
    }
```

I don't understand if it's my fault or a problem between the http packages.
Both share a RequestInterface so this kind of stuff shouldn't happen.

**Comment by damianopetrungaro** [comment]
Copy and paste from Postman app.



`curl -X PUT -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 0fafa1de-47a0-ca43-d2ca-90d2e7ecebb0" -d '{"translations":{"en":{"name":"...","short_description":"...","long_description":"..."}}}' "http://api.gateway.dev/translations/id"`

**Comment by sjzurek** [comment]
Try using
`$body = $apiRequest->getParsedBody();`

Have a look there:
[https://www.slimframework.com/docs/objects/request.html#media-type-parsers](https://www.slimframework.com/docs/objects/request.html#media-type-parsers)

**Comment by damianopetrungaro** [comment]
Same result...i tried more than once in those days 😄

**Comment by JoeBengalen** [comment]
Can you show how you set the body?

Also what is this? It's neither valid PHP nor JSON.
`'translations" => "{"en":{"name":"...","short_description":"...","long_description":"..."}}'`

**Comment by damianopetrungaro** [comment]
@JoeBengalen 
The body is sent by a browser request.
I simply pass the Slim request to Guzzle Client.

Anyway this is the JSON i sent:
`{"translations":{"en":{"name":"...","short_description":"...","long_description":"..."}}}`

Sorry but i pasted wrong 😄

**Comment by damianopetrungaro** [comment]
@JoeBengalen  there's also a cURL [https://github.com/slimphp/Slim/issues/2111#issuecomment-268495682](here)

**Comment by JoeBengalen** [comment]
Ah ok, looking at the cURL command, you post invalid JSON. Does it help if you wrap the root key in an object?

```json
{"translations": {
	"en": {
		"name": "...",
		"short_description": "...",
		"long_description": "..."
	}
}}
```

**Comment by damianopetrungaro** [comment]
@JoeBengalen updated the cURL.
The json is correct anyway in the cURL, the error is when i pass the Slim request to Guzzle Client.

**Comment by chadicus** [comment]
What's the actual error?

> When i tried to get the params from the request $data = $req->getParams();

Remember that `getParams` is not PSR-7 so don't expect it to exist on the guzzle request object.

Also, i've noticed a few slight differences between the  `Request` class that comes with the core `slim/slim` package and the `Request` class that comes with the `slim/http`

It would also help to know which version of Slim and Guzzle you are using.

**Comment by damianopetrungaro** [comment]
Of course $req->getParams(); is not a psr method, but i use it one the server request.

Browser(as Client)  -> Gateway(as Server) -> Build a new Request(as Client) -> Microservice(as Server)

When building a new Request from the gateway i must do:
``` php

 protected function call(RequestInterface $apiRequest)
    {
        // Rebuild the request from Slim to Guzzle
        try {
            // Get method, body, uri, headers by request
            $method = $apiRequest->getMethod();
            $body = $apiRequest->getBody()->getContents();
            $uri = $apiRequest->getUri();
            $headers = [];

            // Clean up all headers
            foreach ($apiRequest->getHeaders() as $key => $value) {
                $headers[$key] = $value[0];
            }

            $request = new Request($method, $uri, $headers, $body);

            return $this->client->send($request);
        } ...
    }
```

And i can't do 
``` php

 protected function call(RequestInterface $apiRequest)
        {
            try {
                return $this->client->send($apiRequest);
           } ...
        }
```

**Comment by damianopetrungaro** [comment]
Someone knows why there's this incompatibility?

**Comment by tuupola** [comment]
It would be helpful if you also provided minimal runnable code which reproduces the problem. Currently I can see your code and understand the problem, but to actually reproduce it I would need to write quite much additional code.

**Comment by damianopetrungaro** [comment]
I'll try to give you a little codebase, so you'll can check the problem.

**Comment by akrabat** [comment]
@damianopetrungaro any luck in producing a small reproducible case?

**Comment by damianopetrungaro** [comment]
I am writing it in my free time, I hope to post it during this week.

Il mar 17 gen 2017, 20:43 Rob Allen <notifications@github.com> ha scritto:

**Comment by geggleto** [comment]
I think he needs to rewind the body after writing to it.

I hate streams.

**Comment by damianopetrungaro** [comment]
Sorry i can't reproduce it locally :/
