### ISSUE TITLE
Stream wrapper issue

### ISSUE THREAD

**Issue by acid24** [slimphp/Slim#2112]
Hi,

I am using mongo-php-library to store files in Mongo via GridFS and I have stumbled upon a problem. I am trying to output a file (to trigger a download dialog in the browser) via some code like this:

```php
$db = (new MongoDB\Client('mongodb://127.0.0.1:27017'))->selectDatabase('mydb');
$bucket = $db->selectGridFSBucket('test');

$stream = $bucket->openDownloadStreamByName('some-file-in-the-database.txt');
$doc = $bucket->getFileDocumentForStream($stream);

$headers = new \Slim\Http\Headers([
    'Content-Type' => $doc['metadata']['mimeType'],
    'Content-Disposition' => sprintf('attachment; filename="%s"', $doc['metadata']['realFilename']),
    'Content-Length' => $doc['length']
]);

$response = new Response(200, $headers, new \Slim\Http\Body($stream));
```

But this causes an error in vendor/slim/slim/Slim/App.php at line 373 where rewind() is called on the body of the response. The problem is that mongo-php-library uses a stream wrapper which apparently falsely advertises that it is seekable (via stream_get_meta_data).

I also opened an issue here mongodb/mongo-php-library#317. Their recommendation is to avoid stream_get_meta_data to determine if a stream is seekable as 

> StreamWrapper implementations have no control over the "seekable" property of stream_get_meta_data() and always advertise themselves as seekable 

and use fseek instead. I guess something like this in vendor/slim/slim/Slim/Http/Stream.php

```php
public function isSeekable()
    {
        if ($this->seekable === null) {
            $this->seekable = false;
            if ($this->isAttached()) {
                $meta = $this->getMetadata();
                $this->seekable = !$this->isPipe() && $meta['seekable'] && @fseek($this->stream, 0, SEEK_CUR) === 0;
            }
        }

        return $this->seekable;
    }
```

I am willing to open a PR if the fseek solution is acceptable.

I am using PHP 7.1.0, Slim 3.7.0 and version 1.1.0 of mongo-php-library

Thanks.

**Comment by geggleto** [comment]
hmm... //cc @akrabat @codeguy ... thoughts?

The obvious part is that you are trying to shove a square into a circle... The simplest solution would be to create a Wrapper Class which would read the contents of one stream and put it into the body of the other.

I'm hesitant on your fix just because using `@` in production is a very big no-no for me.

**Comment by acid24** [comment]
I ended up extending \Slim\Http\Body and overriding the isSeekable method with the code in my previous comment. In other words I worked around the issue so this is not a problem for me anymore. Also the guys from mongo-php-library said that they "have an implementation of seeking for readable streams" coming up in version 1.2.0 which would also fix the specific GridFS issue I was having.

**Comment by geggleto** [comment]
ahhh coolio :) if you could mark as closed that would be great :D
