### ISSUE TITLE
Issue getting URL parameters in Slim 3

### ISSUE THREAD

**Issue by v-escobar** [slimphp/Slim#2114]
Hi there,

I'm using Slim 3.4 with PHP-DI Slim bridge 1.0.3 and I just can't get URL parameters

I have defined the url as follows:

````
// Get plan task
$app->get('/plan/{id}', [GetPlanController::class, 'execute']);
````
And this is the method that handle that url
````
public function execute($request,$response, $args = null)
{
	$id = $request->getAttribute('id');
        ...
}
````
getAttribute method returns null, but if I inspect the value of the attribute property, it has this information stored:
![085e90335ab7c89775373299de9515a0](https://cloud.githubusercontent.com/assets/822629/21546717/17b1b170-cde1-11e6-901c-0f02a4cdeb33.png)

As you can see the information is not properly stored in the data array. Anybody knows if this is related to Slim Bridge integration or it's an issue in Slim.

**Comment by tflight** [comment]
With PHP-DI, you would accept the URL parameter like this.

```php
public function execute($request,$response, $id)
{
    echo $id;
}
```

See [Request Attribute Injection](http://php-di.org/doc/frameworks/slim.html#request-attribute-injection) in the docs:

> As you can see above, the route's URL contains a name placeholder. By simply adding a parameter with the same name to the controller, PHP-DI will directly inject it.

**Comment by v-escobar** [comment]
@tflight Thank you very much, you have saved my day, but still I think it might be an issue in Slim, don't you think?

**Comment by tflight** [comment]
I believe that is the way it is supposed to work. That's the way the PHP-DI documentation suggests it should work.

**Comment by v-escobar** [comment]
@tflight my concern is that if getAttribute method does not work if PHP-DI bridge is included, at least something should be said related to that.

**Comment by campersau** [comment]
I think you are mixing up `getAttribute` with [request params](https://www.slimframework.com/docs/objects/request.html#request-parameter) such as `getParam`, `getQueryParam` ...

**Comment by v-escobar** [comment]
@campersau you are right, it's a typo in my comment.

**Comment by tflight** [comment]
See the Slim docs for [Route Strategies](https://www.slimframework.com/docs/objects/router.html#route-strategies). Note the part about alternative strategies that implement `\Slim\Interfaces\InvocationStrategyInterface`. Then see where PHP-DI [implements the strategy](\Slim\Interfaces\InvocationStrategyInterface).

You can still access attributes in the body from something like
```php
$request->getParsedBodyParam('user_email');
```
and route segments from something like 
```php
$request->getQueryParam('id');`
```

**Comment by akrabat** [comment]
There's an argument that we should always put the route arguments into request attributes, but we don't do it for the `RequestResponseArgs` strategy either.

Thoughts?

**Comment by tflight** [comment]
It would be convenient for me in some instances, but the current implementation is not a pain point.

**Comment by cdekok** [comment]
This is kinda annoying if the pattern changes especially if you want to create something reusable.
Implementation X won't work in application Y because the interface is different because it uses the bridge.

**Comment by v-escobar** [comment]
+1 for @cdekok

**Comment by garnold** [comment]
Possibly relevant: https://github.com/slimphp/Slim/issues/2019

**Comment by geggleto** [comment]
PHP-DI injects the route parameters into the function call of the method.

I don't like hiding everything inside the request object. It doesn't feel right to me.

I think things here are resolved. So I am going to close it :)
