### ISSUE TITLE
How to use classes for routes?

### ISSUE THREAD

**Issue by majoess** [slimphp/Slim#2118]
Hello,

i don't know how I can use Classes like this? How can I get the Request and Response?

`$app->get('/test', myClass);`

**Comment by tflight** [comment]
@majoess check out the [Slim Container Resolution](https://www.slimframework.com/docs/objects/router.html#container-resolution) section of the docs.

**Comment by majoess** [comment]
Hey,
thanks for you reply. How can I create a Controller? Please give me some example.

Best regards,
majoess

**Comment by tflight** [comment]
@majoess , see https://github.com/akrabat/slim-bookshelf/blob/master/app/src/Bookshelf/AuthorController.php

**Comment by majoess** [comment]
Hello,

i don't know how to autoload my Controller with namespace. they are located under /controllers/informationController (+ public function) and informationController.php is in
`namespace miroAPI\Controllers`
