### ISSUE TITLE
Support X-Forwarded-For in Slim_Http_Request

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#212]
Check for `HTTP_CLIENT_IP`, then `X_FORWARDED_FOR`, then `REMOTE_ADDR`.

**Comment by designermonkey** [comment]
This needs reflecting in the `Environment` class, as it only looks for `REMOTE_ADDR` and not `X-Forwarded-For`.

**Comment by codeguy** [comment]
Currently this is done in the Request class, but probably best moved into Environment.

**Comment by designermonkey** [comment]
It would be ok in both I think, unless the `Request` class just looked it up from the `Environment` class, would you agree it would be ok to set the environments `REMOTE_ADDR` to whatever matches, and add a switch of `X-Forawrded = true` or something like that? as the environment is Slim specific, and not entirely related to the `SERVER` variables?
