### ISSUE TITLE
NotFoundException not passed to custom notFoundHandler

### ISSUE THREAD

**Issue by pachico** [slimphp/Slim#2125]
Context: **Slim 3.7.0**
According to #2082, Exception is passed to notFoundHandler, however, in App.php:453 you can read:
```php
/** @var callable $notFoundHandler */
$notFoundHandler = $this->container->get('notFoundHandler');
return $notFoundHandler($request, $response);
```
Am I missing something or this should look more like:
```php
return $notFoundHandler($request, $response, new NotFoundException($request, $response));
```
Cheers

**Comment by akrabat** [comment]
The use-case was for the situation when a user has thrown their own Exception that extends our NotFoundException.

In line 453, there's no exception in play and the request and response are already passed to the handler, so a new Exception isn't created.

Do you have a use-case where you need this Exception to be instantiated  in line 453?

**Comment by pachico** [comment]
Thanks for your reply.
No, I don't have a use case (yet?) but there's something that feels fishy to me where the same (or a child) exception is handled differently if thrown by the system or by a user.
Somehow, it feels like a lack of consistency but once again I don't have a use case to support any change of behaviour.

Cheers

**Comment by akrabat** [comment]
I'm not intrinsically against making the change if there's a reason to do so. I just can't think of one and at the moment, the handler can distinguish between a not found because the route couldn't be found and a not found because the application threw an exception which could be a useful distinction.

**Comment by pachico** [comment]
Fair enough.
Cheers
