### ISSUE TITLE
Trying to Port Singletons to Slim 3 Error: "Cannot use object of type Slim\App as array..."

### ISSUE THREAD

**Issue by fluffywaffles** [slimphp/Slim#2129]
This is probably something I'm doing wrong, but here goes anyway:

I'm porting a Slim 2.x project to Slim 3.x. I have several singletons, and I'm looking at the docs [here](https://www.slimframework.com/docs/start/upgrade.html#changes-to-container) to port them to Slim 3. Here's a minimal example for reproducing:

```php
$app = new \Slim\App();
$app['auth'] = function () {
  /* Nothing has to be in body; same bug occurs with or without a body and proper return value... */
};
```

I get a fatal error, though, that says:

```
PHP Fatal error:  Cannot use object of type Slim\App as array in /Users/{...}/index.php on line xx
```

**Comment by pachico** [comment]
Hi there. It seems you're trying to use the dependency container, which in Slim3 is accessible by doing:
```php
$app->getContainer();
```

Try by doing:
```php
$app = new \Slim\App();
$container = $app->getContainer();
$container['auth'] = function () {
    return new Foo();
};
```

Hope that helps.

**Comment by fluffywaffles** [comment]
Thanks, @pachico. Perhaps we can update the Upgrade Guide docs to reflect this? They currently suggest that you can just... slap stuff onto `$app`. Which apparently you cannot.

I've tried your suggestion now, and I am getting a new error.

```php
// in index.php...
$app = new \Slim\App();
$app->getContainer()['auth'] = function () {
  class auth { 
   public function authorize() {
     return 'SomeThing::SomeMethod';
   }
   // etc.
  }

  return new auth();
};
```

```php
// in routes.php...
$app->get('/...', function () {
  // ...
})->add($app->auth->authorize());
```

New error message:

```
Notice: Undefined property: Slim\App::$auth in /Users/.../routes.php on line xx
```

So, it occurs to me that maybe I need to change the line `$app->auth->authorize()` to be `$app->getContainer()->get('auth')->authorize())`. Which was not clear to me from the docs - which repeatedly state some version of "$app['x']" for getting "x" out of the container. So I tried that, instead:

```php
// in routes.php...
$app->get('/...', function () {
  // ...
})->add($app->getContainer()->get('auth')->authorize();
```

This, finally, appears to work -- but maybe we can update the docs to more clearly state how to put things into, and get them out of, the application container?

**Comment by akrabat** [comment]
Clearly the docs need improving (calling @geggleto!)

You should be able to do this simplification and let Slim sort out the container retrieval:

```
// in routes.php...
$app->get('/...', function () {
  // ...
})->add('auth:authorize');
```

**Comment by fluffywaffles** [comment]
Thanks, @akrabat! I'm not so well acquainted with Slim 3 to feel comfortable offering to edit the docs, but I'd be glad to look at an update if you want an outside opinion on whether things get clearer. :)

**Comment by geggleto** [comment]
_has been summoned_

Yes @akrabat is correct. I will add this as a todo.

If you have any questions please feel free to reopen this issue :)
