### ISSUE TITLE
make a pdf version for Slim 3 documentation

### ISSUE THREAD

**Issue by the94air** [slimphp/Slim#2130]
as you know there is not a lot books for slim 3. can you make a pdf version for Slim 3 documentation has more explaning with examples and stuff like that?

**Comment by JustSteveKing** [comment]
An option for this could be to star the project and read through the docs in github pages? If you follow the project (as the docs are github hosted) it will be easy to read on all devices :)

**Comment by the94air** [comment]
You are right but is there any book that can help me throw. Because i usually does not have internet connection (Stupid ISP New prices ). can you suggest any any book that i can use.

**Comment by JustSteveKing** [comment]
I would recommend any book on SOLID principles or Dependency Injection. If you have time you can download PHP: The Right Way by Josh Lockhart (also the main contributor to Slim).

One thing to bear in mind is that Slim is just PHP. You do not have to earn anything in-particular like you do with other frameworks. You have the freedom to do things yourself, just make sure you understand the middleware / DI container and you will be fine.
