### ISSUE TITLE
Fragments in URI not found

### ISSUE THREAD

**Issue by hornta** [slimphp/Slim#2131]
My URL looks like this:
https://example.com/#myFrag

And then I do
`$container['request']->getUri()->getFragment()`
But it returns empty. Must be a bug.

**Comment by akrabat** [comment]
Web browsers do not send the fragment to the server.

**Comment by hornta** [comment]
But why do the PSR have that?

**Comment by akrabat** [comment]
PSR-7 is for handling all types of HTTP messages, not just server requests.
