### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by yongloon** [slimphp/Slim#2135]
Hi, i had facing the issue "**Method not allowed**" which delete and post method will produce the error.

**Get** method work
$app->get('/post', function (Request $request, Response $response) {
    $posts = Post::all();
    return $response->withJson($posts);
});

**Delete** method show "Method not allowed"
$app->delete('/post/[{id}]', function ($request, $response, $args) {
    $id = $args['id'];
    return Post::destroy($id);
});

Thanks for anyone have the solution.

**Comment by tuupola** [comment]
Example curl request and result of the actual misbehaving`DELETE` request would be helpful.

**Comment by ghost** [comment]
ping @night-cypher

**Comment by yongloon** [comment]
thanks, i solved it using curl request
