### ISSUE TITLE
create-project example oddity with CLI web server

### ISSUE THREAD

**Issue by winks** [slimphp/Slim#2138]
Not saying this is a real problem, but the  "if (PHP_SAPI == 'cli-server') {" part of the *autogenerated* index.php doesn't work out of the box on 5.6

Error:
```
$ php -S 0.0.0.0:9090 -t public public/index.php
PHP 5.6.29-0+deb8u1 Development Server started at Thu Jan 26 09:10:00 2017
Listening on http://0.0.0.0:9090
Document root is /home/florian/code/winks/nano/public
Press Ctrl-C to quit.
[Thu Jan 26 09:11:27 2017] PHP Notice:  Undefined index: path in /home/florian/code/winks/nano/public/index.php on line 9
[Thu Jan 26 09:11:27 2017] PHP Warning:  fwrite() expects parameter 2 to be string, array given in /home/florian/code/winks/nano/vendor/slim/slim/Slim/Http/Stream.php on line 406

# head -n 10 public/index.php
<?php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;

if (PHP_SAPI == 'cli-server') {
    // To help the built-in PHP dev server, check if the request was actually for
    // something which should probably be served as a static file
    $url  = parse_url($_SERVER['REQUEST_URI']);
var_dump($url);
    $file = __DIR__ . $url['path'];

```
Steps to reproduce:
```
$ composer.phar create-project slim/slim-skeleton nano

$ curl -XPOST http://localhost:9090/status

array(1) {
  ["path"]=>
  string(7) "/status"
}
[... errors]
```

**Comment by akrabat** [comment]
How strange, I use PHP 5.6. all the time here with no problems.

**Comment by winks** [comment]
I was just trying to repro some more and I think this an Apache2 ProxyPass onto a CLI server..

```
# works
 curl -XPOST http://localhost:9090/status -d "xx=y"
array(1) {
  ["path"]=>
  string(7) "/status"
}
```

```
# doesn't work
curl -XPOST https://example.org/nano/status -d "xx=y"
array(1) {
  ["host"]=>
  string(6) "status"
}
```

**Comment by akrabat** [comment]
How is Apache2 involved when you're using `php -S` ?

**Comment by winks** [comment]
Sorry, was still editing for clarity.

I think this can be closed as "nobody uses php -S behind ProxyPass unless for testing"

**Comment by akrabat** [comment]
Thanks for working out what was happening.

As this is a skeleton, it's intended to be edited and I think that if you're doing something unusual, then it's not unreasonable to have to edit the code too :)

**Comment by winks** [comment]
Yes, but I'm a firm believer that example code should work out of the box ;)

But 100% my fault not testing with `localhost:9090`, it boils down to

```
# incorrect
  ProxyPass /folder http://0.0.0.0:9090/

# correct
  ProxyPass /folder/ http://0.0.0.0:9090/
```
and then `$_SERVER['REQUEST_UTI']` would be `//subdir` instead of `/subdir` and of course `parse_url` takes it as short for `http://subdir/`.
