### ISSUE TITLE
Performance is Slim ? (question)

### ISSUE THREAD

**Issue by mrzslr** [slimphp/Slim#2139]
i have a simple question .
what is different between pure PHP and Slim framework. i mean in database handling and speed for performing queries . does Slim support all PHP functions? 
what's benefit in it? 
in fact why and when i should use Slim Framework?

**Comment by akrabat** [comment]
Slim is PHP code, so you can use all PHP functions in an application that uses Slim.

The key thing that Slim provides is routing and the encapsulation of HTTP's request and response messages as these are fairly boring to write and every app needs them. This means that you don't have to write the code that works out which function to execute if the url is `/hello` or if it's `/contact`.

**Comment by mrzslr** [comment]
@akrabat Thanks so much.
