### ISSUE TITLE
Service call in middleware with custom request attributes

### ISSUE THREAD

**Issue by tafel** [slimphp/Slim#2144]
Hi,

Currently, I make some authorization checks in middlewares this way:

```php
// configure the service...
$c = $app->getContainer();
$c['authCheck'] = function ($c) {
    $checker = new AuthCheck($c);
    // has a method ->is('something')
    return $checker;
};

// use it...
$app
    ->get('/route', 'controller:method')
    ->add($app->getContainer()->authCheck->is('admin'));
```

I recently discovered that you can call a container service in a middleware like this:

```php
$app
    ->get('/route', 'controller:method')
    ->add('authCheck:is');
```

The problem is that it's not possible to set an argument to the method. Is something like below considered a bad practice and, if not, should it be implemented?

```php
// adapt is() method
class AuthCheck {
    public function is($req, $res, $next) {
        // $req->getAttribute('right') should be set to "admin"
        // do some tests based on this, and then
        return $next($req, $res);
    }
}

$app
    ->get('/route', Controller::CLASS)
    ->add('authCheck:is', ['right' => 'admin']);
```

Thanks for your clarification.

EDIT:
my current implementation (simplified) of AuthCheck is this:

```php
class AuthCheck {
    public function __construct(RightService $right) {
        $this->right = $right;
    }

    public function is($right) {
        $service = $this->right;
        return function (Request $req, Response $res, callable $next) use ($right, $service) {
            if (!$service->pass($right)) {
                throw new Exception("boum, not authorized");
            }
            return $next($req, $res);
        }
    }  
}
```

**Comment by ghost** [comment]
Doesn't it make more sense to have
```php
$app->get('/route', Controller::class)
    ->add(AdminMiddleware::class);

class AdminMiddleware {
    public function __invoke($request, $response, $next) { ... }
}
```
a custom middleware for admin users/routes? In my opinion **Object behaviour must not be configurable**, that's the point OOP encapsulation.

More for middlewares in Slim [https://www.slimframework.com/docs/concepts/middleware.html](https://www.slimframework.com/docs/concepts/middleware.html)

BTW. this question doesn't belong here, you should have posted on StackOverflow

**Comment by tafel** [comment]
Thanks for your answer. The point is I have multiple rights (admin, session.list, session.edit, session.remove, workshop.list, workshop.edit, etc.). I wasn't so sure that creating a class for every single use-case was a good idea.

Maybe I can cheat a little, writing method in route like `AuthCheck:isSessionList` using `public function _call ()` and "guessing" which right to test :-)

It's maybe a bit hacky... In the end, what you suggest is to create a class for each right, or at least one method per right in a class?

Thanks

**Comment by ghost** [comment]
Then if you have more complexity as you specified, you should implement a **basic ACL** or definitely, don't reinvent the wheel and use something like this 

- [https://packagist.org/packages/geggleto/psr7-acl](https://packagist.org/packages/geggleto/psr7-acl)
- [https://packagist.org/packages/slimphp-api/slim-acl](https://packagist.org/packages/slimphp-api/slim-acl)

**Comment by tafel** [comment]
Interesting. So it means two routes definitions. Something like this:

```php
// somewhere in bootstrap...
$slimapp->group('/api', function () use ($slimapp) {
    $slimapp->get('/users', 'UserCtrl:getList');
    $slimapp->post('/users', 'UserCtrl:create');
});

// elsewhere in bootstrap (with slimphp-api/slim-acl)
$acl_configure = [
    // ...
    'guards' => [
        'routes' => [
            ['/api/users', ['user'], ['get']],
            ['/api/users', ['admin'], ['post']]
        ]
    ]
];
```

So I should more or less define my routes twice, one time for defining controllers and not-acl-middlewares, and one time for acl-middlewares. I think that's why I started to "reinvent the wheel". Because I'm trying to keep all my route definitions in one place.

Is it "better" to write routes multiple times, depending on which middleware you use (here ACL)? I'm feeling more comfortable with everything concerning routes written in the same script.

**Comment by geggleto** [comment]
@tafel in theory you could integrate both solutions. You could extend the App class which has an ACL library built in. Then override the `get()`, `post()`...etc methods to add them into the ACL automatically... but of course that is outside the scope of Slim. 

Also if you have any questions and are using my acl library just open an issue on that repo <3.
