### ISSUE TITLE
Response with global variable 

### ISSUE THREAD

**Issue by jimmyphong** [slimphp/Slim#2147]
How to response with global variable . Example my global variable is array

$varaibles = array(
   'api_version' => '1.0',
   'you_request' => 'http://example.com'
)

and in all my response as json , i need append this array to all response data, is that possible ?

Thanks for help !

**Comment by pachico** [comment]
It really seems like a good candidate for a [middleware](https://www.slimframework.com/docs/concepts/middleware.html).
In your case you could implement a middleware that just modifies the response
In pseudo code:
```
function (request, response, next) {

   response = next(request, response)
   newResponse = modifyYourResponseWithYourArrayData(response)
   return newResponse
}
```

Refer to the docs for real world examples.

Cheers

**Comment by geggleto** [comment]
Closing, looks answered.
