### ISSUE TITLE
Wildcard with optional pagination param suffix?

### ISSUE THREAD

**Issue by ryanscherler** [slimphp/Slim#2148]
I'm a bit stumped on how to handle a wildcard parameter with an optional pagination 'trigger'. Here's what I have so far and its not working as I'd hoped:

```
<?php
// Pagination
$pageTrigger = trim($app->getContainer()['settings']['pageTrigger'], '/'); // set to `page` in ENV

// Routes
$app->get("[/{path:.+}[/$pageTrigger/{page:\d+}]]", '\App\Controllers\PageController:page');

// /blog/page/2 <- fails ( Array ( [path] => blog/page/2 ) 

```

This seems to work but forces one to always have a trailing slash:

```
<?php
// Pagination
$pageTrigger = trim($app->getContainer()['settings']['pageTrigger'], '/');

// Routes
$app->get("[/{path:.+}/[$pageTrigger/{page:\d+}]]", '\App\Controllers\PageController:page');

// /blog/page/2 <- works ( Array ( [path] => blog [page] => 2 ) 
// blog <- fails 
```

Any thoughts on how not to have a trailing slash to make this work? I am sure there might be some regex magic I'm overlooking ;-)

**Comment by svanlaere** [comment]
Have you considered using unlimited parameters?

```
$app->get('/[{params:.*}]', '\App\Controllers\PageController:page');
$params = $request->getAttribute('params');
```

Then explode the $params array and use its parts.

**Comment by ryanscherler** [comment]
Hi @svanlaere - I ended up doing that - but was hoping to not have to do that sort of thing and rather just have the optional argument.

**Comment by svanlaere** [comment]
Untested:
$app->get('/blog[/{page:\d+}]', '\App\Controllers\PageController:page');

**Comment by ryanscherler** [comment]
I ended up implementing some route middleware to parse the path and add a `page` argument if needed. See here: https://github.com/ryanscherler/alpine/blob/master/app/src/core/PathPaginationMiddleware.php

It requires this setting in Slim:

```
'settings' => [
  ...
  'determineRouteBeforeAppMiddleware' => true,
  ...
]
```

**Comment by geggleto** [comment]
Look's like you have this solved. Closing :)
