### ISSUE TITLE
getParsedBody() outputs nothing with a PUT request with a non-empty body 

### ISSUE THREAD

**Issue by migueldemoura** [slimphp/Slim#2149]
## Issue
`getParsedBody()` outputs nothing with a non-empty body when using the http method 'PUT'.

## Steps to reproduce

xhr.js
```js
var formData = new FormData($(form)[0]);
$.ajax({
     url: '/endpoint',
     type: 'PUT',
     data: formData,
     async: false,
     cache: false,
     contentType: false,
     processData: false,
     success: function (response) {
          ....
     },
     error: function () {
          ....
     }
});
```

Controller:
```php
$data = $request->getParsedBody();
```
$data is empty.

```php
$data = $request->getBody();
```
$data has something like this:

`------WebKitFormBoundary..... Content-Disposition: form-data; name="data1" something1 ------WebKitFormBoundary..... Content-Disposition: form-data; name="data2" something2 ------WebKitFormBoundary.....--`

Changing both the ajax type in jQuery and the route handler to 'POST' fixes this.

**Comment by tuupola** [comment]
See https://github.com/slimphp/Slim/issues/1396.

**Comment by migueldemoura** [comment]
Closing since it's a duplicate. Thanks, @tuupola.
