### ISSUE TITLE
Only request is passed to route callback (after construction)

### ISSUE THREAD

**Issue by drnasin** [slimphp/Slim#2154]
Reading thru this part:

> Allow Slim to instantiate the controller
> 
> Alternatively, if the class does not have an entry in the container, then Slim will pass the container’s instance to the constructor. You can construct controllers with many actions instead of an invokable class which only handles one action.
```
> 
> class HomeController 
> {
>    protected $container;
> 
>    // constructor receives container instance
>    public function __construct(ContainerInterface $container) {
>        $this->container = $container;
>    }
>    
>    public function home($request, $response, $args) {
>         // your code
>         // to access items in the container... $this->container->get('');
>         return $response;
>    }
>    
>    public function contact($request, $response, $args) {
>         // your code
>         // to access items in the container... $this->container->get('');
>         return $response;
>    }
> }
```
> 
> You can use your controller methods like so.
> 
```
> $app->get('/', \HomeController::class . ':home');
> $app->get('/contact', \HomeController::class . ':contact');
```

It doesn't seem to work this way so I don't know if it's a bug or my misunderstanding of the concept. I use this version and what happens is that slim instantiates the HomeController, passing the container to constructor (so far so good), The problem is that then instead of passing all three (req, res, args) to function home() it just passes the "request". Am I missing something?

**Comment by akrabat** [comment]
Please provide some sample code demonstrating this.

**Comment by drnasin** [comment]
My bad. Misunderstood the documentation! Works as expected!

**Comment by akrabat** [comment]
I'm glad you sorted it
