### ISSUE TITLE
Route Arguments via CI?

### ISSUE THREAD

**Issue by sajov** [slimphp/Slim#2155]
Here [1797](https://github.com/slimphp/Slim/issues/1797) already discussed  but please clarify why it's not similar compared to docs [route-object](https://www.slimframework.com/docs/objects/request.html#route-object).

To avoid passing args around i tried these middleware
```php

class RequestArguments extends AbstractMiddleware
{

    public function __invoke(Request $request, Response $response, callable $next)
    {
        $route = $request->getAttribute('route');
        $request = $request->withAttributes(['route' => $route]);

        $response = $next($request, $response);

        return $response;
    }
}

```

guess make it possible to access route arguments via ci like this

```php
...
        $request = $this->ci->request;
        $route = $request->getAttribute('route');
        $args = $route->getArguments();
...

```
uncertain if  Slim\Http\Request->withAttributes method comments are understand right

life cycle add "routeInfo" and route is gone

**Comment by geggleto** [comment]
What you are looking for is... https://github.com/PHP-DI/Slim-Bridge

```php
$app->get('/{a1}/{a2}', function ($a1, $a2, Response $response) {
   return $response->write($a1 . $a2);
});
```

**Comment by geggleto** [comment]
Closing as resolved. Please let me know if you have any other questions!
