### ISSUE TITLE
Intermittent error in Slim\Collection 

### ISSUE THREAD

**Issue by wshaver** [slimphp/Slim#2160]
I've been fighting this for a bit, and can't figure it out, maybe someone else has or maybe there's a deeper issue here with Slim, PHP, Apache etc. After working just fine for hours, my Slim install will start giving this on all routes:

> Fatal error: Class Slim\Collection contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (IteratorAggregate::getIterator) in F:\Projects\example\server\vendor\slim\slim\Slim\Collection.php on line 21

Maddeningly this issue ***goes away*** if I restart Apache. (For a few hours anyway.)

I found this where someone had a similar problem two years ago, and the person helping badgered them without actually assisting at all: https://community.apachefriends.org/viewtopic.php?p=250966&sid=96ef58aaeb7fe142a7dcdfd506a8683f

I've tried doing a clean wipe and install of my `vendor` directory. This doesn't fix it. I can clearly see that the getIterator file is implemented as expected. 

PHP Version 7.0.12
Windows 7
x86 PHP Build

Any guesses? My apologies if this isn't actually a `slim` problem although other folks may also be having this problem and not finding answers.

**Comment by geggleto** [comment]
Sounds like a bug in your filesystem or opcache.

The class does implement that method.

**Comment by geggleto** [comment]
If/When you can provide more information please reopen this issue. 

Personally, I have a feeling that it's some kinda bug in PHP or Opcache, but from our point of view there is nothing wrong.
