### ISSUE TITLE
Request::getHeader(string) returns all headervalues in one array-item

### ISSUE THREAD

**Issue by jmattheis** [slimphp/Slim#2163]
Found out by [this Stackoverflow question](http://stackoverflow.com/q/42531499/4244993).
Version: 3.7.0

According to the phpDoc of `Slim\Http\Message::getHeader(string)` it should return an array with the header values. But it returns the whole headervalues line with the `,` in it, same goes for `Slim\Http\Message::getHeaders()`.

I've created a failing phpunit test for that:
```
class HeaderTest extends \PHPUnit\Framework\TestCase
{
    public function testHeaderShouldReturnArrayWithHeadersSplitByComma()
    {
        $env = \Slim\Http\Environment::mock(['HTTP_MyCustomHeader' => 'apple,banana' ]);
        $request = \Slim\Http\Request::createFromEnvironment($env);
        $this->assertEquals(['apple', 'banana'], $request->getHeader('MyCustomHeader')); // is actual:  ['apply,banana']
    }
}
```

**Comment by geggleto** [comment]
This is not a bug, we do not explode header data. 
The reason why it says it will return an array, is that you can have multiple new-lines in a header.

`['HTTP_MyCustomHeader' => 'apple\nbanana' ]`

in which case you will receive your array from the header.

**Comment by jmattheis** [comment]
the `\n` or `\r\n`  doesn't make any difference, it just returns an array with one entry with an linebreak,

What would be a usecase for that, I do not see any.

Also I find that some phpDoc is missleading, something like this: (in `getheaders()`
```
     *     // Represent the headers as a string
     *     foreach ($message->getHeaders() as $name => $values) {
     *         echo $name . ": " . implode(", ", $values);
     *     }
```
and for `Message::getHeaderline`

```
     * NOTE: Not all header values may be appropriately represented using
     * comma concatenation. For such headers, use getHeader() instead
     * and supply your own delimiter when concatenating.
```

**Comment by geggleto** [comment]
While you or even I might agree that it's silly.

This comes from the PSR-7 community standard.

https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L43-L68

**Comment by tuupola** [comment]
Sounds like a bug to me too. I understand PSR-7 says that if headers contain either:

```
X-Foo: hello
X-Foo: world
```
or

```
X-Foo: hello,world
```
 
Then `$request->getHeader("X-Foo")` should return `["hello", "world"]` and 
`$request->getHeaderLine("X-Foo")` should return `hello,world`.

**Comment by jmattheis** [comment]
@tuupola I thought that too.

**Comment by akrabat** [comment]
Pretty sure that not all headers use comma a separator

**Comment by jmattheis** [comment]
@akrabat in the [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) its defined that it should be a comma separated list

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list

**Comment by akrabat** [comment]
> @akrabat in the RFC its defined that it should be a comma separated list

> > Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list

i.e. A header may occur once with a comma in it where that comma does not mean two separate values.  It just may not appear twice.

**Comment by akrabat** [comment]
FWiW, Diactoros behaves the same way as Slim.

```
$headers = ['MyCustomHeader' => 'apple,banana'];
$request = new Zend\Diactoros\ServerRequest([], [], null, null, 'php://input', $headers);
var_dump($request->getHeader('MyCustomHeader'));
```

will output:

```
array(1) {
  [0] => string(12) "apple,banana"
}
```

Adding a header of the same name adds a new element to the output array:

```
$headers = ['MyCustomHeader' => 'apple,banana'];
$request = new Zend\Diactoros\ServerRequest([], [], null, null, 'php://input', $headers);

$request = $request->withAddedHeader("MyCustomHeader", "orange");

var_dump($request->getHeader('MyCustomHeader'));
```
gives:

```
array(2) {
  [0] => string(12) "apple,banana"
  [1] => string(6) "orange"
}
```

**Comment by akrabat** [comment]
I don't think this is a bug and nothing in http://www.php-fig.org/psr/psr-7/#headers-with-multiple-values leads me to think that we should explode on `,` in `getHeader()`.

**Comment by viniciusmarangoni** [comment]
I have tested some different kind of requests and something seems inconsistent for me. 

If you do something like this:
```
$targetResponse = $response
                    ->withAddedHeader("test", "value1")
                    ->withAddedHeader("test", "value2");

var_dump($targetResponse->getHeader("test"));
return $targetResponse;
```

The HTTP response will be this:
```
HTTP/1.1 200 OK
Date: Thu, 13 Feb 2020 18:53:15 GMT
Server: Apache/2.4.18 (Ubuntu)
test: value1
test: value2
Vary: Accept-Encoding
Content-Length: 71
Content-Type: text/html; charset=UTF-8

array(2) {
  [0]=>
  string(6) "value1"
  [1]=>
  string(6) "value2"
}
```

That makes you think that if you perform an HTTP request containing two separated headers with the same name (like in the example below), `$request->getHeader("test")` will return an array of size 2. However, according to my tests this is actually not the obtained results.
Request example:
```
POST /test HTTP/1.1
Host: localhost
test: value1
test: value2


```

For the above request, `var_dump` returns the following:
```
array(1) {
  [0]=>
  string(14) "value1, value2"
}
```

Additionally, I was not able to perform **any** kind of HTTP request that makes `$request->getHeader("test")` return an array of size greater than 1. The only way to do this is by programmatically (artificially) append a header using `withAddedHeader`.
