### ISSUE TITLE
Group callbacks should only be run if the group matches

### ISSUE THREAD

**Issue by theodorejb** [slimphp/Slim#2165]
Currently lots of time is wasted initializing routes in groups that don't match the request.

I'm working on a fairly large app with hundreds of routes, and all this unnecessary initialization is slowing down requests by ~50% (I did a before/after test where I commented out the code in all group callbacks except one, and the average request time dropped from 119ms to 80ms).

I realize this would be a BC break, since some people may be relying on code inside a group callback always being run (even when the request is for a route in a different group). However, for the next major release wouldn't the performance benefits far outweigh this small BC break?

**Comment by geggleto** [comment]
I don't think there's a way that this could ever work.

The group function on app acts as a URL builder. It would require a complete rewrite of how we handle grouping.

Imo, if you want a speed up, if it matters... do not use groups at all.
Groups are great in development as it enables you to rapidly prototype something, but there is an overhead attached as you have mentioned in production.

You could possibly use the Cached Router file instead to gain more throughput. 

https://www.slimframework.com/docs/objects/application.html#application-configuration 

### routerCacheFile

Filename for caching the FastRoute routes. Must be set to to a valid filename within a writeable directory. If the file does not exist, then it is created with the correct cache information on first run.
Set to false to disable the FastRoute cache system. 
(Default: false)

**Cautionary note** This might not work if you are executing any other code than defining routes in your group callbacks.

**Comment by silentworks** [comment]
@theodorejb would you be able to provide an example app showing the slowdown, so we can take a look at where we could improve performance please?

**Comment by theodorejb** [comment]
Here's a basic example app: https://github.com/theodorejb/slim-group-performance.

It's not the performance of Slim's route matching that's a problem, but simply the fact that Slim runs all the code in group/subgroup callbacks even when the group doesn't match the active route.

In a real-world app, the code for generating routes in a group callback can be non-trivial and take several milliseconds to run. When it has to run for scores of different groups that don't contain the requested route, this has a negative impact on performance.

**Comment by akrabat** [comment]
This isn't a "small BC break" as not running the route registrations in `group()` will break `urlFor()` which means that you can't create links to those routes.

**Comment by akrabat** [comment]
I'm interested to know what the performance difference is if you use strings rather than closures in `$app->get()`

**Comment by geggleto** [comment]
I can tun some teats at work on the performance. I have a lot of group calls but i do not notice any slowdown at all.

**Comment by garnold** [comment]
@geggleto How does using `routerCacheFile` help? Won't the `group` calls still be invoked during initialization of the app? 

Reason I'm ask is we've been experimenting with `routerCacheFile` and haven't found any noticeable speedup.

**Comment by theodorejb** [comment]
@akrabat I've never used `urlFor()` and I'm not sure what the use case for it would be. Couldn't a user just create their own mapping between names and routes if they wanted to reference a route path in multiple places?

I'm not sure what you mean by "use strings rather than closures in `$app->get()`." Each set of route callbacks relies on a unique class inherited via its `use()` construct - a static callable wouldn't have this info. I updated my example app to make this clearer.

The performance issue isn't from calling Slim's `group()` method, but from executing the function returned by `endpointFactory()` hundreds of times for subgroups that don't match the requested route.

**Comment by silentworks** [comment]
@theodorejb so a `route` callback will always execute when the app is initialized, because this is used for `urlFor()` as noted before. This is something I make heavy use of and many other do also. What we are asking is if you use a string as your `route` callback then you shouldn't have performance issue.

```php
$app->get('/', 'Class:method');
```

This is lazy loaded and only requested when the route is matched, so any code inside of that method won't be executed until the route is matched.

**Comment by akrabat** [comment]
> What we are asking is if you use a string as your `route` callback then you shouldn't have performance issue.

Well, it should be less of an impact than registering closures.

**Comment by theodorejb** [comment]
> What we are asking is if you use a string as your route callback then you shouldn't have performance issue.

How can I pass a class name to the route callback with this approach? You can see a real-world example of this here: https://github.com/theodorejb/phaster/blob/v1.0.2/src/RouteHandler.php#L67.

**Comment by theodorejb** [comment]
> a route callback will always execute when the app is initialized, because this is used for `urlFor()` as noted before. This is something I make heavy use of

If a feature that not everyone uses makes the library 50x slower, IMO the cost is greater than the benefit. Would it be possible for Slim to only run all the callbacks if `urlFor()` is actually used, so those who do not use it won't have to pay the performance penalty?

**Comment by silentworks** [comment]
@theodorejb what is that `$class` and what does it contain? If possible jump in the slack channel, its probably easier to get back and forth quickly.

**Comment by theodorejb** [comment]
@silentworks `$class` is a string containing a class name which the route callback constructs to handle the request.

**Comment by silentworks** [comment]
@theodorejb yeah just looked at the README in the repo, I am working on an example now.

**Comment by akrabat** [comment]
In generally in favour of a tree-like lazily loaded routing solution, but have no idea how it could practically be implemented with FastRoute. Happy to look at at a PR for it

**Comment by silentworks** [comment]
@akrabat I think it could as it would just be a lookup table of route paths that would be necessary, I mean FastRoute kinda generates one when you use RouteCaching.

**Comment by akrabat** [comment]
@silentworks so how would:

```
$app->group(`/users/{id:[0-9]+}`, function () {
    $this->get('/address', 'UserController:address'):
    $this->get('/messages', 'UserController:messages'):
}
```

work?

**Comment by silentworks** [comment]
@akrabat would it not just store

```
[
    '/users/:id/address' => 'UserController:address',
    '/users/:id/messages' => 'UserController:messages'
]
```

**Comment by akrabat** [comment]
How? I thought @theodorejb didn't want the closure to run unless the group's "`url`" was matched?

**Comment by silentworks** [comment]
@akrabat I think @theodorejb issue is to do with the actual `get` running than the actual `group` closure.

**Comment by silentworks** [comment]
@theodorejb I have created an example project so you can have a look at how I would approach this with lazy loading the callback by using a class string.

https://github.com/silentworks/slim-route-group-test

**Comment by theodorejb** [comment]
I tried out this approach in my test repository: https://github.com/theodorejb/slim-group-performance/blob/da1d1dc4b1cea81d352e60752463c1a048b2ccbd/init.php.

Unfortunately, it doesn't improve the performance in any meaningful way (average response time went from 0.33 seconds to 0.32 seconds). I think the reason is that the overhead of creating a closure has just been swapped with the overhead of calling `setArgument` on every route.

**Comment by silentworks** [comment]
@theodorejb I don't think this is being lazy loaded as how it is in my example, you just mapped a callback as a string, in my example its all in the container and the container doesn't get invoked unless the route matches. I think your example will invoke all callbacks even if the route don't match.

**Comment by theodorejb** [comment]
Only the group callbacks are invoked. Your example doesn't use groups.

**Comment by silentworks** [comment]
@theodorejb I would really like to see the test done on a real world app, an app where you don't actually write anything inside of the `group` besides your `$app->[get,post,put,delete]`. I think you are getting a slow down due to the loops you have in that example, each request cycle those loops have to be run.

**Comment by theodorejb** [comment]
Our real-world app has many subgroups inside of groups, just like this example. The example does generate a higher number of groups and subgroups than our real-world app currently has, to simulate expected performance as our API continues to grow.

I could manually write out all the code for group/subgroup callbacks in my example repo, but I don't expect that this will change performance much compared to using the loop. The slowdown isn't from looping, but from registering thousands of routes in groups/subgroups that don't match the requested route.

**Comment by akrabat** [comment]
The point still stands that FastRoute doesn't support the concept that you want so you have two choices that I can see:

1. Write a PR to Slim that creates the concept of group objects that register the group's URL to the router which upon matching removes all current routes, adds the child routes to the router and then re-run the router to match these. The PR will also need to ensure that `pathFor()` continues to work as currently - i.e. you can retrieve the URL for any other group's route that has a name.

2. Implement a simplistic manual check in `group()` before adding the child routes.

    e.g.

    ```php
    $app->group('/users', function () {
        $uri = $this->getContainer()->get('request')->getUri();
        $path = $uri->getPath();

        if (strpos($path, '/users') === 0) {
            $this->get('/one', 'UsersController:one');
            $this->get('/two', 'UsersController:two');
            $this->get('/three', 'UsersController:three');
        }
    });
    ```

**Comment by geggleto** [comment]
I agree with @akrabat last comment. :) I am closing this. But please reopen if you feel like writing a PR for this use case.
