### ISSUE TITLE
error_reporting() and php.ini

### ISSUE THREAD

**Issue by diananana** [slimphp/Slim#2167]
Hi,
I am using  Slim version 2.6.1  and was wondering if error_reporting function should report notices? The code in the function handleErrors() is the same in 2 different environments and one of them is logging notices and other one does not. I had to resolve the issue by hard coding as below.

```php
public static function handleErrors($errno, $errstr = '', $errfile = '', $errline = '')
$error_reporting = E_ALL & ~E_DEPRECATED & ~E_NOTICE;
        if (!($errno & $error_reporting)) {

            return;
        }
       throw new \ErrorException($errstr, $errno, 0, $errfile, $errline);
    }
```

Any suggestions on how to avoid this? Also, would Slim  override error_reporting settings from php.ini or would it just ignore?
Thanks

**Comment by geggleto** [comment]
I'm sorry, I am not totally sure what exactly you are asking here.

Slim v2 does provide a facility to catch some errors, however due to the nature of php, not all errors will invoke Slim's error handler.

**Comment by tallona** [comment]
@geggleto I think the question above it that Slim 2.x is throwing fatal errors on notices when a notice shouldn't throw an error.

**Comment by aromka** [comment]
Had the same issue, this helped - https://github.com/slimphp/Slim/issues/1454#issuecomment-132616067

**Comment by geggleto** [comment]
Closing
