### ISSUE TITLE
Slim 2.6.3: XSS vulnerability for route config

### ISSUE THREAD

**Issue by preflight** [slimphp/Slim#2168]
In Slim 2.6.3, for this defined route:
```
$app->get('/:route(/)(:ref(/))', function($route, $ref = null) use ($app) {
  // ...
})->name('foobar')->conditions(array('route' => '(foobar|foo|bar)'));
```

If the following string is appended to the `$route`:
```
occy'-alert("xss vulnerable")-'olz88
```

...like this:

```
https://google.com/foobaroccy'-alert("xss vulnerable")-'olz88
```

...an alert window is triggered indicating an XSS vulnerability.

Modifying the route definition to the following eliminates the vulnerability:

```
// before
$app->get('/:route(/)(:ref(/))', function($route, $ref = null) use ($app) {

// after
$app->get('/:route(/:ref(/))', function($route, $ref = null) use ($app) {
```

**Comment by akrabat** [comment]
Surely the problem you are seeing is related to the fact that you are not properly escaping `$ref` when you render it?

Please show a complete minimal example that shows what you are seeing.

**Comment by preflight** [comment]
@akrabat - You're right; thanks for reviewing
