### ISSUE TITLE
controllers auto load

### ISSUE THREAD

**Issue by blendsoft** [slimphp/Slim#217]
hello

I want to use external controllers files, which will be autoloaded
so i made 
controllers dir in main dir
and MainController.php in it:

<?php..
    namespace controllers;..
    class MainController {..
        public function index() {..
            echo 'test';
        }..
    }..

and route in index.php:

$app->get('/', function(){
    //require_once('controllers/MainController.php');..
    $controller = new controllers\MainController();
    $controller->index();
});

but i want controller will be autoloaded
but autload methods autoload only files with "Slim"

so I changed :

public static function autoload( $class ) {

if ( strpos($class, 'Slim') !== 0 ) {
    $class = str_replace('\', '/', $class) . '.php';..
    require_once($class);.
 }
$file = dirname(**FILE**) . '/' . str_replace('_', DIRECTORY_SEPARATOR, substr($class,5)) . '.php';
if ( file_exists($file) ) {
  require $file;
}
}

now controllers are autoloaded
It would nice feature if not only Slim classes can by autoloaded

**Comment by codeguy** [comment]
You should write and register your own autoloader instead of modifying Slim's autoloader. You can queue more than one. If the first does not find a class, the next will be called, and so on. See this page for details:

http://us3.php.net/manual/en/function.spl-autoload-register.php
