### ISSUE TITLE
Not show data from mysql

### ISSUE THREAD

**Issue by herudi** [slimphp/Slim#2172]
$app->get('/note', function() {
    try {
        $db = getConnection();
        $stmt = $db->query("select * from note");
        $data = $stmt->fetchAll(PDO::FETCH_OBJ);
        echo json_encode($data);
    } catch (PDOException $e) {
        echo $e . getMessage();
    }
});

table note is 1000 row. but is 10 row working. why ?

**Comment by pachico** [comment]
I fail to see how is this related to Slim. You might want to use another forum for your issue.

**Comment by geggleto** [comment]
I'm sorry but this is not a slim core issue. Perhaps try something like Stackoverflow
