### ISSUE TITLE
$response->header(x,y) instead of $response['x'] = y

### ISSUE THREAD

**Issue by 84564221** [slimphp/Slim#218]
The functionality to add a customized Response Header by array has changed in the latest branch 1.5.1.4-3-ge3d59c1.

The function works now with:

```
    $response = $app->response();
    -$response['Content-Type'] = 'application/json';
    +$response->header('Content-Type', 'application/json');
```

**Comment by hexa2k9** [comment]
Hi,

I think it's the way it is supposed to be. I'm working with headers like `$app->response()->header('key', 'value')` for ages .. It's on the docs as well like that: http://www.slimframework.com/documentation/stable#response

Regards,
Chris

**Comment by codeguy** [comment]
It works both ways. I was experimenting with an easier, quicker way to set headers and iterate over them.

**Comment by BigBlueHat** [comment]
I'd prefer to have it both ways actually (via [ArrayAccess](http://us3.php.net/manual/en/class.arrayaccess.php), maybe?).

Regardless, the documentation reflects the (old?) array access approach, and likely needs updating:
http://www.slimframework.com/documentation/stable#response-header

I'd update it via a patch request, but I'm not sure which you want or if the array access approach is just out "for now."

Thanks.

**Comment by codeguy** [comment]
@BigBlueHat It'll still work both ways. I intend to leave it that way.

**Comment by BigBlueHat** [comment]
Hmmm...guess I need to upgrade...
"Fatal error: Cannot use object of type Slim_Http_Response as array..."

Will do, and retest.

Thanks.
