### ISSUE TITLE
Slim_Middleware_SessionCookie problem ?

### ISSUE THREAD

**Issue by imknight** [slimphp/Slim#219]
it seem like it will create 2 cookie with 2 different path , one is the root path and another one is route path.

example my url is    domain.com/account/

it will create 2 cookie with path "/" and path "/account"

this causing error for decodeSecureCookie because the first param is expected to be a string, in stead of array.

[10-Jan-2012 13:24:15] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'explode() expects parameter 2 to be string, array given' in /Users/knight/Dev/web/tuts/Slim/Http/Util.php:210
Stack trace:
#0 [internal function]: Slim::handleErrors(2, 'explode() expec...', '/Users/knight/D...', 210, Array)
#1 /Users/knight/Dev/web/tuts/Slim/Http/Util.php(210): explode('|', Array)
#2 /Users/knight/Dev/web/tuts/Slim/Middleware/SessionCookie.php(118): Slim_Http_Util::decodeSecureCookie(Array, 'CHANGE_ME', 0, 0)
#3 /Users/knight/Dev/web/tuts/Slim/Middleware/SessionCookie.php(101): Slim_Middleware_SessionCookie->loadSession(Array)
#4 /Users/knight/Dev/web/tuts/Slim/Slim.php(1148): Slim_Middleware_SessionCookie->call(Array)
#5 /Users/knight/Dev/web/tuts/tuts/index.php(43): Slim->run()
#6 {main}

  thrown in /Users/knight/Dev/web/tuts/Slim/Http/Util.php on line 210

**Comment by codeguy** [comment]
Thanks for the report! I'll have a look at this tonight.

**Comment by codeguy** [comment]
Can you show me how you are adding the `Slim_Middleware_SessionCookie` middleware to your application? You can post it here publicly, or you can post a private message http://help.slimframework.com, or you can email me the code to info [at] slimframework [dot] com.

**Comment by codeguy** [comment]
Nevermind. I see where the bug is. Thanks for bringing this to my attention.

**Comment by codeguy** [comment]
Just pushed a fix. Tested this out both in a unit test and with a quick test app. Seems to work for me. Does this update work for you? Be sure you pull the latest down from the develop branch.

**Comment by imknight** [comment]
yup it work, thanks for the update.
