### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Router cacheFile directory must be writable

### ISSUE THREAD

**Issue by flanderboy** [slimphp/Slim#2193]
Hello everyone,
i'm setting this config.php on my SLIM 3 App

```
Array
(
    [displayErrorDetails] => 1
    [addContentLengthHeader] => 
    [determineRouteBeforeAppMiddleware] => 1
    [view] => ./includes/view/
    [static] => ./static/
    [routerCacheDisabled] => (false)
    [routerCacheFile] => ./cache/
)
```

The error is 
`
Fatal error: Uncaught RuntimeException: Router cacheFile directory must be writable ... in slim/slim/Slim/Router.php:130
`

the /cache/ directory is 

`drwxrwxrwx  2 www-data www-data`

Any idea?
Tks
Stefano

**Comment by akrabat** [comment]
it's probably not relative to public. Try a fully qualified directory using `__DIR__ . '/../cache/'` (or whatever)

**Comment by flanderboy** [comment]
I Rob,
i'm changes the path 

`$config['routerCacheFile']						= __DIR__ . '/cache/';`

the dir /cache/ is inside the root of project but does not change.

**Comment by akrabat** [comment]
`__DIR__` is the directory of the file you are in. This is probably not in the root…

**Comment by flanderboy** [comment]
normally not, but in this case i want to try the cache and i put 

```
/config.php 
/index.php 
/cache/ 
```

in the same place

**Comment by geggleto** [comment]
You cannot write a file to a directory.

 [routerCacheFile] => ./cache/myCacheFile

**Comment by flanderboy** [comment]
i write them... 

`drwxrwxrwx 2 www-data www-data /cache/`

**Comment by geggleto** [comment]
You need to specify a FILENAME in your cache folder.

**Comment by geggleto** [comment]
From https://github.com/nikic/FastRoute

```php
$dispatcher = FastRoute\cachedDispatcher(function(FastRoute\RouteCollector $r) {
    $r->addRoute('GET', '/user/{name}/{id:[0-9]+}', 'handler0');
    $r->addRoute('GET', '/user/{id:[0-9]+}', 'handler1');
    $r->addRoute('GET', '/user/{name}', 'handler2');
}, [
    'cacheFile' => __DIR__ . '/route.cache', /* required A FILENAME */ 
    'cacheDisabled' => IS_DEBUG_ENABLED,     /* optional, enabled by default */
]);
```
