### ISSUE TITLE
[Question] Reading a JSON file

### ISSUE THREAD

**Issue by JCarlosR** [slimphp/Slim#2194]
Hi.
I am trying to read JSON file located in my ```/public``` folder.

For that I am using the next lines:

```
$app->get('/employees', function ($request, $response, $args) {
    $str = file_get_contents('employees.json');

    return $this->renderer->render($response, 'employees.phtml', ['str' => $str]);
});
```

Unfortunately I am getting the next error: 

```
Warning: file_get_contents(employees.json): failed to open stream: No such file or directory in [...]
```

I have tried to read the file with several paths but I can't get it working.

Please help me with some ideas.
It is my first time using Slim framework.

Thank you in advance.

**Comment by adelowo** [comment]
This error is from your end.. Is your `index.php` file in `/public` ?

**Comment by JCarlosR** [comment]
@adelowo Yes. I can see the ```http://localhost:8080/employees.json``` right.

But I can't read it using ```/employees.json``` in the ```file_get_contents```.

I finally got it working, but in a different way:
```file_get_contents(__DIR__ . '/../public/employees.json');```

There is no a variable like the DIR but pointing to the public directly?

Thank you.

**Comment by akrabat** [comment]
> There is no a variable like the DIR but pointing to the public directly?

No. PHP has the concept of current working directory, but unless you specifically set it, you can't be sure where it is.  That's why `__DIR__` exists - which is the directory of the current file.

**Comment by OptimusCrime** [comment]
Not a Slim related problem? Suggest closing this issue.

**Comment by JCarlosR** [comment]
@akrabat Thank you.

I got it working.
