### ISSUE TITLE
flash msg not working

### ISSUE THREAD

**Issue by imknight** [slimphp/Slim#220]
follow the wiki and testing the flash msg and it seem like not working.
I belive it should be after $app->flash('key','msg) then we can use $flash[key] in the template, but currently on dev branch it doesn't really work.

**Comment by codeguy** [comment]
Have you enabled a PHP session, or have you added the `Slim_Middleware_SessionCookie` middleware to your app?

**Comment by imknight** [comment]
yup tested both also can't, nothing in the $_SESSION

**Comment by codeguy** [comment]
Hmm. Can you send me code that demonstrates this not working? I'm testing the development branch right now and it works as expected for me. If I can see your code I may be able to see what is causing this not to work. This example app does work for me:

```
require 'Slim/Slim.php';

$app = new Slim();

$app->add('Slim_Middleware_SessionCookie');

$app->get('/foo', function () use ($app) {
    $app->flash('info', 'Hello there');
    $app->redirect('/bar');
});

$app->get('/bar', function () use ($app) {
    var_dump($_SESSION);
});

$app->run();
```

Josh

**Comment by codeguy** [comment]
Also, an important bug fix was pushed yesterday that fixed a bug in `Slim_Middleware_SessionCookie`. If you are using that middleware, be sure you pull down the latest code.

**Comment by imknight** [comment]
ya i m the one reporting that bug : ) , k will try to post it later when I have time.

**Comment by codeguy** [comment]
haha. Sorry about that. It's early and I've yet to have my coffee :P

**Comment by codeguy** [comment]
Any luck? I'm unable to duplicate. Let me know tonight. Otherwise I'll close this out and we can continue troubleshooting in a forum thread at http://help.slimframework.com.

**Comment by imknight** [comment]
sorry I was rather busy for the past 2 day, just did another round testing and found the problem.

found the problem after I flash and redirect, i redirect to a url without ending slash and my controller is the one with ending slash, so it redirect one more time, thats why the session is gone.

closing this issue.

**Comment by imknight** [comment]
sorry just a follow up base on the Doc ,  

The message in the example below will be available in the variable flash['info'] in the current request’s View templates.

does it mean i should be able to use $flash['info'] variable on the render() template ?

**Comment by codeguy** [comment]
@imknight Yes, but how you access the variable in your templates depends entirely on the template system you are using. If you are using the default `Slim_View`, you will access it with `$flash['info']`. If you are using Twig, you will access it with `flash.info`, and so on.
