### ISSUE TITLE
getHeader('Accept') returning a single value array containing a comma separated string.

### ISSUE THREAD

**Issue by adjenks** [slimphp/Slim#2200]
The following should return an array containing each accepted type, but instead it returns an array of length 1 with the first element containing a comma delimited string.
```
$app->get('/', function($request, $response){
		if($request->hasHeader('Accept')){
                        $accepts = $request->getHeader('Accept');
			$response = $response->getBody()->write(var_export($accepts,1));
		}
		return $response;
	});
```

I believe what it is supposed to return is something like what is in this variable:
`$accepting = explode(',',$request->getHeader('Accept')[0]);`

**Comment by tuupola** [comment]
See https://github.com/slimphp/Slim/issues/2163. It is because you are receiving one `Accept` header with concatenated values. If you receive multiple headers it will return array with multiple headers.

**Comment by adjenks** [comment]
Ah, alright. I wasn't considering receiving many of the same header. I suppose I just have to stick with exploding it myself.
It seems silly that the web supports multiple headers, each containing lists.

**Comment by adjenks** [comment]
@tuupola 

After further reading I think the behavior I expected may still be correct.
According to rfc2616-sec4:

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded. 

So, because it MUST be possible to combine them into one, which is what I was expecting, I believe it should return a list of strings, explode()'d on the comma, representing all of the data in all of the headers. I don't think it should include a list of strings each representing one header all together including commas, since there is usually only one anyways and the standard says they must be able to be combined.

Also, does this then mean that Slim's getHeaderLine() should return an array, each containing one line from each of the received headers with the same name if present? If so, it would be going against the standard since PSR-7 says that getheaderLine() returns the following:

> * @return string A string of values as provided for the given header
>      *    concatenated together using a comma. If the header does not appear in
>      *    the message, this method MUST return an empty string.

Based on Slim's behavior of getHeader(), getHeaderLine() should return an array of strings. Which is basically what getHeaderLine() does. So then what would the purpose of getHeaderLine be?

So I would like to reaffirm that I believe getHeader should return: An array of strings, containing no commas, containing all the separate values of the headers. If there were multiple headers, their values should be combined in order.

**Comment by geggleto** [comment]
Unfortunately that is not how things work :( having commas in headers is valid. Headers are determined by newline characters. I didn't write the HTTP spec so don't shoot the messanger :D

Now if you wish; one could write a Middleware that would "clean" the headers ... but that would be something a middleware author would write.

GetLeaderLine() returns the entire header.

Example:

```
X-My-Header: 123,
456,
789,
...
```
Get Header Line will return the full string including newline
getHeader('X-My-Header') will explode on the NEW LINE character and return a set of headers with the commas.

**Comment by adjenks** [comment]
I guess it is a "Slim" framework.

**Comment by tuupola** [comment]
@adjenks I am well aware of the the RFC and that is how I also originally understood it. However as @geggleto explained we cannot just blindly explode with commas since comma is a valid character in a header value. This is quite confusing part of the RFC.

> I guess it is a "Slim" framework.

This is also how Diactoros works.

**Comment by geggleto** [comment]
FWIW this is how most PSR-7 implementation works. While I realize it can be confusing ... there was a great deal of thought that went into it.

I will think about how to better communicate this to our users... it's quite a difficult problem.
