### ISSUE TITLE
Slim 3.X $request->getUri() gives different results if called in a subrequest

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2203]
Hi Guys,

I'll try and explain as simply as possible, using Slim 3.X to create a REST API, I have monolog logging set up and whenever a route is called it makes a call similar to the below before anything else.

      $this->logger->info($request->getMethod() . ": " . $request->getUri() .  " Starting");

I get an entry like the below in the logs:

"POST: http://localhost/base_path/path_name starting"

When I call the route from Swagger UI, that works fine, however if I call the route from within another route, for example below:

        $url = "route_name";
        $reqType = 'POST';
        $res = $app->subRequest($reqType, $url, "id=1234");

The same logging call is invoked and I get an entry like:

"POST: http://localhost/base_path/path_name starting"

http://localhost/path_name

For some reason it drops the BASE_PATH from the uri when called as a subRequest.

The REST API is in a sub folder at the root of my server, the log entry is misleading obviously but it showed me that I can't trust getURI to behave the same because it isn't returning the actual URI from my perspective.

Am I missing something?

**Comment by geggleto** [comment]
Yes. Calling a route within a route is not best practice and we will be depricating it in 4.0.

In this case you should not be logging the uri to the action but some other information. Like the class and method that is being invoked. if tou are not using classes and methods then you should be refactoring to do so.

A short term solution would be to modify the reqeust object directly.

**Comment by ghost** [comment]
Thanks @geggleto, can you explain why it's not good practice please? 

In this case I have 3 routes which are used for specific purposes to wrap and call 3rd party APIs and are used individually by, however a seperate requirement of the UI is orchestrate all three calls in certain circumstances, in which case having one route that fires the other three seems quite logical. So in this case I want to log the route call and parameters, when they are called directly, and also when they are orchestrated.

I am using classes and methods for some aspects of the code, however in this case I don't see the need to refactor 3 classes only for the purpose of orchestrating calls to the other routes, seems like extra complexity for little gain.

Can you provide some guidance on where/how to modify the request object as per your last comment please?

Deprecating the ability in future versions is fine, but when people want to do it, then we can obviously just go around the framework by using something like Curl to make a call to outside the current app, seems better to facilitate it in a way that make sense in the framework rather than have people work around it particularly if they have already coded against the current solution.

**Comment by geggleto** [comment]
What you want to do is wrap those 3 routes in a Class.

```php
class MyExternalAPI {

    public function __invoke(Request $req, Response $res, array $args) {
           
    }

}
```

You can add it to the container
```php
$container = $app->getContainer();
$container[MyExternalAPI::class] = function ($c) {
     return new MyExternalAPI();
};
```

Finally add it as a route
```php
$app->get('/path', MyExternalAPI::class);
```

Ideally you are using proper practices and you have no domain logic in your action methods at all.
The reason for this is that you do not want to tie your business logic to your framework. It should be separate. When designing it this way, you can then use this logic in other places in your application [ your use case ].

Example...

public MyExternalAPI:getData($options) => Returns an array formatted data.
You can simple access this class from other sub-systems in your app. You can still keep invoke so you can simply return a JSON formatted representation of the data.

I hope this helps.

If this is for a production/money making product both myself and @akrabat provide consulting services on these sorts of System Design problems, if not I would recommend checking out our slack. It's very complex to discuss in a github thread.

**Comment by ghost** [comment]
Thanks for the clarification, that helps a lot.
