### ISSUE TITLE
ipv6 address without port causing output

### ISSUE THREAD

**Issue by IceReaper** [slimphp/Slim#2209]
https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Uri.php#L188

should be ````if (count($matches) > 2 && $matches[2]) {````
else this warning is always displayed:
````Notice: Undefined offset: 2 in ...\vendor\slim\slim\Slim\Http\Uri.php on line 188````

**Comment by geggleto** [comment]
While I personally haven't discovered this bug.... We should have at minimum 1 unit test to ensure that IPv6 isn't causing problems.
