### ISSUE TITLE
Passing data from route to middleware

### ISSUE THREAD

**Issue by tchapi** [slimphp/Slim#2210]
Hi,

I understand it is possible to pass attributes (in the request object) from middleware to route, but is the opposite possible ? Is there a way to pass something to the middleware from the route? We cannot use the response object for that (PSR-7), but there must be a way, no ?

This doesn't work (foo is `null`, and not `[ 'some' => 'array']` as expected) : 

    $app->group('/api', function () {
         $this->get('/test', function ($request, $response, $args) {
             $request = $request->withAttribute('foo', [ 'some' => 'array']);
             return $response->withStatus(200);
         });
    })->add( function ($request, $response, $next) {
          $response = $next($request, $response);
          $foo = $request->getAttribute('foo'); // foo is null
          return $response;
    });

**Comment by akrabat** [comment]
The only way is to use a global (probably via the container so that you think you're not using a global…)

**Comment by geggleto** [comment]
The route only passes the response object back through the chain of middleware... so there is no direct way to do it without accessing a system service outside of that. As @akrabat has explained you might be able to use a container object this way.

Something like this...
```php
Interface InMemoryRequestAttributes
{
    public function add($item, $value);
    public function get($item, $value);
}
```

In our route you can access the instance via the Container to add, and in your middleware access it via the container to get.

**Comment by tchapi** [comment]
Ok understood, thanks a lot for your answers
