### ISSUE TITLE
$request->getQueryParams() with basic Auth

### ISSUE THREAD

**Issue by thaibnai** [slimphp/Slim#2212]
when using $request->getQueryParams() with basic Auth , it includes the path in the returned array 
`array(2) {
  ["/api/v1/customers/properties?page"]=>
  string(1) "8"
  ["per_page"]=>
  string(1) "10"
}
`

**Comment by geggleto** [comment]
What middleware are you using?

**Comment by geggleto** [comment]
I'm closing this as I have no clue what it's about. Feel free to reopen when you can provide more info.
