### ISSUE TITLE
"Slim" Title Easy Customization

### ISSUE THREAD

**Issue by designcise** [slimphp/Slim#2214]
I haven't really come across a setting parameter (or passing of an argument) that allows for removal of "Slim" brand name from pages such as error reporting. Although, I know these pages can be replaced by custom pages, still if one chooses to use the existing template, it should be easy-to-customize. For example:

```
$config['defaultAppTitle'] = 'Designcise';
```

should replace all instances of the 'Slim' brand name with the user-specified name for the application. Could this be something that may be added to future releases?

**Comment by silentworks** [comment]
I don't think we will consider this, as you stated you can already change these by using custom pages. The Slim name is part of the framework branding and should remain so in the core codebase that is provided.

**Comment by designcise** [comment]
@silentworks yeah but for people looking for a quick-start, it's not really friendly. Think of it this way, why would anyone want to show 'Slim' brand on their website? I'm just saying a user should easily be able to overwrite the 'slim' name across the framework with a simple setting. Please do reconsider, thanks!

**Comment by silentworks** [comment]
@designcise I think a more important question is why would you be running your production website in development mode? You will only see Slim in an error if you are running it in development mode, otherwise this is not seen.

**Comment by designcise** [comment]
@silentworks ahh, totally slipped my mind, but I can still imagine some scenarios where it may be useful such as demonstrating to a client in development mode, or making a presentation. Customization is never a bad thing.

**Comment by silentworks** [comment]
@designcise We want you to give credit where credit is due, if the project is built on Slim, let it be known it is built on Slim, especially in development mode. We don't want people trying to sell the Framework as their own, it even builds confidence for your client when they know you are building on a already solid codebase (not that they would be interested, unless they are a technical client). It also mean that the next developer who takes over doesn't need to guess which framework you used.

If you are ever so concerned about the name leaking out in your presentation, switch your application to production mode for your presentation. Actually by default out of the box, Slim is in production mode. (Note we are talking about debugMode being off, not that we are adding any extra production optimisations for you).

To be clear, we will not be facilitating this sort of functionality that you requested in the core of the framework.
