### ISSUE TITLE
withJson sometimes appending extra curly brace to serialized body

### ISSUE THREAD

**Issue by alexweltman** [slimphp/Slim#2217]
I have a web page that polls the server every 2 seconds.  Our entire REST API is defined with slim
When calling this route from the client, the response body occasionally has an extra curly brace appended to the end, which causes JSON parsing to fail in the client.   I have not seen this in any of my other routes.  The last place I touch the body is in a middleware class that adds the appropriate HTTP status to the body.

Before I return the body at the end of my Slim route, I print out the JSON:
```php
error_log(json_encode($body, JSON_PRETTY_PRINT));
```
```json
{
  "time": 1493771061,
  "interfaces": {
    "eno1": {
      "bytes": 2222599052,
      "packets": 23312437,
      "ip": "10.3.3.50"
    },
    "eno2": {
      "bytes": 0,
      "packets": 0
    },
    "enp10s0f0": {
      "bytes": 0,
      "packets": 0
    },
    "enp10s0f1": {
      "bytes": 337364761057900,
      "packets": 830662506879
    }
  }
}
```
Next I call 
```php
return $response->withJson($body, $statusCode);
```

And here is the JSON when it is received in the client. (It can't be auto-formatted because it's invalid json). Notice the extra brace at the end:
```json
{"time":1493771061,"interfaces":{"eno1":{"bytes":2222599052,"packets":23312437,"ip":"10.3.3.50"},"eno2":{"bytes":0,"packets":0},"enp10s0f0":{"bytes":0,"packets":0},"enp10s0f1":{"bytes":3.373647610579e+14,"packets":830662506879}}}}
```

Again, this doesn't happen every time I call the route.  Probably 1 out of every 40 times.  However, this route is polled every 2 seconds constantly, so 1/40 is significant.

Anyone have any idea?

**Comment by akrabat** [comment]
Take out as much code as you can until the problem goes away and then add back in.

**Comment by geggleto** [comment]
I cannot think of anything that would do this except for some kind of middleware that is tinkering with the Response Body.

**Comment by tuupola** [comment]
I would try disabling the `Content-Length` header to see if there is more unexpected JSON in the response and the header itself is off by one for some reason.

**Comment by alexweltman** [comment]
Thanks guys! Disabling the content-length header didn't fix it.  Next I will try disabling all my middleware.
