### ISSUE TITLE
Simplexml_load_string() warning/Fatal output buffer error when POSTing invalid xml

### ISSUE THREAD

**Issue by jasonetwork** [slimphp/Slim#2218]
I came across an unexpected error while creating a slim application. I noticed that if invalid XML is submitted to a POST route with an application/xml content type header, the following errors are outputted:

`<br />
<b>Warning</b>:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in <b>/var/www/vendor/slim/slim/Slim/Http/Request.php</b> on line <b>202</b><br />
<br />
<b>Warning</b>:  simplexml_load_string(): rrr&lt;breakfast_menu&gt;&lt;food&gt;&lt;name&gt;Belgian Waffles&lt;/name&gt;&lt;price&gt;$5.95&lt;/price&gt;&lt;descri in <b>/var/www/vendor/slim/slim/Slim/Http/Request.php</b> on line <b>202</b><br />
<br />
<b>Warning</b>:  simplexml_load_string(): ^ in <b>/var/www/vendor/slim/slim/Slim/Http/Request.php</b> on line <b>202</b><br />
<br />
<b>Fatal error</b>:  Uncaught RuntimeException: Unexpected data in output buffer. Maybe you have characters before an opening &lt;?php tag? in /var/www/vendor/slim/slim/Slim/App.php:547
Stack trace:
#0 /var/www/vendor/slim/slim/Slim/App.php(339): Slim\App-&gt;finalize(Object(Slim\Http\Response))
#1 /var/www/vendor/slim/slim/Slim/App.php(293): Slim\App-&gt;process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#2 /var/www/html/sandbox2/index.php(18): Slim\App-&gt;run()
#3 {main}
  thrown in <b>/var/www/vendor/slim/slim/Slim/App.php</b> on line <b>547</b><br />`

You can easily replicate this error by creating a simple Slim application with a single post route, and try performing a POST request with an "application/xml" content-type header and invalid/broken xml content in the body. Obviously users should not be submitting invalid XML, but there is always the possibility of this occurring. If you tell PHP to ignore the warnings, Slim returns a 500 Internal Server Error. Is there a way to avoid this problem? My initial thought is that If XML is expected, but it is invalid, should Slim not just return the body as a string instead of just failing?

**Comment by pachico** [comment]
You might want to have a middleware that will just validate xml and, given a malformed xml, return a custom error to client.

**Comment by akrabat** [comment]
ideally it should return a 400

**Comment by jasonetwork** [comment]
Yup, that's exactly what I landed up doing, and it works fine with the middleware. It just seems wrong to have to make a "patch" for something like this. This problem doesn't exist when using JSON data. It just seems so buggy the way it is right now. I actually think the solution is a simple fix. If malformed XML is detected, it should simply return null for $request->getParsedBody(). This would fix the problem, IMO.

**Comment by pachico** [comment]
While I understand the issue, I don't think it should be the framework's responsibility to deal with it, especially being a "micro" framework.
By doing what you say, the framework should make business assumptions, which, in my opinion, goes against the beauty of it.

**Comment by jasonetwork** [comment]
Well, if that's the case, then there shouldn't even be a getParsedBody method. With your logic, we might as well just retrieve the raw body data and validate it ourselves in all cases. I don't think its asking too much to simply return null if malformed XML is being submitted.

**Comment by akrabat** [comment]
On the contrary, we intentionally try to handle it already in https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L214-L223

Which version of Slim are you using @jasonetwork?

**Comment by jasonetwork** [comment]
@akrabat, I'm using the latest version 3.8.1

**Comment by akrabat** [comment]
So why is that stack trace saying that the problem is with [line 202](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L202) of Request.php?

**Comment by jasonetwork** [comment]
Hmm. Interesting. Composer shows that the version installed is 3.8.1. Nice catch. I'll have a look into that.

**Comment by jasonetwork** [comment]
For some reason, in my composer.json file, it showed that I was running 3.8.1, when in fact it was an older version. Not sure what went wrong there. Removed and reinstalled Slim, and now working as expected. Thank you much @akrabat for pointing that out!!!!!

**Comment by akrabat** [comment]
I'm glad we solved it!
