### ISSUE TITLE
I wrote small api service using slim and i can not able to deploy into my shared hosting server 

### ISSUE THREAD

**Issue by VPageDevelopment** [slimphp/Slim#2219]
I wrote small api service using slim and I can not able to deploy into my shared hosting server 

as per slim documentation :
<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteRule ^$ public/     [L]
   RewriteRule (.*) public/$1 [L]
</IfModule>

i just replace the public into public_html .. My server give an Internal server error

**Comment by akrabat** [comment]
What does your hosting supplier advise?

**Comment by VPageDevelopment** [comment]
Thanks for your awesome reply. Sorry for the delay in response. I had no idea about that and i need to contact them for that info ... Thanks for your awesome reply. thank you so much ...

**Comment by akrabat** [comment]
Closing as reply indicates that poster doesn't want support from this channel.
