### ISSUE TITLE
Potential bug in App->respond, its somehow breaking output

### ISSUE THREAD

**Issue by Mariyo** [slimphp/Slim#2224]
Hello,
I've found one issue, but I am not sure what is actually broken, I think it has something with output from ```Slim\App::respond(ResponseInterface $response)```

I am trying to use 3rd party debugger [Tracy](https://github.com/nette/tracy). It appends small debug panel to my response `<body>`. In some cases it was not displayed, so I have opened [issue](https://github.com/nette/tracy/issues/255) for Tracy nette/tracy/issues/255

Problem is, when I try to render `<select>` with more than 128 options. Then the Tracy panel is gone. I tried to find out what is terminating the panel, and I stopped on this line https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L426, it seems that reading body from response has problem to render magic (128) number of items in selectbox. 

> Slim version is 3.8.1

I am really **confused**, so any help appreciated!

**Comment by akrabat** [comment]
Add the setting `'addContentLengthHeader' => false` to your settings.

**Comment by Mariyo** [comment]
Yes, its working now! Can you describe me shortly, what is the issue when its enabled? Just for educational purposes.

Thx

**Comment by akrabat** [comment]
By default, Slim sets the `Content-Length` header to the number of characters in the `$response`'s body. This works fine until you have a third party thing that adds additional data to the body, such as Tracy or New Relic. In these case, the `Content-Length` value is now too short and so data gets truncated as you have seen.

**Comment by Mariyo** [comment]
Ok, clear now, this I've checked in Headers of my response. 

I am just confused, why it was truncating data only in some cases, like in case with selectbox of some (bigger) size. In other cases Tracy was there even with `Content-Length` header.

**Comment by tflight** [comment]
FWIW, I use Tracy in most of my web apps, with Slim, and I don't have `'addContentLengthHeader' => false` set. While I'm not using Nette Forms, I did put your long country list into a `<select>` list and didn't have an issue.

**Comment by Mariyo** [comment]
@tflight I actually tried to replace Nette Forms Selectbox by normal `<select>`, but problem continued.
