### ISSUE TITLE
Pull requests again 2.x

### ISSUE THREAD

**Issue by nicktacular** [slimphp/Slim#2227]
Are pull requests against version 2.x going to be considered or is that version closed off to only security related updates?

**Comment by geggleto** [comment]
I really think it depends on what it is. We will not be developing any new features for 2.x... Currently we are only going to develop security related patches.

//cc @akrabat

**Comment by akrabat** [comment]
Security fixes or show-stoppers for a new PHP release are the only reasons I can think that we'd accept a 2.x patch.
