### ISSUE TITLE
Enhancement proposal: Slim\Router data to accept/parse objects

### ISSUE THREAD

**Issue by Mariyo** [slimphp/Slim#2231]
Hi,
for my CMS built on Slim I need (I've already found) enhancement, which could parse object with lazy loaded properties into Route placeholder:

```
$app = new \Slim\App();
$app->get('/user/{user-address-city}-{user-name}', function ($request, $response, $args) {
    echo "Hello, " . $args['user-name'];
});
```

URL generation using pathFor:
```
$router->pathFor(Sandbox\Actions\User::class, $user->getRouteData());
```

where `$user->getRouteData()` returns:
```
array(
    'user' => $this
)
```

My proposal is to update https://github.com/slimphp/Slim/blob/3.x/Slim/Router.php#L382-L391 by:
```
// Does $item[0] contains "-"? Maybe its object argument 
if (strpos($item[0], '-')) {
	$matches = array_filter(explode('-', $item[0]));
	$objectKey = array_shift($matches);

	// Does argument exists and is object?
	if (!empty($data[$objectKey]) and is_object($data[$objectKey])) {
		$object = $data[$objectKey];
		foreach ($matches as $match) {
			$object = $object->{$match};
		}
	}
}

if (isset($object)) {
	$segments[] = $object;
	unset($object);
} else {

	// This segment has a parameter: first element is the name
	if (!array_key_exists($item[0], $data)) {
		// we don't have a data element for this segment: cancel
		// testing this routeData item, so that we can try a less
		// specific routeData item.
		$segments = [];
		$segmentName = $item[0];
		break;
	}
	$segments[] = $data[$item[0]];
}
```

Thank you for any feedback,
Mariyo

**Comment by geggleto** [comment]
I do not think this belongs in Slim's core.

 However you may extend Slim's router and add this enhancement your self.
To use it in your Slim installation simply replace the `$container['router']` with your version.

**Comment by Mariyo** [comment]
Yes,
this way I extend `Slim\Router` with mine, where I added my enhancement. But I thought, it would be nice to have, because its not big deal to implement and it improves router a lot.

**Comment by geggleto** [comment]
I am going to close this as I think this belongs in user code.
