### ISSUE TITLE
Failed CSRF Check for Page Refresh  

### ISSUE THREAD

**Issue by it-all** [slimphp/Slim#2232]
Hi, I'm returning a direct response of an HTML form with errors instead of doing a redirect. This works fine, except that a refresh of that error page gives the dreaded 'Failed CSRF check!' error. Is redirecting necessary to avoid this? Note, I do redirect upon successful form completion to adhere to the PRG pattern.

Thanks for any help.

**Comment by it-all** [comment]
Actually the same thing happens with a redirect response. Sorry for the confusion. There is something going on that I don't understand. Perhaps I've set up the CSRF incorrectly.

**Comment by tflight** [comment]
Are you using [Slim CSRF](https://github.com/slimphp/Slim-Csrf)? When you refresh the error page is it sending a `GET` or `POST` request?

**Comment by it-all** [comment]
Yes. It is refreshing a POST.

**Comment by tflight** [comment]
I recall Slim CSRF regenerates the CSRF code on each request. See the [Token Persistence](https://github.com/slimphp/Slim-Csrf#token-persistence) section of the docs for more info. I suspect that is what you are running into.

**Comment by it-all** [comment]
Thanks! That must be it.

**Comment by it-all** [comment]
Yes, it works now.
