### ISSUE TITLE
Can't create a route when a directory with same name exists

### ISSUE THREAD

**Issue by giftnuss** [slimphp/Slim#2234]
I've tried to create a route like this:
```php
   $app->get('/view/{type:[a-z]+}/{num}', function ($request, $response, $args) {
       $this->logger->info("Route /view/pdf/ " . $args['num'] );
       ...
   });
```
When a folder 'view' in public exists the route is not found by the router. Tested only with the php dev server. If it is a desired behavior, then it would be nice to mention it in the documentation.

Thank you.

**Comment by geggleto** [comment]
This is not a bug. This is expected behaviour and default behaviour of web servers in general.

**Comment by giftnuss** [comment]
Is there a way to give the route the precedence. At least I forgot to mention, that at end the default Route matching '/' is used for me.

**Comment by geggleto** [comment]
This problem wont exist when using Apache or NGinx. The default apache .htacess that we provide says that the request should go to Slim IF and ONLY IF the path does not exist on the file system.

The above problem is a problem with the built-in web server that PHP ships with. it's documentation and the PHP core team have attached a Wont-Fix to it saying basically if you don't like it install an actual web-server.
