### ISSUE TITLE
Where put the index.php file mentioned in the README

### ISSUE THREAD

**Issue by odrik** [slimphp/Slim#2238]
Hello.

I want to use Slim in CodeIgniter so I put all the requirements files and slim in the /vendor directory, then I set the variable for autoload in application/config/config.php to TRUE.

then i don't understand how to use slim... in the readme it's mentioned an "index.php" but never said where put this file.....
please help me.

thanks a lot.

**Comment by geggleto** [comment]
as far as I know, it wouldn't be possible to use Slim inside a CodeIgniter project.

**Comment by odrik** [comment]
ok thx
