### ISSUE TITLE
develop branch: isAjax() Issue?

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#224]
I'm currently upgrading my Application to `develop` branch. The first issue I'm seeing is an Application Error regarding `$app->request()->isAjax();`. 

```
Code: 8
Message: Undefined index: X_REQUESTED_WITH
File: /Users/hexa/Code/api-v2.slim/vendor/Slim/Slim/Http/Request.php
Line: 132
```

Were there any undocumented changes? The current docs for develop branch are not mentioning any changes here. I'm running Slim-1.5.1.2-99-g4f8c26c (which should be HEAD at develop branch) on nginx with PHP 5.3.8 via. FastCGI.

**Comment by codeguy** [comment]
Hmm.... will take a look at this tomorrow.

**Comment by hexa2k9** [comment]
thanks, Josh ;)
