### ISSUE TITLE
Setting nested-array values in Container and Collection

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2240]
(FYI, this is @designermonkey on another account, sorry)

Because of the way a project I am on is using environment config loading (.env), I have had to make minor modifications to the settings for Slim.

The test below highlights the change:

```php
    /**
     * Test settings can be edited
     */
    public function testSettingsCanBeEdited()
    {
        $this->assertSame('1.1', $this->container->get('settings')['slim']['http_version']);

        $this->container->get('settings')['slim']['http_version'] = '1.2';
        $this->assertSame('1.2', $this->container->get('settings')['slim']['http_version']);
    }
```

As you can see, there is an extra level to isolate Slim settings from others within the app. Because of this change, the test fails with:

> Indirect modification of overloaded element of Slim\Collection has no effect

This is due to the weird and wonderful way that Collection accesses it's values internally.

Many moons ago (at least two years if I remember right) we had this issue before, long before the introduction of the current container and collection structure, and I'm sure we solved it back then.

Can anyone think of how we could tackle this issue?

Irrespective of my alterations which have only highlighted the issue, we have prevented any way of having alterations made to nested settings without a horrible amount of extra code for the developer in getting from the container, getting from the collection, setting into the collection and then setting into the container.

**Comment by ghost** [comment]
For reference, the changes are [here](https://github.com/johnrobertporter/Slim/tree/feature-env-settings).

There are 2 failing tests due to this change, both attempting to modify the settings.

**Comment by ghost** [comment]
Of course, to fix the test I mentioned:

```php
    /**
     * Test settings can be edited
     */
    public function testSettingsCanBeEdited()
    {
        $this->assertSame('1.1', $this->container->get('settings')['slim']['http_version']);

        $settings = $this->container->get('settings');
        
        $slim = $settings['slim'];
        $slim['http_version'] = '1.2';
        $settings['slim'] = $slim;

        $this->assertSame('1.2', $this->container->get('settings')['slim']['http_version']);
    }
```

But this goes against the simple approach requested by the test, I suppose.

**Comment by geggleto** [comment]
@johnrobertporter You can pass in ENV settings into the container before you create slim. This allows you to override the settings.

https://github.com/slimphp/Slim/blob/3.x/Slim/Container.php#L95-L97

**Comment by ghost** [comment]
@geggleto this doesn't deal with the crux of the issue though.

>Indirect modification of overloaded element of Slim\Collection has no effect

You can't modify nested values. This is something we need to fix, not make people code around.

I hope with the invent of Slim4, we find a better way of handling this.

**Comment by geggleto** [comment]
John :D It's a pimple problem. In 4.x we aren't even shipping with a container!

**Comment by geggleto** [comment]
I would be willing to entertain a new method on Slim's container that is a short-cut to replace a value though.

**Comment by ghost** [comment]
If it's been sidestepped in 4, no problem.
