### ISSUE TITLE
Extend Slim\Handlers\Error to support PHP7 errors

### ISSUE THREAD

**Issue by AviBueno** [slimphp/Slim#2241]
I have a Slim\Handlers\Error derived class that handles all uncaught exceptions.
It is currently impossible to use this class (or even just Slim\Handlers\Error) for installing a phpErrorHandler.

Seems like [Rob already made a small effort](https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/Error.php#L126) towards bridging between Exception and Error.

The question is if there's a plan to refactor the whole class in this manner (such that the concrete "\Exception" type hinting will be dropped) or if it will only be addressed in Slim 4, maybe as part of this: https://github.com/slimphp/Slim/pull/2222?

**Comment by geggleto** [comment]
It will only be addressed in Slim 4 as any serious change in 3.x would cause a BC break which we will not do :)
