### ISSUE TITLE
Credentials in baseUrl will be deprecated in chrome

### ISSUE THREAD

**Issue by X-Tender** [slimphp/Slim#2248]
I've notices a Warning in chrome today after I've opened a website which is protected by a simple htaccess Password.

```
[Deprecation] Subresource requests whose URLs contain embedded credentials (e.g. https://user:pass@host/) are deprecated, and will be blocked in M59, around June 2017. See https://www.chromestatus.com/feature/5669008342777856 for more details.
```

Then I notices that the baseUrl which i set via baseUrl() in my twig template looks like:
`http://user:pass@mydomain.net`.

So my question is, could lead to an unpredicted behaviour when Chrome starts blocking this requests? Do the slim framework have to be updated to deliver the baseurl without the credentials?

**Comment by damianopetrungaro** [comment]
I don't think is a "slim topic", is more a generic one. Anyway credential in .htaccess are really fast to create, but no so a good approach.

I recommend you to move on a JWT/OAuth2 for authorization, and a simple login implementation for authentication.

**Comment by X-Tender** [comment]
I use it for temporary locks, no production. I use JWT for normal logins like a user or admin area.

**Comment by geggleto** [comment]
I don't see that Slim can do anything about this... thank you though for giving it some visibility. The PSR-7 spec is kinda holding us hostage on this point.
