### ISSUE TITLE
can't  run in centons7+nginx1.10+php7.0

### ISSUE THREAD

**Issue by ywqyuan** [slimphp/Slim#2249]
when i run slim application in centos7 
I got some error like this :

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/lingdian/vendor/slim/slim/Slim/Container.php on line 149

how to fix it? please help me.

**Comment by tflight** [comment]
Times I've seen other people encounter that exact error they were running 5.5.x versions of PHP. (Sometimes they thought they were running a newer version, but `phpinfo()` convinced them otherwise.)

**Comment by ywqyuan** [comment]
ok  tks  !!! change the php version. it's work!
