### ISSUE TITLE
How can I request for URI parameters when using a controller function in route

### ISSUE THREAD

**Issue by ayushav12** [slimphp/Slim#2251]
My Route is:

$app->get('/api/courts/{id}/{date}','\App\Controllers\AvailabilityController:getCourtAvailability'){
	$id=$request->getAttribute('id');
	$date=$request->getAttribute('date');
    return json_encode();
};

I know that my way is incorrect. Please tell me the correct method as I cannot find any solution

**Comment by tflight** [comment]
See [Route Placeholders](https://www.slimframework.com/docs/objects/router.html#route-placeholders) and [Container Resolution](https://www.slimframework.com/docs/objects/router.html#container-resolution) in the docs.

The route:
```php
$app->get('/api/courts/{id}/{date}', '\App\Controllers\AvailabilityController:getCourtAvailability');
```

Then in your controller:

```php
public function getCourtAvailability($request, $response, $args) {
    $id = $args['id'];
    $date = $args['date'];
    return $response; // your real response
}
```

**Comment by johnhunt** [comment]
thanks for helping @tflight !! 👍  💯  🥇
