### ISSUE TITLE
Slim error

### ISSUE THREAD

**Issue by ayushav12** [slimphp/Slim#2252]
Controller:

namespace App\Controllers;

use Illuminate\support\Facades\DB;
use Slim\Http\{Request, Response};

class AvailabilityController extends Controller
{
public function getCourtAvailability($request, $response, $args)
{
$selected_court=$args('id');
$selected_date=$args('date');

$booked_sessions=DB::table('sessions')->where('booking_type','=','INDIVIDUAL')->orWhere('booking_type','=','GROUP');
$softbooked_sessions=DB::table('sessions')->where('booking_type','=','SOFT');
$arr=array('booked_sessions'=>$booked_sessions, 'softbooked_sessions'=>$softbooked_sessions);
$response->status(200);
return $response->json_encode($arr);
}
public function getAllCourtAvailability($request, $response, $args)
{
$selected_date=$args('date');

$booked_sessions=DB::table('sessions')->where('booking_type','=','INDIVIDUAL')->orWhere('booking_type','=','GROUP');
$softbooked_sessions=DB::table('sessions')->where('booking_type','=','SOFT');
$arra=array('booked_sessions'=>$booked_sessions, 'softbooked_sessions'=>$softbooked_sessions);
$response->status(200);
return $response->json_encode($arra);
}
}

Routes:

$app->get('/api/courts/{id}/{date}',[''\App\Controllers\AvailabilityController','getCourtAvailability']) ;
$app->get('/api/courts/{date}',['\App\Controllers\AvailabilityController','getAllCourtsAvailability']);

When I run the URL in the browser, I get the error: 
"The page you were looking for was not found"

Where am I going wrong? Any help would be great.

**Comment by pachico** [comment]
Hi,
Could you specify what URL are you calling?
(as a side note, please consider markdown code when embedding snippets for better readability.)

**Comment by ayushav12** [comment]
Virtual host : bady.dev

URL : bady.dev/api/courts/1/2017-06-25

**Comment by gpredl** [comment]
second argument passed to 'get' must be a callable, not array. 
right syntax:
$app->get('/api/courts/{id}/{date}', '\App\Controllers\AvailabilityController:getCourtAvailability'); 
or
$app->get('/api/courts/{id}/{date}', \App\Controllers\AvailabilityController::class . ':getCourtAvailability'); 

and you have a double-quote in your code:
$app->get('/api/courts/{id}/{date}',['' <<<<

**Comment by akrabat** [comment]
> second argument passed to 'get' must be a callable, not array.

An array is a callable if the first element is a class name and the second element is a static method of that class. See `// Type 2`` in the "Example #1" code samples on  http://php.net/manual/en/language.types.callable.php

**Comment by ayushav12** [comment]
@akrabat excluding the typo of "(double quotes), what am I doing wrong?

**Comment by akrabat** [comment]
I haven't a clue. Does a simple get to `/` work?

**Comment by ayushav12** [comment]
@akrabat It shows me the same error.

**Comment by akrabat** [comment]
Does:

```php
<?php
require 'vendor/autoload.php';

$app = new \Slim\App;
$app->get('/', function (Request $request, Response $response) {
    $response->getBody()->write("Hello World");

    return $response;
});
$app->run();
```
Work?

**Comment by ayushav12** [comment]
Yes, that works fine

**Comment by jakelehner** [comment]
Is the error you're getting a slim error, or generic not found from the web server?

Perhaps your web server config isn't sending all routes through you slim app. Try the previous "hello world" example with /api as the URL.

**Comment by ayushav12** [comment]
I resolved the error. It was with my virtual host.
While working on php development server, end-points were working fine.
