### ISSUE TITLE
Slim, MySQL foreign keys errors 

### ISSUE THREAD

**Issue by ayushav12** [slimphp/Slim#2253]
Controller :

`public function postBookSession(Request $request, Response $response, Validator $validator)
	{     
		$data=$request->getParsedBody();

       if($session= Session::create([
                'id' => $session_id,
                'court_id' => $data['court_id'],
                'booking_date' => $data['booking_date'],
                'start_time'=> $data['start_time'],
                'end_time'=> $data['end_time'],
                'booking_type'=> $data['booking_type'],
                'group_id'=> $data['group_id'],
                'book_status'=> $book_status,
                'blocked_by_admin' => $blocked_by_admin,
                'slot_scheme_id'=>$data['slot_scheme_id'],
                'booked_by'=> $data['user_id'] 

        	])) {

       	    return $response->withStatus(201);
       }
       else {
       	   return $response->withStatus(400);
       }
	}
}`

Session Model : 

`class Session extends Model {
    protected $fillable = ['court_id','booking_date','start_time','end_time','booking_type','group_id','slot_scheme_id','user_id'];
    protected $table = "sessions";
    public $timestamps = true;
    //const CREATED_AT = 'creation_date';
    //const UPDATED_AT = 'last_update';

    public function court() {
      return $this->belongsTo('App\Models\Court','court_id','id');
    }
    public function group() {
      return $this->belongsTo('App\Models\Group','group_id','id');
    }
    public function slotScheme() {
      return $this->belongsTo('App\Models\SlotScheme','slot_scheme_id','id');
    }
    public function user() {
      return $this->belongsTo('App\Models\User','booked_by','id');
    }
    public function booked_by() {
      return $this->belongsTo('App\Models\User', 'booked_by');
    }
    public function matchHistories() {
      return $this->hasMany('App\Models\MatchHistory','session_id','id');
    }
    public function userSession() {
      return $this->hasMany('App\Models\UserSession','session_id','id');
    }
    public function bookingRequests() {
      return $this->hasMany('App\Models\BookingRequest','session_id','id');
    }
  }
`
While testing with Postman, I get the error : 

![postman1](https://user-images.githubusercontent.com/24531683/27469158-a629dbda-580b-11e7-8091-1437c9d1547e.png)

![postman2](https://user-images.githubusercontent.com/24531683/27469165-b0957746-580b-11e7-95cd-fb2b0b5ca969.png)

**Comment by danopz** [comment]
This is not related to Slim.

**Comment by ayushav12** [comment]
@copynpaste Sorry for posting a wrong issue.
Anyhow, you know the solution??

**Comment by danopz** [comment]
You try to save booked_by=14. The Exception says that you don't have User#14 - so you cannot set this into the foreign key.

**Comment by ayushav12** [comment]
But i have User#14 created in my database.
Anyway, thanks man.

**Comment by danopz** [comment]
booked_by is missing in the query, maybe because of the type? You post a string, but it should be an int, i think.
