### ISSUE TITLE
Not return the complete response

### ISSUE THREAD

**Issue by jeremiecourlivant** [slimphp/Slim#2255]
Hello,

I try Slim. In a localhost Wamp server, it's work fine but when I put on the web server, there is a problem.

The test code : 

require __DIR__ . '/vendor/autoload.php';

$app = new Slim\App;

$app->get('/', function ($request, $response) {
    return "hello world";
});

$app->run();

When I return a string of less than 40 characters, the last 13 characters of the string disappear. So when I return "Hello World !", in my navigator I have only "He". When the string does more than 39 characters, there is no problem.

In localhost or in the server, the test is in subdirectory. The web server is a shared server, in OVH.

Thanks for your attention.

**Comment by geggleto** [comment]
Your test code is wrong.

Please review the documentation.

https://www.slimframework.com/

A minimal example from the website.
```php
<?php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;

require 'vendor/autoload.php';

$app = new \Slim\App;
$app->get('/hello/{name}', function (Request $request, Response $response) {
    $name = $request->getAttribute('name');
    $response->getBody()->write("Hello, $name");

    return $response;
});
$app->run();
```

**Comment by jeremiecourlivant** [comment]
It's the same thing with the example of the documentation.

**Comment by geggleto** [comment]
In your code example provided you are returning a string from the anonymous function. You need to return a response object.

**Comment by jeremiecourlivant** [comment]
Ok.

But with your exemple, the same thing appends.

**Comment by geggleto** [comment]
What version of PHP?

**Comment by jeremiecourlivant** [comment]
7.0 for the web server

**Comment by geggleto** [comment]
Are you overriding any of the defaults in the Slim App?

there are multiple test cases that show that Slim is returning the correct response body.

https://github.com/slimphp/Slim/blob/3.x/tests/AppTest.php#L777-L858

Something is chopping up your response. The likely candidates are:
- some whitespace character in your code
- A middleware
- In some rare occurrences New Relic / Content Length header is not set correctly.

**Comment by jeremiecourlivant** [comment]
I have research about Content Length header and I find [this topic](https://github.com/slimphp/Slim/issues/1690) . At the end, I find the solution : put addContentLengthHeader in false in the settings. Now it works.

Thank you for your help.
