### ISSUE TITLE
How to get an absolute URI

### ISSUE THREAD

**Issue by aimeos** [slimphp/Slim#2258]
How can I create an absolute URL including the scheme, host and port?
The pathFor() method of the Slim router only creates URLs with a leading slash.

**Comment by llvdl** [comment]
Are you using the PHP built-in webserver? It seems `$_SERVER['SCRIPT_NAME']` is used to [determine the base path](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Uri.php#L200). When running the PHP buit-in web server. this path is relative.

**Comment by aimeos** [comment]
No, this is an Apache and PHP FPM setup. Apache talks to the FPM process using a TCP connection

**Comment by llvdl** [comment]
What do you see when you output `$_SERVER`? Particularly in the `SCRIPT_NAME` and `REQUEST_URI` parts?

**Comment by aimeos** [comment]
This is printed by the PHP FPM process:
```
[USER] => www-data
  | [HOME] => /var/www
  | [SCRIPT_NAME] => /test.php
  | [REQUEST_URI] => /test.php
  | [QUERY_STRING] =>
  | [REQUEST_METHOD] => GET
  | [SERVER_PROTOCOL] => HTTP/1.1
  | [GATEWAY_INTERFACE] => CGI/1.1
  | [REMOTE_PORT] => 38876
  | [SCRIPT_FILENAME] => /...../slim.demo.aimeos.org/public/test.php
  | [SERVER_ADMIN] => aimeos@aimeos.org
  | [CONTEXT_DOCUMENT_ROOT] => /...../slim.demo.aimeos.org/public
  | [CONTEXT_PREFIX] =>
  | [REQUEST_SCHEME] => http
  | [DOCUMENT_ROOT] => /....../slim.demo.aimeos.org/public
  | [REMOTE_ADDR] => ...
  | [SERVER_PORT] => 80
  | [SERVER_ADDR] => 85.25.49.53
  | [SERVER_NAME] => slim.demo.aimeos.org
  | [SERVER_SOFTWARE] => Apache/2.4.18 (Ubuntu)
  | [SERVER_SIGNATURE] => <address>Apache/2.4.18 (Ubuntu) Server at slim.demo.aimeos.org Port 80</address>
  |  
  | [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  | [HTTP_COOKIE] => PHPSESSID=...
  | [HTTP_ACCEPT_LANGUAGE] => de,en-US;q=0.8,en;q=0.6
  | [HTTP_ACCEPT_ENCODING] => gzip, deflate
  | [HTTP_DNT] => 1
  | [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
  | [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
  | [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
  | [HTTP_CONNECTION] => keep-alive
  | [HTTP_HOST] => slim.demo.aimeos.org
  | [proxy-nokeepalive] => 1
  | [SCRIPT_URI] => http://slim.demo.aimeos.org/test.php
  | [SCRIPT_URL] => /test.php
  | [FCGI_ROLE] => RESPONDER
  | [PHP_SELF] => /test.php
```
This is the result when printed by mod_php in Apache:
```
[HTTP_HOST] => servername.tld
  | [HTTP_CONNECTION] => keep-alive
  | [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
  | [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
  | [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
  | [HTTP_DNT] => 1
  | [HTTP_ACCEPT_ENCODING] => gzip, deflate
  | [HTTP_ACCEPT_LANGUAGE] => de,en-US;q=0.8,en;q=0.6
  | [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  | [SERVER_SIGNATURE] => <address>Apache/2.4.18 (Ubuntu) Server at servername.tld Port 80</address>
  |  
  | [SERVER_SOFTWARE] => Apache/2.4.18 (Ubuntu)
  | [SERVER_NAME] => servername.tld
  | [SERVER_ADDR] => 85.25.49.53
  | [SERVER_PORT] => 80
  | [DOCUMENT_ROOT] => /var/www/html
  | [REQUEST_SCHEME] => http
  | [CONTEXT_PREFIX] =>
  | [CONTEXT_DOCUMENT_ROOT] => /var/www/html
  | [SERVER_ADMIN] => aimeos@aimeos.org
  | [SCRIPT_FILENAME] => /var/www/html/test.php
  | [REMOTE_ADDR] => ...
  | [REMOTE_PORT] => 38880
  | [GATEWAY_INTERFACE] => CGI/1.1
  | [SERVER_PROTOCOL] => HTTP/1.1
  | [REQUEST_METHOD] => GET
  | [QUERY_STRING] =>
  | [REQUEST_URI] => /test.php
  | [SCRIPT_NAME] => /test.php
  | [PHP_SELF] => /test.php
```
There doesn't seem to be much difference besides inside PHP FPM, more information is available.

**Comment by 1ma** [comment]
`(string) $request->getUri()`

It won't include the port if it runs on the standard 80 or 443 ports, though. If it is that important maybe you can build something up with `UriInterface::getScheme()`, `UriInterface::getHost()`, `UriInterface::getPort()`, `UriInterface::getPath()` and `UriInterface::getQuery()`

**Comment by aimeos** [comment]
`$request->getUri()` only returns the current URL. What we need is to generate an absolute URL for the next page and `pathFor()` doesn't seem to do that. So what's the way to do this in Slim?

**Comment by geggleto** [comment]
@aimeos no since PHP doesn't care about the base url, this is something that you will have to do in your user code.

**Comment by aimeos** [comment]
@geggleto Seems like a missing feature as all other frameworks (Laravel, Symfony resp. Lumen, Silex, etc.) can generate absolute URIs on request without bothering the application code with the details.

To me, the simplest solution is to change `getBasePath()` to `getBaseUrl()` here:
https://github.com/slimphp/Slim/blob/7aabd47614448326ecb3908eec2a6440f36b50b9/Slim/App.php#L359
https://github.com/slimphp/Slim/blob/7aabd47614448326ecb3908eec2a6440f36b50b9/Slim/App.php#L323

**Comment by geggleto** [comment]
@aimeos it possibly could be... I have never actually wanted to use an absolute URL in a production app as I just use `href="/...route/"`.

We could add something like this for 4.x. If you feel the need for it open a pr on the 4.x branch as I am sure it will be gladly accepted. :)

**Comment by sundayz** [comment]
@geggleto It's useful for generating Open Graph's `og:url` and `og:image` tags. They can't be relative URLs, so you will have to manually generate them by appending root url + path to image.

I know it's not hard to do yourself but others might find this issue on Google. People using twig or other templating engines can also just define a function or macro that build the absolute path using the solutions above.
