### ISSUE TITLE
PSR-15 compliant Strategy for the foundHandler

### ISSUE THREAD

**Issue by damianopetrungaro** [slimphp/Slim#2259]
Hello folks!
I am currently writing a micro framework inspired to Slim and Expressive.

And i have found in Expressive a really cool approach for resolve the request.
So imho could be cool give to Slim in version 4 a PSR-15 middleware route resolution, instantiating a Delegate and use the container for build at run time the middleware to execute.

I may write a simple PSR-15 implementation in Slim using only delegates and middleware.

**Comment by geggleto** [comment]
I believe the idea was that in Slim 4 we would be switching resolution to be a middleware; so that Slim simply executes a chain of middleware [last being your route]... But I think @akrabat might know more about that.

**Comment by damianopetrungaro** [comment]
Fixed by #2379 , still waiting @akrabat ahahaha
