### ISSUE TITLE
Pass exceptions in middleware up the stack

### ISSUE THREAD

**Issue by dannykopping** [slimphp/Slim#226]
Hey Josh

I have a similar problem to one I've reported before.
The `PrettyExceptions` middleware class will intercept exceptions occasionally (but in a repeatable way) and render out a pretty page which gives me all the error details.

I think this should not happen if a custom `error()` callable has been defined.
I'm experimenting with ways of sending the exception back up the stack, but the problem is that the middleware instances are only aware of the middleware OR Slim application instance that invoked them; if we don't have an objective reference to the invoking application then it becomes hairy.

I hope this is all making sense.
Thanks

**Comment by codeguy** [comment]
I can add the PrettyExceptions middleware at the beginning of `Slim::run()` guaranteeing that it will always be the outermost middleware layer so that any uncaught exceptions are passed through the entire stack.

**Comment by dannykopping** [comment]
Excellent - I'll test it out tomorrow

**Comment by codeguy** [comment]
I've made this change to the `release-1.6.0` and `develop` branches. Pull down and test out when you get a chance. Thanks!

**Comment by dannykopping** [comment]
Looks good to me! Thanks mate
