### ISSUE TITLE
Call methods without passing arguments

### ISSUE THREAD

**Issue by alexxasmith** [slimphp/Slim#2260]
I am using slim bridge for DI.

Say, from AController i want to call the function 'second' in BController.

    namespace App\Controllers;

    use Psr\Http\Message\RequestInterface as Request;
    use Psr\Http\Message\ResponseInterface as Response;
    use Noodlehaus\Config as Config;

    class BController extends Controllers {

    public function second(Request $request, Response $response, Config $config, $optional = []){
        // do stuff
    }

How could i call the second function passing only the parameter i want to send ($optional in this case) and not all other dependencies like request or response.

    class AController extends Controllers{
        public function second(Request $request, Response $response, BController $bController){
            $bController->second(['custom parameter']);

            // or

            $this->container->get('App/Controllers/BCOntroller')->second();

            // i do not want this
            
            $bController->second($request, $response, $cache, etc etc);
        }
    }
 

I tried to follow the route logic.'first' function gets executed without sending parameter

    $app->get('/', ['\App\Controllers\AController', 'first']);

**Comment by geggleto** [comment]
This really isn't a slim question... but

In short: You cannot / you need to use proper injection / principles... 

Alternatively you can write some kinda adapter for your class that uses PHP Magic methods to grab all of the required parameters to execute the function.

I hope this answers your question.
