### ISSUE TITLE
How to use redis or memcached with slim3 

### ISSUE THREAD

**Issue by ayushav12** [slimphp/Slim#2268]
I browsed the internet and didn't find much content on how to use any caching library with slim 3 framework. 
Can anyone help me out on this issue?

**Comment by akrabat** [comment]
Slim doesn't get in your way for any caching libraries you want to use. Just use the library as per their docs.

**Comment by ayushav12** [comment]
Thank you for your help again @akrabat !!
Do I need to define the service provider in Container??

**Comment by akrabat** [comment]
I generally find it easier to put my dependencies in the the Container as it separates out the creation of an object from where it is used.

**Comment by ayushav12** [comment]
But
