### ISSUE TITLE
getBaseUri is silly

### ISSUE THREAD

**Issue by Radagaisus** [slimphp/Slim#227]
Hi,

Here's the default 404 template:

``` php
echo self::generateTemplateMarkup('404 Page Not Found', '<p>The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.</p><a href="' . $this->request->getRootUri() . '">Visit the Home Page</a>');
```

getRootUri uses getBaseUri which returns "" if the application sits on the root of the web server:

``` php
    /**
     * @var string  The root URI of the Slim application without trailing slash.
     *              This will be "" if the app is installed at the web
     *              document root.  If the app is installed in a
     *              sub-directory "/foo", this will be "/foo".
     */
    protected $root;
```

Too bad this means the link in the 404 won't work (it should be <a href="/" in this case), and every other construct that will use it won't work either.

Cheers,

**Comment by codeguy** [comment]
I've updated the default 404 page so that it will always have a trailing slash. I'll revisit the debate of having or not having a trailing slash later on.
