### ISSUE TITLE
Error on get install by composer

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2274]
Hi Guys !
Following the installation guide, I was unable to install Slim via Composer.

I used the following command:
Composer require slim / slim "^ 3.0"

And the following error occurred:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package slim / slim No set (parsed as 1.0.0) is satisf
Iable by slim / slim [No version set (parsed as 1.0.0)] but these conflict with you
R requirements or minimum-stability.

Best Regards,

Charles

**Comment by karsasmus** [comment]
Did you write `slim / slim`? 
To install slim via composer you have to write `slim/slim` 😉

**Comment by ghost** [comment]
I typed:  composer require slim/slim

But the error is: 


  Problem 1
    - The requested package slim/slim No version set (parsed as 1.0.0) is satisf
iable by slim/slim[No version set (parsed as 1.0.0)] but these conflict with you
r requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by geggleto** [comment]
remove what you have in composer.json for slim and retry

**Comment by ghost** [comment]
No worked. I think is my PHP.ini is not configured properly. What i need enable to use slim?

**Comment by akrabat** [comment]
What does `php -v` output?

**Comment by ghost** [comment]
The output is:
PHP 5.6.31 (cli) (built: Jul  5 2017 22:25:43)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by tuupola** [comment]
I would try the following:

```
$ composer self-update
$ composer clear-cache
$ mkdir test
$ cd test
$ composer require slim/slim
```

**Comment by geggleto** [comment]
I am going to close this as I know composer install of slim works given that I use it daily for production updates. Please reopen if you are still having issues.

**Comment by fgesora** [comment]
Still came across same issue. managed to sort by re-configuring my .phar file, but important to trace the exception trace - use the vvv flag. Check your permission structure
