### ISSUE TITLE
No way to get current route without Request object from App

### ISSUE THREAD

**Issue by Ikke** [slimphp/Slim#2277]
Slim version 3.x.

The app creates new request objects when executing `$request->withAttribute()`. This means the attributes being set are not available for other objects that get the request object injected from the DI container.

Scenario: I'm trying to create a twig extension that needs the current route name. It gets the request object injected, but this reject object has no attributes because the object is treated immutable.

The matched route is also not stored somewhere else, but only used in transition (in the `dispatchRouterAndPrepareRoute()` method), so the only way to currently find the current route is to match it again.

Any ideas on how to get access to the current route object?

**Comment by akrabat** [comment]
This is how PSR-7 works.

Use the request object in the action - the route is in an attribute.

**Comment by Ikke** [comment]
Yes, I've already used that attribute in middleware, and that's working alright. But now I'm trying to get the current route in a Twig extension (somewhat like `is_current_path` in Twig-View), but that's already setup before `$app->run()` is executed.

**Comment by geggleto** [comment]
... ah yes. chicken and the egg problem.

@akrabat Twig-View has a dependency on the Request object... I think this issue should be opened on Twig-View

**Comment by Ikke** [comment]
@geggleto I just used Twig-View as an example. That extension itself does not need the current route, as it is just looking at the paths, so it can just do with the router and request object.

But I'm trying to match on the route name instead of its path. That way you don't need to provide the path params. But getting the current route proves to be difficult.

**Comment by geggleto** [comment]
@Ikke for the reasons Akrabat stated it's not possible to do what you want with Slim 3. PSR-7 clearly states objects must be cloned which causes issues with referencing them.... Slim requires them to be in the container... for BC/Other reasons. Slim 4 will not have this problem.

**Comment by Ikke** [comment]
@geggleto Alright, thanks. Then I'll use my work-around for now.

**Comment by akrabat** [comment]
The way to do it is to set the setting that determines the route early to true. Then have a piece of middleware that sets the matched route into a property in your extension, which it retreives via the DIC (though I suppose it could be a static propety).
