### ISSUE TITLE
Need to add specific unit test for withJSON()

### ISSUE THREAD

**Issue by RyanNerd** [slimphp/Slim#2279]
From the comment by @geggleto in  #2278

**Comment by RyanNerd** [comment]
Does [this test](https://github.com/slimphp/Slim/blob/3.x/tests/Http/ResponseTest.php#L286) offer coverage?

**Comment by geggleto** [comment]
yep :)

**Comment by RyanNerd** [comment]
The related issue turned out to be a red herring and there **are** unit tests for testing `withJSON()`
Closing.
