### ISSUE TITLE
tests/Mocks/SmallChunksStream write() function returns the wrong type

### ISSUE THREAD

**Issue by RyanNerd** [slimphp/Slim#2281]
https://github.com/slimphp/Slim/blob/3.x/tests/Mocks/SmallChunksStream.php#L104

This function is echoing back the string argument as a string when it should probably be returning an int of `strlen($string);`

See: https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php#L112

**Comment by geggleto** [comment]
I'm teetering to tag wontfix for v3 .... but will fix in v4... @akrabat  ?

**Comment by akrabat** [comment]
Should be fixed as it's a Mock.

Fortunately, [Stream::write()](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Stream.php#L413) gets it right.
