### ISSUE TITLE
Remove setting default_mimetype in Slim 4

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#2284]
I think we should not set the `default_mimetype` in `finalize` in Slim 4 and document that it should be cleared.

Alternatively, we should only set it to black if it's an empty response.

See #2225.

**Comment by akrabat** [comment]
We could also set it in the Skeleton, so that it's easy to remove?

**Comment by odan** [comment]
Maybe add a (optional) middleware for that?

**Comment by akrabat** [comment]
Replaced with #2396

**Comment by Fritofour** [comment]
Hi, 
Is there a release planified for this issues?
Thanks a lot!
