### ISSUE TITLE
ErrorException 8 - Where to start troubleshooting?

### ISSUE THREAD

**Issue by MauriceW2** [slimphp/Slim#2293]
Hi, I've installed an application that throws the following error:

Slim Application Error
The application could not run because of the following error:
Details
Type: ErrorException
Code: 8
Message: Use of undefined constant onAddSubscriber - assumed 'onAddSubscriber'
File: /var/www/clients/client2/web16/web/API/functions_subscriber.php

What's the meaning of "Use of undefined constant onAddSubscriber - assumed 'onAddSubscriber'"?

Please advice.

**Comment by tuupola** [comment]
`onAddSubscriber` is not part of Slim. I would look at the file  `/var/www/clients/client2/web16/web/API/functions_subscriber.php` suggested by the error message.

**Comment by akrabat** [comment]
`Use of undefined constant` is a PHP error: See here: https://encrypted.google.com/search?hl=en&q=Use%20of%20undefined%20constant

**Comment by MauriceW2** [comment]
Thanks, guys! With your help I found the source of the problem.

I changed this code:
`if (function_exists(onAddSubscriber)) {
	onAddSubscriber($email_list_id);
}`

into

`if (function_exists('onAddSubscriber')) {
	onAddSubscriber($email_list_id);
}`

Needed to wrap the function name in single quotes.
Problem solved!
