### ISSUE TITLE
isXHR() not working

### ISSUE THREAD

**Issue by olignyf** [slimphp/Slim#2295]
Hi,

Please tell me if it is my usage that is wrong but I think there is something not working as I expected with isXhr(). It always returns false, even on Ajax requests.

In this middleware, I print a header and footer, but only when not XHR. Unfortunately the header is still printed for XHR requests. Any idea what I am doing wrong or if it is a slimphp bug?

Thanks,
Francois

```
use Psr\Http\Message\RequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;

$app->add(function (Request $request, Response $response, callable $next) 
{
    $renderer = $this->get('renderer'); 
    error_log(print_r($request,true));
    
    // header
    if (!$request->isXhr()) 
    {  $response = $renderer->render($response, 'header.phtml');
    }
    
    // actual request
    $response = $next($request, $response);
    
    // footer
    if (!$request->isXhr()) 
    {  $response = $renderer->render($response, 'footer.phtml');
    }
    
    return $response;
});
```

**Comment by tflight** [comment]
Does your ajax request have this header? `X-Requested-With: XMLHttpRequest`

**Comment by piotr-cz** [comment]
It's a convention that javascript libraries (jQuery, MooTools) used to set such header to every request

**Comment by geggleto** [comment]
Yes. I do believe so.

**Comment by olignyf** [comment]
Yes I was using just a native XMLHttpRequest object. I will add that
special header and retest. I thought the browser was responsible to add it.
Many thanks.

**Comment by olignyf** [comment]
Thanks, adding X-Requested-With as I did below in my code made it work !

```
var xhr = new XMLHttpRequest();
xhr.open(type, encodeURI(url));
xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
...
```
