### ISSUE TITLE
$validProtocolVersions should include "2" (without minor version)

### ISSUE THREAD

**Issue by daberlin** [slimphp/Slim#2296]
See: https://http2.github.io/faq/#is-it-http20-or-http2

https://github.com/slimphp/Slim/blob/a641082cdc08769c6fe195180ed73a63ca828b73/Slim/Http/Message.php#L39

**Comment by geggleto** [comment]
@akrabat thoughts?

**Comment by akrabat** [comment]
Seems valid to me.
