### ISSUE TITLE
$response = $app($request, $response); Slim 3

### ISSUE THREAD

**Issue by WillSkates** [slimphp/Slim#2297]
Hi there,

TLDR;

If you want to run tests through your Slim application without spinning up a web server....

use this:
```php
$response = $app->callMiddlewareStack($request, $response);
```

Instead of this:
```php
$response = $app($request, $response);
```

I don't think this is a bug but I'm using Slim 3 and middleware that are added to $app don't get run for me unless I call the whole stack.

Apologies if this is documented somewhere else, this isn't the best place to put this or i'm just plain wrong.

**Comment by geggleto** [comment]
It's not reallllly documented anywhere... but yes. I guess for those who do not want to use a web server they use the builtin one.

**Comment by akrabat** [comment]
Depends what you're testing. If I'm unit testing an action, I don't want to test the middleware at the same time. If I'm doing integration/acceptance tests, then I would probably use `$app->process()`.

However, if `callMiddlewareStack` works for you, then that's the right approach.

**Comment by akrabat** [comment]
Feel free to submit a cookbook article on your testing approach to the [Slim-Website](https://github.com/slimphp/Slim-Website) repository.

**Comment by WillSkates** [comment]
@akrabat That's interesting. I might do that.

@geggleto do you mean the inbuilt development server "php -S"?

**Comment by geggleto** [comment]
@WillSkates yep :)

**Comment by WillSkates** [comment]
@geggleto The inbuilt dev server is unfortunately still a '[web server](http://php.net/manual/en/features.commandline.webserver.php#features.commandline.webserver)'. Running requests through the app kernel has been faster and more stable for me.

If I need to use a headless browser or selenium I'll spawn a server. It's good enough to start with.
