### ISSUE TITLE
hello, $request->getQueryParams() value is null

### ISSUE THREAD

**Issue by springleng** [slimphp/Slim#2299]
app env
slim v3.8.1
php 7.1.8 nts

GET /payment/tianfubao/notify?cipher_data=S%2FTqbQYcG36j0%2FeEX2%2FdVdTVkwuViUpf12%2BpDexOBfguz%2BgSJyVSmT0JPmuXeOt4bMCnQYGl7VJQbaTaC3vhjhlAaKEfcfSxZP2oFMITX91VdDwW8pwOTNd0wkF51UD%2FJHJNBbOXcM2KgTaPJvnaytPoZ%2B%2F3Ctk%2B04ZJydoQWeMxHIguVzZJJundilntL6%2FrHhKTkQFP3j6t2KPoj60HEbxjg41UKc1fbktwW06l0yyVAfHxPDkygO%2B47%2Fyt2ySYallFKO5%2BBpCpLZfM%2BNTSs%2F9kkGfArA0oiYvXxnTSe1GSio2jpGxUgJJtDdq6DAcZxhq3ocpGBrzZp9xEO9s7fXNyihIyw7saRbepYu9hDl1%2FjAS%2BuaaYawWKnRmCLnup0ziPxH0ndz%2FjL8CZhL4YYeaA3C32O4DUh%2FoYmV6YUuVAxkfJVDA7aVbx7D%2Fod27SJ3EHDmTi6o3wAvpCW2XpgxG5zV1%2BpHtZYqYSQT2T0tHFgt98zQTgdALyjeAaDOyW&retcode=00&retmsg=%B2%D9%D7%F7%B3%C9%B9%A6

$request->getQueryParams()  // NULL

retmsg=%B2%D9%D7%F7%B3%C9%B9%A6 // urlencode gbk encoding

Resolvent:
$getDatas = $request->getUri()->getQuery();
parse_str(iconv('gbk', 'utf-8', urldecode($getDatas)), $returnData);

**Comment by geggleto** [comment]
Your URL is not valid according to PHP.

`var_dump(parse_str('http://example.com/payment/tianfubao/notify?cipher_data=S%2FTqbQYcG36j0%2FeEX2%2FdVdTVkwuViUpf12%2BpDexOBfguz%2BgSJyVSmT0JPmuXeOt4bMCnQYGl7VJQbaTaC3vhjhlAaKEfcfSxZP2oFMITX91VdDwW8pwOTNd0wkF51UD%2FJHJNBbOXcM2KgTaPJvnaytPoZ%2B%2F3Ctk%2B04ZJydoQWeMxHIguVzZJJundilntL6%2FrHhKTkQFP3j6t2KPoj60HEbxjg41UKc1fbktwW06l0yyVAfHxPDkygO%2B47%2Fyt2ySYallFKO5%2BBpCpLZfM%2BNTSs%2F9kkGfArA0oiYvXxnTSe1GSio2jpGxUgJJtDdq6DAcZxhq3ocpGBrzZp9xEO9s7fXNyihIyw7saRbepYu9hDl1%2FjAS%2BuaaYawWKnRmCLnup0ziPxH0ndz%2FjL8CZhL4YYeaA3C32O4DUh%2FoYmV6YUuVAxkfJVDA7aVbx7D%2Fod27SJ3EHDmTi6o3wAvpCW2XpgxG5zV1%2BpHtZYqYSQT2T0tHFgt98zQTgdALyjeAaDOyW&retcode=00&retmsg=%B2%D9%D7%F7%B3%C9%B9%A6'));`

Returns
`NULL`

**Comment by wedumatt** [comment]
@geggleto  `parse_str` always returns null

the "return value" has to be provided as a 2nd argument that's filled by reference... because PHP 🙄

**Comment by kafene** [comment]
@geggleto  `parse_str` always returns null

the "return value" has to be provided as a 2nd argument that's filled by reference... because PHP 🙄

**Comment by geggleto** [comment]
haha. whoops :)

**Comment by mariusklocke** [comment]
I tried to reproduce this issue. But it seems to work for me. I wrote this little CLI script which should cover the use-case @springleng mentioned.

```php
<?php

require_once 'vendor/autoload.php';

$uriString = "/payment/tianfubao/notify?cipher_data=S%2FTqbQYcG36j0%2FeEX2%2FdVdTVkwuViUpf12%2BpDexOBfguz%2BgSJyVSmT0JPmuXeOt4bMCnQYGl7VJQbaTaC3vhjhlAaKEfcfSxZP2oFMITX91VdDwW8pwOTNd0wkF51UD%2FJHJNBbOXcM2KgTaPJvnaytPoZ%2B%2F3Ctk%2B04ZJydoQWeMxHIguVzZJJundilntL6%2FrHhKTkQFP3j6t2KPoj60HEbxjg41UKc1fbktwW06l0yyVAfHxPDkygO%2B47%2Fyt2ySYallFKO5%2BBpCpLZfM%2BNTSs%2F9kkGfArA0oiYvXxnTSe1GSio2jpGxUgJJtDdq6DAcZxhq3ocpGBrzZp9xEO9s7fXNyihIyw7saRbepYu9hDl1%2FjAS%2BuaaYawWKnRmCLnup0ziPxH0ndz%2FjL8CZhL4YYeaA3C32O4DUh%2FoYmV6YUuVAxkfJVDA7aVbx7D%2Fod27SJ3EHDmTi6o3wAvpCW2XpgxG5zV1%2BpHtZYqYSQT2T0tHFgt98zQTgdALyjeAaDOyW&retcode=00&retmsg=%B2%D9%D7%F7%B3%C9%B9%A6";
$uri = \Slim\Http\Uri::createFromString($uriString);

$request = new \Slim\Http\Request('GET', $uri, new \Slim\Http\Headers([]), [], [], new \Slim\Http\Body(fopen('php://input', 'r')));
var_dump($request->getQueryParams());
```

That produces the following output on PHP 7.1.3 with Slim 3.9.2

```php
array(3) {
  ["cipher_data"]=>
  string(512) "S/TqbQYcG36j0/eEX2/dVdTVkwuViUpf12+pDexOBfguz+gSJy
VSmT0JPmuXeOt4bMCnQYGl7VJQbaTaC3vhjhlAaKEfcfSxZP2oFMITX91VdDwW8pw
OTNd0wkF51UD/JHJNBbOXcM2KgTaPJvnaytPoZ+/3Ctk+04ZJydoQWeMxHIguVzZJ
JundilntL6/rHhKTkQFP3j6t2KPoj60HEbxjg41UKc1fbktwW06l0yyVAfHxPDkyg
O+47/yt2ySYallFKO5+BpCpLZfM+NTSs/9kkGfArA0oiYvXxnTSe1GSio2jpGxUgJ
JtDdq6DAcZxhq3ocpGBrzZp9xEO9s7fXNyihIyw7saRbepYu9hDl1/jAS+uaaYawW
KnRmCLnup0ziPxH0ndz/jL8CZhL4YYeaA3C32O4DUh/oYmV6YUuVAxkfJVDA7aVbx
7D/od27SJ3EHDmTi6o3wAvpCW2XpgxG5zV1+pHtZYqYSQT2T0tHFgt98zQTgdALyj
eAaDOyW"
  ["retcode"]=>
  string(2) "00"
  ["retmsg"]=>
  string(8) "ɹ"
}
```

@springleng: Does this issue still occur on more recent Slim versions?

**Comment by akrabat** [comment]
Closing as it appears solved and there's been no response.
