### ISSUE TITLE
Indentation problems

### ISSUE THREAD

**Issue by j4mie** [slimphp/Slim#23]
There seem to be some indentation issues creeping in - see [this comment block](http://github.com/codeguy/Slim/blob/master/slim/Slim.php#L657) for example.

The problems are:
1. Most lines are indented with tabs, but some are indented with spaces.
2. Blank lines often have a single tab character on them. This is a bit messy.

This should probably be fixed sooner rather than later. Pick a style (most of Slim already uses tabs, so I would recommend sticking with tabs for minimal disruption). Fix all the Slim files (normalise indentation and remove hanging indentation on blank lines). Then _document_ in the wiki the indentation style for all contributors. Check all patches conform to this style.

I am happy to do this work, but I'll wait for a decision on which style you want to go with.

**Comment by codeguy** [comment]
I would agree to just stick with tabs for now. Go ahead and take care of this if you can. I'll fix the notFound handler issue.
