### ISSUE TITLE
fastcgi_finish_request use?

### ISSUE THREAD

**Issue by juliangut** [slimphp/Slim#2300]
Should [fastcgi_finish_request](http://php.net/manual/es/function.fastcgi-finish-request.php) be added to APP::respond to improve FPM performance?

**Comment by akrabat** [comment]
Benchmark it and see what improvement it makes?

If nothing happens after respond(), I suspect that it won't make any difference. If you do stuff after respond(), then you probably should consider using closing the session and finishing the request.

**Comment by juliangut** [comment]
I'll find some time to benchmark it with and without code running after respond() call

But I feel, as you do, it won't make a difference unless you do something afterwards

Anyway it could be a good addition for the end user, so they can know stuff can be done after Slim without penalizing response time

**Comment by geggleto** [comment]
Any update? :)

**Comment by juliangut** [comment]
Oh, I forgot about this sorry. I'll try to put the benchmark together tomorrow

**Comment by juliangut** [comment]
Check test project here: https://github.com/juliangut/slim-fastcgi_finish_request-benchmark

> If you are not performing actions after Slim's run there is absolutely no difference using fastcgi_finish_request whatsoever

In case you're executing code after Slim's run (a sleep in my example to give a sense of a heavy task)

* with fastcgi_finish_request => browser receives content as if it weren't there, even though the process is still running on server
* without fastcgi_finish_request => browser is stalled waiting for server process to finish and then it gets the content

What I get from this is that if fastcgi_finish_request is available (only through fastcgi of course) it should be definitely used: it doesn't penalize you if you're not executing code beyond Slim's run but in case you are response is way faster

Please point out things I haven't considered

**Comment by l0gicgate** [comment]
@akrabat what are we doing with this? Is that something you want to implement for Slim 3/4?

The benchmarks aren't all that convincing. 4ms vs 7ms isn't a large enough difference to justify this in my opinion, but your opinion may differ.

**Comment by akrabat** [comment]
Agreed.
