### ISSUE TITLE
Add middleware to a route inside a group

### ISSUE THREAD

**Issue by jvitoroc** [slimphp/Slim#2305]
Im trying to add a middleware to a route that is inside a group but I get following error:
**Undefined variable: auth**
I know... this is silly error($auth is declared in the same scope that the group is)

```
$app->group('/login', function(){
    $this->get('', function (Request $request, Response $response) {
        return $this->view->render($response, 'login.html');
    });

    $this->post('', function (Request $request, Response $response) {
        $body = $request->getParsedBody();
        $userV = new UserLoginValidation($body, $this->db, $this->session);
        $message = new ErrorCodes($userV->loginUser(), getUserLang($this->session, $request));
        return $this->view->render($response, 'login.html', array('flash' => $message->getErrorMessage()));
    })->add($auth);
});
```

**Comment by mathmarques** [comment]
Is `$auth` set before `$app->group('/login', function(){` ?
If the answer is true, it's not the same scope so you must inherit the `$auth` like:
`$app->group('/login', function() use ($auth){`

[See Anonymous functions](http://php.net/manual/en/functions.anonymous.php)

**Comment by jvitoroc** [comment]
@mathmarques problem solved, thanks :D
