### ISSUE TITLE
Callable as string

### ISSUE THREAD

**Issue by piernik** [slimphp/Slim#2306]
In doc I can see that controllers can be defined by string 'ControllerClass:myMethod' (https://www.slimframework.com/docs/objects/router.html). But it doesn't work for me. I always get error: `is neither a callable nor a valid container entry`.
my code:
`$app->get('/test/controller', SprawdzanieKlientaPoRefererze::class . ':controller');`

But when I pass it as array all works:
`$app->get('/test/controller', [SprawdzanieKlientaPoRefererze::class, 'controller']);`

I'm using 3.8.1

Edit:
I think there should be '::' instead of ':'

**Comment by geggleto** [comment]
This is a bug in the documentation.

I assume that your SprawdzanieKlientaPoRefererze::class either accepts the Container as the only constructor argument?

**Comment by akrabat** [comment]
Can you create a minimal example code that shows the problem?

**Comment by piernik** [comment]
I do think it's bug in docs

**Comment by gpredl** [comment]
i'm doing like this
$app->get('/ftp-users', VhostsController::class . ':getFtpUsers')->setName('getVhostFtpUsers');
and have no problems at all.
did you include the class with 'use' statement?

**Comment by RusAlex** [comment]
Just tested and have not found the bug.

https://gist.github.com/RusAlex/baf97b94f5a43ad8bf2b8a4551c9bf89

this code works well for me.

**Comment by geggleto** [comment]
Closing issue :)
