### ISSUE TITLE
RouteGroup class don't respect RouteGroupInterface

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2307]
When I used method "group"  about  "Slim\App" for my router same the documentation a have this error  
 

```
PHP Fatal error:  Class Slim\RouteGroup contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Slim\Interfaces\RouteGroupInterface::getInstance) in ~\MyProject\vendor\slim\slim\Slim\RouteGroup.php on line 19
```

I need add method "getInstance()" myself in the "vendor" directory for fixit this error.

**Comment by geggleto** [comment]
What are you doing exactly? ... 

RouteGroup extends Routable and implements RouteGroupInterface.

Routable is abstract but does not define a method called getInstance

RouteGroupInterface does not define a method getInstance.

https://github.com/slimphp/Slim/blob/3.x/Slim/RouteGroup.php

**Comment by geggleto** [comment]
Closing as old and no follow up
