### ISSUE TITLE
Slim doesn't work

### ISSUE THREAD

**Issue by Kristaps89** [slimphp/Slim#2308]
http://213.239.202.151/api/hello/api

this is api url.
but slim doesn't work for me..
Apache/2.2.15, php 5.6.31 
how can resole it?

**Comment by geggleto** [comment]
Hello. This is not really a support forum; please use our discourse or stack-overflow. http://discourse.slimframework.com/  https://stackoverflow.com/questions/tagged/slim

However in the meantime the basic debugging steps you can do.
- Check your server logs for errors
- Check your application was installed correctly
