### ISSUE TITLE
[Discussion] Document all Methods in a new Response or Request Interface

### ISSUE THREAD

**Issue by Raistlfiren** [slimphp/Slim#2311]
Hey,

It would be significantly more beneficial if Slim included a new interface for both the `Response` and `Request` class to document all methods instead of providing the class as a parameter.  Right now the best interface to use is `ServerRequestInterface` and `ResponseInterface`, but they don't document all methods that the classes provide. 

Thoughts?

Thanks for your time and consideration.

**Comment by geggleto** [comment]
I personally don't see any value in providing an interface for those objects as they contain non-PSR-7 methods. IMO it's okay to type-hint Slim's concrete implementations.
