### ISSUE TITLE
When using IIS & CORS middleware - web.config documentation could use an update

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2312]
Hi,

I hit an issue recently while following the documentation for running SLIM 3 on IIS (specifically IIS8 via Azure App Services), I tried following https://www.slimframework.com/docs/start/web-servers.html which is close but need a couple of additions if you want the OPTIONS calls to be passed to SLIM instead of intercepted by IIS/ASP.NET.

The problem presented during to work I was trying to do with CORS using @tuupola's middleware so I started the issue over at his repo, but it became apparent the web.config needs the tweak not SLIM or the CORS middleware: https://github.com/tuupola/cors-middleware/issues/8

Just logging an issue to update/add a note on the documentation, attached the Web.Config I used to resolve in case it helps someone.

[web.config.txt](https://github.com/slimphp/Slim/files/1349640/web.config.txt)

**Comment by geggleto** [comment]
Feel free to PR. Can you log the issue here: https://github.com/slimphp/Slim-Website

**Comment by ghost** [comment]
Thanks @geggleto  will do
