### ISSUE TITLE
$request->getQueryParams return URL method?

### ISSUE THREAD

**Issue by ursoforte** [slimphp/Slim#2314]
Is it normal that "$request->getQueryParams()" in production,  and APP in a subdirectory, the result in the array, come with the URL method called?
For example:
`app.example.io/admin/reports/premium_customers?type=register&date=10`

The return the method "$request->getQueryParams()" come with a first parameter  the array with "reports/premium_customers".

Here a example the return
![query-params](https://user-images.githubusercontent.com/578063/31297477-7a9d9dcc-aabc-11e7-917f-139d3480dc23.png)
---
I think it should only return "type=register&date=10". Or I am wrong? Is Default for all?
In localhost env, the return is correct, return only the options GET.

**Comment by mathmarques** [comment]
@ursoforte Could you please provide a `var_dump` of the `$_SERVER` received on that url on your production server?

**Comment by ursoforte** [comment]
Sorry. I think that I not can this. Do you want a specific param?
The above case, is a doubt. My easy solution with: in production

`
    if( isset($param['type'])){
    //rum
    }
`

Ignoring the first parameter.

**Comment by tobiasstadler** [comment]
What web server are you using in production?

We are using nginx which we configerd to pass the path as an query param, e.g we have 

fastcgi_param  QUERY_STRING       $uri$query_string;

in our nginx.conf

**Comment by ursoforte** [comment]
Understand. I using Apache 2. and no special settings.
Out a htaccess

```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?$1 [L,QSA]
</IfModule>
```

**Comment by mathmarques** [comment]
Change your [.htaccess](https://www.slimframework.com/docs/start/web-servers.html#apache-configuration) to:
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
</IfModule>
```
and see if the problem persists.

**Comment by ursoforte** [comment]
@mathmarques you're right. This `RewriteRule ^(.*)$ index.php?$1 [L,QSA]` I have caught in another local. Thanks. It Work.
