### ISSUE TITLE
[Slim4] Skeleton Application not work!!

### ISSUE THREAD

**Issue by francescobianco** [slimphp/Slim#2316]
Hi! The current skeleton application
https://github.com/slimphp/Slim-Skeleton
not work with Slim4, it is possible found online Slim4 Skeleton App?
the variable $settings results empty in this line
https://github.com/slimphp/Slim-Skeleton/blob/ce0ceb8398264bb183465dea2a81048bf1552334/src/dependencies.php#L14

**Comment by ivandokov** [comment]
Slim 4 is under heavy development, not released.

**Comment by akrabat** [comment]
As @ivandokov says, there is no skeleton application for the 4.x branch.

**Comment by ruslan-avantis** [comment]
Try this https://github.com/pllano/slim4-skeleton

The stable version will be after the release Slim4
