### ISSUE TITLE
Access and modify view data from Response object

### ISSUE THREAD

**Issue by jakesee** [slimphp/Slim#2322]
I am relatively new to Slim and I am trying to [solve the problem of populating edit forms](https://stackoverflow.com/questions/46958441/how-to-modify-twig-template-data-from-slim-response-object).

I am currently using Slim Twig View for templating and I want to access and edit the template data from Response object. Is it possible to do that? Looking through the source code, I think it is not possible. In that case what is the recommended strategy when using Slim/Twig combination?

Thanks.

**Comment by geggleto** [comment]
This question is better asked on our slack and/or our discourse forum http://discourse.slimframework.com/

You are in full control of the template data prior to rendering the template to the response object. if you post on our discourse, I'm sure one of our community members can help you out with a concrete code example :)
