### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#2324]
Personally, I like and have used the [Contributor Covenant](https://www.contributor-covenant.org) on other projects.

Does anyone disagree or have another preference?

**Comment by akrabat** [comment]
The main advantage I've seen has been clarity of expectations. Anecdotally, on other projects, we've had devs say to us privately that they only considered submitting a PR because the CoC gave them the confidence that they wouldn't be attacked in the comments.

**Comment by geggleto** [comment]
Do we need it? I have felt that our community has been incredibly good in this aspect.

**Comment by geggleto** [comment]
Also; do we as maintainers have the resources to monitor and enforce a CoC?

**Comment by juanpagfe** [comment]
@geggleto I think it is always needed.  Even if it has not been needed.  Better to have it and don't need it than need it and don't have it.

**Comment by akrabat** [comment]
Discussion on Slack suggests that basing on https://www.ruby-lang.org/en/conduct/ / https://github.com/laravel/framework/blob/5.5/CODE_OF_CONDUCT.md may work for our community.

i.e. something like:

> This document provides community guidelines for a safe, respectful, productive, and collaborative place for any person who is willing to contribute to the Slim community. It applies to all “collaborative space”, which is defined as community communications channels (such as mailing lists, submitted patches, commit comments, etc.). Any violations of the code of conduct may be reported by contacting one or more of the project maintainers.
>
> * Participants will be tolerant of opposing views.
> * Participants must ensure that their language and actions are free of personal attacks and disparaging personal remarks.
> * When interpreting the words and actions of others, participants should always assume good intentions.
> * Behaviour which can be reasonably considered harassment will not be tolerated.

**Comment by chris48s** [comment]
> Do we need it? I have felt that our community has been incredibly good in this aspect.

@geggleto One of the findings from GitHub's [open source survey](http://opensourcesurvey.org/2017/#insights) was that

> "Documentation that clearly explains a project's processes, such as contributing guides and codes of conduct, is valued more by groups that are underrepresented in open source, like women."

While it is amazing that the existing Slim community is fortunate enough not to have issues with poor behaviour which need to be addressed, adopting a code of conduct may remove a barrier to some potential contributors which you may not be aware is a problem for them.

**Comment by damianopetrungaro** [comment]
@akrabat 

> The main advantage I've seen has been clarity of expectations. Anecdotally, on other projects, we've had devs say to us privately that they only considered submitting a PR because the CoC gave them the confidence that they **wouldn't be attacked in the comments**.

Really?!

Anyway if we have this kinda issue i totally agree to integrate a CoC.
For me it's ok Contributor Covenant.
