### ISSUE TITLE
500 Internal Server Error.

### ISSUE THREAD

**Issue by kjhatis** [slimphp/Slim#2325]
Why it is always showing this in case of any kind of error?? Shouldn't you put an error handler. i am not able to detect what was the thing causing error.

**Comment by akrabat** [comment]
Try looking in your PHP error log. Alternatively, Enabled the `displayErrorDetails` setting.

**Comment by kjhatis** [comment]
Log Path? there is no log or temp or any storage folder exist. do i need to manually create?

`$stmt = $this->con->prepare("INSERT INTO questions(question,description, askedby, status,created_time,update_time) values(?, ?, ?, '1', NOW(), NOW())");
            $stmt->bind_param("sss", $data['question'], $data['description'], $data['imei']);`

These two statement causing the error, and i am getting internal server error. even for undefined functions or class it is showing internal server error.

**Comment by akrabat** [comment]
It's wherever you've set it up in your `php.ini`.  Do you have `displayErrorDetails` set? There's an example here:per https://www.slimframework.com/docs/objects/application.html#application-configuration

**Comment by ghost** [comment]
Hello Kjhatis

As Ive noted when using slim, you need to know where your logs are (you can set that in three places, in a config file when using Loggers with slim, in your webserver config and in php.ini for pure php errors).

I dont really know if you are using eloquent, but I am 100% sure you are missing a comma or mixed something wrt to your database table. Error 500s with database connections are common if you dont use models.

Read the below 
https://www.google.pl/url?q=https://www.slimframework.com/docs/cookbook/database-eloquent.html&sa=U&ved=0ahUKEwiV94XiuKTXAhVJqxoKHYJrDsMQFggLMAA&usg=AOvVaw33cKZsF9AklfAThVJJRPQy

**Comment by 4e4y** [comment]
Hi guys,

I do not know if this is resolved but here are my observations:
Kjhatis is executing 2 PHP statements:

$stmt = $this->con->prepare("INSERT INTO questions(question,description, askedby, status,created_time,update_time) values(?, ?, ?, '1', NOW(), NOW())"); 
and
$stmt->bind_param("sss", $data['question'], $data['description'], $data['imei']);

First one is expecting 3 bind parameters (the ? symbols) while in the second one 4 parameters are passed.

Kjhatis,
Please check this and pass proper bind parameters and let us know if this solves your issue.

Best regards.

**Comment by kjhatis** [comment]
My Actual Problem Was "Internal Server Error". for wrong sql statement it should not show Internal Server Error.

and take a look at the Parameters again one is expecting 3 params and i passing 3 also that is correct.

**Comment by kjhatis** [comment]
this issue i have resolved. i enabled the errors by adding this on the top of v1/index.php

`error_reporting(-1);
ini_set('display_errors', 'On');
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);`

now i am able to catch if any exception raised.
