### ISSUE TITLE
Output buffering in 3.9 breaks with custom error handlers

### ISSUE THREAD

**Issue by moritz-h** [slimphp/Slim#2334]
I updated to 3.9 and had to deal with lots of warning from PHPUnit `Test code or tested code did not (only) close its own output buffers`.
It took a while to find the reason as the changed output buffering behaviour from #2270 in combination with custom error handlers.
I would totally agree with the problem mentioned in #2208 (I often enough typed var_dump();exit; to workaround this during debugging) but I think the error handlers are the wrong place to fix this.

In the Slim documentation is written:
> The default error handler is very basic. [...] This is probably not appropriate for production applications. You are strongly encouraged to implement your own Slim application error handler.
https://www.slimframework.com/docs/handlers/error.html

This makes me think using custom error handlers is more or less the official way to go like a clean API and not just some kind of hack. Therefore it feels totally wrong to have to deal with framework internals like the output buffering.

**Comment by dmelo** [comment]
This issue seems related with the PR #2333 .

**Comment by moritz-h** [comment]
@dmelo 
#2333 does only address the implementation within the Error handler, I think it is generally a bad idea to handle Output buffering in an Error handler, because when you use your own Handlers you must know about output buffering, which I think is a framework internal thing.

I think #2337 looks like a good solution. This makes the buffer interaction optional within the Error handler. The frameworks cleans the buffer by itself, you don't need to do this in a (custom) Error Handler by default. But optionally if you want access to the buffer you can just use `ob_get_contents()`

**Comment by akrabat** [comment]
Can you provide the code that caused the problem?

**Comment by moritz-h** [comment]
@akrabat I think this more a design bug what I reported. It is clear where the problem comes from. With 3.9 Slim closes the output buffering in the Error handlers. When I now replace the Error handlers with custom ones, I need to know that I also have to handle the closing of output buffering.
The above mentioned problem is gone when I copy the outbuffer handling from Slim Error handlers to my custom ones. But I think this is bad design as I think you see the Error handlers as replacable modules.(At least the documentation makes me think this)
I like the discussion in #2337 This should fix what I reported here.

**Comment by travisdetert** [comment]
I can confirm that this is still a bug.  I think it's fair to say that unsetting the handler via your docs: 
unset($app->getContainer()['errorHandler']);
unset($app->getContainer()['phpErrorHandler']);

SHOULD disable it, but it does not.  Output buffering is truncated.  This really should be fixed since your error handling doesn't handle all errors anyway.

**Comment by akrabat** [comment]
@travisdetert Can you explain how error handling is not disabled after removing the error handler?

**Comment by travisdetert** [comment]
Error handling is disabled, but simply overriding error handling (admittedly not using your handler functionality, as that was not obvious per the docs), buffer output is truncated.  Error handling should not have any impact on output buffering in this context.

**Comment by akrabat** [comment]
@travisdetert Can you provide an example app in a single index.php that shows the problem?
