### ISSUE TITLE
Middleware Short Circuit

### ISSUE THREAD

**Issue by kevinmlong** [slimphp/Slim#2335]
Let's say I have an app that has a series of middleware layers:

- MIDDLEWARE 3
- MIDDLEWARE 2
- MIDDLEWARE 1
- APP

Let's also say that Middleware 3 is a logging middleware and as a request passes through layers it, Middleware 2 decides there is no need for it to continue (e.g. authentication). Is there a way to get the return to pass back through Middleware 3 so that the logging middleware and log information about the response? My current understanding is that Middleware 2 can either return a complaint response object or pass it along to the next layer. Is this accurate?

Thanks in advance for the help!

**Comment by geggleto** [comment]
That is how middleware works...

Standard Middleware
```php
function ($req, $res, $next) {
    //BEFORE
    $res = $next($req, $res);
    //AFTER
    return $res;
};
```

//Short Circuit
```php
function ($req, $res, $next) {
    //BEFORE
    if (cond) {
        $res = $next($req, $res);
        //AFTER
        return $res;
    }

    return $res;
};
```

**Comment by kevinmlong** [comment]
@geggleto - your example of the short circuit doesn't cause the Middleware 3 to be called though. Essentially what I'm looking for is something like:

```php
// MIDDLEWARE 2
public function __invoke($request, $response, $previous, $next){       
      if (cond) {
         // carry-on down the path - MIDDLEWARE 1
         $res = $next($req, $res);
         return $res;
      }

      if (retreat) {
          //Go back to MIDDLEWARE 3
          return $previous($req, $res);
      }
}
```

**Comment by geggleto** [comment]
Ah; then no you cannot do conditional routing like that.

**Comment by akrabat** [comment]
I'm confused as Slim's middleware works exactly like you want.

i.e. when Middleware2 returns a response, that response is returned through the previous middleware (Middleware3 in this case).

Consider this code:

```php
$app->add(function ($request, $response, $next) {
    // middleware 1
    $response->write('Middleware 1, before $next()<br>');
    $response = $next($request, $response);
    $response->write('Middleware 1, after $next()<br>');
    return $response;
});

$app->add(function ($request, $response, $next) {
    // middleware 2
    $response->write('Middleware 2, before $next()<br>');
    $response = $next($request, $response);
    $response->write('Middleware 2, after $next()<br>');
    return $response;
});

$app->add(function ($request, $response, $next) {
    // middleware 3
    $response->write('Middleware 3, before $next()<br>');
    $response = $next($request, $response);
    $response->write('Middleware 3, after $next()<br>');
    return $response;
});

$app->get("/", function ($request, $response, $args) {
    $response->write("<p>Hello World.</p>");
    return $response;
});
```

The output is:

```
Middleware 3, before $next()
Middleware 2, before $next()
Middleware 1, before $next()
Hello World.

Middleware 1, after $next()
Middleware 2, after $next()
Middleware 3, after $next()
```

Now. change middleware2 so that it _doesn't_ call `next()`:

```php
$app->add(function ($request, $response, $next) {
    // middleware 2
    $response->write('Middleware 2 short circuits<br>');
    return $response;
});
```

The output is now:

```
Middleware 3, before $next()
Middleware 2 short circuits
Middleware 3, after $next()
```


As you can see, Middleware 3 has still run and can do its logging as you would expect.
