### ISSUE TITLE
Throw an exception when controller returns a stream with a failed popen process

### ISSUE THREAD

**Issue by Rudloff** [slimphp/Slim#2338]
Hello,

I'm sometimes returning `popen` streams in my controllers:
```php
$process = popen('foo');
return $response->withBody(new \Slim\Http\Stream($process));
```

It works pretty well but it is really hard to debug when the process fails because I don't get any error in the logs, Slim just outputs an empty response.

Do you think it would be possible to make Slim raise an exception if the popen process fails? Maybe by calling `pclose()` at the end of the stream and throwing an exception if it does not return 0?
(We already have some code to detect if a stream is a pipe [here](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Stream.php#L438).)

**Comment by geggleto** [comment]
Unfortunately once you pass control over via the process that is it for Slim.

I think what you really want is a way to message/listen across the process.

You can listen for things inside the process via STDOUT as documented on the popen page.

> This pointer may be used with fgets(), fgetss(), and fwrite(). 

Aside from this there is nothing we can do at a framework level; popen doesn't generate exceptions from what I can tell in the docs.

**Comment by Rudloff** [comment]
I can't use STDOUT since it is already used to return the data that will be streamed to the browser.

I guess the only thing we can use is the exit code, so I was thinking about something like this:
```diff
diff --git a/Slim/App.php b/Slim/App.php
index 587e6710..42e79914 100644
--- a/Slim/App.php
+++ b/Slim/App.php
@@ -439,6 +439,13 @@ class App
                     }
                 }
             }
+
+            if ($body->isPipe()) {
+                $exitCode = $body->close();
+                if ($exitCode > 0) {
+                    throw new \Exception('Process did not exit correctly. Exit code: '.$exitCode);
+                }
+            }
         }
     }
 
diff --git a/Slim/Http/Stream.php b/Slim/Http/Stream.php
index 27c7a764..80167957 100644
--- a/Slim/Http/Stream.php
+++ b/Slim/Http/Stream.php
@@ -212,13 +212,15 @@ class Stream implements StreamInterface
     {
         if ($this->isAttached() === true) {
             if ($this->isPipe()) {
-                pclose($this->stream);
+                $exitCode = pclose($this->stream);
             } else {
                 fclose($this->stream);
             }
         }
 
         $this->detach();
+
+        return $exitCode;
     }
 
     /**
```
which would at least throw an exception if the process didn't exit correctly.
