### ISSUE TITLE
Add Authorization header to Slim_Http_Request::headers()

### ISSUE THREAD

**Issue by brodrigu** [slimphp/Slim#234]
PHP and sometimes apache removes the 'Authorization' header from the $_SERVER variable. 

Since Slim uses the $_SERVER variable instead of apache_request_headers() to retrieve the list of headers "Authorization" cannot be retrieved using $request->headers('Authorization').

Please update the headers function to check apache_request_headers() for missing headers.

**Comment by codeguy** [comment]
Most HTTP headers will be available as `HTTP_*` (e.g. DNT, X-Do-Not-Track, X-Forwarded-For). PHP and Basic/Digest authentication is a bit weirder. PHP hijacks these HTTP request headers and inserts them into:
- PHP_AUTH_DIGEST
- PHP_AUTH_USER
- PHP_AUTH_PW
- AUTH_TYPE

The `AUTH_TYPE` value is "Basic" or "Digest". The raw value of the Authorization header is available in the `PHP_AUTH_DIGEST` value.

Slim does not presume you are using Apache. Many use nginx, lighttpd, and others. That being said, I do not think that Slim looks for the `PHP_AUTH_DIGEST` variable, so I'll be sure that is pulled in, too. Look for a push in a few days.

**Comment by codeguy** [comment]
I've tweaked how Slim parses and exposes the request headers through the Response object. The `PHP_AUTH_DIGEST` variable is now available both in the Slim app's environment array and with `$response->headers('PHP_AUTH_DIGEST')`. If present, this should equal the raw `Authorization` header sent with the request.

I'll be introducing HTTP Basic/Digest auth middleware eventually.

**Comment by savdeep** [comment]
@codeguy , In current version i am not able to find any of them. Neither $response->headers('PHP_AUTH_DIGEST') not Authorization .. 
Any suggestion?

**Comment by tuupola** [comment]
Discussion at https://github.com/slimphp/Slim/issues/831 might help.

**Comment by sachinvrg** [comment]
try this one in your .htaccess
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(._)
RewriteRule ._ - [e=HTTP_AUTHORIZATION:%1]
may be it helps you.

**Comment by erjatingro** [comment]
$_SERVER[REDIRECT_HTTP_AUTHORIZATION] showing value of Authorization
