### ISSUE TITLE
Response from Slim 3.9.0 not forwarding

### ISSUE THREAD

**Issue by AlgyTaylor** [slimphp/Slim#2340]
Hi all,

I'm afraid I have **no** idea why this is happening, but my redirects have stopped working with Slim 3.9.0 (downgrading to 3.8.1 fixes the problem).  It just shows a blank page.  I assume some output has been sent to the client, although the page headers suggest that there's no body content in it

The code that works in 3.8.1 but not in 3.9.0 is:
```
          return $response
                ->withStatus(401)
                ->withHeader(
                    'Location',
                    $this->defaultPath . '?path=' . urlencode($path)
                );
```

Let me know if you need any more information :) sorry if the above is woefully inadequate!

**Comment by geggleto** [comment]
This is not a bug; you cannot forward a HTTP request with anything but at 3xx status code.

**Comment by geggleto** [comment]
...... it should not work in 3.8.1...

**Comment by geggleto** [comment]
Possibly related to https://github.com/slimphp/Slim/commit/dfcd63234d9610c8bfc3c26c8813659212a8c55e

**Comment by akrabat** [comment]
It's a bug in your code

For a browser to redirect, you need to send a `3xx` status code. You're setting a `401`.

In Slim 3.8.1, there's a bug where setting a "Location" header meant that the status code you've set with `withStatus()` was ignored. This has been fixed, which is your problem.

Change your code to:

```
return $response
                ->withStatus(302)
                ->withHeader(
                    'Location',
                    $this->defaultPath . '?path=' . urlencode($path)
                );
```

This should work in both Slim 3.8.1 and 3.9.0

**Comment by AlgyTaylor** [comment]
Ah, an error in user!  Hadn't realised it **needed** to be a 3xx code.  I've learnt something new today.

Thanks both :1st_place_medal:
