### ISSUE TITLE
Unofficial hack submission

### ISSUE THREAD

**Issue by jakesee** [slimphp/Slim#2343]
Hi @codeguy 

I would like to submit [Slim-Template-Response](https://github.com/jakesee/Slim-Template-Response) for your consideration to be added to the [unofficial hack list](https://github.com/slimphp/Slim/wiki/Slim-Unofficial-Hacks).

Thanks.

**Comment by akrabat** [comment]
Hi, for Slim 3, we use the documentation website for things like this. 

Create a cookbook entry and PR it to the [Slim-Website](https://github.com/slimphp/Slim-Website) repository.
