### ISSUE TITLE
Syntax error, unexpected 'class' 

### ISSUE THREAD

**Issue by QusaiFarraj** [slimphp/Slim#2348]
### I'm getting this error in Slim v3.8.1.

`Got error 'PHP message: PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or      '{' or '$' in /api/vendor/slim/slim/Slim/Container.php on line 149\n'`

I found that `PimpleContainer::class` giving this error and I did this `new PimpleContainer` to solve this issue. 

### Here is the function that I messed with:
`private function exceptionThrownByContainer(\InvalidArgumentException $exception)
    {
        $trace = $exception->getTrace()[0];
        return ($trace['class'] === new PimpleContainer) && ($trace['function'] === 'offsetGet');
    }`

Is that something has been fixed in the new release?

**Comment by geggleto** [comment]
This is not a bug at all in our code base.

We have unit tests that run against every PR and this has not shown up at all.

You can see the status of them here: https://travis-ci.org/slimphp/Slim

**Comment by tflight** [comment]
Which version of PHP are you running under?

**Comment by QusaiFarraj** [comment]
I have two versions 5.6 and 5.4. I found out that I'm using the older version.
