### ISSUE TITLE
Slim\Http\Uri has no way to disable authorization

### ISSUE THREAD

**Issue by splitbrain** [slimphp/Slim#2349]
When you have an Uri that has a user and password set, you can not get a Uri without the auth info.

I would assume this would work:

```php
$uri = Slim\Http\Uri::createFromString('https://user:pass@host.com/path');
echo (string) $uri . "\n";
# https://user:pass@host.com/path

$uri = $uri->withUserInfo('','');
echo (string) $uri . "\n";
# https://:pass@host.com/path
```

As you can see, the password is not unset and an incorrect URL is constructed.

**Comment by geggleto** [comment]
@akrabat  ... I honestly can't tell if this is a problem in the PSR-7 spec... or not.

@splitbrain I'll look at other PSR-7 implementations and see what they do; this is very likely a huge edge case that no-one thought of.

**Comment by splitbrain** [comment]
The Interface comment says:

> Password is optional, but the user information MUST include the user; an empty string for the user is equivalent to removing user information

I would interpret this as removing *all* user information including the password, when an empty user is passed.

Some info on the background: My application runs behind mod_kerberos which sets `PHP_AUTH_USER` and `PHP_AUTH_PW` which are used in createFromEnvironment. I my application I then need to pass the baseUrl to my Twig template handler, however `getBaseUrl` now returns urls with the password in clear text which are then added to all my links. So I need  a way to pass a baseUrl without the credentials. I worked around this by doing a `parse_url` myself, but it would be nicer to simply unset the authentication on the Uri object.

**Comment by geggleto** [comment]
yeah looks like a 🐛  👍

**Comment by splitbrain** [comment]
I just noticed that this seems to be fixed by #2332

**Comment by mahagr** [comment]
Yeah, this one was an issue I fixed for some time ago. Reverting back to 3.8 also fixes the issue.

**Comment by akrabat** [comment]
#2332 is now merged to 3.x
