### ISSUE TITLE
redirect don't work in production server

### ISSUE THREAD

**Issue by nicogranelli** [slimphp/Slim#235]
When I upload my app to the production server the redirect 

For example $app->redirect('/login'); produce a page with "/login" as text. Also checked that the Location header is not set.

For this problem I tried to redirect using a simple view with a refresh meta. And now I see that the values in $_SESSION are lost

can this be a configuration problem? maybe php version? what info do I need to post here to help fix this?

Thanks

**Comment by codeguy** [comment]
There are a lot of variables at play. Can you push this to a public URL and send me the URL that demonstrates the faulty redirect? This will let me narrow down what may be happening.

**Comment by nicogranelli** [comment]
Well, while I was trying to create an example I found the problem: one of the files I require (with "require_once") had an utf8 format but with BOM. In notepad++ you have 2 uft8 option, with or without BOM. It seems that this BOM if what was causing my problem. 

Now I will have to try this modification in my real project, but I'm pretty sure this is the source of the problem.

**Comment by codeguy** [comment]
Sounds good. Closing this out. If you continue to have issues, please open a thread at http://help.slimframework.com.
