### ISSUE TITLE
Redirects with status no longer work in 3.9

### ISSUE THREAD

**Issue by emilorol** [slimphp/Slim#2355]
I have been doing this before 3.9

```
return $response->withStatus(404)->withRedirect($this->router->pathFor('home'));
```

Now even if I do it like this:

```
return $response->withRedirect($this->router->pathFor('home'), 404);
```
The redirection fail.

**Comment by akrabat** [comment]
Web browsers will not redirect on a `404` status code as that's against the spec. You need a `302` status code to make a browser redirect.

`return $response->withRedirect($this->router->pathFor('home'));`

or

`return $response->withStatus(302)->withRedirect($this->router->pathFor('home'));`

**Comment by emilorol** [comment]
Thank you.
