### ISSUE TITLE
How to get the container in v4 to output exceptions?

### ISSUE THREAD

**Issue by lazharichir** [slimphp/Slim#2358]
My app obviously throws `\Exception` when it needs to and I would love for Slim to send the response immediately once there is an `\Exception` thrown, and show the `\Exception` message in the json body.

However, it doesn't work (see below one-page example): the browser shows

    Slim Application Error
    A website error has occurred. Sorry for the temporary inconvenience.

And my php_error.log shows more details:

	[30-Nov-2017 23:00:57 Europe/Madrid] Slim Application Error:
	Type: Exception
	Message: Error blah blah...
	File: /Users/Lazhar/myproject/services/user-service/v1/src/app.php
	Line: 24
	Trace: #0 [internal function]: {closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
	#1 /Users/Lazhar/myproject/services/user-service/v1/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
	#2 /Users/Lazhar/myproject/services/user-service/v1/vendor/slim/slim/Slim/Route.php(327): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
	#3 /Users/Lazhar/myproject/services/user-service/v1/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
	#4 /Users/Lazhar/myproject/services/user-service/v1/vendor/slim/slim/Slim/Route.php(301): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
	#5 /Users/Lazhar/myproject/services/user-service/v1/vendor/slim/slim/Slim/App.php(694): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
	#6 /Users/Lazhar/myproject/services/user-service/v1/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
	#7 /Users/Lazhar/myproject/services/user-service/v1/vendor/slim/slim/Slim/App.php(588): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
	#8 /Users/Lazhar/myproject/services/user-service/v1/vendor/slim/slim/Slim/App.php(566): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
	#9 /Users/Lazhar/myproject/services/user-service/v1/src/app.php(30): Slim\App->run()
	#10 /Users/Lazhar/myproject/services/user-service/v1/src/index.php(3): require('/Users/Lazhar/t...')
	#11 {main}
	View in rendered output by enabling the "displayErrorDetails" setting.

This is the app.php file...

    <?php

    // Autoload
    require_once('../vendor/autoload.php');

    // Instanciate our Slim App
    $app = new \Slim\App();

    // ERROR HANDLING

    $c = $app->getContainer();
    $c['errorHandler'] = function ($c) {
        return function ($request, $response, $exception) use ($c) {
            return $c['response']->withStatus(500)
                                 ->withJson([
                                    'error' => true,
                                    'message' => $exception->getMessage()
                                ]);
        };
    };

    $app->get('/exception', function($request, $response, $args) {

        throw new \Exception("Error blah blah...");

        return $response->withJson(['foo'=>'bar']);
    });

    // Run the show
    $app->run();

**Comment by geggleto** [comment]
Depending what version of 4 you are using there might not actually be a container :D

**Comment by l0gicgate** [comment]
@lazharichir are you using the lastest version of the Slim 4 branch?

I suspect that you may be using an older version of that branch. If so, update to latest version. Notice that the error handlers are being set via shortcut methods `App::setErrorHandler()`, `App::setPhpErrorHandler()`, `App::setNotFoundHandler()` and `App::setNotAllowedHandler()`.

Note that error handling is being moved to middleware. Please refer to PR #2398. Feel free to use the code base from my forked version for enhanced error handling capabilities. It is located [here](https://github.com/l0gicgate/Slim/tree/4.x-ErrorMiddleware)

The following code will let you implement what you're trying to do with the current error handling in the current `4.x` master branch.

```php
use Slim\App;
use Slim\Http\Request;
use Slim\Http\Response;

$app = new App();

$handler = function (Request $req, Response $res, $exception) use ($app) {
    return $res->withStatus(500)->withJson($exception->getMessage());
};
$app->setErrorHandler($handler);

$app->get('/foo', function ($req, ResponseInterface $res) {
    throw new \Exception('My message.');
});

/**
 * This will output the string "My message." and have a status code of 500.
 */
$app->run();
```
@geggleto you can close this.
