### ISSUE TITLE
Possible Backwards Incompatible Change in 3.9

### ISSUE THREAD

**Issue by it-all** [slimphp/Slim#2359]
My custom notFoundHandler works in 3.8.1 but not in 3.9.x. Now I just get the browser error. The redirect line doesn't work. Any idea on what changed and how I can fix it?

```
//Override the default Not Found Handler
'notFoundHandler' => function ($container) {
    return function ($request, $response) use ($container) {
        return $container['response']
            ->withStatus(404)
            ->withHeader('Content-Type', 'text/html')
            ->withRedirect($container->router->pathFor('pageNotFound'));
    };
}
```

**Comment by tflight** [comment]
See [this discussion](https://github.com/slimphp/Slim/issues/1730) as it may pertain to your issue.

**Comment by akrabat** [comment]
Browsers only automatically follow the Location header if you set the status to a 3xx code. You’re setting 404.

In 3.8.1 and below, there was a bug where the status code you set was not being honoured.

**Comment by it-all** [comment]
Ok, thanks. 
It works when I remove the status and header lines and simply redirect:
```
//Override the default Not Found Handler
'notFoundHandler' => function ($container) {
    return function ($request, $response) use ($container) {
        return $container['response']
            ->withRedirect($container->router->pathFor('pageNotFound'));
    };
}
```
