### ISSUE TITLE
Minimum PHP version of 7.1 for next major release ?

### ISSUE THREAD

**Issue by MarioBlazek** [slimphp/Slim#2364]

**Comment by geggleto** [comment]
7+ :D

**Comment by MarioBlazek** [comment]
Not sure what do you mean @geggleto https://github.com/slimphp/Slim/blob/4.x/composer.json#L31

**Comment by geggleto** [comment]
The PSR-15 spec is written for 7+ we haven't updated the 4.x composer json

**Comment by MarioBlazek** [comment]
Cool, tnx for the clarification.

**Comment by danopz** [comment]
ref #2175
