### ISSUE TITLE
Slim Parse Error 

### ISSUE THREAD

**Issue by jbalbert** [slimphp/Slim#2365]
Hi! Is there anyway I could catch 'Parse Error' and 'Warnings' on Slim's Error Handler?

I already applied these lines of codes on my container. 

$container["errorHandler"] = function ($c) {
    return new \Slim\Handlers\ExceptionErrorHandler($c["logger"]);
};

$container["phpErrorHandler"] = function ($c) {
    return new \Slim\Handlers\PhpErrorHandler($c["logger"]);
};

But when I get these kinds of error the error handlers doesn't work :
1. <br />
<b>Parse error</b>:  syntax error, unexpected '$app_log_error' (T_VARIABLE) in
<b>/var/www/html/myProject/backend/api/module/Handlers/ExceptionErrorHandler.php</b> on line
<b>23</b>
<br />

2. <br />
<b>Warning</b>:  Division by zero in
<b>/var/www/html/myProject/backend/api/module/Controllers/LoginController.php</b> on line
<b>56</b>
<br />
float(INF)

Is there anyway that I could catch these errors using Slim's Error Handler?

**Comment by geggleto** [comment]
No they are syntax errors

**Comment by jbalbert** [comment]
Ohhh Okay. Thank you
