### ISSUE TITLE
The App overrides static basePath on the router

### ISSUE THREAD

**Issue by morozov** [slimphp/Slim#2367]
When a Slim application works behind a reverse proxy and generates absolute URLs, it generates them according to the internal web server hostname and port, not the external ones. Even if the base path is statically defined in container configuration, it gets overridden during request processing:

https://github.com/slimphp/Slim/blob/3ab1a154e45546fd8654f87708577096391b50f7/Slim/App.php#L340-L342

Currently, it's only possible to override this behavior by introducing a middleware which kicks in after `App::process()` and restores the needed base path.

It would be nice if the `App` only set the base path if it's not set yet.

**Comment by geggleto** [comment]
I don't think we will be fixing this in v3... but we will probably address this in v4.

**Comment by morozov** [comment]
Should this be reopened for Slim 4? From the DX perspective, it looks like a bug while the described approach is more of a workaround, not a recommended solution.
