### ISSUE TITLE
Slim Redirect Displays Headers Only

### ISSUE THREAD

**Issue by UchennaPrudensia** [slimphp/Slim#2370]
Slim Redirect method returns a 301 status code and nothing more. I will like to redirect to a login page if a user is not signed in. but I keep getting a header that looks like this : 

HTTP/1.1 301 $s
Server: nginx/1.13.7
Date: Thu, 14 Dec 2017 15:56:53 GMT
Transfer-Encoding: chunked
Connection: keep-alive
: /login: 

I expect that the redirect method will call '\login' route which will then display my login.html page. I  have attached a copy of my server.php file below. When I execute curl -D- localhost/login, it works. What am I doing wrong?

> $slim->get('/', function(Request $req, Response $res) use ($provider): Response{
>   $sessionId = $req->getCookieParams()['session'] ?? ' ';
>    if(!$provider->hasSession($sessionId))
>     {
>        return $res->withRedirect('/login');
>     }

//Login Callback
> $slim->get('/login', function(Request $req, Response $res): Response {
> $res->getBody()->write(file_get_contents('templates/login.html'));
> return $res->withHeader('Content-Type', 'text/html;charset=utf8');
});

`$adapter = new \Packt\Chp6\Http\SlimAdapterServer($slim);`

//Login Route 
`$app->route('/', $adapter, ['*']);`
`$app->route('/login', $adapter, ['*']); `

[server.php.zip](https://github.com/slimphp/Slim/files/1559897/server.php.zip)

**Comment by akrabat** [comment]
Please provide the output of `curl -I http://yourserver.com/path/to/`

**Comment by UchennaPrudensia** [comment]
Thank you. This is the output I get... 

>HTTP/1.1 301 $s
>Server: nginx/1.13.7
>Date: Thu, 14 Dec 2017 16:26:04 GMT
>Connection: keep-alive
>: /login:

**Comment by akrabat** [comment]
That makes no sense as the status line is wrong and you're missing a header name. 

How about `curl -v http://yourserver.com/path/to/` ? Also show me the curl command itself.

**Comment by UchennaPrudensia** [comment]
Ahh Yes you are right when I curl -I http://localhost/login, I get this output: 

>HTTP/1.1 200 $s
>Server: nginx/1.13.7
>Date: Thu, 14 Dec 2017 16:30:31 GMT
>Connection: keep-alive
>: text/html;charset=utf8: 

curl command is  `curl -I http://localhost/login`

**Comment by geggleto** [comment]
You dont have a content type header?
In the previous one you don't have a Location header.

**Comment by UchennaPrudensia** [comment]
thank you.  Where do I set the content type header and location header...
I did `curl -v http://localhost/login` and I got this output: 

>Trying ::1...
>TCP_NODELAY set
>Trying 127.0.0.1...
>TCP_NODELAY set
>Connected to localhost (127.0.0.1) port 80 (#0)
> GET /login HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> 
> HTTP/1.1 200 $s
> Server: nginx/1.13.7
> Date: Thu, 14 Dec 2017 16:45:40 GMT
> Transfer-Encoding: chunked
> Connection: keep-alive
> : text/html;charset=utf8: 
> 
> <!DOCTYPE html>
> <html>
>  <head>
>    <meta charset="utf-8">
>   <title>Chat Application: Login</title>
>    <script src="bower_components/jquery/dist/jquery.min.js"></script>
>    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
>    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css"/>
>  </head>
>  <body>
>    <div class="row" id="login">
>    <div class="col-md-4 col-md-offset-4">
>        <div class="panel panel-default">
>            <div class="panel-heading">Login</div>
>            <div class="panel-body">
>                <form action="/authenticate" method="post">
>                    <div class="form-group">
>                        <label for="username">Username</label>
>                        <input type="text" name="username" id="username" placeholder="Username" >class="form-control">
>                   </div>
>                    <div class="form-group">
>                        <label for="password">Password</label>
>                       <input type="password" name="password" id="password" placeholder="Password" >class="form-control">
>                   </div>
>                    <button type="submit" id="do-login" class="btn btn-primary btn-block">
>                        Log in
>                    </button>
>               </form>
>           </div>
>       </div>
>    </div>
></div> 
></body>
></html>

**Comment by geggleto** [comment]
I'm going to guess that it's a problem somewhere in your NGINX configuration. Slim and PHP sets a default header for Content-Type.

**Comment by UchennaPrudensia** [comment]
wow, I just realized that. Let me check my Nginx config file.

**Comment by UchennaPrudensia** [comment]
I fixed the header issue. My output for `curl -D- http://localhost` is 
> HTTP/1.1 302 Found
>Server: nginx/1.13.7
>Date: Fri, 15 Dec 2017 05:13:37 GMT
>Transfer-Encoding: chunked
>Connection: keep-alive
>Location: /login 

The content-type is not showing up at all. When I `curl -D- http://localhost/login` (file that I want to be redirected to...) I get the following output: 

>HTTP/1.1 200 OK
>Server: nginx/1.13.7
>Date: Fri, 15 Dec 2017 05:21:32 GMT
>Content-Type: text/html;charset=utf8
>Transfer-Encoding: chunked
>Connection: keep-alive

**Comment by akrabat** [comment]
I would have expected that redirection to work. You don't need a Content-Type header for a 302, but you do need a Location.

**Comment by UchennaPrudensia** [comment]
Perhaps it could be from my Nginx conf file. Please, can you take a look at it and see if it has any bug. According to my Nginx configuration, a request made to http://localhost/ should serve index.html, then my code logic says the user has no sessions so redirect to http://localhost/login instead. 
Am I missing something? Thank you for your replies and help... 

**Server.php**
[server.php.zip](https://github.com/slimphp/Slim/files/1562653/server.php.zip)

> server {
>    listen       80;
>    server_name  localhost;

>    #charset koi8-r;
>    access_log  /var/log/nginx/host.access.log  main;
>    error_log /var/log/nginx/error.log;

>    location / {
>       root   /usr/share/nginx/html;
>        try_files $uri $uri/index.html
>        @phpsite;
>    }

>    location @phpsite{
>    proxy_http_version 1.1;
>    proxy_set_header X-Real-IP  $remote_addr;
>    proxy_set_header Host $host;
>    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>    proxy_set_header Upgrade $http_upgrade;
>    proxy_set_header Connection $connection_upgrade;
>    proxy_pass http://app:8080;
>    }

**Comment by UchennaPrudensia** [comment]
You are right. It is working now. Thank you so much

**Comment by akrabat** [comment]
You’re welcome.
