### ISSUE TITLE
Routes behaving strangely in 3.9.2

### ISSUE THREAD

**Issue by cholthi** [slimphp/Slim#2371]
In my application root composer.json, I have slim/slim ^3.1, after few composer updates, my slim installation is now at 3.9.2. 
The problem now is routes in 3.9.2 appear to be cached by default, this is a little odd especially on development where you're changing routes rapidly and expect to see your changes. Even more odd is, the routes seem to be cached with their handlers because even after changing the route to point to a class method which originally was handled by a Closure, continue to point to Closure that doesn't exist anywhere in my routes now
THEN
`$app->post('/tests/create', function (Resquest $req, Response $res) {
});`
NOW
`$app->post('/tests/create', 'Class:method');`

I deleted the first route and replaced with the second, but strangely it still points to the first Closure which me make think that it is caching problem

**Comment by tflight** [comment]
Two possibilities come to mind. First, is a different route matching than the one you are expecting? Second, are you using OPcache in your webserver, and if so, what are the settings? OPcache could certainly produce those symptoms. Slim itself doesn't have any caching attributes that would explain what you see aside from [routercache](https://www.slimframework.com/docs/objects/application.html#slim-default-settings) which defaults to false if you don't set it up.

**Comment by cholthi** [comment]
I found it, the issue was php storm caching project files, so the changes
were not synced to the web server

**Comment by potievdev** [comment]
@akrabat This issue is not actual, You can close it.
