### ISSUE TITLE
How To Send Form Data To Slim App 

### ISSUE THREAD

**Issue by UchennaPrudensia** [slimphp/Slim#2372]
I am trying to collect user data from a form and passed it to slim app. The form action attribute is /authenticate. When the user clicks the login button, the url redirects to http://localhost/authenticate.

## Server File
```
 $slim->post('/authenticate', function(Request $req, Response $res) use ($provider): Response {
   $this->logger->addInfo("authentication");
   $username = $req->getParsedBodyParam('username');
   $password = $req->getParsedBodyParam('password');

      $data = $req->getParsedBody();
      $username = $data['username'];
      $password = $data['password'];

   if(!$username || !$password)
   {
     return $res->withStatus(403);
   }

   if(!$username == 'uchenna' || !$password =='secret')
   {
    return  $res->withStatus(403);
   }

   $session = $provider->registerSession($username);
   return $res->withHeader('Set-Cookie', 'session=' . $session)->withRedirect('/');

   return $res->withRedirect('/');
});
```

## Router 
`$app->route('/authenticate', $adapter, ['*']);`

The issue is that http://localhost/authenticate remains blank and it does not redirect back to the home page. I tried refreshing the page and I get this error: 

> ## Method not allowed
> Method not allowed. Must be one of POST

This shows that the closure function works, and perharps its from my login page. Am I linking my login page to slim correctly? Thank you.

Please check below to see my project

[chat-web.zip](https://github.com/slimphp/Slim/files/1566096/chat-web.zip)

**Comment by piotr-cz** [comment]
Make sure you are sending request with proper `content-type` that may be auto-parsed by request, ie. `application/x-www-form-urlencoded`.

Also you in your example you are reading variables _$username_ and _$password_ two times.

**Comment by geggleto** [comment]
Please try opening this question on our discourse community. Github is not the place for asking for help of this type. Thanks.
