### ISSUE TITLE
Changing status without effect

### ISSUE THREAD

**Issue by piernik** [slimphp/Slim#2376]
I manually change my status but it's not changed in response. If it matters I'm using phpdi slim bridge: http://php-di.org/doc/frameworks/slim.html

Here is my sample code:
```
$app->get('/test/406', function (Response $response) {
    return $response
        ->withStatus(406, 'direct')
        ->withJson(['status' => 406]);
});
```

As You can see on https://api.infirma.pl/2.6.0/test/406 status isn't changed. Always status is 200

Also tried with 202 - the same: https://api.infirma.pl/2.6.0/test/202

**Edit:**
I looked in old version and it works
```
$app->get("/test/406", function () use ($app, $infirma) {
    echo json_encode(['asas'=>'asa']);
    $app->response()->status(406);
});
```

https://api.infirma.pl/2.5.1/test/406 - displays with good response code.

If I strip json in new version I also get 200 status code:
```
return $response
        ->withStatus(406, 'direct');
```

**Edit 2:**
I think it's connected with https://github.com/slimphp/Slim/issues/2377

**Comment by RyanNerd** [comment]
I am unable to duplicate your issue. I am using PHP 7.1.12 and suspect that the issue you are having may be in your web server configuration and not within Slim itself.  [Tarball of working test of your sample code (including using DI Slim Bridge v1.1)](https://github.com/slimphp/Slim/files/1593664/testing.tar.gz)

Run `php -S localhost:8082`
Postman GET request returns expected results (status 406 direct):
![image](https://user-images.githubusercontent.com/10543911/34444215-ac5cc932-ec89-11e7-9bf1-1e8b65dffa8c.png)

**Comment by akrabat** [comment]
Which version of Slim 3 are you using?

**Comment by RyanNerd** [comment]
@akrabat if you are asking me it appears to be Slim 3.9.2. Running `composer require php-di/slim-bridge` output:

```
Using version ^1.1 for php-di/slim-bridge
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 10 installs, 0 updates, 0 removals
  - Installing psr/container (1.0.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing nikic/fast-route (v1.2.0): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing pimple/pimple (v3.2.2): Loading from cache
  - Installing slim/slim (3.9.2): Loading from cache
  - Installing php-di/invoker (1.3.3): Loading from cache
  - Installing php-di/phpdoc-reader (2.0.1): Loading from cache
  - Installing php-di/php-di (5.4.6): Loading from cache
  - Installing php-di/slim-bridge (1.1.2): Loading from cache
php-di/php-di suggests installing doctrine/cache (Install it if you want to use the cache (version ~1.4))
php-di/php-di suggests installing doctrine/annotations (Install it if you want to use annotations (version ~1.2))
php-di/php-di suggests installing ocramius/proxy-manager (Install it if you want to use lazy injection (version ~1.0 or ~2.0))
Writing lock file
Generating autoload files
```

**Comment by piernik** [comment]
I'm using slim 3.8.1.
As I posted in edit I think it's related to https://github.com/slimphp/Slim/issues/2377
I'm trying to isolate it...

**Edit:**
I've updated to 3.9.2. It's isolated. I'll continue issue in  https://github.com/slimphp/Slim/issues/2377
