### ISSUE TITLE
Changing Uri works but very wierd

### ISSUE THREAD

**Issue by piernik** [slimphp/Slim#2377]
I have adresses with version number like `https://api.infirma.pl/2.6.0/version`.
I have middleware that strips that version number:
```
$app->add(function (Request $request, Response $response, callable $next) {
    $uri = $request->getUri();
    $path = $uri->getPath();
    $version = file_get_contents(__DIR__ . '/../../VERSION.md');
    if (substr($path, 0, strlen($version) + 1) === '/' . $version) {
        $uri = $uri->withPath(substr($path, strlen($version) + 1));

//        echo ' ';

        return $next($request->withUri($uri), $response);
    }

    return $next($request, $response);
});
```

With `echo ' ';` code works. But when I comment it in request stops at 'OPTION' method.
I have no idea  how to fix it.

**Comment by akrabat** [comment]
Can you create a small working project that shows the problem please?

**Comment by piernik** [comment]
Ok. I updated slim library to `3.9.2`. And now it is even worse. I always get Option phase.

 I've created github project: https://github.com/piernik/slimError

Here is my frontend: https://alpha.infirma.pl/auth/login/
There are two buttons: `Fetch from dummy source` which leads to https://api.infirma.pl/2.6.0/dummy/backend. I get `Options failed` error.
But fetching in it browser url works: https://api.infirma.pl/2.6.0/dummy/backend.

I don't think it's CORS issue.

**Comment by tuupola** [comment]
FWIW:

```
$ curl --include --insecure --request OPTIONS  --header "Origin:  https://alpha.infirma.pl" https://api.infirma.pl/2.6.0/dummy/backend

HTTP/1.1 200 OK
Date: Tue, 02 Jan 2018 10:17:50 GMT
Content-Type: text/plain;charset=UTF-8
Content-Length: 20
Connection: keep-alive
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: *
Allow: GET
Server: IdeaWebServer/v0.80

curl: (18) transfer closed with 20 bytes remaining to read
```

**Comment by piernik** [comment]
I don't know what to do with that info :)

**Comment by mathmarques** [comment]
@piernik ``curl: (18) transfer closed with 20 bytes remaining to read`` probably means that your application is sending the wrong Content-Length which will cause error on requests.
Try change the [Slim's setting](https://www.slimframework.com/docs/objects/application.html#application-configuration) `addContentLengthHeader` to false.

**Comment by piernik** [comment]
wow `addContentLengthHeader` solved problem for me. 
Thank You very much. Happy New Year ;)
