### ISSUE TITLE
getQueryParams() and duplicate fields

### ISSUE THREAD

**Issue by kdubuc** [slimphp/Slim#2378]
If multiple fields of the same name exist in a query string, getQueryParams() silently overwrites them (because of parse_str()) :

```
GET /api/users?id=1&id=2
```
Give this array :
```php
[
  "id" => "2"
]
```

The first id is missing.

A patch to handle this case can be interesting ? (for 3.X and 4.x because slim-http contains the same code) ?

EDIT : Oh, and best wishes to all for 2018 ! 🎄

**Comment by akrabat** [comment]
As I recall, In PHP, the way that multiple parameters of the same name are expected to be handled is like this: `GET /api/users?id[]=1&id[]=2`

What do other PSR-7 libraries do with `GET /api/users?id=1&id=2` as we should probably try and match in Slim-Http?

**Comment by tuupola** [comment]
Default PHP way for this is this. 

```
GET /api/users?id[]=1&id[]=2
```

I do agree your example would be cleaner. Personally I use something like following.

```
GET /api/users?id=1,2,3
```

**Comment by kdubuc** [comment]
So, the query string should be _normalized_ to be handled correctly by getQueryParams()

```GET /api/users?id=1,2,3 (or id=1&id=2, or whatever)``` ➡️  ```GET /api/users?id[]=1&id[]=2```

The normalization can be happen in Slim\Http\Ur: createFromEnvironment ?

**Comment by akrabat** [comment]
I think that the expected result is for the second `id` to overwrite the first.

Create a PHP script containing:

```php
<?php
echo "<pre>";
var_dump($_GET);
```

Run it using `php  -S 0.0.0.0:8888 test.php` and then navigate to http://localhost:8888/?id=1&id=2 and you'll see:

```
array (size=1)
  'id' => string '2' (length=1)
```

Doing anything different would be confusing.

**Comment by tuupola** [comment]
Slim does the  least surprising thing, ie. behaves the same way as vanilla PHP.  If developer wishes to implement some different behavior a middleware would be perfect place to do it.

**Comment by kdubuc** [comment]
Indeed, cool idea, like ```Middleware\UriNormalizer```. Thanks all !
