### ISSUE TITLE
use Response object for onion

### ISSUE THREAD

**Issue by KampfCaspar** [slimphp/Slim#238]
Hi!

By switching to the onion model, it seems, you left the response object model...

Rather than returning the triplet status,headers,body and then handling communication in the main class, I suggest:
a) sending a Response object 'down the onion', which encapsulates all of the above (and optionally more, like logging)
b) letting the response object handle client communication (like cgi vs. apachemod vs. fcgi vs. cli)

HP

**Comment by codeguy** [comment]
This partly answers my previous question on your other pull request. This would provide a common interface to all responses, in and out of the onion. However, I believe we would need to stub the `write()` and `body()` methods on `Slim_Http_Stream`, correct? This is likely the only way to ensure a common interface so middleware layers do not need to run conditionals to detect a string response vs. a stream response.

**Comment by KampfCaspar** [comment]
Probably Slim_Http_Stream could be incorporated into Slim_Http_Response? The whole 'response logic' should be the same, whether it prints a string directly or delegates the printing to some helper object.

Now, whether to encapsulate strings into their own helper object? That's probably not necessary... middleware should not inspect the 'helper output' anyway, as this output may be very large or only gettable once. As for the API of the response object, I think it would be sufficient to expose both string (maybe empty) and the helper object (which may be inspected but not read).

**Comment by codeguy** [comment]
One thing I like about currently returning the triplet [status, header body] from each onion layer is that each layer may completely re-construct and/or return a fresh response rather than modify one master response object. In my opinion, this adds a lot of helpful flexibility to middleware.

That being said, we could return an instance of `Slim_Http_Response` rather than the triplet... this creates a more tightly coupled system, but provides the benefit of a more encapsulated response.

**Comment by KampfCaspar** [comment]
I don't follow... Logically, replacing a value in a triplet and e.g. calling setStatusCode() is the same. Middleware can completely meddle with the result as it wants. But as there can logically be only one response a single instance should suffice.

**Comment by codeguy** [comment]
This is done and available in the develop and release-1.6.0 branches.  You can read about the final middleware implementation at http://www.slimframework.com/documentation/develop#middleware. Each middleware layer, and the Slim application itself, all reference the same objects.
