### ISSUE TITLE
Static routing with `pathFor()`

### ISSUE THREAD

**Issue by xymz** [slimphp/Slim#2381]
(First, sorry for my poor English.)

Recently I faced a tiny problem. I want to build URI/URL with my static assets, like below codes.

```php
$container->router->pathFor('static', ['path' => 'a.css'], ['absolute' => true])
```

But, there is no way to do(without overriding/customizing default `Router`). Once I used [Flask](http://flask.pocoo.org/docs/0.12/api/#flask.url_for), there is a function for routing `url_for()` supports static routing. And I thought both have same concept for url routing.

Is there any plan for support static routing in `pathFor()`? (And thanks for your patience :smile: )

**Comment by geggleto** [comment]
Not currently no, but we are open to PRs :)

**Comment by xymz** [comment]
Thanks! And, do you feel the pseudo code follows your design policy?

**Comment by silentworks** [comment]
Yes this would be a helpful feature.

**Comment by akrabat** [comment]
I'm unclear what is being asked for here.

**Comment by akrabat** [comment]
This may be related to https://github.com/slimphp/Slim/pull/2493 ?

**Comment by akrabat** [comment]
Closing as there's been no movement on this one and I'm unclear what is being asked for.

Please create a new issue with detailed information if necessary.
