### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by mrceperka** [slimphp/Slim#2382]
Hi,
I am doing some kind of proxy with **Slim**.

I was hoping, **that I can process request with the app**, but unfortunately I am always **getting 404** and only way I've managed this **to work was with Guzzle**. I do not like solution with guzzle, because it creates an additional request to the server.

Do you have any idea, why this approach does not work?

- Should I create a whole new request and not just replacing URI, which is used for routing?

```php
<?php declare(strict_types = 1);
class ApiProxy
{
        //....
	public function __invoke(Request $request, Response $response)
	{
		$uriString = $request->getQueryParam('uri');
		if ($uriString === null) {
			return $response->withErrorJson(['uri_required' => 'uri param missing in query']);
		}
		
		try {
			
			$cred = new OAuth2ClientCredentials($this->clientId, $this->clientSecret);
			$ssoResponse = $this->ssoClient->obtainOAuth2Token($cred);
			if ($ssoResponse->getStatusCode() === 200) {
				$uri = Uri::createFromString($uriString);
				$uriRequest = $request->withUri($uri);

				// IMPORTANT PART IS HERE
				// this is what I want but it does not work
                                // this gives me always 404
				return $this->app->process($uriRequest, $response);
			}
			
			return $response->withStatus(403);
		} catch (\InvalidArgumentException $e) {
			return $response->withErrorJson(['uri_error' => $e->getMessage()]);
		}
		
		return $response->withStatus(500);
	}
}

```

**Comment by akrabat** [comment]
if you're getting a 404 error, then process() is failing to route to the URI.

Consider tracing through and finding out why.

**Comment by mrceperka** [comment]
Will close this, because I am ok with guzzle solution. I won't do tracing now.
