### ISSUE TITLE
Case insensitive routes v3

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [slimphp/Slim#2383]
Hi guys.
I completely read #1449 this issue and test ideas but does not work for me.
I need case insensitive route but does not change place holders parameters.
I try to strtolower uri but it changes place holders value and its not good!
Anyone can help me?!

**Comment by geggleto** [comment]
Strictly speaking... This stack-overflow response is appropriate.

https://stackoverflow.com/questions/15641694/are-uris-case-insensitive

It should also be noted that different web-servers treat URIs differently.

You could accomplish this by modifying the super globals before the Slim app has been run. Ofc that means you are going to need to build your own URI Parser as you stated you don't want the route Parameters modified.

**Comment by AmirHosseinKarimi** [comment]
This mean no way to fix this?

**Comment by geggleto** [comment]
I mentioned a workaround in my last comment.

Furthermore, we use FastRoute for route parsing and do not maintain that package. Any change required to the router would need to be made in the upstream package. There could be additional settings in Fastroute that would enable the features you want; I however am not an expert and you should inquire there to find out ( https://github.com/nikic/FastRoute )

**Comment by adjenks** [comment]
@AmirHosseinKarimi and those interested, change the environment in the container like so:

```
,'environment' => function(ContainerInterface $c){

	$env = $_SERVER; // The super duper environment global.
	$env['REQUEST_URI'] = strtolower($env['REQUEST_URI']);

	return \Slim\Http\Environment::mock($env);

}
```

More info: https://github.com/nikic/FastRoute/issues/175

**Comment by adjenks** [comment]
https://github.com/nikic/FastRoute/issues/175#issuecomment-433980751

**Comment by odan** [comment]
Is the `environment` container entry still available in Slim 4?

**Comment by adrhumphreys** [comment]
If anyone stumbles across this you can achieve it with middleware by creating the following class:
```
<?php
declare(strict_types = 1);

namespace App;

use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

class Lowercase implements MiddlewareInterface
{
    /**
     * @var ResponseFactoryInterface
     */
    private $responseFactory;

    /*
     * Whether returns a 301 response to the new path.
     */
    public function redirect(ResponseFactoryInterface $responseFactory): self
    {
        $this->responseFactory = $responseFactory;

        return $this;
    }

    /*
     * Process a request and return a response.
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $uri = $request->getUri();
        $path = strtolower($uri->getPath());

        if ($this->responseFactory && ($uri->getPath() !== $path)) {
            return $this->responseFactory->createResponse(301)
                ->withHeader('Location', (string) $uri->withPath($path));
        }

        return $handler->handle($request->withUri($uri->withPath($path)));
    }
}
```
And then adding it through:
```
$app->add(new Lowercase());
```
