### ISSUE TITLE
Unexpected: 404 Not Found response does not trigger notFoundHandler

### ISSUE THREAD

**Issue by garnold** [slimphp/Slim#2390]
Hello,

I incorrectly assumed that returning `$response->withStatus(404)` from our controllers would trigger our configured `notFoundHandler`, but that doesn't appear to be the case. Should we instead be throwing `NotFoundException` from our controllers?

Thanks,
Geoff.

**Comment by geggleto** [comment]
Yes if you wish the not found handler to be used.

return a 404 is valid since if you are writing a REST API; you can simply return 404 with empty body and that's perfectly fine.

**Comment by garnold** [comment]
Thanks for confirming, @geggleto 

I get what you're saying with REST APIs but the default `notFoundHandler` also handles `application/json` requests so this can cause inconsistencies in REST APIs (Slim will return a certain 404 message when the route doesn't exist, while controllers will return a different 404 message).

**Comment by geggleto** [comment]
Closing this as resolved
