### ISSUE TITLE
Slim always removes port from Host: header

### ISSUE THREAD

**Issue by garnold** [slimphp/Slim#2391]
It appears that Slim is always overwriting the `Host:` header and dropping the port. [I believe the `||` should be an `&&` here](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L200).

**Comment by geggleto** [comment]
Hmm. I actually can't think of a reason why the first condition of that if would ever be false.

**Comment by garnold** [comment]
@geggleto Right, but it's an `||`. The first condition is likely to be `false`, but the second condition is likely to be `true`.
