### ISSUE TITLE
getBaseUrl returns the wrong port when using ngrok

### ISSUE THREAD

**Issue by jamiemtdwyer** [slimphp/Slim#2394]
I'm building an example application that interfaces with an OAuth Provider (in this case, Shopify).

The `redirect_uri` must be passed in to the external service as an absolute URL, so I am using the following code to accomplish this:

```
$baseUrl = $request->getUri()->getBaseUrl();
$redirectUri = $baseUrl . $this->router->pathFor('oAuthCallback');
$installUrl = "https://{$shop}/admin/oauth/authorize?client_id={$apiKey}&scope={$scope}&redirect_uri={$redirectUri}";
```

where `oAuthCallback` is the name of my OAuth callback route that the user should be redirected to after authorizing the application.

This works fine except when using a tunnelling service (ngrok), in which case `getBaseUrl` returns `http://b6008d35.ngrok.io:8000`. My PHP server is running locally on port 8000, but the tunnelling service is running on port 80. I would expect that `getBaseUrl` would return `http://b6008d35.ngrok.io:80` or better yet, simply `http://b6008d35.ngrok.io`.

I'm trying to avoid the need for hard coding the expected path in an environment variable, but at this point it seems inevitable.

**Comment by mahagr** [comment]
I think you can modify the URL by `$uri->withPort(null)`.

**Comment by geggleto** [comment]
Our Request objects pull from data provided from the PHP super globals... if php is being run at port 8000 then that's what we will have.

**Comment by geggleto** [comment]
Closing this as it's a php-ism.
