### ISSUE TITLE
defaultNotFound

### ISSUE THREAD

**Issue by j4mie** [slimphp/Slim#24]
The default 404 handler does not work in Google Chrome. According to [this link](http://perso.hirlimann.net/~ludo/blog/archives/2008/09/chrome-and-404s.html), 404 pages must be at least 512 bytes long for Chrome to display them.

Also, the default 404 is a bit ugly. Why don't we generalise the generateErrorMarkup method to display any type of error, including 404s? We could (for example) show the routes matched, in order. We could pad the content with &nbsp; to ensure it reaches 513 bytes.

**Comment by codeguy** [comment]
This is fixed.
