### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by panczypani** [slimphp/Slim#240]
I suggest add support for layout/templates. See at http://stackoverflow.com/questions/7017755/sub-views-layouts-templates-in-slim-php-framework . I suggest opt-out disable layout for ajax.

```
public static function set_layout($layout=NULL,$in_ajax=false)
{
if(!Slim::getInstance()->request()->isAjax() || $in_ajax){ //Disable layout in Ajax
        self::$_layout = $layout;
};
}
```

**Comment by codeguy** [comment]
This is best delegated to custom Views. You can learn more about custom Views with Slim at http://www.slimframework.com/documentation/stable#views. You can see a bunch of available custom Views in the `Slim_Extras` repo at https://github.com/codeguy/Slim-Extras.

Best,
Josh
