### ISSUE TITLE
GetHeaders and GetHeader have a different result

### ISSUE THREAD

**Issue by sridesmet** [slimphp/Slim#2400]
With custom headers, if you do:
`$request->getHeaders()` resulting in headers like HTTP_X_APIKEY
and 
`$request->getHeader($name)` resulting in X_APIKEY

getHeaders() should rewrite the header key also. The current getHeaders could be renamed to getRawHeaders()

**Comment by akrabat** [comment]
I thought this was handled by https://github.com/slimphp/Slim-Http/blob/master/src/Headers.php#L54.

Maybe not though.

**Comment by sridesmet** [comment]
Yep, that's where the magic happens. But the all() function in Headers, uses the original keys:
https://github.com/slimphp/Slim-Http/blob/master/src/Headers.php#L100

**Comment by jdrieghe** [comment]
According to PSR-7, `getHeaders()` _MUST_ preserve the original case. 

> Despite that headers may be retrieved case-insensitively, the original case
> MUST be preserved by the implementation, in particular when retrieved with
> getHeaders().

However, the spec doesn't state we should preserve the `HTTP_` prefix.
That said, the following section makes me believe the philosophy of the spec is to preserve whatever the user intended.

> Non-conforming HTTP applications may depend on a certain case, so it is useful
> for a user to be able to dictate the case of the HTTP headers when creating a
> request or response.

I'm not sure if that means we should remove the `HTTP_` prefix though. I'll leave that to @akrabat :)

If it turns out we want to make changes here, feel free to shoot me a message and I'll create a PR.

**Comment by sridesmet** [comment]
It should preserve the original case, but it doesn't. e.g. 
I try to send header with name `A-a-a`,
`$request->getHeaders()` contains `HTTP_A_A_A`.  
php's `getallheaders()` contains `A-a-a` and so does `$request->getHeader('A-a-a')`

Even worse, when I try to send the header `A_a-a` (with a lower dash). 
The `$request->getHeaders()` does not contain the header at all. 
`$request->getHeader('A_a-a')` does, and `getallheaders()` does too.

So there are clear workarounds, but in my opinion getHeaders() and getHeader() should at least be consistent :)

**Comment by llvdl** [comment]
The headers are taken from the `$_SERVER` variable. As per the [CGI/1.1 specification](http://www.faqs.org/rfcs/rfc3875):

    Meta-variables with names beginning with "HTTP_" contain values read
    from the client request header fields, if the protocol used is HTTP.
    The HTTP header field name is converted to upper case, has all
    occurrences of "-" replaced with "_" and has "HTTP_" prepended to
    give the meta-variable name.

If I call a test script with curl and send the header A_a-a, it is stored in PHP in `$_SERVER` as:
```
Array(
    [HTTP_A_A_A] => test
)
```
`$request->getHeaders()` returns the header as PHP passes it through $_SERVER:
```
["HTTP_A_A_A"]=>
  array(1) {
    [0]=>
    string(4) "test"
  }
```

From what I gather, there is no original case to be retrieved. The headers in `$_SERVER` are already stored in uppercase before Slim starts. `getallheaders()` does seem to contain the headers in the original case, but I don't think that function is available on all web servers, e.g. Nginx.

Changing `$request->getHeaders()` to return the headers without the HTTP_ prefix looks like the right thing to do to me, but I it would break backwards compatibility for Slim 3. Perhaps fix this only for Slim 4?

**Comment by akrabat** [comment]
This is a Slim-Http issue, so I've raised https://github.com/slimphp/Slim-Http/issues/61 for it.
