### ISSUE TITLE
README.md has two broken links

### ISSUE THREAD

**Issue by RyanNerd** [slimphp/Slim#2401]
The pugx.org domain these stats are coming from may be down:

```
[![Total Downloads](https://poser.pugx.org/slim/slim/downloads)](https://packagist.org/packages/slim/slim)
[![License](https://poser.pugx.org/slim/slim/license)](https://packagist.org/packages/slim/slim)
```

**Comment by jdrieghe** [comment]
I think this works fine again? May have been a temporary hiccup:
![image](https://user-images.githubusercontent.com/12606789/36562311-e499c148-1816-11e8-8caa-f6bdda13fb05.png)

Can this issue be closed?

**Comment by RyanNerd** [comment]
@jdrieghe Looks like you are correct. Probably a hiccup. Closing.
