### ISSUE TITLE
[Questions] Slim 4

### ISSUE THREAD

**Issue by RyanNerd** [slimphp/Slim#2402]
1) Is the current 4.x branch in a _working_ state? (Can i create a simple hello world skeleton app and it will work?)
2) Is Slim 4 going to continue to use Pimple, or switching to PHP-DI, or dropping DI internally? (The reason I ask is that I use `php-di/slim-bridge` exclusively in all my projects that leverage Slim. I also have made contributions to `slim-bridge` and would like to _keep up_ with any changes that may be needed for 4.x.)
3) I've looked through issues marked as _Slim 4_, but haven't found any I feel qualified to help with. Are there any issues for 4.x that need attention but are not posted to issues that I could assist with?

**Comment by l0gicgate** [comment]
1. Yes the current 4.x branch is in a working state

2. Container has been replaced from `Pimple` to `PSR-11` Container and you can simply drop in your own container such as `PHP-DI` in there or any other `PSR-11` compatible containers. Simply use the `$app->setContainer($yourPSR11CompatibleContainer)` 

3. I suggest you join the Slack server [slimphp.slack.com](https://slimphp.slack.com) to discuss with the active community.

**Comment by akrabat** [comment]
Yes. I test bits and bobs with a simple Slim app that has this composer.json:

```
$ cat slim4x-testbed/composer.json
{
    "repositories": [
        {
            "type": "path",
            "url": "../Slim4x",
            "options": {
                "symlink": true
            }
        }
    ],
    "require": {
        "slim/slim": "4.x@dev"
    }
}
```

Where `../Slim4x` is a checkout of Slim on the `4.x` branch (most of the time, sometimes it's on a PR branch…)

**Comment by akrabat** [comment]
As @l0gicgate has noted, Slim 4 doesn't actually care which PSR-11 container you use. We'll probably ship the Skeleton with a default one though.

**Comment by RyanNerd** [comment]
Thanks @l0gicgate and @akrabat Very helpful. I'm closing this issue as you answered my questions.

**Comment by RyanNerd** [comment]
@l0gicgate Can I get an invite to Slack? It does not appear to be open to the public.
TIA

**Comment by l0gicgate** [comment]
@RyanNerd I'm sorry I forgot about the invitation process. Go to this [link](https://slimphp-slack-invite.herokuapp.com/) to join.
