### ISSUE TITLE
Custom Dispatcher Implementation for 3.x (work around)

### ISSUE THREAD

**Issue by RyanNerd** [slimphp/Slim#2406]
See #2399 and #2405 
The [PR that targets 4.x](https://github.com/slimphp/Slim/pull/2405) has been created. 
In Slack and discussed in #2399 there is __work-around__ proposed by @akrabat to include the new Custom Dispatcher in 3.x without introducing breaking changes. 
I've created this issue in assuming that PR #2405 will be merged that the _work-around_ for 3.x stays on the radar since #2399 has been closed.

**Comment by l0gicgate** [comment]
After further review the custom dispatcher can't be implemented into 3.x without BC changes. Closing this as wont implement.
