### ISSUE TITLE
ReactPHP compatibility: Optional route argument persistence

### ISSUE THREAD

**Issue by fiskWasTaken** [slimphp/Slim#2418]
Hi,

I've been busy migrating a Slim application to PHP-PM, and although it appears to work on the surface, there appears to be a bug with the persistence of optional route arguments, i.e. if a route of `/hello/{name}[/{optional}]` is accessed twice, with the second request omitting the `optional` argument, it will still pass the optional argument from the first request. This is because the `arguments` property of the Route is never reset between requests.

I made a fix for it, which was simple as erasing existing arguments in `Route->prepare()`, but when I wrote a unit test to confirm my fix, I ran phpunit to discover three failing tests. These are all related to setArgument() calls:

* Slim\Tests\AppTest::testInvokeWithMatchingRouteWithNamedParameterOverwritesSetArgument
* Slim\Tests\AppTest::testInvokeWithMatchingRouteWithSetArguments
* Slim\Tests\AppTest::testInvokeWithMatchingRouteWithSetArgument

I've not come across this function before, but I'm at an impasse since I'm not sure how to fix this without breaking these tests or adding unnecessary complexity to the Route class. Any ideas?

**Comment by geggleto** [comment]
I don't know what you are expecting from us, but we will gladly take a look at a PR to solve this problem.

**Comment by mathmarques** [comment]
This is the same as #2430 , and #2431 should fix it and keep `setArgument` working.

**Comment by designermonkey** [comment]
As two PRs have been addressed for the same concern, I'm going to close this issue. If you think this is in error, please say so, and it can be discussed further.
