### ISSUE TITLE
Stream using fopen from AWS S3 bucket returning file not found.

### ISSUE THREAD

**Issue by J-Kelley** [slimphp/Slim#2419]
Attempting to download files from an AWS S3 bucket to the user in Slim3 using the following code:
```
 $s3Path = 's3://mybucket/' . $file['path'] . $file['storedfile'];

 if (file_exists($s3Path) == false) {
     echo 'File does not exist.';
 }

 try {
    $fh = fopen($s3Path, 'r');
 }
 catch (Aws\S3\Exception\S3Exception $e) {
    echo "There was an error downloading the file. " . $e->getMessage() . "\n";
 }

 #$fh = fopen($file['path'] . $file['storedfile'], 'r');
 $basename = $file['alternative'] === 'file' ? 'file' : $file['name'];
 $this->sitelog->logAction('downloaded an attached file', 'downloaded "' . $basename . "'");
 $stream = new \Slim\Http\Stream($fh);

 return $response
     ->withHeader('Content-Type', 'application/force-download')
     ->withHeader('Content-Type', 'application/octet-stream')
     ->withHeader('Content-Type', 'application/download')
     ->withHeader('Content-Description', 'File Transfer')
     ->withHeader('Content-Transfer-Encoding', 'binary')
     ->withHeader('Content-Disposition', 'attachment; filename="' . basename($file['name']) . '"')
     ->withHeader('Expires', '0')
     ->withHeader('Cache-Control', 'must-revalidate, post-check=0, pre-check=0')
     ->withHeader('Pragma', 'public')
     ->withBody($stream);
```

This returns the following error: File not found

Firefox can’t find the file at http://mydomain/attachments/1491/657833117/groupID/download.

-Standard context returns that error.

-Seekable context returns an empty file.

-Using fread on the stream followed by an exit (instead of the withBody response) outputs the file correctly but means I can't send a proper response.

-Opening the file with an s3 GET object works correctly, but means I have to load the whole file into memory.

**Comment by geggleto** [comment]
I would not recommend doing this. Please try to use FlySystem https://flysystem.thephpleague.com/docs/adapter/aws-s3/ 

> Opening the file with an s3 GET object works correctly, but means I have to load the whole file into memory.

Yes. That is what you will need to do. Slim supports Chunked output, however it still requires the entire object to be in memory. If you want a proper stream solution, you will need to look into another framework.
