### ISSUE TITLE
Request headers not present on $request->getHeaders()

### ISSUE THREAD

**Issue by dmelo** [slimphp/Slim#2420]
I'm using Slim 2.9.2, and it seems to be neglecting custom request headers I have set on apache virtualhost configuration. My apache virtualhost configuration have the following settings:

```
        RequestHeader set SSL_CLIENT_S_DN    "a"
        RequestHeader set SSL_CLIENT_I_DN    "a"
        RequestHeader set SSL_SERVER_S_DN_OU "a"
        RequestHeader set SSL_CLIENT_VERIFY  "a"
        RequestHeader set SSL_CLIENT_S_DN_CN  "a"
        RequestHeader set HTTP_TEST1 "1"
        RequestHeader set X_TEST2 "2"
        RequestHeader set X_HTTP_TEST2 "2"
```

Inside the method handling the request, I have the following:

```php
	$response->write(print_r($request->getHeaders(), true));
	$response->write(print_r(apache_request_headers(), true));
	return $response;
```

When I curl the server (with `curl -H 'CURLHEADER: CURLSVALUE' http://localhost:8003/ping/a/b`), I get the following response:

```
Array
(
    [Host] => Array
        (
            [0] => localhost
        )

    [HTTP_USER_AGENT] => Array
        (
            [0] => curl/7.53.1
        )

    [HTTP_CURLHEADER] => Array
        (
            [0] => CURLSVALUE
        )
)
Array
(
    [Host] => localhost:8003
    [User-Agent] => curl/7.53.1
    [CURLHEADER] => CURLSVALUE
    [SSL_CLIENT_S_DN] => a
    [SSL_CLIENT_I_DN] => a
    [SSL_SERVER_S_DN_OU] => a
    [SSL_CLIENT_VERIFY] => a
    [SSL_CLIENT_S_DN_CN] => a
    [HTTP_TEST1] => 1
    [X_TEST2] => 2
    [X_HTTP_TEST2] => 2
)
```

The first array shows the headers from `$request->getHeaders()`. It has the header I have set while calling curl but it is missing all custom headers I have set on apache. All the headers are present on `apache_request_headers()`, which means apache is indeed setting does headers.

Why is Slim not showing/processing my custom headers? Am I doing something wrong? How can I make it work?

**Comment by geggleto** [comment]
You will need to add them to the request object via a middleware. Slim 2 never had this kinda support iirc.

**Comment by dmelo** [comment]
Thank you for clarifying.
