### ISSUE TITLE
Error handling with "application/json" not working

### ISSUE THREAD

**Issue by odan** [slimphp/Slim#2424]
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* Slim Version: 3 (latest)
* Platform and Target: All

### What you did
I try to make a Ajax call with Json payload. 
The request header `Accept` is set to `application/json; charset=utf-8`.

The PHP application throws an exception. For example: `throw new RuntimeException('error');`

### What happened
The response is a Slim standard HTML error page (Content-Type: `text/html`)

### What you expected to happen
The response Content-Type: `application/json` or `application/json; charset=utf-8`
and a Json payload with a `message` and `error` element.

### What you've already tried

* Set the request header `Accept` to `application/json+json; charset=utf-8`.
  * It works, but it's not the correct (and standard) content type.
* I found this [Issue 1781](https://github.com/slimphp/Slim/pull/1781)
  * Problem: The suffixes syntax in RFC 6839 doesn't work for `application/json`.
* I checked the source code of slim and found the "Bug" [here](https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/AbstractHandler.php#L50)

### Do you want to address this issue?

Yes, I could do a PR.

**Comment by crtl** [comment]
You have to register your own error handler as stated in the [documentation for System Error Handler](https://www.slimframework.com/docs/v3/handlers/error.html)

**Comment by odan** [comment]
@crtl Slim is often used for RESTful APIs and the default data type is JSON `application/json`. Why wouldn't Slim support that by default? A change (to the regex) would be minimal and very useful.

**Comment by akrabat** [comment]
The `Content-Type` header indicates the format of the data you are sending, not the format of the data that you expect to receive as that's the purview of the `Accept` header.

If you set your `Accept` header to `application/json` then you'll find that Slim sends you errors in JSON format.

**Comment by odan** [comment]
@akrabat Sorry, my mistake. I'm using the `Accept` header and not the `Content-Type`. I just updated my first question.

**Comment by akrabat** [comment]
Given this Slim application:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$config = [
    'settings' => [
        'displayErrorDetails' => true, // set to false in production
        'addContentLengthHeader' => false, // Allow the web server to send the content-length header
    ],
];
$app = new \Slim\App($config);

$app->get("/", function ($request, $response, $args) {

    throw new RuntimeException('error');

    return $response;
});

// Run!
$app->run();
```

Then this curl call returns JSON:

```
$ curl -i -H "Accept: application/json" http://localhost:8888/
HTTP/1.1 500 Internal Server Error
Host: localhost:8888
Date: Mon, 09 Apr 2018 12:09:51 +0000
Connection: close
X-Powered-By: PHP/7.1.12
Content-type: application/json

{
    "message": "Slim Application Error",
    "exception": [
        {
            "type": "RuntimeException",
            "code": 0,
            "message": "error",
            "file": "\/Users\/rob\/tmp\/test-slim\/public\/index.php",
            "line": 30,
            "trace": [
                "#0 [internal function]: Closure->{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#1 \/Users\/rob\/tmp\/test-slim\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#2 \/Users\/rob\/tmp\/test-slim\/vendor\/slim\/slim\/Slim\/Route.php(335): Slim\\Handlers\\Strategies\\RequestResponse->__invoke(Object(Closure), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#3 \/Users\/rob\/tmp\/test-slim\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(117): Slim\\Route->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#4 \/Users\/rob\/tmp\/test-slim\/vendor\/slim\/slim\/Slim\/Route.php(313): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#5 \/Users\/rob\/tmp\/test-slim\/vendor\/slim\/slim\/Slim\/App.php(495): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#6 \/Users\/rob\/tmp\/test-slim\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(117): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#7 \/Users\/rob\/tmp\/test-slim\/vendor\/slim\/slim\/Slim\/App.php(388): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#8 \/Users\/rob\/tmp\/test-slim\/vendor\/slim\/slim\/Slim\/App.php(296): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
                "#9 \/Users\/rob\/tmp\/test-slim\/public\/index.php(36): Slim\\App->run()",
                "#10 {main}"
            ]
        }
    ]
}
```

i.e. Slim is working as expected. It sends JSON if your `Accept` header is `application/json`

**Comment by odan** [comment]
Thanks @akrabat The problem was caused by another request for a not existing `bootstrap.min.js.map` file (error 404). Unfortunately, the Google Chrome Developer Toolbar does not display such requests.

**Comment by akrabat** [comment]
@odan I'm glad you found it!
