### ISSUE TITLE
multipart/form-data with PATCH method

### ISSUE THREAD

**Issue by caom92** [slimphp/Slim#2427]
I'm trying to write a RESTful API for my application but just found out that sending a `PATCH` request with `Content-Type: multipart/form-data` and then trying to retrieve it with `request->getParsedBody()` always return `NULL`. After doing some research, I've found out that this could be because PHP only parses form-data for `POST` requests and for both `PUT` and `PATCH` requests it only parses `application/x-www-form-urlencoded` data. However, you can't send binary data (like an uploaded file) with `application/x-www-form-urlencoded`. Is there currently any way to retrieve the form-data sent in a `PUT` and `PATCH` request using Slim PHP?

**Comment by akrabat** [comment]
I think you can parse the output of `getBody()` yourself.

**Comment by caom92** [comment]
That's what I thought, I believe this should be managed by the framework, though, and not by the programmer.

**Comment by geggleto** [comment]
@caom92 we don't support this type out of the box, feel free to PR a new media parser for our request object.

**Comment by designermonkey** [comment]
I agree with @geggleto so I'm closing this issue. If a PR is sent, or any other info can be added, it can be reopened.
