### ISSUE TITLE
Reset Route's attributes on prepare()

### ISSUE THREAD

**Issue by joke2k** [slimphp/Slim#2430]
I'm writing some functional tests and I noticed that if I call twice a route like that:
`/view[/{code:[\w-]+}]`

`Route::prapare()` method doesn't clean `Route::attributes`.
Then if the first call has `code` attribute (`/view/hello-world`), `prepare()` method set it in `attributes` field.
If the second call doesn't have `code` attribute (`/view`) when `App` call `Route::prepare()` method with empty `$arguments`, the `code` still remain `hello-world`, breaking my request handler.

Maybe in `Route::prepare()` we could reset its attributes?

**Comment by carc1n0gen** [comment]
Are you reinstanciating the app for each call? I ask because that's what would happen in a real world scenario, every single request instanciates the app.

**Comment by mathmarques** [comment]
This is actually a bug. There are cases where we could have to dispatch more than one request on a singles instance. That's one of the reasons the `App::process` was created. See https://github.com/slimphp/Slim/pull/1688.

**Comment by joke2k** [comment]
> Are you reinstanciating the app for each call?

No, actually I create one instance of App in setUp, but for a functional test I do more then one request with this app instance:
```
public function setUp()
    {
        $this->app = (new App())->get();
    }

protected function createRequest($method = 'GET', $url = '/', $data = [], $envs = [])
    {
        $method = strtoupper($method);
        $env = [
            'REQUEST_METHOD' => $method,
            'REQUEST_URI'    => $url
        ];
        if (in_array($method, ['POST', 'PUT'])) {
            $env['CONTENT_TYPE'] = 'application/x-www-form-urlencoded';
        }
        $env = Environment::mock(array_merge($env, $envs));
        $request = Request::createFromEnvironment($env);
        if ($method === 'GET') {
            $request = $request->withQueryParams($data);
        } else {
            $request = $request->withParsedBody($data);
        }
        if ($this->xhr) {
            $request = $request->withHeader('X-Requested-With', 'XMLHttpRequest');
        }
        return $request;
    }
```
then I execute it with:

```
protected function executeRequest(RequestInterface $request)
    {
        $container = $this->app->container();
        $headers = new Headers(['Content-Type' => 'text/html; charset=UTF-8']);
        $response = new Response(200, $headers);

        $container['response'] = $response->withProtocolVersion($container->get('settings')['httpVersion']);
        $container['request'] = $request;
        return $this->app->run(true);
    }
```

Everything works except those cached route's attributes.

>  I ask because that's what would happen in a real world scenario, every single request instanciates the app.

It makes sense obviously, but it's more simple if we could do more then one request.

**Comment by carc1n0gen** [comment]
@joke2k  Because of the lifecycle of any php app, you're going to need to reinstanciate the app before the seconds, third, etc. request.  I had to something similar when testing an app of my own.

php in invoked, the app is created, the request is processed, the response is sent, and then php quits, which makes all the state stuff - parameters, headers, cookies disappear.  The next request starts it all over again.  The only way to emulate that with a unit test (since you're invoking multiple requests in a single unit test) is to reinstanciate the app before another request

Here is my test with just the important parts

```php
<?php

namespace Tests\Feature;

use Tests\TestCase;
use Slim\Http\Environment;

class UnshortenALinkTest extends TestCase
{
    protected $app;

    public function setUp()
    {
        $this->app = $this->createApplication();
    }

    public function testThatItRedirectsWhenAShortlinkExists()
    {
        // Setup the mock environment
        ...

        // Run the app
        $response = $this->app->run(true);
        
        // Make some assertions
        ...


        // This is the important part
        $this->app = $this->createApplication(); // re-init the app

        // Setup the mock environment again
        ...

        // Run the app again
        $response = $this->app->run(true);
        
        // Make some more assertions
        ...
    }
}
```

**Comment by mathmarques** [comment]
@carc1n0gen Not exactly, as I mentioned, see this use case: #1688

**Comment by carc1n0gen** [comment]
@mathmarques I don't believe that is this specific issue.  OP explained that he is indeed executing `App::run` more than once.

**Comment by geggleto** [comment]
Slim wasn't really designed to be run more than once. We attempted to solve this with a few different feature flags.

The solution unfortunately is to regenerate a new App instance. 

This might be something we try to solve in v4.
