### ISSUE TITLE
Should Cookies->get also read from responseCookies?

### ISSUE THREAD

**Issue by carc1n0gen** [slimphp/Slim#2432]
I'm using `Slim\Http\Cookies` in my app like so:

Retrieve the cookies
```php
// Container.php
$container[Cookies::class] = function ($c) {
    return new Cookies($c->get('request')->getCookieParams());
};

$container[CookieMiddleware::class] = function ($c) {
    return new CookieMiddleware($c->get(Cookies::class));
};
```

Save the cookies
```php

// CookieMiddleware.php
class CookieMiddleware
{
    private $cookies;

    public function __construct(Cookies $cookies)
    {
        $this->cookies = $cookies;
    }

    public function __invoke($request, $response, $next)
    {
        $response = $next($request, $response);
        return $response->withHeader('Set-Cookie', $this->cookies->toHeaders());
    }
}
```

```php
// Bootstrap.php
$app->add(CookieMiddleware::class);
```

But when I use `$cookies->get('key)` in my app, I noticed it only reads from the internal `$requestCookies` array. While $cookies->set(...) only writes into the `$responseCookies` array. So any cookies I set along the way, cannot be ready until the next request.  Should we also read from `$responseCookies`? I'd happily make a PR

Let me know if I'm doing this all wrong or if this totally breaks PSR standards or something

**Comment by geggleto** [comment]
You aren't pulling in the correct cookie object.

This is different 
```
 return $response->withHeader('Set-Cookie', $this->cookies->toHeaders());
```

Than this
```
$cookies = $this->get(Cookies::class);
 return $response->withHeader('Set-Cookie', $cookies->toHeaders());
```

**Comment by carc1n0gen** [comment]
@geggleto Sorry, that was a typo on my part when converting my code into simpler snippets.  I've updated the question.  I inject `Cookies::class` in to the constructor of my middleware and store it in `$this->cookies`

**Comment by mathmarques** [comment]
The idea of set cookie, is to set them on response, not the request you received.
If you wanna know what cookies have you set, you will have to get with `toHeaders()`.
but if you wanna add something that you need to know further on app, you could use [`$request->withAttribute()`](https://www.slimframework.com/docs/v3/objects/request.html#attributes)

**Comment by carc1n0gen** [comment]
It would be nice to be able to read cookies that have been set so far later on in the chain (like in a twig extension for example), but I guess I'll take another approach as suggested, thanks.
