### ISSUE TITLE
http 500 with $container issue

### ISSUE THREAD

**Issue by incisakura** [slimphp/Slim#2436]
My current version is 5abbab0 on 4.x. I'm planing to update it to the lastest version. After I ran ```composer update```,it's updated to 83e069e and the web page is on http 500. Log is as follows.

    [root@sakura test]# php -S 0.0.0.0:8888 -t public public/index.php
    PHP 7.2.5 Development Server started at Fri May 11 00:00:00 2018
    Listening on http://0.0.0.0:8888
    Document root is /home/nginx/test/public
    Press Ctrl-C to quit.
    [Fri May 11 00:00:33 2018] PHP Fatal error:  Uncaught Error: Class 'Slim\Container' not found in 
    /home/nginx/test/config/routes.php:43
    Stack trace:
    #0 /home/nginx/test/public/index.php(11): require()
    #1 {main}
      thrown in /home/nginx/test/config/routes.php on line 43
 The Line 43 of routes.php is ```$container = new Container($configuration);```. I have tried to delete the line,and the web page can be accessable,but many functions in my site is down.
I also have tried to update it to 8315e84 which is the next version of my current version,the error is the same.

Could you give me some help?

**Comment by silentworks** [comment]
I wouldn't recommend you use 4.x branch, this branch is a WIP and breakage should be expected. The official stable branch is 3.x.

**Comment by akrabat** [comment]
Slim 4 doesn’t come with a container anymore, so you need to provide your own PSR-11 compatible one.

**Comment by incisakura** [comment]
I have switched to 3.x branch. It seems that all is ok. Thank for guys' reply.
