### ISSUE TITLE
It would be nice pass dependencies to controller constructor

### ISSUE THREAD

**Issue by sananguliyev** [slimphp/Slim#2437]
I think that it would be nice to have something like that.

```
$app->get(
    '/',
    \Some\Controller::class . ':someMethod',
    ['someServiceFromDi']
);
```

And controller:
```
class SomeController
{
    /**
     * @var SomeService
     */
    private $someService;

    /**
     * SomeController constructor.
     * @param SomeService $someService
     */
    public function __construct(SomeService $someService)
    {
        $this->someService = $someService;
    }
}
```

I just want to read your opinions about that.

**Comment by zelding** [comment]
you can always create continerAware Controllers, and pull your dependencies "manually"

**Comment by sananguliyev** [comment]
@zelding thanks for your reply. I know it but I do not like to pass the whole container to the controller. It is not good practice I think. It looks like to buy market for getting one chocolate :)

**Comment by chadicus** [comment]
@SananGuliyev  I'm not sure if this helps, but you can define the controller construction within the container

```php

use Psr\Container\ContainerInterface;
use Some\Controller;

$app->getContainer()[Contorller::class] = function (ContanierInterface $container) : Controller {
    return new Controller($container->get('someService'));
};

$app->get('/',    Controller::class . ':someMethod');
```

**Comment by sananguliyev** [comment]
@chadicus thanks for the suggestion. I currently use this approach in one of my projects. Using controller as the dependency is a good solution but after some time it grows dependency container because you should have the dependency for every single container. That's why it would be nice to keep the DI slim, too. 

To be honest I already overwritten the `\Slim\App' for that need. I want to know maybe the others also want to have something like this. Then maybe we can contribute to that functionality.

For example:
```
    /**
     * @param string $pattern
     * @param callable|string $callable
     * @param array $dependencies
     * @return \Slim\Interfaces\RouteInterface|void
     */
    public function get($pattern, $callable, $dependencies = [])
    {
        $this->resolveCallable($callable, $dependencies);
        parent::get($pattern, $callable);
    }

    /**
     * @param string $callable
     * @param array $dependencies
     */
    private function resolveCallable($callable, $dependencies = [])
    {
        if (is_string($callable)){
            $methods = explode(':', $callable);
            $container = $this->getContainer();

            if ($container->has($methods[0]) === false){
                $arguments = [];

                foreach ($dependencies as $dependency) {
                    $arguments[] = $container->get($dependency);
                }

                $container[$methods[0]] = function () use ($methods, $arguments){
                    return new $methods[0](...$arguments);
                };
            }
        }
    }
```

**Comment by geggleto** [comment]
What you want is to use PHP-DI, it supports auto-wiring.

`http://php-di.org/doc/frameworks/slim.html`

We are removing the default container in Slim 4, so we wont be making any changes to the container and how it works.
