### ISSUE TITLE
Make session startup optional and lazy-loaded

### ISSUE THREAD

**Issue by olivierphi** [slimphp/Slim#244]
Hi !

I appreciate the Slim framework a lot, but I would like to be able to start the session process only if I need it, instead of starting it for every request.
Do you think it would be possible to start the Session process only when the developer requests it ? For exemple, via a `$mySlimInstance->session()` accessor, with a bit of lazy-loading ? The first time it would be used during the Slim app lifecycle, the session process would be started and the session data would be returned, then it would return just a pointer to the session data.
Would you agree such a process ?

**Comment by codeguy** [comment]
Version 1.6.0 does not start a session for you at all. I felt sessions in 1.5.x were too presumptuous, too, as you suggested. If you need a native PHP session, you have to prepare and start it on your own in 1.6.0. The current implementation in 1.5.x has been abstracted into optional middleware that you can enable with:

```
$app->add('Slim_Middleware_SessionCookie');
```

This middleware will persist session data into hashed, encrypted client-side cookies. I will be writing additional middleware soon that will enable a native PHP session with safe defaults should someone not want to configure and start the session himself.

**Comment by olivierphi** [comment]
Great !
As I'm working with the stable version (1.5), and didn't have a look to the upcoming 1.6, I hadn't seen this. This is just perfect, I will switch to 1.6 when it's ready, thank you very much !
