### ISSUE TITLE
How to inject Eloquent DB Facade in Slim?

### ISSUE THREAD

**Issue by imageslr** [slimphp/Slim#2443]
**UPDATE:**

I use the following statement to solve the problem. Thank you. Please inform me if you have any better solution.

```PHP
use Illuminate\Database\Capsule\Manager as DB;
```

-----

Dear developers, I want to use DB Facade of Eloquent in my Controller class directly. I hope I can use it like this:

```PHP
use Illuminate\Supports\Facades;

class MyController {
    public function index(){
        $res = DB::table(DB::raw('select * from users'));
        // ...
    }
}
```

But DB is actually initialized and injected automatically in Laravel. In slim, I have to inject db manually in container:

```PHP
// 配置Eloquent
// contig Eloquent
$container = $app->getContainer();
$capsule = new \Illuminate\Database\Capsule\Manager;    // 这些语句必须放在闭包外面
$capsule->addConnection($container['settings']['db']); // 创建一个数据库的链接
$capsule->setAsGlobal(); // 静态可访问
$capsule->bootEloquent(); // 启动Eloquent
$container['db'] = function ($container) use ($capsule){
    return $capsule;
};

// 添加db属性
// inject db into container
$container[App\Controllers\MyController::class] = function ($c) {
    $db = $c->get('db');
    return new App\Controllers\MyController($db);
};

// add route
$app->get('/api/user', 'App\Controllers\MyController:index');
```

And thus my Controller becomes to:

```PHP
class MyController {
    private $db;

    public function __construct($db){
        $this->db = $db;
    }

    public function index(){
        $res = $this->db::table($this->db::raw('select * from users'));
        // ...
    }
}
```

It's ugly, And I have to add dependency for each Controller _(or I don't need to do this every time?)_. Could anyone please tell me a more elegant way to use DB Facade in slim3? Thank you!

**Comment by carc1n0gen** [comment]
This is how dependency injection works.  If you would like it to happen through _magic_, you will want to look in to PHP-DI, which supports autowiring

https://github.com/PHP-DI/PHP-DI
https://github.com/PHP-DI/Slim-Bridge

**Comment by damianopetrungaro** [comment]
@imageslr I suggest you to inject `DB` into each controller instead of using Facade, that is harder to test.
If you prefer you may inject the container into the constructor of the controller and use db from there.


## **BUT:**
try using a repository layer and inject the repository into the Controller so it will be easier to maintain in the future, i am not fun of the other 2 approaches.

**Comment by akrabat** [comment]
Personally, I prefer to inject into each class & something like PHP-DI makes it much easier. 

However, you could probably use Laravel's DB facade directly if it's own repo. Otherwise, just create a `DB` class yourself that has the relevant static method on it.

**Comment by imageslr** [comment]
Thank you sincerely! I will look in these approaches.
