### ISSUE TITLE
Route with special characters shows 404 page error

### ISSUE THREAD

**Issue by anant-svc** [slimphp/Slim#2455]
Using letters like **♪** in route not working on **SLIM 3.10.0**.

How can I use special characters in route?

**Comment by odan** [comment]
Hello @anant-svc 

We have already discussed this question in other issue: https://github.com/slimphp/Slim/pull/2409

This should do the trick:

```php
use Slim\Http\Request;
use Slim\Http\Response;

$app->get('/' . rawurlencode('♪'), function (Request $request, Response $response) {
    return $response->getBody()->write('Sing with me!');
});
```

Open: http://localhost/♪ -> `Sing with me!`

**Comment by Ananth747** [comment]
Thanks again to @odan 
You can close this issue.

**Comment by anant-svc** [comment]
Thanks again to @odan 
Solved my problem.
