### ISSUE TITLE
Difficult to Extend Slim\App

### ISSUE THREAD

**Issue by Abdillah** [slimphp/Slim#2461]
Hi,

In summary, I wanted to extend `Slim\App`: like override `App::run` to be more transparent, adding modular routes loader, etc. But, I can't; due to some blockers: `private $container` and highly-coupled `Slim\RouteGroup`.

The `private $container` disabled anyone to extend existing method since almost every methods needs container. It can be solved through overwriting all methods as-is.

The second blocker is `Slim\RouteGroup` which highly coupled with `Slim\App`. Once I extend `Slim\App`, I must also rewrite `Slim\RouteGroup` (even the interface).

# Expectation
Seamlessly extend `Slim\App` and replace the instance with new one.

# Reality
Extending `Slim\App` and construct will raise the following error.
```
Fatal error: Uncaught TypeError: Argument 1 passed to Slim\RouteGroup::__invoke() must be an instance of Slim\App or null, instance of MyApp\Slim2 given, called in /project/path/src/Slim2.php on line 286 and defined in /project/path/vendor/slim/slim/Slim/RouteGroup.php:38 Stack trace: #0 /project/path/src/Slim2.php(286): Slim\RouteGroup->__invoke(Object(MyApp\Slim2)) #1 /project/path/src/routes.php(182): MyApp\Slim2->group('/admin', Object(Closure)) #2 /project/path/src/App.php(18): {closure}(Object(MyApp\Slim2)) #3 /project/path/public/index.php(39): MyApp\App->withRoutes(Object(Closure)) #4 {main} thrown in /project/path/vendor/slim/slim/Slim/RouteGroup.php on line 38
```

# Proposals
Therefor, some proposal:
1. Change `$container` visibility.
2. Enable reusable RouteGroup.
  Either by (a) Remove typehint in `RouteGroupInterface::__invoke` (low effort 😉), or (b) Create `Slim\AppInterface` and typehint into it.

**Comment by estelsmith** [comment]
I'm not having any issues extending `Slim\App` in my project.

```php
class MyContainer extends \Slim\Container
{
    public function __construct(array $values = [])
    {
        parent::__construct($values);

        $this['settings']['determineRouteBeforeAppMiddleware'] = true;

        $this->register(new MyCustomServiceProvider());
    }
}

class MyApp extends \Slim\App
{
    private $hasBooted = false;

    public function __construct(MyContainer $container)
    {
        parent::__construct($container);
    }

    public function boot()
    {
        $booted = &$this->hasBooted;
        if ($booted) return;
        // @TODO Do some bootstrappy stuff if needed
        $booted = true;
    }

    public function run($silent = false)
    {
        $this->boot();
        return parent::run($silent);
    }
}
```

I'm not sure if you've tried this method, but it works fairly well without having to hack up Slim.

You can do one-time bootstrap work in `MyApp::boot()`, or wire up routes and services in `MyContainer` or `MyCustomServiceProvider`.

**Comment by Abdillah** [comment]
Seem I was too hard on pushing the `ExtendedApp` immutable (to make it testable) and unaware of just (1) `extends`, (2) `getContainer()`, and then (3) modify in place. But, I have successfully restructure my tests by compositing the `Slim\App` inside other class and doing (2) and (3).

If I retain the immutability, means that every container must be cloned before modified, then assigned into cloned app. Something like this:
```php
// In ExtendedApp
public function addDependency($key, $value)
{
    $container = clone $this->container;
    $container->set($key, $value);
    $self = clone $this;
    $self->container = $container; // Not possible, due to the privatization
    return $self;
}
```
To make it possible, I "copy" the whole `Slim\App` but the `Slim\RouteGroup` too tightly coupled.

But, well, the real goal has been achieved and "extension" is possible, easier. I use your method, happily ever after... except once my curiosity woken up. Thank you.
