### ISSUE TITLE
POST request always forbidden

### ISSUE THREAD

**Issue by okumaster** [slimphp/Slim#2465]
Hallo,

I make POST request via posman with application/json, the response is 200. But, when I tried with arduino POST request the response always 403(forbidden), the header request still correct and my arduino is working perfectly. Because, when I make GET request the response is 200.

i see this with same problem, but it use node https://github.com/franciscop/server/issues/26

How should I do?

thank you

**Comment by akrabat** [comment]
This question is better asked on our [Slack](https://www.slimframework.com/#community) and/or our [discourse forum](http://discourse.slimframework.com/).
