### ISSUE TITLE
"redirect" or "halt" hooks ?

### ISSUE THREAD

**Issue by olivierphi** [slimphp/Slim#247]
Sorry to bother you again...
I was just wondering if we could add 1 o 2 new hooks into the Slim lifecycle, when a HTTP redirection is made through `$app->redirect($url)`.

A concrete use case : in my application I have a function registered to the hook "slim.after" which logs the SQL queries made during the display of a page (in "develoment" mode only, of course), + misc performance informations. But each time I have to trigger a HTTP redirection in my application (after a form submission, for instance), I have no SQL queries logs, since the hook is not called. And I haven't been able to find a hook which could allow me to do this (even in the "develop" branch).

What do you think of adding such a hook when the "redirect" method is called (and/or more generally, when the `halt()` method is triggered) ? Something like "slim.redirect" and "slim.halt" hooks...
If you think it's a good idea, I can add them and send you a Pull Request, if you want.

**Comment by rodrigorm** [comment]
+1

**Comment by codeguy** [comment]
This will be resolved in 1.6.4 (coming out in a few days). I've updated the Slim::call loop so that the `slim.after` hook will always be run, even when the `stop`, `halt`, or `redirect` Slim application methods are invoked.
