### ISSUE TITLE
$response->withJson does not work accentuation!

### ISSUE THREAD

**Issue by ewertonrfd** [slimphp/Slim#2470]
I commented on a closed issue. After I saw it :)
But the problem is this:
- Does not work:
return $response->withJson('Erro na atualização', 400);

- It works:
return $response
            ->withStatus(400)
            ->withHeader("Content-Type", "application/json; charset=utf-8")
            ->write('Erro na remoção');

Does anyone know any better solution or are they already aware of the problem?

**Comment by mathmarques** [comment]
First, a simple string is not a valid JSON object/array, see the discussion #2453

This is not a Slim issue, by default `json_encode` encode special characters to unicode like `\uxxxx`
See http://php.net/manual/pt_BR/function.json-encode.php 
But if you want to see those characters use:
`json_encode($response, JSON_UNESCAPED_UNICODE);`

Read about JSON_UNESCAPED_UNICODE here: http://php.net/manual/pt_BR/json.constants.php

**Comment by ewertonrfd** [comment]
Thank you for clarifying this question.

**Comment by designermonkey** [comment]
I'm going to close this as it seems to be resolved. If there is any more info to add, please do and it can be re-opened.
