### ISSUE TITLE
Ability to add trusted proxies / headers to environment

### ISSUE THREAD

**Issue by madsem** [slimphp/Slim#2473]
The problem is that on setups behind an SSL load balancer (I'm speaking in particular about AWS ELB's), ```Slim\Http\Uri``` still generates HTTP links, using a middleware doesn't help in this case, browser url is redirected to HTTPS but the Twig asset() helper for example still generates HTTP.

Also ```$request->getUri()->getScheme()``` outputs HTTP.

If you change ```$_SERVER['HTTPS'] = 'on``` and add this to the Environment, ```\Slim\Http\Uri``` is always HTTPS, even if the actual URL in the browser is HTTP, which then breaks the middleware. 

How about adding this to the core, that trusted headers & proxies can be supplied, and ```\Slim\Http\Uri``` is adjusted to also check ```$_SERVER['REQUEST_SCHEME']``` instead of assuming that it must be HTTPS?

**Comment by akrabat** [comment]
Use [proxy-detection-middleware](https://github.com/akrabat/proxy-detection-middleware) and Slim 3.11.0 and you should be good.

See #2487 and #2486 for details.

**Comment by madsem** [comment]
Hey @akrabat thanks, will look at it again. But I already tested your middleware earlier and the problem was that the IP addresses are unknown (AWS ELB). But I give it a whirl again, maybe there is a way that I didn't see if I only want trusted proxies to be X-Forwarded-For

**Comment by akrabat** [comment]
I'm pretty sure you can set `$trustedProxies` to an empty array and then the middleware will alway inspect the X-Forwarded-For header.

**Comment by madsem** [comment]
nice! Thanks for that tip :) Have a nice sunday
