### ISSUE TITLE
response-withRedirect() not rendering global variable set in twig

### ISSUE THREAD

**Issue by rsd1234** [slimphp/Slim#2474]
favorite
$response->withRedirect() method in slim not rendering global variable for twig created in middleware
slim
```
<?php

namespace Auto\middleware;


class registrationMiddleware{
    public $container;

    public function __construct($container){
        $this->container=$container;
        // $container is the $app instance passed from the route

    }

    public function __invoke($request,$response,$next){

       $this->container->getContainer()->view->getEnvironment()->addGlobal('error','error');
      $response=$next($request,$response);
     return $response->withRedirect($this->container->getContainer()->get('router')->pathFor('redirect'));



  }
}
```
It shows a blank window and no output of
Of global variable after redirecting 

Inside twig view i have
{{error}} but it is not outputting its value and shows only a blank screen after redirecting

**Comment by akrabat** [comment]
This question is better asked on our [Slack](https://www.slimframework.com/#community) and/or our [discourse forum](http://discourse.slimframework.com/).

**Comment by rsd1234** [comment]
I cant get the answer
