### ISSUE TITLE
Allow attributes on Response?

### ISSUE THREAD

**Issue by samtny** [slimphp/Slim#2479]
Similar to #2210, I have a use-case for passing data from a route to middleware.

It looks like we can pass data going the other way - from middleware to route - using the `$request->withAttribute('foo', 'bar')` pattern.

How about something similar for the Response?  In my route I could e.g. `return $response->withAttribute('bar', 'baz')`, then pick it up in the middleware.

This avoids the use of a global with what seems to be a consistent / sensible pattern.

**Comment by odan** [comment]
Hi @samtny According to [PSR-7](https://www.php-fig.org/psr/psr-7/) (HTTP message interface) only the `ServerRequestInterface` has a `withAttribute` method. The `ResponseInterface` has no `withAttribute` method.

**Comment by akrabat** [comment]
You could create your own Response object that your action returns. This Response object could extend Slim's and add custom properties for the data you want to send to the middleware.

**Comment by samtny** [comment]
Thanks, guys.
