### ISSUE TITLE
The path becomes strange when rewritten in Apache's conf

### ISSUE THREAD

**Issue by r-kagaya** [slimphp/Slim#2480]
The path becomes strange when rewritten in Apache's conf in v2.0

I will explain based on an example

```
<If "% {REQUEST_URI} = '' /simplephp/slim/issues">
　RewriteRule ^ /simple/index.php [QSA, L]
</ if>
```
The expected output is as follows
```
$app-> getResourceuri () -> /simplephp/slim/issues"
```

Actual output
```
$app-> getResourceuri () -> ephp/slim/issues
```

It seems to be because it deletes by looking at the number of characters of $ physicalPath in line 138 of the Environment class

**Comment by akrabat** [comment]
We are no longer updating Slim 2.
