### ISSUE TITLE
[Proposal] Support no output buffering at all

### ISSUE THREAD

**Issue by 1ma** [slimphp/Slim#2481]
### Use case

Adding the ability to completely disable output buffering would empower the developer to push content to the user agent while still processing an HTTP request (i.e. while still inside the callback or Action class). This would allow, for instance, to give real-time feedback at every iteration of a long-running loop.

The following is a minimal demonstration in pure PHP that can be served with the builtin webserver to see the effect firsthand:
```php
// index.php

header('Content-Type: text/plain');

foreach (range('A', 'F') as $char) {
  sleep(1);
  echo "$char\n";

  ob_flush();
  flush();
}
```
![demo](https://i.imgur.com/jTfzDWj.gif)

### Current status

Slim 3 has an `outputBuffering`  setting whose legal values are `false`, `'append'` and `'prepend'` (default `'append'`). However, `false` seems to [simply instruct the framework to neither prepend nor append](https://github.com/slimphp/Slim/blob/0618c56a3a2c6f6e621a11d2863712969ddc0670/Slim/App.php#L322-L331) stray `echo`'s to the PSR7 response.

As far as I understand, Slim does not currently support this behaviour.

### Proposed API

I believe that the cleanest way to add this feature would be through a new  specialized implementation of the `StreamInterface` that would handle all the details under the hood in its `write` method. The former sample could be then rewritten like this:

```php
namespace Demo;

use Slim\Http;

final class NonBufferedAction
{
    public function __invoke(Http\Request $request, Http\Response $response): Http\Response
    {
        $response = $response
            ->withBody(new NonBufferedBody())
            ->withHeader('Content-Type', 'text/plain');

        foreach (range('A', 'F') as $char) {
            sleep(1);
            $response->getBody()->write("$char\n");
        }

        return $response;
    }
}
```

What are yer thoughts?

**Comment by llvdl** [comment]
I think that would break the ability for middleware to replace or alter the response.

I think a generator as a body would be a good fit here. If Slim could be altered to allow a generator as well as a `Psr\Http\Message\StreamInterface` instance, then the following code could be used:

```php
class NonBufferedAction
{
  public function __invoke(Request $request, Response $response): Response
  {
    return $response
      ->withBody(function (): Generator  { // won't work now, as Slim expects a StreamInterface instance
        foreach (['alpha', 'beta', 'gamma', 'delta'] as $data) {
          sleep(1);
          yield $data;
        }
      });
  }
}
```

**Comment by akrabat** [comment]
I like the idea of a specialised StreamInterface.

Implementing this will also address Server Sent Events support (#1959).

**Comment by 1ma** [comment]
I submitted a PR with a possible implementation, but I'd like to have a bit of input from the mantainers and/or other community members before doing the rest of the gruntwork (mostly documentation).
