### ISSUE TITLE
If server is on port != 80 but incoming request is on port 80, the wrong port number appears in the uri

### ISSUE THREAD

**Issue by lornajane** [slimphp/Slim#2486]
I have this setup:
 - PHP running on port 8080 via `php -S localhost:8080`
 - Ngrok running a tunnel pointing to port 8080. The URL for requests is therefore http://somethingsomething.ngrok.io (on port 80)

## What I expected

I expected that this code (in a route):
```php
$uri = $request->getUri();
echo $uri->getPort();
```
Would return either nothing/false or port 80, since the request came in on that port and I'm building a link to a route inside the same application.

## What actually happened

The code returns "8080", and therefore my application returns data that looks like: http://somethingsomething.ngrok.io:8080 which doesn't work!

## Further notes

I can create a PR if someone can help me work out what the right thing to do here is.  Looking at https://github.com/slimphp/Slim/blame/3.x/Slim/Http/Uri.php#L184 I think the default to `SERVER_PORT` is incorrect. Because in this case, there isn't a port number in the URL (since it's port 80), we never pick up the port number from the host data.

What I'm not clear on: in which situation would `SERVER_PORT` be the correct default over whatever is in the `HTTP_HOST`? Because I can't think of a use case for this but I don't want to remove it and break things for someone else.

**Comment by l0gicgate** [comment]
`SERVER_PORT` will return the port that's being accessed when making requests to the PHP application.

In this case, it should return `8080` since your PHP server is listening on `8080`. There's no way for the server to know that it's being tunneled to unfortunately. 

And https://github.com/slimphp/Slim/blame/3.x/Slim/Http/Uri.php#L184 is the correct behavior. `Environment::get()` get method takes two parameters `get($key, $default)` as shown here https://github.com/slimphp/Slim/blob/3.x/Slim/Collection.php#L63 

If the `$key` you are trying to get is nonexistent it will return the `$default` parameter.

**Comment by carc1n0gen** [comment]
People usually get around this type of thing by having the proxy/tunnel add a header to the request containing the port, then on the slim side you can retrieve that port number from the header.  I don't have an example for Ngrok because I am not familiar with it.

**Comment by akrabat** [comment]
> People usually get around this type of thing by having the proxy/tunnel add a header to the request containing the port, then on the slim side you can retrieve that port number from the header. I don't have an example for Ngrok because I am not familiar with it.

[proxy-detection-middleware](https://packagist.org/packages/akrabat/proxy-detection-middleware) does the detection in the Slim side for proxy headers. However, it doesn't fix the problem that Slim sets the port incorrectly when there's a Host header which is fixed by #2487.

**Comment by carc1n0gen** [comment]
@akrabat Thanks for clearing that up

**Comment by akrabat** [comment]
Fixed with #2487 in Slim 3.11.0
