### ISSUE TITLE
CORS enabled, still having 405 on POST endpoint

### ISSUE THREAD

**Issue by pvermeil** [slimphp/Slim#2489]
Hello Slim users. I'm using Slim 3.10 with PHP 7.0 on Ubuntu Apache 2.

When I call one of my endpoints with URI /proforma by POST method, I'm getting a 405 error telling me "Must be one of : GET". However when I look the response headers I have the following : 

Access-Control-Allow-Headers →X-Requested-With, Content-Type, Accept, Origin, Authorization
Access-Control-Allow-Methods →POST
Access-Control-Allow-Origin →*

GET requests on the same path are working, with methods header returning only the current request method in authorized methods list.

I followed the Access-Control-Allow-Methods example in the docs : https://www.slimframework.com/docs/v3/cookbook/enable-cors.html

Even if I comment all code inside my endpoint callback and return an empty response, I have this 405 error, which makes me think the problem is either from my client (Postman 6.2) or a misconfiguration in Middlewares. Here is what I use at the beginning of my index.php where my callbacks live : 

```php
$app->add(function ($request, $response, $next) {
    $route = $request->getAttribute("route");

    $methods = [];

    if (!empty($route)) {
        $pattern = $route->getPattern();

        foreach ($this->router->getRoutes() as $route) {
            if ($pattern === $route->getPattern()) {
                $methods = array_merge_recursive($methods, $route->getMethods());
            }
        }
        //Methods holds all of the HTTP Verbs that a particular route handles.
    } else {
        $methods[] = $request->getMethod();
    }

//    die(print_r($methods));

    $response = $next($request, $response);


    return $response
        ->withHeader("Access-Control-Allow-Methods", implode(",", $methods))
        ->withHeader("Access-Control-Allow-Origin", '*')
        ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization');
});
```

Notice that the commented die() shows me Array ( [0] => POST ) 1. Since request method is found from Request object, I made a print_r of it but didn't even find the route attribute. Only routeInfo. Also I don't understand why my response header returns me POST as Access-Control-Allow-Methods.
In the 405 error's html I see "must be one of : GET".
Now here is the code of my endpoint itself, with an empty response that gives the same error.

```php
$app->post(RESOURCE_PATH, '/proforma', function (\Slim\Http\Request $request, \Slim\Http\Response $response){

return $response->withJson(array())
                ->withHeader('Location', $oProforma->getUrl())
                ->withHeader('Content-Type', 'application/json')
                ->withStatus(201);

});
```

Here is a curl dump of what postman sends (except the payload). It's the same as for the working POST on /invoices, another path. It leads me to think it's not client's fault.

```
curl -X POST \
  http://slimapi.dev:81/invoices/proforma \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 93ce3a0c-d11c-4839-9746-44c868ee440f' \
```

Last point : when comparing request object between the working POST path and POST /proforma, I notice request for /proforma has extremely small attributes object, **with only routeInfo in its data array. No route attribute :** 
```
[attributes:protected] => Slim\Collection Object
        (
            [data:protected] => Array
                (
                    [routeInfo] => Array
                        (
                            [0] => 2
                            [1] => Array
                                (
                                    [0] => GET
                                )
                            [request] => Array
                                (
                                    [0] => POST
                                    [1] => http://slimapi.dev:81/invoices/proforma
                                )
                        )
                )
        )
```
I'm confused about what happens between my client, the Request object, this middleware and my endpoint. Any help is welcome :) Let me know if I should post here or on https://discourse.slimframework.com/ in the future, thanks a lot :)

**EDIT : I tried commenting every callback but the one I want to reach (POST /proforma) and... It gives a 404 error ! Note that POST /proforma is on the top of index.php, after init and middleware stuff.**

**Comment by tuupola** [comment]
Are you sure there really is a POST route defined for `/invoices/proforma`? Assuming value of `RESOURCE_PATH` is `invoices` then shouldn't this:

```php
$app->post(RESOURCE_PATH, '/proforma', function (\Slim\Http\Request $request, \Slim\Http\Response $response){
```

be something like this instead:

```php
$app->post(RESOURCE_PATH . '/proforma', function (\Slim\Http\Request $request, \Slim\Http\Response $response){
```

**Comment by pvermeil** [comment]
Thank you so much. I can't believe this was that trivial. Just typo inside post function parameters. I close the topic, have a nice day/night
