### ISSUE TITLE
Sentry via Monolog

### ISSUE THREAD

**Issue by flowdee** [slimphp/Slim#2490]
Anyone already figured out how to use Monolog's Sentry support with Slim3?

According to their [documentation](https://docs.sentry.io/clients/php/integrations/monolog/) it should be quite simple, but when requiring Sentry via composer, it still does not find the "Raven_Client" class as expected.

**Comment by lotarbo** [comment]
did you try `$client = new \Raven_Client(...);` ?

**Comment by flowdee** [comment]
You're right, this worked out!
