### ISSUE TITLE
Parameter $value in RouteInterface::setArgument()

### ISSUE THREAD

**Issue by o5** [slimphp/Slim#2492]
Hello, 

is there any reason for accept only strings in second parameter $value in [RouteInterface::setArgument()](https://github.com/slimphp/Slim/blob/254c45edba0873d105be55ad6d9c4f8c2ed66026/Slim/Interfaces/RouteInterface.php#L59). 

I'm using boolean and I think it's ok, but it isn't OK for PHPStan  :)

Thanks
Peter

**Comment by akrabat** [comment]
Route arguments are used in URIs which are strings. If you use a boolean, you are implicitly converting it to `"0"` or `"1"` and that should really be an explicit choice.

**Comment by o5** [comment]
OK, thanks!
