### ISSUE TITLE
Call to undefined function imagecreatetruecolor

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2506]
I've been trying out several methods of running away from this problem but I can't seem to find a solution. I'm in hopes of using Gd image processing library but Slim says its undefined. I even created a class to inject as a service with which I still get the same error. Am I missing something here?

`Trace
#0 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /var/www/html/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /var/www/html/api/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/www/html/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /var/www/html/api/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /var/www/html/api/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /var/www/html/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/www/html/api/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/www/html/api/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /var/www/html/api/index.php(23): Slim\App->run()
#10 {main}`

Above is the trace of just using `imagecreatetruecolor()`

I tried using a package Imagine which offers a wrapper but also throws an error when running a function `gd_info`

**Comment by tflight** [comment]
Hi @sduduzog,

This isn't an issue with Slim, so it would be best handled in our [Slim Support Forum](https://discourse.slimframework.com) our in our [Slack channels](https://slimphp-slack-invite.herokuapp.com).

Check if your PHP version has GD enabled, and/or check if the function exists.

```php
if (!function_exists('imagecreatetruecolor')) {
	echo 'No GD';
	exit();
}
echo 'GD exists';
```

**Comment by ghost** [comment]
@tflight Thanks for the response, I'll definitely do so. I have been working with GD before using Slim on the same machine. I even tried injecting gd functions as services with no luck

**Comment by ghost** [comment]
Turns out my php.ini file had some errors, fixed and thank you for the heads up @tflight
