### ISSUE TITLE
Stream Read TypeError

### ISSUE THREAD

**Issue by bobdercole** [slimphp/Slim#2511]
Hello,

Slim causes a TypeError when using a stream class with ```declare(strict_types=1)``` that relies on ```fread``` within ```StreamInterface::read()```. I noticed this issue because part of my code uses zend-diactoros, which [now has](https://github.com/zendframework/zend-diactoros/pull/329) ```declare(strict_types=1)```.

Here is the stack trace:

```
PHP Fatal error:  Uncaught TypeError: fread() expects parameter 2 to be integer, string given in /var/www/client-api/vendor/zendframework/zend-diactoros/src/Stream.php:277
Stack trace:
#0 /var/www/client-api/vendor/zendframework/zend-diactoros/src/Stream.php(277): fread(Resource id #17, '112')
#1 /var/www/client-api/vendor/slim/slim/Slim/App.php(464): Zend\\Diactoros\\Stream->read('112')
#2 /var/www/client-api/vendor/slim/slim/Slim/App.php(337): Slim\\App->respond(Object(Zend\\Diactoros\\Response))
#3 /var/www/client-api/public/index.php(11): Slim\\App->run()
#4 {main}
  thrown in /var/www/client-api/vendor/zendframework/zend-diactoros/src/Stream.php on line 277
```

It seems that Slim could pass the string value of the ```Content-Length``` header to ```read()``` [here](https://github.com/slimphp/Slim/blob/6d347477d09ab7910e625cee74c8108b7b85c7f9/Slim/App.php#L464). Since ```StreamInterface::read()``` expects an integer, I think this should be fixed in Slim. Thoughts?

I am using Slim 3.11.0.

Thank you!

**Comment by hidehalo** [comment]
Same error
