### ISSUE TITLE
[Proposal] Support no output buffering in Slim 4

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#2513]
Slim 4 version of https://github.com/slimphp/Slim/issues/2481.

Is this solved by #2166 ?

**Comment by l0gicgate** [comment]
This will be fixed with #2529

**Comment by akrabat** [comment]
I think this becomes a [Slim-Psr7](https://github.com/slimphp/Slim-Psr7) item if we want to do it in 4.x

**Comment by akrabat** [comment]
Opened issue https://github.com/slimphp/Slim-Psr7/issues/24 to track on Slim-Psr7.
