### ISSUE TITLE
Redirect not working when specifying status code

### ISSUE THREAD

**Issue by alffonsse** [slimphp/Slim#2517]
PHP version : 7.2.5
Slim version 3.11

Hello,

I just started a new project with Slim yesterday and I realized that my redirections don't work when I specify a status code. They do however if I do not specify a status code.

I use the following code to do my redirections : `return $response->withRedirect('/somepage', 500);`

Whether I use a class controller for my route target and do the redirect in there or I just use a callback I just get a blank page.

The target page is always a GET route and I don't send any header prior to my response or echo anything.

Am I doing something wrong here ?

**Comment by akrabat** [comment]
Hi,

This is a limitation of web browsers. Slim is doing the right thing and setting the status code to 500 and a `Location` header to `/somepage`. However, browsers do not automatically redirect unless these status code is in 301 or 302.

Regards,

Rob

**Comment by alffonsse** [comment]
Wow that was a quick response !

Thank you for the explanation :smiley:

**Comment by akrabat** [comment]
You picked a moment when I happened to be maintaining the issues list :)
