### ISSUE TITLE
Can't Override Error Handlers

### ISSUE THREAD

**Issue by ObeeWanKenobee** [slimphp/Slim#2521]
I've followed https://www.slimframework.com/docs/v3/handlers/not-found.html and https://www.slimframework.com/docs/v3/handlers/not-allowed.html instructions but no luck.

I've even changed `->write('Page not found');` to `->write('Page not founds');` but still the same.

Please enlighten me. Did I miss something?

**Comment by akrabat** [comment]
This question is better asked on our [Slack](https://www.slimframework.com/#community) and/or our [discourse forum](http://discourse.slimframework.com/).

If you can create a single file `index.php` complete Slim app that shows the problem, then someone should be able to help you.

**Comment by ObeeWanKenobee** [comment]
Thanks @akrabat
