### ISSUE TITLE
Question: Successful stories?

### ISSUE THREAD

**Issue by stefanos82** [slimphp/Slim#2524]
I have tried to find a link with successful stories and couldn't find anything.

Is it possible to have a dedicated page with such option? It would help attract newcomers that show interest in Slim.

**Comment by adjenks** [comment]
I use it. It's good. Minimal learning curve. Not too opinionated. Easy to swap out parts.

**Comment by l0gicgate** [comment]
This PR needs to be directed to the [Slim-Website repo](https://github.com/slimphp/Slim-Website). I opened an issue there. See [#331](https://github.com/slimphp/Slim-Website/issues/331)
