### ISSUE TITLE
Updating the route does not update the URI

### ISSUE THREAD

**Issue by tobiashinz** [slimphp/Slim#2525]
I am trying to manipulate a request in a way that I change a path argument.

The pattern is `/customers/{customerid}/licenses`

So I am getting the `Route` of the request, change one of its argument and set it back to the request. 

```php
 /** @var \Slim\Route $route **/
$route = $request->getAttribute('route');

$request = $request->withAttribute('route', $route->setArgument('customerid', 'newCustomerId'));
```

The problem is, that the `Uri` is not updated (see `path`)

```php
var_dump($request->getUri());

object(Slim\Http\Uri)#163 (9) {
  ["scheme":protected]=>
  string(4) "http"
  ["user":protected]=>
  string(0) ""
  ["password":protected]=>
  string(0) ""
  ["host":protected]=>
  string(9) "localhost"
  ["port":protected]=>
  int(8080)
  ["basePath":protected]=>
  string(3) "/v1"
  ["path":protected]=>
  string(21) "customers/oldCustomerId/licenses"
  ["query":protected]=>
  string(301) "access_token=XXX"
  ["fragment":protected]=>
  string(0) ""
}
```

Is there a way to trigger the recreation of the `URI` based on the changed request?

**Comment by akrabat** [comment]
This question is better asked on our [Slack](https://www.slimframework.com/#community) and/or our [discourse forum](http://discourse.slimframework.com/).

You would need to update the `Uri` object too as that is created from the original `$_SERVER` data.
