### ISSUE TITLE
Populating route pattern with args

### ISSUE THREAD

**Issue by ilyachase** [slimphp/Slim#2526]
Hi there! Thanks for very cool framework.
It would be very nice to have method that can build route link from pattern and array of arguments.
Something like that:
`$request->buildRouteUri(''/hello/{name}', ['name' => 'my name']); //returns /hello/my%20name`

Isn't it?

**Comment by akrabat** [comment]
You can't do it for arbitrary URIs, but you can do it for registered routes:

Given:
```
$app->get('/hello/{name}', MyAction::class)->setName('hello');
```

You can do:

```
$router = $app->getContainer->get('router');
$uri = $router->pathFor('hello', ['name' => 'Rob']);
```

and `$url` will be `/hello/Rob`

**Comment by ilyachase** [comment]
Thanks! Would be great to see this example in the docs.

**Comment by akrabat** [comment]
We'd love a PR against https://github.com/slimphp/Slim-Website

**Comment by ilyachase** [comment]
Will do.

**Comment by ilyachase** [comment]
Sorry it was already in the docs. My bad.
