### ISSUE TITLE
Mention $app->expires() on develop docs

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#253]
Hi,

currently `$app->expires()` for sending `Expires` Headers seems to be undocumented at http://www.slimframework.com/documentation/develop or https://github.com/codeguy/Slim/tree/develop/docs. 

That should be mentioned.

Regards,
Chris

**Comment by codeguy** [comment]
Agreed. I've consolidated what needs to be documented before the 1.6.0 release into the issue linked below. Closing this out.

https://github.com/codeguy/Slim/issues/274
