### ISSUE TITLE
Classes not found: Slim\Http\Headers, Slim\Http\Request, Slim\Http\Response

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2530]
Hi, I just installed the 4.x branch (using composer) and there seems to be a problem in the Slim class.

The following classes could not be found.
```
Slim\Http\Headers;
Slim\Http\Request;
Slim\Http\Response
```

Any idea, why this happened? Where are they? I thought they should be in the slimphp/Slim-Http project.

**Comment by akrabat** [comment]
The `4.x` branch is very much in flux at the moment! Slim-Http is now a set of decorators over a separate PSR-7 implementation. PR #2529 covers the integration of this into Slim 4.
