### ISSUE TITLE
slim 4 + slim-http 0.5 decorators

### ISSUE THREAD

**Issue by sinitsa** [slimphp/Slim#2531]
Hello!
Now i'm using slim4 and slim psr7 implementation.. Today you have upgraded slim-http to decorators, very good update, thanks! 
1. After upgrade i got errors in slim4 App.. If i understood right, now slim psr7 moved to slim/psr7, but composer couldn't find it..
2. Some modules of my system (stand-alone) using Guzzle implementation. Is it will be better, to move the entire system to Guzzle too, using new decorators?
How to do it right?)
Thanks in advance

**Comment by akrabat** [comment]
1. See PR #2529 for where we're going. We're in flux at the moment on this branch.

2. It really doesn't matter and is up to you. There is no "right" here. Personally, I'd use Nyholm's PSR-7 implementation for my Slim app as I like it and then use Guzzle as an HTTP client within my actions.
