### ISSUE TITLE
When using middleware, withJson() does not work, while getBody()->write(json_encode()) works.

### ISSUE THREAD

**Issue by webvikrant** [slimphp/Slim#2534]
(Note: I am a newbie to Slim & PHP)
This happened when I was using a simple application middleware.
The application has just one root route (GET '/'), and a simple middleware that conditionally calls next(), so that the '/' route may or may not execute.
Either way, the '/' route or the middleware returns a simple JSON object.

The JSON object in middleware is returned successfully if response->getBody()->write(json_encode()) is used, **BUT**, not if you use response->withJson().
Please correct me if I am missing something.
Thanks.
Attached, herewith, the text of index.php
[index.txt](https://github.com/slimphp/Slim/files/2544787/index.txt)

``
![01-condition-true](https://user-images.githubusercontent.com/10268689/47950021-8545a580-df72-11e8-83b6-3be678416bfb.PNG)
![02-json returned](https://user-images.githubusercontent.com/10268689/47950022-8545a580-df72-11e8-9664-395086f2aac9.PNG)
![03-condition-false](https://user-images.githubusercontent.com/10268689/47950023-85de3c00-df72-11e8-8c03-7b7ff8675cb1.PNG)
![04-no json returned](https://user-images.githubusercontent.com/10268689/47950024-8676d280-df72-11e8-8965-b8726968ebaa.PNG)

**Comment by akrabat** [comment]
When you call `withJson()` you get a *new*  `Response` object back. The original is not touched.

Hence you need to change:

```php
$response->withJson($result);
```

to:

```php
$response = $response->withJson($result);
```

and all will work as you expect.

**Comment by webvikrant** [comment]
Thanks Rob for such a quick response.
