### ISSUE TITLE
[3.x] Determining +json or +xml in abstract handler

### ISSUE THREAD

**Issue by filips123** [slimphp/Slim#2535]
Why are `+json` and `+xml` content types converted to known content types in [`AbstractHandler.php`](https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/AbstractHandler.php#L49-L55)?

The problem is that this does not follow [JSON:API Specifications](https://jsonapi.org/format/#content-negotiation-servers) which require `application/vnd.api+json` content type.

Is there specific reason for that conversion?

**Comment by akrabat** [comment]
This is only used by the error handling. It's to ensure that Slim sends back JSON when the client's Accept header indicates that it's expecting JSON.

**Comment by filips123** [comment]
What can I do if I want that unhanded errors will be send using `application/vnd.api+json` content type?
I don't want that all responses are JSON because I also want to support other formats. So I want to send same content type as request, but format depending on type.

**Comment by akrabat** [comment]
Replace the Error Handler with your own one.

**Comment by filips123** [comment]
Ok. Thank you.
