### ISSUE TITLE
Add helper to simplify streaming a file download

### ISSUE THREAD

**Issue by Rarst** [slimphp/Slim#2536]
I am currently migrating one of my applications from Silex (RIP) to Slim and got to the part that streams file downloads.

Silex implemented that as an extremely succinct and convenient [`sendFile()`](https://silex.symfony.com/doc/2.0/usage.html#sending-a-file) helper:

```php
return $app->sendFile($path);
```

While doing this seems possible just fine in Slim, from what I found it seems a lot more involved with multiple steps:

1. Open stream to the file
2. Convert it to the Slim stream
3. Create/adjust response object with stream body
4. Set significant amount of headers on the body to define it as download

I ended up with something like this (via [docs](https://www.slimframework.com/docs/v3/objects/response.html#the-response-body) and [forum](https://discourse.slimframework.com/t/slim-3-download-files/224)):
```php
$fileStream = fopen($sendFile->getRealPath(), 'rb');

return $response->withHeader('Content-Type', 'application/force-download')
    ->withHeader('Content-Type', 'application/octet-stream')
    ->withHeader('Content-Type', 'application/download')
    ->withHeader('Content-Description', 'File Transfer')
    ->withHeader('Content-Transfer-Encoding', 'binary')
    ->withHeader('Content-Disposition', 'attachment; filename="'.$sendFile->getBasename().'"')
    ->withHeader('Expires', '0')
    ->withHeader('Cache-Control', 'must-revalidate, post-check=0, pre-check=0')
    ->withHeader('Pragma', 'public')
    ->withBody(new Stream($fileStream));
```

A _lot_ more verbose and honestly on top of my head I hardly _know_ what _exactly_ those headers do and if they are _right_ as my defaults.

So I would like to suggest that **Slim implements a helper for simple file download** in a manner that Silex did.

Thank you for considering. :)

**Comment by l0gicgate** [comment]
@akrabat would you like to include that into Slim 3/4?

**Comment by akrabat** [comment]
I like this idea - it feels like a Slim-Http thing.

**Comment by l0gicgate** [comment]
@akrabat Slim-Http or Slim-PSR7 or both 😂

**Comment by akrabat** [comment]
Slim-Http - it feels like a convenience thing.

**Comment by l0gicgate** [comment]
Issue moved to https://github.com/slimphp/Slim-Http/issues/82
