### ISSUE TITLE
Cannot register media type parser containing '+' character

### ISSUE THREAD

**Issue by PaulKiddle** [slimphp/Slim#2537]
I want to register a handler for `application/activity+json` and return a custom class, however the request is just treated as JSON and returned as an array.

Looks like herein lies the bug https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L1034

I can understand why it's useful to do this if there's no specific handler registered but I think the method of execution is a bit too aggressive for situations like mine.

**Comment by akrabat** [comment]
Fixed by #2538
