### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by xiao872380658** [slimphp/Slim#2540]
error 
![image](https://user-images.githubusercontent.com/6781698/48700612-63f9e000-ec27-11e8-9e1d-ffa5bd169280.png)

![image](https://user-images.githubusercontent.com/6781698/48700658-7d9b2780-ec27-11e8-8485-eb1cfee9c520.png)

![image](https://user-images.githubusercontent.com/6781698/48700678-8c81da00-ec27-11e8-842c-da20f912ad8c.png)

**Comment by tflight** [comment]
Hi @xiao872380658,

Support requests are better handled in our [discussion forums or slack](https://www.slimframework.com/#community). Your route doesn't look right, you probably want something more like this, but may not be exactly right for your setup.

```php
$app->get('/index', '\Controller\Home\GoodsController:showGoods');
```
Have a look at the [container resolution](https://www.slimframework.com/docs/v3/objects/router.html#container-resolution) section of our docs.
