### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by slischka** [slimphp/Slim#2542]
Hello.
There is problem with parsing query parameters from Environemnt.
```
// Query string
$queryString = $env->get('QUERY_STRING', '');
if ($queryString === '') {
	$queryString = parse_url('http://example.com' . $env->get('REQUEST_URI'), PHP_URL_QUERY);
}
```
but if `$_SERVER['QUERY_STRING']` looks like this `?test=1`, then Uri::getQuery() returns `?test=1` and thats wrong. 
PSR - 7:
> The leading "?" character is not part of the query and MUST NOT be added.

It can be fixed like this:
```
// Query string
$queryString = $env->get('QUERY_STRING', '');
if ($queryString === '') {
	$queryString = parse_url('http://example.com' . $env->get('REQUEST_URI'), PHP_URL_QUERY);
}

$strPos = \strpos($queryString, '?');
if ($strPos === 0) {
	$queryString = \ltrim($queryString, '?');
}
```

**Comment by slischka** [comment]
I found typo in my nginx configuration:
```
    location ^~ /api/v1 {
        index api.php;
        try_files api.php /api.php?$is_args$args;
    }
```
but i stil think Slim should handle this propery even if query string starts with `?`.

But this should be closed.

**Comment by akrabat** [comment]
As I understand it, `$_SERVER['QUERY_STRING']` should never have the leading  `?`.

**Comment by slischka** [comment]
So this should be close. Thanks.
