### ISSUE TITLE
`EnvironmentInterface` seems to be a useless type to expect / depend on

### ISSUE THREAD

**Issue by Rarst** [slimphp/Slim#2548]
`Slim\Container` declares default `environment` service to be an implementation of `EnvironmentInterface`.

```
Slim\App expects a container that implements Psr\Container\ContainerInterface
with these service keys configured and ready for use:

 - environment: an instance of \Slim\Interfaces\Http\EnvironmentInterface

@property-read \Slim\Interfaces\Http\EnvironmentInterface environment
```

Thing is `EnvironmentInterface` doesn’t contain anything actually needed for it to work, only test–related `mock()`.

This means that this ` $app->getContainer()->environment->get('foo');` won’t be understood by any tools, because the interface doesn’t _have_ `get()`.

Also the classes that depend on environment like `Slim\Http\Request::createFromEnvironment(Environment $environment)` all require specific `Slim\Environment` _class_, not the interface. So trying to replace `environment` service with something that implements `EnvironmentInterface` would break the app.

It feels like either:

1. `EnvironmentInterface` should be expanded to comprehensively describe a generic replaceable service, in analogue to `ContainerInterface`. Other components of the app should be changed to depend on the interface, not the implementation.
2. Inline documentation should reflect the de–facto dependency on concrete `Environment` implementation, not the interface.

**Comment by Rarst** [comment]
Hey, I noticed this was tagged as a workable issue... But I could use some feedback on _which_ approach is desirable here?

**Comment by jdrieghe** [comment]
I made a small PR that implements one of your proposals: https://github.com/slimphp/Slim/pull/2625.
If it's decided to go with this, I'm more than willing to do the same for the documentation.
