### ISSUE TITLE
Update the slim4 example please.

### ISSUE THREAD

**Issue by Danack** [slimphp/Slim#2552]
Currently the example in the Slim4 branch doesn't work due to 
```
$app = new Slim\App();
```
requires changing to something like:
```
$psrFactory = new Psr17Factory();
$app = new Slim\App(
    $psrFactory
);
```

The run line also needs changing, as:

```
$app->run();
```
requires a request to be passed in. However I can't seem to see an obviously correct way of doing that. Any suggestion please.

**Comment by akrabat** [comment]
https://github.com/slimphp/Slim/pull/2529 currently has the best explanations of how to run the Slim 4.x branch.

**Comment by akrabat** [comment]
@Danack Example now works. Note that you don't have to use that PSR-7 implementation though.
