### ISSUE TITLE
Method 'withJson' not found in Psr\Http\Message\ResponseInterface

### ISSUE THREAD

**Issue by oskarbarcz** [slimphp/Slim#2554]
Response interface from PSR does not include withJson() method, which is run on it in closure.

**Comment by danopz** [comment]
`withJson()` is just implemented in the Slim response for convenience and has to be implemented yourself in some way when you want to use a different PSR7 implementation.
Thats the reason for this note on the doc-block:

https://github.com/slimphp/Slim/blob/a5a2da92d24c2c30384ff89d90008327f9040cb8/Slim/Http/Response.php#L341

**Comment by oskarbarcz** [comment]
Okey, but still - it's not in the interface so IDEs and Rich text editors will throw a warning, why don't you create SlimResponseInterface that will extends PSR7 implementation?

**Comment by froschdesign** [comment]
@archi-tektur 
> …why don't you create SlimResponseInterface that will extends PSR7 implementation?

This would be against the idea of PSR and interoperability.

Suggestion: create a separate `JsonResponse` class which implements the PSR-7 interface for response.
(Compare with zend-diactoros and the custom responses: https://docs.zendframework.com/zend-diactoros/v2/custom-responses/)

**Comment by akrabat** [comment]
Another option is to type hint to a `Slim\Http\Response` if you know that it will always be one in your application.

**Comment by oskarbarcz** [comment]
Okay, thanks, to be closed then

**Comment by l0gicgate** [comment]
Closing as per @archi-tektur's request
