### ISSUE TITLE
AppTest.php - testRouteWithInternationalCharacters() - Fails - Slim 4

### ISSUE THREAD

**Issue by magikstm** [slimphp/Slim#2557]
I'm on Windows 7 x64 english and using PHPUnit 7.5.1.

I just installed a copy of Slim 4.x (latest) and ran tests in the tests folder with this command after doing a `composer install` :
`phpunit --bootstrap C:\projects\Slim\vendor\autoload.php ...`

All tests ran fine except `testRouteWithInternationalCharacters()` in `AppTest.php`.

Full report below:
```
There was 1 error:

1) Slim\Tests\AppTest::testRouteWithInternationalCharacters
Slim\Exception\HttpNotFoundException: Not found.

C:\projects\slim\Slim\Middleware\RoutingMiddleware.php:88
C:\projects\slim\Slim\App.php:494
C:\projects\slim\tests\AppTest.php:299

ERRORS!
Tests: 248, Assertions: 455, Errors: 1.
```

Ref: https://github.com/slimphp/Slim/blob/4.x/tests/AppTest.php#L285

Is this test supposed to fail on my setup? Should it be adjusted?

**Comment by lordrhodos** [comment]
from what I can see this error is known and came up in August 2018 the first time. 

> tflight [21:06 Uhr]
>seems like `parse_url` will work with utf-8 URLs in some instances on Ubuntu and other Linux flavors, but not under MacOS or Windows. That could be why it is working under Travis.
>
>https://github.com/symfony/symfony/issues/16776
>
>https://bugs.php.net/bug.php?id=52923

**Comment by l0gicgate** [comment]
Perhaps we should add a windows build @akrabat? You can do that as of October, 2018.

I cannot replicate this issue in my dev environment and I'm running Windows 10 Pro x64

**Comment by akrabat** [comment]
Windows build is fine with me. 

Mind you, given that the issue appears to be at the PHP level, I'm not sure that a Windows build helps much?

**Comment by l0gicgate** [comment]
It was determined that this issue was resolve on MacOS with running the command `export LANG=C` before running the test suite.
