### ISSUE TITLE
loaded classes will not be cached by an opcode cache because of autoload

### ISSUE THREAD

**Issue by xjia1** [slimphp/Slim#256]
`autoload` makes development more friendly since there is no need to explicitly include each class file. The downside of using `autoload` is that the loaded classes will not be cached by an opcode cache (if installed). Since Slim follows the front controller pattern, it is costly to load all the Slim classes on every page request. So maybe `Slim::autoload` should be replaced by some other mechanisms to `require` all the Slim classes at once?

**Comment by codeguy** [comment]
I'm doing some research and running a few tests using no opcode cache, using XCache, and using APC. Do you know of any URLs that confirm this? I don't doubt you, I'm just not as familiar with this issue and want to read more about it.

**Comment by xjia1** [comment]
See http://mwop.net/blog/245-Autoloading-Benchmarks.html

Compare the results of class map (`__DIR__`) and SPL closure, under both no-opcode-cache and with-opcode-cache conditions. When there is no opcode cache, SPL closure seems better. However, when there is opcode cache, class map outperforms SPL closure.

But also see http://stackoverflow.com/questions/1396501/do-php-opcode-cache-work-with-autoload#answer-1396538

Maybe by using APC the results will be relatively close to each other. You may feel free to close this issue because I think the difference may not be that big now. :-)

**Comment by codeguy** [comment]
Cool. I'm not entirely convinced the performance gain is worth the convenience lost. But I certainly learned something new :)
