### ISSUE TITLE
error handling of warnings and notices

### ISSUE THREAD

**Issue by mbohal** [slimphp/Slim#2562]
Hi
I'm running pretty standard Slim application. I'm trying to get it to treat `Warning` and `Notice` as Errors on my dev machine, but I do not know hot to do it.

I have added `error_reporting(E_ALL);` to my `index.php`.

It seems to me that the root of the problem is [here](https://github.com/slimphp/Slim/blob/a5a2da92d24c2c30384ff89d90008327f9040cb8/Slim/App.php#L410) where Warnings and Notices are not caught as `Throwable`.  I can get them to show by putting `ini_set('display_errors', 1);` in my `index.php`, but that is not very elegant as I want it to be used only during development. I think this is something that should be handled by the framework.

What is the recommended way of handling this? Are there any plans to improve this?

I think using [set_error_handler](https://secure.php.net/manual/en/function.set-error-handler.php) and [set_exception_handler](https://secure.php.net/manual/en/function.set-exception-handler.php) would be more robust. Would that be acceptable?

Thank you.

**Comment by chriseskow** [comment]
You can use `set_error_handler()` and throw an exception, such as PHP's built-in `ErrorException` which is meant precisely for this purpose:

```php
error_reporting(E_ALL); // set to whatever types of errors you want to be fatal

set_error_handler(function ($severity, $message, $file, $line) {
    if (error_reporting() & $severity) {
        throw new \ErrorException($message, 0, $severity, $file, $line);
    }
});
```

The exception would then be caught by Slim's error handler and can be handled as you wish.

**Comment by mbohal** [comment]
I see.That would probably work. I will use it now.

IMHO it is boilerplate code though. If these lines must be part of each project that wants to follow best practices, then they might as well be part of the framework.

Or is there some reason why not having `set_error_handler` in the framework is the better option?

**Comment by akrabat** [comment]
With a micro framework there is always a balance between what goes into it as it's not full-stack.

In this case, some people prefer their notices to go to their error error logs and not their Exception handling, so it's a choice each app makes.

**Comment by mbohal** [comment]
@ akrabat Would you accept a PR to the documentation describing the solution suggested by @chriseskow?

I've spent quite a bit of time with this and I had to look through the source code to figure out whats up. I understand your decision, but it might make users life easier if it is documented. 

What about the skeleton app?

**Comment by akrabat** [comment]
@mbohal Would definitely accept a documentation update! I'm mildly surprised it's not there already and certainly should be on the Error Handling page.

I'm on the fence about the skeleton. Maybe?

**Comment by mbohal** [comment]
@akrabat 
I would put it in the skeleton app, because I'm used to treating notices and warnings as errors during development and testing. I think it helps to write cleaner code.

But then again if it was up to me I would put it in the framework itself. So should I make a PR against the skeleton app?

**Comment by akrabat** [comment]
> So should I make a PR against the skeleton app?

I don't know. I can't promise you it'll be accepted, but it might be.

I also can't imagine developing without a `tail -f` on my PHP error log in a terminal window, so clearly we're all different!

**Comment by mandienk** [comment]
> You can use `set_error_handler()` and throw an exception, such as PHP's built-in `ErrorException` which is meant precisely for this purpose:
> 
> ```
> error_reporting(E_ALL); // set to whatever types of errors you want to be fatal
> 
> set_error_handler(function ($severity, $message, $file, $line) {
>     if (error_reporting() & $severity) {
>         throw new \ErrorException($message, 0, $severity, $file, $line);
>     }
> });
> ```
> 
> The exception would then be caught by Slim's error handler and can be handled as you wish.

Great, thx :-)

**Comment by plasid** [comment]
Lets get real honest here, Error handling in Slim is an overall terrible experience, tons of boilerplate code is needed - you would think that Error/Exception handling and security would be first priority and simple in any framework.
Note: The above solution for PHP warnings as well as on the official documentation does not working for all framework setup/boot techniques.
Slim Docs: "Warnings and Notices are not caught by default..." yet we catch everything else, or perhaps not, deal with your own fatal errors, why not just bubble ALL errors from within the framework and let the developer easily hook into/handle it.
(I've used Slim since early days)
