### ISSUE TITLE
ErrorMiddleware::handleException function passes wrong number of parameters to handler

### ISSUE THREAD

**Issue by lordrhodos** [slimphp/Slim#2564]
The new `ErrorMiddleware` currently passes 5 parameters to the handler:

https://github.com/slimphp/Slim/blob/bcf7df5129a3d126999cc73a6c961d35b83fce35/Slim/Middleware/ErrorMiddleware.php#L116-L122

The PR https://github.com/slimphp/Slim/pull/2398 documents four parameters, one of them being a `$response` object:

```php
...
$callableResolver = $app->getCallableResolver();
$errorMiddleware = new ErrorMiddleware($callableResolver, true, true, true);

$handler = function ($req, $res, $exception, $displayErrorDetails) {
    return $res->withJson(['error' => 'Caught MyNamedException']);
}
$errorMiddleware->setErrorHandler(MyNamedException::class, $handler);
$app->add($errorMiddleware);
```

This PR fixes several issues:

* pass `$response` object as second parameter to the handler with the status code set to the exceptions code
* update documentations

a working example looks like:
```php
$callableResolver = $app->getCallableResolver();
$errorMiddleware = new ErrorMiddleware($callableResolver, $responseFactory, true, false, true);
$handler = function (
    ServerRequestInterface $request,
    ResponseInterface $response,
    ApiException $exception,
    bool $displayErrorDetails,
    bool $logErrors,
    bool $logErrorDetails
) {
    $data = ['code' => $exception->getErrorCode(), 'description' => $exception->getErrorDescription()];
    $response = $response->withHeader('Content-Type', 'application/json');
    $response->getBody()->write(\json_encode($data));

    return $response;
};
$errorMiddleware->setErrorHandler(ApiException::class, $handler);
$app->add($errorMiddleware);
```

*Discussion*
The phpdocs on some methods mention the return type
https://github.com/slimphp/Slim/blob/bcf7df5129a3d126999cc73a6c961d35b83fce35/Slim/Middleware/ErrorMiddleware.php#L155-L156

but it is not enforced when calling the handler callable. I suggest to add correct return type declaration to the `ErrorMiddleware::handleException` function but wanted to get you opinion about it. Should this be enforced and if how would you have this enforced?

**Comment by l0gicgate** [comment]
The `Response` object needs to be created in the handler, hence why it isn't being passed. Also with the migration to PSR-15 Middleware the `Response` object won't be available at all via `ErrorMiddleware` anymore after #2555 is merged.

**Comment by lordrhodos** [comment]
@l0gicgate thx for pointing this out. I missed this in your PSR-15 middleware branch I guess. I was stumbling across this in the current `4.x` branch.
