### ISSUE TITLE
Dependency resolved at the beginning of pipeline - impossible to use `ServerRequestInterface` if it was changed in middleware

### ISSUE THREAD

**Issue by wdolek** [slimphp/Slim#2567]
It seems that dependency resolution is executed before all registered middlewares. (At least from how I reproduce the issue, I didn't go trough source code deeply)

_Steps to reproduce_:
1. create component class `A` which depends on `ServerRequestInterface` (... don't ask why... yet)
2. create controller class `B` which depends on `A`
3. register both components to container
4. add middleware, which determines language (from header, path, cookie, what not...) and sets attribute to current request
5. register route for controller `B`
6. ... run app

Using: `"slim/slim": "3.11.0"`

_Expected_:
Since there's no other dependency on component `A`, only from controller `B`, I would expect that resolution of `A` happens just before router tries to run request on controller `B`. That should already happen when we processed pipeline -> **component `A` can see attribute on request**

_Actual_:
Component `A` has different version of request, thus no attribute.

_Scenario_:
I'm building multi-language web app using:  `gettext/gettext`, `twig/twig`, ... and `cemerson/translator-twig-extension`. When creating Twig extension for translating, I need to provide translator. Translator must know what language I want to use. Language is defined by request (path, cookie, ...).

I was inspired by thread [Multi-language website with translated URI](https://discourse.slimframework.com/t/multi-language-website-with-translated-uri/2767).

```
$container['view'] = function (Container $c): Twig {
    // yada yada yada, registering slim twig extension with router
    // ...

    // and finally here I really need request so I can access its attribute set by language detecting middleware
    // (... TwigExtensionBuilder is my helper class which orchestrates all stuff around)
    $extensionBuilder = $c->get(TwigExtensionBuilder::class);
    $extension        = $extensionBuilder->build($c->request);
    $view->addExtension($extension);

    return $view;
};
```

_Sample code_:
You can try this behavior even without Twig related code, simple app requiring just `slim/slim` (3.11).
```
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;

$app       = new \Slim\App();
$container = $app->getContainer();

// dummy component
class LeComponent
{
    private $value;
    public function __construct(Request $request)
    {
        $this->value = $request->getAttribute('test-value');
    }
    public function getValue()
    {
        return $this->value;
    }
}

// controller
class LeController
{
    private $component;
    public function __construct(LeComponent $component)
    {
        $this->component = $component;
    }
    public function index(Request $request, Response $response, array $args)
    {
        return <<<RESOPONSE
value from dependency: {$this->component->getValue()}
value from request: {$request->getAttribute('test-value')}
RESOPONSE;
    }
}

// ioc
$container[LeComponent::class] = function (Container $c): LeComponent {
    return new LeComponent($c->request);
};

$container[LeController::class] = function (Container $c): LeController {
    return new LeController($c->get(LeComponent::class));
};

// middleware
$app->add(function ($request, $response, $next) {
    return $next(
        $request->withAttribute('test-value', '42'),
        $response->withHeader('Content-Type', 'text/plain')
    );
});

// controller
$app->get('/test', 'LeController:index')->setName('home');

$app->run();
```

_Workaround_ (for my case):
- it could be possible to access `view` component from another middleware and just create and register my Twig extension there... but it just looks funny (not right)
- abuse slim environment or introduce new context container (registered as singleton) to pass value around

**Comment by akrabat** [comment]
Dependency resolution happens as each middleware or route callable is needed when a key to the container is used in `add()` or `get()`/`post()`/`map()`.

However, this is not your issue. What you are seeing is due to the _immutable_ request object that Slim uses as it's  [PSR-7](https://www.php-fig.org/psr/psr-7/) compliant.

This means that, the request that is received into your middleware or route callable is _not_ the one that is in the container and that is intentional and by design. In fact, having a request object in the container was a mistake and Slim 4 will not register a request or response into the container.

Therefore you use middleware to extract the language and either pass it to the route callable via `withAttribute()` or update the Twig object's global language variable directly in middleware and then your extension should look for the language in the context when it comes to do its work.

e.g.

```php
class LanguageMiddleware
{
    public function __constuct(Twig_Environment $twig)
    {
        $this->twig = $twig;
    }

    public function __invoke ($request, $response, $next)
    {
        $lang = $this->determineLanguage($request);
        $this->twig->addGlobal('language', $lang);
        return $next($request, $response);
    }
}
```

Register a factory in the container for the middleware:

```php
$app->getContainer()[LanguageMiddleware::class] = funcion ($c) {
    return new LanguageMiddleware($c->get('twig'));
});
```

(This assumes that you've registered the `Twig_Environment` factory with the key `'twig'`)

Add middleware:

```php
$app->add(LanguageMiddleware::class);
```

**Comment by akrabat** [comment]
FWiW, questions like this are better asked on our [Slack](https://www.slimframework.com/#community) and/or our [discourse forum](http://discourse.slimframework.com/).

**Comment by wdolek** [comment]
@akrabat Thanks for quick reply! :) Yes, I noticed that request is immutable, just needed your post to realize connection between container and pipeline... (doh) I'm happy this is not a bug && sorry for polluting github issues.

**Comment by akrabat** [comment]
@wdolek I prefer that you ask rather than struggle for days! :)

Mostly commenting that unless you get lucky and someone's on GitHub when you post (like I was), you're more likely to get a response from the forums.
