### ISSUE TITLE
Header names should not have underscores

### ISSUE THREAD

**Issue by ghola** [slimphp/Slim#2573]
The headers present in the Slim 3.12.0 Request object make use of underscores, whereas those from other frameworks (eg. Diactoros) use dashes. This affects me as I'm trying to implement a reverse proxy with Buzz. I'm taking the Slim request, changing the host and passing it to Buzz with a Curl client. The resulting request hits the server with missing headers (headers containing underscore are not present in the request).

According to the HTTP standard headers with underscores are valid, however servers like nginx silently drop them (unless `underscores_in_headers on;` is set in it's configuration). I was wondering if this is a bug in Slim or if it's a deliberate decision. A whole class of issues could be avoided if dashes would be used instead of underscore.

Fore reference, here are the headers with slim:
```
  'HTTP_CONNECTION' => 
    array (size=1)
      0 => string 'keep-alive' (length=10)
  'HTTP_ACCEPT_ENCODING' => 
    array (size=1)
      0 => string 'gzip, deflate' (length=13)
  'HTTP_HOST' => 
    array (size=1)
      0 => string 'test.box' (length=17)
  'HTTP_ACCEPT' => 
    array (size=1)
      0 => string '*/*' (length=3)
  'HTTP_USER_AGENT' => 
    array (size=1)
      0 => string 'PostmanRuntime/7.6.0' (length=20)
  'HTTP_AUTHORIZATION' => 
    array (size=1)
      0 => string 'Basic YjU3NjkzZmQxNWJmMTQyOTlkN2E4M2M4MmMxZDc4YWEzZmQ5YmEzMDo=' (length=62)
  'HTTP_POSTMAN_TOKEN' => 
    array (size=1)
      0 => string '90971226-2211-41c1-bbb6-61c76ba39eb6' (length=36)
  'HTTP_CACHE_CONTROL' => 
    array (size=1)
      0 => string 'no-cache' (length=8)
  'HTTP_X_VALIDATE_RESPONSE' => 
    array (size=1)
      0 => string '1' (length=1)
  'CONTENT_TYPE' => 
    array (size=1)
      0 => string 'application/json' (length=16)
  'CONTENT_LENGTH' => 
    array (size=1)
      0 => string '58' (length=2)
  'PHP_AUTH_USER' => 
    array (size=1)
      0 => string 'b57693fd15bf14299d7a83c82c1d78aa3fd9ba30' (length=40)
  'PHP_AUTH_PW' => 
    array (size=1)
      0 => string '' (length=0)
```

And here they are with Diactoros:

```
  'connection' => 
    array (size=1)
      0 => string 'keep-alive' (length=10)
  'content-length' => 
    array (size=1)
      0 => string '58' (length=2)
  'accept-encoding' => 
    array (size=1)
      0 => string 'gzip, deflate' (length=13)
  'host' => 
    array (size=1)
      0 => string 'test.box' (length=17)
  'accept' => 
    array (size=1)
      0 => string '*/*' (length=3)
  'user-agent' => 
    array (size=1)
      0 => string 'PostmanRuntime/7.6.0' (length=20)
  'authorization' => 
    array (size=1)
      0 => string 'Basic YjU3NjkzZmQxNWJmMTQyOTlkN2E4M2M4MmMxZDc4YWEzZmQ5YmEzMDo=' (length=62)
  'postman-token' => 
    array (size=1)
      0 => string 'c850fc9e-0a56-4850-b602-97636ebaef74' (length=36)
  'cache-control' => 
    array (size=1)
      0 => string 'no-cache' (length=8)
  'x-validate-response' => 
    array (size=1)
      0 => string '1' (length=1)
  'content-type' => 
    array (size=1)
      0 => string 'application/json' (length=16)
```

**Comment by sridesmet** [comment]
This is because of the  $_SERVER variable.

See:
https://github.com/slimphp/Slim-Psr7/issues/11
https://github.com/slimphp/Slim/issues/2400

**Comment by ghola** [comment]
Thank you for pointing out the related issues. Closing this one.

**Comment by akrabat** [comment]
We must make sure that this is 100% fixed in [Slim-Psr7](https://github.com/slimphp/Slim-Psr7)!

**Comment by akrabat** [comment]
Note that there's nothing to stop you using Diactoros in Slim 3. Just replace the request and response in the container before you call run().

**Comment by sridesmet** [comment]
Would it be enough to use this middleware in Slim 3? Because that's what I'm doing now to create a reverse proxy. https://gist.github.com/sridesmet/a3e0a6f3a3515aaf5d5b4b42479e8c67

**Comment by akrabat** [comment]
> Would it be enough to use this middleware in Slim 3? Because that's what I'm doing now to create a reverse proxy. https://gist.github.com/sridesmet/a3e0a6f3a3515aaf5d5b4b42479e8c67

Looks good to me!
