### ISSUE TITLE
Variable route overwrites static route if defined first

### ISSUE THREAD

**Issue by AlexandraK** [slimphp/Slim#258]
`$router->map('/hello/:name', 'A')`
`$router->map('/hello/xxx', 'B')`

The A function will be executed instead of B.
I think static routes should have priority, regardless of the route order...

**Comment by xjia1** [comment]
If you DO mean to execute B before A, why not put the second line above your first line?

**Comment by AlexandraK** [comment]
that works, but if you want to implement some kind of plugin system in your application, and allow plugins to map routes, then this can cause problems

**Comment by xjia1** [comment]
You may use [hooks](http://www.slimframework.com/documentation/stable#slim-application-hooks-filters), especially one of the default hooks which is called `slim.before.router`.

**Comment by AlexandraK** [comment]
ok :P

**Comment by jonasraoni** [comment]
What's the feasibility of reopening this issue? =]

I expected the router to be smart enough to give preference to the static route instead of depending on ordering, which is more error-prone.

**Comment by l0gicgate** [comment]
@jonasraoni we use FastRoute as the underlying package to do routing. You should raise the issue on that repo instead.

**Comment by jonasraoni** [comment]
Yeah, I've seen it in the debugger... I just decided to use the cascade effect (I complain here, you complain there and they complain elsewhere) 😎

Well, I've just checked the FastRoute issues and looks like they've decided to keep it this way, so I won't disturb them.
