### ISSUE TITLE
[4.x] CallableResolver is misused as Container provider

### ISSUE THREAD

**Issue by bnf** [slimphp/Slim#2590]
#2555 introduced a new method `getContainer` for the `CallableResolverInterface`.
This is actually a hack that is used to hide a real dependency to the `ContainerInterface`. Classes that use `CallableResolverInterface::getContainer` need to be refactored to depend on `ContainerInterface` directly and the method `CallableResolverInterface::getContainer` should be removed again.

Here is an example how `Slim\Routable` uses the `CallableResolver` to fetch the container:
`$this->callableResolver->getContainer()`:
https://github.com/slimphp/Slim/blob/5311e952552dcd3c8c49a363c438649031965783/Slim/Routable.php#L63-L64

**Comment by l0gicgate** [comment]
There’s more changes coming to Route/RouteGroups/Routable that is upcoming as I discussed in #2583. It will deal with all of this.

**Comment by l0gicgate** [comment]
Closing #2591 has been merged
