### ISSUE TITLE
4.x - DeferredResolutionMiddleware should replicate CallableResolver behavior

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2592]
At the moment `CallableResolver` passes `ContainerInterface` to the constructor of a resolved object/callable:
- https://github.com/slimphp/Slim/blob/4.x/Slim/CallableResolver.php#L73
- https://github.com/slimphp/Slim/blob/4.x/Slim/CallableResolver.php#L97

In `4.x` that behavior is not honored in `DeferredResolutionMiddleware`
- https://github.com/slimphp/Slim/blob/4.x/Slim/Middleware/DeferredResolutionMiddleware.php#L65
- https://github.com/slimphp/Slim/blob/4.x/Slim/Middleware/DeferredResolutionMiddleware.php#L69-L70

Depending on what happens with #2591 we should add this functionality

**Comment by akrabat** [comment]
See Slack conversation: https://slimphp.slack.com/messages/C06SHUR19/p1551046761239000
