### ISSUE TITLE
4.x Need to remove all file header comment blocks

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2594]
We need to remove all of these comment blocks in the header files:
```php
/**
 * Slim Framework (https://slimframework.com)
 *
 * @link      https://github.com/slimphp/Slim
 * @copyright Copyright (c) 2011-2018 Josh Lockhart
 * @license   https://github.com/slimphp/Slim/blob/4.x/LICENSE.md (MIT License)
 */
```

A couple reasons:
- They provide absolutely no information or serve no purpose, the `LICENSE.md ` file has all the required information.
- We are just creating unnecessary chores for the maintainers since we have to update the copyright dates yearly. Much simple to update the `LICENSE.md` file yearly

Any opposing parties?

**Comment by froschdesign** [comment]
@l0gicgate 
>  They provide absolutely no information or serve no purpose…

I'm sorry, but this wrong. The header contains important informations:

* the name of the licence
* the link / reference to this licence
* the copyright

The problem is another: if the copyright and / or licence information is missing, your software can not be used by default because nobody knows if it's allowed.

But I'm not a lawyer or jurist and without someone with this expertise, the discussion is a waste of time – _in my opinion_!

Here my suggestion for this problem: https://github.com/malukenho/docheader

**Comment by tuupola** [comment]
IMO each source file should contain the license information. Then it is implicit what is licensed and with which license.

**Comment by RyanNerd** [comment]
[This may be helpful or muddy the water](https://softwareengineering.stackexchange.com/questions/125836/do-you-have-to-include-a-license-notice-with-every-source-file). In short the most accepted suggestion is that a license file is all that is needed and to follow the specifics of the license ([MIT](https://opensource.org/licenses/MIT) in the case of Slim) which in part states (emphasis mine):

> ...copyright notice and this permission notice shall be included in all copies or **substantial portions** of the Software.

The MIT license does not _require_ **every** module to have a license header; just the substantial portions. Also, these are instructions to _those who wish to distribute the software_; not necessarily the creators of the software.

I'm leaning toward @l0gicgate 's suggestion that this be removed from all files.

**Comment by akrabat** [comment]
The Apache foundation requires that every file has the license in it but not the copyright in their [policy](https://www.apache.org/legal/src-headers.html).

**Comment by akrabat** [comment]
The Software Freedom Law Center has useful information too in their [Managing copyright information within a free software project](https://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html) article.

In particular:

> Since copyright notices are not mandatory, there is generally no harm in under-using them, particularly if authorship is recorded in VCS logs. Over-use, however, can cause problems.

**Comment by akrabat** [comment]
Given that we don't require assignment of copyright to Josh, arguably the current copyright line is incomplete at best and wrong for some files.

I think that we should keep the block with the link to the license, but lose the copyright and link elements:

```php
/**
 * Slim Framework (https://slimframework.com)
 *
 * @license https://github.com/slimphp/Slim/blob/4.x/LICENSE.md (MIT License)
 */
```

**Comment by l0gicgate** [comment]
@akrabat sounds good! I’ll remove all the dated copyrights and link!
