### ISSUE TITLE
[WIP] 4.x - Doc Blocks Convention

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2601]
We need to agree on a convention for all doc blocs in the codebase. Right now it's an absolute mess.

I'm not a fan of the PSR-5 phpdoc standard but something that can be looked at for inspiration:
https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md

**For class, interface and trait declaration:**
```php
/**
 * <Type> <Class Name>
 * @package <Namespace>
 */
```
Example:
```php
/**
 * Interface CallableResolverInterface
 *
 * @package Slim\Interfaces
 */
```
<br/>

**For class constructor declaration (See variable names aligned using tabs)**:
```php
/**
  * <Class Name> constructor.
  * 
  * @param array     $property
  * @param string    $otherProperty
  */
```
<br/>

**For class property declaration (See that types are ordered alphabetically)**:
```php
/**
 * @var null|string
 */
protected $property;
```
<br/>

**For function declaration (See that types are ordered alphabetically, @return before @throw tag)**:
```php
/**
  * With a comment, a separating line has to be below the comment before parameter declaration
  *
  * @param    array        $property
  * @param    string       $otherProperty
  * @return   string
  * @throws   Exception 
  */
protected function (array $property, string $otherProperty)
```

**Comment by froschdesign** [comment]
@l0gicgate 
My suggestion is not to duplicate the type declaration of the parameters and omit everything if no additional description is added. 

> For class, interface and trait declaration...

Can be omitted if no description is added and do you really need `@package`?

> For class constructor declaration...
> For function declaration...

Can be omitted if no descriptions are added and it often duplicates the type declaration of the parameters.

> variable names aligned using tabs

This will not work with IDEs like PhpStorm. You can only align parameters and tag comments but you can not define the spaces between them.

**Comment by akrabat** [comment]
> For class, interface and trait declaration

I don't think we need @package.

One thing I would like is an explanation of why this class exists. i.e. what's the point of it?

**Comment by akrabat** [comment]
I would also like to remove any redundant `@param`, `@return` or `@var` for anything that's unambiguously type hinted.

**Comment by froschdesign** [comment]
@akrabat 
> One thing I would like is an explanation of why this class exists. i.e. what's the point of it?

That would be great and should be a must.

**Comment by l0gicgate** [comment]
> My suggestion is not to duplicate the type declaration of the parameters and omit everything if no additional description is added.
> Can be omitted if no descriptions are added and it often duplicates the type declaration of the parameters.

The biggest problem with that is that you end up with random doc blocks in the code base. What's the purpose to even have them. Let's just get rid of them altogether since everything is going to be typed anyway. 

> variable names aligned using tabs
> This will not work with IDEs like PhpStorm. You can only align parameters and tag comments but you can not define the spaces between them.

I'm not sure I understand what you're saying, my tab characters in PHPStorm is defined as 4 spaces for PHP. I guess I should have said spaces (1 tab = 4 spaces). It does require a bit of manual work to make it look pretty but that's fine it doesn't take that much effort to do it.

I was browsing for posts on this subject and found the following:
https://localheinz.com/blog/2018/05/06/cost-and-value-of-docblocks/

Y'all should give it a read.

**Comment by RyanNerd** [comment]
Just my two cents. Are there any places in Slim that use duck typing? For example: An argument in a method that could be a string **or** an array? (It seems I've run into this a few times in the Slim code).

Any methods that can not be strictly typed should probably be refactored to not do that, or if that isn't possible then this is a case where a detailed Doc Block should exist.

**Comment by l0gicgate** [comment]
@RyanNerd from my understanding, that is currently our goal. As little duck typing as possible, unfortunately some methods cannot be typed but we are trying to minimize those as much as possible.

**Comment by akrabat** [comment]
> The biggest problem with that is that you end up with random doc blocks in the code base. What's the purpose to even have them. Let's just get rid of them altogether since everything is going to be typed anyway.

When it's not typed (eg `App::add()`) then we need a docblock for our users and for PHPStan.

**Comment by froschdesign** [comment]
@l0gicgate 
> I'm not sure I understand what you're saying, my tab characters in PHPStorm is defined as 4 spaces for PHP.

You misunderstood me. Not the tab-size is a problem, but the automatic formatting with tools like PhpStorm. In PhpStorm you can not set the a tab to align the variable names. Please look at the [help of PhpStorm](https://www.jetbrains.com/help/phpstorm/settings-code-style-php.html#54e7331f) (direct link to Code Style for PHPDoc) or at the screenshot:

![phpstorm](https://user-images.githubusercontent.com/103362/53696638-54af3480-3dc9-11e9-87d0-8023359e332e.png)

Btw. an IDE is only one (easy) option for contributors. Any other coding standard fixer should also support the preferred format.

> It does require a bit of manual…

The goal should be _no_ manual work! 😉 

> Y'all should give it a read.

Already read last year and therefore my suggestions to avoid duplicates.
