### ISSUE TITLE
output buffer

### ISSUE THREAD

**Issue by AlexandraK** [slimphp/Slim#261]
In https://github.com/codeguy/Slim/blob/release-1.6.0/Slim/Slim.php#L1141

on line 1174, shouldn't that be `ob_get_clean()` instead of `ob_get_contents()`
because on line 1129 the body (output buffer) is supposed to be echoed...

**Comment by xjia1** [comment]
`ob_get_clean()` essentially executes both `ob_get_contents()` and `ob_end_clean()`. Once you reach line 1174, it will be the last time writing to the response,  so I think there's no need to call `ob_end_clean()` and `ob_get_contents()` is just fine.

**Comment by AlexandraK** [comment]
yes, but isn't the output kept twice in memory? In both the output buffer and the body property of "response"

**Comment by xjia1** [comment]
You cannot be sure about that. Compilers will do optimizations but you never know that. Anyway, the size of the body is relatively small and will be garbage collected as soon as you finish the request processing. So I think it doesn't matter. :-)

**Comment by JohZap** [comment]
Hi, sorry for the off-topic.
Ank, could you please contact me via e-mail? I need to ask you something, thanks in advance! :)
(keystrange@gmail.com)
