### ISSUE TITLE
\Slim\Http\Response: use static instead of self

### ISSUE THREAD

**Issue by thomasphansen** [slimphp/Slim#2614]
Hello, looks like there is a small bug in \Slim\Http\Response: since SlimResponse extends it, using the methods ->withJson(), ->withStatus(), ->withRedirect() and ->write()  will raise warning/error messages in PhpStorm (and probably other IDEs). Look at the following code, for example:
```
class Whatever
{
   ...

   /** @var SlimResponse **/
   private $response;

   public function doSomethingAndReturnRedirectResponse(string $url): SlimResponse
   {
      return $this->response->withRedirect($url, 302);
   }
}
```

This will make the IDE complain, because, withRedirect() return a Response object instead of SlimResponse. But the implementation of withRedirect() (as well as the other three mentioned previously) is using `clone` to create the new response - which means, the returned object is actually of type SlimResponse.

So, shouldn't these four methods have their php doc blocks stating `@return static`, instead of `this`?

**Comment by l0gicgate** [comment]
I'm not sure I understand.

`Slim\Response` docblocks seem fine. Their docblocks all say they return `static`
- `Response::withStatus()`: https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Response.php#L189
- `Response::withHeader()`: https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Response.php#L270
- `Response::withRedirect()`: https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Response.php#L321
- `Response::withJson()`: https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Response.php#L350

Am I not looking at the right thing?

**Comment by l0gicgate** [comment]
@thomasphansen I'm closing this issue, feel free to re-open if you have a valid counter-point to my reply above.

**Comment by thomasphansen** [comment]
You are totally right. The library I use (that extends Slim) is locking the version of it to 3.5.0, which is unacceptably old, and didn't notice that this wasn't an issue in your current versions (actually, since 24.01.2017!). I'll talk to the library maintainer and ask for an upgrade. Thanks for your time!
