### ISSUE TITLE
Slim 3 Php-View 

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2617]
I've use slim for make only url rewrite and friendly url's, it's a good framework, love it!!! 
But need make redirect for a page after user make login! i've using php-view! 
In pure php: header("Location: views/dashboard.php"), but on slim, how make this?
Trying:  return $response = new Slim\Http\Response::withRedirect('Location', $router->pathFor('dashboard')) but don't works! and I don't use MVC!!!

**Comment by tflight** [comment]
The `withRedirect` method takes two arguments, the URL and then the status code. See the [Returning a Redirect](https://www.slimframework.com/docs/v3/objects/response.html#returning-a-redirect) documentation for more info. So it would look more like this:

```php
withRedirect($router->pathFor('dashboard'), 301);
```

**Comment by ghost** [comment]
Ok! Thanks!!
