### ISSUE TITLE
HEAD is assumed to be the same as GET

### ISSUE THREAD

**Issue by xjia1** [slimphp/Slim#262]
See https://github.com/codeguy/Slim/blob/master/Slim/Slim.php#L406 and https://github.com/codeguy/Slim/blob/release-1.6.0/Slim/Slim.php#L392 .

HEAD returns with no response body. And their semantics is different. HEAD is usually used to see if something is present. For example, HEAD for checking whether a user exists, and GET for the user information.

So I think it's better to include a separate routing method called `head`.

**Comment by alganet** [comment]
The HTTP protocol states exactly this. A HEAD request should be identical as a GET request but without body. This means the same headers should be sent, and if the user sends a header inside the application this header should be sent as well.

A separate overriding of this behavior declaring a custom `head` method though is desirable for users who want to tweak the application performance to not run the routed function.

**Comment by xjia1** [comment]
Isn't it better if no HEAD routes matched, defaults to the GET ones?

**Comment by codeguy** [comment]
It is my understanding that, as @alganet said, a HEAD request for a given resource should return a response identical to a GET request of the same resource but without a body. It is necessary for Slim to execute the GET resource's route/callable in case the route attaches custom headers to the response.

I certainly appreciate your argument, but I don't think the time/effort saved implementing HEAD-only routes is worthwhile.
