### ISSUE TITLE
AppFactory with PSR-7 Auto Detection

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2621]
Need to create an `AppFactory` to create an instance of `App` that detects installed PSR-7 and PSR-7 Factory and auto-wires it all for the user.

**Comment by odan** [comment]
Why not use the (Pimple) container as a factory? Then we can define all dependencies explicit. I think we don't need this kind of "autowiring". This "black magic" is what I don't like in other frameworks.

**Comment by l0gicgate** [comment]
Pimple is not a dependency on Slim 4 @odan. We need to make this not depend on a container as it is optional.

**Comment by akrabat** [comment]
Key thing for me is ensuring that it's clear what's going on and that it fades away if the user explicitly sets their PSR-7.
