### ISSUE TITLE
Slim Framework and Google App Engine Standard PHP7.2: How to make it work ?

### ISSUE THREAD

**Issue by dev-mansonthomas** [slimphp/Slim#2624]
Google is taking Slim framework as a very basic example, when introducing the Google App Engine Standard with PHP 7.2 : (which is great advertising for Slim)

https://cloud.google.com/blog/products/application-development/introducing-php-7-2-runtime-on-the-app-engine-standard-environment

But the documentation of Slim Framework says that a mod_rewrite must be used, and no example is given for Google App Engine standard.

About mod_rewrite, they only provide a PHP alternative that dates back to PHP55 engine sample:

https://cloud.google.com/appengine/docs/standard/php/config/mod_rewrite

So I wonder if I can have a real app that use Slim Framework, working on Google App Engine Standard.

How can I make my Slim Application application working on GAE Standard ?

I'm not sure I'll be able to implement a mod_rewrite.php as google suggest.

Any suggestions ?

**Comment by odan** [comment]
`mod_rewrite` is important for the Apache webserver in combination with a [.htaccess](https://github.com/odan/prisma/blob/master/public/.htaccess) file to redirect the internal traffic to the [index.php](https://github.com/odan/slim-hello-world/blob/master/public/index.php) front controller. But google does that job for us.

> By default, App Engine serves all traffic to either public/index.php or index.php

According to the [docs](https://cloud.google.com/blog/products/application-development/introducing-php-7-2-runtime-on-the-app-engine-standard-environment), the other settings are just optional. Have you tried to create a [public/index.php](https://github.com/odan/slim-hello-world/blob/master/public/index.php) file?

[Example App](https://github.com/odan/slim-hello-world)

**Comment by dev-mansonthomas** [comment]
Hi Daniel,

 Thanks for your reply!

 I use the app.yaml
entry_point: serve public/rest/index.php
to point to the correct path.

I need the path to start with /rest/ (or I need to change all my Angularjs
Resources, not a problem, but if I can avoid making changes, the better).

but anyway,
whether it's in public/rest/index.php or public/index.php
I've tested both as per your suggestion and :

if I make the following http call :

/rest/authenticate
or
/authenticate

I get a 404 from GAE.

My understanding is that with URL Rewriting of NGINX (GAE Flex) or Apache
(my local dev machine), those path are transformed as

/rest/index.php?authenticate (or /rest/index.php/authenticate, I'm not sure)

which doesn't seems to be the case with GAE Standard.

I'm also using a dispatch.yaml to route the http call that start with
/rest/ to the backend service, and the rest to another engine for the
angularjs app.

I'll make some test later today without the dispatch.yaml.

I'm also trying to simulate mod_rewrite with a php script as suggested in
the GAE documentation, but I face a strange behaviour. where I need the
path to have an extra leading '/', and this have quite an impact on my code

I've posted some details here:
https://discourse.slimframework.com/t/google-app-engine-standard-slim-configuration/3079

**Comment by dev-mansonthomas** [comment]
I end up having it working, but I had to adapte the routes and some internal code depending the code is running on GAE or Apache (local dev), as on GAE, the REQUEST_URI is prefixed with /rest/ while it's not on APACHE (although the script path has the /rest/prefix).

weird, but it's not working on Google App Engine Standard without any explicit URL rewriting, and using dispatch.yaml to spilt the traffic between the angularjs app and the backend (slim)
