### ISSUE TITLE
Deprecate Slim 3 style callables in Slim 4

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2626]
We haven't been able to type hint any callables throughout the codebase because we still support the callable format used in Slim 3:
https://github.com/slimphp/Slim/blob/4.x/Slim/CallableResolver.php#L59 which is equivalent to a string formatted like so: `Class:method` 

This just seems like synthax sugar to me which doesn't positively outweigh the benefits of typehinting. I'm not sure exactly as I didn't implement them but I'm definitely open to feedback from the community if anyone feels there's still a need for them.

My main reasons for wanting to deprecate them as of Slim 4 is so we can type hint callables everywhere in the codebase as well as there are already enough methods in my opinion to declare a callable:
- `Foo::class` works when `__invoke()` is implemented
- `my_callback_function` global function name
- `function () {...}` anonymous functions
- `['Class', 'method']` an array with the class name and method
- `[$object, 'method']` an array with an instantiated object and method name

**Comment by akrabat** [comment]
Im general, I'm in favour of `controller:action` as it's a clean way to define an action method in a lazily instantiated class.

I'm open to alternatives as long as they are easy for write in the `routes.php` file.

**Comment by l0gicgate** [comment]
We have to make a hard choice here @akrabat as we were discussing internally yesterday. This is the main question that arose from our conversation:

How do you deprecate `Class:method` strings for route handlers and force the `callable` typehint in our function signatures without removing the functionality entirely and keeping the synthax short?

**We need the following characteristics to the changed behavior:**
- Ability to lazy load route handlers
- Ability to instantiate the object via a DIC and call a specific method of the instantiated object
- Or ability to instantiate and pass container into the constructor, then call a specific method of the instantiated object

**Problems:**
A valid `callable` type only works for statically called methods `Class::staticMethod`, `['Class', 'staticMethod']`, anonymous functions or methods on an already instantiated object `[$object, 'method']`

**One way it could be done:**
Get a generator function from `$app` that enables you to generate callables on the fly while declaring route handlers or middleware that will be resolved by `CallableResolver` at the time of execution (lazy load):
```php

class App {
    ...
    /**
     * This function returns a generator function that returns an anonymous function
     * bound to CallableResolver that returns the result of resolved callable when executed
     */
    public function getDeferredResolverGenerator(): Closure
    {
        return (function ($callable) {
            return (function () use ($callable) {
                $args = func_get_args();
                $resolved = $this->resolve($callable);
                return $resolved(...$args);
            })->bindTo($this);
        })->bindTo($this->callableResolver);
    }
}

$g = $app->getDeferredResolverGenerator();

$app->get('/hello', $g('Class:Method'));
```

**Comment by akrabat** [comment]
To my mind, I'd rather it was cleaner for the user and having a weird function isn't it when this "just works" in Laravel, Symfony, etc.

Maybe have a set of sibling methods that are type-hinted for users who care?

**Comment by l0gicgate** [comment]
Besides strict type hinting I suppose I don't see any other upside to removing this.

**Comment by glen-84** [comment]
Is it possible to use a Callable in Slim 4, like `[Some::class, 'action']`?

Concatenating is a bit ugly. 🙂

**Comment by adriansuter** [comment]
Hi @glen-84 

Of course, why not? Callables are supported (even closures).

**Comment by glen-84** [comment]
@adriansuter My apologies, I was reading [this section](http://slim-website.lgse.com/docs/v4/objects/routing.html#container-resolution) of the documentation, and didn't realize that I had missed the earlier section on route callbacks. 🤦‍♂
