### ISSUE TITLE
Netbeans debug only provides path via a parameter

### ISSUE THREAD

**Issue by keithy** [slimphp/Slim#2627]
Netbeans insists on using index.php as an access point, and providing the path via the parameter. Slim 3 is not using that parameter, but rather the uri->getPath()

**Comment by l0gicgate** [comment]
This is not a relevant issue to the Slim codebase. This is behavior specific to use of Netbeans.

**Comment by keithy** [comment]
As indicated, I submitted this to document the issue.

It has nothing to do with Netbeans itself. The difficulty with netbeans is that it offers no alternative means to invoke. I placed Netbeans in the issue title to help others who may have had the same problem.

The issue being that when the framework is invoked like so: index.php?path=/some/path.php slim does not pick up the path from the parameter. Whether it should or not is another question. I think it should, you may disagree. If you do, then this would be a suitable place to document it and explain why, because I am not understanding.
