### ISSUE TITLE
Sessions are forced to be started

### ISSUE THREAD

**Issue by xjia1** [slimphp/Slim#263]
See https://github.com/codeguy/Slim/blob/master/Slim/Slim.php#L205 , session will always be started. However, sessions are not required by every page.

Due to the limitation of PHP that only a single page can be reading from or writing to a single session, this auto-starting session management potentially slows down the overall response time for a specific user, especially when AJAX is involved and requests are sent concurrently but responded mostly sequentially.

**Comment by StJudeWasHere** [comment]
This is fixed in branch 1.6.0. Slim won't automatically start the session.
