### ISSUE TITLE
405 error with backbonejs

### ISSUE THREAD

**Issue by zekenie** [slimphp/Slim#264]
I've been hitting my head against a wall for a while now. I've got MAMP setup with php 5.3.2. I'm making a backbone.js/slim app. When backbone tries to send put requests to slim, slim responds 405 method not allowed. Any suggestions?

I've tried a few things. For one, there's already a pull request:https://github.com/codeguy/Slim/pull/252 related to this. I've taken the suggested code and implimented in. No success.

I've made sure that apache is watching for .htaccess files.

I've made sure that the .htaccess file that ships with slim is in the directory.

**Comment by codeguy** [comment]
The only reason Slim will respond with a 405 is that if one of your Slim app's routes matches the request URI but not the request method. Can you post the request URI you are using, and then post the PHP code of the Slim app's route that should be invoked?

**Comment by codeguy** [comment]
Please post your code to a new thread at http://help.slimframework.com and I'll continue helping you there.
