### ISSUE TITLE
[Feature request] Pass the dynamic URL argument as a string/int

### ISSUE THREAD

**Issue by Ayesh** [slimphp/Slim#2650]
I would like to suggest a feature, that we can declare a router that accepts a URL argument (Say, `posts/(\d)+`), and have the call back function directly receive the URL argument as an integer/string instead of an array. 

This will help to have a slightly cleaner code base with Parameter typing applied directly at the function declaration. 

This will be a breaking change, so we will probably need an additional call to the route method to mark that we expect the exact arguments instead of the array. 

Of this sounds like a good feature that others might benefit from too, I'd be happy to work on a PR.

Thank you.

**Comment by l0gicgate** [comment]
You can already do that by creating your own route invocation strategy. It wouldn’t be a BC change as the default invocation strategy would stay the same but could be changed to this one if a user wanted a more stricter typed approach for their route callables. 

I want to add that `RequestResponseArgs` strategy does this already, but does not type the parameters.

Example on how to do this in Slim 4:
```php
use Slim\Factory\AppFactory;
use Slim\Handlers\Strategies\RequestResponseArgs;

$app = AppFactory::create();
$routeCollector = $app->getRouteCollector();
$routeCollector->setDefaultInvocationStrategy(new RequestResponseArgs());

$app->get('/hello/{name}', function ($request, $response, $name) {
    return $response->write($name);
});
```
