### ISSUE TITLE
Risky testMoveToStream()

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2655]
PHPUnit marks the following test as risky (no asserts). Could that be removed?

https://github.com/slimphp/Slim/blob/203dd4e768cb0c1cf634e01e2521a95699017c8d/tests/Http/UploadedFilesTest.php#L217

**Comment by l0gicgate** [comment]
Instead of removing it, we should implement it.

**Comment by adriansuter** [comment]
This would be tricky.

Currently the test case uses the stream `php://temp`. But the php documentation states in example 5 of https://www.php.net/manual/en/wrappers.php.php

> **php://memory and php://temp are not reusable**

So we can't use this stream to check if `\Slim\Http\UploadedFile::moveTo()` worked as expected, can we?

A possible solution would be to write a custom stream wrapper or to use the stream `php://output`. So for example:
```php
    public function testMoveToStream()
    {
        $uploadedFile = $this->generateNewTmpFile();
        $contents = file_get_contents($uploadedFile->file);

        ob_start();
        $uploadedFile->moveTo('php://output');
        $movedFileContents = ob_get_clean();

        $this->assertEquals($contents, $movedFileContents);
        $this->assertFileNotExists($uploadedFile->file);
    }
```
Is it okay to use output buffering in a PHPUnit test case?

**Comment by l0gicgate** [comment]
It's totally fine to use output buffering in a test case. That test looks good to me, not sure why it was never implemented in the first place.

**Comment by adriansuter** [comment]
Alright, I will create a pull request.
