### ISSUE TITLE
getBasePath() is not part of PSR-7

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2658]
The property `uri` is of type `\Psr\Http\Message\UriInterface`. In the following line the method `getBasePath()` is called. This method is not part of the PSR-7 standard and therefore is not defined in `\Psr\Http\Message\UriInterface`.

https://github.com/slimphp/Slim/blob/203dd4e768cb0c1cf634e01e2521a95699017c8d/Slim/Http/Request.php#L500

However the method is defined in `\Slim\Http\Uri`, of which type the property usually is.

Possible solutions:
- Check that `$this->uri` is of that type.
- Check that `$this->uri` has the method `getBasePath()`.
- The base path has to be injected into the Request from somewhere else.

**Comment by l0gicgate** [comment]
Good catch. Will you create a PR for this? If not, I can.
