### ISSUE TITLE
Slim\App docblocks have missing throws annotations

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2666]
The class `\Slim\App` (3.x) has many methods that may throw exceptions, but their docblocks do not contain corresponding `throws` annotations.

Should we add those annotations or would that break installations?

**Comment by l0gicgate** [comment]
I think that we can add those annotations. It shouldn't break anything.

**Comment by RyanNerd** [comment]
@adriansuter @l0gicgate I have some time on my hands. I'll see if I can spin up a PR for this today.

**Comment by adriansuter** [comment]
Great.
