### ISSUE TITLE
Unit tests failing building Fedora RPM

### ISSUE THREAD

**Issue by trasher** [slimphp/Slim#2669]
Hi,

I'm helping on Slim packaging on fedora from a while. Since 3.12, unit tests are failing in the build environment :/
On this try, PHP 7.3.5 RC1 is used, but result is the same with 7.2.17.

Log can be found here:
https://kojipkgs.fedoraproject.org//work/tasks/3317/34483317/build.log

You can find software versions at:
https://kojipkgs.fedoraproject.org//work/tasks/3317/34483317/root.log

Any idea what goes wrong? Thank you :)

**Comment by l0gicgate** [comment]
It's hard to diagnose what's going on since the builds for that release pass just fine. The tests that are failing weren't affected by code from that release. I'm not sure what's going on here.

The failing tests are:
```bash
1) Slim\Tests\AppTest::testResponseReplacesPreviouslySetHeaders
Failed asserting that Array &0 () is identical to Array &0 (
    0 => Array &1 (
        'header' => 'X-Foo: baz1'
        'replace' => true
        'status_code' => null
    )
    1 => Array &2 (
        'header' => 'X-Foo: baz2'
        'replace' => false
        'status_code' => null
    )
    2 => Array &3 (
        'header' => 'HTTP/1.1 200 OK'
        'replace' => true
        'status_code' => 200
    )
).

2) Slim\Tests\AppTest::testResponseDoesNotReplacePreviouslySetSetCookieHeaders
Failed asserting that Array &0 () is identical to Array &0 (
    0 => Array &1 (
        'header' => 'Set-Cookie: foo=bar'
        'replace' => false
        'status_code' => null
    )
    1 => Array &2 (
        'header' => 'Set-Cookie: bar=baz'
        'replace' => false
        'status_code' => null
    )
    2 => Array &3 (
        'header' => 'HTTP/1.1 200 OK'
        'replace' => true
        'status_code' => 200
    )
).

3) Slim\Tests\RouterTest::testCacheFileExistsAndIsNotReadable
Failed asserting that exception of type "\RuntimeException" is thrown.
```

**Comment by trasher** [comment]
Are there chances some of those failing tests requires an internet connexion? The build environment does not have access to internet.

Since project tests are OK, and usage seems ok; I can find a way to ignore them on packaging side at last; this is not a blocker ;)

Thank you.

**Comment by l0gicgate** [comment]
@trasher no all tests can be run offline. This is kind of weird. Skipping those tests probably isn’t a good idea since that would mean Slim would break when trying to access that functionality. I’m not entirely sure what the best solution is here.

**Comment by trasher** [comment]
Well, I've already see tests failing only on the build env for another project I'm working on; and I've not been able to understand why :/

Packages are built in a chrooted environment, it fails on projects servers  and on my local computer. But tests are OK from the git clone.
I wonder if something is missing in the chroot, I'll check if dependencies are correct.

Let me know if you need informations or want me to try something.

**Comment by l0gicgate** [comment]
is there any way for me to get a copy of the build env from within a container or access to a virtual box somewhere so I can fiddle with things and see what’s going on?

**Comment by trasher** [comment]
The software used to build packages is called mock:
https://github.com/rpm-software-management/mock

The SRPM is mandatory (an archive that contains SPEC file and sources):
https://kojipkgs.fedoraproject.org//work/tasks/3294/34483294/php-slim3-3.12.1-1.fc31.src.rpm

I've never used it outside of the standard build process, but it looks like it can be run from docker:
https://github.com/rpm-software-management/mock/wiki#mock-inside-docker

An alternative would be to install a minimal fedora in a virtual machine and install mock in it.

Hope that helps.

**Comment by l0gicgate** [comment]
@trasher I think I found the issue. So it looks like the SPEC file creates its own bootstrapping files and omits from including the file `tests\Assets\PhpFunctionOverrides.php`

**In your spec file you need to change the following lines from:**
```bash
%check
sed -e \
        "s|dirname(__DIR__) . '/vendor/autoload.php'|'%{buildroot}%{slim_home}/autoload.php'|" \
        -e "s|\$autoloader->addPsr4.*$|require 'autoload.php';|" \
        -i tests/bootstrap.php
```

**To:**
```bash
%check
sed -e \
        "s|dirname(__DIR__) . '/vendor/autoload.php'|'%{buildroot}%{slim_home}/autoload.php'|" \
        -e "s|\$autoloader->addPsr4.*$|require 'autoload.php';\nrequire __DIR__ . '/Assets/PhpFunctionOverrides.php';|" \
        -i tests/bootstrap.php
```

I'm not entirely sure if it'll work or not but it looks like it's not loading the files from the `autoload-dev` section from the `composer.json` file since it's generating the autoloaders manually.

```
"autoload-dev": {
    "files": [
        "tests/Assets/PhpFunctionOverrides.php",
        "tests/Assets/PhpHttpFunctionOverrides.php" // This file will be added on the next release 3.12.2
    ]
},
```

**Comment by trasher** [comment]
Good catch, thank you! I did not check the dev part of the composer file; and I should have

Since tests are ok now, I can proceed the update. Thank you very much!
