### ISSUE TITLE
RouteCollector add optional cacheFile parameter to constructor

### ISSUE THREAD

**Issue by bednic** [slimphp/Slim#2688]
RouteCollector has method setCacheFile accepting string path, but this cost additional calls in setup of application, it's not possible set cache file trough DI simply. If constructor will contain optional cacheFile parameter it will much simpler. I mean now it's not impossible but tough, much more line of codes 🙂

**Comment by l0gicgate** [comment]
I'm open to that for sure. Feel free to raise a PR. We can add it as the last parameter of the current constructor.
