### ISSUE TITLE
Error With URL-Encoded Octothorpes

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#269]
See http://help.slimframework.com/discussions/problems/102-parameter-with-url-encoded-is-being-ignored

**Comment by StJudeWasHere** [comment]
I guess we could get rid of $_SERVER['PATH_INFO'] and rely on $_SERVER['REQUEST_URI'] instead. What do you think?

**Comment by h9k** [comment]
Thank you very much. I can confirm that it fixes the issue :)

**Comment by codeguy** [comment]
Thanks guys. I'll pull this into 1.6.0 before release.
