### ISSUE TITLE
getError() after update not working

### ISSUE THREAD

**Issue by julzlegaspi** [slimphp/Slim#2698]
I got this error after I run `composer update` 
Upload file not working anymore. 
`
Call to a member function getError() on string`

**Comment by l0gicgate** [comment]
Which version of Slim, can you isolate the bit of code that doesn't work and show it?

**Comment by julzlegaspi** [comment]
I am using Slim 3. I just followed the upload file example from [slim 3 docs](https://www.slimframework.com/docs/v3/cookbook/uploading-files.html) then I run a `composer update`  after that I got an error

**Comment by julzlegaspi** [comment]
before I run a composer update it was working fine I can able to upload a file from a form

**Comment by l0gicgate** [comment]
I need to see some code.. it sounds like you're trying to call `getError()` on an string.

**Comment by julzlegaspi** [comment]
Ok here is my code

```php
namespace App\Controllers;

use Psr\Http\Message\{
    ServerRequestInterface as Request, 
    ResponseInterface as Response
};
use App\Controllers\Controller;
use App\Models\UploadFile;
use Slim\Http\UploadedFile;

class RequestFormController extends Controller
{
    public function postRequest (Request $request, Response $response) 
    {
        // handle single input with multiple file uploads
        $directory = $this->c->get('upload_directory');

        $uploadedFiles = $request->getUploadedFiles();
        foreach ($uploadedFiles['file'] as $uploadedFile) {
            if ($uploadedFile->getError() === UPLOAD_ERR_OK) {
                $filename = $this->moveUploadedFile($directory, $uploadedFile);
            }
        }
    }
}
```

**Comment by l0gicgate** [comment]
can you do `var_dump($uploadedFiles)` and show me the output?

**Comment by julzlegaspi** [comment]
![error](https://user-images.githubusercontent.com/13739471/58069137-b3b16800-7bc6-11e9-89dd-be6abca473f9.png)

**Comment by froschdesign** [comment]
@julzpalomiano 
> `foreach ($uploadedFiles['file'] as $uploadedFile)`

This is wrong, use instead:

`foreach ($uploadedFiles as $uploadedFile)`

Please compare with the interface `Psr\Http\Message\ServerRequestInterface` and your result:

> An array tree of UploadedFileInterface instances

https://www.php-fig.org/psr/psr-7/#321-psrhttpmessageserverrequestinterface

**Comment by julzlegaspi** [comment]
@froschdesign 

I think I did the correct way because I want to upload multiple files. 

@l0gicgate 

Thank you for your time. working fine now I just forgot to put brackets in my input field. 

`<input type="file" class="form-control-file" name="file" id="attachment" multiple="multiple">` this will result an error I just fixed by putting `[]` in my field name `name="file[]"`

**Comment by l0gicgate** [comment]
@julzpalomiano you probably forgot to put the brackets in the input name.

**As per the example**
```html
<p>
    <label>Add files (up to 2): </label><br/>
    <input type="file" name="example2[]"/><br/>
    <input type="file" name="example2[]"/>
</p>
```

When the brackets aren't present it will return a single file versus an array of files.

**Comment by froschdesign** [comment]
@julzpalomiano 
> I think I did the correct way because I want to upload multiple files.

This information is missing in your issue description!

**Comment by julzlegaspi** [comment]
@froschdesign my bad. Thank you.
