### ISSUE TITLE
Project doesn't follow the uniform package layout

### ISSUE THREAD

**Issue by hopeseekr** [slimphp/Slim#2700]
## The Problem
This project odes not conform to the uniform package layout for PHP projects. This, among other things, hinders the running of certain automated processes (such as the code analyzer of the Bettergist Collective) and also adds cognitive load to contributing developers.

## The Solution
Rename the `Slim` directory to `src`.

**Comment by l0gicgate** [comment]
That sounds like a flaw with the code analyzer of the Bettergist Collective. Being bound to a specific directory structure sounds like a terrible way to develop a code analyzing tool.

Also, this package follows PSR-4 namespacing specifications. Nowhere is it specified that "src" should be the folder containing the source.

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md
