### ISSUE TITLE
Robust handling of line termination in headers

### ISSUE THREAD

**Issue by mfprimo** [slimphp/Slim#272]
Hi,
  some buggy clients send header fields with line termination different from the canonical CRLF.
It is easy to cope with them adding a trim():

```
            $headers[$name] = trim($value);
```

in the Request::loadHttpHeaders() method.

**Comment by codeguy** [comment]
Cool. If you want to send me a pull request you can get credit for the fix.

**Comment by mfprimo** [comment]
Done.
