### ISSUE TITLE
SLIM framework. was accepting data in localhost but not in 000webhost. 

### ISSUE THREAD

**Issue by oyyarko** [slimphp/Slim#2724]
I am making a signup/login page for my android app. It was working good until i uploaded it into live web hosting. it is giving this error,

 Call to a member function prepare() on null
![image](https://user-images.githubusercontent.com/21188762/59333601-4f417e80-8d16-11e9-861a-9b9493bf56f6.png)

**Comment by l0gicgate** [comment]
Which version of Slim are you using? Which version of PHP is on your server? Can you show the entire stack trace?

Thanks

**Comment by oyyarko** [comment]
PHP version --- 7.2
slim - 3

**Comment by oyyarko** [comment]
<html>
    <head>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
        <title>Slim Application Error</title>
        <style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style>
    </head>
    <body>
        <h1>Slim Application Error</h1>
        <p>The application could not run because of the following error:</p>
        <h2>Details</h2>
        <div>
            <strong>Type:</strong> Error
        </div>
        <div>
            <strong>Message:</strong> Call to a member function prepare() on null
        </div>
        <div>
            <strong>File:</strong> /storage/ssd5/304/3403304/public_html/includes/DbOperation.php
        </div>
        <div>
            <strong>Line:</strong> 122
        </div>
        <h2>Trace</h2>
        <pre>#0 /storage/ssd5/304/3403304/public_html/includes/DbOperation.php(17): DbOperation-&gt;isUserExist('arko13@gmail.co...')
#1 /storage/ssd5/304/3403304/public_html/public/index.php(28): DbOperation-&gt;registerUser('arko', 'arko13@gmail.co...', '1300', '798974')
#2 [internal function]: Closure-&gt;{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /storage/ssd5/304/3403304/public_html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /storage/ssd5/304/3403304/public_html/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /storage/ssd5/304/3403304/public_html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /storage/ssd5/304/3403304/public_html/vendor/slim/slim/Slim/Route.php(334): Slim\Route-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /storage/ssd5/304/3403304/public_html/vendor/slim/slim/Slim/App.php(515): Slim\Route-&gt;run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /storage/ssd5/304/3403304/public_html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App-&gt;__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /storage/ssd5/304/3403304/public_html/vendor/slim/slim/Slim/App.php(405): Slim\App-&gt;callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /storage/ssd5/304/3403304/public_html/vendor/slim/slim/Slim/App.php(313): Slim\App-&gt;process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /storage/ssd5/304/3403304/public_html/public/index.php(166): Slim\App-&gt;run()
#12 {main}</pre>
        <div style="text-align: right;position: fixed;z-index:9999999;bottom: 0;width: auto;right: 1%;cursor: pointer;line-height: 0;display:block !important;">
            <a title="Hosted on free web hosting 000webhost.com. Host your own website for FREE." target="_blank" href="https://www.000webhost.com/?utm_source=000webhostapp&utm_campaign=000_logo&utm_medium=website&utm_content=footer_img">
                <img src="https://cdn.000webhost.com/000webhost/logo/footer-powered-by-000webhost-white2.png" alt="www.000webhost.com">
            </a>
        </div>
        <script>function getCookie(e){for(var t=e+"=",n=decodeURIComponent(document.cookie).split(";"),o=0;o
            <n.length;o++){for(var i=n[o];" "==i.charAt(0);)i=i.substring(1);if(0==i.indexOf(t))return i.substring(t.length,i.length)}return""}getCookie("hostinger")&&(document.cookie="hostinger=;expires=Thu, 01 Jan 1970 00:00:01 GMT;",location.reload());var notification=document.getElementsByClassName("notice notice-success is-dismissible"),hostingerLogo=document.getElementsByClassName("hlogo"),mainContent=document.getElementsByClassName("notice_content")[0],newList=["Powerful and Easy-To-Use Control Panel.","1-Click Auto Installer and 24/7 Live Support.","Free Domain, Email and SSL Bundle.","5x faster WordPress performance","Weekly Backups and Fast Response Time."];if(0
                <notification.length&&null!=mainContent){var googleFont=document.createElement("link");googleFontHref=document.createAttribute("href"),googleFontRel=document.createAttribute("rel"),googleFontHref.value="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600",googleFontRel.value="stylesheet",googleFont.setAttributeNode(googleFontHref),googleFont.setAttributeNode(googleFontRel);var css="@media only screen and (max-width: 768px) {.web-hosting-90-off-image-wrapper {position: absolute;} .notice_content {justify-content: center;} .web-hosting-90-off-image {opacity: 0.3;}} @media only screen and (min-width: 769px) {.notice_content {justify-content: space-between;} .web-hosting-90-off-image-wrapper {padding: 0 5%}} .content-wrapper {z-index: 5} .notice_content {display: flex; align-items: center;} * {-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;} .upgrade_button_red_sale{border: 0; border-radius: 3px; background-color: #ff123a !important; padding: 15px 55px !important; margin-left: 30px; font-family: 'Open Sans', sans-serif; font-size: 16px; font-weight: 600; color: #ffffff;} .upgrade_button_red_sale:hover{color: #ffffff !important; background: #d10303 !important;}",style=document.createElement("style"),sheet=window.document.styleSheets[0];style.styleSheet?style.styleSheet.cssText=css:style.appendChild(document.createTextNode(css)),document.getElementsByTagName("head")[0].appendChild(style),document.getElementsByTagName("head")[0].appendChild(googleFont);var button=document.getElementsByClassName("upgrade_button_red")[0],link=button.parentElement;link.setAttribute("href","https://www.hostinger.com/hosting-starter-offer?utm_source=000webhost&utm_medium=panel&utm_campaign=000-wp"),link.innerHTML='
                    <button class="upgrade_button_red_sale">TRANSFER NOW</button>',(notification=notification[0]).setAttribute("style","padding-bottom: 10px; padding-top: 5px; background-image: url(https://cdn.000webhost.com/000webhost/promotions/springsale/mountains-neon-background.jpg); background-color: #000000; background-size: cover; background-repeat: no-repeat; color: #ffffff; border-color: #ff123a; border-width: 8px;"),notification.className="notice notice-error is-dismissible",(hostingerLogo=hostingerLogo[0]).setAttribute("src","https://cdn.000webhost.com/000webhost/promotions/springsale/logo-hostinger-white.svg"),hostingerLogo.setAttribute("style","float: none !important; height: auto; max-width: 100%; margin: 40px 20px 10px 30px;");var h1Tag=notification.getElementsByTagName("H1")[0];h1Tag.remove();var paragraph=notification.getElementsByTagName("p")[0];paragraph.innerHTML="Fast & Secure Web Hosting.
                    <br>Limited time offer: get an SSL certificate for FREE",paragraph.setAttribute("style",'max-width: 600px; margin-left: 30px; font-family: "Open Sans", sans-serif; font-size: 22px; font-weight: 600;');var list=notification.getElementsByTagName("UL")[0];list.setAttribute("style","max-width: 675px;");for(var listElements=list.getElementsByTagName("LI"),i=0;i
                    <newList.length;i++)listElements[i].setAttribute("style","color:#ffffff; list-style-type: disc; margin-left: 30px; font-family: 'Open Sans', sans-serif; font-size: 14px; font-weight: 300; line-height: 1.5;"),listElements[i].innerHTML=newList[i];listElements[listElements.length-1].remove();var org_html=mainContent.innerHTML,new_html='
                        <div class="content-wrapper">'+mainContent.innerHTML+'</div>
                        <div class="web-hosting-90-off-image-wrapper">
                            <img class="web-hosting-90-off-image" src="https://cdn.000webhost.com/000webhost/promotions/springsale/web-hosting-90-off.png">
                        </div>';mainContent.innerHTML=new_html;var saleImage=mainContent.getElementsByClassName("web-hosting-90-off-image")[0];!function(){var t=document.querySelectorAll("body.wp-admin")[0];function e(){var e=document.createElement("iframe");e.id="hgr-promo-widget",e.setAttribute("src","https://www.hostinger.com/widgets/bottom-banner-sale/000_wp_admin"),e.setAttribute("allowfullscreen",!0),e.setAttribute("frameborder",0),e.style.cssText="z-index: 2147483000 !important;position: fixed !important;bottom: 0; width: 100%;!important; left: 0!important;",e.style.opacity=0,e.onload=function(){iFrameResize({},"#hgr-promo-widget"),e.style.opacity=1},t.insertAdjacentElement("afterend",e)}if(window.iFrameResize)e();else{var n=document.createElement("script");n.type="text/javascript",t.insertAdjacentElement("afterend",n),n.onload=e,n.src="https://unpkg.com/iframe-resizer@3.6.3/js/iframeResizer.min.js"}}()}
                    </script>
                </body>
            </html>Failed to connect to MySQL: ProxySQL Error: Access denied for user '######'@'2a02:4780:bad:f00d::f' (using password: NO)

**Comment by froschdesign** [comment]
@arvinakori 
The class `DbOperation` in `includes/DbOperation.php` has nothing to do with Slim. I guess it's your own database connection class and login credentials are wrong or something similar.

**Comment by l0gicgate** [comment]
This isn’t a Slim related issue. As @froschdesign pointed out there’s an issue in your `DbOperation.php` file.

**Comment by godignorant2** [comment]
glance at this https://kennedy370.github.io/js_mgefN3U5hPX2ZQaMqVPmRQxfo8Ijel44-xkxtNlL4wg/ observation
