### ISSUE TITLE
[4.x] ErrorMiddleware::getDefaultErrorHandler() might return different instances when called multiple times

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2735]
Hi everybody

If we are calling the method `ErrorMiddleware::getDefaultErrorHandler()` twice, we would get two different instances of the error handler (see line 139), as long as we haven't set the default error handler explicitely.

https://github.com/slimphp/Slim/blob/56657131b917e3326842b20706386436e8b4ab75/Slim/Middleware/ErrorMiddleware.php#L133-L140

That is why, in PR #2734 a user has to do the following:
```php
// Get the default error handler
$eh = $errorMiddleware->getDefaultErrorHandler();
// Register the error renderer
$eh->registerErrorRenderer('text/html', MyErrorRenderer::class);
// Set the default error handler we got before
$errorMiddleware->setDefaultErrorHandler($eh);
```

Shouldn't we store the default error handler upon first instantiation and then always return that one? If we would do that, then the user could simply call
```php
$errorMiddleware->getDefaultErrorHandler()
    ->registerErrorRenderer('text/html', MyErrorRenderer::class);
```

## Solution

The method `getDefaultErrorHandler()` of the error middleware could be changed like this:
```php
    public function getDefaultErrorHandler()
    {
        if ($this->defaultErrorHandler === null) {
            $this->defaultErrorHandler = new ErrorHandler($this->responseFactory);
        }

        return $this->callableResolver->resolve($this->defaultErrorHandler);
    }
```

**Comment by l0gicgate** [comment]
Let's go ahead with your proposed solution. We do need to store an instance instead of instantiating a new one every time that function is called.

Good catch!

**Comment by adriansuter** [comment]
Oh no, I made branches in slimphp. Could you please delete those branches? That was a mistake - hmm, should not work in the browser. Sorry.

**Comment by l0gicgate** [comment]
That’s not a big deal, I’ll delete them!
