### ISSUE TITLE
[4.x] PlainTextErrorRenderer always displays details

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2739]
Hi

The `\Slim\Error\Renderers\PlainTextErrorRenderer` would always display error details, even if `$displayErrorDetails` is `false`.

If the error handler is set to log errors, then this renderer would be used - hence the error log might get huge very quickly (if there are many errors 😄).

## Proposition

Wrap the following loop into an if-condition to be executed only if the details should be displayed:
https://github.com/slimphp/Slim/blob/6d6d34e32b4e4e783545cfb912bccc611a993bda/Slim/Error/Renderers/PlainTextErrorRenderer.php#L30-L33

**Comment by l0gicgate** [comment]
I agree. We should probably only display previous exceptions when error details are displayed.
