### ISSUE TITLE
[4.x] Missing xml declaration in xml error renderer

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2747]
There is no xml declaration in
https://github.com/slimphp/Slim/blob/854b3cef212ac0bc505b06fb443aed4f90502917/Slim/Error/Renderers/XmlErrorRenderer.php#L27

## Proposition
Prepend the following xml declaration
```xml
 <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
```
Of course, we need to use `chr(63)` instead of `?`.

**Comment by l0gicgate** [comment]
XML declaration is optional. I mean we can declare it, does it add any value?

**Comment by adriansuter** [comment]
While optional, the W3C recommends in
https://www.w3.org/TR/xml/#sec-prolog-dtd that: "...XML documents SHOULD begin with an XML declaration which specifies the version of XML..."

Of course, we can decide against that recommendation. No big deal, I just stumbled upon this while reading the code.

**Comment by l0gicgate** [comment]
Let's just add it. It does no harm!
