### ISSUE TITLE
Setting response headers doesn't work

### ISSUE THREAD

**Issue by gdarko** [slimphp/Slim#2750]
Hello,

I am using Slim4 of current 4.x branch (not beta). Trying to output image via route but this doesn't work. None of the headers i am setting are set, this happens in other route when i try to send json with setting the header and `json_encode($data)` - the content type is always `text/html`.

```php
$accepted_mime_types  = array('png' => 'image/png'); // ignore this for now. it's valid array of extensions.
$storagePath    = '/path/to/file.png';
$file_name      = basename($storagePath);
$file_contents  = file_get_contents( $storagePath );
$file_extension = pathinfo( $storagePath, PATHINFO_EXTENSION );
$content_type   = array_key_exists( $file_extension, $accepted_mime_types ) ? $accepted_mime_types[ $file_extension ] : '';

$response->withHeader( 'Content-Disposition', 'inline; filename="' . $file_name . '"' )
     ->withHeader( 'Content-Length', filesize( $storagePath ) )
     ->withHeader( "Content-Type", $content_type )
     ->getBody()->write( $file_contents );

return $response;
```

Image of the received http headers: [see image](http://prntscr.com/o8aind)

**Comment by l0gicgate** [comment]
That’s because PSR-7 objects have some immutable methods. The `withHeader()` method returns a copy of itself with the additional header. 

You need to do `$response = $response->withHeader(...)` or compose within your return statement and chain everything `return $response->withHeader(...)->withHeader(...)`

**Comment by gdarko** [comment]
Thanks for clarification @l0gicgate, i updated it and works fine.
