### ISSUE TITLE
[4.x] Remove duplicate binding logic for route handlers

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2753]
_Originally posted by @l0gicgate in https://github.com/slimphp/Slim/issues/2740#issuecomment-507339027_

We will get a phpunit failure if the binding gets removed in `\Slim\Routing\RouteCollectorProxy::map()`. The test case `Slim\Tests\Routing\RouteCollectorProxyTest::testMapBindsContainerToCallable()` complains, as obviously no binding occurs.

Do you think that removing the test case is safe?

Is it possible that someone relies on that binding in the "map-phase"?

**Comment by l0gicgate** [comment]
That test should be replicated in two places, one in the `RouteCollectorProxyTest` and one in the `CallableResolverTest`. We can go ahead and remove the `RouteCollectorProxyTest` case as long as we make sure it's covered in `CallableResolverTest`
