### ISSUE TITLE
slim config method not found

### ISSUE THREAD

**Issue by DennisZjeusus** [slimphp/Slim#2755]
Uncaught BadMethodCallException: Method config is not a valid method

call method from slim\app

$app = new App([
	'mode' => file_get_contents(INC_ROOT.'/mode.php')
]);

$app->configureMode($app->config('mode'), function () use ($app) {
	$app->config = ['test' => true];
    /*$app->config(array(
        'log.enable' => true,
        'debug' => false
    ));*/
});

**Comment by shadowhand** [comment]
Setting `config` as an array in the container does not magically make an `App::config()` method. Perhaps this is what you're looking for ... ?

```php
$container = $app->getContainer();
$container['log.enable'] = true;  // note: this is not a setting Slim recognizes
$container['debug'] = false;
```

http://www.slimframework.com/docs/v3/concepts/di.html covers more about the container.

**Comment by mrcat323** [comment]
There is no config method, to add some configs, you'd just set an array, give it to `Slim\App` instance, like this:
```PHP
$config = ['settings' => ['displayErrorDetails' => true]];
$app = new Slim\App($config);'
```
Just putting settings as **'settings' key's value**

**Comment by l0gicgate** [comment]
I’m closing this as resolved.
