### ISSUE TITLE
Accessing RouteParser From Route Callables

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2758]
We need to figure out a sane way for users to access the `RouteParser` component from a route callable. Right now you have to jump through hoops to get access to it from within a route and it feels unnatural to have to map it via DI.

Perhaps an internal middleware, or perhaps creating a route callable wrapper which would provide the component.

Open to suggestions.

**Comment by shadowhand** [comment]
What if a RouteParser reference was added to Route instances? Then you could do:

```php
$userUri = $route->getRouteParser()->relativeUrlFor('users', ['id' => $user->id()]);
```

**Comment by adriansuter** [comment]
What is wrong with adding it into the DI. If the route callable needs the route parser, then that should be injected into the callable. Or am I missing anything?

**Comment by l0gicgate** [comment]
@adriansuter because this functionality should be easily accessible since a lot of users will be using it. Users shouldn’t have to map internal functionality externally via DI to access it. You should be able to do everything without depending on DI.

**Comment by adriansuter** [comment]
I see. So, it needs to be added to the request, needn't it? Either directly or via route, as @shadowhand suggested. Otherwise the signature of the route callable would be changed, right?

**Comment by adriansuter** [comment]
The route parser can be injected into the route callable without DI. Either the user writes a class and passes the route parser to the constructor, or in case of a closure, the user could do `function(...) use ($routeParser) {}` and use it.

**Comment by l0gicgate** [comment]
I’m thinking that we may be able to add it via the `RoutingMiddleware` where we append the `route` attribute already and the `routingResults` attribute as well.

**Comment by adriansuter** [comment]
Sure.

That's some sort of compromise. That way, the request object serves as some sort of "internal container". Of course, at least to me, it still feels weird to have the route parser in the request.

**Comment by l0gicgate** [comment]
Yes I agree. It would be nice to pass a context object in the route, or some sort of way to access context bound functionality. Using the request is hackish, and it's not typed which is annoying. You're just hoping it will be available.

We need to figure out a different mechanism for this.

**Comment by adriansuter** [comment]
No idea so far.

But to be able to type-hint, we could define a class with static methods that would return the type-hinted attributes.

Something like
`RequestUtils::getRouteParser($request)`.

Not the best solution, I know. We still assume that the attributes are there.

**Comment by shadowhand** [comment]
What if Slim added a context object to the request under the `slim` attribute name:

```php
namespace Slim;

final class RequestAttributes
{
    public static function fromRequest(ServerRequestInterface $request): self;
    public function __construct(RouteInterface $route, RouteParserInterface $routeParser);
    public function getRoute(): RouteInterface;
    public function getRouteParser(): RouteParserInterface;
}
```

Accessible as:

```php
$slimAttributes = Slim\RequestAttributes::fromRequest($request);
// is the strongly typed version of:
$slimAttributes = $request->getAttribute('slim');
```

**Comment by adriansuter** [comment]
I am supporting that idea.

Probably, to make things even easier for a user, we could add other static methods to retrieve the route parser directly.

Or even a mapping of `relativeUrlFor`, although in this case, the name `RequestAttributes` would not make sense anymore.

**Comment by shadowhand** [comment]
Right, I am suggesting having a single attribute that holds all references to Slim objects, rather than defining multiple attributes in the request. It makes it easier to document and reduces the chances that a 3rd party middleware will overwrite something.

The naming is arbitrary, I could see something like:

```php
$userUri = SlimContext::fromRequest($request)->relativeUriFor('users', ['id' => $id]);
```

**Comment by l0gicgate** [comment]
Why don't we do `RouteContext` since all those attributes would pertain to the route itself?

**Comment by adriansuter** [comment]
Would it be possible, that someone needs the callable resolver in route callable? Because if yes, then this should maybe also be packed into this new context object.

What about the response factory? Maybe someone needs that in the callable.

**Comment by l0gicgate** [comment]
I think that maybe we could have two different context objects instead. One which is created by the AppFactory or on Instantiation of the app and can be accessed statically and then a route context object which needs to be instantiated from within the route.

`AppContext` would reference the latest instantiation of the app. I don't see why people would instantiate multiple apps anyway.

```php
$responseFactory = AppContext::getResponseFactory()
$callableResolver = AppContext::getCallableResolver()
```

```php
$routeContext = RouteContext::fromRequest($request);
```

**Comment by shadowhand** [comment]
I don't think that response factory and callable resolver fit, because they are almost always consistent objects, whereas the route changes state depending on the request. Context should be used for variable things and the DIC should be used for consistent things.

Put another way, the `ResponseFactory` (and `CallableResolver`) should be injected into the `AppFactory` from the DIC and is therefore already available to any middleware or handler that needs it.

**Comment by adriansuter** [comment]
Agree, but if you do not have a DI container, how do you access to these instances?

**Comment by shadowhand** [comment]
Hmm, after digging around in the code a bit, wouldn't it be easiest to add this to `App`?

```php
public function getRouteParser(): RouteParserInterface
{
    return new RouteParser($this->getRouteCollector());
}
```

Then someone can easily add `RouteParser` to their DIC:

```php
// Assuming Pimple or something like it
$container[RouteParserInterface::class] = function () use ($app) {
    return $app->getRouteParser();
};
```

Because really, that's what this is all about: being able to use the route parser for reverse routing.

**Comment by l0gicgate** [comment]
@shadowhand that still doesn't solve the problem. All you need to do right now is `$app->getRouteCollector()->getRouteParser()` but it's still not accessible from inside of a route callable.

We need a `RouteContext` object for sure. as for the `CallableResolver` and the `ResponseFactory` we can solve that in a different issue perhaps.

**Comment by adriansuter** [comment]
Great.

We cannot remove or change the attributes `route` and `routingResults` added to the request, can we? That is a BC.

**Comment by l0gicgate** [comment]
We will need those if we use something like `RouteContext::fromRequest($request)` as it will pull the data from those attributes.

I envision the `RouteContext` object having the following interface:
```php
class RouteContext {
    public function getRoute(): RouteInterface
    public function getRouteParser(): RouteParserInterface
    public function getRoutingResults(): RoutingResults
    public static function fromRequest(ServerRequestInterface $request): RouteContext
}
```

**Comment by adriansuter** [comment]
I was asking because @shadowhand  suggested to add the `RouteContext` only. So instead of having three or more attributes attached to the route, only one would be attached, the `RouteContext`. The route, the route parser and the routing results would then be added to and can be retrieved from the `RouteContext`.

But as we cannot remove these two attributes, maybe it is better to follow your idea.

**Comment by l0gicgate** [comment]
We can leave them for now and add the `routeParser` attribute to the request. Then we won't have any BC issues. Maybe we can deprecate that in Slim 5 (years from now 😂)

**Comment by adriansuter** [comment]
Do you plan to instantiate the `RouteContext` in the `public static function fromRequest(ServerRequestInterface $request): RouteContext`? If yes, that means that every middleware (at least those after the routing middleware) and the route callable might have different `RouteContext` instances.

Another solution would be, to instantiate the `RouteContext` already in the route middleware and pass it as attribute to the request.

**Comment by l0gicgate** [comment]
The `RouteContext` cannot be instantiated from within middleware, only from within a route callable where `route`, `routingResults` and `routeParser` request attributes will be available.

I mean it could be instantiated from within middleware if you needed it, given that the middleware is placed before the `RoutingMiddleware` in the queue so the request attributes are available.

**Comment by shadowhand** [comment]
@adriansuter @l0gicgate have either of you started on this? I am willing to give it a try.

**Comment by adriansuter** [comment]
@shadowhand No, go for it.
