### ISSUE TITLE
Routing tests have impossible case

### ISSUE THREAD

**Issue by shadowhand** [slimphp/Slim#2761]
`RoutingMiddlewareTest::testRouteIsNotStoredOnMethodNotAllowed()` expects an exception, but it also includes inspection of the request. The [inspection part of the test][1] is never reached, because `RoutingMiddleware` throws an exception for a "method not allowed" error.

[1]: https://github.com/slimphp/Slim/blob/c4bdfa0bf05b6391f8bfe44852e289dba7cc40f4/tests/Middleware/RoutingMiddlewareTest.php#L72-L81

**Comment by l0gicgate** [comment]
We should probably modify the test accordingly or remove it entirely. By looking at the code you can explicitly see that it cannot happen. These kind of tests are useless imo

**Comment by shadowhand** [comment]
@l0gicgate this was fixed by #2759.
