### ISSUE TITLE
V3: middlewares not executed when invoking Slim App in PHPUnit tests

### ISSUE THREAD

**Issue by MorenoGentili** [slimphp/Slim#2781]
Hello there,
I'm trying to use PHPUnit to perform some integration testing on my Slim controllers.
Here's a sample test:
```
public function testItShouldRequireHttps(): void {
    //Arrange
    $settings = [];
    $app = new \Slim\App($settings);
    $app->add(new \RequireHttpsMiddleware());
    $app->get('/serverTime', \UtilityController::class . ':getServerTime');

    $env = \Slim\Http\Environment::mock([
        'REQUEST_METHOD' => 'GET',
        //'HTTPS' => 'on', //No https
        'REQUEST_URI' => '/serverTime',
        'QUERY_STRING' => '',
        'SERVER_NAME' => 'localhost',
        'CONTENT_TYPE' => 'application/json'
    ]);
    $request = \Slim\Http\Request::createFromEnvironment($env);

    //Act
    $response = $app($request, new \Slim\Http\Response());

    //Assert
    $this->assertEquals(400, $response->getStatusCode());
}
```

As you can see I'm adding a `RequireHttpsMiddleware`, but that won't get invoked when I execute this line of code.
```
$response = $app($request, new \Slim\Http\Response());
```
Using the debugger in Visual Studio Code I've seen the middleware has indeed been added to the stack of the Slim App.
![app](https://user-images.githubusercontent.com/26599562/62522465-0d264c00-b832-11e9-8e01-0c15ee9fb4b1.png)
But then, when I press F11 to step inside the $route->run method, I see the stack is empty in the route object.
![ruote](https://user-images.githubusercontent.com/26599562/62522512-24653980-b832-11e9-8bee-f4886fd3712c.png)

What should I do?
My slim application is otherwise working fine when I make a request in the browser. In that case I call $app->run() but I can't do that in a unit test since I wouldn't be able to pass a mocked request.

**Comment by l0gicgate** [comment]
> But then, when I press F11 to step inside the $route->run method, I see the stack is empty in the route object.

The is no middleware on the route itself, hence why the route's middleware stack is empty. The middleware you added is added onto the `App` itself.

Can you post your middleware code? And are you stepping inside of your middleware code? If not, you should.

**Comment by MorenoGentili** [comment]
Hi @l0gicgate and thanks for your reply.

> And are you stepping inside of your middleware code? If not, you should.

That's exactly the issue: I cannot step inside the middleware code since it's not executed at all.
I've prepared a repro here. You'll find a detailed explanation in the readme.

https://github.com/BrightSoul/repro-slim-issue-2781

> Can you post your middleware code?

Sure, it's in the repro project.

https://github.com/BrightSoul/repro-slim-issue-2781/blob/master/src/middlewares/RequireHttpsMiddleware.php

It gets added to the app here.

https://github.com/BrightSoul/repro-slim-issue-2781/blob/ee698baa8cdeb47c79e25d4d6246ecfcf11ad180/src/Bootstrapper.php#L15

Thank you,
Moreno

**Comment by JoeBengalen** [comment]
What if you call [process()](https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L376) instead? Looking at the code that is where middleware is used.

**Comment by MorenoGentili** [comment]
> What if you call [process()](https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L376) instead? Looking at the code that is where middleware is used.

Yes! Thanks, it's working now.
I tried the `process` method yesterday but it wouldn't work at first (the method didn't exist). I've now realized I was referencing Slim 3.0. As soon as I updated to Slim 3.12.1, it started working perfectly.

Thanks for your support guys, you made me realize what the issue was.
Moreno

**Comment by l0gicgate** [comment]
Closing as resolved.
