### ISSUE TITLE
4.x - MiddlewareDispatcherInterface

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2785]
We will need to introduce a new interface in order to enable users to drop in their own `MiddlewareDispatcher`

Since we won't be able to rely on the constructor, we need methods to set the following:
- `add()` - Untyped method to add a `MiddlewareInterface`, a `string` for deferred callables or a `callable`
- `addMiddleware()` - Typed method to add only `MiddlewareInterface` for people who enjoy stricter typed approaches
- `seedMiddlewareStack()` Set the kernel or "tip" of the middleware stack
- ~~`setCallableResolver()` Set a `CallableResolver`, for resolving all middleware class names / callables. Currently we are injecting `ContainerInterface` inside of `MiddlewareDispatcher` and duplicating some of the logic from within `CallableResolver`. That needs to be changed once we modify `CallableResolver` to handle all that logic.~~

Here is the proposed interface:
```php
<?php
declare(strict_types=1);

namespace Slim\Interfaces;

use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

interface MiddlewareDispatcherInterface extends RequestHandlerInterface
{
    /**
     * Add a new middleware to the stack
     *
     * Middleware are organized as a stack. That means middleware
     * that have been added before will be executed after the newly
     * added one (last in, first out).
     *
     * @param MiddlewareInterface|string|callable $middleware
     * @return self
     */
    public function add($middleware): self;

    /**
     * Add a new middleware to the stack
     *
     * Middleware are organized as a stack. That means middleware
     * that have been added before will be executed after the newly
     * added one (last in, first out).
     *
     * @param MiddlewareInterface $middleware
     * @return self
     */
    public function addMiddleware(MiddlewareInterface $middleware): self;

    /**
     * Seed the middleware stack with the inner request handler
     *
     * @param RequestHandlerInterface $kernel
     * @return void
     */
    public function seedMiddlewareStack(RequestHandlerInterface $kernel): void;
}
```

**Comment by shadowhand** [comment]
Why not `MiddlewareCollectionInterface` with a method `createHandler(): RequestHandlerInterface`?

```php
$middleware->add(...);
$middleware->add(...);
$handler = $middleware->createHandler();
$response = $handler->handle($request);
```

**Comment by shadowhand** [comment]
I can't help but feel like all of this would be easier with two factories for callables and container-resolved middleware:

```php
$callableMiddleware = new CallableMiddlewareFactory($callableResolver);
// This creates a CallableMiddleware instance around $callable that will
// be resolved using the $callableResolver when invoked.
$middleware = $callableMiddleware->create($callable);
assert($middleware instanceof MiddlewareInterface);

$containerMiddleware = new ContainerMiddlewareFactory($container);
// This creates a ContainerMiddleware instance around $identifier that will
// be resolved using the $container when invoked.
$middleware = $containerFactory->create($identifier);
assert($middleware instanceof MiddlewareInterface);
```

Expanding on my previous comment:

```php
$collection = new MiddlewareCollection($callableFactory, $containerFactory);
$collection->add($middleware);
$collection->addCallable($callable); // $collection->add($callableFactory->create($callable))
$collection->addIdentifier($identifier); // $collection->add($containerFactory->create($identifier))
$handler = $collection->createHandler();
```

**Comment by l0gicgate** [comment]
I want to give full control over middleware dispatching. That's the whole purpose of this interface. Then nobody can complain anymore 😂

**Comment by jacekkarczmarczyk** [comment]
I'd rather leave just `addMiddleware()` and if someone want's to use string, callable or whatever he should convert it to the `MiddlewareInterface` with some factory:

```
$x->addMiddleware($someMiddlewareFactory->create('foo'));
$x->addMiddleware($someMiddlewareFactory->create([$foo, 'bar']));
```

That would make the interface more SRP/DRY

Also maybe a bit off topic question, maybe not, I've seen that there's try/catch that catches exceptions and calls an error middleware - is there any reason for this? Why the error middleware can't be just added to the stack as all other middlewares? Ignore the question if you feel that it's completely not related to this issue

**Comment by l0gicgate** [comment]
> I'd rather leave just addMiddleware() and if someone want's to use string, callable or whatever he should convert it to the MiddlewareInterface with some factory:

We can't do that. The internals need to be able to add deferred callables (string) / callables. 

> I've seen that there's try/catch that catches exceptions and calls an error middleware - is there any reason for this?

I'm not sure I understand your question. The current `ErrorMiddleware` can be placed anywhere in the stack like any other middleware. You can also not use the `ErrorMiddleware` that Slim 4 ships with and make your own!

**Comment by jacekkarczmarczyk** [comment]
Can't find now the code i'm talking about, i guess i've seen it somewhere in the issue/pr comment, not in the slim, so all is well

**Comment by l0gicgate** [comment]
@jacekkarczmarczyk in Slim 3 it was coupled to the core https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L390-L397 if that's what you're talking about. This has all been extracted to middleware in Slim 4 via `ErrorMiddleware`

**Comment by jacekkarczmarczyk** [comment]
Oh yeah, that was it
