### ISSUE TITLE
Add `inferPrivatePropertyTypeFromConstructor` to phpstan

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2788]
Currently we get the following tip of the day from phpstan:

> Tip of the Day:
> One or more properties in your code do not have a phpDoc with a type
> but it could be inferred from the constructor to find more bugs.
> Use inferPrivatePropertyTypeFromConstructor: true in your /home/travis/build/slimphp/Slim/phpstan.neon.dist to try it out!

Should we add this to the phpstan config file?

**Comment by l0gicgate** [comment]
You could try it out locally, obviously I'd like to find bugs if there are some!

**Comment by adriansuter** [comment]
I tried it locally. No additional bugs found.

**Comment by l0gicgate** [comment]
Let’s add it!
