### ISSUE TITLE
Http message format

### ISSUE THREAD

**Issue by mapogolions** [slimphp/Slim#2794]
Is there a reason to send a status line after all headers instead of before?
- https://github.com/slimphp/Slim/blob/4.x/Slim/ResponseEmitter.php#L44
- https://github.com/slimphp/Slim/blob/4.x/tests/ResponseEmitterTest.php#L138

**Comment by l0gicgate** [comment]
I can’t think of any reason. Status line should be first, that’s just an oversight.

**Comment by mapogolions** [comment]
I will create PR
