### ISSUE TITLE
4.x - Fix message in ErrorHandler

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2795]
https://github.com/slimphp/Slim/blob/4.x/Slim/Handlers/ErrorHandler.php#L271

We need to come up with a more appropriate message.

> View in rendered output by enabling the "displayErrorDetails" setting.

This is confusing to me

**Comment by RyanNerd** [comment]
What is the purpose of appending this? (or any additional text to the error log): 

> View in rendered output by enabling the "displayErrorDetails" setting.

to the `error_log()` in the first place?

@l0gicgate This confuses me as well. What are the arguments for appending **anything** additional here? https://github.com/slimphp/Slim/blob/4.x/Slim/Handlers/ErrorHandler.php#L271

If there aren't any compelling arguments then I propose the line should be removed.

**Comment by l0gicgate** [comment]
@RyanNerd so if someone was to look at the logs and see that there are no error details (stack trace). It would indicate to them that by turning on `displayErrorDetails` on `ErrorHandler` they could see the stack trace via a browser/http client by toggling that on. It's really just a "tip"

**Comment by RyanNerd** [comment]
This is marked as an easy pick but changing the message to something else is very subjective. Perhaps something like:

> To see error details set displayErrorDetails to true in the ErrorHandler.

**Comment by vaga** [comment]
Perhaps, something like:
`Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor.`

And you can add this line only if "$displayErrorDetails" is equal to `false`.
