### ISSUE TITLE
4.x - Add pseudo content type for log renderer in ErrorHandler 

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2797]
The `ErrorHandler` is currently instantiating a `PlainTextErrorRenderer` in the `writeToErrorLog`-method. So a user would not be able to provide a custom log renderer.

I suggest to add a new pseudo content type "slim-log" to the array of error renderers or to add a new method `setLogErrorRenderer()` which takes one param `ErrorRendererInterface|string|callable`.

I prefer the second solution, as the first one might be a little bit hackish.

What are your thoughts?

**Comment by RyanNerd** [comment]
@adriansuter I've created a PR #2801 for the second option `setLogErrorRenderer`. Please review. If the logic looks good I'll add unit tests for this feature.
