### ISSUE TITLE
4.x - Deferred callable as string without resolver

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2804]
Dear reader

In `DeferredCallable` we can pass a `string` as callable. But the callable resolver is allowed to be `null` and therefore the `__invoke` will fail. Shouldn't we throw a `RuntimeException` if that happens? If yes, already in the constructor or later in the invocation?

**Comment by mapogolions** [comment]
I briefly looked - https://github.com/slimphp/Slim/blob/4.x/Slim/DeferredCallable.php#L40. It seems correct. Please, give a counterexample.

```php
function add($a, $b) {
    return $a + $b;
}
$callable = new DeferredCallable('add');
echo $callable(10, 20) . PHP_EOL;
```

**Comment by adriansuter** [comment]
For example if the *callable string* is in Slim notation `ClassName:method`.
```php
class Calculator
{
    function add($a, $b)
    {
        return $a + $b;
    }
}

$callable = new DeferredCallable('Calculator:add', new \Slim\CallableResolver());
echo $callable(10, 20).PHP_EOL;

$callable = new DeferredCallable('Calculator:add');
try {
    echo $callable(10, 20).PHP_EOL;
} catch (Error $e) {
    echo $e->getMessage().PHP_EOL;
}
```
This would output
```
30
Call to undefined function Calculator:add()
```
The first one is working as it has a callable resolver.

Although. I am not sure if this would ever happen.

**Comment by mapogolions** [comment]
In case of `Slim:notation` it's really is. But `DeferredCallable` entities are mainly used in a middleware stack. Therefore, they can be added through the following method calls:
- `MiddlewareDispatcher::add`
- `MiddlewareDispatcher::addDeferred`
I think, created `DeferredCallable's` must recieve `$callableResolver` from - https://github.com/slimphp/Slim/blob/4.x/Slim/MiddlewareDispatcher.php#L48. This field is not nullable.

**Comment by mapogolions** [comment]
I found case. 
```php
$middleware = new DeferredCallable('Slim:notation');
$middlewareDispatcher->add($middleware) or addCallable($middleware);
```
I think it doesn't look natural.

**Comment by l0gicgate** [comment]
> Shouldn't we throw a RuntimeException if that happens? If yes, already in the constructor or later in the invocation?

@adriansuter yes, let's throw a `RuntimeException` as soon as possible.

**Comment by adriansuter** [comment]
@l0gicgate Sure. Is this class actually used somewhere? I haven't found any references.

**Comment by l0gicgate** [comment]
@adriansuter it is not anymore. I think we can remove it altogether. It was an oversight when we merged the PSR-15 PR I believe.

**Comment by adriansuter** [comment]
If we remove that, could that bug someone - for example someone who used it already somewhere? Chances are small, but still.

**Comment by adriansuter** [comment]
Actually it is used:

https://github.com/slimphp/Slim/blob/335b5fd1c6c56023ab9ebed48ad5811d4fce5a45/tests/Routing/RouteTest.php#L388-L403

https://github.com/slimphp/Slim/blob/335b5fd1c6c56023ab9ebed48ad5811d4fce5a45/tests/Routing/RouteTest.php#L405-L452

**Comment by l0gicgate** [comment]
@adriansuter we should either move it into the test mocks, or delete it an not use it at all. It shouldn't be in there and for people using it, why? you can already defer any route/middleware callable.

**Comment by mapogolions** [comment]
@adriansuter  and @l0gicgate I created a draft [PR](https://github.com/slimphp/Slim/pull/2808).  It shows how the `DeferredCallable` class can help us.

**Comment by adriansuter** [comment]
Seems to be a nice idea. What do you think @l0gicgate?

**Comment by l0gicgate** [comment]
If we use `DeferredCallable` again, then we make `MiddlewareDispatcher` depend on `CallableResolverInterface` which will make it harder to decouple that interface as proposed in #2785 

I don't think we need it anymore. Change my mind 😂

**Comment by mapogolions** [comment]
I agree with that opinion

**Comment by adriansuter** [comment]
Right. So I will close #2807, as soon as I can as it is not needed anymore.

**Comment by BusterNeece** [comment]
@l0gicgate Agh, this is what I get for being on effectively `4.x-dev-master`...I just pulled this update down and found this was gone, and while I'm not 100% surprised, I actually was using it in my code. :(

Almost certainly this is a case of [XKCD 1172](https://xkcd.com/1172/), and I don't blame you guys for getting rid of it for Slim itself, but it was a nice little utility class to have to fulfill the same purpose in other places that don't take advantage of Slim's CallableResolver (in my case, Symfony's EventDispatcher).

**Comment by l0gicgate** [comment]
Sorry @SlvrEagle23, it should be fairly easy to re-implement in your code base though if you need it though.
