### ISSUE TITLE
is there a way to disable the error / exception handling?

### ISSUE THREAD

**Issue by cidic** [slimphp/Slim#282]
I already have error / exception handling setup how I need it in most of my apps. is there a way to simple disable this feature in slim?

**Comment by codeguy** [comment]
No. Currently Slim uses the `Slim_Middleware_PrettyExceptions` middleware to catch any exceptions thrown during development. In production, you'll want to set the `debug` app setting to `false` and define your own custom error handler with `$app->error($customHandler)` that will be invoked during production (whose one argument will be the caught exception).

For now, I'd recommend you run in production and define a custom error handler that interfaces with your current setup. In a future version I can introduction an app setting that would disable Slim's built in error handling. It would be on by default.
