### ISSUE TITLE
4.x - Multiple slashes at the beginning of a path

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2822]
Say we have a route 
```php
    $app->get('/foo/bar', function (ServerRequest $request, Response $response, array $args): ResponseInterface { /*...*/ }
```

If we request `http://localhost///////foo/bar`, then this route would be called (which is wrong in my opinion as these are actually directories with empty names - or are there rules how this should be handled correctly?).

If we request `http://localhost/foo///////bar`, then we get a 404 not found, which is correct in my opinion.

We should probably not remove all leading slashes, shouldn't we?
https://github.com/slimphp/Slim/blob/5c493cb5dfd493baa8c01e6fe684e8be4617fdb9/Slim/Routing/RouteResolver.php#L49-L53

If we use a base path, then the following happens:
```php
   /* ... */
    $app->setBasePath('/base-path');
    /* ... */
    $app->get('/foo/bar', function (ServerRequest $request, Response $response, array $args): ResponseInterface { /*...*/ }
```
* `http://localhost/base-path/foo/bar` works (which is correct in my opinion).
* `http://localhost/base-path///////foo/bar` 404 (which is correct in my opinion).
* `http://localhost/base-path/foo///////bar` 404 (which is correct in my opinion).
* `http://localhost///////base-path/foo/bar` works (which is wrong in my opinion).

**Comment by l0gicgate** [comment]
How do you propose we fix this?

**Comment by adriansuter** [comment]
In the mentioned method, instead of removing all leading slashes and prepending one slash we could probably check if the first char is a slash and only if not, we prepend a slash. Otherwise we leave it as is.

**Comment by l0gicgate** [comment]
Let's do that!
