### ISSUE TITLE
Slim Application Error: make customisable?

### ISSUE THREAD

**Issue by pavarnos** [slimphp/Slim#2826]
On a production server, I'd like to disclose as little information as possible about how the app is built or operates. When I provide a bad URL or otherwise throw an exception with the `ErrorHandler` enabled, the title for Html and PlainText renderers is 'Slim Application Error'. The message is hard coded so it cannot be customised or disabled. JSON and XML formats do not include information about the framework used to build the app.

https://github.com/slimphp/Slim/blob/4.x/Slim/Error/Renderers/HtmlErrorRenderer.php#L27
https://github.com/slimphp/Slim/blob/4.x/Slim/Error/Renderers/PlainTextErrorRenderer.php#L27

Is it possible to 
- remove the word 'Slim' from the text
- or make the heading customisable via a setter?

**Comment by l0gicgate** [comment]
Just make a custom error renderer that implements the `ErrorRendererInterface` then on the error handler map the custom renderer to the appropriate content type or as default. You can extend the provided renderers also to modify the heading.
