### ISSUE TITLE
4.x NotFoundHandler example

### ISSUE THREAD

**Issue by phpsyscoder** [slimphp/Slim#2827]
Hi

is there any example how to migrate `NotFoundHandler` from slim3 to slim4?

Thank you

**Comment by t0mmy742** [comment]
Hi,

First, look at [this page](https://www.slimframework.com/docs/v4/middleware/error-handling.html), the **Error Handling/Rendering** part.

With the ___invoke_ method, you can check if **$exception** is an _instanceof_ **HttpNotFoundException**. If not, just return parent::__invoke($exception, $displayErrorDetails).

Then you add your Error Renderer class as written on the documentation.

You could have something like :

```php
class CustomHtmlErrorRenderer extends HtmlErrorRenderer
{
    public function __invoke(Throwable $exception, bool $displayErrorDetails): string
    {
        if ($exception instanceof HttpNotFoundException) {
            return YOUR_404_HTML;
        } else {
            return parent::__invoke($exception, $displayErrorDetails);
        }
    }
}
```

**Comment by l0gicgate** [comment]
I think that you're asking on how to catch not found exceptions:

```php
<?php
use Slim\Factory\AppFactory;
use Slim\Exception\HttpNotFoundException;
require __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

$errorMiddleware = $app->addErrorMiddleware(true, true, true);
$errorMiddleware->setErrorHandler(HttpNotFoundException::class, function (Throwable $exception, bool $displayErrorDetails) {
   return '404 NOT FOUND';
})
```
