### ISSUE TITLE
Slim 4 - How do I force response in middleware?

### ISSUE THREAD

**Issue by Jaffa-Cakes** [slimphp/Slim#2834]
Hello,

I have authentication middleware and when the user can't be authenticated, I want a response to be given and the route to be skipped.

```php
public static function user_auth_middleware($request, $handler) {
	
	$response = $handler->handle($request);

	$routeContext = RouteContext::fromRequest($request);
	$route = $routeContext->getRoute();
	$usersid = (int) $route->getArgument('usersid');

	$result = api_v1::check_token($request, $usersid, $response);
	if ($result['error'] == true) {
		return $response->withStatus(401);
	}

	return $response;
}
```

I can't find a way of cancelling the route from executing and delivering the response immediately.

Any help would be appreciated. :)

**Comment by RyanNerd** [comment]
@Jaffa-Cakes I had the same question. It is answered [here](https://github.com/slimphp/Slim/issues/2667#issuecomment-487204263).

**Comment by adriansuter** [comment]
@Jaffa-Cakes And to stay decoupled from the PSR7-implementation, see https://github.com/slimphp/Slim/issues/2667#issuecomment-529901032

**Comment by Jaffa-Cakes** [comment]
Will I need to use the Middleware class?

It doesn't seem to be working for me.

**Comment by froschdesign** [comment]
@Jaffa-Cakes 
> Will I need to use the Middleware class?

You do not have to use a class, but your `static` implementation looks wrong here.

**Comment by Jaffa-Cakes** [comment]
@froschdesign sorry to be a pain but I don't think I see what's wrong with the function.

Could you please point it out for me?

**Comment by Jaffa-Cakes** [comment]
Ah, @froschdesign I found the issue. I had ran `$handler->handle($request);` before returning my error.

Thanks for your responses :)
