### ISSUE TITLE
Wrong Value in $args in a Delete Method Handler 

### ISSUE THREAD

**Issue by googoogajoob** [slimphp/Slim#2838]
Can someone confirm whether or not this is a Bug or correct behaviour? Perhaps, my routes are not being defined correctly, but my other routes using GET, POST and PUT are working as expected.

I'm using Slim4 Beta and have a route defined **demousers/{id}** which handles the http-method DELETE

In my Handler Class 

`public function deleteDemouser(Request $request, Response $response, $args): Response`

In the parameter $args I was expecting the value given in the UR, e.g. "id" => 5. This is what happens with other Http-Methods (GET, PUT and POST). Instead $args has the Key/Value pair "id" => "delete"

For routing I'm using **Slim\Middleware\RoutingMiddleware** Also  **Slim\Middleware\MethodOverrideMiddleware** is being used to convert the Html POST request to a DELETE request.

With XDebug I was able to locate the Method where the data seems to be mixed up. **\FastRoute\Dispatcher\GroupCountBased::dispatchVariableRoute**

**Comment by l0gicgate** [comment]
Why are you using the beta? Please update to 4.2 and then try to see if the issue persists.

**Comment by googoogajoob** [comment]
I've upgraded to Slim 4.2
For routing I am now using  
`$app->addRoutingMiddleware();`

The same problem persists

**Comment by l0gicgate** [comment]
We are going to need to see a gist of your code.

**Comment by googoogajoob** [comment]
When I went to create the Gist, I discoverd the problem was in my code.

Problem solved (was never there in the first place)

Sorry
