### ISSUE TITLE
4.x - Inconsistent `setBasePath` Behavior

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim#2842]
- When using `$app->setBasePath('/public')` it breaks `RouteParser::relativeUrlFor` output:
  ```
  echo $routerParser->urlFor('about');
  /public/about
  ```

  ```
  echo $routerParser->relativeUrlFor('about');
  about <- expected
  /public/about <- result
  ```

- Using only `$app->getRouteCollector()->setBasePath('/public')`, RouteParser produces corrent urls for both urlFor and relativeUrlFor methods but breaks current path detection
- Using both `$app->setBasePath` and `$routeCollector->setBasePath` produces invalid url paths for all methods

_Originally posted by @piotr-cz in https://github.com/slimphp/Slim/issues/2512#issuecomment-534056851_

**Comment by piotr-cz** [comment]
I have prepared test case here: [Slim-4-basepath-issue](https://github.com/piotr-cz/Slim-4-basepath-issue)
