### ISSUE TITLE
No development branch

### ISSUE THREAD

**Issue by piotr-cz** [slimphp/Slim#2843]
[CONTRIBUTING.md](https://github.com/slimphp/Slim/blob/4.x/CONTRIBUTING.md) says new pull requests should be created against `develop` branch, but ATM there is no branch witch such name.

**Comment by l0gicgate** [comment]
We should probably change that to `4.x`

**Comment by piotr-cz** [comment]
Both 4.x and 3.x branches have own CONTRIBUTING.md files so there may be updated separately

**Comment by l0gicgate** [comment]
Yes @piotr-cz

**Comment by piotr-cz** [comment]
Resolved via #2846,
there is no need to update [CONTRIBUTING.md](https://github.com/slimphp/Slim/blob/3.x/CONTRIBUTING.md) file for 3.x branch as it says

> Send a pull request from each feature branch against the version branch for which your fix is intended.
