### ISSUE TITLE
Slim 3 abuses the container.

### ISSUE THREAD

**Issue by ndobromirov** [slimphp/Slim#2847]
On every new route that gets registered through the `$app->map()` Slim 3 is fetching `router` and `settings` services every time it get's called. It is causing noticeable delays.

We can easily introduce a private lazy loaded utility to have that happen only one time.
On our APP this resolved in a consistent 5% speed-up with an applications with around 70 routes registered and running with route cache enabled.

Have you measured Slim 3 vs slim 2 performance in real life? 
After update half an year ago we are measuring some degraded performance. Form about 2 ms of framework overhead currently we are around 10 ms for an equivalent application.

**Comment by l0gicgate** [comment]
The Slim 3 branch is now in security mode and will not be receiving any more patches besides security fixes. Unfortunately this cannot be addressed.

**Comment by ndobromirov** [comment]
I was kind of expecting that, but thanks for the response!
Will re-validate this once we are on Slim 4, hopefully we are not too late with it, like with update to 3 :smile:
