### ISSUE TITLE
CORS `The simple solution` v3, doesn't work anymore

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2866]
Hi guys, well I probably should've gone to StackOverflow with it but it's my birthday so I feel free to write my first ever github issue. I hope you don't mind.

So using [your CORS setting](https://www.slimframework.com/docs/v3/cookbook/enable-cors.html) from v3 I stepped uppon this error
`
Too few arguments to function Closure::{closure}(), 2 passed in ...../vendor/slim/slim/Slim/MiddlewareDispatcher.php on line 275 and exactly 3 expected"
`
on this bit 
```
$app->add(function ($req, $res, $next) {
  $response = $next($req, $res);
  return $response
        ->withHeader('Access-Control-Allow-Origin', 'http://localhost:4200')
        ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
        ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
});
```

It probably comes from this `$next($req, $res)` section.
But I don't understand the middleware it refers to so I can't really solve it myself.

These are the lines 273-276 of [MiddlewareDispatcher.php](https://github.com/slimphp/Slim/blob/4.x/Slim/MiddlewareDispatcher.php).
```
public function handle(ServerRequestInterface $request): ResponseInterface
{
    return ($this->middleware)($request, $this->next);
}
```
Take care.

**Comment by fqrd** [comment]
Nevermind !
I was tired, using the V3 doc instead of the [V4](https://www.slimframework.com/docs/v4/cookbook/enable-cors.html), which solved my problems.
`add` takes only 2 arguments now. 
Thanks for your support ! (I'm actually glad none replied as I feel quite dumb).
Have a sunny week !
