### ISSUE TITLE
HTTP Response Status Exceptions

### ISSUE THREAD

**Issue by mschop** [slimphp/Slim#2867]
Hi all,

I would like to throw exceptions for several http response codes (in slim 3). This would be very useful for preventing code duplication.

Example:

```
if ($id <= 0) throw new BadRequestException('Id must be gt 0');
```

Is there a way to do this in slim without creating a custom middleware? Is there any existing middleware for this? (I wasn't able to find one).

Thanks right now.

Best Regards
mschop

**Comment by l0gicgate** [comment]
Not sure what you mean. You have to make a custom exception handler to set the response code appropriately on the response object after it catches the exception.
