### ISSUE TITLE
4.x - phpErrorHandler

### ISSUE THREAD

**Issue by mbretter** [slimphp/Slim#2870]
Hi,

what is slim3's phpErrorHandler equivalent in slim4.

I have seted up a default error handler without any success
```php
$errorMiddleware->setDefaultErrorHandler($errorHandler);
```
I have tried adding an error handler for Throwables
```php
$errorMiddleware->setErrorHandler(Throwable::class, $errorHandler);
```
none of them worked, do I have to register a phpErrorHandler using set_error_handler() myself, or is it just a missing feature in slim4?

cheers

**Comment by l0gicgate** [comment]
use `$errorMiddleware->setDefaultErrorHandler($errorHandler)`
