### ISSUE TITLE
Docblock for `\Slim\Routing\RouteCollector::$cacheFile` contains "invalid" sentence

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2873]
https://github.com/slimphp/Slim/blob/7f36c9e3ec0e002a915e6ef85677499d1cd0c728/Slim/Routing/RouteCollector.php#L56-L61

Maybe we should remove the sentence "Set to false to disable route caching", as this property can either be a `string` or `null`. A boolean is not allowed here.

Or we could rephrase to "Set to null to disable route caching".

**Comment by l0gicgate** [comment]
Correct! Let’s fix that
