### ISSUE TITLE
[3.12.2] adding {@inheritdoc} breaks phpstan

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [slimphp/Slim#2879]
Following change in 3.12.2 breaks the phpstan

https://github.com/slimphp/Slim/compare/3.12.1..3.12.2#diff-0662ca8cf8d9ad2868ffab7a85a61847R21

Not sure if it's a slim regression or phpstan issue, See the relevant report in phpstan repo for more details: https://github.com/phpstan/phpstan/issues/2561

To workaround it in my code I had to change
```php
$request = Slim\Http\Request::createFromEnvironment(Slim\Http\Environment::mock([...]));
```

to 
```php
/** @var Slim\Http\Environment $env */
$env = Slim\Http\Environment::mock([...]);
$request = Slim\Http\Request::createFromEnvironment($env);
```

**Comment by jacekkarczmarczyk** [comment]
Seems like a Slim issue https://github.com/phpstan/phpstan/issues/2561#issuecomment-552135751

**Comment by adriansuter** [comment]
Hi @jacekkarczmarczyk 

PHPStan does not currently support overriding of `@inheritdoc`. But as I understand, overriding of `@inheritdoc` should be allowed, although there is no standard and [PSR-5](https://github.com/php-fig/fig-standards/blob/e89924d320c269678fe3f5822c9bf9ef95db1af0/proposed/phpdoc.md) is still a draft. Hence I think this is not really a `Slim` issue.

**Comment by jacekkarczmarczyk** [comment]
I understand, feel free to close the issue, workaround is fine for me

**Comment by adriansuter** [comment]
We could also change the phpdoc of `\Slim\Interfaces\Http\EnvironmentInterface` to return `static` and remove the override from `\Slim\Http\Environment::mock()`.

```php
interface EnvironmentInterface
{
    /**
     * Create mock environment
     *
     * @param  array $settings Array of custom environment keys and values
     *
     * @return static
     */
    public static function mock(array $settings = []);
}
```
