### ISSUE TITLE
Invalid type check

### ISSUE THREAD

**Issue by krmgns** [slimphp/Slim#2882]
Hi all,

So a callable cannot be an array, this code looks invalid;

<pre lang=php>
/**
     * @param callable $callable
     *
     * @return callable
     */
    private function bindToContainer(callable $callable): callable
    {
        if (is_array($callable) && $callable[0] instanceof Closure) {
            $callable = $callable[0];
        }
        if ($this->container && $callable instanceof Closure) {
            $callable = $callable->bindTo($this->container);
        }
        return $callable;
    }
</pre>

Location: https://github.com/slimphp/Slim/blob/4.x/Slim/CallableResolver.php#L171

**Comment by l0gicgate** [comment]
Callables can be arrays:
```php
$callable = [$instantiatedObject, 'method'];
```

See:
https://www.php.net/manual/en/function.is-callable.php

**Comment by krmgns** [comment]
Ups ma bad, just forgot it was PHP who says potatoes can be tomatoes cos both look like eggs... :P 
BTW "all-able" sounds better for these type cases, right? :)
