### ISSUE TITLE
Some reserved keywords are not allowed as route placeholders

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2883]
The following route handler fails and throws an exception:
``` php
$app->get('/{route}', function (Request $request, Response $response, array $args): Response {
    $context = RouteContext::fromRequest($request);

    return $response;
});
```

That is because the default invocation strategy `\Slim\Handlers\Strategies\RequestResponse` puts the route arguments to the request attributes. So the argument `route` would overwrite the attribute with the same key set in the routing middleware.

The exception thrown is even misleading: "Uncaught RuntimeException: Cannot create RouteContext before routing has been completed"

Do you have an idea, how we could avoid that or should we add a hint to the docs?

Currently I guess the following keywords are reserved:
- `route`
- `routeParser`
- `routingResults`
- `basePath`

**Comment by adriansuter** [comment]
Maybe we could check in `\Slim\Handlers\Strategies\RequestResponse::__invoke` whether a request attribute already exists and if so, we could throw a runtime exception "Route argument x is now allowed".

**Comment by shahariaazam** [comment]
No, I don't think so. Here what I just tested after seeing your issue.

```php
$app->get('/test/{route}', function (Slim\Psr7\Request $request, Slim\Psr7\Response $response, array $args): Response {
    $response->getBody()->write($request->getAttribute("route"));
    return $response;
});
```

```
GET /test/2
```
Returns `2`

It's working perfectly. I think there shouldn't be any reserved word in route placeholder. Also I couldn't find anything about it in docs.

So can you please post your full trace to take a look to get any hints?

**Comment by adriansuter** [comment]
@shahariaazam Now put the following line into your route handler:
`$context = RouteContext::fromRequest($request); `.

You will get an error. But if you change the placeholder name, everything is working as expected.

My explanations above are not based on the docs, but on the source code.

**Comment by odan** [comment]
I tried the example from @adriansuter and I get the same error: 

```
Type: TypeError
Code: 0
Message: Argument 1 passed to Slim\Routing\RouteContext::__construct() must implement 
interface Slim\Interfaces\RouteInterface or be null, string given, called in 
RouteContext.php on line 34
File: RouteContext.php
Line: 63
```

The same error occurs for route placeholders such as: `routeParser`, `routingResults` and `basePath`.

Unfortunately, it is a general problem when route argument names overlap with request attribute names.

**Comment by l0gicgate** [comment]
I feel like we should have underscored those:
- `__route__`
- `__routeParser__`
- `__routingResults__`
- `__basePath__`

I think we still can since all we'd need to do is to change the internals of `RouteContext`. This would technically be a BC but since you're suppose to use the `RouteContext` object it's an internal BC.

**Comment by adriansuter** [comment]
Yes.

**Comment by juliangut** [comment]
http://www.slimframework.com/docs/v4/cookbook/retrieving-current-route.html

> If you ever need to get access to the current route within your application all you have to do is call the request class’ getAttribute method with an argument of 'route' and it will return the current route, which is an instance of the Slim\Route class.
> 
> From there you can get the route’s name by using getName() or get the methods supported by this route via getMethods(), etc.
> 
> Note: If you need to access the route from within your app middleware you must set 'determineRouteBeforeAppMiddleware' to true in your configuration otherwise getAttribute('route') will return null. Also getAttribute('route') will return null on non existent routes.

I'd assume "many" people will already be collecting route from the request as noted on the docs, even though it uses RouteContext in the example

**Comment by l0gicgate** [comment]
@juliangut the documentation is wrong, that is still from Slim 3.

I just fixed that via https://github.com/slimphp/Slim-Website/pull/462

**Comment by l0gicgate** [comment]
@adriansuter do you want to PR with the underscored attributes?
