### ISSUE TITLE
i try serialize ResponseInterface,Deserialize again and you get an error

### ISSUE THREAD

**Issue by seth-shi** [slimphp/Slim#2886]
Slim 4 Release
I want to implement a cache, but not through HTTP cache.I declare a global middleware, and on the outermost layer, when the first request, the response object serialization to redis.After that visit, I can take out this value from the redis reverse sequence directly returned directly, without the need for other middleware.
But I did get a ResponseInterface object, but I got an error on the output:
`Uncaught TypeError: fseek() expects parameter 1 to be resource, integer given innyholm\\psr7\\src\\Stream.php:185`
****
From the manual, I learned that serialize was not able to serialize a stream, and the stream read in `Responseitter ::emit` caused the error, so instead of serializing the whole `ResponseInterface`, I stored `Response::getBoday()->getContents()`, I started trying, but the result was always an empty string.

**Comment by l0gicgate** [comment]
What you should do is create your own serializable `Response` and `Stream` object. Implement the `__sleep` and `__wakeup` methods yourself so you can control serialization and then recreate the default `Nyholm/psr7` objects on wake.

**Comment by seth-shi** [comment]
thx, i from here get answer.
https://discourse.slimframework.com/t/caching-with-slim/1107/5
