### ISSUE TITLE
Lazy loaded middleware?

### ISSUE THREAD

**Issue by MontealegreLuis** [slimphp/Slim#2891]
Thank you all for your exceptional work!

Will it be possible to lazy load middleware in groups and routes?

I didn't find anything in the Silm 4 feedback thread nor in the docs (or maybe I missed it)

```php
$app->group('/api', function (RouteCollectorProxy $group) {

  $group->get('/hello', HelloWorldController::class)
      ->addMiddleware(RouteMiddleware::class);

})->add(GroupMiddleware::class);
```

**Comment by l0gicgate** [comment]
All middleware is resolved through the same process in the `MiddlewareDispatcher`. You can lazy load using the `add` method as you did in your example, not via the `addMiddleware` method though since that's a type hinted method.

**Comment by MontealegreLuis** [comment]
Thank you @l0gicgate I completely missed the `add` method
