### ISSUE TITLE
$request->getAttribute('route'); now returning null

### ISSUE THREAD

**Issue by N1ghteyes** [slimphp/Slim#2892]
Ok, so:

```
 public function process(Request $request, RequestHandler $handler): Response
    {
//...
        $route = $request->getAttribute('route');
//...
    }
```

Has been working fine since I've been using it, however the latest commit to dev seems to have broken it, with $route being equal to null.

**Comment by l0gicgate** [comment]
Use the `RouteContext` object as per the docs:

http://www.slimframework.com/docs/v4/cookbook/retrieving-current-route.html
