### ISSUE TITLE
Routes that contain a replaceable param throw 404 if another route with  similar path exists (Slim 4.x)

### ISSUE THREAD

**Issue by N1ghteyes** [slimphp/Slim#2893]
I think this might be a follow on to the route changes from the other day.

I have a number of routes, but i'm specifically having issues when i have routes following this structure.

/path/path2 << this works as expected
/path/path2/{id} << this throws a 404
/path/path2/{id}/edit << this works as expected

it looks like something in the path matching has broken when there are routes that follow a nested pattern and that contain at least one custom element.

**Comment by l0gicgate** [comment]
The pattern matching is done via FastRoute which is a third party library, we did not change anything in that regards. The errors must be with your code.
