### ISSUE TITLE
Working with the new Slim\Exception\HttpException

### ISSUE THREAD

**Issue by Frzk** [slimphp/Slim#2894]
Hi,

I'm currently working on a project that involves Slim 4 and [php-opencloud/openstack](https://github.com/php-opencloud/openstack).

The latter uses a [`GuzzleHttp\ClientInterface`](https://github.com/guzzle/guzzle/blob/master/src/ClientInterface.php) to make requests.

It also throws `BadRequestException` for Http exceptions, such as 401, 404, etc. I don't really like this behavior, and I would like to catch them and re-throw Slim exceptions instead (such as `Slim\Exception\HttpMethodNotAllowedException`, based on the status code returned with the `BadResponseException`).

As you also know, instantiation of a new Slim's `HttpException` requires a `Psr\Http\Message\ServerRequestInterface`. Yet, GuzzleHttp works everywhere with `Psr\Http\Message\RequestInterface`. That's the case, for example, with the `BadRequestException::getRequest()` method : it returns a `RequestInterface`, not a `ServerRequestInterface`.

And so, I can't instantiate Slim's Exceptions with this. PHP obviously complain:

> Argument 1 passed to Corp\Http\Exception\Factory::fromCode() must implement interface Psr\Http\Message\ServerRequestInterface, instance of GuzzleHttp\Psr7\Request given

I'm not really sure to knock at the right door, but I'm trying:

Would it be possible to "downgrade" the `Psr\Http\Message\ServerRequestInterface` parameter in the `Slim\Exception\HttpException` constructor to a simpler `Psr\Http\Message\RequestInterface` ?

Or should I rather knock at the GuzzleHttp door and try to make them use `Psr\Http\Message\ServerRequestInterface` ?

**Comment by l0gicgate** [comment]
Slim only handles `ServerRequestInterface` which are typically incoming. Guzzle uses `RequestInterface` because it's a client, which makes requests. Unfortunately we will not be changing this as this would be a BC break. What I suggest you do is create a transformer which takes your Guzzle request and adapts it into a `ServerRequestInterface`.

**Comment by Frzk** [comment]
Allright, I guess I'd rather build my own exceptions and override `Slim\Handlers\ErrorHandler::determineStatusCode()` in my own class.

Thanks for your time :-)
