### ISSUE TITLE
Application middleware not called if route is not matched

### ISSUE THREAD

**Issue by cdhowie** [slimphp/Slim#2897]
[The documentation](http://www.slimframework.com/docs/v4/concepts/middleware.html) states:

> Application middleware is invoked for every __incoming__ HTTP request.

In my tests, this is not true; application middleware is only invoked if there is a matching route somewhere in the application. After creating a test project with `php composer.phar create-project slim/slim-skeleton slimtest`, I added the following block of code below `$app = AppFactory::create();`:

```
$app->add(function ($request, $handler) {
        $response = new Slim\Psr7\Response();
        $response->getBody()->write('testing');
        return $response;
});
```

If I request `/` from the application, I see the output `testing`. If I request `/foo`, I see the output:

```
{
    "statusCode": 404,
    "error": {
        "type": "RESOURCE_NOT_FOUND",
        "description": "Not found."
    }
}
```

This seems to indicate that the middleware was not executed. Indeed, putting `die()` in the middleware will cause the request to terminate when requesting `/` but the output for `/foo` remains unchanged.

I'm not sure if this is a doc bug or a behavioral bug, but the current behavior does not match the documentation.

This was tested against 4.3.0.

**Comment by l0gicgate** [comment]
That’s because routing is done before your middleware gets reached and then throws an exception which is caught by the error middleware which will short circuit and return a response. 

Add your middleware after ErrorMiddleware and it will get reached first. 

Remember middleware is executed in Last In First Out order.
