### ISSUE TITLE
Timezone Not Set Triggers Application Error

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#29]
When using Slim::lastModified(time()) I'm running into an Application Error. I'm using Slim (latest Git rev) on nginx 0.7.67, php5.3.3 via FastCGI on OS X 10.6:

<pre>
The application could not run because of the following error:
Details:
Message: date() [function.date]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead
File: /Users/hexa/Code/api-v2.slim/slim/Slim.php
Line: 561
</pre>

**Comment by jimpsson** [comment]
Set "date.timezone" to it's correct value in your php.ini or use the php function date_default_timezone_set(). Here you have a list of supported timezones: http://www.php.net/manual/en/timezones.php

**Comment by hexa2k9** [comment]
True, my fault. Had to reinstall php from MacPorts and forgot to configure it properly.

Thanks for the hint.

**Comment by codeguy** [comment]
Should I leave Slim as is so that it **does** alert you of this issue? Or do you think I should implement something like the following in Slim.php which will ensure a Timezone is set, and if not, it will default to 'UTC'?

```
date_default_timezone_set(date_default_timezone_get());
```

If you have already set your timezone, this will effectively do nothing. If your timezone is not set, this would suppress the error you received and use UTC. Let me know what you think.

**Comment by hexa2k9** [comment]
well .. if there is a way to improve that it should be done in my eyes. that just makes one possible error less someone could run into.

**Comment by codeguy** [comment]
I agree. But I'll be sure to make a note of this default in the Docs. Re-opening and marking as a bug. Thanks!

**Comment by codeguy** [comment]
I've just pushed some new code that should fix this issue (see slim/Slim.php just before the Slim class declaration). If your system or ini file does not specify a timezone or that timezone is invalid, then Slim will use "UTC" by default. I'm closing this out for now. If you still have issues. Please leave a comment on this issue.

**Comment by hexa2k9** [comment]
My comment is: pulled, merged, works, thanks ;)
