### ISSUE TITLE
Laminas PSR17 Factory

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2911]
Should we add `\Slim\Factory\Psr17\LaminasDiactorosPsr17Factory`?

See https://github.com/adriansuter/Slim/tree/patch-laminas and https://github.com/adriansuter/Slim/blob/patch-laminas/Slim/Factory/Psr17/LaminasDiactorosPsr17Factory.php

Do you think we should remove `\Slim\Factory\Psr17\ZendDiactorosPsr17Factory`? I think that would be a BC, wouldn't it?

**Comment by l0gicgate** [comment]
We should add Laminas and leave Zend until the next major.

**Comment by t0mmy742** [comment]
Maybe we can deprecate Zend and inform users with phpdoc to move to Laminas.

**Comment by l0gicgate** [comment]
@t0mmy742 we should do that yes
