### ISSUE TITLE
Broken matching in .htaccess

### ISSUE THREAD

**Issue by ArneTR** [slimphp/Slim#292]
Based on you how the apache has ALREADY processed the route, the current default .htaccess may not work in all cases.

The problematic line is the following:

RewriteCond %{REQUEST_FILENAME} !-f

In my case, I included files named "functions.php" and hat the route "/functions/"

However in the functions.php the $app variable was not anymore available, because Apache routed the request directly to the functions.php and NOT through index.php.

So according to Apache documentation: 

"REQUEST_FILENAME
    The full local filesystem path to the file or script matching the request, if this has already been determined by the server at the time REQUEST_FILENAME is referenced. Otherwise, such as when used in virtual host context, the same value as REQUEST_URI."

This made the fix, cause it did not rely on the "purity" of the REQUEST_FILENAME:

RewriteCond %{REQUEST_URI} !-f

if you agree that this does not lead to more problems than it solves i would be happy if you include it in the current release.
This might possibly force SLIM to be installed in a root directory ... I haven't checked on that, cause currently SLIM is running directly in the root path domain.tld/ and NOT domain.tld/SlimFolder/

**Comment by ArneTR** [comment]
I need to correct the issue:

It still exists and I cannot load some routes, even with RewriteBase etc. stated.

However, switching to REQUEST_URI does not solve the problem, cause it prevents some static files to load.

Here is the code that led to the problem:

index.php:

require 'Slim/Slim.php';

$app = new Slim();
require dirname(**FILE**).'/functions.php';

require dirname(**FILE**).'/logs.php';

$app->run();

/\* The logs.php runs fine and has virtually the same code as the checks.php
*/

functions.php:

$app->get('/functions/', function () use ($app) { //$app is not set, cause SLIM loads file directly
  $app->render(
    '/functions/overview.php', array('author' => 'arne')
    );

});

**Comment by buggy** [comment]
It sounds like you have MultiViews enabled in your Apache config file. If you do then disabled it and try again.

**Comment by ArneTR** [comment]
Sry, my bad
