### ISSUE TITLE
Optional segments for route groups

### ISSUE THREAD

**Issue by delef** [slimphp/Slim#2926]
Hi! Thanks for your work on Slim 4. It's very good release of Slim.

But, tell me why `Slim/Routing/RouteGroup` not supporting Optional segments?

**Comment by l0gicgate** [comment]
I'm not sure what you mean. Can you give an example?

**Comment by delef** [comment]
```
$app->group('/users[/{user_id:[0-9]+}]', function (RouteCollectorProxy $group) {
    $group->get('/show', User\UserShowAction::class)->setName('user-show');
    $group->get('/preferences', User\Preference\ShowAction::class)->setName('user-preferences');
});
```

"Optional segments can only occur at the end of a route"

**Comment by l0gicgate** [comment]
That's a limitation from using `nikic/FastRoute` unfortunately. That's not something that we can fix from our side.

https://github.com/nikic/FastRoute/blob/4406c3b79b3cce4e906fa9c11cd564d2828f6257/src/RouteParser/Std.php#L51
