### ISSUE TITLE
addRoutingMiddleware in v4 documentation

### ISSUE THREAD

**Issue by gjdanis** [slimphp/Slim#2929]
**Background**

The example on this [documentation page](http://www.slimframework.com/docs/v4/) suggests that we should call `addRoutingMiddleware`. I don't think this is required in the current versions of Slim.

**Ask**

Please update the documentation if this method no longer exists in the current latest version of the framework.

**Comment by l0gicgate** [comment]
It’s necessary if you want to control in which order the routing is done.
