### ISSUE TITLE
PSR-3 support

### ISSUE THREAD

**Issue by elazar** [slimphp/Slim#2930]
## Introduction

The `logError()` method of the `Slim\Handler\ErrorHandler` class currently [calls](https://github.com/slimphp/Slim/blob/2058eea946d8569323104d188814c0ba2b1d1d2d/Slim/Handlers/ErrorHandler.php#L314) the native `error_log()` function directly.

Overriding this behavior is rather tedious, as it requires:

* Subclassing `Slim\Handler\ErrorHandler` to override `logError()`
* Duplicating a lot of the [boilerplate](https://github.com/slimphp/Slim/blob/2058eea946d8569323104d188814c0ba2b1d1d2d/Slim/App.php#L154) contained in the `addErrorMiddleware()` method of `Slim\App` to manually add an instance of the `ErrorHandler` subclass

## Proposal

Modify `Slim\Handler\ErrorHandler` to receive a dependency that implements the `Psr\Log\LoggerInterface` interface from [PSR-3](https://www.php-fig.org/psr/psr-3/).

To maintain backward compatibility, make this dependency optional. If no value is specified for it, use a default implementation of the interface that implements the current behavior of calling the `error_log()` function.

Add the logger instance as a parameter of the `addErrorMiddleware()` method of `Slim\App`. Again, make this parameter optional to maintain backward compatibility.

At this point, customizing the logging behavior can be done by calling `addErrorMiddleware()` with an instance of the desired logger implementation.

## Rationale

Slim 4.x already heavily utilizes PSR standards to allow for customization including [PSR-7](https://www.php-fig.org/psr/psr-7/), [PSR-11](https://www.php-fig.org/psr/psr-11/), and [PSR-15](https://www.php-fig.org/psr/psr-15/). It also has a need for error logging, as shown in the code referenced in the previous section, and PSR-3 addresses this need.

Additionally, an attempt was made to implement PSR-3 support in Slim 3.x (see #525), so the same need has existed in at least one previous major version of Slim.

## Backward Incompatible Changes

No changes that break backward compatibility are strictly necessary to implement this change.

In a future release where backward compatibility breaks are allowed, the `$logErrors` parameter of the `__invoke()` method of `Slim\Handler\ErrorHandler` could be removed, since the logger itself could be configured to log messages or not (e.g. by using [`NullLogger`](https://github.com/php-fig/log/blob/5628725d0e4d687e29575eb41f9d5ee7de33a84c/Psr/Log/NullLogger.php)).

## Proposed Version(s)

It should be possible to include this change as suggested in Slim 4.x.

The suggestion of removing the `$logErrors` parameter could be done in Slim 5.x if desired.

## Implementation

No implementation has been created yet. However, depending on the reception of this proposal, I'd be happy to create a pull request myself.

**Comment by l0gicgate** [comment]
I'm in favor of this. I'll be honest I'm a bit sad we did not include this in 4.x error handling by default. @adriansuter thoughts?

**Comment by adriansuter** [comment]
Yes.
