### ISSUE TITLE
Slim application errors

### ISSUE THREAD

**Issue by karthibca28** [slimphp/Slim#2933]
Slim Application Error
The application could not run because of the following error:

Details
Type: Propel\Runtime\Exception\PropelException
Message: Unable to execute INSERT statement [INSERT INTO pv_activation (id, uid, act_id, act_uuid, expire_time, act_time, user_agent) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6)]
File: /var/www/html/PitchVision-Dev/database/classes/pitchvision/db/pitchvision/Base/PvActivation.php
Line: 1125

**Comment by l0gicgate** [comment]
That isn't because of Slim, it's because there's an error in the ORM you're using (Propel).
