### ISSUE TITLE
Slim 4 running out of memory when long URLs are passed in

### ISSUE THREAD

**Issue by stevecoug** [slimphp/Slim#2935]
I have the following code:

```
use Slim\Factory\AppFactory;
require_once 'vendor/autoload.php';

$app = AppFactory::create();
$app->run();
```

I call it with this URL:
https://localhost:8443/api2/test/asdf/asdfasdfasdfasdf/asdfasdf/asdfasdf

My Apache server then crashes:
```
[crit] Memory allocation failed, aborting process.
[Tue Mar 31 15:34:05.903418 2020] [core:notice] [pid 1] AH00052: child pid 265 exit signal Aborted (6)
```

If I call it with this URL instead, it returns a 404 (as expected):
https://localhost:8443/api2/test/a/s/d/f

This is with Slim 4.4.0 running on PHP 7.3.16 and Apache 2.4.

**Comment by stevecoug** [comment]
My main concern here is that this represents a Denial of Service attack against my server, using routes that aren't even configured, so there's nothing I can do to stop it.

**Comment by l0gicgate** [comment]
I’m not sure what the exact issue is here. I’ve never encountered this problem. It’d be great to have the stack trace that preceded this failure to gain more insight.

**Comment by stevecoug** [comment]
Actually, when I commented out ALL of the code, I still had the same problem, so it appears to be an issue between Apache and PHP. Sorry to have bothered you.
