### ISSUE TITLE
Potential Output Buffering Issue

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#294]
http://help.slimframework.com/discussions/problems/703-get-route-outputs-the-number-of-chars-when-n-8000-output-buffering-problem

**Comment by jjt** [comment]
I'm the poster of that forum thread.

Same behaviour when using `$app->response()->body($output)` instead of the echo statement, and same when using an anon routing  function instead of a named one.

**Comment by codeguy** [comment]
Thanks for the additional info. I'll investigate this week and include a fix, if necessary, with 1.6.3.

**Comment by codeguy** [comment]
Can you send me the output of `phpinfo()` on your machine? Email to info [at] slimframework [dot] com if you'd rather not post here. I'm not seeing any issues on my machine so I'm wondering if it may be caused by some ob default settings with your local PHP install. I still want to make sure this is fixed, so I'll try to setup my local environment as close as possible to your own.

**Comment by jjt** [comment]
Emailed.

**Comment by codeguy** [comment]
So far I've been unable to replicate this. Any other info you can provide would be great. I'll keep looking, but so far no luck. If anyone else can replicate this, feel free to jump in.

**Comment by gurumike** [comment]
I saw this in the support forum; that looks like HTTP chunked transfer encoding.  It's correct output, as long as the proper transfer encoding HTTP header is set.  The client is responsible for decoding that.  It's possibly a configurable setting on your web server.

For apache, this might help:
http://serverfault.com/questions/59047/apache-sending-transfer-encoding-chunked

For decoding with PHP, see:
http://us.php.net/manual/en/function.http-chunked-decode.php

**Comment by codeguy** [comment]
I can't duplicate this... closing this out for now. Please move discussion back to the support forums until we can reliably replicate this so that it may be fixed if necessary.
