### ISSUE TITLE
4.x Is there short way for urlFor withRedirect ?

### ISSUE THREAD

**Issue by mkraha** [slimphp/Slim#2945]
There is way to use short way for urlFor withRedirect ?

From
`return $response->withRedirect(RouteContext::fromRequest($request)->getRouteParser()->urlFor('cart.index'));`

Like
`return $response->withRedirect(Router->urlFor('cart.index'));`

**Comment by l0gicgate** [comment]
Unfortunately there isn't. but why not split the code in 3 lines instead?
```php
$routeContext = RouteContext::fromRequest($request);
$url = $routeContext->getRouteParser()->urlFor('cart.index');
return $response->withRedirect($url);
```
