### ISSUE TITLE
Slimframework 2 problem - URL and Json output unescape

### ISSUE THREAD

**Issue by burakalac4** [slimphp/Slim#2961]
**Problem 1**
This is my nested array code
```
$product = $db->query("SELECT * FROM product")->fetchAll(PDO::FETCH_OBJ);
return $response
->withStatus(200)
->withHeader("Content-Type", 'application/json')
->withJson($product);
```

output 
```
[
{
"product_id": "1",
"product_name": "Ahmet",
"product_price": "10.00",
"product_status": "",
"product_slung": "",
"product_property": "{\"p1\": 1, \"p2\": \"Leanne Graham\", \"o3\": \"Bret\"}",
"product_createdtime": "{\"date\": \"06.05.2020\", \"time\": \"23:19\"}"
}
]
```
`{\"p1\": 1, \"p2\": \"Leanne Graham\", \"o3\": \"Bret\"}`

adding \ problem (unescape)

**Problem 2**
No problem when you enter this way
`http://as.localhost/api/product/`
When I enter this way, I get such an error
`http://as.localhost/api/product`
"Page Not Found"

**Comment by l0gicgate** [comment]
Which version of Slim are you using? Slim 3?

**Problem 1**
You should `var_dump($product)`. It seems as if your `$product` is being stringified twice for whatever reason. That object may already be implementing the `JsonSerializable` in a funky way causing this behavior. I would suggest trying to examine the raw behavior of `json_encode($product)` outside of the `withJson` method and see what that returns.

**Problem 2**
Can you show how you're declaring your route? `$app->get(???)`

**Comment by burakalac4** [comment]
> Which version of Slim are you using? Slim 3?
> 
> **Problem 1**
> You should `var_dump($product)`. It seems as if your `$product` is being stringified twice for whatever reason. That object may already be implementing the `JsonSerializable` in a funky way causing this behavior. I would suggest trying to examine the raw behavior of `json_encode($product)` outside of the `withJson` method and see what that returns.
> 
> **Problem 2**
> Can you show how you're declaring your route? `$app->get(???)`

`$app->get('/product/', function ($request, $response) {`

**Comment by l0gicgate** [comment]
~~Remove the trailing slash. `/product` or I believe you can do `/product/?` if you want to match both cases.~~

**Comment by burakalac4** [comment]
> ve you can do `/product/?` if you want to match both cases.

I did the following for my 2nd problem, but I am getting the page not found error at this time slim 3 version

$ app-> get ('/product/?', function ($ request, $ response) {

**Comment by l0gicgate** [comment]
> I did the following for my 2nd problem, but I am getting the page not found error at this time slim 3 version

I guess I was wrong. As per https://github.com/nikic/FastRoute/issues/106 you'll need to map the route twice if you want that, or you will need to add `TrailingSlashMiddleware` as per http://www.slimframework.com/docs/v3/cookbook/route-patterns.html

**Comment by l0gicgate** [comment]
I'm closing this as resolved.
