### ISSUE TITLE
Let Slim_Http_Request inspect body before parsing

### ISSUE THREAD

**Issue by urosgruber** [slimphp/Slim#297]
_UPDATE_: Slim_Http_Request should only parse the request body if it is a string and URL encoded. Currently, an upstream middleware layer may parse the request body; downstream middleware should respect upstream changes.

I'm searching for a clue why status is not set correctly to value set inside middleware. I've created a middleware where if things go wrong status is set to 400 and then just return instead of calling next middleware. 

If I check the status and also content type right after Slim echoes $body values are correct but curl outputs status 200 and content type text/html.

Am I missing something here or there is better way to make this work?

Thanks, U

**Comment by codeguy** [comment]
Can you post a gist of your code?

**Comment by urosgruber** [comment]
https://gist.github.com/2669367

and then add it with $app->add(new \SB\Middleware\JsonDecode());

It's the only middleware I add.

**Comment by codeguy** [comment]
Ok. The problem is that you are always calling the downstream middleware which will override the 400 response you are setting in your middleware. You need to update your conditional so that:

```
if ($env['slim.input'] == null) {
    $this->app->response()->status(400);
} else {
    $this->next()->call();
}
```

Only call the downstream middleware if the request is as you expect.

**Comment by urosgruber** [comment]
Just found the source of my problem. It was that echo of json_encode and headers were already sent and the code in Slim run function didn't go through setting headers at all. Maybe you could add to doc about not using echo inside middleware.

**Comment by codeguy** [comment]
Yep, that, too. Middleware is run _around_ the Slim application. Hooks are run _within_ the Slim application. Middleware should only be used to tweak the request and response objects before and/or after the Slim application is run. You should only echo content within a Slim app's route callbacks. Glad you figured it out!

**Comment by urosgruber** [comment]
Yes I change only one line and add error msg with app->response->body() instead of echo.

**Comment by urosgruber** [comment]
Hmm, still something missing or better say broken. I noticed that MethodOverride middleware is added inside Slim. And because I alter $env['slim.input'](same thing you did inside ContentTypes middleware) methodOverride doesn't get string from it. 

My basic idea is that API I'm building should always parse and decode json from raw input on POST and PUT. So there is no need to do this in every controler. And then I can use just  $app->request()->getBody() to get this json decoded object.

Do you think my approach is ok or there is better way to get this work.

**Comment by codeguy** [comment]
@urosgruber The Method Override middleware does not look at the environment's 'slim.input' variable. It only inspects the environment's 'REQUEST_METHOD' variable. Perhaps I misunderstand what you are trying to say.

**Comment by urosgruber** [comment]
It executes $req->post() which is where things breaks. It tries to parse it with  mb_parse_str where the code return Slim error.

"mb_parse_str() expects parameter 1 to be string, object given"

**Comment by codeguy** [comment]
Thanks for the details. I'll get a fix pushed up soon.

**Comment by codeguy** [comment]
Even though I added a minor solution to avoid this potential error, I'm not convinced this is a bug... if you expect your HTTP request to contain a JSON body, your request should have the `application/json` content-type header. Slim will only parse the request body with `parse_str` (or `mb_parse_str`) if the request content type is `application/x-www-form-urlencoded`.

**Comment by urosgruber** [comment]
My application do send application/json header but when I was testing the API on the server I probably forgot to add this header in curl request and then this issue pops out. If Slim works that way then it's perfectly ok. My mistake while testing, but still nice you add this extra check. Thank you for your help.
