### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by tesc0** [slimphp/Slim#2974]
Hello!

I've tried to find a solution for my error but couldn't figure it out for hours.

I'm trying to install the twig extension and followed this tutorial:
http://www.slimframework.com/docs/v3/features/templates.html

After I get an error message saying:
```
Fatal error: Uncaught Error: Using $this when not in object context in D:\xampp\htdocs\...\public\index.php:31
```

My code is (which is basicly a straight copy from the tutorial):
```
<?php
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;
use Slim\Views\Twig;
use Slim\Views\TwigMiddleware;

require __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

// Get container
$container = $app->getContainer();

// Register component on container
$container['view'] = function ($container) {
    $view = new \Slim\Views\Twig('../templates', [
        'cache' => '../cache'
    ]);

    // Instantiate and add Slim specific extension
    $router = $container->get('router');
    $uri = \Slim\Http\Uri::createFromEnvironment(new \Slim\Http\Environment($_SERVER));
    $view->addExtension(new \Slim\Views\TwigExtension($router, $uri));

    return $view;
};

$app->get('/',function($request, $response, $args) {

    return $this->view->render($response, 'index.html.twig', [ <--- this is the 31st line, the problem is here
        'name' => $args['name']
    ]);

});

$app->run();
```

I've tried to look for such errors and questions but these didn't seem to help.
https://steemit.com/utopian-io/@alfarisi94/how-to-use-twig-templating-in-slim
https://stackoverflow.com/questions/31363145/slim-php-fatal-error-using-this-when-not-in-object-context.

The basic hello world example in the slim installation worked.

So now I'm stumped. Can someone help me and tell me how can I fix this? 
Thank you very much!

**Comment by l0gicgate** [comment]
You’re using Slim 4 and referring to v3 documentation. 

Please refer to the Twig-View example on the [README here](https://github.com/slimphp/Twig-View)

**Comment by tesc0** [comment]
Thank you, now it works!
