### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Slim\App::__construct(), 0 passed in C:\xampp\htdocs\subscription-use-cases\server\php\index.php on line 14 and at least 1 expected in C:\xampp\htdocs\subscription-use-cases\server\php\vendor\slim\slim\Slim\App.php:57 Stack trace: #0 C:\xampp\htdocs\subscription-use-cases\server\php\index.php(14): Slim\App->__construct() #1 {main} thrown in C:\xampp\htdocs\subscription-use-cases\server\php\vendor\slim\slim\Slim\App.php on line 57

### ISSUE THREAD

**Issue by Alien10123** [slimphp/Slim#2984]
I am testing stripe subscriptions and i will be using the subscription example from stripe-example,  (on github)but i always get a error on this line:

$app = new \Slim\App();

Here is the error:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Slim\App::__construct(), 0 passed in C:\xampp\htdocs\subscription-use-cases\server\php\index.php on line 14 and at least 1 expected in C:\xampp\htdocs\subscription-use-cases\server\php\vendor\slim\slim\Slim\App.php:57 Stack trace: #0 C:\xampp\htdocs\subscription-use-cases\server\php\index.php(14): Slim\App->__construct() #1 {main} thrown in C:\xampp\htdocs\subscription-use-cases\server\php\vendor\slim\slim\Slim\App.php on line 57

I am using the slim framework. How do i fix this?

**Comment by l0gicgate** [comment]
You need to read the docs. The readme shows a working example.

**Comment by milan089** [comment]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Bulkgatesms::__construct(), 0 passed in D:\xampp\htdocs\jsds_new\system\framework.php on line 123 and exactly 1 expected in D:\xampp\htdocs\jsds_new\vqmod\vqcache\vq2-system_library_bulkgatesms.php:6 Stack trace: #0 D:\xampp\htdocs\jsds_new\system\framework.php(123): Bulkgatesms->__construct() #1 D:\xampp\htdocs\jsds_new\vqmod\vqcache\vq2-system_startup.php(104): require_once('D:\\xampp\\htdocs...') #2 D:\xampp\htdocs\jsds_new\index.php(27): start('catalog') #3 {main} thrown in D:\xampp\htdocs\jsds_new\vqmod\vqcache\vq2-system_library_bulkgatesms.php on line 6

**Comment by Bvenkat2001** [comment]
I'm getting this error while I am trying to test stripe for charge card during payment

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Slim\App::__construct(), 0 passed in D:\charging-a-saved-card\server\index.php on line 21 and at least 1 expected in D:\charging-a-saved-card\server\vendor\slim\slim\Slim\App.php:61 Stack trace: #0 D:\charging-a-saved-card\server\index.php(21): Slim\App->__construct() #1 {main} thrown in D:\charging-a-saved-card\server\vendor\slim\slim\Slim\App.php on line 61

**Comment by l0gicgate** [comment]
@Bvenkat2001 please open issue with a minimal amount of code to reproduce.

The examples from the docs are current and work.

```php
<?php
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;

require __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

$app->get('/hello/{name}', function (Request $request, Response $response, array $args) {
    $name = $args['name'];
    $response->getBody()->write("Hello, $name");
    return $response;
});

$app->run();
```

This works.

**Comment by preetimishra15** [comment]
<?php
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;
require '../vendor/autoload.php';
$app = new \Slim\App();
$app->get('/' ,function ($request , $response , $args)

{
    $response->write("welcome");
});
$app->run();
?>



Fatal error: Uncaught ArgumentCountError: Too few arguments to function Slim\App::__construct(), 0 passed in C:\xampp\htdocs\Slimproject\public\index.php on line 6 and at least 1 expected in C:\xampp\htdocs\Slimproject\vendor\slim\slim\Slim\App.php:47 Stack trace: #0 C:\xampp\htdocs\Slimproject\public\index.php(6): Slim\App->__construct() #1 {main} thrown in C:\xampp\htdocs\Slimproject\vendor\slim\slim\Slim\App.php on line 47
