### ISSUE TITLE
Review of php-slim4 server generator

### ISSUE THREAD

**Issue by ybelenko** [slimphp/Slim#2987]
Hey, Slim team!

Thanks for awesome framework! I'm top contributor to [OpenAPI-Generator](https://github.com/OpenAPITools/openapi-generator) project (open-source fork of Swagger Codegen). I've used different PHP libs and Slim framework is my favourite, that's why I'm responsible for `php-slim4` generator. It makes possible to create server stubs from [OAS3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md) API schema with single command:
```console
openapi-generator generate -i petstore.yaml -g php-slim4 -o /output
```
As result you'll get PHP server stubs which looks like [these samples](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/php-slim4).

We deeply ask for any review/advices/suggestions from Slim framework team. Our project is huge (1500+ contributors and [very long list of companies](https://github.com/OpenAPITools/openapi-generator#4---companiesprojects-using-openapi-generator) which use our codegen) and we don't want to disappoint such a big group of users. We're close to next major release `5.0.0` which will contain a lot of updates.

Here is [config options for php-slim4](https://openapi-generator.tech/docs/generators/php-slim4)

cc founders of OpenAPI Generator @wing328 and @jimschubert

**Comment by l0gicgate** [comment]
Hey @ybelenko, thank you for this. I'm a big fan of all the OpenAPI / Swagger stuff. I will try and review this as soon as possible and give feedback.

@adriansuter if you have some spare time maybe take a look as well!

**Comment by ybelenko** [comment]
> Hey @ybelenko, thank you for this. I'm a big fan of all the OpenAPI / Swagger stuff. I will try and review this as soon as possible and give feedback.

That wasn't expected at all 😆 

@l0gicgate I thought to subscribe you to Slim4 related PRs(we have 1 PR ready and 2 coming up), but I guess it's too much. How about review our samples just twice? In current state and once right before major release.

**Comment by l0gicgate** [comment]
@ybelenko you can subscribe me to those PR if you want. The more we can narrow the scope down the better as I'm pretty busy right now with work.
