### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by FvsJ101** [slimphp/Slim#2988]
Hi Guys, just a quick thanks for everyone's hard work on this fantastic framework.

The issue myself and some of the guys on slim framework forum are experienceing is with the _METHOD overwrite helper.

https://discourse.slimframework.com/t/405-method-not-allowed/4282/6

Some of use are getting the problem trying to overwrite the post to put and myself is getting on the delete.

Any assistance would be greatly appreciated.

**Comment by tflight** [comment]
I replied over in the forums too, but have you added the [Method Overriding Middleware](https://www.slimframework.com/docs/v4/middleware/method-overriding.html) to the routes that will need it?

https://github.com/slimphp/Slim/blob/4.x/Slim/Middleware/MethodOverrideMiddleware.php

**Comment by l0gicgate** [comment]
I'm closing this as resolved. The docs are clear.

**Comment by kdekooter** [comment]
If the docs were clear this issue would never have been submitted....
