### ISSUE TITLE
How to get baseUrl (not basePath) in Slim 4?

### ISSUE THREAD

**Issue by contactjavas** [slimphp/Slim#2994]
Hi! In slim 3 there was a method to get the base url of the uri. What is the right way to get the same with slim 4? Not basePath, but like this one: https://github.com/slimphp/Slim/blob/200c6143f15baa477601879b64ab2326847aac0b/Slim/Http/Uri.php#L825

Thanks.

**Comment by longquangpham90** [comment]
I have the same issue, we cannot getBaseUrl with slim4
can you help me, pls
