### ISSUE TITLE
Class 'Pimple\Container' not found on yii framework

### ISSUE THREAD

**Issue by lalitmalav** [slimphp/Slim#2998]
Hey, Slim team!

can you please suggest what could be the reason for this issue,

Issue >> http://prntscr.com/ufiyzd

PHP Fatal Error – yii\base\ErrorException
Class 'Pimple\Container' not found

We have installed slim thru composer

**Comment by ddrv** [comment]
@lalitmalav if I remember correctly yii uses its own class autoloader and it doesn't work quite correctly. Try turning on the composer's autoloader

**Comment by l0gicgate** [comment]
This is not a Slim related issue.
