### ISSUE TITLE
Default Parameters for Routes

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#30]
Just an Idea - may be this is one of those 20% of what you call edge use cases:
When defining a Route (Slim::get(nickinfo/:nick/:format) which has to get two parameters ('nick' and 'format' in this case) but those or a single one are not set, I'm getting a 404 by default. 

Now when adding some 'predefined defaults' for those 2 parameters wouldn't generate a 404 but makes the Application return proper results.

**Comment by codeguy** [comment]
Right now this is a "20%" thing in my opinion. But I can see where it would be helpful. For now, I am going to close this issue and add this to the Road Map's longer term goals. Please keep posting feedback as you run into issues. It's greatly appreciated.

For now, you can easily define a single function which accepts two arguments with default values. You can then define multiple routes using the same callback function.

```
$callback = function($nick = 'foo', $format = 'xml') {
    //Something
};
Route::get('/nickinfo/:nick/:format', $callback);
Route::get('/nickinfo/:nick', $callback);
Route::get('/nickinfo', $callback);
```

Not the most DRY code, I know. But this will work for now.

**Comment by hexa2k9** [comment]
That's how I'm running currently. The basic Idea behind my thought was to work with Slim::config's values.
`function ($nick, $format)` won't accept those values for setting them for defaults. 

<pre>
Route::get('nickinfo/:nick/:format', function () { 
  something 
})->defaults('nick' => Slim::config('nick'), 'format' => Slim::config('format'));
</pre>

 would take those as far as I see that.

Anyway .. thanks for the Moment. I keep running my current code for the Moment ;)
