### ISSUE TITLE
$app->run() gives 404 with nGinX

### ISSUE THREAD

**Issue by teemobean** [slimphp/Slim#300]
Hi - I'm trying to get Slim to work. I've browsed most of the issues on github as well as google and managed to get somewhere, but I still cannot get slim working properly.

Based on a post here, I use the following in my nGinX conf file. All my files are under /usr/share/nginx/html. Slim is installed there: /usr/share/nginx/html/Slim/*.

```
location / {
    root   /usr/share/nginx/html;
    index  index.php index.html index.htm;
    try_files $uri $uri/ /index.php?$request_uri;
}
```

Adding the try_files was relatively successful - it no longer 404s with just a simple require 'slim.php'

Here's my index.php:

require '/usr/share/nginx/html/Slim/Slim.php';
$app = new Slim();
$app->get('/hello/:name', function($name) {
    echo "Hello, $name";
});
$app->run();

if I comment out the $app->run(); line, it "works" (if I put text after this, it renders in the browser).

If I uncomment the $app->run() line, I get 404.

I'm not sure what I'm doing wrong - does anyone have ideas?

**Comment by codeguy** [comment]
I'm not an nginx expert so there's only so much I can suggest. However, I'm closing this issue out since it's not a problem with the framework itself. Post this question at http://help.slimframework.com/ and you should receive help there from other Slim users.

Best regards,
Josh

**Comment by teemobean** [comment]
ok thanks

**Comment by helenc77** [comment]
OMG thank you @teemobean 

try_files $uri $uri/ /index.php?$request_uri;

made everything work with Userfrosting (based on Slim), have been banging my head against a wall all morning!
