### ISSUE TITLE
Major Version Lifecycle

### ISSUE THREAD

**Issue by ewmanthei** [slimphp/Slim#3002]
Similar to [this inquiry](https://github.com/slimphp/Slim/issues/2140), it would be extremely useful to have something like [PHP Supported Versions](https://www.php.net/supported-versions.php) on the main README and/or website.  I contribute to some applications running version 3 but am not able to find how long we have until we must update to version 4.

Perhaps this exists and I'm just not seeing it?

Thanks in advance!

**Comment by Ayesh** [comment]
From previous comments by the maintainers, it seems that 3.x is not in active development. See comments in #2977.
But I agree, that a README section can help newcomers and existing users a lot.

**Comment by l0gicgate** [comment]
There is no defined lifecycle for Slim at the moment. Slim 3 is currently in maintenance mode only and Slim 4 will go in maintenance mode when Slim 5 is released. There's currently no roadmap to Slim 5 as we don't have enough contributors, feature requests, etc.
