### ISSUE TITLE
Trailing slash and route parameters

### ISSUE THREAD

**Issue by lekoala** [slimphp/Slim#3003]
I was reading the cookbook

https://www.slimframework.com/docs/v4/cookbook/route-patterns.html

The first thing I noticed is that the TrailingSlash middleware would need to call the redirect method as well like so

`$app->add((new TrailingSlash(true))->redirect($responseFactory));`

Otherwise I find the behavior a bit inconsistent when adding a trailing slash

$app->get('/hello/{name}/') => works well
$app->get('/hello/{name}') => doesn't work because it doesn't have the trailing slash

it would be great that defined routes worked in both cases regardless of the ending slash that may change due to a middleware that is added or not.

**Comment by l0gicgate** [comment]
Unfortunately we don’t control the route pattern matching. FastRoute provides that functionality which is a dependency of Slim. 

The middleware is specifically designed to remove the trailing slash from the URI and needs to be place on the outermost layer of the middleware stack so when routing is performed the route can be matched without the slash. 

As for redirection, you can implement your own middleware to do that if you care to.
