### ISSUE TITLE
CallableResolver not working with illuminate/container

### ISSUE THREAD

**Issue by fetzi** [slimphp/Slim#3004]
Hey,

I just noticed that the `CallableResolver` is not fully compatible with the illuminate/container's (Laravel) implementation. The PSR-11 Standard is kind of squishy for the implementation of the `has` method especially for not direct bound (autowiring) dependencies in the container.

The container's `has` method only returns true if the requested element is already known to the container. So I propose to change the implementation of the `resolveSlimNotation` to not use the `has` method but to wrap the `get` call into a try-catch block.

```php
private function resolveSlimNotation(string $toResolve): array
{
    preg_match(CallableResolver::$callablePattern, $toResolve, $matches);
    [$class, $method] = $matches ? [$matches[1], $matches[2]] : [$toResolve, null];

    if ($this->container) {
        try {
            return [$this->container->get($class), $method];
        } catch (ContainerExceptionInterface $ex) {
        }
    }

    if (!class_exists($class)) {
        throw new RuntimeException(sprintf('Callable %s does not exist', $class));
    }
    $instance = new $class($this->container);

    return [$instance, $method];
}
```

Would this be an acceptable solution for you? If yes, I can provide a PR implementing this change.

**Comment by JoeBengalen** [comment]
`has()` ... returns true if the container **can** return an entry for the given identifier. https://www.php-fig.org/psr/psr-11/

Not so squishy at all?

**Comment by fetzi** [comment]
@JoeBengalen: yes, the docblock comment states that, but the description above makes it squishy. https://www.php-fig.org/psr/psr-11/#112-reading-from-a-container 🤔

> has MUST return true if an entry identifier is known to the container and false if it is not.

I think the change should be possible and would allow to use the default `CallableResolver` instead of a custom one.

**Comment by l0gicgate** [comment]
@fetzi this seems to be a problem with the container implementation you’re using. The spec states that it needs to return `true` if the definition is present. 

You will have to use a custom callable resolver if you want to fix this.

**Comment by fetzi** [comment]
Yes, I totally understand the problem. I will try to open a PR on Laravel and fix the issue there. Thanks a lot 👍
