### ISSUE TITLE
Routing: setArgument() is not taking arrays any more

### ISSUE THREAD

**Issue by snoopy72** [slimphp/Slim#3005]
Hello,

upgrading from V3 to V4 we suddenly receive this error message:

```
Argument 2 passed to Slim\\Routing\\Route::setArgument() must be of the type string, array given, called in ...
```

Example (only for showing the system; namespaces and values renamed for public presentation):
```php
$app->group("/demo", function(RouteCollectorProxy $grp) {
    $grp->post("/test/{token}", "App\TestController:test")
        ->setArgument("param1", false)
        ->setArgument("param2", array("value1" => "N", "value2 => 15, ...))
        ->setName("test1");
});
```

That's "a bit" annoying for us, because we pass arrays as parameters to the route very successfully in our running slim app.

A quick change is not the best option: Our App contains several thousand routes and more files. We currently give service to also several 1000 customers with our app and are not is the position to "quickly" rebuild the whole routing.

Any idea or solution ?

**Comment by l0gicgate** [comment]
Use `setArguments()`
