### ISSUE TITLE
Slim\Http\Stream interface for file download in slim 4

### ISSUE THREAD

**Issue by realrecordzLab** [slimphp/Slim#3026]
Is the stream interface not anymore necessary when a file needs to be passed inside the response?
At the moment this code seems working but I saw some examples that implement `new \Slim\Http\Stream` interface

```
$app->get('/u/{filename}', function(Request $request, Response $response, $args){
    $filename = $args['filename'];
    $stream = file_get_contents(TMPDIR.$filename);
    $response->getBody()->write($stream);
    return $response;
});
```

**Comment by l0gicgate** [comment]
It's more elegant to use the stream and then either instantiate the `Response` object with that stream or use `$response = $response->withBody($stream)`;

There's more than one way to skin a cat 😄
