### ISSUE TITLE
Dev dependency in production mode

### ISSUE THREAD

**Issue by arokettu** [slimphp/Slim#3033]
4.7.0 added ``weirdan/prophecy-shim`` as a dependency but it's a testing package, it should be defined as a dev dependency

**Comment by j0k3r** [comment]
The fix will son be released https://github.com/slimphp/Slim/pull/3029

**Comment by arokettu** [comment]
@j0k3r thank you

**Comment by l0gicgate** [comment]
Just released 4.7.1

https://github.com/slimphp/Slim/releases/tag/4.7.1

cc @j0k3r
