### ISSUE TITLE
Slim 4 getParsedBody() doesn't work

### ISSUE THREAD

**Issue by MicheKOKORA** [slimphp/Slim#3040]
Regarding the Slim 's documentation  at [https://www.slimframework.com/docs/v3/objects/request.html#the-request-body ](url), it 's said getParsedBody() helps to get post parameters.

It doesn't work as it is described in the doc. 

**YOU CAN DO LIKE THAT IN ORDER TO FACE THE ISSUE**

**1-Get POST Param with getParsedBody()**
```
...
$parsedBody = $request->getParsedBody();
$keys_values =  array_keys($parsedBody);
$params = json_decode($keys_values[0] , true);  /** True to get params as Array. If u want Object  remove it */

/**  We can now use param .*/
$param1 =  $params["k"];
...
```

**2- Get POST Param with getBody()**
```
...
$parsedBody = $request->getBody();
 $params = json_decode($parsedBody  , true);  /** True to get params as Array. If u want Object  remove it */

/**  We can now use param .*/
$param1 =  $params["k"];
...
```

**3-Using Slim 4 BodyParser MiddleWare**
It 's also possible to use Slim BodyParsing Middleware. Ref to [https://www.slimframework.com/docs/v4/middleware/body-parsing.html](url)
Thanks to  @l0gicgate for that.

May It Helps SomeOne
Thanks

**Comment by l0gicgate** [comment]
Are you adding the body parsing middleware to your app? Because that should be done automatically.

**Comment by MicheKOKORA** [comment]
@l0gicgate 
I Updated the post. Thanks
