### ISSUE TITLE
Any Performance Impact on multiple RouteContext::fromRequest

### ISSUE THREAD

**Issue by wiryonolau** [slimphp/Slim#3041]
Hi is there a performance impact on calling RouteContext::fromRequest multiple time on different middleware ?

RouteContext seems a big class. From what I understand it will traverse the added route every time we use the function.

In the case I have multiple middleware e.g 
1. An authorization middleware that need to get the callable so that it can compare with the defined config
2. An csrf middleware that need to check the route argument whether it can be skip

The middleware is my own library not third party vendor you can neglect the function . The case is I need to use the RouteContext in multiple middleware. Calling multiple time feels like it will impact application performance.

Is there a best way to just call RouteContext once and pass the route object to the next middleware ?

**Comment by l0gicgate** [comment]
The short answer is no, there is no performance impact. All it does is give typed access to what is contained in the private request attributes it instantiates itself from.

**Comment by wiryonolau** [comment]
ok thanks for the clarification.
