### ISSUE TITLE
Duplicate options route not throwing error or working properly!

### ISSUE THREAD

**Issue by M-Shahbaz** [slimphp/Slim#3048]
If we have two routes with same name but different method `[POST, GET]`:
```
$app->post('/test', \App\Action\TestPostAction::class);
$app->get('/test', \App\Action\TestGetAction::class);

```
**ISSUE**: if we add two times options route with same name, then options name not working properly for **CORS** security policies of preflight request or **throwing slim error**:

```
$app->options('/test', function (
    ServerRequestInterface $request, 
    ResponseInterface $response
    ): ResponseInterface {
    return $response;
});
$app->options('/test', function (
    ServerRequestInterface $request, 
    ResponseInterface $response
    ): ResponseInterface {
    return $response;
});
```

**Comment by odan** [comment]
Hi @M-Shahbaz 

I don't understand why you try to add the same options route twice?
Have you tried to remove the redundant options route?

**Comment by M-Shahbaz** [comment]
Hi @odan 
Thanks for the quick response and I also learn and follow your slim4 tutorials 👍 

Created script to auto add preflight options on each route, rather than adding manually.

So if there are duplicate entries with same name in options route then it won't work.

e.g:
```
    $routes = $app->getRouteCollector()->getRoutes();

    $optionPatterns = [];
    foreach ($routes as $route) {
        if ($route->getPattern() == "/test") {
            continue;
        }
        $optionPatterns[$i] = $route->getPattern();
    }
    $optionPatterns = array_unique($optionPatterns);
    foreach ($optionPatterns as $value) {
        $app->options($value, \App\Action\PreflightAction::class);
    }
```

**Comment by M-Shahbaz** [comment]
This one throws error on OPTIONS registering route:

```
/users
/users[/{id:[0-9]+}]
```
error:

`Cannot register two routes matching "/api/users" for method "OPTIONS"`

**Comment by l0gicgate** [comment]
@M-Shahbaz this is a limitation with FastRoute. But theoretically speaking it's not a limitation, it's by design. What you're doing doesn't make sense. There should only be one OPTIONS route per route identifier. Otherwise, use middleware to achieve what you're trying to or a global options route handler.

**Comment by M-Shahbaz** [comment]
@l0gicgate Ok thanks.
