### ISSUE TITLE
Autoloader

### ISSUE THREAD

**Issue by Trekkerite** [slimphp/Slim#3051]
Hello. Can I somehow run it on shared hosting? Is there for example .htaccess and autoloader?

**Comment by odan** [comment]
>  Can I somehow run it on shared hosting?

Yes

> Is there for example .htaccess and autoloader?

Here: 

* https://www.slimframework.com/docs/v4/start/web-servers.html#apache-configuration
* https://www.slimframework.com/docs/v4/start/installation.html#step-4-hello-world

**Comment by l0gicgate** [comment]
Closing as resolved
