### ISSUE TITLE
How to deploy react app from slim 3

### ISSUE THREAD

**Issue by adarshwritescode** [slimphp/Slim#3055]
when i used node with express it was like
```
app.use(express.static('public'));

app.get('/',(req,res) => {
    res.sendFile(path.resolve(__dirname, "client", "build", "index.html"));
})
```

how to achieve same in php slim 3? 

Thanks (consider me a noob in php world)

**Comment by SDBlackwood** [comment]
@WhoAdarshPandya  I would take a look at the [First Tutorial section of the documentaion](slimframework.com/docs/v3/tutorial/first-app.html) and the  [Slim 3 Skelton](https://github.com/slimphp/Slim-Skeleton/tree/3.1.8) project which provides good examples of how to do things in Slim 3.  

If you want to just render a HTML template you can do the following, however it is much easier to [set up Twig](https://www.slimframework.com/docs/v3/features/templates.html) as the template rendering engine

```php
$app->get('/test', function (){
  return file_get_contents('<PATH TO TEMPLATE>');
});
```

**Comment by l0gicgate** [comment]
I would suggest serving static content in a different way, it's unnecessary to go through the router to do that. I'm not sure how this app is being deployed but I typically will generate the static assets and upload them to an S3 bucket and have CloudFront serve it. That enables you to leverage long term browser caching. The only file that doesn't get cached is the `index.html`

If you're not using any cloud based infrastructure I would highly suggest deploying Nginx instead to serve your static files so you can leverage caching also and bypass serving anything via your Slim App.

If you want to serve both your static files and gateway to your API via Nginx then I'd probably serve my API on a subdomain and the static files on the main domain. That way you can have two different configuration files.

PS: Why are you using Slim 3 and not Slim 4? 🤔
