### ISSUE TITLE
session is empty

### ISSUE THREAD

**Issue by MasterProvider** [slimphp/Slim#3064]
after  request sample/one  and I'm hoping that sample/two get data from the session but the session data is empty
even session_start(); is declared 

$app->post('/sample/one', function (Request $request, Response $response, $args) {
     
       $update = $request->getBody();
       
       $_SESSION["data"]=$update->data;
       $response->getBody()->write('succcesssss');
       return $response;
});

$app->post('/sample/two', function (Request $request, Response $response, $args) {

      $update = $request->getBody();
       
     $response->getBody()->write('succcesssss-'.$_SESSION["data"]);
       return $response;
});

**Comment by odan** [comment]
I would recommend asking this question on the [Slim forum](https://discourse.slimframework.com/).
