### ISSUE TITLE
How to improve my Api request time spent

### ISSUE THREAD

**Issue by y7ut** [slimphp/Slim#3065]
I upgrade my App from slim3, but it look slowly than before.  Is it because I use too much ErrorHandle or Middleware(Adapt some old function from old App) ? 
I try to change the PHP/DI config,  like add Container compilation or edit my Container setting. But it seem not work, Same as not edited it.  
Now the API only return some json string without any DB Connection , Well , I found it spend about 800ms times,  The average time spent in old projects is faster than it😭
So , Can anyone give me some tips to upgrade slim4 ?

**Comment by odan** [comment]
Do you have xdebug enabled or disabled?

**Comment by y7ut** [comment]
> Do you have xdebug enabled or disabled?

My App used to use "ln -s"  copy from  windows disk. 
..
Well, When I give up using it, move the project to other Wsl File's disk.
The spent of request  has raised up! !!
