### ISSUE TITLE
Nested groups can't have identically named routes.

### ISSUE THREAD

**Issue by adjenks** [slimphp/Slim#3066]
I'm getting an error for identical routes when I don't believe there are identical routes.

Here is my minimum test case:

```php
<?php

require 'vendor/autoload.php';

$app = \Slim\Factory\AppFactory::create();

$test = function(Request $request, Response $response){
	$response->getBody()->write('testing 123');
	return $response;
};

// Real pages:
$app->group('', function () use ($app,$test) {

	$app->group('/users', function () use ($app,$test) {
		$app->get('/test', $test);
	});

	$app->group('/clients', function () use ($app,$test) {
		$app->get('/test', $test);
	});
});

$app->run();
```

It's returning this error
>PHP Fatal error:  Uncaught FastRoute\BadRouteException: Cannot register two routes matching "/test" for method "GET" 

I was moving from Slim 3 to Slim 4 and renaming $this to $app to make my route groups work, but this error still shows up. Am I not doing it correctly?

My composer.json require section contains:
```
{
                "slim/slim": "^4.7",
                "slim/psr7": "^1.3"
 }
```

This worked fine previously, but now it throws an error. My understanding is that /users/test and /clients/test should be registered as routes. Only if there were two identical routes like /users/test and /users/test should it give this error.

**Comment by adjenks** [comment]
I think I clicked on the wrong documentation on your website, your search feature searches through all versions... It fooled me...

**Comment by gam04** [comment]
I have the same issue.

It seems nested group routes doesn't work 

```php
<?php

require 'vendor/autoload.php';

$app = \Slim\Factory\AppFactory::create();

$test = function(Request $request, Response $response){
	$response->getBody()->write('testing 123');
	return $response;
};

// Real pages:
$app->group('', function () use ($app,$test) {

	$app->group('/users', function () use ($app,$test) {
		$app->get('/test', $test);    // this route must be registered as  '/users/test' , however is registered as '/test'
	});

	$app->group('/clients', function () use ($app,$test) {
		$app->get('/test', $test);  // this route must be registered as '/clients/test', however is registered as '/test'
	});
});

$app->run();
```
