### ISSUE TITLE
Regex Patterns 

### ISSUE THREAD

**Issue by louiss0** [slimphp/Slim#3068]
/** 

    I tested this code out because i found a bug in the code i seems like Slim doesn't support
    
    allow anchoring which is something that I could accept but Why ? 

    anchoring is regex best practice and it looks like i must use "/" instead of "" in my code. 
    
    I wrote something similar to this but I had /posts first as my  group and used it
    
    "" after then /{slug: } then /comments

    This  \S+(?:-\w+) regex will work but ^\S+(?:-\w+)$ won't work

    Second the docs say that "/" and "" are the same but when it comes to using them

    route groups they are not 

    out $group ""

        inner $group "/{slug:}"
        
            inner $group "/comments"

    This sequence will not work even when I use a slash

 */

$app->group("/", function (RouteCollectorProxy $group) {
    # code...

    $group->get("", function (ServerRequestInterface $request, $response) {

        var_dump($request->getUri()->getPath());

        return $response;
    });

    $group->group("{slug:\S+(?:-\w+)}", function (RouteCollectorProxy $group) {

        $group->get("", function (ServerRequestInterface $request, $response) {

            var_dump($request->getUri()->getPath());

            return $response;
        });

        $group->group("/comments", function (RouteCollectorProxy $group) {

            $group->get("", function (ServerRequestInterface $request, $response) {

                var_dump($request->getUri()->getPath());

                return $response;
            });
        });
    });
});

**Comment by l0gicgate** [comment]
The route matching is done via FastRoute. Raise the issue on that repo. We do not handle that internally.
