### ISSUE TITLE
Initially too paranoid about Slim 4

### ISSUE THREAD

**Issue by plasid** [slimphp/Slim#3070]
@l0gicgate Please delete my last 2 issues, having looked deeper into Slim 4 I can now see that my comments were premature - Slim 4 is very powerful and granular, once you change your thought process from 3 to 4. :)

UPDATE: I previously looked at very complex skeleton apps (examples), I think that's what threw me.

Going back to the basic examples/implementation on the official Slim(4) site gave me hope, and Slim4 is in fact not nearly as complex as I previously thought.

To other Slim4 newbies, keep this in mind, start small and look at very basic examples first,  you can model a Slim4 app as simple or as complex as you need.
I will now proceed to migrate my Slim3 app to 4.:)

_Originally posted by @TradeSharer in https://github.com/slimphp/Slim/issues/2770#issuecomment-821869237_

**Comment by l0gicgate** [comment]
I understand this has been pretty polarizing to other Slim users and you are not alone feeling this way as we changed a lot of things from 3 to 4. But I promise it is for the better. 

To others with similar feelings, you can still use Slim 3 if you don't want to have to make some architectural decisions like choosing your preferred PSR-7 implementation.

Anyway, no hurt feelings here. I was just replying to your questions.
