### ISSUE TITLE
Need $response->withJson to sort by values

### ISSUE THREAD

**Issue by srojaspachas** [slimphp/Slim#3075]
If i have this array: `[1=>'a', 2=>'c', 3=>'b']`

When i reach... **$response->withJson**...

Is returning: `{"1":"a","2":"c","3":"b"}`

But if i want to sort the elements by value, having the previous array as: `[1=>'a', 3=>'b', 2=>'c']`

When i reach... **$response->withJson** again...

Still returns: `{"1":"a","2":"c","3":"b"}`

How could i make that **$response->withJson** method can return a value ordered JSON? like: `{"1":"a","3":"b","2":"c"}`

**Comment by odan** [comment]
Hi @srojaspachas 

Are you using Slim 3 or the Slim 4 Decorator `slim/http`?

The PHP `json_encode` function retains the order of the keys.

See here: https://3v4l.org/OVT6G

But there is a problem on the client side. As far as I know Firefox keeps the same order, but Chrome and IE sort them. 

Have you checked the response with Postman or an HTTP test?

**Comment by tuupola** [comment]
With JSON an object is an unordered collection of zero or more name/value pairs. Order of the keys is not guaranteed. Array on other hand is an ordered sequence of zero or more values. Ie in order to maintain the key order encode into an json array instead of json object.

**Comment by srojaspachas** [comment]
> Hi @srojaspachas
> 
> Are you using Slim 3 or the Slim 4 Decorator `slim/http`?
> 
> The PHP `json_encode` function retains the order of the keys.
> 
> See here: https://3v4l.org/OVT6G
> 
> But there is a problem on the client side. As far as I know Firefox keeps the same order, but Chrome and IE sort them.
> 
> Have you checked the response with Postman or an HTTP test?

Hi @odan and @tuupola ,

I'm currently using Slim 3. In Postman it's working fine. @odan you are right, the issue happens because the explorer is sorting the object, so i will try to return the data in a different way. Thanks a lot for your responses.

**Comment by srojaspachas** [comment]
Hi @odan and @tuupola ,

I'm currently using Slim 3. In Postman it's working fine. @odan you are right, the issue happens because the explorer is sorting the object, so i will try to return the data in a different way. Thanks a lot for your responses.
