### ISSUE TITLE
http://docs.slimframework.com/  how out of date is that?

### ISSUE THREAD

**Issue by siims-biz** [slimphp/Slim#3083]
Hello recently I was looking at some of my old php code.
And I found a composer file pointing to slim 2 with composer.lock pointing to this github.
I never started using it, as I was more interested in spending time with node.js
With the launch of php8 and so much rain and covid around, I started to refresh my php skills.
I am still undecided, weather to go with this framework or not.
I think, you are currently working on slim4 and slim5.
That makes me wondering, how out of date is
http://docs.slimframework.com/ ?
And how about letting it make a reference to your newer web pages.

**Comment by odan** [comment]
Thank you for pointing this out. We will fix this soon.

**Comment by odan** [comment]
The old sub-domain will be redirected now.
