### ISSUE TITLE
Upgrading to Slim4 broke a route - not sure how to debug

### ISSUE THREAD

**Issue by Ugoku** [slimphp/Slim#3085]
Hi, I've upgraded an old Slim2 project to Slim3 recently and am now upgrading it to Slim4. I didn't run into any major issues, but one of my routes broke and I can't figure out why.

My routes are laid out in `index.php` like this:

`$app->get('/contact/', ['\Application\Controller\Contact', 'contact']);`

The one that breaks is `$app->get('/locations/', ['\Application\Controller\Locations', 'overview']);`

If I change `/locations/` to `/locations/list/` or `/locationslist/` the route works just fine. This is the only route that doesn't work, it gets redirected to `/index.php/`.
If I go to `/foobarbaz/` (a non-existing route), I _don't_ get redirected so it seems `/locations/` is somehow special?

Is there anyone who can shed some light on this? If more information is needed, I am of course willing to provide whatever it takes :)

**Comment by odan** [comment]
As far as I know, routes should be defined without leading `/`.

**Comment by ddrv** [comment]
@Ugoku 
You should make sure that the application returns the redirect response. Maybe once you had a 301 redirect to this address and the browser cached this response?

Maybe the redirect occurs even before the application is called (in the web server configuration)

It is also worth checking that this route is not redefined anywhere in the application.

To test, do something like this: 

```php
// $app->get('/locations/', ['\Application\Controller\Locations', 'overview']);
$app->get('/locations/', function($req, $res, $args) {
    echo 'This route works'; die;
});
```

and open the page in a browser

**Comment by l0gicgate** [comment]
It would be great to show us an isolated code sample that reproduces the issue if you can. It's easier to help diagnose.

**Comment by Ugoku** [comment]
Sorry to have wasted all of your time. It appears the redirect to index.php was indeed a caching problem, but the route still wasn't working. After trimming the file to the bare minimum, I noticed the non-working route was missing a leading `/`, which must have occurred after creating this issue, since I copy-pasted the actual code in my OP. All in all, it seems there were two problems, both occurring between keyboard and computer ;)
It's working fine now so I can roll this out to production.

Thanks for your help!

**Comment by eerison** [comment]
Hello @Ugoku 

Could you say how was your migration from slim2 to slim3, was it smooth or did you face some issues.

is there something that I could pay attention besides of this: https://www.slimframework.com/docs/v3/start/upgrade.html

and how was your upgrade, did you bump first from 2.6.x to 3.0.0 and after that for the last version (3.12.5)?

other question, when you bumped to version 3, what php version were you using?

**Comment by Ugoku** [comment]
Hi @eerison , you realise this issue is over 2 years old right? I don't remember, but git does ;)

I was on PHP 7.4 at the time, and went from Slim 2.6.3 to 3.12.3. I also migrated from `petebrowne/slim-layout-view` to `slim/php-view`.

I think the biggest issue was that every route in my controllers needed rewriting to accept request, response, and arguments parameters. Pretty smooth, I would say :)

**Comment by eerison** [comment]
> Hi @eerison , you realise this issue is over 2 years old right? I don't remember, but git does ;)
> 
> I was on PHP 7.4 at the time, and went from Slim 2.6.3 to 3.12.3. I also migrated from `petebrowne/slim-layout-view` to `slim/php-view`.
> 
> I think the biggest issue was that every route in my controllers needed rewriting to accept request, response, and arguments parameters. Pretty smooth, I would say :)

Yes I know it is a quite old issue.

But thank you so much for your effort to try to remember how was the progress.

and btw from 3 for 4 was smooth as well?

**Comment by Ugoku** [comment]
Hey, sorry for the late reply.

From 3 to 4, the major thing was replacing Slim's request/response with Guzzle and Slim's container with php-di's container. Some methods that changed etc.

Overal, from 3 to 4 was a lot easier than from 2 to 3!

**Comment by eerison** [comment]
really thank you for your effort in remember how was this migration 2 years ago!

I really appreciate that <3
