### ISSUE TITLE
PHP 8 compatibility for 2.x branch

### ISSUE THREAD

**Issue by gnutix** [slimphp/Slim#3089]
Hello there,

I'm currently upgrading a project heavily using the 2.x branch (and we can't possibly upgrade to 3.x, even less 4.x) to PHP 8. So I've forked your repository to https://github.com/gammadia/slim-2.x (simply replace `"slim/slim": "^2.6"` by `"gammadia/slim-2.x": "^2.6"` in your `composer.json` to use it) and adapted the code so the tests would pass. There's very few necessary changes from what I can see : a change about `get_magic_quotes_gpc()` and another about `libxml_*` functions.

I am therefore wondering if there is a plan to keep maintaining the compatibility with recent PHP versions for this branch ? Or if it is really EOL and unmaintained ? The current `composer.json` has a `"php": ">=5.3.0"` requirement, which is misleading, as it doesn't work on PHP 8.

Thanks for your insights.

**Comment by l0gicgate** [comment]
Slim 2.x and 3.x are in maintenance mode and only critical security updates will be deployed to those branches. We will not be adding PHP 8 support for those branches unfortunately.

**Comment by gnutix** [comment]
@l0gicgate Wouldn't it make sense to change the `php` requirement in `composer.json` to something like `>=5.3,<8.0` then (or whatever "upper" version of PHP was actually properly tested with slim 2.x) ?
