### ISSUE TITLE
The method redirect() clears the session data in Internet Explorer

### ISSUE THREAD

**Issue by cezarsmpio** [slimphp/Slim#309]
Hi guys, I'm using $app->add(new Slim_Middleware_SessionCookie); for my session. It's working perfect in Chrome, Firefox and another browser, but in IE, when I use $app->redirect for redirecting for another page,  the session data it's cleared.

Before redirect I using print_r in $_SESSION and the data is returned normally. But, after redirect, the session data are simply cleared.

Any idea? Thanks!

**Comment by codeguy** [comment]
Please move this to http://help.slimframework.com/. You're more likely to receive more input there. I prefer to keep the Issue Tracker for issues that are immediately actionable. Thanks!
