### ISSUE TITLE
Version in App.php not updated

### ISSUE THREAD

**Issue by WilliamStam** [slimphp/Slim#3091]
the version in App.php isnt matching the released tag. i saw my version in my vendor folder was showing as `public const VERSION = '4.7.0';` whereas the "tag" on github is 4.8.0 and i got very confused. not that this matters much in an app, still something somone might want to update at some point :P 

https://github.com/slimphp/Slim/blob/aa9c401f9d813a57a569a2d2b82f9acac3577bd2/Slim/App.php#L41    
```public const VERSION = '4.7.0';```

![image](https://user-images.githubusercontent.com/182800/123611571-06c46300-d802-11eb-95be-61cfadcf4928.png)

**Comment by JustSteveKing** [comment]
This, would be a great PR for someone who wants to learn about the process of open source development!

**Comment by l0gicgate** [comment]
Fixed via https://github.com/slimphp/Slim/releases/tag/4.8.1
