### ISSUE TITLE
example checked out from git results in 404

### ISSUE THREAD

**Issue by edwardtrunk** [slimphp/Slim#310]
hello, here are the specifics

os: centos 6.2
php: 5.3.3
apache 2.2.15 mod_rewrite on
document root /var/www/html
/var/www/html/.htaccess

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php [QSA,L]

Slim cloned today in /var/www/html which results in /var/www/html/Slim/Slim/Slim.php  

cd /var/www/html
created .htaccess as shown above
created index.php as shown in tutorial but changed require 'Slim/Slim.php' to require 'Slim/Slim/Slim.php as that is how it checkouts out from git and how I would be inclined to use it

typed in example and received the good ole 404. -- looked in logs -- nada -- spent a long time google/search and reading entries in the Slim Issues section...

and then I tried something -- I had done a git clone right into /var/www/html as I wanted to get the example running right away so my path looked like /var/www/html/Slim/Slim/Slim.php. So I moved /var/www/html/Slim to Slim.src and cd Slim.src and cp -r Slim ..

and http://localhost/hello/fubar works as expected -- when i get a chance i'll look into why the things were not working when checked out directly from git.

**Comment by codeguy** [comment]
This is not a framework issue but a local installation-specific issue. Please move this to http://help.slimframework.com instead. Thanks!
