### ISSUE TITLE
Uploaded files are only present on POST requests

### ISSUE THREAD

**Issue by fabiante** [slimphp/Slim#3109]
Hi,

I noticed that the contents of `[$request->getUploadedFiles()](https://www.slimframework.com/docs/v4/objects/request.html#uploaded-files)` is only populated on POST requests.

I am not sure if according to some RFCs body contents should not contain `multipart/form-data` but that sounds unlikely.

Would it be reasonable to support this for other HTTP verbs than POST?

**Comment by odan** [comment]
As far as I know, the HTTP specification [RFC1867](https://datatracker.ietf.org/doc/html/rfc1867#section-2) defines that files has to be uploaded using the `POST` method.

> HTML forms with file submission
> In addition, it defines the default ENCTYPE attribute of the FORM element using the POST METHOD to have the default value
 "application/x-www-form-urlencoded".
   
There are further problems if you try to upload files via PUT/PATCH, as this is not directly supported by PHP itself and no PSR-7 implementation supports it.

**Comment by fabiante** [comment]
Hm, haven't looked deeply into this. But RFC1867 is about HTML forms. In case of a web API, would that even apply?

**Comment by l0gicgate** [comment]
This is not an issue with this library. It’s the default PHP behavior. File uploads are only parsed on POST requests. 

One way to get around this if you must use a PUT to map your route, you can use method overriding middleware to map POST to a PUT route. 

Or you can parse the file uploads manually:
https://www.php.net/manual/en/features.file-upload.put-method.php

Another way would be to have an endpoint which handles all file uploads and you would do two separate requests:
1. POST Request to upload the file which would return a reference to the file you uploaded in form of a unique id. 
2. When dispatching the PUT request you would pass in reference from previous request with the already uploaded object.
