### ISSUE TITLE
Cannot use filenames with extensions (full stop in paths)

### ISSUE THREAD

**Issue by nigeljohnson73** [slimphp/Slim#3110]
I'm attempting to get Google App Engine working, and they say this is the front thing to use. Before we go all rest API, some clients do still automatically request `/favicon.ico` so using a full stop in paths is a valid thing... and if I want to return images, I guess it's still valid, also (still to learn how to serve a static directory for a javascript library). But it seems I cannot (or more likely don't know how to) serve any of the following:

```
/gfx/applogo.png
/gfx/favicon.png
/js/app.min.js
/app.min.js
/app.min
```

I can serve

```
/js/app
/gfx/favicon
/gfx/applogo
```

Here is my code snippet for my 'standard' javascript file, inside index.php:

```
$app->get ( '/js/app.min.js', function (Request $request, Response $response) {
	logger("Doing javascript"); // So I know it happens
	ob_start ();
	include (__DIR__ . "/_js/app.min.js.php"); // this file does categorically exist
	$c = ob_get_contents ();
	ob_end_clean ();
	$response->getBody ()->write ( $c );
	return $response;
} );
```

I then followed the limited/confusing to me instructions [on the slim site](https://www.slimframework.com/docs/v4/start/web-servers.html) about running in a PHP standalone server... do I need to do the rest of the bits??? reckoned so, I set up a `.htaccess` file

```
Nigels-iMac-Pro-6:www nigel5$ cat .htaccess 
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
```

Then did the bits about enabling modules in my `/etc/apache2/http.conf` file (not `apache.conf` file as in the instructions) and setting specific directory entries:

```
<Directory /Users/nigel5/git/coin73/www>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
```
I restarted apache (and even rebooted)

I start a local PHP server:

```
Nigels-iMac-Pro-6:www nigel5$ php -S localhost:8080
PHP 7.3.24-(to be removed in future macOS) Development Server started at Sat Sep  4 16:52:01 2021
Listening on http://localhost:8080
Document root is /Users/nigel5/git/coin73/www
Press Ctrl-C to quit.
[Sat Sep  4 16:52:03 2021] [::1]:55597 [404]: /js/app.min.php - No such file or directory
```
As you can see, the directories match (I have tried the Directory entry with and without the ending slash), but I get the 404, and a pretty PHP coloured error:

![image](https://user-images.githubusercontent.com/6493525/132100579-7e7e4c0c-9a33-4726-891f-553a47e5378c.png)

I tried serving from the root `/app.min.js` but get the same issue.

If I run this through the dev server script, I get a blank screen and empty document (even though I have an entry in `app.yaml` for everything to go through my `index.php`) the fact I get a 200 response code means it didn't bomb out.

```
Nigels-iMac-Pro-6:www nigel5$ dev_appserver.py app.yaml --php_executable_path /usr/bin/php
INFO     2021-09-04 16:05:23,989 devappserver2.py:309] Skipping SDK update check.
INFO     2021-09-04 16:05:24,122 api_server.py:383] Starting API server at: http://localhost:59032
INFO     2021-09-04 16:05:24,229 dispatcher.py:267] Starting module "default" running at: http://localhost:8080
INFO     2021-09-04 16:05:24,230 admin_server.py:150] Starting admin server at: http://localhost:8000
INFO     2021-09-04 16:05:25,700 instance.py:294] Instance PID: 76098
INFO     2021-09-04 16:05:31,799 module.py:861] default: "GET /app.min.php HTTP/1.1" 200 -
INFO     2021-09-04 16:05:32,403 instance.py:294] Instance PID: 76149
INFO     2021-09-04 16:05:38,669 module.py:861] default: "GET /js/app.min.php HTTP/1.1" 200 -
```

What can I try to diagnose this?

**Comment by odan** [comment]
Hi Nigel

The documentation contains configuration examples for various web servers.
The **PHP built-in server** is intended for local development and does not require configuration files.  The second section describes how to set up **Apache** correctly using `mod_rewrite`. The PHP built-in server and Apache run completely independently and have nothing to do with each other.

When you start the PHP built-in server, you have to make sure that you either start the php command in the document root (where your index.php file is) or you set the document root using the `-t public/` parameter.

* https://www.php.net/manual/en/features.commandline.webserver.php

**Comment by nigeljohnson73** [comment]
I am using the php internal testing server and there is something else going on. I found the fix though, I forget where I found it but you need to create a separate file (I called mine `router.php` next to your `index.php` file with this in it.

```
<?php
$_SERVER['SCRIPT_NAME'] = 'index.php';
include 'index.php';
?>
```

Then when you call the PHP server use this

```
php -S localhost:8080 -t . router.php
```

Or I start mine from the parent directory as I also use dispatch.yaml on the GAE server (that doesn't work locally but I digress)

```
php -S localhost:8080 -t www www/router.php
```

I don't know if just calling the `index.php` file directly will work, as I didn't do much testing (there are other issues unrelated to this I need to fix :) 

Maybe this might help someone else? Maybe there is a documentation update?

**Comment by odan** [comment]
Thanks for your feedback. I am absolutely sure that this additional file (router.php) is not needed for a Slim project to work. For example, when I start the internal web server, I use this command:

```
cd {project-path/}
php -S localhost:8080 -t public
```

Then navigate to: `http://localhost:8080/`

The `public/` directory contains the `index.php` front controller file.

Can you please try this setup?

In case you still have trouble with the setup, you may try to upload the [Server Setup Checker](https://github.com/odan/slim-checker) to get an idea about the issue.

**Comment by nigeljohnson73** [comment]
![image](https://user-images.githubusercontent.com/6493525/132998327-c9b3aceb-d420-4320-870f-c8a56f9c78a9.png)

If I don't use the `router.php` file and don't declare the entry file, the file request with dots in it doesn't work. If I restart through the router.txt file all is well. 

The third attempt was to just use the `index.php` file specifically, and this also works. So the `router.php` file is not needed specifically, however, the entry point is required to be specified.

**Comment by tuupola** [comment]
This is a "feature" of the PHP builtin webserver. It assumes any url with a dot in the filename to be a static file. 

https://bugs.php.net/bug.php?id=61286

Apparently there is a workaround though:

https://www.php.net/manual/en/features.commandline.webserver.php

_"If a PHP file is given on the command line when the web server is started it is treated as a "router" script. The script is run at the start of each HTTP request. If this script returns false, then the requested resource is returned as-is. Otherwise the script's output is returned to the browser."_

With this info we can make a kludge which checks if the given file exists.

```php
<?php 

/* Workaround for routes with a dot. */
if (php_sapi_name() == "cli-server") {
    $_SERVER["SCRIPT_NAME"] = basename($_SERVER["SCRIPT_FILENAME"]);

    $file = parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH);

    if (file_exists(__DIR__ . $file)) {
        /* Return contents of the static file. */
        return false;
    }
}

require __DIR__ . "/../vendor/autoload.php";

$app = new Slim\App();

$app->get("/foo.txt", function ($request, $response, $arguments) {
    print "foo from slim\n";
});

$app->run();
```

```
$ php -S localhost:8080 index.php  
```

```
$ curl http://localhost:8080/foo.txt
foo from slim
$ echo "foo from file" > foo.txt
$ curl http://localhost:8080/foo.txt
foo from file
$ rm foo.txt
$ curl http://localhost:8080/foo.txt
foo from slim
```

But in my opinion you're better off by using Vagrant or Docker as development environment instead.

**Comment by nigeljohnson73** [comment]
Docker and that other thing all sound quite complex to just get a webserver going. You could just update the documentation about invoking the local development server from this:

```
cd {project-path/}
php -S localhost:8080 -t public
```

to this:

```
cd {project-path/}
php -S localhost:8080 -t public public/index.php
```

Assuming you're service from the 'public' folder :)

When PHP fix the bug, the instructions are still valid, and everything works really well so far.

**Comment by odan** [comment]
I have tested it with (`php -S localhost:8080 -t public`) to serve files on my local machine with the internal webserver and it works as expected. If there is a file on the harddisk, then the file will be served. If there is no file, but a Slim route, the route will be handled. This also works with a dot in the filename.

When I enter `php -S localhost:8080 -t public/index.php` I get this error: `public/index.php is not a directory.`

Just a question. You have defined this route: `$app->get ('/js/app.min.js', ...`, but you are testing a url like `/js/app.min.php`. 
Is this correct? If, yes, an 404 error (not found) would be correct in this case.

**Comment by RyanNerd** [comment]
> When I enter `php -S localhost:8080 -t public/index.php` I get this error: `public/index.php is not a directory.`

The error message is correct. The `php -t` switch is expecting a **directory** you passed in a **file name**. Should read:
` php -S localhost:8080 -t public`

**Comment by nigeljohnson73** [comment]
> When I enter `php -S localhost:8080 -t public/index.php` I get this error: `public/index.php is not a directory.`

Have a quick recheck above

```
php -S localhost:8080 -t public public/index.php
```

the `-t public` is the directory, and then the entry point is specified after this `public/index.php`

> Just a question. You have defined this route: `$app->get ('/js/app.min.js', ...`, but you are testing a url like `/js/app.min.php`.
> Is this correct? If, yes, an 404 error (not found) would be correct in this case.

Yep, in the original post I define the route:

```
$app->get ( '/js/app.min.js', function (Request ...
```

And in the screenshot up there, where its not using the entry point, you can see it's complaining about `/js/app.min.js`

**Comment by l0gicgate** [comment]
I'm closing this as resolved as it is not an issue related with Slim.
