### ISSUE TITLE
Could not install ratchet

### ISSUE THREAD

**Issue by harpreetsb** [slimphp/Slim#3111]
Hi 
I was able to install Slim4 framwork with [following setps](https://www.slimframework.com/docs/v4/start/installation.html),
But now I cannot install ratchet. Running `composer require cboden/ratchet` gives me following error:
![Selection_007](https://user-images.githubusercontent.com/6584304/132135495-8310d340-2429-4ef1-9866-3aba019ecdd8.png)

Please help

**Comment by odan** [comment]
You can use the `-W` option. `composer require cboden/ratchet -W`

**Comment by harpreetsb** [comment]
> You can use the `-W` option. `composer require cboden/ratchet -W`

Already tried this, does not work

**Comment by l0gicgate** [comment]
What version of Slim are you using? If you’re using the `dev` branch we’ve had to upgrade Guzzle to `^2.0` since we wanted to use their http factories. 

If you lock the Slim version to `“slim/slim”: “4.8.1”` delete your lockfile and reinstall all the dependencies it should work as long as you’re using guzzle/psr7 1.x

If this doesn’t work then we’ll need you to provide more info about the project. Your composer file would be helpful to see.

**Comment by harpreetsb** [comment]
I followed what is given on [Slim documentation](https://www.slimframework.com/docs/v4/start/installation.html)(shared in fist post)
`composer require slim/slim:"4.*"`
then as asked in documentation
`composer require slim/psr7`
`composer require nyholm/psr7 nyholm/psr7-server`
`composer require guzzlehttp/psr7 http-interop/http-factory-guzzle`
`composer require laminas/laminas-diactoros`

and finally running
`composer require cboden/ratchet` gives the error

**Comment by l0gicgate** [comment]
You need to pick one psr7 implementation. Not all of them. 

Can you share your composer.json file please

**Comment by harpreetsb** [comment]
```
{
    "require": {
        "slim/slim": "4.*",
        "slim/psr7": "^1.4",
        "nyholm/psr7": "^1.4",
        "nyholm/psr7-server": "^1.0",
        "guzzlehttp/psr7": "^2.0",
        "http-interop/http-factory-guzzle": "^1.2",
        "laminas/laminas-diactoros": "^2.6"
    },
    "autoload": {
        "psr-4": {
            "App\\Controllers\\": "app\\Controllers"
        }
    }
}

```

**Comment by l0gicgate** [comment]
Remove guzzle dependencies, laminas and nyholm. Then remove the lock file and rerun `composer install`

**Comment by harpreetsb** [comment]
just this?
```
{
    "require": {
        "slim/slim": "4.*",
        "slim/psr7": "^1.4",
        "guzzlehttp/psr7": "^2.0",
        "http-interop/http-factory-guzzle": "^1.2",
    },
    "autoload": {
        "psr-4": {
            "App\\Controllers\\": "app\\Controllers"
        }
    }
}
```

**Comment by l0gicgate** [comment]
Remove the guzzle dependencies. You only need slim/psr7. The ratchet package will install the guzzle dependencies it needs and they won’t conflict with the ones from your composer file.

**Comment by harpreetsb** [comment]
got it, ratchet installed

**Comment by l0gicgate** [comment]
Awesome 👏🏼 I’m closing this as resolved
