### ISSUE TITLE
Support PHP 8 on Slim 2.x

### ISSUE THREAD

**Issue by mariosimao** [slimphp/Slim#3119]
According to the `composer.json`, Slim 2.x supports any version of PHP greather or equal to `5.3.0`.
```json
"require": {
    "php": ">=5.3.0"
}
```
However, Slim 2 does not work on PHP 8 due to the use of `get_magic_quotes_gpc()` [here](https://github.com/slimphp/Slim/blob/2.x/Slim/Http/Util.php#L60).

According to the [PHP documentation](https://www.php.net/manual/en/function.get-magic-quotes-gpc.php), `get_magic_quotes_gpc()` was removed as of PHP 8.0.0.

With the problem explained, let's jump to the solution. I can only think of two possibilities:

1. Change the PHP version requirement on Slim 2 to `>=5.3.0` and `<8.0.0`.
2. Check if the function `get_magic_quotes_gpc()` exists before calling it. Something like:

    ```php
    $magicQuotes = false;
    if (function_exists("get_magic_quotes_gpc")) {
        $magicQuotes = get_magic_quotes_gpc();
    }

    $strip = is_null($overrideStripSlashes) ? $magicQuotes : $overrideStripSlashes;

    // ...
    ```

I would suggest option number 2, so Slim 2.x could still work on newer versions of PHP.

If you agree with the proposed solution, I could happily open a PR for this issue.

**Comment by l0gicgate** [comment]
Deploying anything on the Slim 2 branch isn't an option at this point really. Running an outdated version of Slim on PHP 8 isn't necessary. If people want to make this happen they can fork and fix those issues.

**Comment by mariosimao** [comment]
Well, this is unfortunate due to the small size and impact of the proposed change. 

So I think the PHP requirement on `composer.json` should be at least be changed to not allow Slim installation on PHP 8.

**Comment by l0gicgate** [comment]
You're missing the point. I agree the change is small and could be done easily but nothing has been deployed from that branch in over 5 years. I don't feel confident especially without any CI pipeline implemented on that branch to deploy a new release tag. The work that needs to be put in to ensure this goes smoothly doesn't warrant the upside of making it PHP 8 compatible.

**Comment by mariosimao** [comment]
I understand the pains that would be to deploy another version of Slim 2, so I am no longer interested in making it work on PHP 8.

**Comment by tuupola** [comment]
if you want to use Slim 2 with PHP 8 you could also define the `get_magic_quotes_gpc()` yourself. It has only been returning `false` for a long time.

https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

```php
function get_magic_quotes_gpc() 
{
    return false;
}
```

**Comment by mariosimao** [comment]
Hi @tuupola. Yes, this is exactly what I will be doing on legacy APIs. New ones will be using slim 4
