### ISSUE TITLE
$app->router()->getCurrentRoute() question/issue

### ISSUE THREAD

**Issue by pablofierro** [slimphp/Slim#314]
Hello, when calling:

``` php
$app->router()->getCurrentRoute();
```

this error message comes out:

```
 current() expects parameter 1 to be array, null given
```

I'm using this method inside a Middleware, an authentication middleware, so I check for all incoming requests before actually continuing running the app.

Using  `$app->call()` is not an option, since this is a middleware and it gets called before everything else.

Any advice or perhaps a fix for this issue ?

Cheers

**Comment by codeguy** [comment]
Routes are not known until iterated when the Slim application itself is called. Currently, middleware will not know. I will update this method to return `false` in your scenario.

**Comment by pablofierro** [comment]
This can be fixed by modifying current() function inside the router class by this:

```
public function current() {
  return current($this->getMatchedRoutes());
}
```

Any reason why you are not using this ?

**Comment by pablofierro** [comment]
@codeguy indeed, I understand why it is happening but, if I won't be able to use that method in a middleware, could there be any solution for this ?

**Comment by codeguy** [comment]
Give me a few days and I'll see what I can do.

**Comment by pablofierro** [comment]
I'm currently using this to get the current request route:

```
$current_route = $app->router()->getMatchedRoutes();
if($current_route) {
  $current_route = $current_route[0];
  $current_route = $current_route->getPattern();
}
```

**Comment by pablofierro** [comment]
I forgot to mention I was defining my routes before adding the middleware, so this works for me.
