### ISSUE TITLE
Before Middleware Response overwrites REST API Controller Response?

### ISSUE THREAD

**Issue by met68** [slimphp/Slim#3141]
A couple of days ago I opened and closed the following issue, where I found-out eventually, that my before middleware was automatically overwriting the status code I set in my REST API controller response:

[https://github.com/slimphp/Slim/issues/3140](url)

My invokable before middleware was based on the BEFORE Hello World example given in the docs:

[https://www.slimframework.com/docs/v4/concepts/middleware.html](url)

In this, you instantiate a new Response as follows:

`$response = new Response();`

It turns-out, when I do this, any response status codes I set in the controllers, which get hit AFTER passing through the before middleware, get overwritten with HTTP status 200 automatically, no matter what status codes I try and set in my REST API controllers.

This probably isn't an issue as such, but I don't understand, why setting a new response in the before middleware impacts what happens to the response object AFTER the before middleware has passed.

I may just be too dim to get it, but I can't make any logical sense of it and so any explanation would be much appreciated.

Thanks.

**Comment by odan** [comment]
Usually an ingoing middleware is to check the incoming request object and an outgoing middleware is to change the response (object). So the shown example (ExampleBeforeMiddleware) in the documentation is quite confusing because it is an outgoing middleware. So maybe we should fix the example instead.

**Comment by met68** [comment]
Thanks Daniel, kind of makes sense. So what you're saying is that we shouldn't try and manipulate the response object in the incoming middleware, unless, I guess, we want to send a response directly from the incoming middleware, say in case of an auth or CSRF type incoming middleware.

**Comment by odan** [comment]
Yes, that's it.

**Comment by met68** [comment]
As you suggest, it may be a good idea to change the example in the docs and clarify, that if the response object is altered in the incoming middleware without actually returning a response from it, then changing status codes (and headers? Haven't tested.) after the incoming middleware has no effect.

I will close the issue, as it doesn't look like this is a bug as such.
