### ISSUE TITLE
Question about middleware pre and post.

### ISSUE THREAD

**Issue by Tommuh** [slimphp/Slim#3142]
I am probably not the first to ask this question. I have searched the Internet but could not find a satisfying answer. Hence this issue.

What do I want to achieve:
I would like to execute PHP code before a route is executed and I would like to execute PHP code after a route is executed.

The before is done with middleware. However, I cannot do the after. Each middleware is executed beforehand. Tried with "echo" and so on.

I do not want to edit the request and response.For example, I want to store the request in the database and the response after everything else is done.

How can you do this? Of course I can call that code at the end of each request myself but this seems wrong because middleware exists.
Can someone help me or point me in the right direction?

**Comment by ghost** [comment]
This is achievable with [application-middleware](https://www.slimframework.com/docs/v4/concepts/middleware.html#application-middleware).

Try to change BEFORE and AFTER parts with desired code. Also, you might want to used a class to use dependency injection.

Keep in touch in [discourse.slimframework](https://discourse.slimframework.com/), I think it's a better channel for this sort of things.

**Comment by Tommuh** [comment]
Thank you for your reply. 
Next time I will go to the other forum.

However. 
If I change the "BEFORE" and "AFTER" text in your example isn't that just "text" and concatenation it to the body text?
I want to execute PHP before and after.

**Comment by ghost** [comment]
In the example, the code is changing the content of the response.
But you are not limited to that. You can do wherever you want.
Just write the code for it.

Here is an example:
First middleware to be executed: create a unique identifier for the request;
Last middleware to be executed: attach the request identifier to a custom header.

You can check it here: https://github.com/raffster-dev/slim-middleware-example
Try to play around it.

**Comment by Tommuh** [comment]
Thank you for your example.

But when I do the following:
- echo 'BEFORE' in 'ExampleBeforeMiddleware.php' 
- echo 'AFTER'  in 'ExampleAfterMiddleware.php'
- echo 'MIDDLE' in $app->get('/', function() { .... })

The output is:
BEFORE AFTER MIDDLE

What I expected:
BEFORE MIDDLE AFTER

This is confusing for me.
Sorry for this - I just want to understand what is happening.

**Comment by Tommuh** [comment]
Ah big brian time.
I see what you did.

```
BEFORE
$handler->handle($request); 
AFTER
```

I understand it now. Thank you for your help.

**Comment by ghost** [comment]
Yeah.
There's some points you need attention, as you figured it out.

You can interact before and/or after you handle the request. This is why it the example from docs a new Response is created.

Also, the order you add middleware is very important.

You welcome! Glad you got it working the way you need.
