### ISSUE TITLE
Slim in PHP 8.1: site returns error

### ISSUE THREAD

**Issue by taylorren** [slimphp/Slim#3143]
I have been using Slim PHP framework to provide my API service (https://api.rsywx.com).

Recently, I updated my PHP to 8.1 and when I visited the site, it gives the following error:

```
{
    "statusCode": 500,
    "error": {
        "type": "SERVER_ERROR",
        "description": "ERROR: Return type of App\\Application\\Actions\\ActionPayload::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice on line 67 in file \/home\/tr\/www\/api.rsywx.com\/src\/Application\/Actions\/ActionPayload.php."
    }
}
```

I have not changed anything in my source code, so I guess the problem raises from Slim framework itself.

Any hints to solve this issue?

**Comment by odan** [comment]
At first, I thought it could be a bug, but Slim does not do any JSON encoding etc.

I assume this is a PHP 8.1 deprecation in your code:

See this: https://3v4l.org/Fon9f#v8.1.2
vs.
this: https://3v4l.org/gqeus#v8.1.2

Please try to add `: mixed` as return type in file ActionPayload.php on line 67.

**Comment by l0gicgate** [comment]
This is a `Slim-Skeleton` issue that's been fixed.

See https://github.com/slimphp/Slim-Skeleton/pull/252
