### ISSUE TITLE
HttpException extends RuntimeException

### ISSUE THREAD

**Issue by visavi** [slimphp/Slim#3144]
Hello everyone, I have a question, why not make the HttpException class inherit from RuntimeException
https://github.com/slimphp/Slim/blob/4.x/Slim/Exception/HttpException.php#L20

This is how it is done in the symfony and in other frameworks

The fact is that phpstorm RuntimeException is added to the exceptions by default, more details here
https://blog.jetbrains.com/phpstorm/2018/04/configurable-unchecked-exceptions/

**Comment by nbayramberdiyev** [comment]
Hey @visavi, what benefits does it provide except being useful for PhpStorm users only?

Despite being IDE-specific improvement, I'm happy to submit a PR if you're open to it @l0gicgate, @odan.

**Comment by odan** [comment]
From my side, a 👍 for this change. It is generally a better practice to extend from RuntimeException. The Slim 4 ErrorMiddleware should not be affected.

**Comment by l0gicgate** [comment]
I'm open to making this change. Since it extends `Exception` it shouldn't break anything.
