### ISSUE TITLE
The Slim framework cuts any auth headers.

### ISSUE THREAD

**Issue by Flint-San** [slimphp/Slim#3167]
I use Slim version 4.4.0/4.9.0 with PHP 7.4/PHP 8 on Apache 2.4 with use **.htaccess**

The Slim framework cuts any auth headers. 
For example:
1) After successful authentication through **NTLM**. Slim lost a header **REMOTE_USER**.
2) After successful authentication through **OpenId Connect** with use **mod_auth_openidc** for **Keycloak** . Slim loses the header **REMOTE_USER** and all SERVER variables that have a prefix **OIDC_CLAIM_** and **PHP_AUTH_USER**

It's making the authorization process impossible if I try using these headers in my program.

If I use  auth only with **nikic/fast-route** without Slim then all headers exist.

**Comment by odan** [comment]
This may depend on the PSR-7 implementation. But I'm sure Slim itself does not remove any request headers.  Can you please try to post some code to reproduce this behavior? Please note that there is also a Slim [forum](https://discourse.slimframework.com/).

**Comment by l0gicgate** [comment]
I'm closing this as resolved, please provide a test case isolating this issue if it exists. This is most likely a problem with Nginx or Apache or whatever infrastructure is being used to serve the app.
