### ISSUE TITLE
Unlimited parameters vs. linebreak 

### ISSUE THREAD

**Issue by GonozalIX** [slimphp/Slim#3168]
From the [doc](https://www.slimframework.com/docs/v4/objects/routing.html#route-placeholders):

> For “Unlimited” optional parameters, you can do this:
> ```php 
> $app->get('/news[/{params:.*}]', function ($request, $response, array $args) {
>     // $params is an array of all the optional segments
>    $params = explode('/', $args['params']);
>    // ...   
>    return $response;
>});
>```

If params contains an url encoded linebreak `%0A` the regular expression will not match and lead to a HttpNotFoundException
```
PHP Fatal error: Uncaught Slim\\Exception\\HttpNotFoundException: Not found. in /vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:91
Stack trace:
#0 /vendor/slim/slim/Slim/Routing/RouteRunner.php(72): Slim\\Middleware\\RoutingMiddleware->performRouting()
#1 /vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\\Routing\\RouteRunner->handle()
#2 /vendor/slim/slim/Slim/App.php(215): Slim\\MiddlewareDispatcher->handle()
#3 /vendor/slim/slim/Slim/App.php(199): Slim\\App->handle()
#4 /index.php(16): Slim\\App->run()
#5 {main}
 thrown in /vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php on line 91'
```
All other encoded chars tested so far like spaces `%20` work as intended.

**Comment by odan** [comment]
I have tested it and can confirm your described behavior. But have you tested a "real unlimited" parameter without anything?

This pattern should work:

```php
$app->get('/news[/{params}]', ...
```

`/news/test%0Atest2%20test3`

`
array (
  0 => 'test
test2 test3',
)`

**Comment by GonozalIX** [comment]
Yes, I have tested it as well but both patterns (yours and mine) are actually different. 
Your "real unlimited" parameter indeed is a more limited one because '/' is not included.
While `/news[/{params:.*}]` includes e.g. `/news/foo/bar` the pattern `/news[/{params}]` ends if additional parameters with slashes are added.

**Comment by odan** [comment]
Wouldn't a query string be a better way to pass such complex parameters?

**Comment by GonozalIX** [comment]
This bug report isn't about best practice and tbh I just realized this issue due to some corrupt data during testing. 
So no big deal for me but nevertheless it's a bug.

**Comment by odan** [comment]
Slim uses `nikic/FastRoute` under the hood as a router. There is also this open issue https://github.com/nikic/FastRoute/issues/219 with unescaped values. 

I'm not sure, but these characters are possibly invalid in URL paths as defined in RFC 3986 Section 3.3
and therefore FastRoute does not support it. So my guess is that this is more of a FastRoute related issue. 
Maybe someone knows more?

**Comment by l0gicgate** [comment]
I'm closing this as resolved as this is a limitation with FastRoute. 

If you want to use the Symfony router check out this sample repo I put together:
https://github.com/l0gicgate/slim4-symfony-router-exp
