### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [slimphp/Slim#3171]
Hey there!

I belong to an open source security research community, and a member (@cyberhomeless) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by l0gicgate** [comment]
@JamieSlome thank you for reporting this. We will add something as soon as possible, in the mean time they can email security[at]slimframework.com

**Comment by JamieSlome** [comment]
@l0gicgate - thanks for the response!

I will get those e-mails sent over now. In the meantime, you can view the reports directly here:

https://huntr.dev/bounties/c7fff12a-71b9-4330-8524-7350d85b6222/
https://huntr.dev/bounties/635427f2-0c88-472e-80df-659cb57aea3a/

They are both private and only accessible to maintainers with repository write permissions!

**Comment by l0gicgate** [comment]
@JamieSlome I addressed both bounties. I will close this issue once we add SECURITY.MD

**Comment by JamieSlome** [comment]
@l0gicgate - appreciate your time and contribution here! 👍

**Comment by l0gicgate** [comment]
Closing as SECURITY.MD has been added. Thank you for reporting this @JamieSlome

**Comment by JamieSlome** [comment]
Thanks @l0gicgate!
