### ISSUE TITLE
There are no commit changes in a downloaded project

### ISSUE THREAD

**Issue by solventt** [slimphp/Slim#3174]
Strange thing: here in the repository there are changes added by the `"Add a new PSR-17 factory to Psr17FactoryProvider"` commit.

But when I type `composer require slim/slim` in the downloaded project the specified changes are missing - I have to add them manually.

**Comment by l0gicgate** [comment]
That's because there hasn't been a release yet. I will do a release shortly here for 4.10 and it will be in there. In the mean time you can use 4.x-dev version if you need.

**Comment by l0gicgate** [comment]
@solventt just released 4.10.0, your changes should be in there now:
https://github.com/slimphp/Slim/releases/tag/4.10.0
