### ISSUE TITLE
Route parameter injection

### ISSUE THREAD

**Issue by briannesbitt** [slimphp/Slim#318]
It would be nice if you could inject parameters into the route.  An example for parsing a wildcard route is shown here:

``` php
$parseWildcardToArray = function ($param_name) use ($app) {
   return function ($req, $res, $route) use ($param_name, $app) {

      $values = explode('/', $route->getParams()[$param_name]);
      // inject $values array back into route
   };
};

$app->get('/api/getitems/:items', $parseWildcardToArray('items'), function ($items) use ($app) {
   // access the injected route parameter
})->conditions(['items' => '.+']);
```

In this example having the route middleware inject the new array parameter into the route would be much cleaner then storing it any where else.

**Comment by codeguy** [comment]
I'm working on this now. I assume the value of `$param_name` would be an array, correct? A simple `setParam($name, $value)` setter method should be sufficient.

**Comment by codeguy** [comment]
Index order is going to be an issue. Will tweak this afternoon.

**Comment by codeguy** [comment]
Some additional proposed code. This allows you to completely replace the given params, or to set a single param by index. If you choose to set or get a param by index, a param must exist at that index else an exception will be thrown.

```
Route {
    protected $params = array();

    public function getParams () {
        return $this->params;
    }

    public function setParams ( $params ) {
        $this->params = $params;
    }

    public function getParam ( $index ) {
        if ( !isset($this->params[$index]) ) {
            throw new InvalidArgumentException('Route parameter does not exist at specified index');
        }
        retun $this->params[$index];
    }

    public function setParam ( $index, $value ) {
        if ( !isset($this->params[$index]) ) {
            throw new InvalidArgumentException('Route parameter does not exist at specified index');
        }
        $this->params[$index] = $value;
    }
}
```

Because Route parameters are tightly coupled to the Route pattern, I'm not too concerned about not providing an interface to add or remove params. I'm only concerned about changing values of existing params.

**Comment by briannesbitt** [comment]
Thumbs up!
