### ISSUE TITLE
Middleware $app->redirect()

### ISSUE THREAD

**Issue by pablofierro** [slimphp/Slim#319]
Hello, I'm using this middleware class to create an authentication system for my app, I've narrowed it down to whats causing the issue:

``` php
<?php

class Auth_Middleware extends Slim_Middleware {

  public function call() {

    $app = $this->app;
    $req = $app->request();
    $res = $app->response();
    //redirects to root if given condition
    if(current_route != "login") {
      $app->redirect('/');
    }
  }
}

?>

```

This works great on my local enviroment and on another web server, but using the mediatemple (gs) shared hosting this doesn't work. So I started investigation and it turns out the halt() function is causing the issue as it is firing an $app->stop() function.

When you fire a halt() function directly inside the middleware the same error comes out, however when calling redirect() this is not the case.

In theory, calling redirect() from the middleware or any other place calls halt() right ? And in theory it should raise an error as if you call halt() directly from the middleware, but in both my local and another web server this is not happening.

To wrap it up:

redirect() should raise an error when called from a middleware but doesn't on some servers ?

Can you reproduce the error ?

Cheers

**Comment by codeguy** [comment]
The redirect method is designed to run only in application route callbacks... not from middleware. I'll need to refactor some code before this will be possible. Middleware is meant to act on the raw request and response objects.

My recommendation is to manipulate the Response object like so:

```
$res = $app->response();
$app->status(301);
$app['Location'] = '/foo';
```

If you do redirect from middleware, you should not call the downstream middleware.

**Comment by pablofierro** [comment]
Thanks.

I ended up using:

```
$res->redirect('/foo');
```

Is this correct ? or should I be defining the header manually ?

**Comment by codeguy** [comment]
That's fine, too. It's a helper method on the Response object that does the same thing (I forgot to mention it above). But the point being that many of the Slim instance's helper methods that affect application flow (e.g. `halt`, `stop`, `redirect`) are intended only for the primary Slim application's route callbacks — not middleware. Middleware is an opportunity to inspect and tweak the Request and Response objects before and after the application is called.
