### ISSUE TITLE
Uncaught InvalidArgumentException from guzzlehttp/psr7

### ISSUE THREAD

**Issue by afady** [slimphp/Slim#3190]
**Summary:**
Using a fresh Slim & guzzlehttp/psr7 install and passing in an Authorization header with invalid bearer token causes an `Uncaught InvalidArgumentException`.

**Expectation:**
I expected the InvalidArugmentException to be caught by the custom error handler I configured.

**Steps to reproduce:**
Start a new project with this `composer.json`:
```
{
    "name": "ffarid/slim-test",
    "require": {
        "slim/slim": "^4.10",
        "slim/http": "^1.2",
        "guzzlehttp/psr7": "^2.2"
    }
}
```
and this `public/index.php`:
```php
<?php
use Psr\Http\Message\ServerRequestInterface;
use Psr\Log\LoggerInterface;
use Slim\Factory\AppFactory;
use Slim\Psr7\Response;

require __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

// Add Routing Middleware
$app->addRoutingMiddleware();

// Define Custom Error Handler
$customErrorHandler = function (
	ServerRequestInterface $request,
	Throwable $exception,
	bool $displayErrorDetails,
	bool $logErrors,
	bool $logErrorDetails,
	?LoggerInterface $logger = null
) use ($app) {
	$payload = ['error' => $exception->getMessage()];

	$response = $app->getResponseFactory()->createResponse();
	$response->getBody()->write(
		json_encode($payload, JSON_UNESCAPED_UNICODE)
	);

	return $response;
};

// Add Error Middleware
$errorMiddleware = $app->addErrorMiddleware(true, true, true);
$errorMiddleware->setDefaultErrorHandler($customErrorHandler);

$app->run();
```

Run `composer install`

Start a local server: `php -S localhost:8000 -t public`

Send a cURL request with an invalid Authorization header:
`curl "localhost:8000"  -X GET -H "Authorization: Bearer ����V�������5�{ԉ����p��@g�s"`
curl "localhost:8000"  -X GET -H "Authorization: Bearer ����V�������5�{ԉ����p��@g�s"
> note: it looks like GitHub is converting the string to 'valid' characters - I'm not sure how to share the string that was originally used.

Error thrown:
```
curl "localhost:8000" \                                                                                                                                                                                         
  -X GET \
  -H "Authorization: Bearer ��^P�^F�V�^W��^A����5^R�{ԉ����p��^D@g�s^O"
<br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: &quot;Bearer ����V�������5�{ԉ����p��@g�s&quot; is not valid header value in /Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/MessageTrait.php:263
Stack trace:
#0 /Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/MessageTrait.php(209): GuzzleHttp\Psr7\Request-&gt;assertValue('Bearer \xEF\xBF\xBD\xEF\xBF\xBD\x10\xEF...')
#1 [internal function]: GuzzleHttp\Psr7\Request-&gt;GuzzleHttp\Psr7\{closure}('Bearer \xEF\xBF\xBD\xEF\xBF\xBD\x10\xEF...')
#2 /Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/MessageTrait.php(212): array_map(Object(Closure), Array)
#3 /Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/MessageTrait.php(174): GuzzleHttp\Psr7\Request-&gt;trimAndValidateHeaderValues(Array)
#4 /Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/MessageTrait.php(154): GuzzleHttp\Psr7\Request-&gt;normalizeHeaderValue('Bearer \xEF\xBF\xBD\xEF\xBF\xBD\x10\xEF...')
#5 /Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/Request.php(49): GuzzleHttp\Psr7\Request-&gt;setHeaders(Array)
#6 /Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/ServerRequest.php(77): GuzzleHttp\Psr7\Request-&gt;__construct('GET', Object(GuzzleHttp\Psr7\Uri), Array, Object(GuzzleHttp\Psr7\CachingStream), '1.1')
#7 /Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/ServerRequest.php(174): GuzzleHttp\Psr7\ServerRequest-&gt;__construct('GET', Object(GuzzleHttp\Psr7\Uri), Array, Object(GuzzleHttp\Psr7\CachingStream), '1.1', Array)
#8 /Users/ffarid/code/slim-test/vendor/slim/slim/Slim/Factory/Psr17/ServerRequestCreator.php(46): GuzzleHttp\Psr7\ServerRequest::fromGlobals()
#9 /Users/ffarid/code/slim-test/vendor/slim/slim/Slim/Factory/Psr17/SlimHttpServerRequestCreator.php(48): Slim\Factory\Psr17\ServerRequestCreator-&gt;createServerRequestFromGlobals()
#10 /Users/ffarid/code/slim-test/vendor/slim/slim/Slim/App.php(196): Slim\Factory\Psr17\SlimHttpServerRequestCreator-&gt;createServerRequestFromGlobals()
#11 /Users/ffarid/code/slim-test/public/index.php(37): Slim\App-&gt;run()
#12 {main}
  thrown in <b>/Users/ffarid/code/slim-test/vendor/guzzlehttp/psr7/src/MessageTrait.php</b> on line <b>263</b><br />
```

Is this a configuration issue or a bug?

**Comment by odan** [comment]
I guess this is not a bug. It looks like a valid Exception, because the header value contains invalid characters.

> Fatal error</b>:  Uncaught InvalidArgumentException: Bearer XXX is not valid header value in /vendor/guzzlehttp/psr7/src/MessageTrait.php:263

Make sure that the header value fits into this regex:

https://github.com/guzzle/psr7/blob/master/src/MessageTrait.php#L261

**Comment by afady** [comment]
Hey @odan thank you for the reply. I understand that the Exception is valid, but I expected Slim to catch the Exception: https://www.slimframework.com/docs/v4/middleware/error-handling.html
>Each Slim Framework application has an error handler that receives all uncaught PHP exceptions.

Are you suggesting that we should first validate `$_SERVER['HTTP_AUTHORIZATION']` before allowing Slim to run?

**Comment by odan** [comment]
Ah yes, this is a known behavior, because the Slim `$app->run();` method tries to create (and parse) a Request object from the global variables. This happens before the Slim runs through the middleware stack. So the ErrorMiddleware is not able to catch and handle such a specific error.

We have talked about this issue in the Slim forum, see here: https://discourse.slimframework.com/t/handle-invalidargumentexception-thrown-by-requestfactory/3677/3

Workaround:

```php
<?php

// bootstrap code ...

try {
    $app->run();
} catch (Throwable $exception) {
    http_response_code(400);
    echo sprintf('Bad Request: %s', $exception->getMessage());
}
```

**Comment by afady** [comment]
@odan we came to a similar workaround internally. I'll go ahead and close this issue since its a known behavior. Thank you.
