### ISSUE TITLE
Warning in Request file

### ISSUE THREAD

**Issue by cjean-fr** [slimphp/Slim#32]
When I test slim framework in my environment (PHP 5.3.3, display_errors at true and error_reporting at E_ALL), I've this warning in index file :

<code>
Warning: preg_replace() [function.preg-replace]: No ending delimiter '@' found in path\slim\Request.php on line 194
</code>

**Comment by codeguy** [comment]
I've just pushed a commit to master which should resolve this issue. Pull the latest code and let me know if the issue is fixed. I was not calling preg_quote in slim/Request.php on line 204.

**Comment by codeguy** [comment]
Closing this out. Re-open if you still have problems with this.
