### ISSUE TITLE
3.12.3 doesn't contain the fix for libxml_disable_entity_loader deprecated 

### ISSUE THREAD

**Issue by andybutlermf** [slimphp/Slim#3201]
tag: https://github.com/slimphp/Slim/releases/tag/3.12.3
fix: https://github.com/slimphp/Slim/commit/ce3cb65a06325fc9fe3d0223f2ae23113a767304

can we have a 3.12.4 with the fix bundled

**Comment by l0gicgate** [comment]
See release https://github.com/slimphp/Slim/releases/tag/3.12.4
