### ISSUE TITLE
Variable App not available in routes

### ISSUE THREAD

**Issue by EzequielGv83** [slimphp/Slim#3202]
I just need some tips on to fix this, i've read a bit of the documentation and downloaded some demos and there is some problem in the routes (i'm just troubleshooting to move to another server and testing on my dev. env.)
 
Undefined variable: app in C:\wamp64\www\portal\app\routes.php on line 12

**Routes.php**
`$this->group('/access/{id}', function() use ($app) {`

I manage to make it run using the routes that don't use the app var.

I have a virtual host set and mod rewrite on Apache (Wampp server)

**Index.php**
`$app = new Slim\App(["settings" => $config]);`

`$container = $app->getContainer();`

`$container['view'] = new \Slim\Views\PhpRenderer("resources/views/");`

`require 'app/routes.php';`

`$app->run();`

If i do a var_dump on $app in the routes files, i get the dependecy container.

`object(Slim\App)[3]`

Any tips?

**Comment by odan** [comment]
Slim 3 is no longer fully supported. Why don't you try Slim 4 instead?
Note that we also have a special Discourse [forum](https://discourse.slimframework.com/) for questions like this.

**Comment by EzequielGv83** [comment]
Thanks for the answer, but i just need to deploy this application (i'm not the original developer).

I guess something is wrong, i did the following steps:
`New Folder`
`Composer require slim/slim:3.7`
`Composer require slim/php-view`
`Edit composer JSON with autoload psr-4`

**composer.json**
`
{
    "require": {
        "slim/slim": "3.7",
        "slim/php-view": "^3.1"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    }
}`

`Move the old app files to new slim3.7 instalation folder`
`set virtualhost`

**index.php** 
`require __DIR__ . '/vendor/autoload.php;`
`require __DIR__ . '/config/constants.php;`
`require __DIR__ . '/config/config.php;`
`$app = new Slim\App(["settings" => $config]);`

`$container = $app->getContainer();`
`require 'app/routes.php';`

`$app->run();`

**app/routes.php**

`$app->get('/', 'App\Home\Home:index');`

`$this->group('/news/{id}', function() use ($app) {`
`        $this->get('', 'App\Home\News\News:index');`

**Comment by wnnawalaniec** [comment]
Can you copy/paste whole `routes.php` file? I can see you are using `$this` so you must be inside some object scope, and `$app` variable is in global scope so it cannot be reached directly. But I'm just guessing.

**Comment by l0gicgate** [comment]
Closing this as stale
