### ISSUE TITLE
Smarty View support for Slim 4

### ISSUE THREAD

**Issue by khairdi** [slimphp/Slim#3203]
Please release Smarty View support for Slim 4

**Comment by odan** [comment]
Not sure what you mean. Have you tried this package for Smarty and Slim 4?

* https://github.com/mathmarques/Smarty-View

**Comment by odan** [comment]
This question is not directly related to Slim. The Slim 4 issue for the [Smarty-View](https://github.com/mathmarques/Smarty-View) package can be found [here](https://github.com/mathmarques/Smarty-View/issues/8).
