### ISSUE TITLE
Why no config  components?   Like .env read and wrie .

### ISSUE THREAD

**Issue by w3yyb** [slimphp/Slim#3222]
Why no config  components?   Like .env read and wrie .

I think this is a  basic feature, I hope It will be add.

**Comment by w3yyb** [comment]
Like  laravel 's  illuminate/config.

**Comment by odan** [comment]
Slim is a micro-framework. The advantage is that everyone can install their own packages, according to need and preference. For this reason, Slim does not require unnecessary packages.

**Comment by l0gicgate** [comment]
@w3yyb as @odan said, we are not a kitchen sink type framework. Slim core is just a routing library, environment loading and configuration is a different set of concerns that other packages do very well and there's no reason for us to reinvent that wheel.
