### ISSUE TITLE
Problem with withHeader method in Message class

### ISSUE THREAD

**Issue by arvindpdmn** [slimphp/Slim#3224]
There's a check in this method `$this->body instanceof NonBufferedBody`. This check doesn't pass since body is of type `Stream` in my app. As a result, cookie can't be cleared.

The strange thing is cookie can be set but not deleted. Don't really understand what's happening.

Versions used: slim/slim 4.10.0, slim/psr7 1.5, slim/twig-view 3.3.0

**Comment by arvindpdmn** [comment]
When setting the cookie, I use this code and it works (redirecting after a login):
```
$response = $response->withHeader('Set-Cookie', $cookie);
$response->withHeader('Location', $redirectUrl)->withStatus(303);
```

When clearing the cookie (simulating a hack attempt via stolen or expired cookie), a page is served with the following code:
```
$response = $response->withHeader('Set-Cookie', $cookie);
return Twig::fromRequest($request)->render($response, 'myTempate.twig', $params);
```

Clearing the cookie doesn't work. However, I can clear the cookie via a 303 redirect!

**Comment by l0gicgate** [comment]
@arvindpdmn the way to clear a cookie via the `Set-Cookie` header is to re-issue the original cookie with an expired date

[This thread might help you](https://stackoverflow.com/questions/5285940/correct-way-to-delete-cookies-server-side)

**Comment by arvindpdmn** [comment]
I have done this but it doesn't work. The problem is inside `Message::withHeader()`. Something's not working there. I am trying to debug the line `$clone->headers->setHeader($name, $value)`

**Comment by arvindpdmn** [comment]
Problem solved. It was a bug in one of my middleware where `$response = new Response();` was used. This was therefore ignoring cookies set earlier.
