### ISSUE TITLE
Is is possible to automatically save error log?

### ISSUE THREAD

**Issue by laikee99** [slimphp/Slim#3230]
I don't know how to save error log like laravel, Laravel just automatically saved everything to "runtime/log" but how could Slim to achieve the same thing?
Thanks

**Comment by laikee99** [comment]
I could not get the error from `errorHandler` nor `phpErrorHandler`, I just got 500 error, I really want to know how could I get all these messages

**Comment by odan** [comment]
You can supply a logger that conforms to the [PSR-3 standard](https://www.php-fig.org/psr/psr-3/), such as one from the popular [Monolog](https://github.com/Seldaek/monolog/) package.

See: [Slim 4 Error Logging](https://www.slimframework.com/docs/v4/middleware/error-handling.html#error-logging)

**Comment by l0gicgate** [comment]
Closing this as resolved
