### ISSUE TITLE
PHP 8.1 deprecated warnings for Slim 3.x

### ISSUE THREAD

**Issue by Datta-Telukunta** [slimphp/Slim#3234]
`Deprecated: Return type of Slim\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/slim/slim/Slim/Collection.php on line 112

Deprecated: Return type of Slim\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/slim/slim/Slim/Collection.php on line 124

Deprecated: Return type of Slim\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/slim/slim/Slim/Collection.php on line 135

Deprecated: Return type of Slim\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/slim/slim/Slim/Collection.php on line 145

Deprecated: Return type of Slim\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/slim/slim/Slim/Collection.php on line 155

Deprecated: Return type of Slim\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/slim/slim/Slim/Collection.php on line 165`

**Comment by l0gicgate** [comment]
Slim 3.x branch is in security fixes only mode. There will be no new releases. If you want PHP 8 support you must migrate to Slim 4.
