### ISSUE TITLE
Is 4.11 released?

### ISSUE THREAD

**Issue by rafrafek** [slimphp/Slim#3244]
Hi!

Is 4.11 released?

I can see there is 4.11 in GitHub releases:

https://github.com/slimphp/Slim/releases/tag/4.11.0

But there is no 4.11 in CHANGELOG.md:

https://github.com/slimphp/Slim/blob/4.x/CHANGELOG.md

And there is no news for 4.11 on the slim framework website:

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/23004737/213216601-91bb2c22-762d-4a27-b534-6bf839f21375.png">

**Comment by dfranco** [comment]
Actually, I've have the same questions as above, any feedback from the maintainers ?
