### ISSUE TITLE
Add I18n support

### ISSUE THREAD

**Issue by williamwa** [slimphp/Slim#325]
Hi,

I add a I18n Middleware, pls have a look here and give me your thoughts:

https://github.com/lancehub/Slim/blob/master/Slim/Middleware/I18n.php

and it works this way:

```
$app->add(new Slim_Middleware_I18n());

//GET route
$app->get('/', function () {
    echo _('Hello');
});
```

and with mo file this way:

```
./langs/zh_CN/LC_MESSAGES/default.mo
```

**Comment by williamwa** [comment]
and user can visit the site like this way:

http://site/slim-url?lang=zh_CN to see its Chinese language interface

thanks!

**Comment by miraage** [comment]
Imho this feature is not nessesary. I think you will be asked for moving your issue to Slim-Extras.

**Comment by codeguy** [comment]
This is a good idea if your Slim app requires localization. But this is definitely not something that's going to be in the core. It's a great candidate for the Slim-Extras repository, as @miraage said. Please submit a pull request to Slim-Extras and we'll review it.
