### ISSUE TITLE
Support for authorization

### ISSUE THREAD

**Issue by peters** [slimphp/Slim#326]
This framework is great and since i've used express framework (same principle) i'm inclined to ask you guys to introduce some new and awesome concepts that will make development even more streamlined.

You can read up on the idea here:
https://github.com/LearnBoost/socket.io/wiki/Authorizing

The idea is simple, all requests is verified by calling $this->authorization
and the callback function determines what should happen to the request,
either continue or throw.

```
require 'Slim/Slim.php';
$app = new Slim();
$app->authorization(function() use ($app) { 
     // by returning either true or false here determines
     // if the request should result in an error.
     return true_or_false;
});
$app->get('/hello/:name', function ($name) {
    echo "Hello, $name!";
});
$app->run()
```

**Comment by peters** [comment]
The reason for this is very simple. Since most modern api's today use a X-Auth-Key header in every request, it is very simple to retrieve information about the permissions that specific key has to a given route.

**Comment by peters** [comment]
You could then do the following also:

```
$app->get('/hello/:name', function ($name) {
    echo "Hello, $name!";
})->permission($flags) {
    // allowed to access?
    if($flags->admin & $flags->bla) return true;
    // throw a default json document error
    throw $Document->Json->AuthError();
});
```

**Comment by Baachi** [comment]
I like this idea, but i'm not convinced from the implementation.

@peters Your example will throw a `PHP Parse Error` ;)

**Comment by peters** [comment]
Hehe, little quick on the trigger there. I'm implementing this is a middleware component, and i'll create a pull request with tests.. then we could go from there? :)

**Comment by Baachi** [comment]
Sounds good! :)

**Comment by miraage** [comment]
Don't forget about:

> Slim is purposefully small and simple with a very slim codebase. Slim encourages configuration and customization over convention.

Via http://www.slimframework.com/ask

**Comment by peters** [comment]
The implementation so far is +/- 100 lines, so the changes will introduce a small footprint.

**Comment by peters** [comment]
Commits are available here:
https://github.com/codeguy/Slim/pull/328

**Comment by codeguy** [comment]
This will not be added to the core. It may be a viable candidate for Slim-Extras. Please submit a PR to Slim-Extras with your proposed auth middleware.

**Comment by peters** [comment]
Ok :)
