### ISSUE TITLE
Better URI template support

### ISSUE THREAD

**Issue by blablabla1234678** [slimphp/Slim#3261]
According to the URI template RFC https://www.rfc-editor.org/rfc/rfc6570 the query string should be part of the template. As far as I understand based on the documentation currently it isn't part of it. In my current case this feature would be very useful, because I have a multilanguage site and I translate the URI templates too including query parameters. I wonder if this could be supported somehow, so others in the future won't have to need to write a separate query parameter translator.

**Comment by odan** [comment]
Are you trying to define a route with query parameters, such as `/users/{type}/?name={name}` ?

In Slim 4 Framework, the URI template is used to define route placeholders that match dynamic segments of a URL. While the RFC 6570 URI template syntax allows for the inclusion of query parameters, Slim 4 does not currently support this feature directly.

However, you can still achieve your goal of translating URI templates with query parameters by using custom middleware. The middleware can intercept the request, translate the URI with query parameters based on the current language, and modify the request to the matching route.

Please note that we have a [forum](https://discourse.slimframework.com/) to discuss questions like this.

**Comment by blablabla1234678** [comment]
@odan Sure it is not implemented, this is a feature request. I can solve it thanks. :-)
