### ISSUE TITLE
Error responding with stream

### ISSUE THREAD

**Issue by alissonrodrigo** [slimphp/Slim#3268]
Today I came across an error that was not happening. When requesting a URI that returns an image via stream, the file comes "broken".

    //get photo
    $this->get('/foto/{id}/{width}', function ($request, $response, $arqs) {
        $id = $arqs["id"];
        $width = $arqs["width"];
        $Usuario = new UsuarioController;
        $img = $Usuario->foto($id, $width);
        if (file_exists(($img))) {
            if ($fh = fopen($img, 'r+')) {
                $stream = new \Slim\Http\Stream($fh);
                //$stream = fpassthru($fh);
                return $response->withBody($stream)
                    ->withHeader("file", $img)
                    ->withHeader("Content-Type", mime_content_type($img))
                    ->withHeader("Content-Length", filesize($img));
            }
        }
    });

is doing all the checks. and if the file exists then return. **but**
![Screenshot_1](https://github.com/slimphp/Slim/assets/8572209/ab3dddb8-f94f-4e82-86ff-12ed56474298)

can someone help me?

**Comment by odan** [comment]
You may check the value of the `Content-Length` response header. I guess that `filesize($img)` does not return the correct length. Note that there is a Slim [forum](https://discourse.slimframework.com/) for this kind of questions.

**Comment by l0gicgate** [comment]
As @odan commented, you're most likely not passing the correct content-length and it truncates the payload. Closing this.
