### ISSUE TITLE
version of `App::VERSION`

### ISSUE THREAD

**Issue by hashimoto-AJ** [slimphp/Slim#3272]
I installed [3.12.4](https://github.com/slimphp/Slim/tree/3.x) by composer, but display of `App::VERSION` is **3.12.3**

~~~
 $ composer show -i
 :
 slim/slim                          3.12.4  Slim is a PHP micro framework that helps you quickly write simple yet po...
 :
~~~

~~~
use Slim\App;
 :
echo App::VERSION
 :
~~~

> 3.14.3

![slim3 12 4](https://github.com/slimphp/Slim/assets/74279799/11fb09d5-31bc-4ebf-b717-d675d307b8ac)

**Comment by l0gicgate** [comment]
Release https://github.com/slimphp/Slim/releases/tag/3.12.5
