### ISSUE TITLE
`App::VERSION` not updated

### ISSUE THREAD

**Issue by stramunin** [slimphp/Slim#3273]
For some reason when posting the `4.11.0` tag someone forgot to change also the version.

https://github.com/slimphp/Slim/blob/b0f4ca393ea037be9ac7292ba7d0a34d18bac0c7/Slim/App.php#L41

What is this constant for? Didn't find usage in this repository. 
Maybe it should be removed and there will be no such problems in the future.

**Comment by l0gicgate** [comment]
Fixed via latest release:
https://github.com/slimphp/Slim/releases/tag/4.12.0
