### ISSUE TITLE
Add a section to the routing docs callbacks section mentioning first class callable syntax

### ISSUE THREAD

**Issue by abdelfattahradwan** [slimphp/Slim#3282]
I suggest adding a new section in the routing documentation highlighting the benefits of using "[First Class Callable Syntax](https://www.php.net/manual/en/functions.first_class_callable_syntax.php)" for route callbacks instead of traditional strings or arrays. This change can improve the safety and maintainability of code and is supported by static analysis tools.

**Comment by odan** [comment]
Can you please add more details? I guess callbacks are already documented here: [Route Callbacks](https://www.slimframework.com/docs/v4/objects/routing.html#route-callbacks)

Do you mean the Short Closure or "Arrow Functions" introduced in PHP 7.4?
Short closures can only have one expression; that one expression may be 
spread over multiple lines for formatting, but it must always be one expression.
I'm not sure if this works in Slim, because a route callback must return a response object.

So this would give an error:

```php
$app->get('/hello/{name}', fn ($request, $response, array $args) => $response->getBody()->write("Hello, {$args['name']}"));
```

The error:

```
Return value must be of type Psr\\Http\\Message\\ResponseInterface, int returned","code":0
```

Do you have a working and practical example?

I would like to suggest that you create a PR (with a working example) for this in the [Slim website](https://github.com/slimphp/Slim-Website/issues) repository.

See:  [routing.md](https://github.com/slimphp/Slim-Website/blob/gh-pages/docs/v4/objects/routing.md#closure-binding)

**Comment by abdelfattahradwan** [comment]
@odan have you checked the official PHP manual link I provided above? It should explain what I mean.

**Comment by odan** [comment]
Yes, I have checked your link. That's why I wrote my answer. See above.

**Comment by abdelfattahradwan** [comment]
@odan the page I linked clearly has nothing to do with what you said above. It talks about the new first-class callable syntax. Some of the examples on the page:
```php
<?php
class Foo {
   public function method() {}
   public static function staticmethod() {}
   public function __invoke() {}
}

$obj = new Foo();
$classStr = 'Foo';
$methodStr = 'method';
$staticmethodStr = 'staticmethod';

$f1 = strlen(...);
$f2 = $obj(...);  // invokable object
$f3 = $obj->method(...);
$f4 = $obj->$methodStr(...);
$f5 = Foo::staticmethod(...);
$f6 = $classStr::$staticmethodStr(...);

// traditional callable using string, array
$f7 = 'strlen'(...);
$f8 = [$obj, 'method'](...);
$f9 = [Foo::class, 'staticmethod'](...);
?>
```
The above is what I am talking about.

**Comment by odan** [comment]
Did you mean the following route syntax?

```php
$app->get('/user', MyUserAction::class);
```

If yes, then I fully agree with you, because this is my preferred way to define routes. The docs actually don't highlight the benefits of this.

**Comment by abdelfattahradwan** [comment]
@odan here is an example of what I am talking about
```php
<?php

// index.php

$app->$group('/users', new UsersController());
```
```php
<?php

// UsersController.php

class UsersController
{
	public function __invoke(RouteProxyCollector $routeProxyCollector): void
	{
		$routeProxyCollector->post('', self::createUser(...));
		$routeProxyCollector->get('', self::getUsers(...));
		$routeProxyCollector->get('/{id}', self::getUser(...));
		$routeProxyCollector->put('/{id}', self::updateUser(...));
		$routeProxyCollector->delete('/{id}', self::deleteUser(...));
	}

	private static function createUser(ServerRequestInterface $request, ResponseInterface $response): ResponseInterface
	{
		// ...
	}

	private static function getUsers(ServerRequestInterface $request, ResponseInterface $response): ResponseInterface
	{
		// ...
	}

	private static function getUser(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
	{
		// ...
	}

	private static function updateUser(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
	{
		// ...
	}

	private static function deleteUser(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
	{
		// ...
	}
}
```
See the `self::methodName(...)` syntax? That is called first-class callable syntax. It allows the creation of closures from callables.

**Comment by odan** [comment]
Thank you for the example.
Have you actually tried this in a real application?
I ask because it doesn't work because PHP doesn't support static closures.

```
Cannot bind an instance to a static closure in \vendor\slim\slim\Slim\CallableResolver.php on line 171
```

**Comment by abdelfattahradwan** [comment]
@odan yes, I did, and it works. I suggest you try it for yourself as well if you would like to confirm.

**Comment by odan** [comment]
I have just tried it with Slim 4 and PHP 8.2, and it gives the following error "Cannot bind an instance to a static closure"

This is not supported, see [here](https://www.slimframework.com/docs/v4/objects/routing.html#closure-binding) 

![image](https://github.com/slimphp/Slim/assets/781074/4e1bbdea-3b6d-40cb-840f-269dc0ccb61b)

**Comment by abdelfattahradwan** [comment]
@odan I am sorry, but I doubt you did. I ***just*** tested the following code using Slim 4.12 and PHP 8.2.8, and it works without throwing any errors.
```php
class UserController
{
    private static function getUser(ServerRequestInterface $request, ResponseInterface $response): ResponseInterface
    {
        $response->getBody()->write(json_encode(['id' => 1, 'name' => 'John Doe']));
        return $response->withStatus(200)->withHeader('Content-Type', 'application/json');
    }

    public function __invoke(\Slim\Routing\RouteCollectorProxy $routeProxyCollector): void
    {
        $routeProxyCollector->get('', self::getUser(...));
    }
}

$app->group('/users', new UserController());
```
Can you show me the code that is throwing the error?

**Comment by odan** [comment]
I tested it again with the same result. If you don't trust me, then ask other people. I will not give you any more feedback.

![image](https://github.com/slimphp/Slim/assets/781074/c4e1182d-f3a9-4ec5-b7af-bce5ba79369e)

**Comment by abdelfattahradwan** [comment]
I said I doubt it because you didn't provide the code you used for testing.

I have tested the code I provided above, and it worked, multiple times.

Thanks for your feedback. I will await further responses from others 👍

**Comment by abdelfattahradwan** [comment]
@l0gicgate I think the documentation is outdated in regards to static closures support. I checked the entirety of the `CallableResolver.php` and couldn't find any code that throws an error if a static closure is used.

**Comment by l0gicgate** [comment]
@Abdelfattah-Radwan first of all, your example is wrong.

If you did not instantiate your app with a container, the callable resolver will not try to bind a container to the callables since there isn't one to bind.

But use this example `index.php` and you will see that it absolutely throws with static functions.

```php
<?php

use DI\ContainerBuilder;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;
use Slim\Routing\RouteCollectorProxy;

require __DIR__ . '/../vendor/autoload.php';

$containerBuilder = new ContainerBuilder();
$container = $containerBuilder->build();

$app = AppFactory::create(null, $container);

$handler = static function (Request $request, Response $response): Response
{
    $response->getBody()->write(json_encode(['id' => 1, 'name' => 'John Doe']));
    return $response->withStatus(200)->withHeader('Content-Type', 'application/json');
};

$app->group('/users', function (RouteCollectorProxy $group) use ($handler) {
    $group->get('', $handler);
});

$app->run();
```

This throws when you run it:
```
Warning: Cannot bind an instance to a static closure in /var/www/vendor/slim/slim/Slim/CallableResolver.php on line 171

Fatal error: Uncaught TypeError: Slim\CallableResolver::bindToContainer(): Return value must be of type callable, null returned in /var/www/vendor/slim/slim/Slim/CallableResolver.php:173 Stack trace: #0 /var/www/vendor/slim/slim/Slim/CallableResolver.php(83): Slim\CallableResolver->bindToContainer(NULL) #1 /var/www/vendor/slim/slim/Slim/CallableResolver.php(63): Slim\CallableResolver->resolveByPredicate(Object(Closure), Array, 'handle') #2 /var/www/vendor/slim/slim/Slim/Routing/Route.php(340): Slim\CallableResolver->resolveRoute(Object(Closure)) #3 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(Slim\Psr7\Request)) #4 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #5 /var/www/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #6 /var/www/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(Slim\Psr7\Request)) #7 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\RouteRunner->handle(Object(Slim\Psr7\Request)) #8 /var/www/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request)) #9 /var/www/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(Slim\Psr7\Request)) #10 /var/www/public/index.php(30): Slim\App->run() #11 {main} thrown in /var/www/vendor/slim/slim/Slim/CallableResolver.php on line 173
```

I'm closing this as resolved.

**Comment by abdelfattahradwan** [comment]
@l0gicgate I wasn't using containers, yes. I was following the first example [here](https://www.slimframework.com/docs/v4/objects/application.html), though.
