### ISSUE TITLE
middleware precedence is not working

### ISSUE THREAD

**Issue by alshukri9** [slimphp/Slim#3283]
i have a route that has two middleware

![anlnfd](https://github.com/slimphp/Slim/assets/129284063/d72d0322-1144-4720-b959-5d0a16042872)

and in the docs there is a section that talks about the order the middlewares will be executed

![Screenshot 2023-08-22 at 12-36-25 Middleware](https://github.com/slimphp/Slim/assets/129284063/0046e33b-cd8b-4136-a530-aee3a26022bc)

but when i run the app i get this 

![Screenshot 2023-08-22 at 12-45-34 Screenshot](https://github.com/slimphp/Slim/assets/129284063/cbc24aa5-97da-415e-84a6-00f784dd3b5a)

ok that is the problem it's a simple fix for me but this happens also in the $app->group() method i have to make a route out of the group method to change the order of middleware

**Comment by odan** [comment]
I have tried to reproduce this behavior. What I can say is that the "order of execution" of the middleware is correct.

There are two types of middlewares. Incoming and outgoing. When you invoke the handlers `handle` method to get the response for further manipulation, the order is the opposite. This may sounds strange, but it is the correct behavior.

 ```php
// Incoming request logic (LIFO)
// ...

$response = $handler->handle($request);`

// Outgoing response logic (FIFO)
// ...

return $response
```

**Comment by odan** [comment]
Can we close this issue?
