### ISSUE TITLE
Nginx subdirectory

### ISSUE THREAD

**Issue by Vic-M** [slimphp/Slim#3284]
I'm trying to run slim in a subdirectory but unfortunately slim doesn't really like not being at the document root. I have an application at /apps/project and slim at /apps/project/php/public/index.php, with the following nginx conf:
```
    server {
        listen       443 ssl http2 default_server;
        listen       [::]:443 ssl http2 default_server;
        server_name  _;
        root         /apps/project;

        index index.php index.html index.htm;
        
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_intercept_errors on;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_pass   php-fpm;
        }

        #main application
        location = / {
            ....
        }

        #slim application
        location /slim {
            try_files $uri /php/public/index.php$is_args$args;
        }
    }
```

When I call https://localhost/slim/someApi, slim runs but the uri path it sees is /slim/someApi. Is there a way for slim to route as if it were /someApi without adding /slim/ to all the route paths?

**Comment by odan** [comment]
You may need to set the [base path](https://www.slimframework.com/docs/v4/start/web-servers.html#run-from-a-sub-directory).

```php
$app->setBasePath('/slim/someApi');
```

**Comment by Vic-M** [comment]
Setting the base path works:
```
$app->setBasePath("/slim");
``` 
Unfortunately, the path needs to be hardcoded or configuration needs to be added to get the base path. I'm guessing there's no pure nginx solution?
