### ISSUE TITLE
Bump slim 2 to 3 with BC

### ISSUE THREAD

**Issue by eerison** [slimphp/Slim#3286]
Hello :)

Is there any lib, Middleware, bridge or something like that to make `slim 2` and `slim 3` works with the same code base?

Atm I'm facing the issue to bump to slim 3 without do a huge change.

I know that slim 2 is not maintained anymore,  but I would like to see if someone faced thus same issue before,  and how did you proceed. 

I really appreciate some help or suggestion

**Comment by odan** [comment]
Hi @eerison As far as I know, there is no specific tool or package that helps with this. If you have specific questions about migration, you could contact the [Slim forum](https://discourse.slimframework.com/).

**Comment by eerison** [comment]
> Hi @eerison As far as I know, there is no specific tool or package that helps with this. If you have specific questions about migration, you could contact the [Slim forum](https://discourse.slimframework.com/).

Ok, I just thought that someone started some rector lib,  but that is fine,  thank you for replying
