### ISSUE TITLE
withHeader is not working

### ISSUE THREAD

**Issue by blackslayR** [slimphp/Slim#3288]
```
    public function __invoke(Request $request, Response $response)
    {
        ['name' => $name, 'email' => $email] = $request->getParsedBody();

        Payment::create([
            'name' => $name,
            'email' => $email,
            'token' => bin2hex(random_bytes(32)),
            'stripe_id' => 'abc'
        ]);


        return $response->withHeader('Location', '/');
    }

```

Am still new to slim, am trying to redirect back to the home page, instead it stays at the url of the post method. i dont think it has something to do with my code, therefore it could be a bug?

**Comment by odan** [comment]
Just setting the `Location` header does not cause a redirect. To redirect a request, you also need to set the status code to one of the HTTP redirect codes, usually 302 for a temporary redirect.

Here's how you can do it:

```php
return $response->withHeader('Location', '/')->withStatus(302);
```

* https://www.slimframework.com/docs/v4/objects/response.html#returning-a-redirect
