### ISSUE TITLE
Routing error with array $args but not everytime

### ISSUE THREAD

**Issue by flanderboy** [slimphp/Slim#3294]
Hello everyone,
hai have this route

`$app->get('/topics/{id}', function ($request, $response, array $args) {
   print_r($args['id']);
   exit;
})->setName('app-topics');`

if I call with this URL or other one, it's ok 

`https://www.mydomain.com/topics/STDkQPPO1u0bOCQOX0c2fnvTd1pxUWZNa2QlhOcWmtzXRRJsUZJUv0WO2vKdeehanJz8WJ68cLk8jJ`

but if I use this specific URL 

`https://www.mydomain.com/topics/STDUtN30XOLTilztjcJDaAHa5zQH9Y5i8IyULvsv1UbrpRblPKjaTFGhiNHlL0Yn8rfIkBNRaxImvX`

SLIM redirect me to home route /

Any idea?

thenks 
Stefano

PHP 8.2
SLIM 4

**Comment by odan** [comment]
Your example works on my dev machine. It could be something with the server setup or your browser cache.

Please note, we have nice [Slim Forum](https://discourse.slimframework.com/).

**Comment by flanderboy** [comment]
Thenks @odan
