### ISSUE TITLE
PSR 7 http-message version requirement

### ISSUE THREAD

**Issue by rotexdegba** [slimphp/Slim#3296]
I noticed that version **1.1** of **psr/http-message** is what has been required in the **composer.json** ( https://github.com/slimphp/Slim/blob/fdb6d614700a4e9390c3b08dde96e1f9147ec3fc/composer.json#L51 ) for Slim 4. 

Is it possible to have **"^1.1 || ^2.0"** as the requirement instead?

Version 2.0  ( https://github.com/php-fig/http-message/compare/1.1...2.0 ) of **psr/http-message** has explicit return type typing which is better. Both versions **1.1** & **2.0** of **psr/http-message** require PHP **7.2** or **8.0**.

**Comment by BelleNottelling** [comment]
Temporarily you can do this to get it working with 2.0. I'm using the nyholm PSR7 packages and there aren't any issues with this.
```JSON
"psr/http-message": "2.0 as 1.1"
```

Regardless, it would definitely be ideal to no longer need to implement a workaround

**Comment by l0gicgate** [comment]
Feel free to raise a PR for this

**Comment by rotexdegba** [comment]
> Feel free to raise a PR for this

See https://github.com/slimphp/Slim/pull/3302

**Comment by andreas-aeschlimann** [comment]
I just updated Slim PHP which included this PR (#3302). I had several issues due to the added return types, so I would consider this a breaking change. Maybe this should be noted in the Changelogs?
