### ISSUE TITLE
How to set routes in cli mode?

### ISSUE THREAD

**Issue by sorbing** [slimphp/Slim#330]
How to set route for running cron task? Thanks?

**Comment by codeguy** [comment]
Please move to http://help.slimframework.com/.

**Comment by sorbing** [comment]
Sorry , but you can leave a link to the example page?

**Comment by codeguy** [comment]
I'm not entirely sure what example page you are asking for. You'll find more help for this issue on the forum.

**Comment by sorbing** [comment]
Just give an example of how to run a route on CRON. Please. At the forum, I not found nothing.

**Comment by sorbing** [comment]
да как же запустить роут из консоли в этом чертовом фреймворке?!
