### ISSUE TITLE
Running out of memory by using custom middlewares

### ISSUE THREAD

**Issue by blablabla1234678** [slimphp/Slim#3300]
I have a container like this:

```php
    public function getApplication(){
        if (!isset($this->application)){
            AppFactory::setContainer($this);
            $application = AppFactory::create();

            $application->addRoutingMiddleware();
    
            $errorMiddleware = $application->addErrorMiddleware(
                $displayErrorDetails = $this->getConfiguration()->isDisplayingErrors(), 
                $logErrors = true, 
                $logErrorDetails = true
            );
    
            $application->add(new CSRFMiddleware($this));

            $application->get('/', HomeAction::class);
            $application->get('/posttest', PostTestAction::class);
            $application->post('/posttest2', PostTest2Action::class);

            $this->application = $application;
        }
        return $this->application;
    }
```

I am trying to add a middleware

```php
namespace presentation\middleware;

use Slim\Psr7\Response;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Psr\Container\ContainerInterface;

class CSRFMiddleware
{
    protected $csrf;
    public function __construct(ContainerInterface $container){
        $this->csrf = $container->getCrossSiteRequestForgeryPreventionToken();
    }

    public function __invoke(ServerRequestInterface $request, RequestHandlerInterface $handler): Response {
        if ($request->isPost() && !$this->csrf->validateToken($_POST[$this->csrf->getTokenNameKey()], $_POST[$this->csrf->getTokenValueKey()]))
            throw new Exception('Invalid cross-site request forgery token!');
        return $handler->handle($request);
    }

}
```

Even when I comment out the code inside the middleware I got "PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /home/inf3rno/Desktop/projects/GDPR-manager/vendor/composer/ClassLoader.php on line 425".

Maybe I am doing something wrong, I don't know for sure, this is my first middleware with this framework, but it does not seem to work.

**Comment by odan** [comment]
It looks like there is an infinite loop due to a circular dependency. This occurs when two or more classes depend on each other directly or indirectly, creating a cycle in the dependency graph.

**Comment by blablabla1234678** [comment]
@odan The code runs smoothly without this middleware. I have node idea what the circular dependency can be by a middleware that depends only on the interfaces above. I instantiate it in the container and even when I comment out everything and keep only the $handler->handle I got the same error...

**Comment by blablabla1234678** [comment]
Ok. I got it, the line `$container->getCrossSiteRequestForgeryPreventionToken();` causes the problem.

```php
    public function getCrossSiteRequestForgeryPreventionToken(){
        if (!isset($this->csrf)){
            $this->getSession();
            $responseFactory = $this->getApplication()->getResponseFactory();
            $this->csrf = new Guard($responseFactory);
        }
        return $this->csrf;
    }
```

I am not sure how to use this csrf library then.

**Comment by blablabla1234678** [comment]
Ohh I see I call getApplication() from getApplication() which causes an infinite loop. Strange that it reaches the memory limit before detecting the infinite loop.
