### ISSUE TITLE
How to cache internal https requests

### ISSUE THREAD

**Issue by dawkaka** [slimphp/Slim#3304]
I have a middleware whose constructor makes an HTTP call to get some credentials, these credentials don't change
and with each request that HTTP call is made which makes the requests slow, is there a way to cache the response after the first call and then use it for subsequent calls? does slim PHP have a global cache I can add these credentials to?

**Comment by odan** [comment]
Slim itself does not provide a built-in caching system, but you can integrate any (PSR-6 or PSR-16) caching libraries.
