### ISSUE TITLE
Wrong Response instantiation inside Mİddleware Example

### ISSUE THREAD

**Issue by pdesign** [slimphp/Slim#3309]
Slim documentation examples about Middlewares contains wrong code as you create new Response... It's trying to instantiate Response using "Psr\Http\Message\ResponseInterface"...

I guess it should use "Slim\Psr7\Response" to create "new Response()"

https://www.slimframework.com/docs/v4/concepts/middleware.html

Example here in this page includes code like this...

	<?php
		$beforeMiddleware = function (Request $request, RequestHandler $handler) {
			$response = $handler->handle($request);
			$existingContent = (string) $response->getBody();
			$response = new Response(); **// Here is the faulty line...**
			$response->getBody()->write('BEFORE' . $existingContent);
			return $response;
		};
	?>

**Comment by odan** [comment]
This approach is indeed a point of confusion. Technically this is also not correct. 
Slim is designed to be compatible with the PSR-7 interfaces, and developers can choose different PSR-7 implementations. 

In practice, the PSR-7 [ResponseFactoryInterface](https://github.com/php-fig/http-factory/blob/master/src/ResponseFactoryInterface.php) should be used anyway to create a new Response object within a **middleware**. 

Example:

```php
$app->add(function (Request $request, RequestHandler $handler) use ($app) {
    $response = $handler->handle($request);
    $contents = (string)$response->getBody();
    // ...
    
    $response = $app->getResponseFactory()->createResponse();
    $response->getBody()->write('My data');
    
    return $response;
});
```
On the other hand, the `handle` method already returns a Response object. So creating a new Response is a very rare and specific use-case. The documentation just tries to show the concept.

**Comment by akrabat** [comment]
Documentation fixed in https://github.com/slimphp/Slim-Website/pull/689.
