### ISSUE TITLE
Slim 3 error (Deprecated) on PHP 8.2

### ISSUE THREAD

**Issue by abdo-host** [slimphp/Slim#3327]
`( ! ) Deprecated: Return type of Slim\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\Wamp\www\PHP\slim3\vendor\slim\slim\Slim\Collection.php on line *112*`

Example:

```
<?php
require 'vendor/autoload.php';

$app = new \Slim\App();

$app->get('/', function (Request $req,  Response $res, $args = []) {
	return $res->withStatus(200)->write('Hello World');
});
```

**Comment by odan** [comment]
See here: https://github.com/slimphp/Slim/issues/3234
