### ISSUE TITLE
Property $app with generic class Slim\App does not specify its types: TContainerInterface

### ISSUE THREAD

**Issue by j0k3r** [slimphp/Slim#3329]
Following this PR https://github.com/slimphp/Slim/pull/3322, PHPStan is yelling on one of our project.

The error is:

> Property Tests\OurProject\BaseTestCase::$app with generic class Slim\App does not specify its types: TContainerInterface

Here is the code:

```php
<?php

namespace Tests\OurProject;

use PHPUnit\Framework\TestCase;

class BaseTestCase extends TestCase
{
    /** @var \Slim\App */
    protected $app;

    protected function setUpApp(bool $mockedClient = false): void
    {
        $this->app = require __DIR__ . '/../src/App.php';
```

PHPStan throw that error on the line `protected $app;`.
What type or change I need to apply to resolve it?

_Poke @limarkxx_

**Comment by akrabat** [comment]
As App has a `getContainer(): ?ContainerInterface` method, the generic doc block enables you to specify what type is actually returned when this method is called. i.e. if you are using PHPDI and write:

```php
$container = $this->app->getContainer();
$entries = $container->getKnownEntryNames();
```

PHPStan has no way of knowing that `$container` is an instance of PHPDI which has a `getKnownEntryNames()` method and so will complain.

To tell PHPStan this we change: `/** @var \Slim\App $app */` to `/** @var \Slim\App<DI\Container> $app */` and now PHPStan knows this.

If you want to use just PSR `ContainerInterface` methods, then you hint as `/** @var \Slim\App<\Psr\Container\ContainerInterface> $app */`

If you are not using a container at all, then hint with: `/** @var \Slim\App<null> $app */`

**Comment by j0k3r** [comment]
Awesome, thanks for that great explanation.
I'm not so familiar with template & generics.
