### ISSUE TITLE
strpos complaining about empty delimiter with short URLs

### ISSUE THREAD

**Issue by Adirelle** [slimphp/Slim#333]
I'm having the following error with the URL "http://localhost:8080" (which redirect to  using apache mod_rewrite from core config) :

`Warning: strpos() [function.strpos]: Empty delimiter in /var/www/appli/vendor/slim/slim/Slim/Environment.php on line 137`

In this case, $_SERVER['REQUEST_URI'] contains '/' and $_SERVER['SCRIPT_NAME'] is empty.

As a fix, I tried to use the @ operator with strpos. It seems to work thought I'm not sure about all side-effects..

**Comment by miraage** [comment]
Are you using NGINX?

**Comment by Adirelle** [comment]
No. Standard Debian packages for Apache2 (2.2.16) and PHP (5.3.3).

The setup is done in a "site" file (Debian"s /etc/apache2/sites-_/_ files) and I'm using the following rewrite rules :

```
RewrireEngine On
RewriteCond %{REQUEST_URI} !^/.+\.php
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
RewriteRule ^/?(.*)$ %{DOCUMENT_ROOT}/index.php/$1 [QSA,L]
```

My index.php file is stored directly in the document root.

URL containing the script name are working fine but short URLs are causing this warning twice.

I'm currently trying to use Composer to fetch my project dependencies, including Slim, so I cannot use a modified version (as I was doing until now).

**Comment by Adirelle** [comment]
On a side note, short URLs are also working fine when the application is hosted into a subfolder .

**Comment by miraage** [comment]
Put next .htaccess file into your document root: https://gist.github.com/3096679 (correct RewriteBase option if need)
Helped you?

**Comment by Adirelle** [comment]
This works fine. However I'm not fond of using .htaccess files.

**Comment by codeguy** [comment]
Seems like you have a resolution. Closing. Please move further discussion to http://help.slimframework.com/.
