### ISSUE TITLE
Tests badge always indicates "failing"

### ISSUE THREAD

**Issue by limarkxx** [slimphp/Slim#3330]
![image](https://github.com/slimphp/Slim/assets/53534357/66bd5d7a-00d2-4aac-9758-fab9e59fb337)
The Tests badge indicate failing tests, even though tests pass.

The badge markdown should be changed to 
```markdown
[![Tests](https://github.com/slimphp/Slim/actions/workflows/tests.yml/badge.svg)](https://github.com/slimphp/Slim/actions/workflows/tests.yml)
```
in accordance to [Github docs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name) in this readme and any other media which may reference this badge.

Result below:
[![Tests](https://github.com/slimphp/Slim/actions/workflows/tests.yml/badge.svg)](https://github.com/slimphp/Slim/actions/workflows/tests.yml)

**Comment by l0gicgate** [comment]
Feel free to raise a PR to fix this. Thank you for raising 😄
