### ISSUE TITLE
UrlFor protocol

### ISSUE THREAD

**Issue by tobiascapin** [slimphp/Slim#3332]
I'm using urlFor method to get the full URL of a route, but is it not clear to me if it is possibile to set the wanted protocol, it seems always http is given.

**Comment by tobiascapin** [comment]
Sorry, I just discovered the current UriInterface is used and my server uses http because https is handled by the balancer.

**Comment by odan** [comment]
The schema of the request object could be switched using a middleware that you add after the RoutingMiddleware. 

```php
$app->addRoutingMiddleware();

$app->add(function(ServerRequestInterface $request, RequestHandlerInterface $handler) {
    $request = $request->withUri($request->getUri()->withScheme('https'));
    return $handler->handle($request);
});

```

To get the full url you can use the `fullUrlFor` method of the RouteParser instance.

```php
// https://api.example.com/
$fullUrl = $routeParser->fullUrlFor($request->getUri(), 'home', $data, $queryParams);
```

**Comment by tobiascapin** [comment]
Great. Thank you very much.

**Comment by tobiascapin** [comment]
I come back to this topic because it seems `getUri()->withScheme('https')` doesn't fill the correct port. 
had also to add `->withPort(443)` otherwise some https URL will be made like https://myhost:80/path and doesn't work.
I don't know if I'm missing something or by design withScheme has to go with withPort method.

**Comment by odan** [comment]
@tobiascapin Yes, it makes sense to change these two values (scheme and port) together. Thanks for your feedback.
