### ISSUE TITLE
GRPC

### ISSUE THREAD

**Issue by tjgumis** [slimphp/Slim#3337]
Some GRPC request handler would be much appreciated :)

**Comment by odan** [comment]
You mean something like [Roadrunner](https://github.com/roadrunner-php/grpc)?

**Comment by tjgumis** [comment]
Roadrunner is a server (among all http), Slim can be easily hooked up, and it works fine, cause receives http request shaped properly to be handled.
On the other hand Roadrunner serves also GRPC requests, and Slim has nothing to deal with it yet.
There is something like Sprial framework (dedicated to Roadrunner), its a pitty, that is actually kind of fork of Symfony, which is ready to serve both grpc and websockets connections, even mettrics. Slim's simplicity makes it possible to do it all either with a  bit of a good will of Slim dev team.

GRPC in Slim looks for me like something worth to be considered, for the future, considering Slim's long time releases - which is good by the way.
We, as a team, have almost finished a platform (modular monolith microservices), highly resources and transfer intensive, everything based on Roadrunner/Slim and all works as expected, but in a year or two we will find ourselves on the edge of http capabilities, so GRPC looks to be a natural choice. Possible lack of Slim just breaks my hart.
