### ISSUE TITLE
Port 5.x working branch to slimphp/slim

### ISSUE THREAD

**Issue by jlaswell** [slimphp/Slim#3341]
I propose the 5.x working branch be brought over to slimphp/slim to prevent individuals needing to subscribe to multiple repos to keep up to date. This also keeps a change history directly in slimphp, which is best for future contributors.

**Comment by odan** [comment]
This brach for 5.x will be created here in the next days.

**Comment by odan** [comment]
The branch "5.x" has been created. Closing this as solved.
