### ISSUE TITLE
"Sail up -d" for Slim?

### ISSUE THREAD

**Issue by joserick** [slimphp/Slim#3342]
Is there an automated system for developing Slim like Laravel's "Sail"?

So that with a single command "curl -s "https://laravel.build/example-app" | bash" I can generate the entire environment (Docker) necessary to start programming?

Without the need to install PHP, Aapche/Nginx, Composer, etc. and these are independent of each other.

**Comment by odan** [comment]
As far as I know Slim doesn't have an official tool like Sail, but you can create your own Docker setup with a bash script.

**Comment by joserick** [comment]
In case we develop something similar to Sail with domain and everything, would you allow us to add it to the official documentation @odan ? More than anything to make it worthwhile.

**Comment by odan** [comment]
Yes, we would list such a project in the official documentation.

**Comment by joserick** [comment]
Hi @odan ,

Below is a list of names that we think could be used for the program that will automate the development environment. We would like to hear your opinion or if you have any in mind.

1. Skif
2. Glid
3. Drft
4. Flow
5. Sift
6. Swft
7. Bree
8. Flux
9. Drip
10. Slip

Likewise, I'm told that "[Slim.build](https://slim.build/)" has already been acquired.

**Comment by odan** [comment]
Could this also be hosted on Github pages?

**Comment by joserick** [comment]
Of course, if you like you can create the repository for the site and give us permissions to proceed with the configuration of the domain DNS ([Slim.build](https://slim.build/)) and this redirects to Github pages.

At the end of the day, we decided to call the project "lift" because it would give meaning to the command:
"slim lift -up": "The word "lift" suggests raising or launching, which fits with the idea of ​​getting your project off the ground."

To which, We would like to know if it is possible for you to create a private repository with this name “Lift” and give us the corresponding permissions to start with it.

**Comment by odan** [comment]
Thanks for your interest in improving the Slim development experience.

After internal discussion, we've concluded that we try to keep Slim focused on being a micro-framework while still helping developers who want to use Docker. This type of content would work better as **documentation**. 

I would like to encourage you to contribute this as a PR to the documentation repository instead. You could create a new section about Docker environments, including your examples and approach. Feel free to also reference your Slim lift project there.

**Comment by joserick** [comment]
Thank you very much for your responses, then we will proceed to implement "Slim lift" as a third-party package, and subsequently make contributions to the repository, referring to the documentation for implementation and Docker environment.
