### ISSUE TITLE
Can't get params as array in $args

### ISSUE THREAD

**Issue by Cristian9828** [slimphp/Slim#3345]
Hello,
I have a problem with your framework.

According to the documentation found at the link https://www.slimframework.com/docs/v4/objects/routing.html#how-to-create-routes, I tried to create a GET route to pass two parameters.

The route is this: 
![image](https://github.com/user-attachments/assets/9aff9ba8-cdcf-4aa3-855e-9211af64dfdb)

Route management in Slim:
![image](https://github.com/user-attachments/assets/6ccfc9e7-59a0-452e-bde1-5c393b22be01)

Added Routing Middleware in index.php:
![image](https://github.com/user-attachments/assets/966e4d47-345a-4b71-9152-08ee31b05b27)

As you can see, at the next step, it all seems correct. $routeArguments value correctly shows an associative array:
![image](https://github.com/user-attachments/assets/273d50ac-a06f-459c-a2f4-f330b00c064b)

Than passing to my controller, at the direct next step, the same parameter transforms into a unique string:
![image](https://github.com/user-attachments/assets/9dee8435-6aac-4e9f-a9fb-cbf6a76f1739)

I'm doing something wrong?
Tried anything but really can't solve the problem.
I found out that there is the possibility to get this params correctly from this:
$request->getAttributes()['__route__']->getArguments()

I'll appreciate to use what is advised from docs and all forums users, so $args..
Let me know!
Thank you

**Comment by odan** [comment]
It looks like you are using the `RequestResponseArgs` strategy, which passes  the route parameters as individual arguments.  To get the args as an array, you need to change the strategy to `RequestResponse`.

**Comment by Cristian9828** [comment]
Hello!
Thank you for your answer!

Edited the strategy to RequestResponse as you suggested and now it works perfectly!!
Didn't found anything in documentation about this. Even using searchbar and typing exactly "RequestResponse", no results. Did I miss any other link or forum explaining this?

Thank you very much!
Great framework!
Cristian

**Comment by odan** [comment]
As reference, the documentation is here: https://www.slimframework.com/docs/v4/objects/routing.html#route-strategies
