### ISSUE TITLE
StdLogger default constuctor arguments not compatible with all SAPI's

### ISSUE THREAD

**Issue by vdelau** [slimphp/Slim#3347]
The `StdLogger` class introduced in 5.x has `STDOUT` and `STDERR` as default values in the constructor [1]. These constants are not available in every SAPI, for instance in the built-in webserver. This will lead to a fatal error:

```
PHP Fatal error:  Uncaught Error: Undefined constant "Slim\Logging\STDOUT"
```

`StdLogger` is the default logger used in the `DefaultDefinitions` [2], so if no `LoggerInterface` implementation is specified, `StdLogger` will be used.

I see three possible directions to solve this:
- Default to using `Psr\Log\NullLogger`, either always or when `STDOUT` and `STDERR` are not defined.
- Make `StdLogger` more resilient and not log if `STDOUT` and `STDERR` are not available (effectively making it a `NullLogger`).
- Keep as is and just document configuration of an appropriate `LoggerInterface` implementation explicitly.

I think defaulting to `NullLogger` makes most sense. In web SAPI's, outputting to `STDOUT` might not be desirable anyway. I think in addition it would be good to make `StdLogger` more resilient, by not using the constants as a default value but something else.

[1]: https://github.com/odan/Slim/blob/5.x/Slim/Logging/StdLogger.php#L33
[2]: https://github.com/odan/Slim/blob/5.x/Slim/Container/DefaultDefinitions.php#L134

**Comment by geggleto** [comment]
//cc @odan

**Comment by odan** [comment]
> I think defaulting to NullLogger makes most sense.

Yes, that's a good input. The NullLogger will be the "default" logger.

**Comment by vdelau** [comment]
`StdLogger` was removed in https://github.com/slimphp/Slim/commit/58f11b64f41e9ec1ce0933ca9a9d2183e650fa91 and replaced with the `NullLogger`.
