### ISSUE TITLE
Update FastRoute

### ISSUE THREAD

**Issue by FrantzUml** [slimphp/Slim#3352]
The functions \FastRoute\cachedDispatcher and \FastRoute\simpleDispatcher
are deprecated since V2 of FastRoute 
and will bee removed soon.
The 2 functions are used in Dispatcher

**Comment by odan** [comment]
That's interesting. Could you please provide a link to that information?

**Comment by SAutushka** [comment]
https://github.com/nikic/FastRoute/blob/d3ada013d0f683ad2a8d0614fc97917a6ab72ce9/src/functions.php#L14
https://github.com/nikic/FastRoute/blob/d3ada013d0f683ad2a8d0614fc97917a6ab72ce9/src/functions.php#L31

**Comment by odan** [comment]
> deprecated since v2.0 and will be removed in v3.0

FastRoute v2 is still in beta (not yet released), so Slim 4 does not support it. When FastRoute v3 is released, Slim 4 could add support with a shim. Therefore, I suggest waiting until the first beta of FastRoute v3. Note that already in Slim 5, the simpleDispatcher function will not be used any more.
