### ISSUE TITLE
Code optimization for Slim_Route::matches()

### ISSUE THREAD

**Issue by thomas-0816** [slimphp/Slim#336]
Slim_Route::matches()

changes:
- moved preg_match_all down since it is only needed if the uri matches
- replaced [a-zA-Z0-9_-.!~*\\'():\@&\=\$+,%] with [^/]
- changed the delimiters to # to be able to match the "@"
- changed convertPatternToRegex to anonymous function

``` php
    public function matches( $resourceUri ) {
        //Convert URL params into regex patterns, construct a regex for this route
        $patternAsRegex = preg_replace_callback('#:([\w]+)#', function($m) {
            return '(?<' . $m[1] . '>' . (isset($this->conditions[ $m[1] ]) ? $this->conditions[ $m[1] ] : '[^/]+') . ')';
        }, $this->pattern);

        if ( substr($this->pattern, -1) === '/' ) $patternAsRegex += '?';

        //Cache URL parameters if this route matches the current HTTP request
        if ( ! preg_match('#^' . $patternAsRegex . '$#', $resourceUri, $paramValues) ) return false;

        //Extract URL param names
        preg_match_all('#:([\w]+)#', $this->pattern, $paramNames, PREG_PATTERN_ORDER);

        foreach ( $paramNames[1] as $name ) {
            if ( isset($paramValues[$name]) ) {
                $this->params[$name] = urldecode($paramValues[$name]);
            }
        }
        return true;
    }
```

**Comment by codeguy** [comment]
Slim supports 5.2+ and cannot rely only on an anonymous function just yet. Replace with 5.2+ compatible implementation. Slim will go 5.3+ in version 1.7 or 1.8.

**Comment by thomas-0816** [comment]
ok, second one:

``` php
    const PATTERN_NAME = '#:([\w]+)#';

    public function matches( $resourceUri ) {
        //Convert URL params into regex patterns, construct a regex for this route
        $patternAsRegex = preg_replace_callback(self::PATTERN_NAME, array($this, 'matchesCallback'), $this->pattern);

        if ( substr($this->pattern, -1) === '/' ) $patternAsRegex += '?';

        //Cache URL params' names and values if this route matches the current HTTP request
        if ( ! preg_match('#^' . $patternAsRegex . '$#', $resourceUri, $paramValues) ) return false;

        //Extract URL params
        preg_match_all(self::PATTERN_NAME, $this->pattern, $paramNames, PREG_PATTERN_ORDER);

        foreach ( $paramNames[1] as $name ) {
            if ( isset($paramValues[$name]) ) {
                $this->params[$name] = urldecode($paramValues[$name]);
            }
        }
        return true;
    }

    protected function matchesCallback( $m ) {
        return '(?P<' . $m[1] . '>' . (isset($this->conditions[ $m[1] ]) ? $this->conditions[ $m[1] ] : '[^/]+') . ')';
    }   
```

**Comment by codeguy** [comment]
~~Seems like you're using a similar pattern to Sinatra (e.g. `[^/]+`). Keep in mind that you should also break on `#` and `?` for final url segment~~

EDIT: Realized this is not necessary since this method is given a pre-sanitized version of the resource URI that will not contain the `#` or `?` characters.

**Comment by codeguy** [comment]
Can you submit pull request?

**Comment by codeguy** [comment]
Also, be sure you are working from the release-1.6.5 branch which includes additional code for matching wildcard characters.

**Comment by thomas-0816** [comment]
Yes, will do it next weekend and also check for the test cases.

**Comment by codeguy** [comment]
Ok. I'll likely have 1.6.5 released by then. I'll get this pulled into 1.6.6.

**Comment by thomas-0816** [comment]
The 1.65 has the new wildcard matching:

$_SERVER["REQUEST_URI"] = "/hello/foo/bar/world";
$app = new Slim();
$app->get('/hello/:foo/*/:bar', function ($foo, $bar) {
print_r(func_get_args());
});
$app->run();

=> the function is called with 3 parameters (wildcard is second parameter).

**Comment by thomas-0816** [comment]
1) I propose named wildcard parameters:
:name to match a parameter to params[name] as scalar
:name+ to match a path to params[name] as array
"*" to match any path and don't get into params[]
e.g.
$_SERVER["REQUEST_URI"] = "/hello/foo/bar/bar2/world/some-seo-bla";
$app->get('/hello/:foo/:bar+/world/*', function ($foo, $bar) {
// $foo = foo
// $bar = [bar, bar2]
});

2) Or use $route->getWildcardParams() together with protected $wildcardParams

=> I can make a patch for both

**Comment by codeguy** [comment]
I prefer that both named parameters and wildcard placeholders be provided to the route callback as arguments. Otherwise, it becomes cumbersome to fetch wildcard values in the route callback.

For your second suggestion using `getWildcardParams`, can you provide an example demonstrating how that should be used in practice?

I propose we use something like this:

```
$app->get('/test/:foo/*/:bar', function ($foo, $splat1, $bar) {
    // Do something 
});
```

For a request URI "/test/one/two/three/four":
- The arg `$foo` will equal `one`.
- The arg `$splat1` will equal `array('two', 'three')`.
- The arg `$bar` will equal `four`.

**Comment by codeguy** [comment]
If named wildcards are easier, I'd still use the '*' character to designate wildcard parameters (not 1:1 with regex connotation, but that's fine). In this case:

```
$app->get('/test/:foo/:splat*/:bar', function ($foo, $splat, $bar) {
    // Do something 
});
```

For a request URI "/test/one/two/three/four":
- The arg `$foo` will equal `one`.
- The arg `$splat` will equal `array('two', 'three')`.
- The arg `$bar` will equal `four`.

The only benefit to using a named param is that you can easily fetch the splat's array value via custom named key from `$route->getParams()`.

I think I may prefer this method, really. Best of both.

**Comment by codeguy** [comment]
You'll want to pull and rebase against a few tweaks I've pulled in with #338.

**Comment by thomas-0816** [comment]
> not 1:1 with regex connotation, but that's fine

That's where I think "+" maybe more intuitive. People not reading documentation properly might think of :splat\* being an optional parameter.

**Comment by codeguy** [comment]
I think that's a reasonable compromise. Go for it. Be sure you rebase against changes pulled in with #338 though.

**Comment by thomas-0816** [comment]
Here is a use case:
e.g. someone builds a shop: http://www.amazon.de/Samsung-Smartphone-Super-AMOLED-Touchscreen-Megapixel-ceramic-white/dp/B00812YWXU/

/*/dp/:asin/
function showProduct($asin) {...}

/:seo*/dp/:asin/ or /:seo+/dp/:asin/
function showProduct($seo, $asin) {...}

$r = new Slim_Route('/*/dp/:asin/', function () {});
$r->matches('/Samsung-Smartphone-Super-AMOLED-Touchscreen-Megapixel-ceramic-white/dp/B00812YWXU/');
$this->assertEquals( ['asin' => 'B00812YWXU'], $r->getParams() );
$this->assertEquals( [ ['Samsung-Smartphone-Super-AMOLED-Touchscreen-Megapixel-ceramic-white'] ], $r->getWildcardParams());

**Comment by codeguy** [comment]
Ok. I still think that it is far too difficult to fetch the wild card parameter values if they are not provided as arguments to the callback. Can you implement both our suggestions? Use named wildcard parameters with "+" suffix, but also pass each wildcard parameter's values as arguments to the callback?

**Comment by thomas-0816** [comment]
I Implemented named wildcard parameters with "+" suffix, passing all parameters to the callback:
https://github.com/codeguy/Slim/pull/355 I hope it's ok?

**Comment by thomas-0816** [comment]
Done.
