### ISSUE TITLE
Use configureMode without setting mode in new Slim()

### ISSUE THREAD

**Issue by m1chu** [slimphp/Slim#351]
``` php
$app = new Slim(array(
    'mode' => 'production'
));

$app->configureMode('production', function () use ($app) {
    $app->config(array(
        'log.enable' => true,
        'debug' => false
    ));
});
```

Above comes from official documentation. What happens if we don't initialize settings when instance is created, but by $app->config()? Something like:

``` php
$app = new Slim();
// some other code
$app->config(
    array(
        'mode'                      => 'production'
    )
);

// this will not work (but should)
$app->configureMode('production', function() use($app) {
    $app->config(
        array(
            'debug'                     => false,
        )
    );
});

// this will work (but shouldn't)
$app->configureMode('development', function() use($app) {
    $app->config(
        array(
            'debug'                     => true,
        )
    );
});

$app->run();
```

This is because only configuring in new Slim() sets correctly mode. When you will try to set it in $app->config() settings array element will be changed, but mode variable of Slim class not. A natural consequence of this is that although 'production' mode is set, the 'development' (default) configureMode is used.

Confusing...

**Comment by codeguy** [comment]
You're more than welcome to submit a PR to improve this. If you'd rather I make these changes, just let me know. I want you to get credit for your improvements.

**Comment by m1chu** [comment]
I have already found only potential bug. But if you give me few days I will try to submit a PR as improvement proposial. Thanks for you response.

**Comment by codeguy** [comment]
Sounds good.

**Comment by codeguy** [comment]
Did you send a separate PR for this?

**Comment by codeguy** [comment]
Closing. You should set Slim app mode in environment variable or during Slim construction. Docs have been updated to clarify this.
