### ISSUE TITLE
problem with redirect()

### ISSUE THREAD

**Issue by fathihadi** [slimphp/Slim#358]
I just tried bellow code (from http://www.slimframework.com/documentation/stable#request)

$app = new Slim(); $app->get('/foo', function () use ($app) {

$app->redirect('/bar');
}); $app->run()

my working directory is localhost/new/api/public/

the problem is when i access it using browser(GET) ' localhost/new/api/public/index.php/foo ' it redirect me to ' localhost/bar ' not to ' localhost/new/api/public/index.php/bar/ '

But when i change $app->redirect('/bar'); to $app->redirect('bar'); it redirect to ' localhost/new/api/public/index.php/bar'

Is this bug or only typo in documentation ? http://www.slimframework.com/documentation/stable#request, If yes i hope Slim team will fix this. Thanks

**Comment by mariodev** [comment]
Redirecting with "/bar" probably assumes that you have your domain set up, so you need to set your virtualhost in development environment

**Comment by codeguy** [comment]
I don't see any issues. But I need a few more details to help you troubleshoot:
- What is your virtualhost document root?
- What exact URL do you request?
- What exact URL does it redirect to?

**Comment by codeguy** [comment]
For now I recommend you post your question to the Slim support forum at http://help.slimframework.com/. If we find that it is indeed a Slim issue, I'll re-open a ticket for it here.
