### ISSUE TITLE
env['PATH_NAME'] in dev and master

### ISSUE THREAD

**Issue by rs3d** [slimphp/Slim#361]
I've got an issue concerning $env['PATH_INFO'] and therefore the routing logic with the current versions 1.6.4 and 1.6.5 is broken in my app.

My directory structure (/html is the document root):

/html/Slimplr--0.0.1/index.php --> My rewrites go here and includes Slimplr.php
/html/Slimplr--0.0.1/app/Slimplr.php --> My Slimplr-Class which extends Slim

/html/Slim --> Slim framework source files

So if i request URLs like  http://domain.com/foo or  http://domain.com/foo/bar the request object 'env'=>['PATH_INFO'] and getResourceUri always return '/' since I've updated the slim sources. Slim 1.5.0 worked for me.
If I request http://domain.com/Slimplr-0.0.1/foo I'm getting '/foo' 

'env' =>  'SCRIPT_NAME' is '/Slimplr-0.0.1' in all cases.

This is happening both on nginx and apache.

**Comment by codeguy** [comment]
I'm a bit confused. I encourage you to revise your application directory structure to remove your dependency on mod_rewrite magic. The physical path to your public subdirectory must be in your application's HTTP request URI else it will break Slim's routing.

I think you're better off posting your question to the Slim support forum at http://help.slimframework.com/.
