### ISSUE TITLE
Website documentation code indenting

### ISSUE THREAD

**Issue by briannesbitt** [slimphp/Slim#375]
The website documentation code snippets don't get indented properly.  Typically the code is all indented by 4 spaces which indicates a code block.  In the code block if there is more indentation levels, the website rendering doesn't reflect that.

Example:

```
for ($i = 0 ; $i < 5 ; $i++) {
    echo $i;
}
```

In the example above the `echo $i;` is indented within the code block but the website rendering doesn't reflect that.

**Comment by codeguy** [comment]
Hmm. The source markdown seems fine. Probably something going awry when generating the HTML. Will have a look.

**Comment by codeguy** [comment]
Also, the documentation will soon be moved into its own GitHub Pages repo. So I'm not going to worry too much about this.
