### ISSUE TITLE
Is ContentType: image/png supported?

### ISSUE THREAD

**Issue by istvanskeri** [slimphp/Slim#377]
Is it possible to return an image using the gd library?

**Comment by ianvanness** [comment]
This works great for me (php5.4 array dereferencing in effect here)

``` php
$app->get( '/png/', function() use ( $app ) {
    $app->response()['Content-Type'] = 'image/png';
    $im     = imagecreatefrompng("pants.png");
    imagepng($im);
    imagedestroy($im);
});
```

Response header shows this, as expected:

```
Content-Type:image/png
```

**Comment by istvanskeri** [comment]
hmm i'm getting a syntax error, unexpected '['

from this line:

  $app->response()['Content-Type'] = 'image/png';

wonder if i need to change something in php.ini it wont let me do that

**Comment by istvanskeri** [comment]
nevermind got it to work, thanks!
