### ISSUE TITLE
There should be a way to have custom Exception handler

### ISSUE THREAD

**Issue by jcubic** [slimphp/Slim#378]
There should be a way to disable `Slim_Middleware_PrettyExceptions` or overwire it with your own Middleware or a function.

there can be abstract class `Slim_Middleware_Exception` that have not defined `renderBody`.

class `Slim_Middleware_PrettyExceptions` can extend `Slim_Middleware_Exception` class and implement this method, and there can be option to include object of the class that extend `Slim_Middleware_Exception`.

The other option is to have `Slim::exceptionHandler( Closure $fun);` and that function will be executed instead of `Slim_Middleware_PrettyExceptions::renderBody`

I can fork repo and fix this and add pull request if you accept them (there are 14 waiting for merge).

**Comment by jcubic** [comment]
Actually I just found that I can overwrite `Slim_Middleware_PrettyExceptions` with 

``` php
class NiceExceptions extends Slim_Middleware_PrettyExceptions {
    protected function renderBody(&$env, $exception) {
       return '<pre>' . $exception->getTraceAsString() . '</pre>';
    }
}

$app = new Slim();
$app->add(new NiceExceptions());
```

**Comment by codeguy** [comment]
You already have that ability. Set application setting `debug` to `false` and then specify your own handler like this:

```
$app->error(function (\Exception $e) {
    // Do something
});
```

**Comment by jcubic** [comment]
Yes, thanks I know you tell me, I think it was in other issue, because I don't see your answer here. I close this one already.

**Comment by kishu27** [comment]
how do you suggest I do something like:  

```
$app->error(function (CustomException $e) {
    // Do something
});
$app->error(function (AnotherException $e) {
    // Do something
});
$app->error(function (MoreCustomException $e) {
    // Do something
});
$app->error(function (\Exception $e) {
    // Do something
});
```

or do you suggest using an instanceOf  check inside a single $app->error route?
