### ISSUE TITLE
Stripslashes

### ISSUE THREAD

**Issue by d-fens** [slimphp/Slim#38]
Hello World` application (PHP 5 < 5.3)

So you're supporting less than 5.3 in some cases s I thought I'd mention this bug.

You need to stripslashes if get_magic_quotes_gpc is enabled. I used an array_map and static function to remove them recursively and call it on $COOKIE, $_POST and $_GET.

```
    public static function stripslashes($value) {
            if (is_array($value)) {
                    $value = array_map(array('CLASSNAME', 'stripslashes'), $value);
            } else {
                    $value = stripslashes($value);
            }
            return $value;
    }
```

**Comment by codeguy** [comment]
Thanks for this. I'll be sure to add this code into the Request class and strip slashes on $_COOKIE and $_POST and $_GET data.

**Comment by codeguy** [comment]
I've just pushed a fix for this.
