### ISSUE TITLE
notFound overwrite body set in the handler

### ISSUE THREAD

**Issue by jcubic** [slimphp/Slim#380]
This code will not work, because notFound function invoke halt that remove everything that was set.

``` php
$app->notFound(function () use ($app) {
    $response = $app->response();
    $response['Content-Type'] = 'text/html';
    $response->body('Some Error');
});
```

there is no need for `ob_start();` beceause it's handled by `Slim::call`. so notFound should look like this (without halt and buffer).

``` php
    public function notFound($callable = null) {
        if (!is_null(($callable))) {
            $this->router->notFound($callable);
        } else {
            $customNotFoundHandler = $this->router->notFound();
            if (is_callable($customNotFoundHandler)) {
                call_user_func($customNotFoundHandler);
            } else {
                call_user_func(array($this, 'defaultNotFound'));
            }
            $this->response->status(404);
            $this->stop();
        }
    }
```

I didn't created patches nor pull request because I don't know if you merge them.

**Comment by jcubic** [comment]
Looking again at the code, it sould look like `Slim::error` that execute `Slim::callErrorHandler` look cleaner.

**Comment by codeguy** [comment]
Send PRs against the develop branch, please. Day job has kept me busy the past few weeks. Will start pulling fixes in tomorrow.

**Comment by jcubic** [comment]
I'm still learning git and never work with forks and pull requests (I'm reading [Git-Branching](http://git-scm.com/book/en/Git-Branching)). 

I've created a [branch for pull request](https://github.com/jcubic/Slim/commits/handlers), I commit 2 fixes, I need to test it and I want to add fix for Slim::error which should be executed on exceptions

https://github.com/jcubic/Slim/commit/afdcd708957ac479b80492bdd8abae1be665a3e9

PS: how can I add branch that is in the repo, like `remotes/origin/develop` so I can switch to it using `git checkout develop`?  I have repo in two places, on server I have branches develop and master and an my local machine

On local machine I created a new brach and pull from develop I think I those changes where merge to my handlers branch.

**Comment by jcubic** [comment]
Re: PS: I found it, when I call `git checkout develop` it add this branch.

**Comment by briannesbitt** [comment]
They are implemented the same.  In your notFound handler just echo what you want rendered to the body rather than returning it and it will be added to the reponse.  Take a look at `Slim::notFound( $callable = null )` vs `Slim::callErrorHandler($argument)` rather than the 2 you were looking at as they are serving different purposes.

Your suggested code changes above would leave whatever was already written to the response body (by middleware or hooks) there.  This is why the new ob is created and ob_get_clean() is used and the halt() is necessary.

**Comment by jcubic** [comment]
You're are right my code don't fix that, but bug remain - here is code for develop branch

``` php
$app->get('/xxx', function() use ($app) {
   echo "xxx";
   $app->response()->body("xxx body");
   $app->notFound();
});


$app->notFound(function () use ($app) {
    echo "notfound echo";
    $app->response()->body('not Found body');
});
```

for /xxx it show

```
notfound echo
```

but should display

```
not Found body<br/>
```

response->body is overwriten by ob_ buffer it's wrong because body method will never work.

and there is also one different bug in standard route:

``` php
$app->get('/xxx', function() use ($app) {
   echo "xxx<br/>";
   $app->response()->body("xxx body<br/>");
});
```

this display:

```
xxx body
xxx
```

instead of just `xxx body`

**Comment by jcubic** [comment]
I think that solution is to add ob_clean to `body` method for normal route to work.

for Ultimate solution Slim should 

get the start ob_buffer body will clean the buffer if called if reponse have body it would be printed if something is in the ob_buffer that need to be printed and after that the return value need to be appended.

and for this to work

``` php
$app->get('/', function() use ($app) {
    $r = $app->response();
    echo "1";
    $r->body("2");
    echo "3";
    $r->body("4");
});
```

body method will need to start another buffer before it ends. (data from Buffer append to body body reset buffer and result value append at the end).

**Comment by briannesbitt** [comment]
None of what you are describing I would consider a bug but rather its expected behaviour.

**Comment by jcubic** [comment]
There are 3 types of handlers and Slim give two results if its executed in notFound or error and route

``` php
$handler = function() use ($app) {
   echo "xxx<br/>";
   $app->response()->body("xxx body<br/>");
}
```
- route and error:

```
xxx body
xxx
```
- not found

```
xxx
```

Slim documentation said that:

> You can use the Slim application’s Response object to set the HTTP response’s body like this
> $response->body('Foo'); //The body is now "Foo" (overwrites)

body function don't set body of the response it append ob_ buffer in the end in route and error and in notFound it don't work at all, and you tell me that this is not a bug but expected behavior?
