### ISSUE TITLE
error handler should overwrite default prettyprint exception handler

### ISSUE THREAD

**Issue by jcubic** [slimphp/Slim#393]
To overwrite `Slim_Middleware_PrettyExceptions` you can create it's child class and add it to the list using `Slim::add`. I think that this code is much better, one function instead of a class with one function

``` php
$app->error(function($e) {
    return "Sorry but " . $e->getMessage() . " has happen";
});
```

Note also that most errors are just exceptions

In this way we get rid of one class because that code can be moved to `Slim::prettyprint` Note also that this class have the same html as returned by `Slim::generateTemplateMarkup`

I creating this isse because I want to know if you want this fix so I can create PR.

**Comment by codeguy** [comment]
This is already accomplished with the `debug` application setting. If `debug` is `true`, Slim will rely on the `Slim_Middleware_PrettyExceptions` middleware. If `debug` is `false`, Slim will rely entirely on the custom application error handler.

**Comment by jcubic** [comment]
Ok, that's great,  I'm closing the issue
