### ISSUE TITLE
Wrong rewrite rule for Lighttpd

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#405]
It should be

("(.*)" => "/index.php/$0")

instead of

("^" => "/index.php")

The second one cannot handle GET parameters.

**Comment by codeguy** [comment]
I can do this now. Would you like to send a pull request though? That will give you credit for the fix. Let me know. Be sure to send the pull request to the develop branch.

**Comment by ghost** [comment]
Please just go ahead to fix this without my pull request. Sorry for that.

**Comment by pabloh007** [comment]
I know this  is closed but it helped me out when migrating from a windows version of slim to a linux.

**Comment by tree1891** [comment]
It does not work with lighttpd 1.4.59.

**Comment by gstrauss** [comment]
What does not work on lighttpd 1.4.59?  Please be more specific.
