### ISSUE TITLE
Using PHP 5.4 server

### ISSUE THREAD

**Issue by rahul286** [slimphp/Slim#406]
I am new to Slim and exploring it as of now...

I am wondering if it uses builtin webserver added by PHP5.4

Something Sinatra does!

**Comment by codeguy** [comment]
Never use the built-in PHP server for production. But for development, absolutely. In the same directory as your Slim app's `index.php` file, run this bash command:

```
php -S localhost:4000
```

Open `localhost:4000` in your browser and you'll see your Slim app. That server won't support rewrite rules, so you'll have to include the `/index.php` in your URLs.

**Comment by rahul286** [comment]
Thanks for details. I wanted to use built-in server for development only. :-)

For... 

> That server won't support rewrite rules, so you'll have to include the /index.php in your URLs.

I was thinking about something like this... https://wiki.php.net/rfc/builtinwebserver#router_script

I guess Slim already knows which "URL pattern" will invoke which function. 
So it might do something like "routing" as mentioned at above link.

Idea is to speed-up development further...

**Comment by rahul286** [comment]
Another example - http://silex.sensiolabs.org/doc/web_servers.html#php-5-4
