### ISSUE TITLE
flash() / flashNow() not working in v.1.6.5

### ISSUE THREAD

**Issue by iafan** [slimphp/Slim#409]
Here's a boiled down example:

```
<?php

session_start();

require_once 'Slim/Slim.php';

$app = new Slim();

$app->flash('error', 'later');
$app->flashNow('info', 'now');

$app->run();

var_dump($_SESSION);
```

The $_SESSION has the 'slim.flash' array present, but it's empty. I tried this with secure cookies, tried calling flash() in my own middleware, but the result is the same. I'm running Slim version 1.6.5 and PHP 5.3.3.

**Comment by ziadoz** [comment]
Are you using any the Slim Extra CSRFGuard middleware? It had a bug (which is now fixed) that would cause this to happen (https://github.com/codeguy/Slim-Extras/pull/20).

**Comment by iafan** [comment]
No, I don't. The code above is the full example (pure Slim with no extras).

**Comment by ziadoz** [comment]
I tried your code and you're right it doesn't work (even in 1.6.6). 

Moving the flash calls into a route closure makes `flash()` work correctly, `flashNow()` didn't work at all though.

```
<?php
session_start();

require_once 'Slim/Slim.php';

$app = new Slim();

$app->get('/', function() use ($app) {
    $app->flash('error', 'later');
    $app->flashNow('info', 'now');
});

$app->run();

var_dump($_SESSION);
```

**Comment by iafan** [comment]
I think this can be closed in favor of https://github.com/codeguy/Slim/issues/412
