### ISSUE TITLE
Slim spits out Slim_Exception_Stop exception to the log on redirect

### ISSUE THREAD

**Issue by iafan** [slimphp/Slim#410]
I'm using an authentication middleware, which, in case the user is disallowed to view a resource, just does a redirect to a root URL, like this:

```
if ($user_ok) {
    // do something
    $this->next->call();
} else {
    $app->redirect('/');
}
```

But every time I do the redirect, I see the exception in the log:

```
ERROR - 2012-09-07T01:35:56+04:00 - exception 'Slim_Exception_Stop' in /var/www/myapp/lib/Slim/Slim.php:857
Stack trace:
#0 /var/www/myapp/lib/Slim/Slim.php(877): Slim->stop()
#1 /var/www/myapp/lib/Slim/Slim.php(939): Slim->halt(302)
#2 /var/www/myapp/lib/MyApp/AuthenticationRole.php(94): Slim->redirect('/')
#3 /var/www/myapp/lib/Slim/Middleware/SessionCookie.php(114): MyApp\AuthenticationRole->call()
#4 /var/www/myapp/lib/Slim/Middleware/PrettyExceptions.php(65): Slim_Middleware_SessionCookie->call()
#5 /var/www/myapp/lib/Slim/Slim.php(1094): Slim_Middleware_PrettyExceptions->call()
#6 /var/www/myapp/public/index.php(100): Slim->run()
#7 {main}
```

This happens even if the debug mode is turned off. Is there any reason to pollute the application log with such artificial excpetions, which are used to control the flow of the application? I'd suggest these to be inhibited.

**Comment by codeguy** [comment]
The `redirect` method is intended for use only within route callbacks. If you need to issue a redirect in middleware, you'll want to work with the response object itself. Fetch it with `$this->app->response()`.

**Comment by iafan** [comment]
Hmm. But it works flawlessly there (apart from throwing this exception) — why the need to work with the response object? Just curious.

Also, in Slim docs, there's an authentication example which I tried to follow: 

```
$authenticateForRole = function ( $role = 'member' ) {
return function () use ( $role ) {
$user = User::fetchFromDatabaseSomehow();
if ( $user->belongsToRole($role) === false ) {
    Slim::flash('error', 'Login required');
    Slim::redirect('/login');
}
};
};
$app = new Slim();
$app->get('/foo', $authenticateForRole('admin'), function () {
//Display admin control panel
});
```

Isn't that a middleware that uses the same redirect?

**Comment by iafan** [comment]
And a related question in this case, if I may:

If I do `$app->response()->redirect('/')` in the middleware, this will just set the header but will not stop processing the request (unlike `$app->redirect('/')`, right?. What's the desired method of stopping the processing and finalizing the request then?

**Comment by jcubic** [comment]
I had similar problem with Slim::error in my custom Slim where I handle objects returned by routes as strings, and that object (of Template class) need to call error() so I just catch it 

``` php
try {
} catch (Slim_Exception_Stop $e) { }
```

it seems that the exeptions is use for internal control flow to instant break a loop from nested functions. You can try to just catch it and do nothing.

**Comment by iafan** [comment]
See https://github.com/codeguy/Slim/issues/412
