### ISSUE TITLE
Log Unit Test Fails

### ISSUE THREAD

**Issue by ziadoz** [slimphp/Slim#411]
On the development branch some of the log tests are failing:

```
PHP Fatal error:  Call to undefined method LogTest::expectOutputString() in Slim/tests/LogTest.php on line 77
```

**Comment by codeguy** [comment]
Tests pass here. What version of PHPUnit do you have? Running 3.6.12 here.

**Comment by ziadoz** [comment]
I was running PHPUnit 1.3.2, but after upgrading to 3.6.12 all the tests pass.
