### ISSUE TITLE
unable to get Slim with Composer

### ISSUE THREAD

**Issue by benoitsan** [slimphp/Slim#414]
I'm unable to install Slim 2.0 with Composer

My composer.json

```
{
    "require": {
        "slim/slim": "2.*"
    }
}
```

Error logged in the console when launching `composer install`

```
Loading composer repositories with package information
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package slim/slim 2.* could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
```

**Comment by codeguy** [comment]
Yep. I'm on it. Packagist indicates it knows about latest version, but in reality it downloads older version. Not sure why.

**Comment by benoitsan** [comment]
I think the problem is the message `Your requirements could not be resolved to an installable set of packages.` 

Perhaps it's due to the missing key `minimum-stability`.
[same kind of issue](https://github.com/composer/composer/issues/878)
[an example of composer.json with minimum-stability](https://github.com/symfony/symfony/blob/master/composer.json)

**Comment by codeguy** [comment]
I've added that setting to the composer.json file. Packagist still fails. Will keep trying.

**Comment by codeguy** [comment]
The problem is not isolated to Slim. Follow this issue I've opened for further updates:

https://github.com/composer/composer/issues/1090

**Comment by benoitsan** [comment]
argh, server issue... Wait&see then ;)

**Comment by benoitsan** [comment]
It's fixed.
https://github.com/composer/composer/issues/1090#issuecomment-8402267
