### ISSUE TITLE
No link to the Tender support forum on the Slim website

### ISSUE THREAD

**Issue by benoitsan** [slimphp/Slim#417]
The Tender support forum http://help.slimframework.com is no more linked on the website of Slim http://www.slimframework.com. It's a very good resource, could be good to re-add it.

**Comment by codeguy** [comment]
Good catch. I'll get it re-added.

**Comment by codeguy** [comment]
Done. Added a link to main menu.

**Comment by benoitsan** [comment]
Perfectly placed ;)
