### ISSUE TITLE
Redefined constructor in Slim\Log

### ISSUE THREAD

**Issue by ziadoz** [slimphp/Slim#419]
This error occurs running PHP 5.3.2-1 with `E_ALL | E_STRICT` error reporting. It started happening after the conversion to PSR-0. The class name is now `Log` (in the namespace `Slim`) and it has a method called `log()` (the PHP4 style constructor name). Previously the class was called `Slim_Log` so presumably that's why this error didn't occur before. 

The error message:

```
Strict standards: Redefining already defined constructor for class Slim\Log in /vendor/slim/slim/Slim/Log.php on line 229
```

And the offending function:

```
protected function log($object, $level)
{
    // ...
}
```

**Comment by alessandroraffa** [comment]
Le latest version of Slim, perfectly solves this issue.

**Comment by apmuthu** [comment]
The [v3.x commit](https://github.com/slimphp/Slim/commit/e67d30a47145c02135b866dd7773c40c32640377) solves this issue for higher versions of PHP. For those on lower versions of PHP and using Slim 2.x just change the Set and Log filename and method name as in [this commit](https://github.com/apmuthu/FA24extensions/commit/8724ca8bd2928a6b36b541344345e613e7471d10). The FrontAccounting [forum post](http://frontaccounting.com/punbb/viewtopic.php?pid=29648#p29648) discusses this.
