### ISSUE TITLE
Slim should not manage templates path

### ISSUE THREAD

**Issue by pyrsmk** [slimphp/Slim#422]
I'm trying to make Twig working with Slim, but currently I can't. Twig needs to know the templates path but Slim\View too. This is really redundant and it should be a template engine functionnality, not a view one (maybe I'm wrong, but I only see view objects as template engine wrappers). As an end, Slim\View doesn't want to render the template because it cant' find it if I don't pass the templates path (and if I provide it, Slim\View seems to take priority over my own view, that extends Slim\View, and the template is just displayed as raw... but I think this is another problem...).

**Comment by sirlancelot** [comment]
This is definitely worth more discussion. However, there's already a TwigView class here: https://github.com/codeguy/Slim-Extras/blob/master/Views/Twig.php

**Comment by pyrsmk** [comment]
Nice, I didn't see that there is a Slim-Extras repo. By the way, Twig's now working on my framework, it was because the documentation is not for the 2.0 yet ;)

**Comment by codeguy** [comment]
I'm happy with how rendering is delegated to custom views at the moment. I admit template paths can likely be decoupled from the Slim class and moved into the View classes. Will need to make sure this doesn't break backwards compatibility. Should get to this soon.

**Comment by codeguy** [comment]
So status on this is... I agree with you in theory but any changes now will likely break things. So this will likely wait to the next major point release.

**Comment by codeguy** [comment]
This is addressed in https://github.com/codeguy/Slim/tree/release-2.4.0
