### ISSUE TITLE
More structure thoughts: about flash messages

### ISSUE THREAD

**Issue by pyrsmk** [slimphp/Slim#423]
There's two things to consider:
- flashNow(), flashKeep(), ..., in order to be chainable as well, must return the Slim instance
- to have real independent components, these methods shouldn't be hardcoded into the Slim base class but added by the middleware into a container like `$app->addNewMethod('flashNow',function(){...})`; it's not really well coded, but you see the point; also, we could use a dependency injection container like Pimple or Chernozem, or anything else

Of course, these thoughts could be extended to other components.

**Comment by codeguy** [comment]
I agree. Flash messages will soon be getting an overhaul that will better decouple flash messaging from the Slim object... I already have a developer working on it so look for this within the next point release or two.
