### ISSUE TITLE
Not Respecting X_HTTP_METHOD_OVERRIDE

### ISSUE THREAD

**Issue by earlPeriscopic** [slimphp/Slim#427]
Using Slim 2.0.0 I cannot get the x_http_method_override to work.  I'm using Backbone.emulateHTTP.  I verified it is sending a POST with the header X-HTTP-Method-Override:DELETE.  

``` php
$app->delete('/myroute/:id', 'functionToRun');
```

Returns a 404.  I verified that other routes are working, other POST routes and GET routes to the same location work so I know that's not the issue.  

I'm on a very short timline.  Any idea?  I'm desperate.

**Comment by tyd** [comment]
Do you have the MethodOverride middleware added?

```
$app->add(new Slim\Middleware\MethodOverride());
```

**Comment by codeguy** [comment]
@earlPeriscopic Can you inspect the raw HTTP request and post that here?

@tyd Slim apps have that middleware added by default.

**Comment by earlPeriscopic** [comment]
Request:
POST /project/admin/html/potential/384 HTTP/1.1
Host: localhost
Connection: keep-alive
Content-Length: 0
Origin: http://localhost
X-Requested-With: XMLHttpRequest
X-HTTP-Method-Override: DELETE
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1
Accept: application/json, text/javascript, _/_; q=0.01
Referer: http://localhost/blaine/admin/html/
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8,de;q=0.6
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Cookie: YII_CSRF_TOKEN=975bc28723f7372c45df81d9c52fac950034bf09; 05a80-j283csmkp5_r=0; _chartbeat2=t1sp890cd248ueuv.1346429276440.1346430188015.00000000000001; WibiyaProfile=%7B%22toolbar%22%3A%7B%22stat%22%3A%22Max%22%7D%2C%22apps%22%3A%7B%22openApps%22%3A%7B%7D%7D%2C%22connectUserNetworks%22%3A%5Bnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%5D%7D; PHPSESSID=aa8d99e8b6c27913b9b0c38809b2b01d; SQLiteManager_currentLangue=2

Response:
HTTP/1.1 404 Not Found
Date: Wed, 19 Sep 2012 19:01:15 GMT
Server: Apache/2.2.21 (Unix) mod_ssl/2.2.21 OpenSSL/0.9.8r DAV/2 PHP/5.3.6
Content-Length: 229
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

**Comment by earlPeriscopic** [comment]
@tyd  I did verify the middleware was being loaded properly.

**Comment by earlPeriscopic** [comment]
@codeguy Is that what you were looking for?

**Comment by codeguy** [comment]
Yep. I'll double-check tonight to make sure it works correctly. Right now, make sure this isn't a simpler issue related to routing.

**Comment by earlPeriscopic** [comment]
Thanks.  These are my routes:

``` php
$app->get('/potential', 'getPotentials');
$app->get('/potential/:id',  'getPotential');
//$app->get('/potential/search/:query', 'findByName');
$app->post('/potential', 'addPotential');
//$app->put('/potential/:id', 'updatePotential');
$app->delete('/potential/:id', 'deletePotential');

$app->get('/updatePotential', 'updatePotentials');

$app->post('/tweet', 'addConcreteTweet');
```

The GET and POST routes work.  If I don't set Backbone.emulateHTTP to true I get the 405 error with DELETE which I expect.  The DELETE route setup there is the only one that returns a 404.  Any other ideas on why that route won't work are totally appreciated.  It's my first time using Slim, but I love it.  Used lot's of other frameworks and none that I've used are so lightweight and focussed.  

Thanks.

**Comment by codeguy** [comment]
Your HTTP request for `POST /project/admin/html/potential/384` does not match any of your application's routes.

**Comment by earlPeriscopic** [comment]
That's why I sent this header: 
X-HTTP-Method-Override: DELETE

Shouldn't that reroute it to $app->delete('/potential/:id')?

**Comment by codeguy** [comment]
Your request URI still must match one of your app's routes. That header only affects the request method, not the URI.

**Comment by codeguy** [comment]
Is your Slim app installed in a subdirectory?

**Comment by earlPeriscopic** [comment]
Yes in html/api

So how do I write that route correctly?  I tried $app->post instead of delete but no luck there either.

**Comment by earlPeriscopic** [comment]
... ... ...
Ok, feeling sheepish.  It was user error, but I thought I did something wrong on the Slim side.  

NOPE!  It was the Backbone portion.  I had my Collection looking at 'api/potential' but my model looking at 'potential'.  Full fetch of the Collection worked great.  The model level had the issue.  

Your question about the subdirectory helped me figure it out though.  I looked at the full path being sent by the header and realized a directory was missing.  I fixed that and everything works!

Thanks for the help, and for responding so fast.  Sorry to bother you with this since Slim was working properly.

**Comment by codeguy** [comment]
No worries. Glad you got it fixed.

**Comment by earlPeriscopic** [comment]
Not sure if this helps, but the Blanket 405 error with DELETE was what threw me off.  For some reason I assumed that I had the path right since I didn't get back a 404.  Not sure if you can control that or if Apache did that though.
