### ISSUE TITLE
Make documentation easier to navigate

### ISSUE THREAD

**Issue by ziadoz** [slimphp/Slim#429]
The old documentation, being all on one page, was easy to search and browse; the new documentation (which looks great btw) however is a bit of a pain. It would be nice if there was a way to move between the next and previous sections, as well as some kind of search functionality.

**Comment by nope** [comment]
I think is a good idea make a downlodable pdf of the documentation for offline reading. ;)

**Comment by ivannovak** [comment]
Yes please.  Whether it be a search function or back to one page - this would make all the difference in the world.

**Comment by codeguy** [comment]
I'm working on this now and will be moving this from GitHub Pages (as it is now) to a one-page Statamic website.

**Comment by Semogj** [comment]
I agree on the suggestion about making documentation available for download as html or pdf. :)

**Comment by codeguy** [comment]
I've reverted the documentation back to one page. You can now easily search it with the browser's built-in Cmd+F search.

http://docs.slimframework.com/

**Comment by ivannovak** [comment]
Thank you
