### ISSUE TITLE
proposal for rest/crud route in one line

### ISSUE THREAD

**Issue by nope** [slimphp/Slim#430]
for future develop a one ine rest/crud route like:

``` php
$app->rest('/:entity/',function (){
     //code here
});

//or 
$app->crud('/:entity/',function (){
     //code here
});

```

this route respond to:

get /:entity ---list all entity
get /:entity/add ---- display form to add entity
post /:entity/add/ ---- add entity
put /:entity/:id ---- update entity id
delete /:entity/id ----- delete entity id

it's just an idea.

**Comment by thomas-0816** [comment]
// or
$app->any('/:entity(/:id_or_op)',function($http_method, $entity, $id_or_op=null){
     //code here
});

// equal to
$app->map('/:entity(/:id_or_op)',function($entity, $id_or_op=null) use ($app){
    $method = $app->request()->getMethod();
     //code here
});

**Comment by tuupola** [comment]
I think it is cleaner to have separate handler for each rest method. This way amount of code in each handler is small. With suggested catchall route there is one handler but total amount of code is same. Only difference is that code for each method is separated with if sentence.

I do see usage cases for `$app->any()` though. Useful when you cannot be sure which http verb will be used.

**Comment by nope** [comment]
use option wildcard '(:item+)' and test it to catch the rigth route like code belove.

``` php
//i use this one
$app->map('/entity(/:item+)', function ($item = null) use ($app) {

//and test the request via if like

if($app->request()->isGet() and !$item)

//or

if ($app->request()->isPut() and $item[0] == 'update' and $item[1] != null) {

```

**Comment by silentworks** [comment]
Hey guys this can be accomplished by using map, its is a few more lines of code than one but it works for this really well.

``` php
$app->map('/entity(:item+)', function ($item = null) use ($app) {

})->via('GET', 'POST', 'PUT', 'DELETE');
```

**Comment by codeguy** [comment]
Short term, I will likely add a `$app->any()` method that will map the given resource URI to all HTTP methods. Long term, I will likely look at implementing resource controllers in separate standalone classes. I'm not entirely sure on the exact implementation, but that's something that can be fleshed out in the support forums.
