### ISSUE TITLE
Problem with routes ending in "S" (or even "s")

### ISSUE THREAD

**Issue by barlowm** [slimphp/Slim#437]
I'm just starting to investigate slim for a project of mine (and so far it looks REALLY great!), but seem to have one "small" issue.

I'm running on my local environment (Windows) using Apache (2.2.14) and PHP Version 5.3.10.

I've got a couple of example routes set up but when I tried to create a route ending in "s" it failed...

Here's my basic (no brainer) code:

``` php
// GET routes
$app->get('/', function () {
    echo "ERROR: Service Call Root. No Service Call Specified";
});
$app->get('/FooBar', function () {
    echo 'This is the FooBar route';
});
$app->get('/patient', function () {
    echo 'This is the Patient route';
});
$app->get('/patients', function () {
    echo 'This is the Patients route';
});
```

Here's the results of my calling the individual routes:

``` route
http://localhost/Dev/Slim/

ERROR: Service Call Root. No Service Call Specified
```

``` route
http://localhost/Dev/Slim/FooBar
This is the FooBar route
```

``` route
http://localhost/Dev/Slim/patient
This is the Patient route
```

``` route
http://localhost/Dev/Slim/patients

404 Error - 
Not Found

The requested URL /Dev/Slim/patients was not found on this server.
```

Notice that "patient" worked (and even "patientX" works) but not "patients" (even tried it with a capital "S", same results).

Am I missing something obvious or is this a bug?

Thanks
MikeB

**Comment by thomas-0816** [comment]
Hello,

"patients" works for me, tested with PHP 5.4.5 as Web-Server, Slim 2.1.0 (composer) and Win7-64 SP1.

bye
Thomas

**Comment by barlowm** [comment]
Hmmm thanks for the quick response Thomas, let me see if upgrading to PHP
5.4.5 resolves the problem (I've tried various things with the code base I
have but none of them seems to resolve this particular issue).

Mike Barlow

**Comment by barlowm** [comment]
Ok now this is just way too weird...

I've upgraded my local server to PHP Version 5.4.7, everything works as
before...
HOWEVER... here's the problem I'm still having...

http://localhost/Dev/Slim/books works (so it's not as simple as a "s" on
the end.
http://localhost/Dev/Slim/patient works
http://localhost/Dev/Slim/patiens works (again it's not the "s" problem)
http://localhost/Dev/Slim/patientt works (so it's not a specific URI length
problem)
http://localhost/Dev/Slim/patientts works (at which point I throw up my
hands and say "I give up" ;))
http://localhost/Dev/Slim/patients1 works (again it's not a length problem)

But there's no way I can find to get
http://localhost/Dev/Slim/patients http://localhost/Dev/Slim/patients1 to
work!!!

So I know it's not likely it's anything wrong with the Slim framework, but
it's driving me batty here, especially since it's such a simple little
thing! :)

Any suggestions on how I might go about troubleshooting this? And it's not
as simple as a typo issue (I did think of that and did a copy/paste of the
URI several times and simply can not get "patients" to work no matter what
case (or mixed cAsE) I use.

TIA
Mike Barlow

**Comment by tyd** [comment]
@BarlowMW Try adding a trailing slash to your routes

**Comment by tyd** [comment]
@BarlowMW actually, can you explain what you are trying to accomplish? 

Do you want the route '/patients' to match against 'http://localhost/Dev/Slim/patients1' and 'http://localhost/Dev/Slim/patients2'  etc?

**Comment by barlowm** [comment]
_sigh_ interesting suggestion (I read the thread about "trailing slashes"
and how to eliminate them so I hadn't thought of that), but alas no luck
with "/patients/" either (which is interesting because "/patients1" DOES
work). Looks like I may have to simply resort to another URI, but it's just
frustating more than anything else!!!

Thanks
Mike Barlow

**Comment by barlowm** [comment]
Nope, I'm trying to use the URI "'http://localhost/Dev/Slim/patients" to
retrieve a list of patients in a medical record system.
I've just been trying variations on that theme to find another variant
which does NOT work, simply to assist in troubleshooting.

Mike Barlow

**Comment by bbaisley** [comment]
Almost seems like there is word stemming going on. But I can't imagine where that would be happening. Although stemming does explain the behavior you are seeing.

-Brent Baisley

**Comment by barlowm** [comment]
Well what's even weirder is that, after porting all the code from my local
(windows) machine up to a hosted linux site with NO Code changes, it works
perfectly (but ONLY on my ISP Hosted site, not my local site).

So since it's something, that's obviously, very specific to my local
machine it's now a non issue.

Thanks for the help.
Mike Barlow

**Comment by silentworks** [comment]
Guys if this is not a actual Slim issue please take it over to the forum instead. http://help.slimframework.com/

**Comment by bibob-zz** [comment]
I had the same problem today when all of a sudden GET '/tests' failed to work, POST '/tests' did work. After investigation, I found out it's the problem with browser cache. Clear my browser cache and things are back to normal :)

**Comment by barlowm** [comment]
Hmmm interesting, although that didn't solve my problem. Still have it on my local environment, but since it works on my hosted site, I'm just going to leave it as one of those "Mysteries" of the computer world :)

**Comment by lplume** [comment]
could you please take a look at this thread
http://help.slimframework.com/discussions/problems/979-trailing-slash

**Comment by codeguy** [comment]
@barlowm I'm not able to duplicate the issue here (Mac/Apache/PHP 5.4.3). That being said, I don't doubt that you're seeing an issue. I'm wondering if something is happening to the request URI between your web server and PHP. Can you `var_dump($_SERVER)` before you instantiate Slim and see if the request URI is what you expect?

**Comment by codeguy** [comment]
Closing this out. Please move this to a new topic at http://help.slimframework.com/ and I'll investigate further there.
