### ISSUE TITLE
Custom error handler does not work

### ISSUE THREAD

**Issue by dannykopping** [slimphp/Slim#439]
In composer.json:

``` json
{
      "require": {
        "slim/slim": "2.*"
       }
}
```

``` php
    require_once "vendor/autoload.php";

    use Slim\Slim;
    $app = new Slim();

    $app->error(function (\Exception $e) use ($app)
    {
        $app->halt(500, "error");
    });

    $app->notFound(function () use ($app)
    {
        $app->halt(404, "not found");
    });

    $app->get("/", function ()
    {
        throw new Exception("e");
    });

    // run Slim!
    $app->run();
```

When navigation to `/`, the `PrettyExceptions` middleware is hit first (before the custom error handler) and as such produces HTML output instead of halting with an error like the `notFound` handler does.

**Comment by dannykopping** [comment]
Sorry, didn't RTFM well enough I guess.
How would one implement a custom error handler when debugging is turned on?

**Comment by tyd** [comment]
Probably get more help with that question over at http://help.slimframework.com/discussions

**Comment by codeguy** [comment]
I guess I'm not too clear on why you need this or what you are trying to do. Please open a discussion on the forum if you haven't already and we can discuss.
