### ISSUE TITLE
Something's wrong with Slim::halt()?

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#44]
I'm using one line of Code which looks like this:
`$link = mysql_connect(Slim::config('mysqlserver'), Slim::config('mysqluser'), Slim::config('mysqlpassword')) or Slim::halt(500, 'Cannot Connect to Database Server.');`

Now my MySQL Server is not running currently. So it should raise an error 500 containing my Message. But this does not happen.

Instead I get the following: `Fatal error: Exception thrown without a stack frame in Unknown on line 0`

When starting my MySQL Server the error is gone. So my code should actually be fine.

I'm running PHP 5.3.3 as CGI.

**Comment by codeguy** [comment]
Slim::halt() should only be called form within a Slim route callback. If you are using this code outside of a route callback, you should use:

```
mysql_connect(...) or trigger_error('Error message', Slim::ERROR);
```

**Comment by hexa2k9** [comment]
This is basically generating the same Error.

Setting Config 'debug' to true gives me a more detailed Error (as expected), but still no custom Message.

**Comment by codeguy** [comment]
Can you email me your entire script? It will help me diagnose this issue in context.

**Comment by codeguy** [comment]
Re-opening. The default error handler incorrectly depends on Slim::halt, which itself throws an Exception. This is a bug and I'll fix this tonight.

**Comment by codeguy** [comment]
I've just pushed updated code to the master repo. I've made some fairly major changes affecting how Slim responds to errors and exceptions. Many of Slim's internal functions (notFound(), error(), redirect(), etc.) now rely on Slim::halt to send appropriate responses. As a result, however, you should now be able to call Slim::error, Slim::notFound, trigger_error(), or Slim::halt inside OR outside of a route callback and Slim will function as expected. The Slim interface has not changed, so you won't need to update any of your code. Give this a go and let me know if it resolves your issues. Closing this out for now, but let me know if there is still a problem.

**Comment by hexa2k9** [comment]
Jepp. Reverted to my original bootstrap.php (without that workaround I've written about yesterday) and now it works as expected. No more creepy errormessage from PHP.
