### ISSUE TITLE
Invalid redirect headers

### ISSUE THREAD

**Issue by pyrsmk** [slimphp/Slim#446]
It seems that the way that Slim handles redirections is quite unstable. On my apache server, it works like a charm, but on a distant host it doesn't. I think it comes from the PrettyExceptions middleware that overwrites response 302 status by a 500 one.

Then, currently, I fixed that behavior with:

```
public function call()
{
    try {
        $this->next->call();
    } catch (\Slim\Exception\Stop $e) {
    } catch (\Exception $e) {
        $env = $this->app->environment();
        $env['slim.log']->error($e);
        $this->app->contentType('text/html');
        $this->app->response()->status(500);
        $this->app->response()->body($this->renderBody($env, $e));
    }
}
```

I don't think that is a clean fix because I'm not used to Slim internals. Any thoughts?

**Comment by codeguy** [comment]
Hmm. I am not seeing any issues with this. Please open a thread at http://help.slimframework.com/ and post example code and information about your web server setup so I can troubleshoot further. Will open a new issue for this if necessary when we narrow down the problem.

**Comment by pyrsmk** [comment]
In fact, this is not my own server, thus I can't access to the apache configuration. Anyway, a 500 HTTP response is not valid for a redirect request, it should be a 302, but PrettyExceptions overwrite this behavior. I think it may crash with some weird apache configuration or other http servers.

Tell me if I'm wrong and didn't understand your code well, but the 302 response shouldn't be overwritten at all.

**Comment by inabeo** [comment]
Came across something similar in the last couple of days -
I traced the issue to not having the date.timezone variable set in the php.ini file.

Once this was entered everything work ok - hope this helps.
