### ISSUE TITLE
No hook before render

### ISSUE THREAD

**Issue by natestarner** [slimphp/Slim#449]
It would be very nice to have a "default hook" that is applied before the render function.  This would allow variables that will be accessed by the view to be manipulated by the controller without having to pass it on every render call.

**Comment by codeguy** [comment]
You can do this already in the `slim.before` and `slim.before.dispatch` hooks. In either of these hooks' callbacks, fetch the View object and use `appendData`.

**Comment by natestarner** [comment]
Thank you for your response.  Here is a brief example of my use case:

$_SESSION["first_name"] = "Nate";

$app->get('/', function() use ($some_var) 
{
$_SESSION["first_name"] = "Mike";
$app->render('a_view.php');
});

$app->hook('slim.before', function () use ($app,$twig)
{
$twig->addGlobal("first_name",$_SESSION["first_name"]);
});

When I output "first_name" in my twig view, it will still read "Nate", not "Mike" as I would want it to.
