### ISSUE TITLE
Installing with composer

### ISSUE THREAD

**Issue by lkorth** [slimphp/Slim#457]
I'm new to composer and I seem to be getting the following error with 2.1.0 and 2.0.0. Anyone else having this problem? 

```
[Composer\Downloader\TransportException]
The "http://nodeload.github.com/codeguy/Slim/zipball/2.1.0" file could not
be downloaded (HTTP/1.1 404 Not Found)
```

Going to http://nodeload.github.com/codeguy/Slim/zipball/2.1.0 in my browser is also a 404, but http://github.com/codeguy/Slim/zipball/2.1.0 is not. Is there a config change I missed?

**Comment by codeguy** [comment]
Will investigate. Nothing has changed on our end, so it's likely something with Packagist.

**Comment by codeguy** [comment]
I was able to install Slim and Slim-Extras with composer as expected. Are you still having this issue?

**Comment by lkorth** [comment]
I am, my composer.json is just 

```
{
    "require": {
        "slim/slim": "2.*"
    }
}
```

I did a clean install of composer and am running the composer install command

**Comment by lkorth** [comment]
This only seems to be an issue on Windows. 

I was able to get it to work with "slim/slim": "dev-master" though.
