### ISSUE TITLE
How to access $_SESSION from Twig template in Slim 1.6.7

### ISSUE THREAD

**Issue by jhrmnn** [slimphp/Slim#458]
I need to access session variable from the Twig template. I've tried {{ session.<variable> }}, but that doesn't work. If it's not accessible, is there any other way than to pass the session variable to every route?

EDIT: I've solved the problem by adding "$this->data['session'] = $_SESSION;" to TwigView->render(), but I still wonder, if there is not a neater solution. Especially when this seems to be quite a basic feature.

**Comment by wieczo** [comment]
You could write a view extension if you have to use $_SESSION often.
Examples for Twig Extensions are in Slim Extras.

**Comment by silentworks** [comment]
Hi @azag0 you can use a twig global. http://help.slimframework.com/kb/views/using-twig-functions-inside-of-slim

Close this ticket out please.
