### ISSUE TITLE
A little more magic

### ISSUE THREAD

**Issue by anho** [slimphp/Slim#459]
I would really like to see a little more magic in Slim. Specifically something like autodiscovery of classes, which would reflect the class and then create some corresponding routes for it.

**Comment by moiseevigor** [comment]
+1 would be great to have this one!

**Comment by tuupola** [comment]
-1 Too much magic is exactly what is wrong with Rails. Having as little magic as possible is what make Sinatra great. If there will be magic make it as optional plugin.

**Comment by bbaisley** [comment]
-1 Too much magic means less transparent and obvious functionality. When something isn't working, you need to debug magic. I agree with tuupola, make it an optional plugin.

**Comment by anho** [comment]
I really think of it as an extra so it may reside in the repo Slim-Extras. Maybe with different strategies to generate the routes from a class and/or method-name. But when using Slim in any medium sized project this would definitely help (me) to get it rapidly on a solid ground.
Currently i do search for a framework that helps me to migrate a legacy "rest" application and having such a feature would help a lot.

**Comment by moiseevigor** [comment]
Just found: https://github.com/dannykopping/spore/
and it's doing quite a lot of magic!

**Comment by anho** [comment]
Promising :)
