### ISSUE TITLE
Warning: strpos(): Empty delimiter in <ROOT>/vendor/slim/slim/Slim/Environment.php on line 143

### ISSUE THREAD

**Issue by brantmessenger** [slimphp/Slim#460]
require realpath('../vendor/autoload.php');

$app = new Slim\Slim();

$app->get('/hello', function() {
            echo "Welcome!";
        });

$app->get('/', function() {
            echo 'Index';
        });

$app->run();

...Looks like the server variable $_SERVER['SCRIPT_NAME'] is empty.

**Comment by brantmessenger** [comment]
Possible solution...

if(strpos($_SERVER['REQUEST_URI'], (empty($_SERVER['SCRIPT_NAME'])) ? $_SERVER['PHP_SELF'] : $_SERVER['SCRIPT_NAME'] ) === 0) {

**Comment by codeguy** [comment]
What web server are you using?

**Comment by lucascosta** [comment]
Hello, I'm using Slim on HipHop PHP (RedBull) and I had the same issue with URL rewriting. I used brantmessenger's solution and it worked. Could it be merged to the code? Here's my configuration:

```
VirtualHost {
  * {
    Pattern = .*
    RewriteRules {
      * {
        pattern = ^/(.*)$
        to = /index.php/$1
      }
    }
  }
}
```

**Comment by brantmessenger** [comment]
Maybe codeguy will open this back up?

**Comment by codeguy** [comment]
Thanks for the info. Will try to get a fix into a point release as soon as I can, definitely in a 2.x release.

**Comment by lucascosta** [comment]
Cool!

**Comment by codeguy** [comment]
I've been experimenting with Apache, nginx, and hhvm today. This snippet of code seems to work well in all three, with or (for Apache) without rewriting.

```
$scriptName = $_SERVER['SCRIPT_NAME']; // <-- "/physical/index.php"
$requestUri = $_SERVER['REQUEST_URI']; // <-- "/physical/index.php/virtual?abc=123" or "/physical/virtual?abc=123"
$queryString = isset($_SERVER['QUERY_STRING']) ? $_SERVER['QUERY_STRING'] : ''; // <-- "abc=123"
if (strpos($requestUri, $scriptName) === false) {
    // With rewriting
    $settings['SCRIPT_NAME'] = str_replace('/' . basename($scriptName), '', $scriptName);
} else {
    // Without rewriting
    $settings['SCRIPT_NAME'] = $scriptName;
}
$settings['PATH_INFO'] = '/' . ltrim(str_replace(array($settings['SCRIPT_NAME'], '?' . $queryString), '', $requestUri), '/');
```

I like this code because it is much simpler than Slim's current way of parsing the request url. Can you all verify? I was intending to use this code in 3.0, but if it is stable I'll get it into the next 2.x point release.

**Comment by codeguy** [comment]
I lied, sort of. It appears that hhvm does not set the SCRIPT_NAME server variable correctly. For the above code to work, you will need to add this block to your hhvm configuration virtual host block:

```
ServerVariables {
    SCRIPT_NAME = /index.php
}
```

And that works.

**Comment by codeguy** [comment]
Or we could derive the proper script name from other available server variables like this:

```
str_replace($_SERVER['DOCUMENT_ROOT'], '', $_SERVER['SCRIPT_FILENAME'])
```

**Comment by brantmessenger** [comment]
Why would we do this after manually setting some of those vars. Seems like you'd want to do this before the manual code.

Line 166 : $headers = \Slim\Http\Headers::extract($_SERVER);
            foreach ($headers as $key => $value) {
                $env[$key] = $value;
            }

Looks like a possibility to overwrite what we just did. I would do the above before manually setting anything.

**Comment by lucascosta** [comment]
Setting the SCRIPT_NAME variable through hhvm configuration does the trick without messing with any other code. The warning stops, thanks!

**Comment by codeguy** [comment]
This is resolved in the release-2.3.3 branch and will be resolved in the develop branch in a few days. I've talked with the hhvm devs, and they are aware that the SCRIPT_NAME server var is set incorrectly... that will be fixed in a future hhvm point release.

**Comment by unframework** [comment]
In Slim v2.4.2 this issue still shows up for me when using an Apache rewrite rule. I know there are a couple ways to resolve this, but fundamentally the framework should be resilient to the empty `SCRIPT_NAME` possibility, or at least throw an informative error message. If I submit a pull request, would this have a chance to be looked at?

**Comment by MarcoMatarazzo** [comment]
Under Apache, the problem seems to happen when the rewrite is in the vhost configuration instead of being in the .htaccess file. The Rewrite engine does two different things depending on the context, and this is often overlooked. Hint: the PT flag seems to solve the problem. 

You may want to look here for some more information, and maybe add something to the configuration page: http://chapter31.com/2013/06/21/php-script-name-returning-empty-string/
