### ISSUE TITLE
configureMode doesn't work with some settings

### ISSUE THREAD

**Issue by xintron** [slimphp/Slim#462]
The problem with configureMode is that it doesn't work for some setups. Having a testsuite and doing something like:

``` php
$_ENV['testing'];
$app = new \Slim\Slim();
$app->configureMode('testing', function() use ($app) {
    $app->config(array(
        'log.enable' => false
    ));
});
```

That will never work since the log-instance is already initiated and no update for the log-level is done. As I see it either the setter of the Log-instance needs to be invoked or (perhaps a simpler solution) the Log-instance always reads the configuration-setting for enable/level/writer etc.

**Comment by codeguy** [comment]
This is addressed in the develop branch.
