### ISSUE TITLE
how do i post to external link from slim with post params.?

### ISSUE THREAD

**Issue by lalith-b** [slimphp/Slim#470]
Is it possible to post to external link using Slim ?

I have a link like http://www.example.com which takes post params I need to post from slim and get a response..! Is this scenario possible. ? the equalent PHP curl option is possible.

**Comment by adriencarbonne** [comment]
In my humble opinion this is not Slim-related.
If you want to make a HTTP POST request and get its response, you should indeed use CURL.

**Comment by codeguy** [comment]
There are plenty of third-party libs that will do this... look at Guzzle or Resty.

http://guzzlephp.org/
https://github.com/fictivekin/resty.php

Both can be integrated with your Slim app.
