### ISSUE TITLE
PrettyExceptions Middleware and Ajax don't mix well

### ISSUE THREAD

**Issue by paulyg** [slimphp/Slim#472]
A common pattern in my ajax heavy apps is on an error to show the text/html returned by the server in an error notice on the client side. My error handler function, registered via `\Slim\Slim::error()`contains logic like this.

``` php
if ($app->request()->isXhr()) {
    // send a string or JSON response
} else {
    // send a full HTML response
}
```

However when my app throws an exception it is caught and handled by the `\Slim\Middleware\PrettyExceptions` class and does not go through the above logic. `\Slim\Middleware\PrettyExceptions` renders out a full HTML page with some styles embedded in the head. When I inject that response into my error notice jQuery and the browser handle the fact that the response is a full HMTL document gracefully. But because of the styles my CSS goes all funny until I dismiss the notice. There are several ways in which this could be improved, so I wanted to get feedback on which one you favored before I go preparing a pull request.
1. Make `\Slim\Middleware\PrettyExceptions` use the `$app->error()` handler internally.
2. Namespace all of the CSS classes in the error response so they don't trample all over the default CSS. Also this way I could use jQuery to yank out the contents of the error from the full HTML page by doing `$(xhr.reponseText).find('body.slimerror')` or similar.
3. Put a check for `$app->request()->isXhr()` inside like my example above.
4. Allow a user defined middleware to be substituted for `\Slim\Middleware\PrettyExceptions` inside of `\Slim\Slim::call()`.

**Comment by anho** [comment]
Definitely +1 for this proposal.

**Comment by honzabrecka** [comment]
+1
I'm for solution 1. or 4.

**Comment by dinacel** [comment]
+1 too, solution 1 seems to be the best.

**Comment by smagch** [comment]
At the moment, Slim doesn't allow Middlewares to stop application. Let's say there is a `MyMiddleware` that can possibly throw a exception. And you want to stop app with a custom status code and a body.

``` php
class MyMiddleware extends \Slim\Middleware
{
    public function call()
    {
        try {
            // something could possibly go wrong
        } catch (\Exception $e) {
            $app = \Slim\Slim::getInstance();
            // I know 10000 is invalid status code. It's just a example.
            $app->halt(10000, 'Hello. Nice to meet you');
            return;
        }
        $this->next->call();
    }
}

$app = new \Slim\Slim();
$app->add(new MyMiddleware());
$app->run();
```

But the response is always 500 Internal Server Error because `\Slim\PrettyException` catches `\Slim\Exception\Stop`. So I think it would be nice to move [this top level try catch](/codeguy/Slim/blob/2b54c9b30e2705482dd3ccee1b47b36e110ba9bb/Slim/Slim.php#L1210-L1249) to [inside run()](https://github.com/codeguy/Slim/blob/2b54c9b30e2705482dd3ccee1b47b36e110ba9bb/Slim/Slim.php#L1173-L1175) in order to allow Middlewares to stop application.

**Comment by codeguy** [comment]
@paulyg Where in your Slim app is the exception thrown? Is it thrown from within a route callback? Or from one of your middlewares?

**Comment by paulyg** [comment]
From within a route callback.

I started working on a pull request to make the the outermost, exception handling middleware pluggable, with '''Slim\Middleware\PrettyExceptions''' the default implementation. Actually what I need to do is write tests for it.
