### ISSUE TITLE
SessionCookie middleware is a huge security risk

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#479]
The concept of session cookie is, that you store the session data in the server where it is secure, and the application provides only a unique id to the client, so the client cannot modify the session data; for example the permissions stored in it. Storing the session data in an encrypred cookie is a very very bad idea...

**Comment by Cyrille37** [comment]
I think so. Sensible data should not be stored in a poor encrypted string at client side.

**Comment by adriencarbonne** [comment]
First, Slim does not force you to use SessionCookie. Second, why do you think this cookie is poorly encrypted?

**Comment by ghost** [comment]
Yepp, Slim does not force me, but there are no alternative Middlewares in the lib, and this is the second worst solution to handle session data. (The worst is non encrypted cookie on client side...) So I think this SessionCookie Middleware is a bad idea, and should not exist, because not everybody realizes the risk of this solution.

**Comment by dinacel** [comment]
Not everybody is able to decrypt an encrypted cookie, I won't use this middleware, but we can't say that there's a huge risk. It could be a risk to take in consideration for a bank site, but I don't think they will use Slim... neither PHP (it's not a disguise criticism).

**Comment by tuupola** [comment]
It is just a documentation issue. Documentation should mention it is probably bad idea to store sensitive data in SessionCookie.

**Comment by ghost** [comment]
@tuupola I agree, at least documentation should mention it.

**Comment by silentworks** [comment]
@tuupola we will take this into consideration and add some info in the documentation around this.

**Comment by codeguy** [comment]
Documentation will be updated to explain the risk of using client-side storage. Also, a future point release will add a new way to activate and use sessions (with a native or custom save handler) to avoid relying on client-side storage.

**Comment by ghost** [comment]
Thank you! :-)
