### ISSUE TITLE
functionnality proposal in Slim->config public function

### ISSUE THREAD

**Issue by toto83** [slimphp/Slim#480]
For my purpose, i have added a new functionnality. 
In the Slim class (see Slim/Slim.php), i have modified the public function config.
When $name is '*', and $value is null, config return the settings array instead of an item.

Added in the Slim->config phpDoc header
     \* Added by toto83 (2/02/2013)
     \* If only one argument is specified and that argument is `*`, the settings
     \* array is returned.
     *
The function Slim->config become:
    public function config($name, $value = null)
    {
        if (func_num_args() === 1) {
            if (is_array($name)) {
                $this->settings = array_merge($this->settings, $name);
            } else {
                if ($name === '*') {
                    return $this->settings;
                } else {
                    return isset($this->settings[$name]) ? $this->settings[$name] : null;
                }
            }
        } else {
            $this->settings[$name] = $value;
        }
    }

Sorry for my poor english

**Comment by codeguy** [comment]
I'd prefer to separate this into two new methods: `getConfig($name = null)` and `setConfig($name, $value)`. Currently, there is the one `config()` method that acts as both a getter and a setter. But I'd like to separate this out. Would you be interested in leading this up?

**Comment by codeguy** [comment]
Configuration will be changing interfaces in 3.0 release making this unnecessary.
