### ISSUE TITLE
"$allGetVars = $req->get()" reveals amp; in slim.request.query_hash

### ISSUE THREAD

**Issue by goldsky** [slimphp/Slim#481]
Hi,
I'm just a noob who's trying to use this library.
I'm using proxy that control all ajaxs request for my script.
So for this case, I place the slim's index.php inside a subfolder, and request it using query variable.

**http://localhost/thesite.org/www/assets/components/chat/connectors/w.php?action=web/rest/message/index&path=hello&channel=1**

It returns as expected if I test like this

``` php
$app->get('/', function () {
            echo 'slim root';
        });
```

But apparently not for the query

``` php
// Get request object
$req = $app->request();

//GET variable
$paramValue = $req->get('path');
echo '$paramValue=' . $paramValue;
```

Then I figured out that the later queries were appended with amp; (not &amp;amp;)

``` php
$req = $app->request();
$allGetVars = $req->get();
echo '<pre>';
print_r($allGetVars);
```

output

``` html
<pre>Array
(
    [action] => web/rest/message/index
    [amp;path] => hello
    [amp;channel] => 1
)
```

If I tested using this

``` php
echo '<pre>';
print_r($_GET);
echo '</pre>';
```

It returns as expected

``` html
<pre>Array
(
    [action] => web/rest/message/index
    [path] => hello
    [channel] => 1
)
```

Can anyone point me out what am I missing here?

TIA,
Rico

**Comment by goldsky** [comment]
I ended up by

``` php
$_SERVER['QUERY_STRING'] = str_replace('&amp;', '&', $_SERVER['QUERY_STRING']);
```

right before calling the Slim class.

**Comment by codeguy** [comment]
I haven't been able to duplicate this. If you want to post some example code to the support forum I will be happy to look over it for you.

**Comment by mewejo** [comment]
I am seeing the exact same thing - The code he supplied is more than enough to replicate the issue. Happy to assist with further testing for you @codeguy
