### ISSUE TITLE
429 Too Many Requests not supported

### ISSUE THREAD

**Issue by gcatlin** [slimphp/Slim#482]
Slim doesn't gracefully handle HTTP status that are not predefined in `Response`. I have 2 requests:
- Add support for the "429 Too Many Requests" status (which is commonly used to convey that the client is being rate limited)
- Modify Slim such that it can more gracefully handle HTTP status that are not predefined in `Response`; perhaps as an optional second parameter to `Response::status()`

Let me know if these should be separate issues.

I am happy to fulfill both of these requests, but I wanted to make sure @codeguy consider's them worthwhile first.

**Comment by xintron** [comment]
One thing to notice is that some web servers don't support the newer status codes. E.g. nginx will take the 429 response and turn it into 200 instead. I would love to see the support in Slim though but it might be worth mentioning in the documentation while this is implemented that some unexpected results might come out of this based on the web server used.

**Comment by codeguy** [comment]
@gcatlin This sounds fine. Send PR(s) when ready. Be sure you work from the latest code in the develop branch.
