### ISSUE TITLE
Status 405 if route matches but not HTTP method

### ISSUE THREAD

**Issue by xintron** [slimphp/Slim#484]
When a route matches but the HTTP-method isn't listed it makes sense to send 405 instead of 404 (which was changed in 075eb7e92). Since `Router->routes` is protected and `getNamedRoutes()` only returns those routes that you have named it's very hard to traverse and manually send 405 by overriding the `notFound` callback (the one solution is to try all HTTP methods and hammer `getMatchedRoutes()` with the same URI and different methods).

The easiest way would be to have a getter method for Router->routes but it makes sense to have this handled buy the default notFound-callback as well.

**Comment by codeguy** [comment]
This was removed to simplify things. I did not want to add yet another function to register a handler for 405 responses (like we have now for Not Found and Error responses). I do intend to improve this in the future, but for now it's limited to 404 and 500 handlers.

**Comment by xintron** [comment]
One way of solving this is to add the possibility to set a custom 405 error
handler and when checking against the HTTP-methods a check is made to see if a
error handler has been set, if not run the default notFound-handler. That way
it you can set a custom handler for 405 but if you don't want to bother you
only need to set your own 404 handler and also get all 405's to that
notFound-callback.
