### ISSUE TITLE
Run Slim from command line?

### ISSUE THREAD

**Issue by adamsch1** [slimphp/Slim#486]
Anyway to run the slim setup from the commandilne?  I have backend scripts  I woudl like to run and inherit everything, DB, logging etc.

Didn't see anything in the docs so I thought I would ask here if it's a planned feature or has been considered.  Open to alternatives of course.

Shane

**Comment by pgasiorowski** [comment]
I've just added a pull request for this. https://github.com/codeguy/Slim/pull/487
Hope it helps
