### ISSUE TITLE
Can't assign conditions for wildcard route parameters

### ISSUE THREAD

**Issue by lucasrubini** [slimphp/Slim#491]
Let's say you have the following route:

``` php
$app->get('/hello/:name+',
    function ($name) {
        echo "Hello, $name[0] $name[1]!";
    })
    ->conditions(array('name' => '[a-zA-Z]+'));
```

That condition overwrites the default behavior of a wildcard route parameter and Slim won't capture more than one URI segment. Is that an issue?

**Comment by codeguy** [comment]
Seems like it. I can look into this or you can send over a fix... let me know which you prefer so we don't duplicate effort.

**Comment by lucasrubini** [comment]
I'm pretty sure your solution will be more elegant than mine, since I don't code that much...  thanks!

**Comment by daviddeutsch** [comment]
Any new info on this? If there is anything I can do to help out, let me know.

**Comment by silentworks** [comment]
@lucasrubini is this issue still ongoing? also is it still the same in latest version of Slim?

**Comment by silentworks** [comment]
Closing this one off, please reopen if you find this issue still persists in the latest version of Slim.
