### ISSUE TITLE
Feature request: flash multiple messages with same key

### ISSUE THREAD

**Issue by danilobuerger** [slimphp/Slim#496]
Hey,

i am using flash messages to display errors. It would be nice if i could easily stack them like so:

$app->flash('error', '1');
$app->flash('error', '2');

and have an array for the key "error" containing both messages. Currently only the last one is preserved.

Best regards

**Comment by ghost** [comment]
assuming that flash messages are stored in 

``` php
$_SESSION['slim.flash'] 
```

(from documentation) you can try to save and array like 

``` php
$app->flash('error',array(
'Invalid login'
,'You dont have access to X'
,'..'
));
```

**Comment by danilobuerger** [comment]
Thats how i am doing it now, but it would be much nicer to have Slim take care of it, hence the feature request.

**Comment by silentworks** [comment]
Would FlashKeep not help at this point? http://docs.slimframework.com/#Flash-Keep

**Comment by danilobuerger** [comment]
As far as i know thats something completely different. I am talking about setting multiple messages with the same key in the same request.

**Comment by codeguy** [comment]
@danilobuerger Doing as you suggest would break existing expectations. If I were to change this behavior, it would be for a future major point release. For now, I encourage you to pass an array of messages for a single key.

**Comment by matthew-dean** [comment]
It seems intuitive that multiple flash messages might be added under the same key (by, for example, triggering errors in different places, which isn't as easily managed by collecting it in an array and adding it later).

+1 for this
