### ISSUE TITLE
Discuss Slim Framework RoadMap

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#5]
I have posted a RoadMap working draft at http://github.com/codeguy/Slim/wiki/Road-Map. Please post your thoughts, suggestions, etc. in this thread so we can agree on a RoadMap for Slim's development into the near future. Thanks!

**Comment by neverender** [comment]
Hi, first of all, thanks for starting this project. I think this may become my favorite php micro framework. The RoadMap looks great. Ideas off the top of my head:
- Ability to set a directory for static files.
- Middleware? The documentation says 'Coming soon...'
- Maybe a built-in way to change the response based on extensions in the url like .xml, .json, etc. It would be nice if you could, within one route, set your variables and then have a different view depending on if the url ends in .xml or whatever.
- a 'pass' method. Where the current route halts and you get passed to the next matching route. Like Sinatra. 

These might be non 80/20 things, I dunno.

**Comment by codeguy** [comment]
@Cognitive Thanks!
1. Can you explain this in more detail? If you want to serve static files, you are already able to do this because Apache will serve static files if they exist, else it will forward the request to the Slim application. I'm sure it would be helpful to delegate static file serving to Slim in some instances though. Could you provide several examples?
2. I'm not sure if "Middleware" was the best word for this, nor am I sure how I want to implement it just yet. Currently, Slim allows you to define multiple before and after callbacks that are run in succession, before and after the Slim app runs. Due to the static nature of Slim, I'm not sure we even need a mechanism to register "middleware" when all you have to do is include your custom code at the top of your bootstrap file and call your code where necessary. What do you think?
3. I like this. But we need to be careful not to mix responsibilities between the controller/route and the view. I can parse the requested format based upon the resource URI extension (ie. set "Content-Type: text/json" header for a .json extension). However, it is still the view's responsibility to serve the actual JSON... a responsibility that currently falls on the end developer. We'll need to figure out how to implement this right.
4. This should be fairly simple... if Slim::pass() throws an exception, the exception could be caught in the Router::dispatch() loop that then calls "continue;" to continue looking for the second matching Route.

Nice! Let me know what you think about 1, 2, and 3.

**Comment by codeguy** [comment]
@Cognitive

Regarding number 3, I actually don't think this would be that big of a deal if we built this functionality into the default View.

**Comment by neverender** [comment]
1. You're right, Apache will serve your static files, so I guess it's not a big deal. But I was just thinking of how Sinatra does it. You set a static file directory (defaults to /public) but your files show up at '/file.txt' instead of '/public/file.txt'. I usually would accomplish this through some .htaccess rules, but it would be cool if Slim could take care of it somehow.
2. Yeah I can see how "Middleware" might not be necessary. But on the other hand, it could be good to have a standardized way of plugging stuff in.
3. That's exactly what I meant. Whether it's a controller or view thing, I'm not sure. My first thought was controller, since it would need to know route information. And you call the Render method within the route callback. But it is kind of a view-centric feature...

I just thought of something else. Since you're using github, you might as well fully utilize the wiki and copy the documentation over to it.

**Comment by codeguy** [comment]
1. Will think some more on this and look at how/why Sinatra does this. I'm still not entirely sure it's as necessary with Slim, but it could be useful nonetheless.
2. I agree, a standard plugin interface would be good to have. I'll probably spawn this off into another discussion when ready.
3. Cool. I would really like to have this feature myself. Sounds good.

And I'll work on copying over the documentation to the Wiki sometime soon.

**Comment by j4mie** [comment]
I like the idea of supporting multiple content types, but this should probably be done using content negotiation ( http://en.wikipedia.org/wiki/Content_negotiation ) as this is more in keeping with REST and HTTP. We can support changing URL extensions too (add .json, .xml etc) but this should probably just "spoof" the content type in the same way that _METHOD in forms spoofs PUT and DELETE methods.

I'll have a good look at the roadmap and add my thoughts when I get some time. At the moment, it looks like a great set of ideas.

**Comment by codeguy** [comment]
@j4mie I've found true content negotiation that depends on the Accepts headers very if not completely unreliable because many web browsers (including Safari), do not handle it correctly. But as you said, we could easily shift a new priority preference onto the front of the Accepts header based on the extension. That should work fine (and good idea!)

**Comment by codeguy** [comment]
@j4mie If you were to write a non-browser third-party HTTP client that DID send accurate Accepts headers... I could add a setting to toggle on or off Accepts header content negotiation. But I would still say that a resource URI with an extension would still take priority if it is specified.

**Comment by codeguy** [comment]
@j4mie For reference, Kris Jordan (a colleague of mine) published this in 2009. Things may have changed since then, but its a good read. http://www.gethifi.com/blog/browser-rest-http-accept-headers

**Comment by j4mie** [comment]
I'll leave the work here to someone who knows more about it that me! However, I was thinking more about clients other than web browsers (REST client libraries, cURL, etc) which are more likely to send the correct headers. We could give Slim some sensible defaults and make it behave gracefully when it receives incorrect headers (from browsers) and still support the HTTP spec.

**Comment by codeguy** [comment]
@j4mie I completely agree with you re: non-browser clients. Those are certainly more likely to adhere to the HTTP spec. My only concern is:

We have a cURL client who requests /foo/bar and sends an Accept header that prioritizes XML.

We also have a web browser who requests /foo/bar and expects HTML but requests XML due to a weird Accept header.

In some cases this may work if the browser sends an appropriate Accept header; in other cases (such as Safari), the browser request would still be served XML because that is what the Accept header will prioritize. If a URI extension is specified (ie. /foo/bar.html), then Slim will ignore the Accept header and serve HTML, but then you must always specify the .html extension for web page requests for html. Adding the .html extension is not really clean, especially for those that want cruft-free URLs.

So you see the predicament? Until browser makers can fix the issues with the Accept header, it really throws a wrench into supporting true content negotiation.

So I believe the plan going forward should be to, at first, support fake content negotiation based on the request resource's extension (ie. ".xml" for XML, ".html" for HTML, ".json" for JSON, etc). Later on, I can add a Slim setting to toggle true content negotiation based on the Accept header. For now, it's safer to use the resource extension to explicitly request a format, else default to HTML.

**Comment by codeguy** [comment]
Closing out.

**Comment by tobsn** [comment]
Slim::get( 'route', function(){})->type( CONTENT_JSON ); would be a good idea... to pick up the content negotiation issue. 
look at the examples here: https://github.com/caolan/quip - but i guess you already solved that anyway.
