### ISSUE TITLE
Setting custom template directory using setTemplatesDirectory()

### ISSUE THREAD

**Issue by shameerc** [slimphp/Slim#504]
I've a custom View class which extends <code>Slim\View</code> with render method that invokes <code>render()</code> of base class. I'm also using a custom template directory in my application, which is set using <code>setTemplatesDirectory()</code>. But it doesn't take effect as parent render method has [setTemplatesDirectory()](https://github.com/codeguy/Slim/blob/master/Slim/Slim.php#L670) which changes to the default value in the configuration. I was wondering if its really necessary to call this method twice in the Slim. Or I think it's better if we can take out of the <code>View->render()</code> method

**Comment by codeguy** [comment]
Fix merged into https://github.com/codeguy/Slim/tree/release-2.4.0
