### ISSUE TITLE
Routing not working when query is in QUERY_STRING instead of PATH_INFO

### ISSUE THREAD

**Issue by hay** [slimphp/Slim#509]
Hi guys,
i don't know if this is a bug or a feature, but i'm having some trouble getting a simple Slim application to work with my hosting provider.

I'm using the example from the homepage, and i simply can't get the route ('/hello/:name') to work (getting '404 not found'). What i did was check what happens if i use `getResourceUri` in a callback from `notFound` and sure enough the getResourceUri is completely empty.

The only difference i can find between my host and my local machine (where the example does work) is that on my machine the query seems to be in the PATH_INFO property in `$_SERVER`, while on my host it's in `QUERY_STRING`. Maybe that has something to do with the problem?

**Comment by codeguy** [comment]
Sounds like a server configuration issue. Are you certain you are using the recommended .htaccess file (I assume you are on Apache)? You're better off posting this question to the support forums.

http://help.slimframework.com/

**Comment by hay** [comment]
Hey codeguy, well the problem was that my host has some _really_ weird routing going on, and with lots of patience they managed to fix it. Thanks for coding a cool framework!

**Comment by codeguy** [comment]
Happy to hear you got it worked out!
