### ISSUE TITLE
Dynamically generated JPEG not outputting to the browser?

### ISSUE THREAD

**Issue by tvpmb** [slimphp/Slim#510]
For some reason I can't dynamically output a JPEG image to the browser.

```
  $res = $app->response();
  $res['Content-Type'] = 'image/jpeg';

  ImageHelper::createPreviewImage($settings);
```

CreateImagePreview() looks like this:

```
$newImg = @imagecreatetruecolor($newWidth, $newHeight);
      @imagecopyresampled(
        $newImg,
        $image,
        0, 0, 0, 0,
        $newWidth,
        $newHeight,
        $imgWidth,
        $imgHeight
      );
      imagejpeg($newImg, NULL, 70);
      imagedestroy($newImg);
```

Am I missing something here? This is a very simple process with vanilla PHP, for some reason I can't get it working on Slim?? Has anyone run into this problem before?

The browser just displays a broken image icon. If I turn off the `header('image/jpg')` I see the body of the image displayed in the browser....so it is really strange!

**Comment by tvpmb** [comment]
Just tried this, and it also didn't work.... trying to simply here: Also I'm running nginx+php5-fpm.

```
  $res = $app->response();
  $res['Content-Type'] = 'image/jpeg';
  $res['Content-Disposition'] = 'inline; filename="img.jpg"';
  $image = imagecreatefromstring(file_get_contents('<amazon s3 url>'));
  $res->body(imagejpeg($image));
  imagedestroy($image);
```

**Comment by tvpmb** [comment]
I created a simple test.php file and ran it on my server, this worked perfectly:

```
<?php
header('Content-Type: image/gif');
header('Content-Disposition: inline; filename="img.gif"');
echo file_get_contents('<amazon s3 url>');
```

**Comment by klivan** [comment]
Not a bug. You have bug in you code.

This code will work fine:

``` php
$res = $app->response();

$res->header('Content-type', 'image/jpeg');
$res->header('Content-Disposition', 'inline; filename="img.jpg"');

$image = file_get_contents('<amazon s3 url>');
$res->body($image);

$app->run();
```

The problem with your code is that you're using function imagejpeg. This function not returns image and sets it into ->body() method. imagejpeg function just outputs image content into browser.

As headers are set only during $app->run() call they can't be set because content is already sent to browser.

**Comment by codeguy** [comment]
Closing. Please move this to the support forum at http://help.slimframework.com.
