### ISSUE TITLE
XDomainRequest - getting crazy

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#511]
Hi!
I'm trying to make a REST service with cross-subdomain client, but XDomainRequest has huge restrictions described here: http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx .
Is it possible to support this msie ****\* somehow?

**Comment by ghost** [comment]
Ok. I gave up, no session cookies, I cannot work without them...

**Comment by cwt137** [comment]
Yes, just set the response header and add Access-Control-Allow-Origin. Look at the docs to see how to add a response header. http://docs.slimframework.com/#Response-Headers . While you are at it, better set the headers for CORS support so the cross-site stuff will work in Chrome and Firefox too.

**Comment by ghost** [comment]
@cwt137 IE 8-9 has only very limited features by CORS, that's the problem. I know how to add response header...
