### ISSUE TITLE
Develop - Helpers\Set no property access/overloading

### ISSUE THREAD

**Issue by zomble** [slimphp/Slim#512]
I was playing around with the develop branch of Slim and I ran into an issue with the Set class and Mustache templating.

Mustache is explicitly checking for properties ->foo not ['foo'] (as you currently expect Set to be used).

Obviously one could update Mustache to check for instanceof \ArrayAccess (bit silly), or simply extend Set, and add the usage of magic functions.

Would it be alright to add the use of __get (I think this should still throw ErrorException on properties that don't "exist") and __isset in Helper\Set? Or is it by design to exclude it? If wanted I can PR the change, inc tests.

Also, I'm not 100% sure if it's a good idea to use __get and __isset with out __set and __unset, but I'd personally prefer those were still handled the way you have currently defined in Set. Thoughts?

Cheers.

**Comment by codeguy** [comment]
I think property overloading is fine if it will help improve compatibility with Mustache. Go for it. Send a PR when ready.
