### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by Skeyelab** [slimphp/Slim#517]
I am finding some threads on this, but can't seem to find anything concrete.  Did CN ever get implemented?  If so, how do we use it?

**Comment by moiseevigor** [comment]
Once I've discovered this thread and this answer of Josh: https://github.com/codeguy/Slim/issues/142#issuecomment-1712167
It is not the CN, but works.

**Comment by codeguy** [comment]
This has been an interest of mine for quite a long time, but I haven't really settled on an implementation that I like. It's on the drawing board, but there are other higher priority changes that need to happen first.

**Comment by willdurand** [comment]
Well, Josh's answer is not correct technically speaking, `:format` in the URI is not CN, and this is not a valid alternative (it is not even an alternative). Slim doesn't handle Content Negotiation, but it's easy to integrate a third-party library such as [Negotiation](https://github.com/willdurand/Negotiation) (disclaimer: I wrote the lib). Maybe it's possible to extend either Slim or Negotiation to provide a "all-in-one" solution.

**Comment by codeguy** [comment]
I never said that was content negotiation, but it's a makeshift solution. As is inspecting the Accepts header in the request. Right now Slim doesn't handle CN. For now, your Negotiation lib is certainly a good third-party solution.

**Comment by willdurand** [comment]
So, do you want to handle CN in Slim itself or what? Maybe middlewares are the way to go..

**Comment by codeguy** [comment]
This has definitely been put on the backburner for a while now. My apologies for that. I think it is probably best to implement this in a middleware layer instead of putting it in the core code. @willdurand I don't have time to do this, but you are welcome to head this up if you are interested and have time. You can build this out in the new https://github.com/codeguy/Slim-Middleware repository, or you can keep it in a local repo and push it up to Packagist under the "slim" namespace. Let me know whatever you think is best.

**Comment by codeguy** [comment]
And feel free to source the previous pull request or to require (and credit) your own Negotiation library. No sense reinventing the wheel.

**Comment by designermonkey** [comment]
Middleware was on my mind as I read this 10 minutes ago too. Not used content negotiation before, looking forward to playing around!

**Comment by willdurand** [comment]
@codeguy I will try to come up with something like integrating Negotiation with Slim-Middleware

**Comment by codeguy** [comment]
@willdurand Sounds great. Looking forward to see what you come up with.

**Comment by marleyiam** [comment]
Hi! Does anybody could show me an example about how to set and use Content Negotiation using SlimExtras2+ ? Cheers!
