### ISSUE TITLE
StandAlone?

### ISSUE THREAD

**Issue by sassyn** [slimphp/Slim#519]
Hi,

Can this be used as a stand alone application?

I'm looking for a way to make pure php web server that support REST, without apache or lighthttpd. Just a simple PHP script that run my software.

My goal is to compile at the end my project to a binary using http://www.phpcompiler.org/.

Thanks

**Comment by codeguy** [comment]
Currently Slim is built with the assumption that you are using a web server in front of it... you may be able to get it working as you describe, but I cannot guarantee it will work since that is currently not supported.

**Comment by moiseevigor** [comment]
Actually this raise a good question to create a webserver for php. The one similar to nodejs, Mongrel, Thin and others.

**Comment by tyd** [comment]
@moiseevigor 5.4 introduces a starting point for that http://php.net/manual/en/features.commandline.webserver.php

**Comment by moiseevigor** [comment]
yep, not using that because of  impossibility to serve the static content out of the box. Non concurrent, but as an initial approxiamtion ... kind of webrick for rails.
