### ISSUE TITLE
cors preflight calls

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#522]
I wrote a middleware to handle cors preflight calls. Is there a built in way to handle them, or this is how we should handle them?

```
namespace Slim\Preflight;

class Middleware extends \Slim\Middleware
{
    public function call()
    {
        if ($this->app->request()->getMethod() == 'OPTIONS')
            exit();
        $this->next->call();
    }
}
```

**Comment by codeguy** [comment]
You don't need to use middleware to send a response to an OPTIONS request. You can create a GET or OPTIONS route like any other route:

```
$app->get('/foo', function () { ... });
$app->options('/foo', function () { ... });
```

Either of these will return the appropriate response headers. The method you demonstrate above is also a valid approach, except that you should NOT invoke `exit`; instead, simply do not invoke `$this->next->call()`. If you invoke `exit`, Slim will not complete the app lifecycle.

**Comment by ghost** [comment]
Thanks!
