### ISSUE TITLE
Closures as middlewares

### ISSUE THREAD

**Issue by tassoevan** [slimphp/Slim#524]
I can add some closures as route middlewares, but I can't do the same using Slim::add(Middleware) method; eventually I wrote a class named ClosureMiddleware for this purpose. So, why can't use closures (or another kind of callable) for this?

**Comment by codeguy** [comment]
Middlewares must implement a specific interface for them to run correctly.

**Comment by tassoevan** [comment]
But is exactly what I'm doing: ClosureMiddleware implements Slim\Middleware.
