### ISSUE TITLE
Make slim logging comaptible with PSR-3

### ISSUE THREAD

**Issue by aktau** [slimphp/Slim#525]
Not that I'm a whore for standards or anything. But wouldn't it be nice if the Slim logger implemented PSR-3 by default? That way it could be much nicer to interface with other loggers who do the same (monolog...) and much more importantly we can pass the $app->getLog() to other libraries who expect a PSR-3-like logger.

I'm sorry if this has been discussed before, but the github search feature doesn't turn up anything.

**Comment by codeguy** [comment]
This is actually already implemented and should be available in the develop branch. It'll get merged into the next point release some time soon.

**Comment by aktau** [comment]
That would be awesome, thanks. Too bad I can't use the dev releases of Slim and Slim\Extras yet as a drop-in replacement. Twig gives me some serious errors so I suppose the API has changed somehow. For now I'll create a PSR-3 wrapper. That's 2 levels of wrapping now with some information loss in between, I hope that point release comes soon ;)

**Comment by aktau** [comment]
I've taken another look at the PSR-3 code though and correct me if I'm wrong but I would still need a (empty) wrapper class that implements LoggerInterface (from the PSR-3 package composer I think automatically installs). Is there some reason we don't have 

``` php
class Log implements Psr\Log\LoggerInterface {
    ...
}
```

instead of the current

``` php
class Log {
    ...
}
```

?
