### ISSUE TITLE
Make slim act as a global container

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#527]
Hello,

I think that can be a good thing to make possible to add element to the application object.
We could do things like :

``` php
$app = new \Slim\Slim();
$app->current_user = 'what you want'; // or $app->set('current_user', 'what you want')
```

And add database connexion, facebook sdk .... and retrieve all that in routes methods.

If you think that is not the good way to do I will be please to read your way of doing that.

**Comment by codeguy** [comment]
Closing. See duplicate issue here https://github.com/codeguy/Slim/issues/398

**Comment by lalop** [comment]
sorry,
didn't find it.

thank you
