### ISSUE TITLE
Route User-Agent Condition

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#53]
Allow routes to match an expected User-Agent string like this:

```
Slim::get('/foo/bar', function () {
    //Render template for SongBird
})->agent('Songbird (\d\.\d)[\d\/]*?');
```

**Comment by lukemorton** [comment]
As I suggested in #48 perhaps these Header based conditions could be provided for in a more general ->headers() method. For example:

```
Slim::get('/foo/bar', function () {
    // Render
})
    ->headers(array(
        'User-Agent' => 'Songbird (\d\.\d)[\d\/]*?'
    ));
```

**Comment by bobdia** [comment]
Having too many routes with slightly different conditions seems like a bad pattern. It would be faster to check conditions inside a single route, if you have more than a couple.

**Comment by codeguy** [comment]
Removing this feature from the road map. Decided this is tangential to the framework itself, and can easily be written as a plugin if necessary using an earlier application hook. See https://github.com/codeguy/Slim/issues/closed#issue/75.
