### ISSUE TITLE
AutoLoader issue

### ISSUE THREAD

**Issue by jstrulens** [slimphp/Slim#536]
Hello,

I have the following configuration with WAMP:
`Slim Framework in C:\wamp\www\libs\slim\2.2.0\Slim.php`
`RESTful API : C:\wamp\www\project\api\request.php`

In the file C:\wamp\www\project\api.htaccess
`RewriteEngine On`
`RewriteRule ^(.*)$ request2.php [QSA,L]`

In the file C:\wamp\www\project\api\request.php, I have this code:

`````` require('c:/wamp/www/libs/slim/2.2.0/Slim.php');```
```\Slim\Slim::registerAutoloader();```
```$app = new \Slim\Slim();```
```$app->contentType('application/json; charset=utf-8');```
```$app->get('/hello', function() { echo 'Hello!'; });```
```$app->run();```

When hitting http://localhost/URG_SIU/api/hello, I have the following error: Fatal error: Class 'Slim\Log' not found in C:\wamp\www\libs\slim\2.2.0\Slim.php on line 252

Thanks!
``````

**Comment by civocr** [comment]
I'm also getting the same thing since updating composer yesterday
