### ISSUE TITLE
Django/Rack-inspired Error Page?

### ISSUE THREAD

**Issue by nielsen** [slimphp/Slim#54]
Especially with REST mapping like Slim has, and well documented exceptions to play with, a graceful error page might be a decent addition.

Obviously PHP doesn't support stack tracing out of the box in error handling, and I couldn't possibly imagine trying to add in a meaningful parser for a cachegrind file from XDebug that would n't be bloated as all get out.

Thoughts? Been toying with the idea the past couple hours.

e.g. (in ruby)
https://github.com/rack/rack/blob/master/lib/rack/showexceptions.rb

**Comment by codeguy** [comment]
Not really sure what you mean. Slim already has a built-in custom error page that provides error details (if debugging is enabled) and a full stack trace (if an exception was thrown); else Slim will call your own custom error handler (see Slim::error) should debugging be disabled. Maybe I'm just not clear on what you mean.

**Comment by nielsen** [comment]
Oh! I never had debug set to true; nvm, then.

Great job so far! Looking forward to content negotiation
