### ISSUE TITLE
hook not invoked on redirect

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#540]
Hello,

When doing `$app->redirect()` hooks on `slim.after.dispatch` and `slim.after.router` aren't invoked. The same thing ocurs for or any other helpers like `halt`, `stop` ...

I think that an issue since `slim.after.router` ( for exemple ) is sent :

> before the Response is sent to the client

**Comment by silentworks** [comment]
Closing this off since its over a year old, re-open if you think its still relevant or if its more of a question that a bug, ask about it over at http://help.slimframework.com.
