### ISSUE TITLE
error_reporting() ignored

### ISSUE THREAD

**Issue by skerdilek** [slimphp/Slim#541]
Slim was throwing errors for not so important errors (like notices) even when error_reporting was off.  For some reason error_reporting() function in handleErrors did not fire before making the if comparison.  I ended up assigning it to a variable called $report_errors and it started working properly.  I am not sure why it is this way, but I just wanted to let you know...

```
public static function handleErrors( $errno, $errstr = '', $errfile = '', $errline = '' ) {
    $report_errors = (error_reporting()==0);
    if( $report_errors && $errno ) {
        throw new ErrorException($errstr, $errno, 0, $errfile, $errline);
    }
    return true;
}
```

**Comment by patforg** [comment]
When you set a custom error handler via set_error_handler() PHP function,  the error_reporting value is not taken into consideration.  The handler will be called on every type of error, it is the functions responsibility to respect the error_reporting() value.  http://php.net/manual/en/function.set-error-handler.php

**Comment by codeguy** [comment]
I've simplified Slim's built-in custom error handler (changes pushed to develop branch for now), and it will respect your error_reporting level. Bear in mind that PHP will always report certain types of errors that cannot be handled by the custom error handler. Reference:

http://php.net/manual/en/function.set-error-handler.php

**Comment by Addvilz** [comment]
Josh, this isn't completely correct - PHP can have and does have a way to handle almost all errors, including fatal errors, except syntax errors. This is done by registering shutdown function and checking for error with error_get_last. Therefore it is possible to handle almost all types of errors you would expect to slip by the development stage of any  project. Iv'e used this before many times for a long time now, it's a confirmed solution.

Solution like this could be implemented in Slim, however it must be a configurable option.

**Comment by codeguy** [comment]
@Addvilz Gotcha. I don't want to go to that extreme to handle errors... Slim will only handle errors within the scope of its existence... it will handle its own errors and then cede control back to the previously registered handler.
