### ISSUE TITLE
Why not using `$_SERVER['PATH_INFO']` ?

### ISSUE THREAD

**Issue by steelywing** [slimphp/Slim#544]
I see the source code in `Slim\Environment.php` using below code to get `PATH_INFO`, why not using `$_SERVER['PATH_INFO']` ? what is the different?

```
        $env['PATH_INFO'] = substr_replace($_SERVER['REQUEST_URI'], '', 0, strlen($env['SCRIPT_NAME']));
        if (strpos($env['PATH_INFO'], '?') !== false) {
            $env['PATH_INFO'] = substr_replace($env['PATH_INFO'], '', strpos($env['PATH_INFO'], '?')); //query string is not removed automatically
        }
        $env['SCRIPT_NAME'] = rtrim($env['SCRIPT_NAME'], '/');
        $env['PATH_INFO'] = '/' . ltrim($env['PATH_INFO'], '/');
```

**Comment by akDeveloper** [comment]
`$_SERVER['PATH_INFO']` will catch the path from a url like `http://localhost/index.php/some/path`. In this example will catch `/some/path`

Slim uses urls in type of `http://localhost/some/path` so `$_SERVER['PATH_INFO']` is not available.
So Slim must catch `/some/path` from `$_SERVER['REQUEST_URI']` combined by `$_SERVER['SCRIPT_NAME']` in case you have a base path. 
By base path i mean that your web root is in a subdirecory. Ex. your web app is in `http://localhost/webapp/` dir, so everything after this consider a path info like `http://localhost/webapp/some/path`, `http://localhost/webapp/some/path?foo=bar` etc.

**Comment by steelywing** [comment]
Thank you for answer =)
