### ISSUE TITLE
Custom view class

### ISSUE THREAD

**Issue by jackcvr** [slimphp/Slim#547]
if I want to use own template engine I set 'view' => null, and got an error in the core.
I fix that like this:

``` php
public function call()
{
    try {
        if (isset($this->environment['slim.flash']) && $this->view()) {
            $this->view()->setData('flash', $this->environment['slim.flash']);
        }
```

**Comment by lalop** [comment]
Where is this method ?

**Comment by jackcvr** [comment]
https://github.com/codeguy/Slim/blob/master/Slim/Slim.php#L1277

**Comment by codeguy** [comment]
This should no longer be an issue.
