### ISSUE TITLE
Support for generating absolute url's using urlFor

### ISSUE THREAD

**Issue by radekbenkel** [slimphp/Slim#554]
Now you're not able to generate absolute URL (e.g. for RSS feed) by using `urlFor` itself. You need to go with:

``` php
$app->request()->getUrl() . $app->urlFor('event', ['id' => $id]);
```

Proposition is to add third param to `urlFor` which will decide if url should be absolute or  relative. Relative by default. 

I haven't found any information about similar thing in closed issues.

I can implement this if you think it's good idea.

**Comment by nickshanks** [comment]
Slim's urlFor() method is just crap, using the wrong values from `$_SERVER` and thus providing broken URLs. It's easy enough to override in your Application subclass though.

**Comment by Addvilz** [comment]
Nick, could you care to elaborate - what exactly is wrong with using SCRIPT_NAME to find a relative web root? What would you suggest then?

**Comment by nickshanks** [comment]
Well error #1: it doesn't provide a URL, it only provides a path, which causes output formats like Atom and HAL to be invalid. The code I use does not cater for installations other than at the root level of the server, which is fine for my purposes but would be unsuitable for general use. This is in my subclass of \Slim\Slim:

``` php
    /**
     * Overrides Slim\Slim::urlFor() which inexplicably concatenated the router URI with getScriptName(),
     * which presumably is supposed to return the path up to the script? in case you're not running from /index.php
     * It actually includes the script filename (as the function name implies!) resulting in daft URLs
     * like /index.php/object instead of /object
     */
    public function urlFor($name, $params = array())
    {
        // The Slim\Request::getUrl() method returns scheme://hostname[:port] not the whole request URL
        // It's really badly named, perhaps getHostURL() would have been better Josh?
        return $this->request->getUrl() . $this->router->urlFor($name, $params);
    }
```

**Comment by Pictor13** [comment]
> It actually includes the script filename (as the function name implies!) resulting in daft URLs like /index.php/object instead of /object

A note for issues diggers here:
`/index.php/object` can be legit format for a URL; for example it's used in one routing pattern, where `/object` corresponds to the `PATH_INFO` header. (although iirc PATH_INFO isn't supported by Apache)
