### ISSUE TITLE
Version 2.3.0 breaking twig templates using slim/extra

### ISSUE THREAD

**Issue by nubs** [slimphp/Slim#560]
Updating my application to version 2.3.0 of Slim Framework causes errors to be thrown.  This seems to be related to the `\Slim\Helper\Set` interface that was added.  Rather than an array being passed to `Twig_Template->render`, an instance of `\Slim\Helper\Set` is passed.

The three files in this gist reproduce this error for me: https://gist.github.com/nubs/5997208 (after a `composer install`).

Thanks for your time, and let me know if there is anything else I can provide.

**Comment by codeguy** [comment]
See http://help.slimframework.com/discussions/problems/4765-fresh-slim-230-problem-with-twig-template-render

**Comment by nubs** [comment]
Thanks!
