### ISSUE TITLE
breaking change: view data function

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#561]
Since the view's `data` atribute is an `\Slim\Helper\Set` I can't use it to set some function helper.

for exemple :

``` php
$view->setData('assets_url', function($asset_path) {
  ...
  return $modified_asset_path;
});
```

This throw an exception because when I get it in my view it's executed by `\Slim\Helper\Set` at line 88 `return $isInvokable ? $this->data[$this->normalizeKey($key)]($this) : $this->data[$this->normalizeKey($key)];`

**Comment by codeguy** [comment]
Ah thanks for the heads up. I'll get a fix in place soon.

**Comment by codeguy** [comment]
Fix pushed to the release-2.3.1 branch. Should be merged into master later this week.

https://github.com/codeguy/Slim/commit/baa1585005dcb347d8c4eee783ee0057f414eb38

**Comment by nickshanks** [comment]
Is 2.3 supposed to include breaking changes from 2.2 ?

If so, can I suggest you rename it to 3.0

**Comment by lalop** [comment]
Hello,

I just come to update to the 2.3.1.
If I understand the fix I 've to use View::keep instead of View::set, isn't it ?

I have a new issue with that, a little tiny one :
Argument 2 passed to Slim\View::keep() must be an instance of Slim\Closure, instance of Closure given
