### ISSUE TITLE
New requirement for package "ext-mcrypt", which doesn't exist

### ISSUE THREAD

**Issue by nickshanks** [slimphp/Slim#563]
I tried updating to 2.3.0 yesterday, and to dev-release-2.3.1 today, using Composer. Both of these give the following:

```
  Problem 1
    - Installation request for slim/slim dev-release-2.3.1 -> satisfiable by slim/slim[dev-release-2.3.1].
    - slim/slim dev-release-2.3.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
```

There is an RPM package called "php-mcrypt" but installing that doesn't satisfy the requirement. Running CentOS 6.4 with the latest PHP available for it, 5.3.3.

```
yum whatprovides "*/ext/mcrypt"
```

returns no results either.

**Comment by cbschuld** [comment]
Nick, this does not help your fight much but I am on CentOS 6.4 but using php5.4 and installing the php-mcrypt for 5.4 did solve the dependency for me and it installed w/o issue. //chris

**Comment by codeguy** [comment]
I haven't been able to duplicate this issue on my end. Going to close this out. I encourage you, though, to post this question to the support forums where you may find more help.

http://help.slimframework.com/

**Comment by nickshanks** [comment]
If it helps, I can send you a Vagrant/VirtualBox config, Puppet manifest and my composer.json file which should give you the same set-up I am using.

**Comment by codeguy** [comment]
Sure. Go ahead and post that here and I'll run that tonight.

**Comment by nickshanks** [comment]
Silly GitHub: "Unfortunately we don't support that file type yet. Please use PNG, GIF, or JPG."

I have copied them to http://web.nickshanks.com/github/codeguy/slim/563/
