### ISSUE TITLE
Missing functionality - pretty exceptions (crit)

### ISSUE THREAD

**Issue by Addvilz** [slimphp/Slim#565]
Changelog for 2.3 states "Removed \Slim\Middleware\PrettyExceptions when not in debug mode" however functionality is missing - file /Slim/Slim.php line 1237 in 2.3 release zip/tarball. The might be some merge issue.

**Comment by codeguy** [comment]
Odd. Seems to be a merge error... it made it into develop but should have been in 2.3.0. Fixed now. Thanks for the heads up!

See commits here https://github.com/codeguy/Slim/tree/release-2.3.1
