### ISSUE TITLE
Support Arguements in Set helper

### ISSUE THREAD

**Issue by jleck** [slimphp/Slim#566]
As mentioned on Twitter, it would be great to extend the set class to support parameters in closures. The idea of returning the actual closure was good, but not sure how we can inject the container using that method.

To not break backwards compatibility, I suggest an additional public method similar to get, as there's no viable way to support default values as well as an undefined number of parameters.

The closure inside the singleton method should be extended to cache output by arguments with a function similar to:

``` php
/**
 * Generate a unique key from the passed arguments. Used for storing
 * and retrieving cached singletons
 * @param  array  $args array of arguments
 * @return string       unique key
 */
protected function argumentsKey($args)
{
    $key = '_';
    foreach ($args as $arg) {
        $isInvokable = is_object($arg) && method_exists($arg, '__invoke');

        // Can't cache when an argument is a closure, so return false
        if ($isInvokable) {
            return false;
        }

        // Append to key
        $key .= is_array($arg) ? serialize($arg) : $arg;
    }
    return md5($key);
}
```

Such an idea has been implemented in the Zit library (https://github.com/inxilpro/Zit/blob/master/lib/Zit/Container.php). See the get function in particular.

The change should be reasonably simple. I will pull the change in a few hours (unless you continue working on it first).

**Comment by codeguy** [comment]
Can you post some sample code that demonstrates how you would use this in practice? I think that would help me get a better idea of what you are suggesting. Thanks!

**Comment by jleck** [comment]
Something like:

``` php
// Store settings in container
$container->set('settings', array(

    // Database Connection Details
    'db' => array(
        'read' => array(
            'database' => 'db',
            'username' => 'username',
            'password' => 'password'
        ),
        'write' => array(
            'database' => 'db',
            'username' => 'username',
            'password' => 'password'
        )
    )
));

// Register service to initiate ORM
$container->singleton('db', function($container, $type = 'read')
{
    $settings = $c->get('settings')['db'][$type];
    return new orm($settings);
});

// Retrieve ORM
$container->get('db',  'read');  // New ORM using read DB
$container->get('db',  'write'); // New ORM using write DB
$container->get('db',  'read');  // Returns existing read DB
$container->get('db',  'write'); // Returns existing write DB
```

Hope that helps!

EDIT: I realise you could do something similar by registering the DB twice, but this is the simplest way of explaining I could think of. Another use would be caching DB results. You could setup a closure which finds the company of the userId passed, and this would cache the result so a maximum of one query per user would be needed, no matter how many times you lookup the company :)

**Comment by codeguy** [comment]
I like where this is heading, but I'm going to wait on this feature for the next point release so we don't rush it out the door.

**Comment by jleck** [comment]
no problem! To be honest, I quite like the idea of registering multiple instead, atleast for services.

``` php
$container->get('readDB');
$container->get('writeDB');
```

IMO thats better semantically. Still a useful idea anyway.

**Comment by codeguy** [comment]
Version 3 (in develop branch) will be using Pimple as its container.
