### ISSUE TITLE
Twig error with Slim 2.3.0

### ISSUE THREAD

**Issue by tuimz** [slimphp/Slim#567]
I am getting the following error when upgrading Slim to 2.3.0.

```
Argument 1 passed to Twig_Template::render() must be of the type array, object given, called in     .....\vendor\slim\extras\Slim\Extras\Views\Twig.php on line 99 and defined
File: .....\vendor\twig\twig\lib\Twig\Template.php
```

When I downgrade to 2.2.x it works fine again. I am sure I am not giving an object, as nothing in the render() call has changed.

```
$app->render('template.twig', array('username' => $username, 'tags' => $tags, 'types' => $types));
```

Is what the render call looks like. If you need more information please let me know.

-Tim

**Comment by nubs** [comment]
Take a look at https://github.com/codeguy/Slim-Views.  It was a drop in replacement for me in place of Slim-Extras, although there are a few differences.

**Comment by codeguy** [comment]
Update your older view so that it passes `$this->data->all()` rather than `$this->data`. Or update to the new custom view code in `Slim-Views`.
