### ISSUE TITLE
‘Expires’ field isn't parsed by `strtotime` on serialization of Secure Cookies

### ISSUE THREAD

**Issue by shello** [slimphp/Slim#568]
With Slim 2.3.0, when `cookies.encrypt` is `true` (i.e., Secure Cookies are active), and `setCookie` (from `\Slim\Slim`) is called with `$time` (or `cookies.lifetime`) being a _string_, the serialization of the cookie (`\Slim\Http\Util::serializeCookies`) sets the `$expires` argument of `\Slim\Http\Util::encodeSecureCookie` as the string without parsing it with `strtotime`.

This causes the secure cookie value to have the expires string before the first `|` separator, instead of having a timestamp.

When this cookie value reaches `\Slim\Http\Util::decodeSecureCookie` it's not accepted when the (supposed) timestamp is checked against `time()`.

I wrote a test for this, but it depends on `\Slim\Http\Cookies` and `\Slim\Http\Headers`: https://gist.github.com/shello/6026460

**Comment by codeguy** [comment]
Did you want to send a PR, or would you prefer I do this? Just want to make sure you have a chance to receive credit for the fix. Let me know. Thanks!
