### ISSUE TITLE
MustacheView not rendering

### ISSUE THREAD

**Issue by tutuca** [slimphp/Slim#57]
I've just updated to the develop branch, and I can't get the MustacheView to render anything. I've isolated an ad-hoc test case (http://dpaste.com/hold/280035/), it just renders a blank page, nothing gets printed in apache's log or anywhere visible. 

Using config('debug', true), and Slim::log() makes no difference.

**Comment by codeguy** [comment]
Thank you! Small bug that slipped past me in the latest View updates. Should be fixed. Pull from `develop` and try again.

**Comment by tutuca** [comment]
Woah dude!! that was fast :)
