### ISSUE TITLE
$this->cookies in Response not persisting

### ISSUE THREAD

**Issue by nielsen** [slimphp/Slim#58]
The cookies added to the (response) $this->cookies[] array, for some reason, aren't making it to ln. 282 where they are iterated over. I took a crude peek to see where the disappearing act was happening with var_dump($this->cookies); die; but couldn't find out where the problem started.

I changed addCookie to:
     public function addCookie( Cookie $cookie ) {
        $this->cookies[] = $cookie;
        return setcookie($cookie->name, $cookie->value, $cookie->expires, $cookie->path, $cookie->domain, $cookie->secure, $cookie->httponly);
    }
because by sendHeaders(), there's nothing to iterate through.

**Comment by codeguy** [comment]
Can you send me the code snippet from your app you are using to set cookies?

**Comment by codeguy** [comment]
I'm unable to duplicate this on my end, so it may be something specific to your app. That being said, I am still readying several improvements to Slim's cookie management. Should have those pushed to the `develop` branch sometime tomorrow.

**Comment by nielsen** [comment]
/****\* COOKIES *****/

```
/**
 * Add Response Cookie
 *
 * @param   Cookie $cookie
 * @return  bool
 */
public function addCookie( Cookie $cookie ) {
    $this->cookies[] = $cookie;
    return setcookie($cookie->name, $cookie->value, $cookie->expires, $cookie->path, $cookie->domain, $cookie->secure, $cookie->httponly);
}
```

**Comment by nielsen** [comment]
The code executes as follows:
A POST with login form data is sent to the Route /login/; that calls:
  Slim::post('/login/', function() {
    $user = new user;
    $user->login( $_POST['login'] );
});
[All my custom classes, like the part below, are invoked in Slim::before();]
The offending part with cookies, after all the checks, etc, is:

```
    if ( isset( $info['remember'] ) && $info['remember'] == 'on' ) {
        Slim::session( $config['auth']['cookie'], $content, time() + 75000 * $this->priv, '/');
        setcookie('testing123', $content, time() + 60000, '/');
    } elseif ( !isset( $info['remember'] ) ){
        Slim::session( $config['auth']['cookie'], $content, time() + 30000 * $this->priv, '/');
        setcookie('testing456', $content, time() + 60000, '/');
    }
```

The direct "testing" cookies set, but calling Slim::session() doesn't work as a setter (but it works great as a getter; I think the "NULL" response value is better than just an isset() check).  I can tell you that I traced, as I commented in the original problem, that $this->cookies[] only lasts so far into the app; by the end, when they're iterated through and passed to the PHP handler, they weren't there.

Perhaps some info on the life cycle of a Slim request (which would be helpful in the wiki) would be useful for my debugging.

**Comment by codeguy** [comment]
Thanks for the additional info. I don't seen anything that would cause Cookies to disappear. But I can't really tell you much more without debugging your code directly. Feel free to pull the new code (once it is pushed tomorrow) and see if that resolves these issues. If the issue persists... `setcookie()` will work instead.

**Comment by codeguy** [comment]
Re: Slim app lifecycle, that is a great suggestion and I will be sure to add that to the Wiki as soon as I can.

**Comment by nielsen** [comment]
Thanks; I look forward to looking it over, and pulling it in.

I really like this framework; you've done a great job, and I'm happy to see how it's developing.

**Comment by codeguy** [comment]
I have pushed the latest code to the develop branch and added unit tests. Pull the changes and let me know. I still have not been able to duplicate the issues you've described here. Hopefully the latest changes will help. See the "Cookies" section in the Wiki docs for more info.

**Comment by codeguy** [comment]
I'm closing this out as I don't see any problems on my end. If you still have issues, leave a comment here and I'll re-open.
