### ISSUE TITLE
Add Request and Response __toString method

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#582]
Add __toString method to Request and Response objects to help devs quickly troubleshoot and diagnose request and response issues.

**Comment by designermonkey** [comment]
Would this go some way to helping #549 to work?

**Comment by codeguy** [comment]
Not really. This will print out a literal HTTP protocol representation of the request and response, much like the raw request and response are displayed in Webkit Inspector.

**Comment by designermonkey** [comment]
Ah, ok.
