### ISSUE TITLE
Line 457 of Slim.php

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#586]
Is there any reason why `get` is the only method to have two HTTP methods in it's call to `via`?

```
    public function get()
    {
        $args = func_get_args();

        return $this->mapRoute($args)->via(\Slim\Http\Request::METHOD_GET, \Slim\Http\Request::METHOD_HEAD);
    }
```

All of the other quick methods have only one HTTP method present.

**Comment by codeguy** [comment]
This let's Slim treat HEAD requests just like GET requests (per the HTTP spec)... if it is a HEAD request, the request body will be removed later in the app lifecycle by Slim.

**Comment by designermonkey** [comment]
Ahh, ok. Thanks for answering all my questions Josh :D

**Comment by codeguy** [comment]
No problem. Happy to help. Feel free to keep asking as you see things.
