### ISSUE TITLE
New Container questions

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#587]
Hi Josh.

I'm having a good old play building an app using the new container, and I have question about the implementation.

Would it have not made sense to have the `Slim` object itself be the container? So to extend `\Slim\Helper\Set` directly?

It took me a minute to figure out that I need to use `$app->container->singleton()` to instantiate a singleton in the container, yet I can use `$app->my_var` to instantiate a variable, as there are magic methods on `Slim` to allow this to be passed to magic methods in the container.

I just feel this is duplication and confusion here, and that it could be majorly simplified by directly extending the `Set` container.

**Comment by codeguy** [comment]
Fair point. Will try to improve this in the next major point release since this would be a breaking change.

**Comment by designermonkey** [comment]
I would do a PR for you in preparation, but I don't know jack about doing tests yet.

**Comment by codeguy** [comment]
I think this would be a good opportunity to learn how to do a basic unit test. You can look at some of the existing simpler unit tests for boilerplate.

Else, feel free to submit a PR without unit tests and I can take care of those on my end when you have your code changes complete.

**Comment by designermonkey** [comment]
I'm glad this would be for the next major release, as I am pretty snowed under right now to do it.

I have some ideas though, so will definitely do this. Let me know when you're not far off the next release and I'll pull my finger out :)

**Comment by codeguy** [comment]
Sounds good!

**Comment by designermonkey** [comment]
@codeguy I was just having a look at this, and spotted this:

``` php
$this->middleware = array($this);
```

If we were to make `Slim` an extension of the `Set` container, would this make a circular reference and throw an error? I'm not sure myself until I actually do it.

**Comment by designermonkey** [comment]
I've made the changes required, but for some reason, I can't get any of the tests to run.

I'm a complete TDD noob, and it's complaining that the Helper\Set class doesn't exist. As I don't know what to do, I'll PR this work and let you tell me where I've gone wrong if that's ok @codeguy?

**Comment by codeguy** [comment]
Thanks. I'll have a look at your PR this weekend. You may be right about the circular dependency... I'll have to tinker with that and see if it fails. If it does fail, we may need to hold off on converting \Slim\Slim to a subclass of Set.

**Comment by codeguy** [comment]
Closing.
