### ISSUE TITLE
$cookie->path Reminders

### ISSUE THREAD

**Issue by nielsen** [slimphp/Slim#59]
Not exactly a bug, but if a cookie is set by http://localhost/test/login/, it auto-interprets the path to the level at which it was set--this usually isn't a problem, but with Routes instead of actual file structure, it can be easy to forget a cookie set at http://localhost/test/login/ isn't valid for http://localhost/test/admin/.

I think a quick note in the wiki should be fine and a nice reminder.

**Comment by codeguy** [comment]
I'll add a reminder in the docs. The Cookie class constructor currently accepts the same signature as PHP's native `setcookie()` method. The Cookie class is rudimentary at best right now... I intend to smooth it out in a few weeks.

**Comment by codeguy** [comment]
Do you think a note will suffice? Or should cookies be auto-set for the application root directory path? So if my app is accessible at http://www.mysite.com/sub/directory/, cookies will be set for /sub/directory/. Thoughts? Just want to make this as intuitive as possible.

**Comment by codeguy** [comment]
Added a note to the documentation. Closing.
