### ISSUE TITLE
Rendering template into string variable

### ISSUE THREAD

**Issue by zavg** [slimphp/Slim#591]
To render template into string (it is may be quite usefull when creating AJAX-applications with server-side rendered responses; and also in many other cases) it is necessary to perfom manualy 2 operations (instead of $app->render($data, $template) which is used for usual rendering):

$this->view->appendData($data);
$str = $this->view->fetch($template);

May be it is better to combine them in some method to make it more OOP-like?

**Comment by codeguy** [comment]
This is resolved in the develop branch.
