### ISSUE TITLE
Regression in trailing slash redirection from version 2.1.0

### ISSUE THREAD

**Issue by solarissmoke** [slimphp/Slim#592]
I'm having a bit of an issue with trailing slash handling in routes which I think is a regression. I think it was introduced in version 2.2.0. 

My route is defined as follows:

``` php
$app->get('/test/', function() use ($app) {
    echo 'test';
});
```

There is an explicit trailing slash in the route.

In version 2.1.0, a request for `/test` is properly redirected to `/test/`. However in version 2.3.1 `/test` is not redirected and a 200 response is served (as well as for `/test/`). The first request should be redirected to the canonical path defined in the route.

**Comment by zulrang** [comment]
Are you using mod_php, rewrite, php-fpm?

**Comment by solarissmoke** [comment]
I'm using mod_php with rewrite - but I don't think that is relevant? I can also reproduce with `index.php/test/` type URLs.

The issue is [this block of code](https://github.com/codeguy/Slim/blob/master/Slim/Route.php#L356) which matches the request both with/without trailing slash when the pattern ends in a slash:

``` php
if (substr($this->pattern, -1) === '/') {
    $patternAsRegex .= '?';
}
```

**Comment by solarissmoke** [comment]
Did some further digging and found the relevant change (the one I cited above isn't the problem). In version 2.1, the `Router::dispatch` function had this:

``` php
if (substr($route->getPattern(), -1) === '/' && substr($this->resourceUri, -1) !== '/') {
    throw new Exception\RequestSlash();
}
```

... which no longer exists in the `Route::dispatch()` in the latest code (the function has moved from Router to Route). In fact the RequestSlash exception appears to have been removed completely, so it seems this change was deliberate...

**Comment by silentworks** [comment]
Closing this off as its an old issue, reopen if necessary.

**Comment by mattcg** [comment]
@silentworks I think this issue should be reopened as it is indeed a regression.

**Comment by tuupola** [comment]
IMO `/test` does not equal `/test/` and it should not be automatically redirected. There could be a config for this though. But then again is not mod_rewrite better suited for this case?

**Comment by mattcg** [comment]
@tuupola I agree that there should be a config for this.

If strict routing is turned on, you'd get a 404 when requesting `/test`and the route is `/test/` (and vice-versa).

If it's turned off, you'd get a 302 (because literally, the resource is "Found" under a different URI).

**Comment by silentworks** [comment]
I am going to close this one off again as it can be done through mod_rewrite for now, but will look into it again once we start looking into better error handling and better http response code usage.
