### ISSUE TITLE
Better explain how to manipulate Environment variables

### ISSUE THREAD

**Issue by brod-ie** [slimphp/Slim#595]
I know it's easy to moan about documentation; it's impossible to keep readable, be accessible _and_ be extensive all at once. Slim's goes a long way in stating how fundamental and flexible the environment class is but crucially doesn't explain how to modify it:

```
 $_ENV = $app->environment();
 $_ENV['REQUEST_METHOD'] = 'POST';
```

Something akin to the above would be helpful to those just starting out with the framework and should inspire better use of hooks and middleware.

**Comment by codeguy** [comment]
The environment class is largely being de-emphasized in favor of directly manipulating the request and/or response objects in middleware. The Environment class is a convenient encapsulation of the current `$_SERVER` variables, or a way to inject custom `$_SERVER` variables for testing purposes.

**Comment by brod-ie** [comment]
Sure, but I found this hook helpful in our API (lets a GET variable take priority over request header's method type for easier CORS):

```
$app->hook('slim.before.router', function () use ($app) {
    if ($method = $app->request->get('method')) {
        $app->environment()['REQUEST_METHOD'] = strtoupper($method);
    }
});
```

There's no other way to set the `request` object's method therefore this seems the most appropriate approach? Unless I'm missing a `request->setMethod()` style setter? (Can't see anything in the [documentation](http://docs.slimframework.com/#Request)).
