### ISSUE TITLE
Intelligence in notFound()

### ISSUE THREAD

**Issue by tentwofour** [slimphp/Slim#597]
Using Slim 2.2.0, and really enjoying it!

I was wanting my notFound handler to accept arguments, and found that the notFound() method of Slim doesn't attempt to pass any arguments through to the callable. Maybe this is by design, and I'm in the 20% use-case scenario, or I'm missing something obvious?

For instance, my main controller:

``` PHP
// set 404 callable
$app->notFound(function ($params) use ($app) {
    $app->render('404.html', array(
        'slug' => $params['slug']
    ));
});


$app->get('/:slug', function($slug) use ($app) {
    if (!file_exists(realpath($app->config('templates.path').'/'.$slug.'.html')))
    {
        $app->notFound(array('slug' => $slug));
    }
    else
    {
        return $app->render($slug.'.html');
    }
});
```

I changed Slim.php, lines 506

``` PHP
    public function notFound( $callable = null ) {
        if ( is_callable($callable) ) {
            $this->notFound = $callable;
        } else {
            ob_start();
            // Added
            $args = func_get_args();
            $args = $args[0];
            if ( is_callable($this->notFound) ) {
                // call_user_func($this->notFound);
                call_user_func($this->notFound, $args);
            } else {
                call_user_func(array($this, 'defaultNotFound'));
            }
            $this->halt(404, ob_get_clean());
        }
    }
```

For now, the handler doesn't really do anything with the slug, but in the future, the handler could provide a list of suggestions, based on a 'where slug like "%slug%"' type of idea.

Is there any interest in the idea; is it worth a pull request?

**Comment by StJudeWasHere** [comment]
You can also get the route params from within the `notFound()` method with something like this:

```
$app->notFound(function () use ($app) {
    var_dump($app->router->getCurrentRoute()->getParams());
});
```

This way at least you don't need to change the Slim.php file. Anyway, you may want to ask this one in the in the [help forums](http://help.slimframework.com) instead.

**Comment by silentworks** [comment]
There are currently discussion around error handling and the notFound method at the moment, it would probably be nicer to have something like what @tuupola suggested here https://github.com/codeguy/Slim/issues/881#issuecomment-53032739. I am going to close this one out in favour of @tuupola suggestion.
