### ISSUE TITLE
register_shutdown_function causing problems with exceptions

### ISSUE THREAD

**Issue by j4mie** [slimphp/Slim#6]
Although the approach of using `register_shutdown_function('Slim::run');` to avoid explicitly calling the `run` method saves a little typing, it causes problems when your application throws an exception:

```
Fatal error: Exception thrown without a stack frame in Unknown on line 0
```

Two suggestions:
1. Short term: make the call to `Slim::run()` explicit, at the bottom of the `bootstrap.php` file. Yes, it's slightly more typing, but using `register_shutdown_function` will cause lots of problems with exceptions. Also, it creates a point at which the behaviour of Slim cannot be overridden. Once a shutdown function is registered it can't be unregistered. This causes a few painful issues in Kohana which we want to avoid.
2. A longer-term solution (for the roadmap): Slim probably needs a `try`/`catch` block around the code in the `run` method. If an exception bubbles up to the top here, Slim should return a 500 error code and display a graceful error page (perhaps it should only do this in production mode, and display the full error message in development mode).

**Comment by codeguy** [comment]
Agreed to both. I'll push these fixes up tomorrow. If you have code already, send a pull request and I'll pull them in.

**Comment by j4mie** [comment]
Thanks - issue with the cryptic error message is now solved.

Before we do the work to add the `try`/`catch` block, we need to think about error handling in Slim more generally. We currently have `Slim::error()`, but Slim often throws a `RuntimeException` when something goes wrong. Which method are we going to favour? Ultimately (IMO) we should be throwing exceptions, but we could keep `Slim::error()` as a helper method which just throws the relevant exception, if we decide this is a cleaner approach. Any thoughts?

**Comment by codeguy** [comment]
Hi j4mie. In my mind Slim::error() is a helper method to set the HTTP status and return the response. However, to return a non-success Response, it seems more elegant and flexible based on your suggestion (if I am understanding correctly) , to throw an Exception whose code is equivalent to the desired Response status code. Such an exception would be caught by a try/catch block in Slim::run as you said. This will work for purposefully thrown Exceptions (ie. a 404 or 302), and for inadvertent Exceptions (ie. 500) should something break in the app's code. Is this what you mean? I like this a lot but want to make sure I full understand what you intend before implementing this. Let me know if you think of anything we've missed.

**Comment by codeguy** [comment]
Closing this out. Post any further comments to the Errors and Exception Handling issue.
