### ISSUE TITLE
[Develop Branch] Optional route segments break automatic trailing slash

### ISSUE THREAD

**Issue by nielsen** [slimphp/Slim#60]
The (awesome) optional route segments in the develop branch confound the automatic trailing slash rewrite. e.g.:

```
 Slim::get('/maintenance/(:time)', function ( $time = "a while" ) {
Slim::render('50x.php', array( 'time' => $time ) );
 });

 Slim::get('/login/(:msg)', function( $msg = null ) {
Slim::render('form-login.php');
 });
```

For the first, if I want to say, "Come back in an hour" I set the URI to /maintenance/in%20an%20hour. However, the optional segment for both '/maintenance/' and '/login/' throw 404s without the trailing slash 100% of the time; perhaps it's the regex?

**Comment by codeguy** [comment]
Try using the following route patterns instead:

'/maintenance(/:time)'

'/login(/:msg)'

Do these work for you?

EDIT: Made several formatting changes that were not picked up by GitHub.

**Comment by nielsen** [comment]
The versions I have '/maintenance/(:time)' and '/login/(:msg)' default to '/maintenance/' and '/login/' and 404 without the trailing slashes, i.e. the router doesn't automatically append them.

I had already tried the setup you suggest, which reverses the problems of the original: the slashed version throws 404 unless there is a "/time" or "/msg", and the unslashed version is default.

Neither case utilizes the auto-append slash which works otherwise without optional route segments.

**Comment by codeguy** [comment]
Just fixed Issue 61. This one is next on my to-do list.

**Comment by codeguy** [comment]
First, when you call `Slim::run()`, the URL is passed through `rawurldecode()`. In your example above for `/maintenance/in%20an%20hour`, the ultimate route passed into the router would be `/maintenance/in an hour`. This is an invalid route. Luckily, `rawurldecode()` ignores `+`, so you can instead use `/maintenance/in+an+hour`. Problem solved.

I am able to get both routes working as expected using the following:

```
Slim::get('/maintenance(/:time)/', function ($time = 'default') {
    echo $time;
});
```

In this route, if the trailing slash is omitted, you should be redirected to the same URL with the trailing slash. If you don't want the route to act as a directory, you could use:

```
Slim::get('/maintenance(/:time)', function ($time = 'default') {
    echo $time;
});
```

If you call this route with a trailing slash, you will get a 404. The same goes for your login route. Even though this is perhaps not the most intuitive approach, once you learn how to do this it does work. The route regex's are pretty involved as is, so I'd rather not try to fix an important part of the routing system that is not really broken. I may revisit this in the future. I'm closing this out for now, but if you still think something is wrong, please let me know.

**Comment by nielsen** [comment]
This is a better example:

Slim::get('/blog/(:id)(/:article)', function( $id = null, $article = null ){ 
    if ( !is_null( $id ) && !is_numeric( $id ) ) { Slim::pass(); }
    global $db;
    if ( is_null( $id ) ) {
        $p = $db->query( $db->prepare( "SELECT \* FROM `post` WHERE `type` != %s ORDER BY `date` DESC LIMIT 20", "page" ) );
        Slim::render('posts.php', array('postsObject' => $p)); 
    } else {
        $s = $db->query( $db->prepare( "SELECT \* FROM `post` WHERE `id` = %s", $id ) );
        if ( $s ) {
            Slim::render('single.php', array( 'postObject' => $s[0] ) );
        } else {
            Slim::notFound();
        }
    }
});

I cannot type as a URL "http://localhost/blog" without throwing a 404; perhaps that works a little better as a demonstration?

Also, in reference to your prior point, the "/maintenance/in%20an%20hour" works just fine: http://madebycoil.com/maintenance/in%20an%20hour for example (look @ "Come back in an hour"). http://madebycoil.com/maintenance throws a 404, whereas http://madebycoil.com/maintenance/ doesn't (and takes the optional route segment "a while" and passes it to the template). The code in question is:

Slim::get('/maintenance/(:time)', function ( $time = "a while" ) { 
    Slim::render('50x.php', array( 'time' => $time ) ); 
});

**Comment by codeguy** [comment]
To be honest, optional route segments were only intended to be used for subsequently optional route segments, much like an archive route scenario:

/archive/:year(/:month(/:day))

The examples you provided are more complex than what Slim can currently manage. Honestly, I probably won't update the optional route segments implementation for the time being. If someone else has time to provide a new implementation, that's perfectly fine. But I will be focusing on other tasks.

For your app, I would either organize it to use subsequently optional route patterns or split the functionality into separate routes.
