### ISSUE TITLE
No GET arguments passed in Slim's recommend nginx.conf

### ISSUE THREAD

**Issue by brod-ie** [slimphp/Slim#603]
`try_files $uri /index.php;`

Should be:

`try_files $uri /index.php?$query_string;`

See this [ServerFault](http://serverfault.com/questions/231578/nginx-php-fpm-where-are-my-get-params) question for more info.

**Comment by hoopyfrood** [comment]
+1

**Comment by ffflabs** [comment]
It's true, but I believe that's just a minor documentation omission. I didn't need to resort to google to find out how to do it, for it was somewhere in the former documentation. However, this is my current config

```
    location / {
       try_files $uri $uri/ /index.php?$request_uri;
    }

    location ~ ^/interfaces/([A-Za-z0-9\-\_]*)/(.*)$ {
          try_files $uri $uri/ /interfaces/$1.php?$request_uri;
     }
```

The second block is just my way to handle different methods to different interfaces on a particular subfolder, while preserving the default behaviour in the root.

**Comment by brod-ie** [comment]
@amenadiel GET vars are essential to the functioning of most web apps which means it's not an acceptable omission. Remember: **there's people out there that no less than me and you**; we can't expect people to dig around the web to find a solution to something this trivial.

**Comment by codeguy** [comment]
This is a documentation omission. The repo README is correct (see https://github.com/codeguy/Slim). Feel free to send a PR or I can fix this soon.

**Comment by brod-ie** [comment]
Sure, where is the doc's repo?

**Comment by codeguy** [comment]
https://github.com/codeguy/Slim-Documentation

Thanks for the help!

**Comment by brod-ie** [comment]
No problem, Slim is awesome :)

Just sent that PR now.

**Comment by codeguy** [comment]
And pulled. Thanks everyone. Closing this out.
