### ISSUE TITLE
possible config enhancement

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#607]
It would be easier to use the Slim.config method if it would parse the given key. For example:

```
$app->config(array(
    'model' => array(
        'session' => array(
            'expirationSeconds' => 60*30
        )
    )
));

$app->config('model.session', array(
    'directory' => __DIR__.'../session';
));

$app->config('model.session.mime', 'application/json');

$sessionConfig = $app->config('model.session'); // array(expirationSeconds => 1800, directory => __DIR__.'../session', mime => 'application/json')
$expirationSeconds = $app->config('model.session.expirationSeconds'); // 1800
$sessionDirectory = $app->config('model.session.directory'); // __DIR__.'../session'
$sessionFileFormat = $app->config('model.session.mime'); // 'application/json'
```

**Comment by designermonkey** [comment]
I would also like to see something similar to this. It would make finding values a lot more flexible.

**Comment by ghost** [comment]
Yepp, but implementation is not simple I think.

**Comment by codeguy** [comment]
I'd be on board with this, but I'm worried about the necessary complexity. If this were to happen, I'd prefer that Configuration be isolated into a separate `\Slim\Configuration` class. There are other things I'm focusing on now, but anyone else is more than welcome to take this on.

**Comment by designermonkey** [comment]
Not too difficult IMO, as Laravel has already tackled this with the namespaced config approach.

If you wanted to outline what your ideal approach to a separate `Configuration` class were, I could look at this. I have already got a partial working extended framework from Slim that has a `Configuration` class.

**Comment by codeguy** [comment]
I'd move everything to do with configuration currently in the `\Slim\Slim` class (variables, methods) into a new `\Slim\Configuration` class and then instantiate the `\Slim\Configuration` class with the new DI container as `$app->config`.

**Comment by designermonkey** [comment]
OK, no probs. I will leave the methods on the Slim class for deprecation though, and just reference them out of the DI container.

**Comment by codeguy** [comment]
Sounds good.

**Comment by designermonkey** [comment]
Nearly done here :)

**Comment by designermonkey** [comment]
The way I've implemented the Configuration is to have a parent class with default methods, so it can be re-used elsewhere if required, and the Configuration class extends this.

I was going to put the parent in the Helper namespace, but this is now gone :(

As it's merely a helper class, where should it go now?

**Comment by ghost** [comment]
Slim root, or make a new folder for collections :D

**Comment by codeguy** [comment]
Toss it in the top-level folder with the other classes for now.

**Comment by designermonkey** [comment]
No probs.

Josh Lockhart wrote:

**Comment by codeguy** [comment]
Closing this out since @designermonkey's config changes have been pulled into the develop branch for the upcoming 3.0 release.
