### ISSUE TITLE
GET Parameters for "/" path result in 404 Not Found

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#61]
When the current URL route path is "/", and if GET params are present like this:

/?foo=bar

The Slim application returns a 404 Not Found response.

**Comment by lukemorton** [comment]
If you use $_SERVER['REQUEST_URI'], clean it like Kohana.

https://github.com/kohana/core/blob/3.0.x/classes/kohana/request.php#L249

**Comment by codeguy** [comment]
This is fixed. I have pushed the hotfix to both `develop` and `master`. The latest version of Slim has been bumped to 1.0.1.
