### ISSUE TITLE
catching fatal error

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#612]
Hello,
I'm trying to work on a way to catch fatal error.
I'm trying to do that using `register_shutdown_function`.
I can log error but I don't find a way to send the error template to the user.
Here is my code :

``` php
register_shutdown_function(function() use($app){

    if (null === $lastError = error_get_last()) {
        return;
    }
    $errors = array(E_ERROR, E_PARSE, E_CORE_ERROR, E_CORE_WARNING, E_COMPILE_ERROR, E_COMPILE_WARNING, E_STRICT);
    if (in_array($lastError['type'], $errors)) {
        $e = new ErrorException(
            @$lastError['message'], @$lastError['type'], @$lastError['type'],
            @$lastError['file'], @$lastError['line']
        );
        $app->getLog()->fatal($e);
        ob_get_clean();
        $app->error($e);
    }

});
```

Doing so I get `Fatal error: Uncaught exception 'Slim\Exception\Stop'`
So how can I restart the app ?
And what do you think of this method to catch uncaught errors ?

**Comment by codeguy** [comment]
Please move this to a thread at http://help.slimframework.com/.

**Comment by lalop** [comment]
ok,
It's done here http://help.slimframework.com/discussions/suggestions/199-catching-fatal-error
