### ISSUE TITLE
Slim 404s when encounters encoded url (%20 etc.)

### ISSUE THREAD

**Issue by AshleyWright** [slimphp/Slim#615]
Whenever there is a non-alphanumeric (or ._-) character in the `$_SERVER['REQUEST_URI']` variable `$env['PATH_INFO']` does not get the expected value on apache.

Fix: replace all instances of `$_SERVER['REQUEST_URI']` with `urldecode($_SERVER['REQUEST_URI'])` in `Environment.php`

**Comment by StJudeWasHere** [comment]
This seems to work fine on both branches now, master and develop. Could you confirm it? maybe we can close this issue already.

**Comment by silentworks** [comment]
Over a year and no reply from original author so closing this one out.
