### ISSUE TITLE
Slim/View non existent method

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#616]
There is a call to `$this->data->keep($key, $value);` which doesn't exist in `Slim\Helper\Set`.

Does this method on `Slim\View` get used anywhere?

**Comment by codeguy** [comment]
Where do you see this? On which branch?

**Comment by designermonkey** [comment]
I've branched from `develop` and I can't see a `keep` method in `Set`.

**Comment by codeguy** [comment]
Pull the latest commits from develop. This was refactored yesterday.

**Comment by designermonkey** [comment]
Cheers.
