### ISSUE TITLE
setEncryptedCookie() don't work! @Version 2.3.1

### ISSUE THREAD

**Issue by hrbwaxdoll** [slimphp/Slim#625]
The following code does not work in PHP > 5.3 environment, suggesting that the 500 error, the environment for Apache+mysql+PHP5.4;

$app->get('/set-cookie', function () use ($app) {
    $app->setEncryptedCookie('foo', 'bar');
    echo "Cookie is set";
    home();
});

thanks!!~

**Comment by codeguy** [comment]
Which branch are you working from?

**Comment by hrbwaxdoll** [comment]
thank u reply~

i changed php.ini “timezone=Asia/Shanghai” ~ it’s work!

在 2013年9月17日，下午9:13，Josh Lockhart notifications@github.com 写道：
