### ISSUE TITLE
Use interfaces

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#638]
Use interfaces throughout so that individual classes can be replaced if necessary.

**Comment by designermonkey** [comment]
Happy to help here.

**Comment by charlie-s** [comment]
I'd like to get involved with development and this could be a good place to get started.

**Comment by codeguy** [comment]
@csdco Get in touch with @designermonkey, he's heading up the interfaces feature.

**Comment by charlie-s** [comment]
Thanks, found it @ https://github.com/designermonkey/Slim/tree/feature-interfaces.

**Comment by designermonkey** [comment]
This is all done now :D
