### ISSUE TITLE
Problem with Windows

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#64]
Request::extractQueryString creates incorrect $root on Windows

From user:

I have figured out the root cause the problem I saw. It is from `$request->$root`.

```
private function extractQueryString() {
    $this->root = rtrim(dirname($_SERVER['PHP_SELF']), '/') . '/';
    $uri = ltrim(preg_replace('@' . preg_quote($this->root, '@') . '@', '', $_SERVER['REQUEST_URI'], 1), '/');
    $questionMarkPosition = strpos($uri, '?');
    if ( !!$questionMarkPosition ) {
        return substr($uri, 0, $questionMarkPosition);
    }
    return $uri;
}
```

I run on Windows box, so dirname($_SERVER['PHP_SELF']); gives '\'. I guess we can use conditional statement to resolve this. I would want you to try the highlighted code on Windows first before confirming my findings. I use Slim Version 1.0, being lazy I downloaded from your site.

Now, I will start working on including SQL however rudimentary.

**Comment by bobdia** [comment]
Perhaps the built-in DIRECTORY_SEPARATOR constant would be handy.

**Comment by codeguy** [comment]
@bobdia Perhaps. In this case, Request::$root is the public-accessible URI to the directory in which the Slim app is installed. Most of the times, this will be "/", but it could be "/foo" or "/foo/bar" and so on. I believe DIRECTORY_SEPARATOR will be "\" on Windows so not necessarily useful when constructing URIs. This should be an easy fix... just need to get to it here soon is all.

**Comment by bobdia** [comment]
Just thought I'd mention it. "/" will work on windows so should be simpler to always use that. Let me know if you need someone to test on Windows.

**Comment by codeguy** [comment]
Absolutely. I'll post another message here when I push up the changes so you can test. Thanks!

**Comment by codeguy** [comment]
I'm not at all familiar with IIS, and I believe this issue is specific to that server. If anyone else can chip in and provide a solution for this, that'd be much appreciated. Until then, I'm lowering the priority of this ticket.

**Comment by phaseinducer** [comment]
I run a WAMP server with the latest dev version and I had a similar problem : my URI root was "\" so all my generated URLs were incorrect. This is due to the different behaviour of dirname() on Windows, called in Uri::getBaseUri() (line 71).

I fixed it like this :
    $baseUri = strpos($requestUri, $scriptName) === 0 ? $scriptName : dirname($scriptName);

replaced by :
    $baseUri = strpos($requestUri, $scriptName) === 0 ? $scriptName : str_replace('\', '/', dirname($scriptName));

It's not very pretty but effective.
I tested it with and without a controller call and also with the app installed in a sub-directory.

**Comment by codeguy** [comment]
Nice! If you want to send a pull request I can pull your code and credit you with the change. Else I'll add this in myself later today.

**Comment by phaseinducer** [comment]
I have no fork for the moment so you can make the change, yes.

**Comment by codeguy** [comment]
Pulled in, pushed to master and develop.
