### ISSUE TITLE
issue whith flash middleware

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#640]
Trying to hide the flash messages box if there's no flash message, 
I tested the number of flash messages in my `Slim\Middleware\Flash` with a simple `count` but I get `1` when I've no message.

**Comment by codeguy** [comment]
Can you post a very simple app that demonstrates this?

**Comment by lalop** [comment]
Here's a simple app.php :

``` php
$app = new \Slim\Slim(array(
    'templates.path' => './'
));
$app->get('/',function() use($app){

        return $app->render('view.php');

});

$app->run();
```

and the view.php

``` php
<?php
var_dump(count($flash));
```

that display `int 1`

**Comment by tuupola** [comment]
It is because `$flash` is an instance of `Slim\Middleware\Flash` which contains the flash messages. Slim documentation says:

> Flash messages are persisted with sessions; sessions are required for flash messages to work. Flash messages are stored in $_SESSION['slim.flash'].

So you could do something like `var_dump(count($_SESSION['slim.flash']));`

**Comment by lalop** [comment]
Or maybe Slim\Middleware\Flash can implement Countable ?

**Comment by lalop** [comment]
I can do a pull pull request with that if we are agree on the solution ( and on the issue of course )

**Comment by tuupola** [comment]
+1 on implementing Countable if it is ok with Josh.

**Comment by codeguy** [comment]
Implementing countable is fine. Send PR to the release-2.3.3 branch. Be sure you create your feature branch from the current master branch, NOT the develop branch... a lot has changed in develop that already resolves this.

**Comment by lalop** [comment]
hum... ok.
When do you think merging the develop branch into master ?

**Comment by codeguy** [comment]
Not for a few weeks at least.
