### ISSUE TITLE
Range request support

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#646]
I was wondering maybe it would be useful to add range request support to slim.

```
request:
Range: items=0-24
(items|bytes)=(\d+)-(\d+)

response
Content-Range: items=0-24/66
(items|bytes)=(\d+)-(\d+)/(\*|\d+)
Accept-Ranges: items=0-66
(items|bytes)(?:=\*|(\d+)-(\d+))?
```

Of course there are many possible scenarios, but we can handle all of them with simple regex patterns and a small parsing logic, so it would be easily customizable if needed. Btw. if there would be a default setting for this, people would rather use that instead of inventing a custom solution. What's your opinion?

**Comment by silentworks** [comment]
I think this should be done on a per project basis, so probably better as a custom solution, with the changes to Slim 3, this can be easily implemented by anyone.
