### ISSUE TITLE
Path parsing returns bad script name if Apache DocumentRoot includes trailing slash

### ISSUE THREAD

**Issue by jeremykendall** [slimphp/Slim#653]
`\Slim\Environment::__construct()` generates a bad `$env['SCRIPT_NAME']` if Apache `DocumentRoot` directive  includes a trailing slash.  Per the Apache [`DocumentRoot` documentation](http://httpd.apache.org/docs/2.2/mod/core.html#documentroot), the directive should not include a trailing slash.

**Comment by codeguy** [comment]
Closing. This is fixed in the current release.
