### ISSUE TITLE
Encrypted Session Handling

### ISSUE THREAD

**Issue by OriPekelman** [slimphp/Slim#66]
I saw you wanted to add encrypted session cookie.
You could use https://github.com/AF83/session-cookie which is working quite nicely

**Comment by codeguy** [comment]
Thanks for the suggestion! I've contacted the author of the code to see if this is okay.

**Comment by OriPekelman** [comment]
Hi,

It is kind of you to ask for agreement, but the code is BSD, so you need not ask permission. I am sure François the author will be honored to have you use it. And anyway you can consider this message as a formal accord. Also have a look at Toupti which follows a very similar logic to Slim, there might be stuff there that could interest you (we will be pushing a new version soon I hope).

Ori Pekelman
CTO AF83

**Comment by codeguy** [comment]
I know it's BSD, but I figured I'd be courteous and ask anyway :) Thanks!
