### ISSUE TITLE
plugin access rights

### ISSUE THREAD

**Issue by tobsn** [slimphp/Slim#67]
## the plugin example from the docu states:

$currentRoute = Slim::router()->current();
## if ( preg_match('@^users/@', $currentRoute->pattern) ) {

result here is:
PHP Fatal error:  Cannot access private property Route::$pattern

**Comment by codeguy** [comment]
This is caused by the recent interface changes to the Router and Route classes. Change `$currentRoute->pattern` to `$currentRoute->getPattern()` instead. I'll fix this in the repo tonight.

**Comment by tobsn** [comment]
arg sorry, should've seen that after editing TemplateDirectory to getTemplateDirectory... ;)
