### ISSUE TITLE
undefined method Slim\Slim::patch()

### ISSUE THREAD

**Issue by brushmate** [slimphp/Slim#672]
I installed Slim with composer using the guide on the website. I want to create a patch route, but the method is not defined inside `Slim.php`. In this repository it is defined. Why is it missing in my copy?

**Comment by erizocosmico** [comment]
What is your Slim version?

**Comment by brushmate** [comment]
Version is 2.2.0. I see that 2.3.5 is the current version, but if I run `composer update` it says that everything is up to date.

This is my `composer.json`file:

```
{
  "require": {
    "slim/slim": "2.*"
  }
}
```

I just cloned the repo and now it works. Thanks so far. Maybe someone forgot to update the composer package?

**Comment by brushmate** [comment]
I set the version in the composer file to "2.3.*" and now composer gives me some output which says that I don't have mcrypt installed.

**Comment by tuupola** [comment]
Even though documentation says otherwise mcrypt extension is now mandatory. You can work around it by using fake mcrypt.

https://github.com/tuupola/slim-fake-mcrypt

**Comment by brushmate** [comment]
I'm using XAMPP which ships with mcrypt, but I have installed another copy of php, too. The version without mcrypt comes first in my PATH, so I just added the XAMPP php before the other one. But thank you nevertheless.
