### ISSUE TITLE
Default template -setting is not used always

### ISSUE THREAD

**Issue by NiLon** [slimphp/Slim#673]
## Problem

Default template path can be set __construct of Slim class. But this setting will go live once `$app->render()` is called or `$app->view($app->view())`. However `$app->view()` does not set default template path. This will cause failure of call `$app->view()->display('foo.html')`. In contract `$app->view($app->view())->display('foo.html')` does work but will add extra redundancy. Also it's not good idea to assume that `$app->render()` has been called.
## Why is this a problem

Sometimes it's useful to get output of view (template) before it is at response object.

``` php
$nav = $app->view()->fetch('navigation.html');
$app->render('page.html', ['navblock' => $nav]);
```
## Possible fix

Problem is at Slim.php at method view(). Default template path should be set outside if-statement.

**Comment by ziadoz** [comment]
I've experienced the same issue. It looks like the `templates.path` config setting is only passed to view when `render()` or `view()` are called from the Slim application.

Perhaps I'm wrong, but in the Slim constructor it seems like the `template.path` should be set when the view is put into the dependency injection container:

``` php
// Default view
$this->container->singleton('view', function ($c) {
    $viewClass = $c['settings']['view'];
    $templatesPath = $c['settings']['templates.path'];

    $view = ($viewClass instanceOf \Slim\View) ? $viewClass : new $viewClass;
    $view->setTemplateDirectory($templatesPath);
    return $view;
});
```

I'm happy to submit a pull request if @codeguy thinks this is the best solution. In the meantime, the simplest work around is to set the view using `$app->view(new Slim\View)` **after** your configuration.

**Comment by codeguy** [comment]
Solution looks great. Please send a PR to the master branch when ready and I'll pull in.

**Comment by ziadoz** [comment]
Sure. I've made a pull request: https://github.com/codeguy/Slim/pull/675

**Comment by codeguy** [comment]
This is resolved in https://github.com/codeguy/Slim/commits/release-2.3.6. Will release into master branch soon.
