### ISSUE TITLE
Allow local variables to be passed into templates.

### ISSUE THREAD

**Issue by ziadoz** [slimphp/Slim#676]
The only way to pass local variables along to a 'partial' template in Slim at the moment (as far as I can see), is to set them globally on the main view object:

``` php
$app->view->set('foo', 'bar'); // Data for page.php template.

return $app->render('layout.php', array(
    'partial' => $app->view->fetch('page.php'),
));
```

It'd be cool if the view object's `render()`, `fetch()` and `display()` methods took, as a second parameter, an array of data that gets made available only to the template being rendered:

``` php
$app->view->set('foo', 'bar');

return $app->render('layout.php', array(
    'partial' => $app->view->fetch('page.php', array('foo', 'baz')), // Overrides main 'foo' value.
));
```

It seems like this would be easy to implement by adding another parameter to the `render()` method, then creating and extracting a temporary array that's an `array_merge()` of the view's global data and the new local data. The only implication I can think of is that accessing the `render` functionality through the `Slim` object will behave differently as the data will be globally available in all templates.

I'd be interested to know people's thoughts on this idea. Thanks.

**Comment by ziadoz** [comment]
I've got a commit ready for this by the way: https://github.com/ziadoz/Slim/commit/2fb53177b3631545b6f7d935bfffb30320b1992f

**Comment by codeguy** [comment]
Merged into https://github.com/codeguy/Slim/commits/release-2.3.6
