### ISSUE TITLE
App::finalize output buffer handling issue

### ISSUE THREAD

**Issue by JonEngle** [slimphp/Slim#677]
In the development branch, App.php starting on line 1264, it currently looks like this:

```
                while (!feof($body)) {
                    ob_start();
                    echo fread($body, 1024);
                    echo ob_get_clean();
                    ob_flush();
                }
```

It should be:

```
                while (!feof($body)) {
                    ob_start();
                    echo fread($body, 65536);
                    echo ob_get_clean();
                    ob_end_flush();  <------change to ob_end_flush
                }
```

otherwise, for large files, the entire file content is buffered before sending, since ob_flush doesn't book-end the ob_start.

**Comment by codeguy** [comment]
Do you want to send a PR or do you mind if I make this change? Want to make sure you receive credit if you want.

**Comment by JonEngle** [comment]
Nah, go ahead and make the change.  Thanks though!

Jon
