### ISSUE TITLE
Enhancement: handle large PUT/POST operations

### ISSUE THREAD

**Issue by JonEngle** [slimphp/Slim#678]
I have a need to be able to PUT or POST a large body (potentially >1GB) in a REST API.  Currently working with the development branch (need to stream large files down too), and have a solution that's working, but may not be optimal.  First, modified Environment so that it doesn't load the body into 'slim.input' on construction.  Second, overloaded get from Collection so that when 'slim.input' is requested, the first time it will load it from php://input (what the constructor was doing).  I also modified ContentTypes.php (which I pulled from trunk and modified to work in the dev branch) so that it doesn't touch slim.input unless it's a parse-able content type.  Making those changes allows me to use php://input directly in my handler for the large PUT operation.  Maybe there's a better/nicer way to do this?

**Comment by silentworks** [comment]
Closing this off, if you would like to re-raise this please open on the forum. http://help.slimframework.com
