### ISSUE TITLE
Remove mcrypt as a requirement

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#683]

**Comment by codeguy** [comment]
Added in https://github.com/codeguy/Slim/commits/release-2.4.0

**Comment by ysangkok** [comment]
Installing using composer, I get _slim/slim suggests installing ext-mcrypt (Required for HTTP cookie encryption)_. How can this be, if mcrypt was removed?

**Comment by OptimusCrime** [comment]
It is still present in `composer.json` in the 2.x branch: https://github.com/slimphp/Slim/blob/2.x/composer.json

**Comment by tuupola** [comment]
It is not a requirement. It is suggestion. Ie. you can install `ext-mcrypt` if wanted but it is not required.
