### ISSUE TITLE
redirect doesn't take into account base path

### ISSUE THREAD

**Issue by atykhonov** [slimphp/Slim#684]
There is a very simple Slim application:

<?php
require 'Slim/Slim.php';
\Slim\Slim::registerAutoloader();

$app = new \Slim\Slim();

$app->get('/hello/:name', function ($name) {
    echo "Hello, $name";
});

$app->get('/redir', function () use ($app) {
    $app->redirect('/hello/me');
});

$app->run();
?>

This application is defined in the home.php file so the valid request could be as:

http://localhost/home.php/hello/test

The issue is that that $app->redirect method (which will be triggered on http://localhost/home.php/redir request) will not work as expected. It redirects to the http://localhost/hello/me but not to the http://localhost/home.php/hello/me/.

**Comment by charlie-s** [comment]
Just out of curiosity, do you have any .htaccess rewrite rules in play? What happens if you redirect to "hello/me" instead of "/hello/me"?

**Comment by arsenetar** [comment]
I use:

``` php
$app->redirect($app->urlFor('routeName', array('param' => 'value'));
```

This does require named routes though as in the [docs#Route Names](http://docs.slimframework.com/#Route-Names).

I'm not sure if you would always want the application to add the base url to every redirect method not starting with http(s):// as then you would end up needing a http/https helper.  Probably best to use urlFor() as that is what it is for.

**Comment by codeguy** [comment]
What @arsenetar said.
