### ISSUE TITLE
Flash messages aren't available in views.

### ISSUE THREAD

**Issue by ziadoz** [slimphp/Slim#685]
It looks like flash messages aren't made available to the view. I'm unsure about the best way to fix this, hence no pull request. Any thoughts?

**Comment by codeguy** [comment]
They should be available in the view in variable `flash`. First, make sure you have activated a session with `session_start()` before you instantiate the Slim app. Next, make sure you are using the latest version of Slim... 2.3.5 currently. If it still fails, let me know.

**Comment by ziadoz** [comment]
Hmm, weird. I've cleared my cookies and everything works fine now. My mistake.
