### ISSUE TITLE
ContentType Middleware unable to set proper request data for POST

### ISSUE THREAD

**Issue by foush** [slimphp/Slim#687]
I am using Restangular to make restful calls to my API powered by Slim. I am having an issue where Restangular sends post requests with the proper Content-Type header

Content-Type:application/json;charset=UTF-8

However the request body is a json string of the parameters. I found the ContentType middleware, and added it to my API, however it looks like it is updating the environmental 'slim.input' value too late for the request resource to update. Further it looks like the Request service would ignore the parsed array (it is looking for string data in 'slim.input' environment variable)

Is there a proper way I should be using the ContentType middleware in conjuction with Slim? Ought I not use the request resource at all when handling API Post requests?

**Comment by foush** [comment]
To follow up: it appears from this question that the correct way of getting data is by using $app->request->getBody() to get the params for such an instance

http://help.slimframework.com/discussions/questions/393-interpret-json-data-with-in-app-put

In a future release, it would be ideal for the posted data to appear in when using $app->request->post()

**Comment by codeguy** [comment]
Like @fousheezy said, you can fetch the raw request body with `$request->getBody()` and run that through `json_decode()`. The ContentTypes middleware will be removed from Version 3... so be sure you send any potential pull requests here https://github.com/codeguy/Slim-Middleware
