### ISSUE TITLE
IIS7 path info failure by url rewrite

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#689]
I have an IIS7 on localhost for testing purposes. With this web.config rewrite settings:

``` xml
        <rewrite>
            <rules>
                <rule name="Imported Rule 1" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <action type="Rewrite" url="service/bootstrap.php" appendQueryString="true" />
                    <serverVariables>
                        <set name="SLIM_MODE" value="development" />
                    </serverVariables>
                </rule>
            </rules>
        </rewrite>
```

I require SLIM in the `bootstrap.php`.

Now by this settings the routing fails because of this line:

https://github.com/codeguy/Slim/blob/master/Slim/Environment.php#L143

For example by the `/secret` uri the variables are:

``` php
    $requestUri = '/secret';
    $physicalPath= '/service'
```

So the path info will be an empty string. If the `$requestUri` is longer than the `$physicalPath`, then the path info will be a truncated `$requestUri`. I don't have multiple test environments, so I don't want to send a pull request. If I fix this on IIS, maybe it will break something on apache, etc...

Comparing the beginning of the `$requestUri` with the `$physicalPath` won't help I think. You have to detect somehow whether the request url was rewritten or not, or use other environmental variables...

In my case using the `$requestUri` without truncation helped, but this is highly dependent on the current operation system, http server settings, etc...

**Comment by silentworks** [comment]
Can't test as we don't have a IIS server stack to test it on, closing for now.

**Comment by ghost** [comment]
I hardly believe you don't have access to any windows computer. http://msdn.microsoft.com/en-us/library/ms181052%28v=vs.80%29.aspx
