### ISSUE TITLE
plugins

### ISSUE THREAD

**Issue by tobsn** [slimphp/Slim#69]
within the hooks - how would you pass on the Slim object to classes created within hooks and exchange data with the object? tried to pass on Slim::$app but its private.

thanks!

(sorry, for bothering you all day long - trying to get used to the framework and im writing some plugins right now)

**Comment by codeguy** [comment]
Slim is still very very new, so I'm 100% open to your suggestions. I'll add in an accessor for the app instance.

**Comment by codeguy** [comment]
I have just pushed a commit to `develop` that adds `Slim::getInstance()` which returns the Slim application object.
