### ISSUE TITLE
Pimple Dependances

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#690]
Since Pimple is a dependance of a lot of libraries why do you do a copy of it under Slim\Pimple instead of than add it in composer.json ?

**Comment by designermonkey** [comment]
This is something I was going to raise also, I'm working on the Pimple/Collection structure at the moment, and was going to suggest moving Pimple out of Slim, and as you say, just requiring it via composer

**Comment by erizocosmico** [comment]
It makes sense. +1 to require it via composer.

**Comment by lalop** [comment]
That will be the first Slim dependance, just for one class.
Maybe that's make more sense to build a new container ( based on Pimple ) than make a dependance.
I think Pimple is great for final user who doesn't want to code this feature or for library that has a lot of dependances but for Slim... I'm not sure.

**Comment by designermonkey** [comment]
We had a good old chat in the working group about this exact topic, and the choice was to include Pimple. I didn't take it as literally as @codeguy meant, by physically including it in the project...

@lalop I can see your point actually, we shall wait to hear what @codeguy's thoughts are on it.

**Comment by codeguy** [comment]
I've always wanted to keep Slim self-sufficient with zero third-party dependencies. But at this point in time that line of thought is swimming against the tide. Since 3.0 will be a big refactoring and reorganization, I think we should probably go ahead and move Pimple as a Composer dependency rather than keep it in core.

**Comment by lalop** [comment]
Maybe that can come with the 3.0 ?

**Comment by codeguy** [comment]
@lalop Yep that's what I'm thinking.

**Comment by codeguy** [comment]
Just pushed a fix for this to the develop branch.
