### ISSUE TITLE
Query string causing 404

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#692]
the route is `/user`, if i visite `http://localhost/user`, works fine. 

but if i visite `http://localhost/user?id=23`, it cause 404 error.

**Comment by codeguy** [comment]
1. What version of Slim?
2. What web server?
3. Are you sure your rewriting is setup correctly?
4. Can you provide a sample Slim app that demonstrates?

**Comment by ghost** [comment]
@codeguy here is my slim app bootstrap: https://github.com/towry/Slim-app-bootstrap/blob/master/public/web.config

the version is latest, the web server is `IIS`.

**Comment by codeguy** [comment]
@silentworks You are more familiar with IIS... can you help troubleshoot this?

**Comment by ghost** [comment]
@codeguy ok, fixed it. it's the rewrite problem, the properly rewrite rule should be:

```
    <rewrite>
        <rules>
            <rule name="Slim Rewrite URLs" enabled="true" stopProcessing="true">
                <match url="^(.*)$" ignoreCase="true" />
                <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                </conditions>
                <action type="Rewrite" url="index.php" appendQueryString="true" />
            </rule>
        </rules>
    </rewrite>
```

**Comment by codeguy** [comment]
Awesome. Glad you figured it out. Closing.

**Comment by hh0210** [comment]
Hello, i facing this same problem on nginx.

http://localhost/user?id=23, it cause 404 error.

Nginx Config:
    location / {  
      try_files $uri $uri/ /index.php?$args;
  }

Please help.

**Comment by vyanez** [comment]
Hello everyone, I have been in trouble setting up Slim framework on my server running nginx 1.4.6.

if I run this query (http://api.scyllas.com/ http://api.scyllas.com/index.php) everything works work. The problem is when I try to get response from another method like http://api.scyllas.com/foo or http://api.scyllas.com/index.php/foo

I have done many configurations on my nginx server but nothing has worked.

here my nginx config file:


server {
	listen 80;
	server_name api.scyllas.com;
	root /home/ftpuser/sites/apiscyllas;
	index index.php index.html index.htm;
	passenger_enabled on;

	try_files $uri $uri/ /index.php$is_args$args;
   	 location /index.php {
        	fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
		fastcgi_connect_timeout 3s;     # default of 60s is just too long
        	fastcgi_read_timeout 10s;       # default of 60s is just too long
        	include fastcgi_params;
        	fastcgi_pass 127.0.0.1:9000;    # assumes you are running php-fpm locally on port 9000
    	}
}

if I add a .htaccess file nothing happens as well.

Please help me!!!

**Comment by celebritydeveloper** [comment]
> location / {
> try_files $uri $uri/ /index.php;
> }

location / {
try_files $uri $uri/ /index.php;
} 

Remove the ?$args

**Comment by celebritydeveloper** [comment]
> Hello everyone, I have been in trouble setting up Slim framework on my server running nginx 1.4.6.
> 
> if I run this query (http://api.scyllas.com/ http://api.scyllas.com/index.php) everything works work. The problem is when I try to get response from another method like http://api.scyllas.com/foo or http://api.scyllas.com/index.php/foo
> 
> I have done many configurations on my nginx server but nothing has worked.
> 
> here my nginx config file:
> 
> server { listen 80; server_name api.scyllas.com; root /home/ftpuser/sites/apiscyllas; index index.php index.html index.htm; passenger_enabled on;
> 
> ```
> try_files $uri $uri/ /index.php$is_args$args;
>  location /index.php {
>     	fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
> 	fastcgi_connect_timeout 3s;     # default of 60s is just too long
>     	fastcgi_read_timeout 10s;       # default of 60s is just too long
>     	include fastcgi_params;
>     	fastcgi_pass 127.0.0.1:9000;    # assumes you are running php-fpm locally on port 9000
> 	}
> ```
> 
> }
> 
> if I add a .htaccess file nothing happens as well.
> 
> Please help me!!!


Remove the $is_args$args;

try_files $uri $uri/ /index.php;
