### ISSUE TITLE
Slim::root() doesn't handle Alias

### ISSUE THREAD

**Issue by kperry42** [slimphp/Slim#694]
My Apache config uses an Alias to set the application's root folder to a folder that is not under the server's DocumentRoot.

This causes Slim::root() to return erroneous value, as it uses $_SERVER['DOCUMENT_ROOT'] to calculate its root.

Seems like it should use $_SERVER['SCRIPT_FILENAME'].

**Comment by codeguy** [comment]
@kperry42 Do you want to submit a PR so you can get credit for the fix? If not I can go ahead and do this, but wanted to check with you first.

**Comment by kperry42** [comment]
Nah, that's OK, go ahead and do it.  I'm not set up to do that yet.

**Comment by codeguy** [comment]
Fixed. https://github.com/codeguy/Slim/commit/73a8daab6ab395d0aa38a0de4af21a0b720e8367

**Comment by codeguy** [comment]
FYI this is in the develop branch and will be rolled out with the 3.0 release.
