### ISSUE TITLE
implement Stack PHP

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#696]
I just discovered stack php that is a kind ok rack for php ( if I correctly understand ).
I think that can be a good point for Slim to implement it to share middlewares with other frameworks.
It shouldn't be a big deal, isn't it ?

**Comment by codeguy** [comment]
StackPHP seems tightly coupled to the \Symfony\HttpFoundation\Request class, right? I'm looking here:

http://api.symfony.com/2.3/Symfony/Component/HttpKernel/HttpKernelInterface.html

That makes it a non-starter.

**Comment by lalop** [comment]
Yes it's a kind of alias more than a real project, but that can be a good initiative for modern php developpement.

**Comment by codeguy** [comment]
I agree. Conceptually it is nice, but we really need a PSR interface for HTTP requests for this to be usable for projects that don't use Symfony. Slim already has a middleware system in place that pretty much does exactly this.

**Comment by lalop** [comment]
ok,
I understand
Indeed we need a psr interface and not one from an extra library.
