### ISSUE TITLE
Default Value for request->params()

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#699]
Hi,

I'd love to see `$default` as an optional Parameter in `$app->request->params()`.

Within my Application I have to handle POST and GET operations on a single Route where no route parameters are set. So I could access querystring parameters using `$app->request->params('key')` but have to check first if that is set or not and need to handle that. On the other hand it's possible to use `$app->request->get('key', 'default')`. That would be awesome to have that way on to handle defaults on `params()` too.

Any chance this makes it way into one of the next versions?

// edit: I'm running Slim 2.4.0 on PHP 5.4.28 if that's interesting in any way.

**Comment by codeguy** [comment]
If you can shoot over a PR to the release-2.4.1 branch, I can have that merged tomorrow.
