### ISSUE TITLE
Slim Hooks and Slim Filters

### ISSUE THREAD

**Issue by bobdia** [slimphp/Slim#70]
I noticed that Slim::hook() passes self:$app to listeners as the only argument. Also, the example hook callbacks in the wiki don't define any arguments. So, I'm thinking that maybe hooks should use Slim::getInstance() instead.

On another note, listeners are invoked like this:
    foreach( self::$app->hooks[$name] as $listener )
        $listener(self::$app);

We should definitely change that to:

```
call_user_func($listener, self::$app);
```

which is the correct way to invoke callables.

I've forked Slim and fixed this along with implementing filters as a companion to hooks.

Example:
    // set up a filter
    Slim::filter('html', function ($var) {
        return strip_tags($var);
    });

```
// ... and later apply the filters
echo Slim::applyFilter('html', $html);
```

I will push my "filter_hooks" branch to Github later today. Let me know what you think.

**Comment by codeguy** [comment]
Brilliant. Will pull in your changes to the `develop` branch in the next day or so when I have some free time. Thanks!

**Comment by bobdia** [comment]
What do you think about priorities for hooks/filters?

Here is how WP does it for illustration purposes. The code is a bit dirty but we can do better than that: http://core.trac.wordpress.org/browser/tags/3.0.3/wp-includes/plugin.php

Priorities seem like a must if one has to fine-tune multiple plugins operating on the same hooks.

**Comment by bobdia** [comment]
Here are my changes: https://github.com/bobdia/Slim/commit/a2f4ff7491ff7df9fbe7481cf97984cf13aa771f

I need suggestions for default hooks to add.

**Comment by codeguy** [comment]
@bobdia Is there a reason you updated the `Slim::clearHooks` and `Slim::getHooks` methods so that it works for both hooks and filters? I see that you have added new, separate methods just for filters (preferable), and the changes to `Slim::clearHooks` and `Slim::getHooks` seem redundant. Just wondering.

Default hooks are already in place. Do you mean default Filters? Some filters off the top of my head:

stripTags
sanitize / xss filtering

Will let you know of others I think of. It may be beneficial to make filters also accept arrays (and if the argument is an array, call the filter on the array using array_map).

**Comment by codeguy** [comment]
@bobdia Nevermind about the `Slim::clearHooks` and `Slim::getHooks` changes. I see what you're doing and that's fine. Keeping it nice and DRY. I'll pull in the code shortly once you give me the ok regarding default filters.

**Comment by bobdia** [comment]
I should have started a different issue for the filters.

Doing an array_map by default would be a bad idea when you want to filter the array as a whole. I think just running array_map inside the callback function would be best. 

I mean default filters but not exactly like that. Think "slim.before.flush", so plugins can filter content before Slim flushes the buffer. I'm not sure where are some good places to add applyFilter() in the Slim core, so that's what I was asking for. I've been going through Slim's code myself, so I'll have a better idea of how everything fits together soon. (btw I've commited some minor tweaks in my 'develop' branch)

**Comment by codeguy** [comment]
Can you explain a little more about your filters implementation? Just an overview so we're on the same page. Thanks!

**Comment by bobdia** [comment]
I can't explain much at this point, I should use it a little first. I'll try to work on a plugin that makes use of filters.

I've been working with some WP themes and plugins and that was what inspired me to add this in Slim. This page lists all the filter hooks available in Wordpress and might provide some further insight: http://codex.wordpress.org/Plugin_API/Filter_Reference

**Comment by codeguy** [comment]
@bobdia This thread was before our IRC chat.... so feel free to move forward as you see fit as we discussed. Thanks!

**Comment by codeguy** [comment]
@bobdia Any update on this?

**Comment by bobdia** [comment]
I think keeping them separate is best. Hooks are only about side-effects. Filters only operate on values passed to them. Also makes code easier to search. 

I'll leave the decision to you.

**Comment by codeguy** [comment]
@bobdia If you feel having separate methods for filters and hooks is best, that's fine. Ultimately, hooks appear to be filters that are passed the application instance as their argument. So it's basically only about semantics as far as I can see.

Are you satisfied with your code at this point? Do you have all necessary default hooks and/or filters in place?

**Comment by bobdia** [comment]
I agree it's just semantics and it bugs me the same way. I made a few changes and combined the two. I guess developers will have to document their hooks so other people will know if it's a filter or not.

However, one of my original points was that the existing hooks should not have any arguments. If they need to interact with Slim:$app they can use Slim::getInstance(). This way we don't have to figure out whether to pass Slim::$app to some of the hooks.

**Comment by codeguy** [comment]
Nice. I'll have a look at your changes tonight and get them pulled in soon.

**Comment by bobdia** [comment]
I forgot to push my changes the other day, will do later today.

**Comment by codeguy** [comment]
@bobdia Send a pull request when your changes are ready. Will be releasing 1.1 tomorrow afternoon.

**Comment by bobdia** [comment]
The combined code is ready and I've also added a priority system. My first pull request, so no idea if I did it right.

**Comment by codeguy** [comment]
@bobdia Your pull request was available this morning... I just looked again and it was gone. Did you remove it? I'm going to move your hook and filter updates to the next 1.2 release. Going to go ahead and release 1.1 as is.

**Comment by bobdia** [comment]
It's there in closed tickets. I guess my accidental clicking on the "Comment and close" button was bad timing. I'm keeping up with your develop branch, so it should be easy to pull whenever you get to it.

**Comment by codeguy** [comment]
@bobdia Can you send me another pull request with your changes?

**Comment by codeguy** [comment]
This has (finally) been pulled into the `develop` branch. Will provide foundation for route-specific middleware coming up next.
