### ISSUE TITLE
'Secure' => true breaks session middleware under stable, ubuntu 13.10

### ISSUE THREAD

**Issue by daniel-dressler** [slimphp/Slim#701]
When I set 'secure' => true, sessions appear to break, inspecting with firefox the server responds with a set-cookie like: "slim_session=a:1:{s:10:"slim.flash";a:1:{s:5:"error";s:14:"Login+required";}}; path=/; expires=Mon, 16-Dec-2013 03:34:46 UTC; secure"

Except firefox does not send this cookie upon the next request. When I turn off secure the server will send a cookie like the above but without the "secure" and sessions work. Since the "secure" appears to not be including a hash this seems odd since there is no way to verify the cookie.

The installation of slim was done by extracting the "manual install" zips into my working directory.

I have confirmed that mcrypt is installed, php even reports true when I test for the module and the extra MCRYPT_\* defines are present. I have tried with both the default cipher and the blowfish cipher. cupher_mode is CBC in both cases.

Since I would like to use encrypted sessions for storing my auth tokens this is a painful bug. I have tried using the "latest" download but the app crashed with an error in slim.php

**Comment by codeguy** [comment]
Thank for the detailed report. Can you provide a very simple example app (via pastebin or gist) that can help me duplicate this?

**Comment by daniel-dressler** [comment]
That is a reasonable request, but I'm hesitant to do that since I'm assuming regular usage will have been tested thus I'd need to bi-sect my code. On the other hand if you see the full thing (excluding the templates its maybe <200 lines) you might be able to spot the issue right away.

I have nothing sensitive in my app so could I zip and email it to you in private? I promise to change the secret key afterwards.

**Comment by codeguy** [comment]
If you are comfortable sending your custom code, I'm happy to look through it. Be sure you send any steps necessary to setup the app and reproduce the issue. You can reach me at the email listed on my GitHub profile.

**Comment by daniel-dressler** [comment]
Sure, I'll go package it up. There should be no special steps that I know of. The app is running off my localhost and I'm deving on ubuntu 13.10 with debian's apache and php.

**Comment by codeguy** [comment]
Awesome. Give me a few days to look it over. If you don't hear from me by Wednesday, nudge me here or on Twitter.

**Comment by daniel-dressler** [comment]
Thank you codeguy, I'll mark Wednesday on my calendar and I promise to nudge you if needed.

**Comment by daniel-dressler** [comment]
I should mention that if you need to please feel free to show the app to the other maintainers. It's less that I want to keep it private and more that I have yet to talk with my group members and the pwg's chairman if it can be open sourced. The app itself is related to pwg.org, in case curiosity hits.

**Comment by codeguy** [comment]
I've glanced at this quickly. When you set the `SessionCookie` middleware `secure` setting to `true`, it will only work for requests (and future requests) sent over HTTPS. Can you confirm this is the case on your end?

**Comment by daniel-dressler** [comment]
Thank you codeguy that would explain it. I had assumed the secure refereed to if the session got encrypted. Of course my localhost is all http.

So how would I turn on encryption?

**Comment by codeguy** [comment]
HTTPS is established by your web server configuration (and by having a self-signed certificate or a certificate provided by a CA like Comodo, Verisign, etc.) and is beyond Slim's control. You're better off talking with your web host's support team to get that setup.

If you want to use Cookie encryption within Slim, you can use the `cookies.*` application settings. See http://docs.slimframework.com/#Application-Settings for more info.

**Comment by daniel-dressler** [comment]
Thank you codeguy! Sorry for missing this!

**Comment by codeguy** [comment]
No worries. Happy to help!
