### ISSUE TITLE
[proposal] extract all http stuff from the slim class

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#702]
I'm wondering how to add cli in my app based on Slim.
I'm not sure but I think we could use a kind of slim app to do so, but with cli's input instead of HttpRequest and cli's output instead of HttpResponse.
Maybe the Router has to be revisited to.

Do someone knows how that works between rack and rake in rails ?

**Comment by designermonkey** [comment]
In version 3, there will be lots of interfaces available which will allow different aspects of the framework to be replaced after initialisation, so the following could be an example

```
$app = new \Slim\Slim();

$app['request'] = $app->share(function ($app) {
        return new MyCLIRequestClass();
});

$app['response'] = $app->share(function ($app) {
        return new MyCLIResponseClass();
});

$app->run();
```

Each class would be required to follow the relevant interface to ensure that the application can use it correctly.

The intention for these interfaces is to allow more control, and your use case is a great example of this.

**Comment by lalop** [comment]
Yes, I think that can be great to keep in mind some non-http case.
But the other point is the router, what does it become ?
Do we have to override the web router ?

**Comment by designermonkey** [comment]
I suppose it all depends on the use case. The plan is to be able to make as many parts of the app swappable as can be without compromising the functionality of the app itself.

I must say, I've not done any CLI work with PHP, so would be interested to hear any ideas you have on how it could work.

**Comment by lalop** [comment]
Me too :-)
I will think about it but I have to take a look at the version 3 before.

**Comment by designermonkey** [comment]
It has to be kept in mind that Slim is a request -> response routing framework more than anything.

**Comment by lalop** [comment]
Yes here is the point but the midleware part of it and the request -> response are interesting for command line too.

**Comment by lalop** [comment]
What about adding a command method to Slim ?
We can imagine something like :

``` php
/* index.php */
// include common configuration, boot slim app...
$slim = include 'config.php'; 
$slim->get('foo', function( $req ){ ... });
[...]
```

``` php
/* command.php */
$slim = include 'config.php'; 
$slim->command('bar', function( $req ){ ... });
[...]
```

**Comment by silentworks** [comment]
As with what @designermonkey stated, Slim is a request response framework, I think CLI work should be done with something like Symfony console.

Closing this off on that note, reopen if necessary.
