### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by tobsn** [slimphp/Slim#71]
## slim on freenode

talking over the issue tracker is kinda dumb. ;)

**Comment by iromli** [comment]
nice idea, a public channel would be great :)

**Comment by tobsn** [comment]
well im in there... ;)

**Comment by codeguy** [comment]
Hey guys. Sorry been travelling past few days. I'm registered on freenode as "joshlockhart". The official room is ##slim. I'll try to hang out there as much as I can during the day when I'm not busy with the day job.

**Comment by bobdia** [comment]
Cool. By the way you can also setup a hook to post commit messages on the IRC channel. 

Go to the repo's page, click the 'Admin' buttone next to Watch/Fork. Then 'Service Hooks' > IRC and input the following:

Server: irc.freenode.net
Port: 6667
Channel: ##slim
Nick: SlimCommiter
SSL: false
Active: true
