### ISSUE TITLE
Request::getScheme needs extra functionality

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#711]
If the code exists behind a proxy, whether it be a load balancer or caching server, or another type of proxy server, then `HTTPS` may not be set on the proxy-offloaded data.

I have experienced this with one of our company setups (although not using Slim).

For our specific circumstance, we used `htaccess` rules to identify an extra header being sent by the proxy, namely `HTTP:X-Forwarded-Proto` which had a value of either `http` or `https`.

I'm not sure how the header would come through in Slim's environment class, but it should be identified in the `getScheme` method

**Comment by designermonkey** [comment]
Looking at: http://en.wikipedia.org/wiki/List_of_HTTP_header_fields

maybe we should also check for `Front-End-Https`

**Comment by codeguy** [comment]
We'll want to parse this in the `\Slim\Http\Headers` class along with other special-cased headers. We can then look for this in `\Slim\Http\Request::getScheme()`.

**Comment by codeguy** [comment]
This is done. I'm not too concerned about the `Front-End-Https` non-standard header.

https://github.com/codeguy/Slim/commit/60cc1e4dc3165f268763ca46527be28d35823095
