### ISSUE TITLE
No SessionTest

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#713]
There is no test for the Session class :(

**Comment by designermonkey** [comment]
Is this because Sessions don't work on command line?

**Comment by codeguy** [comment]
Far simpler reason... I haven't had time to write one yet :)

**Comment by codeguy** [comment]
Refactoring the existing session class to make it easier to test. Will be simplifying a few things, too.

**Comment by charlie-s** [comment]
Hey @codeguy, I was playing with writing the test for the Flash class (https://github.com/codeguy/Slim/issues/713) but am having a little trouble with the Session class. Probably what you're referring to above – session values are nested a level deep (in `$_SESSION['slim.session']['slim.flash']['foo']` for example) once the `save()` method is run on the Session object. Is that what you're referring to? Need any help?

**Comment by codeguy** [comment]
I've got the session class tested... but the Flash class still needs tested. If you want to write tests for that, that would be wonderful. I would use Mockery (`composer update` to get it) to mock the Session dependency so we can focus on the Flash class in relative isolation.

**Comment by charlie-s** [comment]
The Session test is in place in `develop`, correct? Should this be closed?

**Comment by designermonkey** [comment]
Yep :)
