### ISSUE TITLE
No way to make Slim work in a subdir

### ISSUE THREAD

**Issue by aledelgo** [slimphp/Slim#720]
Hi All!

my project dir structure is like this:

```
-src
-src/apps
-src/apps/api/v1/index.php
-src/libs
-src/vendors
-src/vendors/slim {and other composer libs}
-src/index.php
-src/.htaccess
```

in the .htaccess i have

```
RewriteRule ^api/v1/(.*)$ apps/Api/v1/index.php [QSA,L]
```

the website is running on Apache2 with Php 5.4.3

Simply there is no way to make the apps/Api/v1/index.php to work...
neither the following snippets are working, both fails to 404 without errors. i've put an echo before and after and i can see the ouput of that echo, but Slim refuse to recognize the path.

```
echo "s10";
$app->get('/hello/', function () {
    echo "Hello";
});

$app->get('/api/v1/hello/', function () {
    echo "Hello";
});
echo "s20";
```

this is what i get at localhost/api/v1/hello

s10s20
404 Page Not Found

is it normal? is there any solution?

**Comment by codeguy** [comment]
And this still fails if you remove the trailing "/" from your Slim route paths? i.e. change:

```
$app->get('/hello/', function () {
    echo "Hello";
});
```

to

```
$app->get('/hello', function () {
    echo "Hello";
});
```

**Comment by zulrang** [comment]
If you're not getting a Slim error, than the problem is how you have your
directories through Apache set up.  I'm assuming your documentRoot is what
you mean by -src, and your .htaccess is in that directory?

**Comment by aledelgo** [comment]
I'm sorry for the crosspost but the discussion on this problem gone forward on the official forum:
http://help.slimframework.com/discussions/problems/5954-no-way-to-make-slim-work-in-a-subdir

You can find there, logs and other test i've done.

to summarize, actually the apache config is calling the right index.php with correct (i hope) server variables (request uri give the correct original url requested) anyway Slim seems to ignore it...
