### ISSUE TITLE
Slim 3.0 autoloader

### ISSUE THREAD

**Issue by prisis** [slimphp/Slim#725]
The autoloader in dev-branch is broken

**Comment by designermonkey** [comment]
Any errors? Suggestions on fixing it?

**Comment by prisis** [comment]
http://help.slimframework.com/discussions/questions/1214-slim-30-and-composer

**Comment by designermonkey** [comment]
I've just done some testing based on the basic info in that thread, and the autoloader is working fine as far as I can see.

The code you showed won't work, as was discussed, but the following works fine:

``` php
<?php

include('vendor/pimple/pimple/lib/Pimple.php');
include('Slim/Autoloader.php');

\Slim\Autoloader::register();

$app = new \Slim\App();

$app->get('/', function () {
    echo 'works!';
});

$app->run();
```

Edit: Sorry, forgot to say, this code is in place of the index file in the Slim package (for path relativity).
