### ISSUE TITLE
I can't set view data inside slim.after.dispatch hook

### ISSUE THREAD

**Issue by okaprinarjaya** [slimphp/Slim#726]
Helo, 
I can't set view data inside a hook, i use defined slim hook 'slim.after.dispatch' 
code example:
        class AppSlimMiddleware extends \Slim\Middleware
        {
            public function call()
            {
                $app = $this->app;

```
            if ($app->request()->isPost()) {
                $app->view()->setData('__form_data', $_POST);
            }

            $app->hook('slim.after.dispatch', function () use ($app) {
                if ($app->request()->isPost()) {
                    if (!$app->input_filter->getRulesEvaluationResult()) {
                        $app->view()->setData('__validations', $app->input_filter->getMessages());
                    }
                }
            });

            $this->next->call();
        }
    }
```

the problem is, '__validations' can not be set, if i var_dump($__validations) the result is null. BUT no problem with '__form_data'  , '__form_data' successfuly set!

**Comment by silentworks** [comment]
Please reopen on http://help.slimframework.com since this is a question.
