### ISSUE TITLE
Enhancement Idea: Paths

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#727]
I had an idea the other day to think about.

Would it be feasible to add a `paths` section to the configuration, to house all of the paths for different aspects of a developer application?

Currently there is a `templates.path` for example, and then the default Twig view that ships with Slim Skeleton defines it's cache path separately.

Something like:

``` php
array(
    'paths' => array(
        'cache' => 'path/to/cache',
        'templates' => 'path/to/templates'
    )
);
```

With our nested keys, this can then be accessed like `paths.templates` for instance.

**Comment by silentworks** [comment]
This sounds good to me, especially if the templates can take an array for its paths too, as Twig and Smarty template allow multiple template paths.

**Comment by codeguy** [comment]
I think this is more a concern of the View object and not the Slim instance, right? Version 3 will be removing the templates.path setting from the default Slim app settings and instead moving that concern to the view itself. Does this make sense?

**Comment by silentworks** [comment]
Ok cool, I will make the necessary changes to the Twig and Smarty views on a new release branch.
