### ISSUE TITLE
No default View class

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#728]
Is there scope to allow an application to be instantiated without a View class?

An app I'm scoping will need certain configuration values to have been loaded from an XML file before it can prepare the View, yet I need to have instantiated the app with a View already.

**Comment by codeguy** [comment]
Can you send me a very simple demo app? Pastebin, email, whatever is fine.

**Comment by designermonkey** [comment]
I've got around it by rebuilding the constructor.
