### ISSUE TITLE
Nested Resource Routing

### ISSUE THREAD

**Issue by francescoagati** [slimphp/Slim#73]
sholud be nice have nested resources like raile e traffic.

t::rel('/users', function () {

   // ommit the first path argument as it's not needed
   t::get(function(){
    echo 'I hit /users';
   });

**Comment by codeguy** [comment]
Very good idea. This will be perfect for those running PHP >= 5.3, but probably too cumbersome to write for PHP < 5.3. Nevertheless, I'll put this on my to-do list. Thanks!

**Comment by codeguy** [comment]
Closing this out. It's on my radar and will be revisited in the future.
