### ISSUE TITLE
How to edit template of 404 page or detect 404 error?

### ISSUE THREAD

**Issue by evivz** [slimphp/Slim#731]
Hi,
I tried a lot buy could not find any solution. Can anyone guide how can I redirect or render a specific page when ever there is 404 error?

Thanks in advance.

**Comment by leonjza** [comment]
You need to define the 404 handler. See the docs for more information here http://docs.slimframework.com/#Not-Found-Handler

**Comment by evivz** [comment]
@th3l33k  Thanks a lot. This is what I was searching for.
