### ISSUE TITLE
return of callable should be printed in output

### ISSUE THREAD

**Issue by francescoagati** [slimphp/Slim#74]
when you process the callable in this code:

$callable = $this->matchedRoute->callable();
                    if ( is_callable($callable) ) {
                        call_user_func_array($callable, array_values($this->matchedRoute->params()));
                    }

you should print the return value with echo if value is a string.
In this mode is possible apply memoize on callable with a high order function for aply memoize

**Comment by codeguy** [comment]
Can you provide an example of how you would use this in your application? I can see the seemingly-apparent benefit of memoization... but I'm more interested in why you would need this for routes. In most cases, a route will only be called once in the lifetime of an application request which reduces the usefulness of memoization. Let me know some specific examples. Thanks!

**Comment by francescoagati** [comment]
hi,
one can should be like caches_action in rails where you define an action that must be cache for a certain time.

in php with functional programming in 5.3 should be possible memoize a function. With an High Order Function that accept like parameter a function and return the function memoized.

This is an example, with slim, imagine that there is a function memoize in php code is possible make this thing:

<?php

$action_fn= function ($name) {
    return "Hello, $name!";
};

Slim::get('/hello/:name',memoize($action_fn));
Slim::run();
?>

memoize will cache all the call all the function $action_fn with parameter name.

**Comment by francescoagati** [comment]
P.S, Memoization is not made in memory of php process but with a cache system like memcached, db or filesystem

**Comment by codeguy** [comment]
A route's callable when invoked will `echo` any output as is. Currently, the Slim app captures a route callable's `echo`d content into an output buffer and eventually writes the buffer content to the Response body. Based on your suggestions, I'm not entirely sure any changes to Slim are necessary. If using your example code above:

`memoize()` should return an anonymous function that wraps the user-defined callable. The `memoize()` wrapper, when invoked, should check for a cache value; if no cache, the `memoize()` wrapper should invoke the user-defined callable (passing its own arguments as arguments into the user-defined callable) and optionally cache the results. The results, cached or not, should be `echo`d from the `memoize()` wrapper so Slim can capture the output to its output buffer and write the content to the Response.

Is this sufficient? Or do you see this being more integrated with Slim?

**Comment by francescoagati** [comment]
i think of yes. but this was an idea for introduce elements of functional programming in slim with php 5.3

**Comment by codeguy** [comment]
I'm adding this to the Road Map for a future release. I agree this would be a nice feature in Slim to take advantage of functional programming intro'd in 5.3. Closing this issue for now, but will link to this thread from the Road Map page for future reference. Feel free to post additional comments here, though.
