### ISSUE TITLE
Writing unit test for Slim powered PHP application?

### ISSUE THREAD

**Issue by shahariaazam** [slimphp/Slim#740]
What I found is nothing on the web about to write unit test for a php application which is developed by slim framework.

I found nothing about to writing unit test for application inside documentation. So are you working on this or is there any resource for this issue?

Thanks.

**Comment by petarov** [comment]
I would suggest that you take a look at the existing Slim [unit tests](https://github.com/codeguy/Slim/tree/master/tests) and derive your own unit tests from there. For example you would create your own Slim mock object and put all the headers and request info inside and then use that to simulate a HTTP request sent to your app.

**Comment by shahariaazam** [comment]
@petarov I tried in that way you recommended. I also built a solution for that. Have a look [Unit Testing for Slim Framework](http://blog.shahariaazam.com/write-unit-test-for-php-slim-framework)

**Comment by codeguy** [comment]
Closing this out since it's not an issue with the framework. If you have any further questions, please pose to the Slim Framework support forum here:

http://help.slimframework.com/
