### ISSUE TITLE
Ability to specify that a cookie should be unencrypted when encrypt => true;

### ISSUE THREAD

**Issue by sobotklp** [slimphp/Slim#744]
Cookie encryption seems to be an all-or-nothing switch. I would like the ability to specify that one of my cookies should not be sent encrypted, but the others should.

The use case for this is a CSRF Token that is sent as a cookie. The client needs to be able to read the value of this cookie so it can add a HTTP header X-CSRFToken to any POST, PATCH, PUT, or DELETE request.

**Comment by thnt** [comment]
closed without explain ?

**Comment by geggleto** [comment]
I didn't think it needed one. His use case does not make sense, and neither does picking and choosing 1 or more cookies to go in plain-text from any point of view.

However the work around would be to set encrypt to false and encrypt the payload yourself.
