### ISSUE TITLE
HTTP_CONTENT_TYPE is Ignored

### ISSUE THREAD

**Issue by jpj** [slimphp/Slim#745]
Why does \Slim\Http\Headers.php ignore HTTP_CONTENT_TYPE?

https://github.com/codeguy/Slim/blob/master/Slim/Http/Headers.php#L75

This causes content-type headers sent to some servers (namely `php -S`) to get squashed. Fixing this would be easy but I have a feeling the decisions behind why this is the current behavior are complex.

**Comment by codeguy** [comment]
This was ignored because it does not adhere the cgi spec. However, apparently the PHP built-in server ignores the spec and only provides the HTTP_CONTENT_TYPE as you explained. I've just released version 2.4.1 that includes this fix.

https://github.com/codeguy/Slim/releases/tag/2.4.1

**Comment by jpj** [comment]
Thanks for the explanation and the fix.
