### ISSUE TITLE
Inject container in Slim

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#746]
Hello,
I love Slim and use it for a lot of project but I found it a bit limiting when I build an app with web and cli functionality.
So I think that could be great to inject the container in Slim like that we could use it to build cli's command.

**Comment by designermonkey** [comment]
Check out the develop branch where we've altered the way that Slim works with a container.

**Comment by lalop** [comment]
Ok, now \Slim\App extends \Pimlpe so App is the new App::container, isn't it ?
But if I build an app with in one hand a web router ( slim ) when in one other hand some cli command (with phake or symfony console component), I would like to share the same DI container.
I think that's not possible with that change. Or I don't see the way to do it.

I love seeing Slim as a library of my app not as the core, using it as a general DI for command line script does it take responsibilities that it hasn't to take. Do you see my point ?

**Comment by silentworks** [comment]
Since this is more of a question could you move it over to http://help.slimframework.com instead please.
