### ISSUE TITLE
Slim instance as parameter in controller constructor

### ISSUE THREAD

**Issue by danielgsims** [slimphp/Slim#748]
We would like to pass Slim as a dependency in controllers without having to use the Slim singleton instance. This would help us to write more thorough tests.

**Comment by scottux** [comment]
+1

**Comment by lectrotext** [comment]
This would make for better unit testing.

**Comment by ciaranmaher** [comment]
I came across a way pass Slim into your controllers without using the Slim singleton. https://github.com/codeguy/Slim/pull/755#issuecomment-35495095

**Comment by silentworks** [comment]
Closing this off in favour of #822
