### ISSUE TITLE
about the User-agent route conditions

### ISSUE THREAD

**Issue by tobsn** [slimphp/Slim#75]
i think it would be better to just supply browser information instead of routing by browser or just leave the whole feature out of the conclusion cause it doesnt really fit into the framework... (i think)

btw. for browser detection see: 
http://chrisschuld.com/projects/browser-php-detecting-a-users-browser-from-php/
it's actually the best one i could find (for a different project) and the maintainer is a really nice guy.

**Comment by codeguy** [comment]
Agreed this seems like a tangential feature not truly necessary to the framework itself. If someone really wants this, it could easily be created as a plugin using one of the earlier application hooks. I'm removing this from the road map.
