### ISSUE TITLE
some issues with devel branch

### ISSUE THREAD

**Issue by tobsn** [slimphp/Slim#76]
2011-01-03 08:21:40: (mod_fastcgi.c.2711) FastCGI-stderr: PHP Notice:  Trying to get property of non-object in /www/pages/t/admin/htdocs/slim/Slim.php on line 330
PHP Warning:  array_keys() expects parameter 1 to be array, null given in /www/pages/t/admin/htdocs/slim/Slim.php on line 330
PHP Warning:  in_array() expects parameter 2 to be array, null given in /www/pages/t/admin/htdocs/slim/Slim.php on line 330
PHP Notice:  Trying to get property of non-object in /www/pages/t/admin/htdocs/slim/Slim.php on line 330
PHP Warning:  array_keys() expects parameter 1 to be array, null given in /www/pages/t/admin/htdocs/slim/Slim.php on line 330
PHP Warning:  in_array() expects parameter 2 to be array, null given in /www/pages/t/admin/htdocs/slim/Slim.php on line 330
PHP Notice:  Trying to get property of non-object in /www/pages/t/admin/htdocs/slim/Slim.php on line 558
PHP Fatal error:  Call to a member function error() on a non-object in /www/pages/t/admin/htdocs/slim/Slim.php on line 459

only changes made in my code using master branch:
init( 'BlitzView' ) => init( array( 'view' => 'BlitzView' ) )

**Comment by codeguy** [comment]
Thanks. Looks like a small bug slipped through. Will fix this by tonight.

**Comment by codeguy** [comment]
Would you mind emailing me your boostrap.php file so I can see this in context? Or a simple bootstrap.php file that demonstrates this? I'm having difficulty pinpointing the bug on my end. info [at] joshlockhart [dot] com. Thanks!

**Comment by codeguy** [comment]
Can you `require` BlitzView **after** Slim::init() and tell me the error you receive then?

**Comment by codeguy** [comment]
Also, initialize Slim with the default View during this test since BlitzView won't exist during init.

**Comment by codeguy** [comment]
Also make sure you are using the updated Slim files from the `develop` branch. I'm sure you are, but want to make sure for testing purposes.

**Comment by codeguy** [comment]
I've just pushed a very small change to the `develop` branch. Pull down the latest commits and see if the error continues. Let me know. The problem seems to originate on line 330 of Slim.php where one uses `Slim::config('foo')` to request the value of a config setting. I've ensured Slim::\$settings is set to an empty array on __construct, so this should (I hope) fix the issue.

**Comment by codeguy** [comment]
@tobsn Does your PHP install support mcrypt? This is required by the new AES Cookie encryption recently pushed to `develop`. If this is the cause of this issue, I'll have to add some fallbacks in the code. Let me know.

**Comment by codeguy** [comment]
This should be fixed. Other users who experienced similar errors did not have the `mcrypt` extension installed, and Slim did not have any fallback in place. Now, `Slim::setEncryptedCookie()` will degrade gracefully and set an unencrypted Cookie if `mcrypt` is not available.

**Comment by tobsn** [comment]
ha! i think thats it - sorry for not replying yesterday, i was busy finding the bug and when you started debugging i went to bed cause im sick right now. 
i remember that mcrypt was installed but the package version of php on my rackspace cloud dev servers on ubuntu is baked and returns a 500 status on almost any error or warning so i hand compiled the latest php 5.3 and forgot about some of the extensions like mcrypt and the int8 stuff. 

going to download devel now and try it out quickly - but im sure that was the problem.

**Comment by tobsn** [comment]
yeah. that was the problem. 
btw. did you got my mail?

**Comment by codeguy** [comment]
Glad that fixed it. Didn't get an email yet.

**Comment by tobsn** [comment]
ha... weird, its in my sent folder to the info@ you wrote at the top.

**Comment by codeguy** [comment]
@tobsn You'll need to re-send it. Let me know when you do and I'll keep an eye out for it.

**Comment by tobsn** [comment]
got it?

**Comment by codeguy** [comment]
Got it. Will take a look in more detail tonight!
