### ISSUE TITLE
Matrix Parameters

### ISSUE THREAD

**Issue by cwhiteley** [slimphp/Slim#760]
Does the Slim framework support Matrix Parameters?

**Comment by codeguy** [comment]
What is a matrix parameter?

**Comment by cwhiteley** [comment]
http://example.com/res/categories;name=foo/objects;name=green/?page=1

This is an example - after the ? are the request params before the ? And after the ; are the matrix parameters..

**Comment by cwhiteley** [comment]
The example above came from here: 

http://stackoverflow.com/questions/2048121/url-matrix-parameters-vs-request-parameters

**Comment by erizocosmico** [comment]
I think that slim does not implement that by default. You could use something like:

``` php
$app->get('/route:params', function ($params) use ($app) {
    $matrixParams = array_map(function ($param) {
        return explode('=', $param);
    }, explode(';', $params);
    // Use $matrixParams here
});
```

**Comment by designermonkey** [comment]
I wouldn't expect to support matrix parameters out of the core, as it was just a personal opinion idea of Tim Berners Lee, a very long time ago. It hasn't been adopted on a wide enough scale to gather momentum as a standard, so I reckon IMO, the only way to have it is as described above.

Bear in mind that (according to the link posted) URLs in forms using GET as a method will convert them to query parameters anyway, so a consistent interface across all verbs wouldn't be possible either.

**Comment by cwhiteley** [comment]
In the last paragraph of section 3.3, 

http://tools.ietf.org/html/rfc3986#section-3.3

The URI specification suggests employing the semicolon ;, equals = and comma , characters for this task. Therefore:

**Comment by silentworks** [comment]
Closing this off as its an old issue.
