### ISSUE TITLE
Suggestion - Use Pimple 2 in Slim 3

### ISSUE THREAD

**Issue by andrewmman** [slimphp/Slim#762]
Since you're introducing Pimple as the base container, you may want to switch to version 2. The container performance has being optimized.

You may find some issues though, mainly because Collection is extending Pimple (not sure why this change was introduced), but if you want I can submit a P.R.

Proposed changes can be seen [here](https://github.com/andrewmman/Slim/commits/dev/pimple2).

**Comment by jamesmoss** [comment]
+1

Making services act like factories by default is much nicer than having to use `share()` everywhere.

**Comment by codeguy** [comment]
Agreed. This will happen.

**Comment by designermonkey** [comment]
> You may find some issues though, mainly because Collection is extending Pimple

It was decided to have that happen as  `Collection` had many of the same `ArrayAccess` and other methods that `Pimple` handled in one little package. It was to thin out the duplicate code.
