### ISSUE TITLE
$app->error() overwrites previous handlers

### ISSUE THREAD

**Issue by DSpeichert** [slimphp/Slim#763]
The documentation suggests that passing exception class type in the argument of error handler function would limit this handler to particular exception class. However, calling the $app->error() function does not register multiple error handlers, it overwrites previous.

This does not work:

``` php
$app->error(function (Illuminate\Database\Eloquent\ModelNotFoundException$e) use ($app) {
    $app->halt(404, 'Not found');
});

$app->error(function (ErrorException $e) use ($app) {
    $app->halt(500, 'Fatal error occured: ' . $e->getMessage() . ' at line ' . $e->getLine() . ' in file ' . $e->getFile());
});
```

It will throw:
`Fatal error: Uncaught exception 'ErrorException' with message 'Argument 1 passed to {closure}() must be an instance of ErrorException, instance of Illuminate\Database\Eloquent\ModelNotFoundException given`

Instead, I have to use:

``` php
$app->error(function ($e) use ($app) {
    if($e instanceof Illuminate\Database\Eloquent\ModelNotFoundException)
    {
        $app->response->setStatus(404);
        $app->response->headers->set('Content-Type', 'application/json');
        $app->response->setBody(json_encode(null), JSON_PRETTY_PRINT);
    }
    elseif($e instanceof InputErrorException)
    $app->halt(500, 'Fatal error occured: ' . $e->getMessage() . ' at line ' . $e->getLine() . ' in file ' . $e->getFile());
});
```

Is it a bug or unclear documentation?
Slim 2.4.2 (3a2ac723f17b5d81607287ff28575d38b9fbc70e)

**Comment by erizocosmico** [comment]
I think there's a mistake in the documentation. https://github.com/codeguy/Slim/blob/master/Slim/Slim.php#L648-L658

**Comment by codeguy** [comment]
This is not the intended functionality, so I suppose the documentation can be worded better. There is one error handler and it is a catch-all for any Exceptions that are caught while the app is running.
