### ISSUE TITLE
HTTP status headers

### ISSUE THREAD

**Issue by bobdia** [slimphp/Slim#77]
I noticed that the Response class doesn't really insert Response::$status in the status header.

```
header('HTTP/1.1 ' . Response::getMessageForCode($this->status()));
```

Should be changed to:

```
header('HTTP/1.1 ' . $this->status() . ' ' . Response::getMessageForCode($this->status()));
```

Fastcgi apparently also needs some consideration (according to php.net), since it requires a header in this format: "Status: 200 OK"

This is the usual solution, AFAIK.

<pre>
if (substr(php_sapi_name(), 0, 3) == 'cgi') {
    header("Status: $status");
} else {
    header("HTTP/1.1 $status");
}
</pre>

**Comment by codeguy** [comment]
I will add a hotfix for the `Status` header needed by fastcgi. But the `HTTP/1.1` header **should** already be including the numeric status code as is. See the `Response::getMessageForCode()` method in `slim/Response.php` on line 246.

**Comment by bobdia** [comment]
I somehow didn't notice that the status number was in both the key and value of the message array. Is there a reason for that?

**Comment by codeguy** [comment]
No real reason... just a convenience factor I guess. They'll never change. I'm sure this could be cleaned up though.

**Comment by codeguy** [comment]
Just applied a hotfix to set the `Status:` header if running under fastcgi. Tagged as 1.0.2.

**Comment by bobdia** [comment]
I didn't test this before opening the issue by the way. Also, Tobsn said he didn't have any problems running this on lighttpd without the fix.

**Comment by codeguy** [comment]
@bobdia Ok. I read more about running PHP under fastcgi, and according to the docs on php.net, as you said, it does expect a Status: header that contains the "200 OK" or similar HTTP status message. If you are not running php under fastcgi, Slim will continue working as it has.
