### ISSUE TITLE
[Proposal] filter on params given at url generation

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim#773]
Hello,
I will start with a simple exemple, in a new app I have a page that lists all my items `/items`, since I've a lot of items I'm doing some pagination so my route is `/items(/:page)`.
To have one uniq url for each page I would like to modify the url generated if `page=1` because that the default case.

``` php
$app->urlFor('items'); // =>   /items
$app->urlFor('items', ['page' => 2]) // => /items/2
$app->urlFor('items', ['page' => 1]) // => /items
```

Do you see my point ?
I see 2 ways to that:
- the first one, and the simplest one is to give a default value to `page`, at the url generation we could hide the param if the given one equals the default one
- the second one, could be adding an "at generation filter" to transform url params before generating it

What do you think of that ?

**Comment by silentworks** [comment]
I am looking at something like this now, but I am thinking that if the params aren't defined in the route then this should probably convert to a query string, I see Laravel doing this, but not sure if this is a normal behaviour of other frameworks.

e.g

``` php
// route
$app->get('/items', function() {})->name('items');

// route call
$app->urlFor('items', ['page' => 1]);
```

In Laravel this would results in `/items?page=1`, I wonder if we should be having this kind of behaviour in Slim.

**Comment by silentworks** [comment]
There is currently a PR implementing what I have suggested https://github.com/codeguy/Slim/pull/876 will be closing this issue in favour of the PR.
