### ISSUE TITLE
Make HTTP request and response components

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#777]
Drastically simplify the HTTP request and response classes. Using the Symfony HTTP Foundation interfaces, let Slim's HTTP request and response classes implement only the core interface methods. This will make it easier for developers to swap in more robust implementations (like HTTP Foundation) if they want.

**Comment by codeguy** [comment]
See https://github.com/codeguy/Slim/issues/776

**Comment by ghost** [comment]
I agree.

**Comment by codeguy** [comment]
After some thought and research, I'm leaning toward providing first-class HTTP request, response, and body classes that will implement the upcoming PSR for HTTP messages. However, I also want to put equal effort into HTTP request and response adapters for the Symfony HTTP Foundation classes since those are so popular.

I also want to roll the header and cookie collection interfaces into the request class interface so we don't violate the Law of Demeter. In other words, we should not expose the cookie and header collections as public properties. Doing so will reduce our class overhead, too.

**Comment by ghost** [comment]
I agree with you.

Cookies and Headers can be used through a method calling a Bag (Symfony way), that can be reused - as abstract - to store those values before flushing them.

What do you think?

**Comment by nagibyro** [comment]
Perhaps it might be worth looking into [Aura's web component](https://github.com/auraphp/Aura.Web) to use as a base for request and response's. It seems like a "slimmer" (excuse the pun) implementation than the Symfony HTTP Foundation. It doesn't mean it'd be better but I saw everyone talking about Symfony HTTP Foundation and no one seemed to mention Aura's web component so I thought I'd put it out there.

Thanks for Slim by the way @codeguy have used it at work for a number of projects and have loved it every time.

**Comment by marcioAlmada** [comment]
+1 for aura, in case of a non distant decision.
+1 for waiting for the HTTP PSR, I've been waiting for this PSR for a long time, hope it comes soon.

**Comment by codeguy** [comment]
I will be implementing native HTTP request and response classes that implement the forthcoming HTTP PSR. I expect we will need to adapt these implementations as the spec moves toward completion, but I don't foresee any big changes from what has already been proposed.

**Comment by codeguy** [comment]
However, because Slim will expect the HTTP PSR interface and not a concrete Slim request/response class, you can easily swap in whatever class you want.
