### ISSUE TITLE
$app->view->fetch() does not pass data

### ISSUE THREAD

**Issue by DSpeichert** [slimphp/Slim#778]
I am using latest version of Slim and Slim-Views with Twig.

When I do:

``` php
$a = $app->view->fetch('template.html', array('something' => 'anything'));
```

`something` is not available in the template.

With:

``` php
$app->view->render('template.html', array('something' => 'anything'));
```

it works fine.

**Comment by DavidePastore** [comment]
:+1: The only way to make it works is:
- append data to the view;
- fetch the view without params.

``` php
$app->view->appendData(array(
  'something' => 'anything'
));

$html = $app->view->fetch('template.html');
```

This seems to be a bug.

**Comment by codeguy** [comment]
Investigating.

**Comment by codeguy** [comment]
This is an issue with the Slim-Views repository. I have a commit pending review from my collaborators. I believe this will fix the problem you are having. Should be available tomorrow.

https://github.com/codeguy/Slim-Views/commit/82daa909f91d535285e898940138196d9306e07e
