### ISSUE TITLE
[BUG] Middleware priority

### ISSUE THREAD

**Issue by nicknill** [slimphp/Slim#781]
```
$app->add(new Mw1());
$app->add(new Mw2());
```

when Slim is loaded - it calls first Mw2 then Mw1. 
It's looks strange, and should be in documentation.

For example next code will be broken:

```
$app = new Slim();
$app->view(new JsonApiView());
$app->add(new JsonApiMiddleware());
$app->post('/auth',function() use ($app) {
   $app->add(new AuthMw());
}

class AuthMw() {
   public function call() {
     if( !$this->auth() ) 
       throw(new Exception('Auth error');
      $this->next->call();
   }
}
```

AuthMw think that JSONApi middleware is loaded, and throws exception, or use $app->stop(), or $app->render - not matter.
In all cases Slim will give Fatal error with Uncaught exception

**Comment by lrlopez** [comment]
I agree that it should be documented, but I don't find it strange. When talking about middleware in Slim think about the layers of an onion. You start from a core and begin adding layers. The first layer you add directly touches the core. The second layer touches the first layer, but not the core, etc.

**Comment by codeguy** [comment]
Thanks @lrlopez, exactly. Think of it like adding more layers around an onion. I think a visual diagram would go a long ways to help explain this, but I'm not the best vector illustrator :)
