### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ppvolto** [slimphp/Slim#786]
I like to create Named Groups to create a Prefix for Named Routes.

like creating a Named Group "book" and have the CRUD routes named after the action
resulting in named routes like "book.create" and "book.delete" the separator needs to be configurable...

**Comment by erizocosmico** [comment]
You mean something like this?

``` php
$app->group('/books', function () use ($app) {
    $app->get('/(:id)', MyCallable)->name('get');
})->name('books');

[...]
$app->urlFor('books.get');
```

I think it would be cool to have this feature. I could pull together a pull request today or tomorrow with this feature if @codeguy likes it.

**Comment by designermonkey** [comment]
In the upcoming version 3, we have a `ConfigurationHandler` class that allows for nested arrays to be accessed using `.` separated keys.

Maybe we could utilise this in the `Router` class for access too.

**Comment by ppvolto** [comment]
Thanks for the quick response,
@designermonkey thanks for the information i hope its possible to use it in the future
and @mvader i checkout for the pull request the days... 

Thanks both of you

> I think i can close it with this...

**Comment by BafS** [comment]
I cannot find anything related in Slim 3, I don't think that a naming group is available. Can you please confirm ?

It could really help to keep a good structure like that:
```php
$app->group('/users', function () use ($app) {
    $app->get('', ...)->name('index');
    $app->get('/:id', ...)->name('show');
    $app->post('/:id', ...)->name('create');
    ...
})->name('users');
```

and to be able to access with `users.show` for example.
