### ISSUE TITLE
Allow log writer to handle object conversion

### ISSUE THREAD

**Issue by mattzuba** [slimphp/Slim#788]
Currently the \Slim\Log::log function converts any object passed in to a string and then eventually sends that resulting conversion to the logwriter.  I think it would be more beneficial to only do a conversion to string if there is some context to work with and allow the log writer to determine how it wants to handle the object passed if there is no context.

I'm thinking of the case of using other logging solutions like Monolog - It's difficult to take full advantage of passing an object to Monolog without extending the \Slim\Log class and overloading with my own log() function to pass the raw object instead of a typecasted representation.

**Comment by silentworks** [comment]
You can easily use monolog with Slim and override the log call in Slim by doing

``` php
$app->log = yourOwnLoggerClass;
```

Take a look at @tuupola comment here #840 you will notice he is using Monolog.

There is another issue relating to this at #851, I will close this in favour of that.
