### ISSUE TITLE
Content-Length not set

### ISSUE THREAD

**Issue by aktau** [slimphp/Slim#790]
In a very simple route here in my slim (2.4.2) app, I see no content-length being set. So I started looking around the Slim source and can only find that Content-Length is removed in finalize in the case of certain status (`204`, `304`) on Http/Response.php line 276. I don't see it being set anywhere despite it being [mentioned in the docs](http://docs.slimframework.com/).

This little niggle makes nginx compress everything because it doesn't know the content-length. Even 20 byte responses and things like that (ajax...).

**Comment by aktau** [comment]
This seems to fix it:

``` php
    public function finalize()
    {
        // Prepare response
        if (in_array($this->status, array(204, 304))) {
            $this->headers->remove('Content-Type');
            $this->headers->remove('Content-Length');
            $this->setBody('');
        }
        else {
            // if not exists....
            if (!$this->headers->has('Content-Length')) {
                $this->headers->set('Content-Length', $this->getLength());
            }
        }

        return array($this->status, $this->headers, $this->body);
    }
```

**Comment by aktau** [comment]
Addendum: I had to check for a zero content-length as well, I still haven't found out why, but the problem was occurring when I did an early quit in some middleware before reaching the actual route. The middleware just did a `->render()` call to a login page, but somehow the body did not get set in the response, which made the `->getLength()` call return 0. Corrected version:

``` php
            if (!$this->headers->has('Content-Length') && $this->getLength() > 0) {
                $this->headers->set('Content-Length', $this->getLength());
            }
```

**Comment by fearfullymade** [comment]
Another option is to set the content-length in a middleware class:

``` php
class ContentLengthMiddleware extends \Slim\Middleware
{
  public function call()
  {
    $app = $this->app;

    $this->next->call();

    $res = $app->response;

    if ($res->getStatus() == "200" && !$res->headers->has('Content-Length') && $res->getLength() > 0) {
      $res->headers->set('Content-Length', $res->getLength());
    }
  }
}
```

**Comment by aktau** [comment]
True enough. Though I don't think this would be a bad thing for core.

**Comment by codeguy** [comment]
Do you want to submit a PR for this?

**Comment by aktau** [comment]
Bit busy atm, will see when I can manage!

**Comment by silentworks** [comment]
This is fixed in the develop branch.
