### ISSUE TITLE
Middeware Calls in the reverse order added?

### ISSUE THREAD

**Issue by JoshWillik** [slimphp/Slim#793]
Hi there, when I tried to do something like this: 

``` php
$app->add( new \Slim\Middleware\SessionCookie() );
$app->add( new \Slim\Middleware\PermissionMiddleware() ); //mine
```

`PermissionManager` kept complaining about $_SESSION not being defined.

I discovered that this was because Slim called the middleware in the reverse order, which seemed odd to me.

When I changed it to this: 

``` php
$app->add( new \Slim\Middleware\PermissionMiddleware() ); //mine
$app->add( new \Slim\Middleware\SessionCookie() );
```

everything became as expected.

Is there some hidden logic to this, or is this counter-intuitive for everyone else too?

**Comment by marcioAlmada** [comment]
Middleware stack works just like an onion. If you put a middleware as the outer "layer" of the stack it will be the first one to be reached by the incoming request.

**Comment by JoshWillik** [comment]
Fair enough, I suppose I'm still stuck in the [express](http://expressjs.com) way of thinking.

**Comment by marcioAlmada** [comment]
Yes, with express we usually just pipe stuff from one place to another. With slim stack every layer contains a reference to the next layer but nothing is piped, just inspected and modified when the middleware has the chance to.

**Comment by JoshWillik** [comment]
That makes sense when explained. 
Is it worth a note in the docs maybe?
The docs do seem worded that way on investigation, but something more explicit perhaps?

**Comment by marcioAlmada** [comment]
Look at what I've found: http://www.sitepoint.com/working-with-slim-middleware/. Maybe it could appear listed on some "useful links" section in docs :smile:

**Comment by lrlopez** [comment]
Cool! You should ask Timothy for permission to use his illustration in the docs. @tboronczyk

**Comment by lrlopez** [comment]
Timothy, may I ask for your permission for including it in my teaching slides? I'll keep attribution, of course!

**Comment by tboronczyk** [comment]
@lrlopez permission granted :)

**Comment by lrlopez** [comment]
Thanks!
