### ISSUE TITLE
Proprietry implementation of SessionHandlerInterface

### ISSUE THREAD

**Issue by alanpich** [slimphp/Slim#794]
[Slim\Interfaces\SessionHandlerInterface](https://github.com/codeguy/Slim/blob/develop/Slim/Interfaces/SessionHandlerInterface.php)

Interface mimics `\SessionHandlerInterface` exactly, and yet does not extend it.
I can sort of see the appeal of having all Interfaces under a Slim namespace, but
for cross-library compatibility it would be easier if Slim used the inbuilt interface instead

**Comment by lrlopez** [comment]
If you have a look [here](https://github.com/codeguy/Slim/blob/develop/Slim/Interfaces/SessionHandlerInterface.php#L38) you'll see the reason.

It seems that PHP 5.3 doesn't implement `SessionHandlerInterface`.

**Comment by anlutro** [comment]
Perhaps it could be defined in the global namespace, but only if the class already does not exist?

Could also be extracted into a separate package. Maybe it already exists.

**Comment by alanpich** [comment]
That sounds like the right option, only creating it if its needed. Otherwise as it stands any third party library would need to be bridged before it would be compatible.

Can you define interfaces inside`if` statements?

**Comment by designermonkey** [comment]
No you can't which is why we opted for adding it.

When PHP 5.3 support is dropped, so will the interface be.

**Comment by alanpich** [comment]
where does 3.0 (develop) stand on that?

**Comment by anlutro** [comment]
What's saying you can't conditionally define interfaces? https://eval.in/121449

**Comment by designermonkey** [comment]
This happens to me a lot. I didn't even know that existed o_O

**Comment by charlie-s** [comment]
Should this be as simple as:

```
if (!interface_exists('SessionHandlerInterface')) {
    interface SessionHandlerInterface
    {
        public function close();
        public function destroy($session_id);
        public function gc($maxlifetime);
        public function open($save_path, $name);
        public function read($session_id);
        public function write($session_id, $session_data);
    }
}
```

?

**Comment by silentworks** [comment]
I opt for removing what we currently have or extending SessionHandlerInterface, Interfaces are only being used in Slim 3 and this will be PHP 5.4+ only from what I gather.

**Comment by charlie-s** [comment]
"When PHP 5.3 support is dropped, so will the interface be."

Do you know if Slim 3 is 5.4 only? I would certainly prefer that.

**Comment by silentworks** [comment]
Yes Slim 3 will be 5.4+ closing this off, we will sort the SessionHandlerInterface class out in Slim 3.
