### ISSUE TITLE
Documentation TOC is only visible at the top of the page

### ISSUE THREAD

**Issue by davestewart** [slimphp/Slim#799]
You could solve that using this rather ace plugin:
- http://gregfranko.com/jquery.tocify.js/

It also scrolls / contracts when running on small screens or too many menu options have been opened :)

**Comment by designermonkey** [comment]
Can you please open this on the documentation repository?

https://github.com/codeguy/Slim-Documentation

Thanks.

**Comment by davestewart** [comment]
All done! Tnx.
