### ISSUE TITLE
Application Redirect does not work properly

### ISSUE THREAD

**Issue by netdust** [slimphp/Slim#800]
Hi

I'm using slim 2.4.2 and I am having an issue with redirect.

$app->redirect('/page'); sends the browser to http://localhost/page instead of the path
were the app is located. ( http://localhost/application/page )

my htaccess is simple:

RewriteEngine on

RewriteCond  %{REQUEST_FILENAME}    !-f
RewriteCond  %{REQUEST_FILENAME}    !-d
RewriteRule  ^(.*)$                 index.php [QSA,L]

any ideas why this might happen?

Stefan

**Comment by designermonkey** [comment]
Try setting the `RewriteBase` directive in your `.htaccess`.

```
RewriteEngine On
RewriteBase /application
...
```

**Comment by netdust** [comment]
Hey

I allready tried this. it has exatly the same result.
Maybe I need to add that the app works fine, so
http://localhost/application/page entered in the browser will launch the
slim route.

it's just internally, when I try to redirect using ->redirect('/otherpage')
that it fails and redirects to http://localhost/otherpage.
If I redirect like this ->redirect('otherpage'), it redirects fine at
first, but a second redirect adds to the path so it gives something like

start page : /

redirect('page'): /page

redirect('otherpage'): /otherpage

redirect('otherpage/sub'): /otherpage/otherpage/sub

once I add a / before to route it just goes to localhost

Stefan

2014-03-27 16:59 GMT+01:00 John Porter notifications@github.com:

> Try setting the RewriteBase directive in your .htaccess.
> 
> RewriteEngine On
> RewriteBase /application
> ...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/codeguy/Slim/issues/800#issuecomment-38822958
> .

## 

_Netdust[i]std._
Stefan Vandermeulen

you can follow me on twitter https://twitter.com/#!/netdust or
google+ https://plus.google.com/u/0/116430909251309245804/postsgsm:
+32(0)475 238 704

**Comment by designermonkey** [comment]
What is the `$_SERVER` superglobal saying that the `DOCUMENT_ROOT` is?

**Comment by StJudeWasHere** [comment]
What the redirect() method does is set the Location header, and what you describe seems to be the expected behaviour.

Doing a redirect('/page') will redirect to http://example.com/page. If you want to redirect to your application folder you have to do something like redirect('/application/page') instead.

**Comment by designermonkey** [comment]
Ah, well, that depends on where Slim is installed, and what the document root is.

If the docroot is `localhost` then yes, it is working fine, but if it's `localhost/application` then there is an issue.

**Comment by netdust** [comment]
'HTTP_HOST' => string 'localhost' _(length=9)_

  'SERVER_NAME' => string 'localhost' _(length=9)_
  'SERVER_ADDR' => string '127.0.0.1' _(length=9)_
  'SERVER_PORT' => string '80' _(length=2)_
  'REMOTE_ADDR' => string '127.0.0.1' _(length=9)_
  'DOCUMENT_ROOT' => string 'C:/Users/stefan/Projects' _(length=24)_

  'CONTEXT_DOCUMENT_ROOT' => string 'C:/Users/stefan/Projects' _(length=24)_
  'SCRIPT_FILENAME' => string
'C:/Users/stefan/Projects/Personal/Kraken/index.php' _(length=58)_

  'REQUEST_URI' => string '/Personal/Kraken/' _(length=25)_
  'SCRIPT_NAME' => string '/Personal/Kraken/index.php' _(length=34)_
  'PHP_SELF' => string '/Personal/Kraken/index.php' _(length=34)_

_this is a var_dump from $_SERVER_

_my directory structure is as follows:_

_APP ( http://localhost/personal/kraken/ http://localhost/personal/kraken/ )_
- - api ( contains conf etc... )*
- - lib ( contains slim, twig, paris, ... )*
- - www ( contains css, tpl, img )*
-   htaccess*
-   index.php*

_stefan_

2014-03-27 18:07 GMT+01:00 John Porter notifications@github.com:

> Ah, well, that depends on where Slim is installed, and what the document
> root is.
> 
> If the docroot is localhost then yes, it is working fine, but if it's
> localhost/application then there is an issue.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/codeguy/Slim/issues/800#issuecomment-38831918
> .

## 

_Netdust[i]std._
Stefan Vandermeulen

you can follow me on twitter https://twitter.com/#!/netdust or
google+ https://plus.google.com/u/0/116430909251309245804/postsgsm:
+32(0)475 238 704

**Comment by designermonkey** [comment]
So @mnlg was correct as your document root is not the root of your project.

**Comment by netdust** [comment]
ah yes, offcourse. mmm. i assumed slim worked from where it's files are. [?]
thx for your time

2014-03-27 20:14 GMT+01:00 John Porter notifications@github.com:

> So @mnlg https://github.com/mnlg was correct as your document root is
> not the root of your project.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/codeguy/Slim/issues/800#issuecomment-38848153
> .

## 

_Netdust[i]std._
Stefan Vandermeulen

you can follow me on twitter https://twitter.com/#!/netdust or
google+ https://plus.google.com/u/0/116430909251309245804/postsgsm:
+32(0)475 238 704

**Comment by designermonkey** [comment]
Hey, it's no problem.

Could you close this then? Thanks.
