### ISSUE TITLE
Environment.php: $env['PATH_INFO'] wrong when using an alias under Apache 2.3/2.4

### ISSUE THREAD

**Issue by rgrellmann** [slimphp/Slim#802]
In Environment.php::__construct() on line 149 (version 2.3.0) the SCRIPT_NAME is stripped off of the REQUEST_URI. When an Alias directive is used in the Apache config, the SCRIPT_NAME contains the alias part and is longer than without an alias (at least in Apache 2.4). This results in an incorrect PATH_INFO.

Suggested Fix:
Apache 2.4 provides the CONTEXT_PREFIX variable, the following code worked for me:
Environment.php, line 149:

``` php
            if (empty($_SERVER["CONTEXT_PREFIX"])) {
                $env['PATH_INFO'] = substr_replace($_SERVER['REQUEST_URI'], '', 0, strlen($env['SCRIPT_NAME']));
            } else {
                $aliasLength = strlen($_SERVER["CONTEXT_PREFIX"]);
                if (substr($_SERVER["CONTEXT_PREFIX"], -1) == '/') {
                    $aliasLength--; // ignore trailing slash
                }
                $env['PATH_INFO'] = substr_replace($_SERVER['REQUEST_URI'], '', 0, strlen($env['SCRIPT_NAME']) - $aliasLength);
            }
```

**Comment by woolfg** [comment]
I encountered the same problem when using apache aliases. I really bad workaround would be replacing the physical path by the virtual path. It would be really nice if one could specify a base path which is used by slim to extract the routes.

```
$_SERVER['SCRIPT_NAME'] = str_replace("/www/blablabl/myapp/app/public/","/myapp/",$_SERVER['SCRIPT_NAME']);
```

**Comment by tbela99** [comment]
I just used this and it worked

 $env['PATH_INFO'] = '/' . ltrim(preg_replace('#\?.*#', '', $_SERVER['REQUEST_URI']), '/');

**Comment by matthew-dean** [comment]
>  It would be really nice if one could specify a base path which is used by slim to extract the routes.

Just to tweak what was written above, I was able to fix routing for me this way:

```
$app = new \Slim\Slim();

$env = $app->environment;
$env['PATH_INFO'] = strtok($_SERVER["REQUEST_URI"],'?');
```
