### ISSUE TITLE
PUT -> accessing the POST datapayload

### ISSUE THREAD

**Issue by cobookman** [slimphp/Slim#804]
PHP doesn't attach the POST data from a HTTP PUT request.  For example If I were to do the following curl statement:

```
curl -X PUT -d "name=TEST2" 'http://localsite.evitics.com/api/meeting/27752'
```

PHP would not set  `$_POST["name"]="TEST2"`

The following code fixes this, so long as its inside the the root PHP file.  By `root` I mean whatever file creates and starts the SLIM framework.

```
if($_SERVER['REQUEST_METHOD'] == 'PUT') {
  $post_vars;
  parse_str(file_get_contents("php://input"),$post_vars);
  foreach($post_vars as $key=>$post_var) {
    $_POST[$key] = $post_var;
  }
}
```

**Comment by ffflabs** [comment]
I don't think you should use PHP superglobals for this. Perhaps you can try getting the value with

``` php
$name = $app->request()->put('name');
```

**Comment by codeguy** [comment]
What @amenadiel said. You do not want to rely on superglobals for this. If you are receiving url-form-encoded data, it will be available like @amenadiel suggests above. If you are receiving non-url-form-encoded data, you must rely on `$app->request->getBody()` to fetch the raw request content.
