### ISSUE TITLE
Found documentation typos

### ISSUE THREAD

**Issue by mondalaci** [slimphp/Slim#809]
Is there any repo for the documentation hosted at http://docs.slimframework.com/   Found some typos that I'd like to fix.

Thanks!

**Comment by mondalaci** [comment]
Given that this issue doesn't seem to be answered quickly let me copy-paste the relevant errors from my notes:
- "standardized interface to interactive with the HTTP request headers" - The word "interactive" should be replaced with "interact".
- "The response object’s finalize() method returns a numeric array of [status, header, body]." - This array doesn't seem to contain all numeric values.
- The comment of the "$res->isInformational();" call is "//Is this an informational response?" which fails to explain the purpose of this method.
- There's a "Rending Templates" link which is broken.

**Comment by DavidePastore** [comment]
@mondalaci: take a look [here](https://github.com/codeguy/Slim-Documentation) and [here](https://github.com/codeguy/Slim-Documentation-3).
