### ISSUE TITLE
How to handle "Batched Requests"

### ISSUE THREAD

**Issue by dstjean** [slimphp/Slim#810]
I was wondering if it was possible to handle batch requests.

For example:
POST /batch
Body:
[ { method: 'POST',
   url: '/blablabla'
   body: {......}
 },
  { method: 'PUT', 
   url: '/asdasdsdad',
   body: { ... }
]

Run the requests in series and return a grouped response
[
  { status: 200,
    body: {}
  }, 
  {status: 400, 
   body: {}
  }
]

**Comment by silentworks** [comment]
Closing this out as this should be asked on http://help.slimframework.com/.
