### ISSUE TITLE
Configuring Hybrid Auth in Slim PHP

### ISSUE THREAD

**Issue by evivz** [slimphp/Slim#812]
Hi,

I am using Hybrid Auth (https://github.com/hybridauth/hybridauth) for social login. But its causing issues with Slim routing. What should I do?

Disable routing in hybrid auth folder is it the way? Or any other proper way to handle this?

Thanks

**Comment by silentworks** [comment]
Can you ask this over at http://help.slimframeworks.com please, this is not an issue with Slim framework but more of a question about how to solve a problem.

**Comment by silentworks** [comment]
Closing this off in favour of moving it over to the help site.
