### ISSUE TITLE
slim.after.router is called too early

### ISSUE THREAD

**Issue by tiwac100** [slimphp/Slim#813]
slim.after.router is called before output buffering is turned off

**Comment by tuupola** [comment]
To be more exact about this. Documentation states:

**slim.after.router**
_This hook is invoked after the router is dispatched, before the Response is sent to the client, and <b>after output buffering is turned off</b>. This hook is invoked once during the Slim application lifecycle._

However in both [master](https://github.com/codeguy/Slim/blob/master/Slim/Slim.php#L1338) and [development](https://github.com/codeguy/Slim/blob/develop/Slim/App.php#L1096) hook is called before turning output buffering off.
