### ISSUE TITLE
Multiple call of route

### ISSUE THREAD

**Issue by rhnkyr** [slimphp/Slim#814]
Hi,
for instance i have a route like

```
 $app->get("/av(/)", '\Controllers\AdminController:activeVideos')->name("name_it");
}
```

when i add (/) at the end of route, Slim calls that route 2 times. I add (/) to prevent 404 error for /av/
instedad /av.

Is it normal to call it 2 times. Cheers...

**Comment by rgsone** [comment]
Simply remove the parenthesis for the same feature without Slim calls that route twice.

`$app->get("/av/", '\Controllers\AdminController:activeVideos')->name("name_it");
}`

**Comment by tuupola** [comment]
Actually this looks like a book to me if it still happens. Route should not be called twice if optional parameter/part exists.

**Comment by silentworks** [comment]
Can you run a test @tuupola and let me know if it still exist, I will reopen this and wait for your feedback.

**Comment by tuupola** [comment]
Sure. Bit later today.

**Comment by tuupola** [comment]
I am unable to reproduce the problem. Tested with Slim 2.4.3 on both Apache and built-in PHP web server. Also `DirectorySlash On` Apache setting does not create the problem. Tested with following code:

``` php
require "vendor/autoload.php";

use Monolog\Logger;
use Monolog\Handler\RotatingFileHandler;
use Monolog\Formatter\LineFormatter;

$log = new Logger("slim");
$formatter = new LineFormatter("[%datetime%] [%level_name%]: %message%\n");
$rotating  = new RotatingFileHandler(__DIR__ . "/logs/slim.log", 0, Logger::DEBUG);

$rotating->setFormatter($formatter);
$log->pushHandler($rotating);

$app = new \Slim\Slim();
$app->log = $log;

$app->get("/foo(/)", function() use ($app) {
    $app->log->debug("Request");
    print "foo";
});

$app->run();
```

**Comment by silentworks** [comment]
Thanks for that @tuupola I will close this off since its no longer an issue.
