### ISSUE TITLE
Switch the default template system to Plates

### ISSUE THREAD

**Issue by ziadoz** [slimphp/Slim#818]
I've used [Plates](http://platesphp.com/) in a couple of Slim projects now where Twig would have been overkill and it works great. I figured it might be a good candidate to replace the existing Slim template system (in a major release, obviously), as it's fairly similar, whilst providing more functionality out-of-the-box. Also, it'd mean you no longer need to maintain your own template system anymore. 

I've seen at least [one](https://github.com/philipsharp/slim-view-plates) Slim View implementation of it in the wild so far.

I'm curious to hear your thoughts on this idea. Thanks.

**Comment by lalop** [comment]
We can use Slim without render a view or using a view engine so add an external lib as dependencies to do that doesn't seem to be a good idea.
Anyway Plates looks like a great tool ( I will use it for my next project ) maybe you can make a PR to the codeguy/Slim-Views repository.

**Comment by ziadoz** [comment]
Fair enough, that makes sense. I'll consider making a PR to the Slim Views repository. Thanks.
