### ISSUE TITLE
Mock method using deprecated constant

### ISSUE THREAD

**Issue by felipedmz** [slimphp/Slim#819]
When I was trying to run integration tests I got this error:
"ErrorException: Undefined index: SERVER_NAME"

I'm running PHP 5.5, and looking at Environment class I found the deprecated constant $_SERVER.

http://us3.php.net/manual/en/reserved.variables.server.php

**Comment by designermonkey** [comment]
`$_SERVER` is not deprecated, `$_HTTP_SERVER_VARS` is, and has been for a while, but `$_SERVER` is still perfectly valid to use.
