### ISSUE TITLE
Optional route separated by dot instead of slash

### ISSUE THREAD

**Issue by carestad** [slimphp/Slim#823]
Hi

I'm working on a simple API that gives you data in the preferred format just by adding a .json or .xml to the URL and I was looking for a way to do something like this:

```
$app->get('/:foo(.:bar)', function($foo, $bar = false) {}
```

... where the URL would be something like http://foo.tld/abc or http://foo.tld/abc.json.

Is that possible somehow? All I want is to simply have the `.json` or just `json` in a variable by itself without having to parse the `$foo` variable for it.

**Comment by silentworks** [comment]
Can you move this over to http://help.slimframework.com and I will have a look into it please.
