### ISSUE TITLE
Why we dont use FastRoute 

### ISSUE THREAD

**Issue by prisis** [slimphp/Slim#825]
I think that we can make Slim much faster, when we use https://github.com/nikic/FastRoute/ for Slim routing.

I'm curious to hear your thoughts on this idea.

**Comment by silentworks** [comment]
After reading the comments on the blog post about FastRoute, it wouldn't support some features and still have some shortcomings. If you look at the comments on Nikic blog post you will see them outlined there.

**Comment by allyraza** [comment]
what in particular did you see that cannot be implemented

**Comment by silentworks** [comment]
I cant remember at this point in time, but if you want to continue discussion around this lets move it over to http://help.slimframework.com/ as the issues section here is mainly for Slim related issues.
