### ISSUE TITLE
Documentation on website does not discuss .htaccess file

### ISSUE THREAD

**Issue by cgsmith** [slimphp/Slim#826]
Update the documentation on the website to show the example .htaccess file and also update the site/install to show this as well.

**Comment by mattzuba** [comment]
It's already there...
http://docs.slimframework.com/#Route-URL-Rewriting

**Comment by cgsmith** [comment]
@mattzuba I see that. I think it would be helpful for newbies to Slim to have it here: http://docs.slimframework.com/#Getting-Started

There are even people on the forums that follow instructions linearly and are not aware of .htaccess: http://help.slimframework.com/discussions/problems/4781-hello-world-example

**Comment by silentworks** [comment]
@cgsmith I personally don't think this should be part of the getting started section, as you can run Slim with the .htaccess.

**Comment by cgsmith** [comment]
@silentworks You actually make my point.  Here is the problem with **not** having it in the _getting started_ section.
1. New programmers to the framework may not understand this is done through .htaccess
2. Having it in Route-URL-Rewriting is perfect, but Getting Started should be preferred.
3. Getting started is the first intro for a user

In addition, this doesn't necessarily have to be a .htaccess example.  A simple 'See this .htaccess example in route-URL-rewriting to configure the web server' would be awesome.

Let me know your thoughts.  I'd submit a PR but am still getting the hang of it ;)

**Comment by silentworks** [comment]
@cgsmith I should really re-read what I type before posting it, I mean't you can run Slim without .htaccess. 

However I see no harm in adding a link to the Getting Started though that point to the Route Url Rewrite section.

**Comment by cgsmith** [comment]
Right on! ill submit a pr soon

**Comment by cgsmith** [comment]
No link is added and this was closed?

**Comment by silentworks** [comment]
No PR was sent, also this is the wrong repo for this issue to be open on. This is related to docs which has its own repo https://github.com/codeguy/Slim-Documentation
