### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by gresakg** [slimphp/Slim#828]
The documentation on the website is deprecated. This should be at least clearly marked as developpers rely on it.

The docummentation says

> The view object’s setData() instance method will overwrite existing view data. You may use this method to set a single variable to a given value:

But in the source code setData method is marked with a deprecation warning.

``` php
/**
* DEPRECATION WARNING! This method will be removed in the next major point release
*
* Set data for view
*/
    public function setData()
```

**Comment by DavidePastore** [comment]
There a lot of this kind of things. `$app->request()->getRootUri()` and `$app->request()->getResourceUri()` are other examples.

**Comment by tuupola** [comment]
[Documentation](https://github.com/codeguy/Slim-Documentation) is in GitHub so everyone can  fork and submit PR.

**Comment by DavidePastore** [comment]
You're right. But I should say one thing: I don't like to see that a project has PRs and no one cares about them. It's a project that has about 4000 stars here and there should be a good group of people that works on this (in their free time). What do you think about it?

**Comment by tuupola** [comment]
I do not see any problems with Slim.

**Comment by DavidePastore** [comment]
I don't know. I see other projects like Symfony that have a great support behind them with daily changes, improvements and fixes. Here I see less releases, less support for the project and less participation in the last months.

**Comment by lplume** [comment]
That's why people fork/fix/PR: it's call open source.

**Comment by DavidePastore** [comment]
PR are useless if the project admin isn't present to include these fixes.

**Comment by silentworks** [comment]
@DavidePastore I am merging PRs as often as I can and really do appreciate the community help in sending them in. It wouldn't be fair to compare Slim to something like Symfony when it comes to project management. We are not full time employed by Slim and everyone who works on the project has other responsibilities.

Unfortunately at the moment @codeguy is a bit busier than usual and unable to get back to some PRs in a specific timeframe. The company he works for if I remember correctly does allow him to work on Slim at times, but with the company having other responsibilities, those would be priority over Slim.

If you have any suggestion on how to make this process more streamlined, we are all ears. Please bear with us as we are working with what we have.

**Comment by DavidePastore** [comment]
@silentworks It was not my intention to criticize Slim and the development team. Sorry, if it seemed so. One thing that you could make is to increase the developers number that have direct access to this repository, to have more hands and manage more features in less time. Right now I don't know who has direct access to this repository, but you know better than me who can be promoted to a real member.
What do you think?

**Comment by silentworks** [comment]
@DavidePastore no criticizim taken, I just wanted you to know the difference between project setups. 

I don't think its always correct to think that more developers on a project mean more issues closed, sometimes this can become an issue, especially when the original author has a vision of where he wants that tool to go and others might not understand this vision. But saying that I do see where you are coming from with that suggestion.

**Comment by DavidePastore** [comment]
@silentworks Yes, you're right. In a way or another I think that a project has some principle and it should respect them, so the project doesn't deviate.
I'm member of different projects and one of them has about 5 active developers that works together on different features/plugins. We can work without worry about the others job. If we have something to discuss, we just chat about it.
