### ISSUE TITLE
request->put() return no values when using ContentTypes Middleware

### ISSUE THREAD

**Issue by entraigas** [slimphp/Slim#832]
I'm working in a restful api and I think I found a bug.
To reproduce the bug you should use the ContentTypes Middleware and send a put request (not a post & _method=put).
The request should have "Content-Type: application/json" and a valid json string in the body.
Then when you try to load the values using $app->request->put(); you'll get an empty array.

I think this bug it's in the Request::post() function, in this line:

```
$this->env['slim.request.form_hash'] = Util::stripSlashesIfMagicQuotes($_POST);
```

I guess this could be a solution... but not sure about the consequences:

```
$this->env['slim.request.form_hash'] = Util::stripSlashesIfMagicQuotes($this->env['slim.input']);
```

As a workaround I suggest to put a  $_POST = $env['slim.input'] in the call() function of the middleware. See below.

```
public function call()
{
    $mediaType = $this->app->request()->getMediaType();
    if ($mediaType) {
        $env = $this->app->environment();
        $env['slim.input_original'] = $env['slim.input'];
        $env['slim.input'] = $this->parse($env['slim.input'], $mediaType);
        $_POST = $env['slim.input'];
    }
    $this->next->call();
}
```

**Comment by codeguy** [comment]
That method only works with the content-type is `application/x-www-form-urlencoded`. Otherwise, you have to use the `$request->getBody()` and decode appropriately. I'm hoping to get native JSON and XML support built into 3.x.
