### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by pine3ree** [slimphp/Slim#834]
Hello Josh,

what about refactoring slim->container['settings'] to a container singleton "config" object descendant of the Helper/Set parameters container class?

that way we can call 
$app->config->get('key', 'a default value');
$app->config->set('key', $value); handling array values and leveraging Helper/Set methods

kind regards

maks

**Comment by StJudeWasHere** [comment]
The Helper/Set class has already been removed in the development branch, Slim will extend Pimple instead, which seems much more convenient.

**Comment by pine3ree** [comment]
Hello @mnlg, yes i noticed that (i use pimple a lot), but the same applies here. 

The Helper/Set was used both as a parameter(data) container and as a IoC helper.
The data part has been moved to Collection, i think.

The configuration now has its own class.

I think it could be useful being able to call a shortcut method:

$app->config->get('key', 'a default value'))

to get $app['settings']['key'] if set, or 'a default value' otherwise

$app->config->set('key', $value) to call $app['settings']['key'] = $value;

kind regards

**Comment by silentworks** [comment]
You could create a class to do this.

``` php
class Config 
{
    protected $setting;

    public function __construct($setting)
    {
        $this->setting = $setting;
    }

    public function get($name)
    {
        return $this->has($name) ? $this->setting[$name] : null;
    }

    public function set($name, $value)
    {
        $this->setting[$name] = $value;
    }

    public function has($name)
    {
        return isset($this->setting[$name]);
    }
}
```

To use you would do

``` php
// Slim 2
$app->container->singleton('config', function ($c)
{
    return new Config($c['settings']);
});

// Call using
$app->config->get('mode');
```

Hope that helps.

**Comment by pine3ree** [comment]
@silentworks Thank You,

actually in my applications i use that pattern a lot (sf2 calls it a ParameterBag), even for request get|post|cookie|files. I have a base DataObject / DataSet class similar to Helper\Set without the ioc methods. I also use it for my quasi-anonymous|quasi-popo(quppo) entity classes.

But nowadays, after writing in zf2, sf2, yii, i am rethinking my way of writing php code.

Now i wouldn't use the container to add an on-demand feature that is always used in every application. Now i use a public property $config (Config)  instantiated in the Application constructor.
Fewer method calls, less overhead. The same goes for request/response/router. Obviously this works when you don't need to extend the $config, $request, $response....

To slim it down even more, although using

``` php
$app->config->get($key);
$app->request->query->get($key);
$app->request->cookies->get($key);
$app->response->header->set($key, $value);
$app->response->cookies->set($key, $cookieSettings);
```

is cleaner and it is what i have always used, I decided to revert back using simple arrays and simpler setter|getter class methods. This saves a few ms. In a framework that runs in 4-5 ms, adding another 4 ms means making it as twice as slow. Let make sure that only the model part of the application do that. 

When major frameworks will be available as php c-extensions, i will go back being a good guy, using good programming practices and interface everything it can|needs to be interfaced.

Of course micro-fmw as slim | flight stands apart: i'm just obsessing about performance right now. I think it will pass sooner or later.

kind regards

**Comment by silentworks** [comment]
Happy to hear you found a solution in the end. Closing this off as it seems to be solved.
