### ISSUE TITLE
Inconsistenty with redirect and urls within a subfolder

### ISSUE THREAD

**Issue by aronduby** [slimphp/Slim#838]
I have slim setup and running within a sub-folder, `/f/`. With routing I can easily say `/` and going to domain.com/f/ works great. If I call `$app->request->getResourceUri()` it returns `/`. However, if I say `$app->redirect->('/')` it goes all the way back to domain.com instead of the subfolder. This makes things a bit tricky, especially with user access.

If a user goes to a page and isn't logged in, within my auth middleware I want to be able to redirect them to the login page, passing along the url they started at. Easy enough within the route middleware:

``` php
if( /* user is not logged in */ ){
     $app = \Slim\Slim::getInstance();
     $app->flash('error', 'Login required');
     $app->redirect('/login?requested='.$app->request->getResourceUri());
}
```

Then on the login page I add the requested parameter as a form element, and when the user has successfully logged in I redirect to that page.

However, the redirection to `/login` will fail because it goes all the way to domain.com/login instead of domain.com/f/login. If I did manage to login properly with the requested parameter, the redirect after that would fail as well since the `getResourceUri()` will return `/` if you started at the homepage

**Comment by DavidePastore** [comment]
@aronduby 
Try to use

``` php
$app->redirect( urlFor('Login',
   array(
      'requested' => $app->request->getResourceUri()
   )
));
```

**Comment by aronduby** [comment]
Guessing that's supposed to be `$app->urlFor()`? Thanks for pointing that out as I had missed that functionality. The downside with that is now you have to make sure to name anything that you might need to redirect to, so basically I should name everything to be able to future proof it. 

I ended up creating a custom request object to handle this situation which I injected into Slim.

``` php
<?php
class BasedRedirectResponse extends \Slim\Http\Response{

    protected $base;

    public function __construct($base){
        $this->base = $base;
        parent::__construct();
    }

    /**
     * Redirect
     *
     * This method prepares this response to return an HTTP Redirect response
     * to the HTTP client.
     *
     * @param string $url    The redirect destination
     * @param int    $status The redirect HTTP status code
     */
    public function redirect ($url, $status = 302) {
        if($url[0] == '/'){
            $url = $this->base.$url;
        }
        parent::redirect($url, $status);
    }
}
?>
```

then in my index file after creating `$app` as a Slim instance I do the following to inject the new request object:

``` php
// override the default Slim\Http\Response object
$app->container->singleton('response', function () {
    return new BasedRedirectResponse('/f');
});
```

So now I have a work-around, but still feel the inconsistency system should be addressed.

**Comment by DavidePastore** [comment]
@aronduby Yes, you're right, you have to name everything. I use this approach in all the projects that I based on Slim and I find it very helpful. I think that the only consistent way to trace a route is to give to it an unique name, so you can refer to it even if one day you decide to change the url.

But:
How would you like it to work? Could you make an example?

**Comment by silentworks** [comment]
This is something I have seen someone blogged about a few days back, I think folks expect the behaviour to be that Slim should recognise that its in a subdirectory and redirect should use that information by default. So Slim redirect should be context aware.

```
htdocs | (webroot)
  - testsite | (Slim project)
    - index.php
```

``` php
$app->redirect('/'); // will redirect to htdocs rather than testsite
```

Symfony HttpFoundation would redirect to `testsite` which I think is what others expect this to do in Slim.

I would like your thoughts on this, I personally use named routes on all my projects as it is good practise all around, but there are some folks who don't.

**Comment by aronduby** [comment]
@DavidePastore Sorry, was gone for a while and just now getting caught back up on here. My suggestion would be to make it like @silentworks suggests and the `BasedRedirectResponse` object in my comment above.

**Comment by lrlopez** [comment]
@silentworks I also think that Slim should be aware of the project root; the current behaviour it really confuses my students. Nevertheless, they are legit causes where a redirect to another project in the same server could be needed. Also, changing the default behaviour would break down some apps that rely on the former inner working.

I see two different alternatives of implementing this:
1. Adding a third optional parameter to `redirect()` that could enable the project root aware redirect.
2. Adding a global config option that could enable it.

We could even combine them for good: if there is no optional parameter, we could get its value from the config option,

For mantaining backward compability, the new behaviour could be disabled by default.

Any thoughts on this?

**Comment by DavidePastore** [comment]
@lrlopez I like your solution :+1:

**Comment by silentworks** [comment]
@lrlopez I am waiting on @codeguy to get some free time to work out the best approach to sorting this, It might just be that we will make it possible in Slim 3 which will break BC anyway. But it would be good to have a solution for 2.4+ since its the most widely used right now.

**Comment by tuupola** [comment]
Personally I do not think `redirect()` method should be context aware. I prefer `redirect("/")` to be able to jump out of Slim folder. I use context aware `url()` helper everywhere which takes care of subfolder installations. Something like:

``` php
function url($path = null, $absolute = false) {
    $url = pathinfo($_SERVER["PHP_SELF"], PATHINFO_DIRNAME) . "/" . $path;
    $url = preg_replace("/\/\/+/", "/", $url);
    if ($absolute) {
        $url = "http://" . $_SERVER["SERVER_NAME"] . $url;
    }
    return $url;
};
```

and then in routes:

``` php
$app->redirect(url("/admin/cars"));
```

same helper is also used in templates

``` html
<link rel="stylesheet" href="<?php print url('css/normalize.min.css') ?>">
<script src="<?php print url('js/main.js') ?>?<?php print filemtime('js/main.js') ?>"></script>
<img src="<?php print url('img/icon-3.png') ?>" class="icon" /> 
```

**Comment by lrlopez** [comment]
Hmmm... @tuupola, your approach is nice, but implies adding boilerplate code into every app. Wouldn't be nice if that functionality was embedded into Slim?

May be that Mika is right about not touching `redirect()`. What about a `localRedirect()` method instead? It would be just a wrapper to `redirect()` with the URL corrected: No breaking changes nor different behaviours for the same method.

We could also add new methods to `slim/views` so that context aware URLs would be available for templating (i.e. `localUrlFor()`).

I can prepare a PR if you find this interesting.

**Comment by codeguy** [comment]
I prefer that `$app->redirect()` be dumb... this lets us redirect to external URLs or to any absolute URI path. Assuming the application base path would drastically limit the usefulness of this method.
