### ISSUE TITLE
log.writer and closures.

### ISSUE THREAD

**Issue by guice** [slimphp/Slim#839]
If we pass a closer to log.writer, it should treat it as an independent writer:

``` php
<?php
$app = new \Slim\Slim(array(
    'log.writer' => function($mixed) { var_dump($mixed) },
));
```

Instead, it tries to call ::writer on the closure itself:

```
Fatal error: Call to undefined method Closure::write() in /.../vendor/slim/slim/Slim/Log.php on line 317
```

**Comment by alexandrubagu** [comment]
A custom log writer must implement the following public interface:

```
<?php
public function write(mixed $message);
```

You must tell the Slim application’s log object to use your custom log writer. You can do so in your application’s settings during instantiation like this:

```
<?php
$app = new \Slim\Slim(array(
    'log.writer' => new MyLogWriter()
));
```

**Comment by silentworks** [comment]
Not an issue, as @alexandrubagu suggested Log writer requires a class that has a write method.
