### ISSUE TITLE
Resource Routing

### ISSUE THREAD

**Issue by rlm80** [slimphp/Slim#84]
Hi,

I only played with the framework a bit. So far I like what I see but something is bothering me about the routes definition with Slim::get(), Slim::post() and so on.

Consider a page with a form to change some user information. The page is first accessed with a GET request that returns an empty form, then the submitted form data comes back as a POST request on the same URL. I would have to define two routes :

```
Slim::get('/user/:id/', function($id) {
  // display empty form
})->name('user_form_get');

Slim::post('/user/:id/', function($id) {
  // do someting with posted data
})->name('user_form_post');
```

Both routes point to the same ressource (it's the same URL, just accessed with different methods), yet I had to define the URL pattern and the conditions that locate the ressource twice (not DRY) and use two different route names (confusing with respect to urlFor()). Besides, despite being the same ressource accessed in different ways, the handler functions are totally isolated from each other, even though it is likely that they will have things in common (since it's the same ressource). This seems very wrong to me.

I would rather have had something like this :

```
Slim::route('/user/:id/', function($id) {
  if (Slim::get())
    // display empty form
  elseif (Slim::post())
    // do someting with posted data
  else
    // error
})->name('user_form');
```

What are your thoughts about this ?

Thanks.

**Comment by codeguy** [comment]
Thanks for your feedback. You definitely have a valid concern. At this point, I would consider Slim a _micro_ framework that you can use _to write_ RESTful web applications. There are, I admit, some non-DRY aspects of Slim's current implementation when looked at from a purely RESTful perspective.

In the future Slim may become smarter about the concept of Resources. For now, Slim is just a small toolkit to help create RESTful APIs and small applications. It doesn't pretend to be anything more.

One critique I have about your examples above... you assume that a resource route "/resource/:id" would display an edit form for the given resource. Instead, that route should display the representation of the resource itself, not an edit form. The edit form could be accessed with "/resource/:id/new" or "/resource/:id/edit".

So, I certainly understand what you're saying. Short term, Slim is not going to fundamentally change. However, longer term, I do hope to make Slim smarter about how it handles Resources. I appreciate your feedback. I hope this clarifies some of Slim's goals and intentions.

**Comment by rlm80** [comment]
I'm not sure solving the problem would require the framework to be smarter about resources. All that's needed to solve it is to provide "method-less" routes : routes that match _any_ HTTP method, not specifically GET or POST or...

It wouldn't take anything away from the current implementation. Method-less routes could exist alongside the usual get, post, etc. routes. They would simply need to be checked for a match by the router after the normal routes, since they are less specific.

The syntax for creating them could be the one I posted above : _Slim::route()_, or if it causes backward compatibility issues, _Slim::any()_ would be fine too.

That way, in addition to solving the problems described above, you would satisfy people who like to put a strong emphasis on HTTP methods distinction (the REST fans) but also people attached to a more traditional approach to web development, where the HTTP method is considered more like a request parameter to be checked on occasion.

**Comment by bobdia** [comment]
How about something like the following:
<code>
    public static function multi($methodArray, $pattern, $callable ) {
        return self::router()->map($pattern, $callable, $methodArray);
    }
</code>

**Comment by tobsn** [comment]
s/multi/any ;)
