### ISSUE TITLE
Returns not found if the other one has a condition

### ISSUE THREAD

**Issue by joeyhipolito** [slimphp/Slim#845]
I have this route:

```
$app->get('/foo/:id/?' function($id) use ($app){

})->condition(array('id' => '[0-9]{1,11}$'));
```

That one above works well, but not with another route:

```
$app->get('/foo/:id/bar/?' function($id) use ($app){
   // returns not found
})->condition(array('id' => '[0-9]{1,11}$'));
```

**Comment by silentworks** [comment]
Do you have both these routes in the same file? if so move the example below above the other one. I am also not sure what the purpose of the ? is for in the routes?

**Comment by joeyhipolito** [comment]
`?` is for optional trailing slash..

**Comment by silentworks** [comment]
Can you move this over to http://help.slimframework.com/ and I will have a look there.
