### ISSUE TITLE
Possible Route Condition bug in 1.1

### ISSUE THREAD

**Issue by enposte** [slimphp/Slim#85]
Thanks for making such an elegant piece of software! I came across this issue, which doesn't seem to be intended.

The following code worked perfectly in 1.0.2:

```
Slim::get('/:domain', function ($domain) {
    echo $domain;
})->conditions(array('domain' => '[a-zA-Z0-9.-]+\.[a-zA-Z0-9.-]+'));
```

But in 1.1 the above doesn't work unless you do:

```
Route::setDefaultConditions(array(
    'domain' => '[a-zA-Z0-9.-]+\.[a-zA-Z0-9.-]+',
));

Slim::get('/:domain', function ($domain) {
 echo $domain;
});
```

The documentation implies that both should work in 1.1, but only the latter does.

**Comment by codeguy** [comment]
Thanks! Will look into this in the next day or so when I find some free time.

**Comment by codeguy** [comment]
@enposte Thanks for bringing this to my attention! I've pushed 1.1.1 which includes a fix for this issue.

**Comment by enposte** [comment]
That was quick! Thanks for looking into it.
