### ISSUE TITLE
Slim router absorbing GET flags

### ISSUE THREAD

**Issue by JoshWillik** [slimphp/Slim#854]
I have some code that looks like this:

```
    $app->get( '/pages/:pageid', function( $pageid ) use ( $app ){
      $page = new Page( $pageid );

      if( !is_null( $app->request->get( 'pageTemplate' ) ) ){
        $app->response->headers->set( 'Content-Type', 'text/html' );
        echo $app->render( 'ajaxPage.twig', [ 'page' => $page ] );
      } else {
        $app->response->headers->set( 'Content-Type', 'application/json' );
        echo $page;
      }
    });
```

If I send this request

```
GET /api/pages/1?pageTemplate
```

the code works if I am running a local apache instance, but explodes on a server running nginx. (Not sure if that is relevant or not ).

The _reason_ this code explodes, is because when the Slim route sees `:pageid` in the path, it matches `1pageTemplate` as the value that it should pass into the function. (but again, only on the server does it do this. On localhost, it matches `1` as you'd expect it to.

Is this desired behavior?

**Comment by tuupola** [comment]
What happens if you do

```
GET /api/pages/1?pageTemplate=foo
```

? It sounds like nginx.conf issue.

**Comment by JoshWillik** [comment]
Same issue. You can try it yourself at:
http://willik.ca/api/pages/80e295e1
http://willik.ca/api/pages/80e295e1?pageTemplate
http://willik.ca/api/pages/80e295e1?pageTemplate=foo

**Comment by JoshWillik** [comment]
If it makes a difference, localhost is running PHP 5.5.6, and the remote server is running 5.5.14

**Comment by tuupola** [comment]
As I mentioned it feels like nginx.conf issue. Looks like redirect rule eats away the ? character. There is example nginx config in [end of routing section](http://docs.slimframework.com/#Routing) of docs.

**Comment by JoshWillik** [comment]
I can't manage to get the the nginx.conf in the Slim docs to work for me. I always end up either downloading index.php as a text file or getting 403'd.
The (mostly) working config that I have now, is http://pastebin.com/7aSg2F2L
The only issue is that it seems to add the query string on to the end of the request path.
Not the proper place to ask for configuration help, I realize, but if you see any obvious issues with the config, please point them out. :)

**Comment by designermonkey** [comment]
I'm no nginx expert, but I have one client server running it, and even though the framework running isn't Slim on that one, maybe this could be helpful

```
    # Match any route and process it
    location / {
        # First attempt to serve request as file, then as directory, then fall back to index.html
        try_files $uri $uri/ /index.php?$query_string;
        # Uncomment to enable naxsi on this location
        # include /etc/nginx/naxsi.rules
    }
```

**Comment by JoshWillik** [comment]
You're a life saver.
I had `try_files $uri $uri/ /index.php;` instead of `try_files $uri $uri/ /index.php?$query_string;`

**Comment by designermonkey** [comment]
Glad to help.
