### ISSUE TITLE
HTTP_ACCESS_CONTROL_REQUEST_HEADERS issue

### ISSUE THREAD

**Issue by dikaso** [slimphp/Slim#855]
I'm building angular app and slim is used as api endpoint.

Since I'm calling routes from different domain I need to enable CORS.

You can see below that I'm fetching `HTTP_ACCESS_CONTROL_REQUEST_HEADERS` from server super global. Reason behind this is that slim returns empty when using `$app->request->get('HTTP_ACCESS_CONTROL_REQUEST_HEADERS')`.

Why? 

``` php
$app->map('/:x+', function($x) use($app){
    // Access-Control headers are received during OPTIONS requests
    if ($app->request()->getMethod() == 'OPTIONS') {

        if ($app->request->get('HTTP_ACCESS_CONTROL_REQUEST_METHOD'))
            $app->response->headers->set("Access-Control-Allow-Methods:","GET, POST, PUT, DELETE, OPTIONS");

        if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
            $app->response->headers->set("Access-Control-Allow-Headers", "{$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");

    }
    http_response_code(200);
})->via('OPTIONS');
```

**Comment by tuupola** [comment]
If you are trying to access headers you should use the following instead:

``` php
$app->request->headers->get("Access-Control-Request-Method")
```

You are currently trying to access `$_GET["HTTP_ACCESS_CONTROL_REQUEST_METHOD"]` variable.
