### ISSUE TITLE
Heroku Documentation

### ISSUE THREAD

**Issue by corbanb** [slimphp/Slim#857]
It would be great to see some info added to the readme or wiki on getting going with heroku with all the new updates for [php](https://devcenter.heroku.com/articles/php-support).

https://github.com/codeguy/Slim#setup-your-web-server - something here or else where you see fit.

Some of the questions I think others would be looking for info around is the [Procfile](https://devcenter.heroku.com/articles/custom-php-settings#specifying-which-web-server-to-use) specifically for the [nginx_app.conf](https://devcenter.heroku.com/articles/custom-php-settings#nginx) file setup or [apache_app.conf](https://devcenter.heroku.com/articles/custom-php-settings#apache) file setup. This is such a great way to get apps up and running fast seems very obvious for this.

**Comment by silentworks** [comment]
I haven't used Heroku for PHP as yet, but if you know the process, would you mind sending a PR and we will get it merged in.

**Comment by silentworks** [comment]
Send PR when its ready, I'm closing this off for now.
