### ISSUE TITLE
User-Assignable Request Data

### ISSUE THREAD

**Issue by andrewmunsell** [slimphp/Slim#858]
In some frameworks in other languages (particularly, Express.js in Node.js), middleware is handled such that a single request and response are passed through the workflow. In other words, if you had an authentication middleware, you could check the user's credentials and load the user object from your database, setting it in the request variable so that it is accessible to all future middleware.

Something like this would be extremely valuable in Slim. Because there's already only a single instance of the request object that's accessible in each middleware and route, all that's needed to make this sort of functionality a possibility is some sort of key-value store on the request object.

For example:

```
\Slim\Http\Request
    setData($key, $value);
    getData($key);
```

Internally this would be a simple associative array, with some sugar to return null if the key doesn't exist when `getData` is called.

Though `flashNow` could also be used in this manner, you'd ideally not want the data to be accidentally exposed to clients through some erroneous template code that just dumps flash messages.

I would be happy to write this and send a pull request, assuming the API proposed above is suitable.

**Comment by StJudeWasHere** [comment]
You can access the $app object in the middleware using `$this->app`, from there you can also access the app config and the environment. These may be a better places to store your user data as the Request object is supposed to represent the HTTP request.

You can check the ContentType or ContentNegotiation middleware to see how they handle this, or ask in the help forum http://help.slimframework.com for a different implementation.

**Comment by andrewmunsell** [comment]
Well if the environment is the Slim-accepted pattern for storing data, then I'll go ahead and close this. Thanks for letting me know!
