### ISSUE TITLE
More public variables are needed in smartyView class

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#86]
There are various other useful smarty variables besides `SmartyView::$smartyDirectory`, `SmartyView::$smartyCompileDirectory`, `SmartyView::$smartyCacheDirectory`, and `SmartyView::$smartyTemplatesDirectory`. 

I'm thinking about: 

[$smarty->caching](http://www.smarty.net/docsv2/en/variable.caching.tpl)

[$smarty->cache_lifetime](http://www.smarty.net/docsv2/en/variable.cache.lifetime.tpl)

[$smarty->force_compile](http://www.smarty.net/docsv2/en/variable.force.compile.tpl)

and [$smarty->compile_check](http://www.smarty.net/docsv2/en/variable.compile.check.tpl)

At the moment I have to set them manually inside my route callback function. Is there any chance for you to add them to `smartyView.php`  as public static class variables?

**Comment by codeguy** [comment]
I agree, but I think adding all of these to the custom View adapter may be unwieldy. Instead, you can use the custom View's `getInstance()` method to fetch the Smarty object and set these yourself directly.

**Comment by ghost** [comment]
Yes, with "have to set them manually inside my route callback function", I meant "use the custom View's getInstance() method to fetch the Smarty object and set these yourself directly" :) 

But that's a bit overkill, you have to add them to every callback function because you don't know which route is called first.

Am I missing something? There should be a cleaner and smarter way to set these variables once in the code.

**Comment by codeguy** [comment]
`SmartyView::getInstance()` is a public static method. You can set this once right after you initialize Slim and the settings will be available for all of your route callbacks. I can certainly add additional methods to the `SmartyView` class as you've suggested, but I'm working on other tasks at the moment. You're more than welcome to send me a pull request though. Hope this helps.

**Comment by ghost** [comment]
Ok great. I'll hack it through and will send you a pull request. Thanks.

**Comment by codeguy** [comment]
Closing this out. Feel free to submit a Pull Request if you have not already when available.
