### ISSUE TITLE
log depends on environment - CLI issues

### ISSUE THREAD

**Issue by opb** [slimphp/Slim#863]
Hi there

If I try to access `$app->environment` while in a CLI script, this throws up errors, as none of the $_REQUEST vars that `environment` uses are available. This would be fine, but accessing `$app->getLog()` makes use of the environment. This basically indicates that logging features can't be used on the CLI.

Is this an issue, or is it working as intended? Any suggestions for a workaround?

Many thanks

**Comment by tuupola** [comment]
What do you mean by cli script? You mean the internal PHP server?

 `php -S 0.0.0.0:8080`

**Comment by StJudeWasHere** [comment]
The `environment` seems to be used when creating the `LogWriter` object only:

```
new \Slim\LogWriter($c['environment']['slim.errors']);
```

You could pass your own `LogWriter` object to Slim instead, and instantiate it without the `environment` object, something like this:

```
$app = new \Slim\Slim(array(
    'log.writer' => new \Slim\LogWriter(@fopen('php://stderr', 'w'))
));
```

Anyway, you may want to ask this one on the [support forums](http://help.slimframework.com) as it's not an issue with the framework.

**Comment by opb** [comment]
@tuupola Sorry for the lack of clarification, I meant when running "php mySlimScript.php". It's just some cli-based commands that I've put together for my Slim app, in a similar way to Laravel having artisan.

@mnlg Thanks for the suggestions. The issue was highlighted to me when using the default log writer, but seemingly stems from `$app->environment` producing PHP Notices. As an example:

``` php
// testEnv.php
<?php

require __DIR__.'/vendor/autoload.php';

use Slim\Slim;

$app = new Slim();

var_dump($app->environment);
```

Running `php testEnv.php` will give several notices similar to this:

```
PHP Notice:  Undefined index: REQUEST_METHOD in /Volumes/UserHomes/oliver2/Development/repos/searchapi/vendor/slim/slim/Slim/Environment.php on line 124

Notice: Undefined index: REQUEST_METHOD in /Volumes/UserHomes/oliver2/Development/repos/searchapi/vendor/slim/slim/Slim/Environment.php on line 124
```

I wasn't sure if this was intentional, or something that should be handled by my PHP setup as opposed to Slim (ignore Notices?), or whether it was something worth reporting.

Thanks again.

**Comment by tuupola** [comment]
Slim probably should check if `$_SERVER['REQUEST_METHOD']` exists. In the meanwhile as workaround you could disable PHP notices with:

``` php
error_reporting(E_ALL & ~E_NOTICE);
```

**Comment by StJudeWasHere** [comment]
Slim is a request response framework, so having all that notices when running from the command line is the expected behaviour. Maybe using something like Symfony console would work better in this case.

**Comment by opb** [comment]
I actually have Symfony console pulled in, but am using Slim and its container for the basis of my app, so have been making use of it in the console commands.

Thanks for the responses guys, just wanted to flag this up in case it was something that needed looking at.

Cheers
