### ISSUE TITLE
gzip encoded POST

### ISSUE THREAD

**Issue by aktau** [slimphp/Slim#867]
One of my clients likes to send gzip'ed POST requests to save bandwidth (it helps a lot, the data is quite redundant). It's my impression that Slim doesn't handle this case by default.

How would you suggest I best handle this so that the uncompressed content gets unfolded into `$app->request->post()`?

**Comment by lplume** [comment]
Perhaps a middleware is a good way to solve this.

**Comment by lplume** [comment]
More: there is the ContentTypes middleware, maybe try to take a look at that middleware

**Comment by lplume** [comment]
More more: it parses XML,json, CSV request body, I think you could implement the parser and add it as a setting

**Comment by lplume** [comment]
Once more: contenttypes middleware should be not responsible for this (sorry) I think the best way is a separate middleware dealing with "content-encoding" header.

**Comment by tuupola** [comment]
See the first comment in [gzuncompress](http://php.net/manual/en/function.gzuncompress.php) manpage.
