### ISSUE TITLE
Nesting level too deep

### ISSUE THREAD

**Issue by davidhuser** [slimphp/Slim#869]
Hi

I get a "Nesting level too deep - recursive dependency" error on [this URL](http://korsettkollektiv.com/api/public/info.php). On an other server with PHP 5.4 it works fine.

If I change the [line 1240 in `vendor/slim/slim/Slim/Slim.php`](https://github.com/codeguy/Slim/blob/master/Slim/Slim.php#L1240)
`if(in_array($newMiddleware, $this->middleware))` 
to 
`if(in_array($newMiddleware, $this->middleware, TRUE))`the error resolves as stated [here](https://coderwall.com/p/5efmag).

How should I go about this when I don't like to tinker with the vendor files?

**Comment by silentworks** [comment]
I think you should extend the Slim.php class and override that method, that way you don't break anything in the core files.
