### ISSUE TITLE
Class autoloading outside of Slim directory

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#87]
I'm looking to create a models directory and have the classes autoloaded from that. I noticed the autoload function only looks in the slim directory. Is there a config option to set more autoload paths or can this be changed? I know a plugin would probably do the trick but creating a plugin for a model just doesn't feel right.

**Comment by codeguy** [comment]
Slim purposefully makes as few assumptions about your own application created with Slim. Slim will autoload its own classes, but it is up to you to provide any additional autoloaders (with `spl_autoload_register`) to load your own class files as you need.

**Comment by ghost** [comment]
Awesome thanks. Registering another autoloader was my fallback just wanted to make sure there wasn't something within the framework I could take advantage of first.
