### ISSUE TITLE
PDO Session handler

### ISSUE THREAD

**Issue by helluvamatt** [slimphp/Slim#871]
Would anyone be interested in a PDO Session handler?

Here is the preliminary code:

https://github.com/helluvamatt/www-php-common/blob/master/src/Schneenet/PdoSession.php

**Comment by tuupola** [comment]
Make a composer installable package out of it and see what happens :)

**Comment by silentworks** [comment]
I am currently leveraging Laravel Session Library with slim, I will release the middleware soon along with steps needed to get it setup. Laravel Session allows you to use Database, File, Redis, Memcache or even write your own based on their interface.

**Comment by silentworks** [comment]
On another note, I will close this off since its not a Slim issue, can you move it over to http://help.slimframework.com/ please.
