### ISSUE TITLE
Middleware on groups not executing

### ISSUE THREAD

**Issue by dmiedema** [slimphp/Slim#872]
When using grouped routes middleware functions don't seem to execute.

I currently have

``` php
function apiKeyCheck() {
  $app = \Slim\Slim::getInstance();
  $apiKey = $app->request->get('X-API-key');
  if ($apiKey !== 'derpy') {
    $app->halt('418', 'invalid api key for coffee pot. Please brew again');
  }
}
// this is the base group defined. No other groups are defined, only other base routes such as /
$app->group('/v0', 'apiKeyCheck', function() use($app) {
... // other groups are listed here. omitted because holy crap that'd make this long
});
```

however the `apiKeyCheck` function doesn't seem to work when calling routes in sub groups.

I tried to follow the format [of the docs](http://docs.slimframework.com/#Route-Middleware) but it doesn't seem to like it.

**Comment by silentworks** [comment]
Are you sure this is the case? I have a few sites with middleware on route groups. Try adding some debugging code in `apiKeyCheck()` to make sure its being called. If its still not working open this up on http://help.slimframework.com/ and I will assist you there.
