### ISSUE TITLE
routes in group with subgroups not executing

### ISSUE THREAD

**Issue by dmiedema** [slimphp/Slim#873]
Defining routes inside a group with other groups inside it (i do like groups, dawg) seem to not execute.

I currently have

``` php

$app->group('/v0', function() use ($app) {

  $app->get('(/)', function() use ($app) {
    processMessage("API v0", $app); // processMessage checks headers and returns JSON or text/plain depending on headers, no other magic happens there
  });

  $app->group('/beers', function() use ($app) {
    ... // methods and things here working great
  });

  // Other groups here, 3 other ones specifically
});
```

Accessing my sub groups, `URL/v0/beers` works great and everything is awesome but trying just `URL/v0` throws a 404 error. it doesn't seem to be matching `GET` requests when a group contains subgroups.

I have the `GET` defined above the groups right now however when its listed at the end it still seems to throw a 404. Is there something I'm missing to get routes to match in a group when said group has subgroups?

**Comment by tuupola** [comment]
Can you include the code where you define the `GET /v0` route.

**Comment by dmiedema** [comment]
I don't explicitly define a `GET /v0` route. `v0` is a group that contains subgroups, `beers`, etc.

So i have

``` php
$app->group('/v0', function() use ($app) {
  $app->get('(/)', function() use ($app) {
    // accessing this route, v0/, throws a 404 error
  });
  $app->group('/beers', function() use ($app) {
    $app->get('(/)', function() use ($app) {
      // code that works awesome
      // v0/beers
    });
    $app->get('/:id', function($id) use ($app) {
      // more code that works awesome
      // v0/beers/31
    });
  });
});
```

the sub groups inside `v0` work fine, so `v0/beers/:id` works as well as any other routes defined in a subgroup. `breweries` for example (not typed out) works fine

However when calling a route defined inside `v0` (`v0/` for example) that is not inside one of its subgroups throws a `404` error

**Comment by tuupola** [comment]
I just tried this code:

``` php
$app->group('/v0', function() use ($app) {
  $app->get('(/)', function() use ($app) {
      print 'v0';
  });
  $app->group('/beers', function() use ($app) {
    $app->get('(/)', function() use ($app) {
        print 'beers';
    });
    $app->get('/:id', function($id) use ($app) {
        print $id;
    });
  });
});
```

Running the above with `php -S 0.0.0.0:8080` and  Slim version 2.4.3. When accessing `/v0`or `/v0/` I get result `v0`. When accessing `/v0/beers`or `/v0/beers/` I get result `beers`. When accessing `/v0/beers/foo` I get result `foo`. So everything seems to be working. Maybe something in rewrite rules or older version of Slim?

**Comment by dmiedema** [comment]
Awesome, thanks!

Since everything else was working fine i wasn't sure if it was my config or not but as long as thats the case then this issue isn't an issue.

Ill double check my rewrite rules & version.

Thanks again for your help

**Comment by dmiedema** [comment]
Problem was between keyboard and chair.
Didn't realize i was attempting to GET from the wrong domain (production instead of staging)

Thanks for your help everyone.
