### ISSUE TITLE
The help sites is down

### ISSUE THREAD

**Issue by Tropicalista** [slimphp/Slim#874]
I have discovered this small framework surfing on google, where a lot of useful question were indexed pointing to http://help.slimframework.com/. However it seems that this site is down. 

Too bad. It could be really helpful. Could you please check?

Thanks

**Comment by tuupola** [comment]
Works for me.

http://www.downforeveryoneorjustme.com/

**Comment by silentworks** [comment]
Working fine here too. Maybe the question your found indexed was deleted by the user who posted it.

**Comment by Tropicalista** [comment]
Now it's working also for me. Probably a server overload....

Close
