### ISSUE TITLE
Return value of route functions

### ISSUE THREAD

**Issue by HendrikF** [slimphp/Slim#877]
Is there a way to reuse the return value of the route functions?
When building an RESTful API or similar it would be great, if the functions could return the requested data and after that the framework executes a specified command on the value, like `echo json_encode(val)`.
Maybe this can be implemented with a anonymous function or a callback?

I think it will take time if this feature will be released, where is the function called, so that I can implement it myself?

**Comment by silentworks** [comment]
Can you move this over to http://help.slimframework.com please, its not a issue with the framework but more of a question.
