### ISSUE TITLE
PrettyExceptionsTest::testReturnsDiagnosticsForErrorResponse uncovers output buffer level issue in PHPUnit 4.2.2

### ISSUE THREAD

**Issue by fredemmott** [slimphp/Slim#880]
```
$ php5 ../../vendor/bin/phpunit --filter=testReturnsDiagnosticsForErrorResponse --tap --config phpunit.xml.dist tests/Middleware/PrettyExceptionsTest.php
TAP version 13
ok 1 - # RISKY Test code or tested code did not (only) close its own output buffers
1..1
```

Based on looking at the test and https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php#L1931 it looks like this is a real issue in Slim.

cc @GrahamCampbell

**Comment by codeguy** [comment]
Yep this is biting a lot of frameworks. This is a moot issue in the latest dev branch.
