### ISSUE TITLE
Slim in VirtualHost as proxy

### ISSUE THREAD

**Issue by DavidePastore** [slimphp/Slim#885]
Hi, I'm working on an application that is developed under a simple **subdirectory** of htdocs of Apache.
Then I created a VirtualHost on another pc that refers to this directory using Proxy.

My issue is that the application doesn't work in the VirtualHost version because it generates urls (using [Slim-views](https://github.com/codeguy/Slim-Views) magic `urlFor('RouteName')`) that refers to my **subdirectory** directory.

My VirtualHost configuration is this:

```
<Proxy *>
  Order deny,allow
  Allow from all
</Proxy>
ProxyPass          /   http://192.168.0.12/subdirectory/
ProxyPassReverse   /   http://192.168.0.12/subdirectory/
```

Do you know how can I make it work?

Thanks

**Comment by ffflabs** [comment]
Is it mandatory for you to use urlFor? Managing routes manually is doable for a small number of routes 

If it is, you could write a custom middleWare to to translate subdirectory routes to proxied routes. In the simplest scenario it's just an str_replace.

**Comment by DavidePastore** [comment]
@amenadiel You're right. The problem is that the project should work in two cases: with and without proxy. If I created a middleware, how can I handle the two cases?

**Comment by DavidePastore** [comment]
I ended up creating a PR for this. #892 .

**Comment by silentworks** [comment]
Closing this off and leaving the PR open.
