### ISSUE TITLE
Get all headers as associative array

### ISSUE THREAD

**Issue by DavidePastore** [slimphp/Slim#888]
Is there a simple method to return all the headers from the `$app->request()`?

What I'm using now to get this result is this:

```
$headers = $app->request()->headers;
$iterator = $headers->getIterator();
$requestHeaders = array();
foreach($headers as $key => $value) {
    $requestHeaders[$key] = $value;
}
```

Maybe it could be useful to implement a method for this use case.

What do you think?

**Comment by tuupola** [comment]
This seems like a bug or documentation is wrong. Documentation says headers should be an associative array.

``` php
// Get request headers as associative array
$headers = $app->request->headers;
```

However actual return value is instance of `Slim\Http\Headers` class which implements `ArrayAccess`. For me this is not the same thing. What you can do though is to call `all()`method of `Slim\Helper\Set`:

``` php
$headers = $app->request->headers->all();
var_dump($headers);
```

or the following will also work:

``` php
$headers = (array)$app->request->headers;
var_dump($headers);
```

Note that `$app->request->headers` might not actually contain all request headers sent by browser. You might be better off using `$_SERVER` superglobal.

**Comment by DavidePastore** [comment]
Thanks @tuupola . You're very helpful.

**Comment by designermonkey** [comment]
`Slim\Http\Headers` parses the entire `$_SERVER` global.

**Comment by tuupola** [comment]
Parses yes, but includes only `CONTENT_TYPE`, `CONTENT_LENGTH`, `PHP_AUTH_USER`, `PHP_AUTH_PW`, `PHP_AUTH_DIGEST`,   `AUTH_TYPE` and anything beginning with `HTTP_` and `X_`. Anything else such as `REDIRECT_HTTP_AUTHORIZATION` is discarded.

**Comment by DavidePastore** [comment]
@tuupola Do you mean it's better to improve `Headers::extract($data)` method?

**Comment by silentworks** [comment]
Since this is not a bug or issue can you move it over to http://help.slimframework.com/ please. Closing this out.

**Comment by tuupola** [comment]
Regarding the redirected headers see #898.
