### ISSUE TITLE
HaangaView

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#89]
Add a new custom View class for the Haanga template library.

https://github.com/crodas/Haanga

http://css.dzone.com/news/php-template-engine-comparison

**Comment by iromli** [comment]
hi,

i wrote a custom View class for Haanga template, you could take a look [here](https://github.com/iromli/Slim/commit/fb65eb463a2fb514c6c42e34bb889bc0a07a7f98).

**Comment by codeguy** [comment]
@iromli Do you want to send me a pull request? I'll be glad to pull in your code.

**Comment by iromli** [comment]
sure, i'll re-fork Slim and sent you a new HaangaView code so you can take a look on it (the old one was accidentally deleted)
