### ISSUE TITLE
Due date for release 3.0

### ISSUE THREAD

**Issue by DavidePastore** [slimphp/Slim#890]
Is there a due date for the release of Slim 3? I have seen that there are several issues to be resolved.

**Comment by silentworks** [comment]
@DavidePastore not at the moment, we are going to release a beta version soon, but I am not sure how soon. I will try and liaise with @codeguy today and see when he has in mind.

**Comment by DavidePastore** [comment]
Thanks for your response! :pineapple:

**Comment by codeguy** [comment]
Yep. Goal is to have a beta release sometime soon. I need to write a blog post about the framework status. It's on hiatus for a bit until I can free up some time to continue working on it. I have every intention of picking up development again as soon as I can wrap up some large projects at work and my upcoming O'Reilly book.

**Comment by DavidePastore** [comment]
Ok @codeguy. Good news from you. Good luck with your book. :cake:

**Comment by sgsheg** [comment]
:+1:

**Comment by nubs** [comment]
:smile_cat:

**Comment by cochesaurus** [comment]
A book about creating web applications with slim would be great 😊

**Comment by silentworks** [comment]
@cochesaurus I heard there was one in the work sometime ago by @jeremykendall but I am not too sure how far along he has gotten with it.

**Comment by thinkjson** [comment]
Any update on this?

**Comment by vik-singh** [comment]
Any movement on the release?

**Comment by prisis** [comment]
ping @codeguy

**Comment by 3nk** [comment]
Any news ?

**Comment by jeremykendall** [comment]
@silentworks Sadly family, new startup, moving too much, etc. has gotten in the way of any progress on the book. It's on the very bottom of my list right now, but it's still on the list.

**Comment by vik-singh** [comment]
@codeguy still alive? :-)

**Comment by codeguy** [comment]
Still alive. It'll be ready when it's ready. Life gets in the way sometimes :)
