### ISSUE TITLE
Test "ViewTest::testSetTemplatesDirectory" fails

### ISSUE THREAD

**Issue by Marwelln** [slimphp/Slim#896]
I just installed slim (`composer require slim/slim:~2.0`) and ran the tests.

```
cd vendor/slim/slim
phpunit
```

Got this error:

```
Time: 1.28 seconds, Memory: 6.75Mb

There was 1 failure:

1) ViewTest::testSetTemplatesDirectory
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'templates'
+'templates/'

H:\...\vendor\slim\slim\tests\ViewTest.php:167
```

Which is this:

```
public function testSetTemplatesDirectory()
{
    $view = new \Slim\View();
    $view->setTemplatesDirectory('templates/'); // <-- Should strip trailing slash

    $this->assertAttributeEquals('templates', 'templatesDirectory', $view);
}
```

**Comment by silentworks** [comment]
Yeah this is a weird one, it only happen on certain environment it seems, I think I had this error on Windows environment, while Travis CI doesn't seem to have this issue.

**Comment by tuupola** [comment]
To me it looks like test always fails in Windows. Looking at the code of [setTemplatesDirectory()](https://github.com/codeguy/Slim/blob/master/Slim/View.php#L207) the offending line is this.

``` php
$this->templatesDirectory = rtrim($directory, DIRECTORY_SEPARATOR);
```

In Windows `DIRECTORY_SEPARATOR` is `\`. In the test code tries to remove `\`from string `templates/`. Result is `templates/` thus the test fails. So Slim code works fine. Test itself is not portable. It should be something like:

``` php
public function testSetTemplatesDirectory()
{
    $view = new \Slim\View();
    $directory = 'templates' . DIRECTORY_SEPARATOR;
    $view->setTemplatesDirectory($directory);

    $this->assertAttributeEquals('templates', 'templatesDirectory', $view);
}
```

**Comment by codeguy** [comment]
This has been fixed at some point in time.
