### ISSUE TITLE
routeGroups is null, mandatory?

### ISSUE THREAD

**Issue by pioter** [slimphp/Slim#899]
i must add routegroup?  
 protected function processGroups()
    {
        $pattern = "";
        $middleware = array();
        foreach ($this->routeGroups as $group) {

**Comment by tuupola** [comment]
It is a bit hard to understand the question. What are you trying to do?

**Comment by pioter** [comment]
Hi,

i added routes by:

foreach ($routes as $routeKey => $route) {
                    $this->addControllerRoute($route['route'],
$route['controller'] . ':' .
$route['action'])->via($route['via'])->name($route['alias']);
                }

i dont use method AddRoutes. Next i receive warning:

$this->routeGroups is empty.I should add group routes?

router.php
protected function processGroups()
    {
        $pattern = "";
        $middleware = array();
        foreach ($this->routeGroups as $group) {
            $k = key($group);
            $pattern .= $k;
            if (is_array($group[$k])) {
                $middleware = array_merge($middleware, $group[$k]);
            }
        }
        return array($pattern, $middleware);
    }

peter

2014-09-21 19:59 GMT+02:00 Mika Tuupola notifications@github.com:

> It is a bit hard to understand the question. What are you trying to do?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeguy/Slim/issues/899#issuecomment-56306838.

## 

pozdrawiam
Piotr

**Comment by silentworks** [comment]
@pioter I am still unsure what you are trying to accomplish? Can you move this over to http://help.slimframework.com please, as the issues section here is to report bug in the frameworks. Closing this out.
