### ISSUE TITLE
Undefined Constant errors

### ISSUE THREAD

**Issue by jakefolio** [slimphp/Slim#90]
Page renders on first load fine, but then I start getting errors like the following:
[ERROR] 2011-02-02T12:39:21-06:00 - Message: Use of undefined constant (jπ - assumed '(jπ' | File: /vhost/path/app/slim/Slim.php | Line: 293 | Level: 8
[ERROR] 2011-02-02T12:39:21-06:00 - Message: Use of undefined constant (jπ - assumed '(jπ' | File: /vhost/path/app/slim/Slim.php | Line: 293 | Level: 8
[ERROR] 2011-02-02T12:39:29-06:00 - Message: Use of undefined constant P∆ª - assumed 'P∆ª' | File: /vhost/path/app/slim/Slim.php | Line: 293 | Level: 8
[ERROR] 2011-02-02T12:40:05-06:00 - Message: Use of undefined constant (jπ - assumed '(jπ' | File: /vhost/path/app/slim/Slim.php | Line: 293 | Level: 8
[ERROR] 2011-02-02T12:40:05-06:00 - Message: Use of undefined constant (jπ - assumed '(jπ' | File: /vhost/path/app/slim/Slim.php | Line: 293 | Level: 8
[ERROR] 2011-02-02T12:40:15-06:00 - Message: Use of undefined constant P∆ª - assumed 'P∆ª' | File: /vhost/path/app/slim/Slim.php | Line: 293 | Level: 8
[ERROR] 2011-02-02T12:40:20-06:00 - Message: Use of undefined constant (jπ - assumed '(jπ' | File: /vhost/path/app/slim/Slim.php | Line: 293 | Level: 8
[ERROR] 2011-02-02T12:40:20-06:00 - Message: Use of undefined constant (jπ - assumed '(jπ' | File: /vhost/path/app/slim/Slim.php | Line: 293 | Level: 8

Any help would be appreciated.  I'm developing on OSX 10.6.5 with PHP 5.3.3 (apache).

**Comment by codeguy** [comment]
No idea what this is. Line 293 of Slim.php deals with setting setting SSL support for secure cookies. Are you sure you haven't specified these weird characters in your Slim app settings during `Slim::init()`?

**Comment by jkaflik** [comment]
That seems to be a problem with charset

**Comment by codeguy** [comment]
@Kofel Agreed. I've looked over the code just in case but do not see anything that would even potentially cause this error.

@jakefolio Were you able to setup an isolated PHP test environment to troubleshoot this as we discussed on IRC?

**Comment by jakefolio** [comment]
@codeguy I tested the code on WAMP and everything worked fine.  I'm going to go ahead and push blame to the OSX php install.  I'm going to blow out the OSX install and use homebrew to setup a new environment.  I will update you guys on the outcome.

**Comment by codeguy** [comment]
@jakefolio Sounds good. I'm going to close this out for now, but if you discover this _is_ a bug, let me know and I'll reopen. Thanks!
