### ISSUE TITLE
Not found (404) alters status code on HEAD request

### ISSUE THREAD

**Issue by aktau** [slimphp/Slim#905]
Something strange popped up. On my site I don't have a '/ping' route. When I run cURL on it to fetch the status code, I get this:

``` bash
➜  server  curl -k -s -o /dev/null -w "%{http_code}" https://my.server/ping
404%

➜  server  curl -k -s -o /dev/null -I -w "%{http_code}" https://my.server/ping
200%
```

The difference here being that the first request happens with a **GET** request and the second one with a **HEAD** request. Am I missing something or is this a bug?

I have a custom `$app->notFound()` handler that returns a pretty 404 webpage and returns the 404 status code. It obviously doesn't get called for a HEAD request.

**Comment by tuupola** [comment]
Do I understand correctly you do not have HEAD route defined? Can you provide minimal Slim code to reproduce the problem.

**Comment by aktau** [comment]
I have nothing in place for '/ping', not route, nothing. It should thus return 404, for both **GET** and **HEAD**, should it not?

**Comment by aktau** [comment]
Said otherwise, you can reproduce this on your own slim for any route that doesn't exist.

**Comment by tuupola** [comment]
Does not seem to be true.

``` php
<?php

require "vendor/autoload.php";

$app = new \Slim\Slim();

$app->notFound(function() use ($app) {
    print "FOO";
});

$app->run();
```

```
$ php -S 0.0.0.0:8081 index.php

$ curl -k -s -o /dev/null -I -w "%{http_code}" http://0.0.0.0:8081/nosuch
404

$ curl -k -s -o /dev/null -w "%{http_code}" http://0.0.0.0:8081/nosuch
404
```

Could you provide minimal code which reproduces your problem.

**Comment by silentworks** [comment]
Closing this one out as there has been no reply on it for awhile.
