### ISSUE TITLE
Bit difference when sending binary data

### ISSUE THREAD

**Issue by alycklama** [slimphp/Slim#906]
I'm sending a picture to the client, but some how an extra bit is added!

``` php
$app->get('/image.jpg', function() use ($app) {
    $app->response->headers->set('Content-type', 'image/png');
    $app->response->headers->set('Content-Transfer-Encoding', 'binary');

    $contents = file_get_contents('images/logo.png');
    $app->response->body($contents);
});
```

When I check the differences with an hex editor, I can see that a 09 has been added at the beginning of the file. Do you have any idea what could be the reason of this behavior?

![bit_difference](https://cloud.githubusercontent.com/assets/6285202/4646947/82f51174-5477-11e4-8b0f-35937e016f0e.png)

I've added the original file, although this behavior exists for any file type.

![logo](https://cloud.githubusercontent.com/assets/6285202/4646962/a9429d38-5477-11e4-987a-86599a57fb9e.png)

**Comment by ha17** [comment]
Using your code I was able to see the image. Perhaps you have an errant tab buffered somewhere before the final output?

**Comment by alycklama** [comment]
There was a required_once file that at the end of the php file (?>) had a tab... Thanks a lot for helping me out!

**Comment by ha17** [comment]
@alycklama -  a lot of people don't use the closing ?> at the end of a file for this very reason. Then PHP won't buffer it to include in the output, it will be ignored as just extra whitespace around the code.
