### ISSUE TITLE
Improvement in loading routings functions

### ISSUE THREAD

**Issue by hachreak** [slimphp/Slim#913]
Hi,
I'm working happily with Slim. :)
But I start to have many routing functions like:

``` php
$app->get('/hello1/:name', function ($name) {
    echo "Hello 1, $name";
});
$app->get('/hello2/:name', function ($name) {
    echo "Hello 2, $name";
});
```

What do you think about a possibility to group all the functions for url like "/hello1/..." in a php file and all functions for url like "/hello2/..." in a other file and load only the necessary functions?

To understand what I mean, I put a example:

``` php
class RoutingMiddleware extends \Slim\Middleware {
    public function call() {
         $app = $this->app;
         $app->hook ( "slim.before.router", function () use($app) {
             $base_url = $app->request ()->getPathInfo ();

             if (strpos ( $base_url, "/hello1" ) === 0) {
                 $app->group ( "/hello1", function () use($app) {
                     require_once __DIR__ . "/hello1.php";
                 }
             }

             if (strpos ( $base_url, "/hello2" ) === 0) {
                 $app->group ( "/hello2", function () use($app) {
                     require_once __DIR__ . "/hello2.php";
                 }
             }
         });
    }
}
```

Something like that, that includes new php functions only if necessary, can be useful to make the application more lightweight? :)

**Comment by wpmvangroesen** [comment]
Hi Hachreak,

You can use class controllers for organizing your routes, see the changelog:

https://github.com/codeguy/Slim/releases/tag/2.4.0 

That way you don't have the bulk of all methods autoloaded.
Adding a route only registers it, so not much overhead there.

For my own use, i have added some abstraction on top of Slim. You could easily add groups to it like your proposal.

**Comment by hachreak** [comment]
Thanks :)
