### ISSUE TITLE
isAjax issue

### ISSUE THREAD

**Issue by tobsn** [slimphp/Slim#92]
public function isAjax() {
        return $this->headers('X_REQUESTED_WITH') === 'XMLHttpRequest';
}

firefox here sends: x-requested-with: XMLHttpRequest
(lowercase)

that was actually not the issue in my case. isAjax is now a function. was a variable before. had to change everything to isAjax() - but i left my fix in the code: 
return ( ( $this->headers('X_REQUESTED_WITH') === 'XMLHttpRequest' ) || ( $this->headers('x_requested_with') === 'XMLHttpRequest' ) );

**Comment by codeguy** [comment]
Thanks for the heads up. Do you think I should convert all headers to lower case automatically? And convert all to underscores or dashes?

**Comment by tobsn** [comment]
not sure, but sounds like a good idea. you know, just for the heck of it to make sure some browsers dont do BS.

**Comment by codeguy** [comment]
Fixed. According to this RFC spec http://www.ietf.org/rfc/rfc2616.txt, HTTP headers may be case insensitive which I did not know. The latest commit to the Develop branch allows for this and resolves this issue. You can request headers in uppercase or lowercase, with dashes or underscores and you will still get the value of the correct header. Internally, header keys are stored in lowercase with dashes.
