### ISSUE TITLE
request->getBody() does not return raw body

### ISSUE THREAD

**Issue by DSpeichert** [slimphp/Slim#923]
```
Use the request object’s getBody() method to fetch the raw HTTP request body sent by the HTTP client. This is particularly useful for Slim application’s that consume JSON or XML requests.
```

I expected to receive raw string, instead I received an object of parsed JSON.

**Comment by ariariari** [comment]
can you post the code?

**Comment by tuupola** [comment]
Are you using [ContentTypes](https://github.com/codeguy/Slim-Middleware/blob/master/src/Slim/Middleware/ContentTypes.php) middleware?

**Comment by DSpeichert** [comment]
@tuupola Yes, I am. That's probably why. I need it most of the time - is there any way to really get a raw body with it?

**Comment by tuupola** [comment]
The idea of ContentType middleware is to automagically turn the body JSON into PHP datastructure. 

_"This is middleware for a Slim application that intercepts the HTTP request body and parses it into the appropriate PHP data structure if possible; else it returns the HTTP request body unchanged. This is particularly useful for preparing the HTTP request body for an XML or JSON API."_

If you want to convert the data structure as back to JSON you could use [json-encode](http://php.net/manual/en/function.json-encode.php) or just not use the middleware.

**Comment by DSpeichert** [comment]
Okay, I guess I just hoped there would be a separate method to still get the really "raw" request body. I need to work with processed body (deserialized json) but at the same time need to run hash verification on the exact raw unmodified body (cannot json_encode it back).
My solution was to simply take `file_get_contents('php://input')`.
