### ISSUE TITLE
Deprecated methods used in framework's source code

### ISSUE THREAD

**Issue by federicojasson** [slimphp/Slim#924]
The framework's source code uses methods that are marked as deprecated.

---

How did I stumble into this? (Just an example of why this can become a problem)

In Slim.php, in the halt method (https://github.com/codeguy/Slim/blob/master/Slim/Slim.php#L1036), the response body is set using response->body instead of response->setBody.

Both functions do the same thing (when response->body is called with a not-null parameter), as you can see here:
https://github.com/codeguy/Slim/blob/master/Slim/Http/Response.php#L202
https://github.com/codeguy/Slim/blob/master/Slim/Http/Response.php#L214

In my app, I coded a class that inherits from the \Slim\Http\Response class, in order to redefine the setBody method.

The problem: when I call app->halt, the response->body method is used, so the redefined method is never invoked.
The (ugly) solution: redefine response->body in order to achieve the goal. This is ugly because it is supposed to be a deprecated method.

---

Reviewing the source code, I see that this issues repeats itself with other methods (e.g. using response->status, instead of response->setStatus).

I'd suggest updating the code so that the deprecated functions aren't used in the framework's source code (leave it available only for backward-compatibility purposes).

**Comment by dgmike** [comment]
:+1:

**Comment by silentworks** [comment]
Thanks for pointing this out, we will get this updated soon.

**Comment by kiswa** [comment]
:+1:

**Comment by codeguy** [comment]
Can someone send a PR to the develop branch?
