### ISSUE TITLE
Fatal Error Status Code

### ISSUE THREAD

**Issue by guilhermecvm** [slimphp/Slim#925]
Hello, I'm trying to upload a file larger then the server can handle, resulting in a fatal error.

[Fatal error] Allowed memory size of 134217728 bytes exhausted (tried to allocate 131596288 bytes)

But instead of a http error response, i'm getting a 200 OK status code.

Environment.php line 166:

``` php
$rawInput = @file_get_contents('php://input');
```

**Comment by geggleto** [comment]
This is a php configuration error not a Slim error.
Your file is larger than the allowable memory for a php process.
