### ISSUE TITLE
Route Group Variables Don't Work

### ISSUE THREAD

**Issue by tusharsoni** [slimphp/Slim#926]
```
$app->group('/foo/:id', function($id) use ($app) {
    $app->get('/bar', function() use ($id) {
        //Cannot use $id here.
    }
}
```

**Comment by tuupola** [comment]
Parameters are passed to route handler not the group. Try something like following.

``` php
$app->group('/foo/:id', function() use ($app) {
    $app->get('/bar', function($id) {
        print $id;
    });
});
```

**Comment by tusharsoni** [comment]
That works. Thanks!

**Comment by gisheri** [comment]
Is there no way to access the parameter inside the group to be used in the group routes?  Like so?

```
$app->group('/contest/:id', function($id) use ($API){
$API->authorize('contest', $id);
$contest = new Contest($id);

$app->get('/settings', function() use ($contest, $API){
    $data = $contest->getSettings();
    $API->output($data);
});

$app->get('/stats', function() use ($contest, $API){
    $data = $contest->getStats();
    $API->output($data);
});
});
```

**Comment by silentworks** [comment]
No as groups are like prefixes, they don't actually exist. We will be working on making the act more like normal routes in the future.

**Comment by gisheri** [comment]
Got it, thanks for the reply!

**Comment by piotr-cz** [comment]
Is such behaviour on the roadmap (ie. `v3.1`)?

@gisheri: Maybe middleware in [Route groups](http://www.slimframework.com/docs/objects/router.html#route-groups) can help you here (actually it may make more sense):

``` php
$request->getAttribute('route')->getArgument('id');
```

Apparently it's possible to use router within the middlewares only with the `determineRouteBeforeAppMiddleware` set to on, but somehow it always works for me.

**Comment by codeguy** [comment]
Sure. I don't see why not so long as it doesn't break bc.

**Comment by piotr-cz** [comment]
Actually I'm not so sure about it anymore.

We shoud evaluate if there are any use-cases when using Group Middleware wouldn't be a better option (given that Router instance may be accessible within Middleware in 3.0 stable).

But some note about it should be in docs for sure, this is so common syntax in other frameworks.

My example:
_I'm using route groups for muliti-language content and within the group I'd like to set the flag of language code. I decided to do it in the middleware, where I'm already loading language strings too._
