### ISSUE TITLE
Route-specific Middleware

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#93]
Implement route-specific, chain-able middleware. Middleware (callable objects) may be registered for a specific route. When a route is executed, middleware is run in the sequence added before the actual route is called. Each middleware will be given a reference to the Request, the Response, and the subsequent middleware callable.

Route-specific middleware will be specified like this:

```
Slim::get('/foo/bar', $middlewareCallable1, $middlewareCallable2, [...], $routeCallable);
```

In this example, the first param is the route pattern. The last param is the callable object to be executed when the route matches an HTTP request. The interior arguments should each be a reference to a callable object that have the following signature:

```
function ($request, $response, $nextMiddleware) {

}
```

Each middleware can perform initialization tasks to affect the Request or Response. Each middleware should also invoke $nextMiddleware to continue the middleware execution chain.

**Comment by tobsn** [comment]
so its chained hooks?

**Comment by codeguy** [comment]
I think so, yes, but they would be passed the Request, Response, and a reference to the subsequent middleware to call so they can choose to call the next one or abort the process.

**Comment by codeguy** [comment]
I'm a ways out from implementing this so feel free to provide suggestions.

**Comment by tobsn** [comment]
well, remember the example i sent you? i guess you could do something like that... with the loaders etc.
