### ISSUE TITLE
Is this repo Still maintain？

### ISSUE THREAD

**Issue by louis-she** [slimphp/Slim#932]
Is it valuable to make patch to it?

**Comment by DavidePastore** [comment]
Yes, it is maintained and you can create patch.

**Comment by silentworks** [comment]
Yes, we are still here and will be picking up pace soon again. Send any PR's related to Slim 2 to master branch and Slim 3 to develop branch.

**Comment by tuupola** [comment]
Should probably update README. It specifically says _"Send a pull request from each feature branch to the **develop** branch."_

**Comment by louis-she** [comment]
I see , but I have review the develop branch source code , it is "totally difference" from the master branch

**Comment by ecoreng** [comment]
The develop branch is going to be Slim 3, which is going to be different internally and have some backward compatibility breaking changes.

**Comment by louis-she** [comment]
Thanks for all the replies
