### ISSUE TITLE
Update to Pimple 3.0 (?)

### ISSUE THREAD

**Issue by ecoreng** [slimphp/Slim#938]
Apparently Pimple 2.\* was just an intermediate temporary bridge between version 1 an 3. There were some updates to the C extension, and the class alias "\Pimple" was removed in favor of "\Pimple\Container".

By updating composer to require Pimple 3 and the App class to extend \Pimple\Container instead of \Pimple we can use the latest version, should I send a PR?

https://github.com/ecoreng/Slim/tree/pimple-3-test

**Comment by prisis** [comment]
If you like, but only for dev branch :)

**Comment by silentworks** [comment]
Yes we will consider this for the release of Slim 3.
