### ISSUE TITLE
Problem with routes and ? . Always 404

### ISSUE THREAD

**Issue by mateosantosdev** [slimphp/Slim#940]
I'm using Apache.

I'm trying to access to: /user/login/facebook?go=go

But I always get a 404 error.

I've tried with these routes:

$app->get('/user/login/facebook?', function(){ 
$app->get('/user/login/facebook/?', function(){ 
$app->get('/user/login/facebook', function(){ 
$app->get('/user/login/facebook/', function(){

My .htaccess
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php?path=$1

Any idea how to solve this ?

Thanks

**Comment by tuupola** [comment]
In your code do you run the Slim app after defining the routes?

```
$app->run();
```

**Comment by prisis** [comment]
Use this
exemple:
get('/books/:one/:two', function ($one, $two) {
    echo "The first parameter is " . $one;
    echo "The second parameter is " . $two;
});

**Comment by mateosantosdev** [comment]
@tuupola yes. My other routes are working fine. The problem is when I append the ?go=go

@prisis that works, but I need to use the ? mark.

**Comment by tuupola** [comment]
Have you tried the rewrite rules suggested by [Slim documentation](http://docs.slimframework.com/#Route-URL-Rewriting)?

```
RewriteEngine On 
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteRule ^ index.php [QSA,L]
```

**Comment by prisis** [comment]
did you try get('facebook:? [or] 'facebook:(?), function..., sorry i cant test it right now...

**Comment by mateosantosdev** [comment]
@tuupola it works! 

I don't know why I was using that .htaccess...
