### ISSUE TITLE
ViewInterface lacking method and view service reference [develop branch]

### ISSUE THREAD

**Issue by ecoreng** [slimphp/Slim#942]
When defining the flash service we are checking if the view object [in the settings] is an instance of the ViewInterface .. and then proceed to call the "set" method
https://github.com/codeguy/Slim/blob/develop/Slim/App.php#L160-L162

but that method is not defined as part of the contract in the interface:
https://github.com/codeguy/Slim/blob/develop/Slim/Interfaces/ViewInterface.php

this is inherited from the Collection class.. but we should not rely on the custom view classes extending that class.

Should I add the method to the Interface?

---

also.. isn't it weird that we are checking  $c['settings']['view'] to see if it is an instance of the interface instead of checking directly through $c['view'].. the problem is going to be more evident if Slim supports Pimple\Container:register(ServiceProviderInterface $provider ...) to register service providers and someone wants to override the default view: $c['settings']['view'] & $c['view'] wont be in sync.

**Comment by silentworks** [comment]
You are indeed correct, can you send a PR with the issues mentioned above please.

**Comment by ecoreng** [comment]
PR Sent.

After reading some more, the second part starts beign a problem after we upgrade to Pimple 3.0 (Pimple 2.0 is not documented now neither in github: https://github.com/silexphp/Pimple nor the website: http://pimple.sensiolabs.org/) and only if we are supporting the ServiceProvider registration (which I personally think is great).

So I already have a way to fix this last part.. but it depends on Slim updating to Pimple 3.0 which I am trying to do here:
https://github.com/codeguy/Slim/pull/939
