### ISSUE TITLE
Slim framework redirecting route wrong

### ISSUE THREAD

**Issue by Mangulomx** [slimphp/Slim#945]
I´m using slim. When I press the event of my anchors onclick

```
<a data-id="{{ empleado['nieempleado'] }}" onclick="showEmployee(this)">{{ empleado['usuario_idusuario'] }} </a>
```

execute the function in javascript

```
var modalBox = $("#box-modal"),
    modalBoxObject = modalBox[0],
    modaltitle = modalBoxObject.getElementsByClassName('modal-title')[0],
    modalContent = modalBoxObject.getElementsByClassName('modal-body')[0],
    modalFooter = modalBoxObject.getElementsByClassName('modal-footer')[0];

function showEmployee(element){
$("#editor-panel").removeClass('hidden'); 
modalBox.modal("show");
modaltitle.innerHTML = "Show employee data"; 
document.location.href = "/empleado/mostrar/"+element.getAttribute('data-id');
}
```

I´ll like go to the route example => 

```
/empleado/mostrar/26237830
```

But the document.location.href go to the route 

```
 GET http://localhost:8080/empleado/mostrar/js/main.js  (NOT FOUND)
```

What´s the trouble. I should use Ajax
![error](https://cloud.githubusercontent.com/assets/5888094/5159692/1ca572ee-736f-11e4-922f-51051289c35d.png)

**Comment by ecoreng** [comment]
I dont think that's related to Slim.
I think that your problem is javascript related.

No creo que sea problema de Slim
Creo que tu problema esta en Javascript

**Comment by Mangulomx** [comment]
thanks I solved it
