### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by knifesk** [slimphp/Slim#954]
Apparently website is down and I need to read the docs.. can someone check it?? Seems to be a DNS issue :(

**Comment by prisis** [comment]
Nope, still working.

**Comment by knifesk** [comment]
Fuck my ISP... yes.. switched to google's DNS and I can access the site just fine... Sorry for the bother guys!

**Comment by knifesk** [comment]
Nope, still cant access the docs.. not even with a proxy :(

I CAN access the website (www) but not the Documentation (docs.slim....)

**Comment by prisis** [comment]
try this https://www.proxysite.com/process.php/jtWQpjY3J1S_2BXV0z2go_2B4wOif53VZqVE5YY_3D/b7/fnorefer/

**Comment by knifesk** [comment]
TY Daniel, that one is working...

**Comment by prisis** [comment]
np.

**Comment by tuupola** [comment]
http://www.downforeveryoneorjustme.com/http://docs.slimframework.com

**Comment by silentworks** [comment]
Its a namecheap DNS issue, its currently working for me.

**Comment by knifesk** [comment]
Yeah, for me too now... Glad it worked fine
