### ISSUE TITLE
Docs Repository?

### ISSUE THREAD

**Issue by jordanwallwork** [slimphp/Slim#955]
Is there a repository for the docs website? I've been reading through the docs and have to keep going back to the top of the page to view the nav - I know there are 'back to top' buttons every now and then but it seems to me that the navigation is crying out for the [affix plugin](http://getbootstrap.com/javascript/#affix).

If there's a repo then I'm happy to make the change myself

**Comment by silentworks** [comment]
The docs are here https://github.com/codeguy/Slim-Documentation

**Comment by jordanwallwork** [comment]
Oh of course, cheers
