### ISSUE TITLE
Create API Documentation

### ISSUE THREAD

**Issue by ThePokyWizard** [slimphp/Slim#957]
Hi, i use Slim do create a REST API. How is possible create a documentation of methods?

**Comment by tuupola** [comment]
https://www.google.com/search?q=document+rest+api

**Comment by cdtweb** [comment]
^ LOL

**Comment by ThePokyWizard** [comment]
Is almost Let Me Google for You lmgtfy.com

**Comment by codeguy** [comment]
http://swagger.io/ is a popular option
