### ISSUE TITLE
Support for namespaces

### ISSUE THREAD

**Issue by sgalonska** [slimphp/Slim#96]
I noticed that Slim does not support namespaces at all, but it could help significantly with loading classes. I am willing to implement it if required by others

**Comment by codeguy** [comment]
Namespaces require PHP >= 5.3 and are not backwards compatible. This is why I have chosen not to implement namespaces; I want Slim to work with PHP 5.1 or newer. You're more than welcome to fork Slim and implement namespaces for your own project though.
