### ISSUE TITLE
Request::getIP() may not return the correct result when the user uses multiple proxies

### ISSUE THREAD

**Issue by brian978** [slimphp/Slim#960]
If the user uses more than 1 proxy to connect to an application then the getIP() method might not return the correct result. Now, I haven't found much information on the HTTP_CLIENT_IP header, but, the HTTP_X_FORWARDED_FOR / X_FORWARDED_FOR header may not contain a single IP address but a list IPs separated by commas. 

Considering this, the getIP() method should return only 1 IP from that list (theoretically the first one, in practice it can be either one, since that header can be spoofed).

I can send a pull request with the changes, if we agree that the behavior should be changed.

**Comment by tassoevan** [comment]
:+1:

**Comment by GeeH** [comment]
I think that @weierophinney has a library that fixes this

**Comment by codeguy** [comment]
Link?
