### ISSUE TITLE
Logwriter breaks when using static function as variable in other function

### ISSUE THREAD

**Issue by Miesvanderlippe** [slimphp/Slim#961]
What I did : 
$response->bindParam(1, Crypt::RandomString(16));

What happened : 
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Cannot create LogWriter. Invalid resource handle.'

What fixed it : 
$publicKey = Crypt::RandomString(16);
$response->bindParam(1, $publicKey);

Full error : 
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Cannot create LogWriter. Invalid resource handle.' in C:\Users\miesvanderlippe\Documents\School\meol1\Slim\LogWriter.php:60 Stack trace: #0 C:\Users\miesvanderlippe\Documents\School\meol1\Slim\Slim.php(191): Slim\LogWriter->__construct(false) #1 C:\Users\miesvanderlippe\Documents\School\meol1\Slim\Helper\Set.php(228): Slim\Slim->Slim{closure}(Object(Slim\Helper\Set)) #2 C:\Users\miesvanderlippe\Documents\School\meol1\Slim\Helper\Set.php(88): Slim\Helper\Set->Slim\Helper{closure}(Object(Slim\Helper\Set)) #3 C:\Users\miesvanderlippe\Documents\School\meol1\Slim\Helper\Set.php(185): Slim\Helper\Set->get('logWriter') #4 C:\Users\miesvanderlippe\Documents\School\meol1\Slim\Slim.php(196): Slim\Helper\Set->offsetGet('logWriter') #5 C:\Users\miesvanderlippe\Documents\School\meol1\Slim\Helper\Set.php(228): Slim\Slim->Slim{closure}(Object(Slim\Helper\Set)) #6 C:\Users\miesvanderlippe\Documents\School\meol1\Slim\Helper\Set.php(88): Slim\Helper\Set->Slim\Helpe in C:\Users\miesvanderlippe\Documents\School\meol1\Slim\LogWriter.php on line 60

**Comment by Miesvanderlippe** [comment]
Same error just after trying to print an array with print();

My logwriter might be bust or something but I didn't change anything about it.

**Comment by tassoevan** [comment]
The pasted code is using PDO, right? Nothing related to Slim (you're using `bindParam` instead of `bindValue`). However, any error in your application is generating an additional exception because your LogWriter is broken. How are you defining the `log.writer` parameter in Slim configuration?

**Comment by silentworks** [comment]
This is not a framework related issue, I will be closing this out. If you wish to continue discussion on this please move it over to http://help.slimframework.com/

**Comment by honeygoyal** [comment]
Did anyone find solution to this problem? https://stackoverflow.com/questions/32473070/slim-framework-fatal-error-uncaught-exception-invalidargumentexception-with-m
I got this answer on stackOverflow but it didn't help! why this error occurs? since I made no changed to my logwriter.

**Comment by tassoevan** [comment]
@honeygoyal Can you check if, before the `$app->run();` line in your `index.php`, the following line throw an error?

```php
fopen('php://stderr', 'w');
```
