### ISSUE TITLE
Routing doesn't work if there are any query parameters or even "?" character in the URL

### ISSUE THREAD

**Issue by german-chosen** [slimphp/Slim#963]
http://mywebsite.com/somepage - Works
http://mywebsite.com/somepage? - Doesn't work
http://mywebsite.com/somepage?param1=val1  - Doesn't work

_Update:_

It seems that adding the following fix for App Engine causes this problem on both local and App Engine environments.

// Google App Engine doesn't set $_SERVER['PATH_INFO']
$app->environment['PATH_INFO'] = $_SERVER['REQUEST_URI'];

_Update:_

Found a way by removing the query string part like this. Solved my problem:

$app->environment['PATH_INFO'] = rtrim(strtok($_SERVER['REQUEST_URI'], '?'), '/');

**Comment by codeguy** [comment]
Which branch does this affect?

**Comment by german-chosen** [comment]
Latest version using composer:

"slim/slim": "2.*"

**Comment by tassoevan** [comment]
`$_SERVER["PATH_INFO"]` variable doesn't includes the query string part of URL, while `$_SERVER["REQUEST_URI"]` does. Actually Slim doesn't use `$_SERVER["PATH_INFO"]` to compute `$app->environment["PATH_INFO"]` (and I think it never used this). The awkward variable can be `$_SERVER["REQUEST_URI"]`.
