### ISSUE TITLE
Bug with notFound()

### ISSUE THREAD

**Issue by samlevin** [slimphp/Slim#965]
Hello! Loving Slim framework. However, I found something in the framework which really ought to be classified as a bug and reworked.

There are two primary ways one would use the Slim framework. One would be for server-side MVC (using PHP templates), where Slim does all of the view/controller helping. In this instance, a 404 error would refer to an HTTP 404 - Page Not Found status.

The second way, which I believe Slim is the perfect framework for, is creating a distributed, stateless REST API. In this case, 404 takes on a different meaning. A 404 from a rest API is indicative that a resource does not exist (I.e. object not found). Moreover, if a URI is not found, a HTTP 400 - Bad Request status would be more appropriate for this.

Unfortunately, Slim's 'notFound()' handler pigeonholes users into return a HTTP 404 status, due to the halt() call invoked after notFound() executes a callable.

This causes two problems:
1) Forced to misuse HTTP404 when using Slim to create a REST API
2) We are forced to use halt() in order to send responses with proper HTTP status codes, which means that we miss out on the slim.after.dispatch hook (as halt invokes stop).

In my opinion, the best way to handle this is to simply let the user set the request status in the notFound() handler, and to drop the halt() command. Let this request run out like it normally would, unless a custom notFound callable is never set - in this case, run the default, and then drop the 404 halt.

Right now, I've simply commented out line 602 of notFound(). This simply allows the OB to get my input like it would on a normal route, and I set the response status myself. However, if you are to patch this, I do believe that the default Slim notFound handler should send a 404 halt! Only skip the halt if a custom handler is set.

Hope this helps,
Sam

**Comment by tassoevan** [comment]
I've seen some discussions around this "400 or 404" subject. The [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5) states for 404:

> The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent. [...] This status code is commonly used when the server does not wish to reveal exactly why the request has been refused, or when no other response is applicable.

I don't think that 404 is a good status to represent that desired resource doesn't exist because is too generic to say what is wrong with the request URI. Some API developers are [using 422 status](http://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm).

Regardless this issue, `Slim\Slim::notFound()` is not handled like a route; sometimes is annoying.

**Comment by samlevin** [comment]
Thanks for the feedback and perspective. Either way, being pigeonholed into 404 for notFound isn't ideal, and the fix is simple. Glad to see some traction on this. Hope the devs see it. 

Best,

Sam Levin

**Comment by silentworks** [comment]
I have seen others mention this issue before and we will definitely look into it, in one comment by @tuupola he suggest having sinatra like error handlers. https://github.com/codeguy/Slim/issues/881#issuecomment-53032739

**Comment by codeguy** [comment]
Resolved in develop branch.

**Comment by samlevin** [comment]
How was this resolved? Can I get some details? I feel like I looked around but didn't see the fix.
