### ISSUE TITLE
Expected behaviour of $app->response->setBody()

### ISSUE THREAD

**Issue by shaundodimead** [slimphp/Slim#969]
Hi,

Not sure if I'm misunderstanding what _setBody_ is supposed to do, but consider

```
<?php
require 'vendor/autoload.php';
$app = new \Slim\Slim();
$app->get('/setbodyprob', function () { print 'foo'; });        
$app->response->setBody('bar');
$app->run();
?>
```

I imagined that in this situation, any output whatsoever would be replaced with 'bar' (this is what i'm trying to achieve). What I get when bringing up /setbodyprob is

```
 barfoo
```

instead of

```
bar
```

I can see the code in Http/Response.php looking like it's trying to do this, but I'm not sure of the rest of the processing path.

What's the expected behaviour? 

Really enjoying using Slim, really quick to get good code up and running!

Shaun

**Comment by shaundodimead** [comment]
Thinking further, I wondered if perhaps the run() which calls the callbacks then starts writing to the end of the output (i.e. setbody,then the function). How about this? 

```
<?php
require 'vendor/autoload.php';
global $app;
$app = new \Slim\Slim();
$app->get('/setbodyprob', function () { 
    global $app;
    print 'foo'; 
    $app->response->setBody('bar');
});        
$app->run();        
?>
```

Output is the same tho, 'barfoo'

**Comment by tuupola** [comment]
From Slim documentation.

_Whenever you echo() content inside a route’s callback function, the echo()’d content is captured in an output buffer and **appended** to the response body before the HTTP response is returned to the client._

According to above `barfoo` is expected behaviour.

In your first example all possible routes get a default response of `bar`. When `GET /setbodyprob` is requested `foo`gets appended to it.

In second example you write `foo` to output buffer. Then response is set to `bar`. After callback finishes the output buffer is appended to response and it becomes `barfoo`.

**Comment by shaundodimead** [comment]
Thanks Mike,

I don't know why I didn't see that in the documentation, it is clearly there. It does also say:

_The HTTP response returned to the client will have a body. The HTTP body is the actual content of the HTTP response delivered to the client. You can use the Slim application’s response object to set the HTTP response’s body:_

I wonder then, what's the point of the Response->SetBody() if it doesn't actually set the body response, it sets part of it. My challenge is my service is calling code which is shared and generates output I don't want.

I guess I'll get the output generation factored out of the shared code (which it probably should be anyway)

Shaun

**Comment by tuupola** [comment]
Actually `$app->response->setBody('bar')` does set the body response as advertised. However as the if you also `print()` or `echo()` something in the route handler it will be appended to the body. I agree this is a bit counterintuitive. However as the docs say you are usually not supposed to use `setBody()` directly.
