### ISSUE TITLE
[develop] Request object

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#970]
I'm finding that the current code doesn't work consistently, but if I change line `949` to

``` php
$physicalPath = rtrim($physicalPath, '/'); // <-- Remove trailing slashes
```

then `getScriptName` returns the script name and not an empty string (script name being `index.php`)

Is that right?

**Comment by codeguy** [comment]
@designermonkey Is this still relevant?

**Comment by designermonkey** [comment]
I don't know I'm afraid. Been out of the loop best part of a year :(

Going to close it until I can test development for you again at a (hopefully not too) later date.
