### ISSUE TITLE
Mixed return types from getCookie()

### ISSUE THREAD

**Issue by nochso** [slimphp/Slim#972]
The doc comment for getCookie() says
`* @return string|null`

If encryption is disabled, this will return null thanks to `$value = $this->request->cookies->get($name);`

However with encryption enabled `$value = \Slim\Http\Util::decodeSecureCookie` will make getCookie() return false when the decryption of the cookie has failed.

I suggest that in this case getCookie() should also return null.

**Comment by krydos** [comment]
I changed return value to null. Tests are passed. 

It seems like cosmetic change but anyway, I hope it will allow me to start to contribute more into this framework :)

**Comment by nochso** [comment]
Thank you. It may feel cosmetic, but something not working properly because of the implementation differing from documentation is either a bug or improper documentation :)
