### ISSUE TITLE
pcre 8.34+

### ISSUE THREAD

**Issue by craveica** [slimphp/Slim#976]
In recent pcre (8.34+) group names starting with digits are no longer allowed.

exception 'ErrorException' with message 'preg_match(): Compilation failed: group name must start with a non-digit at offset 39' in Slim/Route.php:387

**Comment by codeguy** [comment]
Do you want to submit a PR to the develop branch?

**Comment by craveica** [comment]
That's an easy fix, replacing line 380 in Route.php:

diff Route.php.old Route.php.new

```
380c380
<             str_replace(')', ')?', (string)$this->pattern)
---
>             str_replace(')', ')?', strtr((string)$this->pattern, '0123456789', 'abcdefghij'))
```
