### ISSUE TITLE
Class Controllers, add option for dependency injection using __construct()

### ISSUE THREAD

**Issue by dac514** [slimphp/Slim#977]
Hi.

Class Controllers feature as described in 2.4.0 release notes:

_$app->get('/hello/:name', '\Greeting:sayHello'); will instantiate class \Greeting and pass the value "Josh" into its sayHello method._

I would like to see this improved so that Dependency Injection using `__construct` could be satisfied.

Example:

```
$app->get('/hello/:name', '\Greeting:sayHello', [$appInterface, $cachePoolInterface, $adapterInterface]); 
```

Third param is an array that gets passed into to `\Greeting::__construct($app, $cache, $adapter)`

Thank you for your consideration.

**Comment by silentworks** [comment]
This is a good suggestion but wouldn't this mean that if I am calling a different method on the Greeting Class wouldn't this mean passing in the params again since its the constructor.

Here is an proposed alternative which I am still waiting on @codeguy to review https://github.com/codeguy/Slim/pull/822, it would solve you issue and the one I mentioned.

If you do not need to pass the params into the `__construct` method, you can pass the dependencies directly to the method instead using `setParams()`.

``` php
$app->get('/hello/:name', '\Greeting:sayHello')->setParams([$appInterface, $cachePoolInterface, $adapterInterface]);
```

The dependencies would be injected into the sayHello method. `\Greeting::setHello($app, $cache, $adapter)`

**Comment by dac514** [comment]
@silentworks Dependency Injection through setters is good enough for me. Either solution is fine. Hope your #822 gets approved. Cheers!

**Comment by zulrang** [comment]
Why aren't you using the new Resource Locator for this?

```
$app->container->singleton('db', function () {
    return new PDO('sqlite:database.db');
});

$app->get('/hello/:name', '\Greeting:sayHello');

class Greeting {
    public function __construct() {
        $this->app = Slim::getInstance();
    }

    public function sayHello($name) {
        $pdo = $this->app->db;
    }
}
```

**Comment by dac514** [comment]
Hi @zulrang 

Because that's not [dependency injection](http://en.wikipedia.org/wiki/Dependency_injection), that's a [Singleton](http://en.wikipedia.org/wiki/Singleton_pattern)?

I'm using [Pimple](https://github.com/silexphp/Pimple) as my "Service Locator," it still does not help. Dependency injection as a feature request, in my case, is specifically for [writing testable code](http://coderoncode.com/2014/01/06/dependency-injection-php.html). In your example, you are hardcoding  classes in both the constructor and the sayHello method, which goes against the principle of Dependency Injection altogether...

Thanks!

**Comment by zulrang** [comment]
The Singleton was just an example in using the Resource Locator.

Is it the explicit dependency "contract" you're trying to achieve?  

Using a service locator is still just as testable:
`$mockContainer['dependency'] = $mockObject`

Sorry if my questions sound silly.   I'm still trying to learn some of the better practices of using Slim.

**Comment by dac514** [comment]
Hi @zulrang 

You are right in that, with a service locator, I can swap objects with Mocks. I already do it with Pimple. It's great.

It's more of a pattern issue. My feature request is to do it another way, more standard to the design pattern itself.

Cheers.

**Comment by zulrang** [comment]
As opposed to the "anti-pattern."  Got it.  Carry on.

**Comment by danielgsims** [comment]
The goal with #822 is so that you can decide what gets injected into your controller. All you have to do is set a config variable. The first option is to load controllers as they do right now, with nothing injected in the controller. The second option is to pass the Slim DI Container into the constructor like @zulrang suggested, but it's injected instead of you having to use the getInstance method. This makes it easier to debug. The third option is to load objects from your DI Container directly. There are some examples with the PR, and I'd appreciate any feedback. Thanks guys.

**Comment by zulrang** [comment]
My personal preference is to inject the container into the constructor, but
leave the option to use your own container (Pimple, etc.) More flexibility
and test-ability.

**Comment by eko3alpha** [comment]
I would also like to see this implemented.

I am using class based routing and not able to inject dependencies let alone an IOC container.  My current solution is to create a BaseController that will provide the dependencies needed in the controllers.

BaseController.php

```
class BaseController 
{
    protected $dependency1;
    protected $dependency2;

    public function __construct()
    {
           $this->dependency1 = new Dependency1;
           $this->dependency1->initConfig(Config::get('some_config1'););

           $this->dependency2 = new Dependency2;
           $this->dependency2->initConfig(Config::get('some_config2'););
    }
}
```

MyController.php

```
class MyController extends BaseController
{
    public function myMethod($param1)
    {
        $result = $this->dependency1->doSomething($param1);
    }
}
```

}

routes.php

```
$app->get('/get-r-dun/:param1/', 'MyController:myMethod');
```

BaseController instantiates my dependencies.  Unfortunately I have no way to access my config values unless I use a registry pattern. 

Config::get('db_host');

The other solution which I don't like is to make the BaseControllers constructor mount $app.

BaseController

```
class BaseController 
{
    protected $app;
    public function __construct()
    {
          global $app;  // I HATE this idea  >:(
           $this->app = $app;
    }
}
```

This is my least favorite of the 2.  Id love to be able to inject dependencies, or heck even an IOC.  Any news on this?

**Comment by akrabat** [comment]
This is being addressed in Slim 3 where you'll be able to register your class with the Pimple DI container which will allow you to instantiate the class however you wish.

**Comment by eko3alpha** [comment]
Excellent! Thanks for the heads up!
Any Idea when Slim 3 will be ready?
