### ISSUE TITLE
Problem with IIS decoding URLs in advance

### ISSUE THREAD

**Issue by oniric85** [slimphp/Slim#978]
Hi,
I'm using Slim Framework on an IIS 7.5 enviroment. I've noticed a quite picky problem when using specific characters in the URL. I have a URL string parameter that can contain the "plus" sign. I usually encode it as %2B and get URLS like

/test/url/foo%2B

The problem is that IIS url decode the URL and set it in REQUEST_URI server server variable while other webservers like Apache does not. So when Slim try to parse the parameters in the request URL it find the parameter value to be "foo+" and it applies the urldecode function to it, getting "foo " with the space, obviously not the wanted value.

The problem is quite specific to the "plus" character I think.

**Comment by brandisher** [comment]
FWIW, the most correct solution would be to disable the URL decoding done by IIS (if possible) if you're running across multiple web servers.  However, and I don't know if this is advisable, but you may be able to add a callable to the slim.before hook to re-encode the URL before Slim does it's processing.

**Comment by oniric85** [comment]
As a temporary solution I've added this piece of code before the Slim app initialization code:

``` php
// Patch for IIS handling of URL encoding
function on_iis() {
    $sSoftware = strtolower($_SERVER["SERVER_SOFTWARE"]);
    if (strpos($sSoftware, "microsoft-iis") !== false) {
        return true;
    } else {
        return false;
    }
}

if (on_iis()) {
    $_SERVER['REQUEST_URI'] = $_SERVER['UNENCODED_URL'];
}
```

It seems to get the job done though not very elegant.

**Comment by brandisher** [comment]
I can't say that I've seen a problem like this before so perhaps a unique problem requires a unique solution!  Glad you've figured it out!
