### ISSUE TITLE
isAjax change for jquery form plugin file upload

### ISSUE THREAD

**Issue by tobsn** [slimphp/Slim#98]
Http/Request.php:
    public function isAjax() {
        return ( $this->params( 'isajax' ) || ( $this->headers('X_REQUESTED_WITH') === 'XMLHttpRequest' ) || ( $this->headers('x_requested_with') === 'XMLHttpRequest' ) );
    }

because ajax cant handle file upload the jquery form plugin routes over an iframe therefore the header is missing. maybe thats something to discuss.

**Comment by codeguy** [comment]
I like your solution. Simple. Allows manual AJAX detection by passing a parameter with the request. I'll consider that the solution unless anyone else has further suggestions. Will implement shortly unless you want to send a pull request.

**Comment by codeguy** [comment]
Done. Updating docs now.

**Comment by tobsn** [comment]
haha, nice :D

(btw. you couldve put in the lowercase version too in the hotfix)
