### ISSUE TITLE
`setCookie()` does not work with `exit()`

### ISSUE THREAD

**Issue by shanehou** [slimphp/Slim#980]
I use an ajax call to login, and the function that ajax call request is:

```
function loginAdmin() {
    $app = \Slim\Slim::getInstance();
    if (auth()) {
        $app->setCookie('admin', TRUE);
        exit(TRUE);
    }
    exit(NULL);
}
```

Cookies will not be set unless I remove `exit(TRUE)`.

Here I need to exit with an value to indicate the client if the auth was successful.

**Comment by dvikan** [comment]
```
$app->halt(403, 'You shall not pass!');
```

**Comment by shanehou** [comment]
But here I just want to give a response to the ajax call, not refusing.

**Comment by tuupola** [comment]
You cannot use `exit()` for sending response. Instead you should `print` or `echo` the response from the route.

**Comment by shanehou** [comment]
But other route functions are fine with exit. Is it not necessary that I stop the script executing? exit() is actually echo then exit.

**Comment by ICanKittens** [comment]
@shanehou exit terminates the execution at that very point, so the framework can not send out the headers, which also contain the Cookie information you are settings.

To get around this you can do `$app->halt(200);` which for the client will have the same "meaning".

**Comment by codeguy** [comment]
What @Stelian said.
