### ISSUE TITLE
Trailing slash not working inside of a group

### ISSUE THREAD

**Issue by rbalik** [slimphp/Slim#984]
Defining my route like this:

```
$app->map('/test', function () use ($app) {
        $t = new \TestController();
        $t->test($app);
    })->via('GET', 'POST')->name('test');
});
```

Requesting /test?asdf=asdf works fine
Requesting /test/?asdf=asdf results in a 404.

I found a hint online that changing the route definition to '/test/?' fixes it and that does work for me, but it seems like this is a bug in Slim

**Comment by rbalik** [comment]
Was looking into this more and I think the problem isn't related to the parameters at all. The issue is that /test/ doesn't work at all.
This may be related to it being inside of a group so really it's /1/test and /1/test/

**Comment by brandisher** [comment]
What version of Slim are you using?

Also, looks like you've got a typo in the code.  I assume it should be like this?

```
$app->map('/test', function () use ($app) {
        $t = new \TestController();
        $t->test($app);
})->via('GET', 'POST')->name('test');
```

I tested on 2.4.2 and if you define the route as '/test/', both of the following renditions work:
/test?q=1234
/test/?q=1234

**Comment by rbalik** [comment]
Hmm, I'm using composer to get '2.*', looks like I'm on 2.5 so maybe this is a regression.
That typo was left over from the group.

Here's an exact snippet that reproduces the problem:

```
<?php

require('vendor/autoload.php');

$app = new \Slim\Slim();

$app->group('/1', function() use ($app) {
    $app->map('/test', function () use ($app) {
        echo('testing');
    })->via('GET', 'POST')->name('test');
});

$app->run();

?>
```

**Comment by rbalik** [comment]
With that code, requesting /1/test works but /1/test/ returns a 404.

**Comment by rbalik** [comment]
Oh, I see that you said I should define it as '/test/' and that does work for me. I guess I've been doing it wrong. I'll make that change. Thanks for your help.
