### ISSUE TITLE
Multiple flash messages

### ISSUE THREAD

**Issue by thejw23** [slimphp/Slim#985]
Right now flash messages (of the same type, ie. 'error') are strored in single array key:

```
 $this->messages['next'][(string) $key] = $value;
```

If we store them in separate array items, like:

```
 $this->messages['next'][(string) $key][] = $value;
```

Tthis would allow us to have few messages of the same type - currently only last one is shown to user. Wouldn't it be nice?

**Comment by krydos** [comment]
I think it will break API of how we can get these messages.
Actually you can pass array in your flash message and then you can use this message as multiple values message.

``` php
$this->messages['next'][(string) $key] = $value;
```

Here your $value variable can be array with multiple messages. 

**I think nothing should be changed.**
