### ISSUE TITLE
Not able to get app Instance?

### ISSUE THREAD

**Issue by inkrement** [slimphp/Slim#988]
I try to decouple my dependencies so I created a AuthService

```
<?php namespace Service;
use Slim\Slim;

class AuthService {
    public static function login( \User $user){
        $app = Slim:getInstance(); //FIXME: app is Null
        $app->setEncryptedCookie('role', $user->getRole());
        $app->setEncryptedCookie('userid', $user->getId());
    }
//...
```

But when I call `AuthService::login(...)` within a route, `getInstance()` returns Null. How can I access Slims Cookie functions in a static context? And why is a Null-Pointer returned?

**Comment by brandisher** [comment]
You have a typo.  `$app = Slim:getInstance();` should be `$app = Slim::getInstance();`.
